

CREATE FUNCTION dbo.ALDCLIFOR (@CLIFOR varchar(7))  
RETURNS VARCHAR(7) AS  
BEGIN 
	DECLARE @TIPO VARCHAR(1)
	DECLARE @CODICE VARCHAR(6)
	DECLARE @RISULTATO VARCHAR(7)

	SET @TIPO = LEFT(@CLIFOR,1)
	SET @CODICE = RTRIM(LTRIM(SUBSTRING(@CLIFOR,2,6)))
	SET @RISULTATO=@TIPO + @CODICE
	RETURN @RISULTATO
END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[ALDCLIFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALDCLIFOR] TO [Metodo98]
    AS [dbo];

