CREATE FUNCTION [dbo].[AldCalcGGLAVCalendario](@DATAINI DATETIME, @DATAFIN DATETIME)  
RETURNS NUMERIC(19,4) 
BEGIN 
	/*	@RET_ggCalc	 = numero gg lavorativi calcolati */	
	DECLARE @RET_ggCalc AS NUMERIC(19,4)

	/*	@DATAINI	 = data inizio intervallo da cui estrarrre anno mese giorno */	
	DECLARE @ANNOINI CHAR(4)
	DECLARE @MESEINI CHAR(2)
	DECLARE @GIORNOINI CHAR(2)

	SET @ANNOINI=CAST(YEAR(@DATAINI) AS CHAR(4))
	SET @MESEINI=CAST(MONTH(@DATAINI) AS CHAR(2))
	SET @GIORNOINI=CAST(DAY(@DATAINI) AS CHAR(2))

	SET @ANNOINI=RIGHT(RTRIM('0000'+@ANNOINI),4)
	SET @MESEINI=RIGHT(RTRIM('00'+@MESEINI),2)
	SET @GIORNOINI=RIGHT(RTRIM('00'+@GIORNOINI),2)

	/*	@DATAFIN	 = data fine intervallo da cui estrarrre anno mese giorno */	
	DECLARE @ANNOFIN CHAR(4)
	DECLARE @MESEFIN CHAR(2)
	DECLARE @GIORNOFIN CHAR(2)

	SET @ANNOFIN=CAST(YEAR(@DATAFIN) AS CHAR(4))
	SET @MESEFIN=CAST(MONTH(@DATAFIN) AS CHAR(2))
	SET @GIORNOFIN=CAST(DAY(@DATAFIN) AS CHAR(2))

	SET @ANNOFIN=RIGHT(RTRIM('0000'+@ANNOFIN),4)
	SET @MESEFIN=RIGHT(RTRIM('00'+@MESEFIN),2)
	SET @GIORNOFIN=RIGHT(RTRIM('00'+@GIORNOFIN),2)

	BEGIN
		SET @RET_ggCalc=(select count(GIORNOCAL) from CALPRODUZIONE where (CAST(RIGHT(RTRIM('0000'+ANNOCAL),4)+RIGHT('00'+CAST(MESECAL AS VARCHAR(2)),2)+RIGHT(RTRIM('00'+cast(GIORNOCAL as varchar(2))),2) AS VARCHAR(8)) >=@ANNOINI+@MESEINI+@GIORNOINI AND CAST(RIGHT(RTRIM('0000'+ANNOCAL),4)+RIGHT('00'+CAST(MESECAL AS VARCHAR(2)),2)+RIGHT(RTRIM('00'+cast(GIORNOCAL as varchar(2))),2) AS VARCHAR(8))<=@ANNOFIN+@MESEFIN+@GIORNOFIN) and festivo=0)
	END
	RETURN @RET_ggCalc
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[AldCalcGGLAVCalendario] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AldCalcGGLAVCalendario] TO [Metodo98]
    AS [dbo];

