CREATE FUNCTION ECF_RifCommCli(@pRIFCOMM VARCHAR(30)) RETURNS SMALLINT
AS
BEGIN
	DECLARE @ESISTECOMM SMALLINT
	DECLARE @RIFCOMM VARCHAR(30)
	DECLARE CUR_COMM CURSOR FAST_FORWARD READ_ONLY FOR SELECT RIFCOMM FROM ANAGRAFICACOMMESSE WHERE RIFCOMM=@pRIFCOMM

	SET @ESISTECOMM=0
	OPEN CUR_COMM
	FETCH CUR_COMM INTO @RIFCOMM
	IF @@FETCH_STATUS = 0 SET @ESISTECOMM=1
	CLOSE CUR_COMM
	DEALLOCATE CUR_COMM
	
	RETURN @ESISTECOMM
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[ECF_RifCommCli] TO [Metodo98]
    AS [dbo];

