
                           
CREATE FUNCTION [dbo].[FunGIACENZAFINALEARTICOLO](@Esercizio DECIMAL(5,0),
                                                   @ARTICOLO nVARCHAR(50))

RETURNS @Results TABLE (CODART nVARCHAR(50),
             CODDEPOSITO nVARCHAR(10),
              GIACENZA NUMERIC(16,6),
               DISPONIBILITA NUMERIC(16,6),
                ORDINATO NUMERIC(16,6),
                 IMPEGNATO NUMERIC(16,6),
                  CARICO NUMERIC(16,6),
                   SCARICO NUMERIC(16,6),
                    RESODACARICO NUMERIC(16,6),
                     RESODASCARICO NUMERIC(16,6),
                      UM nVARCHAR(3))

AS

BEGIN


DECLARE @GIACENZAINIZIALE TABLE (CODART nVARCHAR(50),
                 CODDEPOSITO nVARCHAR(10),
                  GIACENZA NUMERIC(16,6),
                   DISPONIBILITA NUMERIC(16,6),
                    ORDINATO NUMERIC(16,6),
                     IMPEGNATO NUMERIC(16,6),
                      CARICO NUMERIC(16,6),
                       SCARICO NUMERIC(16,6),
                        RESODACARICO NUMERIC(16,6),
                         RESODASCARICO NUMERIC(16,6),
                          UM nVARCHAR(3))

DECLARE @GIACENZA TABLE (CODART nVARCHAR(50),
             CODDEPOSITO nVARCHAR(10),
              GIACENZA NUMERIC(16,6),
               DISPONIBILITA NUMERIC(16,6),
                ORDINATO NUMERIC(16,6),
                     IMPEGNATO NUMERIC(16,6),
                  CARICO NUMERIC(16,6),
                   SCARICO NUMERIC(16,6),
                    RESODACARICO NUMERIC(16,6),
                     RESODASCARICO NUMERIC(16,6),
                          UM nVARCHAR(3))

DECLARE @CODART     nVARCHAR(50)
DECLARE @CODDEPOSITO    nVARCHAR(10)
DECLARE @UM         nVARCHAR(3)
DECLARE @GIACENZAINT    NUMERIC(16,6)
DECLARE @DISPONIBILITA  NUMERIC(16,6)
DECLARE @ORDINATO   NUMERIC(16,6)
DECLARE @IMPEGNATO  NUMERIC(16,6)
DECLARE @CARICO     NUMERIC(16,6)
DECLARE @SCARICO    NUMERIC(16,6)
DECLARE @RESODACARICO   NUMERIC(16,6)
DECLARE @RESODASCARICO  NUMERIC(16,6)

    INSERT INTO @GIACENZAINIZIALE
    SELECT  CODART,
        CODDEPOSITO,
        SUM(GIACENZAINIZIALE) AS GIACENZA,
        (SUM(GIACENZAINIZIALE) + SUM(ORDINATO) - SUM(IMPEGNATO)) AS DISPONIBILITA,
        SUM(ORDINATO) AS ORDINATO,
        SUM(IMPEGNATO) AS IMPEGNATO,
        SUM(CARICO) AS CARICO,
        SUM(SCARICO) AS SCARICO,
        SUM(RESODACARICO) AS RESODACARICO,
        SUM(RESODASCARICO) AS RESODASCARICO,
        UM
    FROM
    (
        SELECT  CODART,
            CODDEPOSITO,
            (CARICO - SCARICO - RESODACARICO + RESODASCARICO) AS GIACENZAINIZIALE,
            ORDINATO,
            IMPEGNATO,
            CARICO,
            SCARICO,
            RESODACARICO,
            RESODASCARICO,
            UM
        FROM
        (
        SELECT  STMAG.CODART,
            STMAG.CODDEPOSITO,
            SUM((STMAG.QTA1UM*STMAG.ORDINATO)) AS ORDINATO,
            SUM((STMAG.QTA1UM*STMAG.IMPEGNATO)) AS IMPEGNATO,
            SUM((CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END)) AS CARICO,
            SUM((CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END)) AS SCARICO,
            SUM((CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END)) AS RESODACARICO,
            SUM((CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END)) AS RESODASCARICO,
            AUM.UM
        FROM STORICOMAG AS STMAG 
        INNER JOIN TABVINCOLIGIC AS TVG 
            ON STMAG.ESERCIZIO=TVG.ESERCIZIO
        INNER JOIN ANAGRAFICAARTICOLI ART 
            ON ART.CODICE=STMAG.CODART
        INNER JOIN ARTICOLIUMPREFERITE AUM 
            ON AUM.CODART=STMAG.CODART AND AUM.TIPOUM=1
        WHERE   STMAG.CODART=@ARTICOLO AND 
            STMAG.CODDEPOSITO IN (SELECT CODICE FROM ANAGRAFICADEPOSITI WHERE DISPONIBILE = 1) 
            AND STMAG.Esercizio <> @Esercizio
        GROUP BY STMAG.CODART,
             STMAG.CODDEPOSITO,
             AUM.UM
        HAVING  SUM(STMAG.QTA1UM*STMAG.ORDINATO) <>0 OR 
            SUM(STMAG.QTA1UM*STMAG.IMPEGNATO) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 
        ) AS GIACENZAINIZIALEMETODO
    ) AS GIACENZAINIZIALEUNIFICATA
    GROUP BY CODART,CODDEPOSITO,UM
    
    INSERT INTO @GIACENZA
    SELECT  CODART,
        CODDEPOSITO,
        SUM(GIACENZAINIZIALE) AS GIACENZA,
        (SUM(GIACENZAINIZIALE) + SUM(ORDINATO) - SUM(IMPEGNATO)) AS DISPONIBILITA,
        SUM(ORDINATO) AS ORDINATO,
        SUM(IMPEGNATO) AS IMPEGNATO,
        SUM(CARICO) AS CARICO,
        SUM(SCARICO) AS SCARICO,
        SUM(RESODACARICO) AS RESODACARICO,
        SUM(RESODASCARICO) AS RESODASCARICO,
        UM
    FROM
    (
        SELECT  CODART,
            CODDEPOSITO,
            (CARICO - SCARICO - RESODACARICO + RESODASCARICO) AS GIACENZAINIZIALE,
            ORDINATO,
            IMPEGNATO,
            CARICO,
            SCARICO,
            RESODACARICO,
            RESODASCARICO,
            UM
        FROM
        (
        SELECT  STMAG.CODART,
            STMAG.CODDEPOSITO,
            SUM((STMAG.QTA1UM*STMAG.ORDINATO)) AS ORDINATO,
            SUM((STMAG.QTA1UM*STMAG.IMPEGNATO)) AS IMPEGNATO,
            SUM((CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END)) AS CARICO,
            SUM((CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END)) AS SCARICO,
            SUM((CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END)) AS RESODACARICO,
            SUM((CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END)) AS RESODASCARICO,
            AUM.UM
        FROM STORICOMAG AS STMAG 
        INNER JOIN TABVINCOLIGIC AS TVG 
            ON STMAG.ESERCIZIO=TVG.ESERCIZIO
        INNER JOIN ANAGRAFICAARTICOLI ART 
            ON ART.CODICE=STMAG.CODART
        INNER JOIN ARTICOLIUMPREFERITE AUM 
            ON AUM.CODART=STMAG.CODART AND AUM.TIPOUM=1
        WHERE   STMAG.CODART=@ARTICOLO AND 
            STMAG.CODDEPOSITO IN (SELECT CODICE FROM ANAGRAFICADEPOSITI WHERE DISPONIBILE = 1) 
            AND STMAG.ESERCIZIO = @Esercizio
        GROUP BY STMAG.CODART,
             STMAG.CODDEPOSITO,
             AUM.UM
        HAVING  SUM(STMAG.QTA1UM*STMAG.ORDINATO) <>0 OR 
            SUM(STMAG.QTA1UM*STMAG.IMPEGNATO) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
            SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 
        ) AS GIACENZAMETODO
    ) AS GIACENZAUNIFICATA
    GROUP BY CODART,CODDEPOSITO,UM
    
    INSERT INTO @Results
    SELECT  CODART,
        CODDEPOSITO,
        SUM(GIACENZA) AS GIACENZA,
        SUM(DISPONIBILITA) AS DISPONIBILITA,
        SUM(ORDINATO) AS ORDINATO,
        SUM(IMPEGNATO) AS IMPEGNATO,
        SUM(CARICO) AS CARICO,
        SUM(SCARICO) AS SCARICO,
        SUM(RESODACARICO) AS RESODACARICO,
        SUM(RESODASCARICO) AS RESODASCARICO,
        UM
    FROM
    (
        SELECT * 
        FROM    @GIACENZAINIZIALE GIACINIT
        UNION
        SELECT * 
        FROM    @GIACENZA GIAC
    ) AS GIACENZAFINALE
    GROUP BY CODART,
         CODDEPOSITO,
         UM
    ORDER BY CODART,
         CODDEPOSITO,
         UM

RETURN

END


GO
GRANT SELECT
    ON OBJECT::[dbo].[FunGIACENZAFINALEARTICOLO] TO [Metodo98]
    AS [dbo];

