
CREATE FUNCTION FunGIACDISPLOTTILOG(@ARTICOLO nVARCHAR(50),@DEPOSITO nVARCHAR(10),@TIPOUBICAZIONE SMALLINT)
                            RETURNS @Results TABLE (CODLOTTO       nVARCHAR(15) , 
                                                    GIAC           DECIMAL(19,6), 
                                                    DISP           DECIMAL(19,6))

AS

BEGIN

   -- SE @TIPOUBICAZIONE=-1 NON VERRA' APPLICATO NESSUN FILTRO SULLE UBICAZIONI

   INSERT INTO @Results	
	
   SELECT
    
     ISNULL(NRIFPARTITA,'') AS CODLOTTO, 
    (SUM(CASE WHEN GIACENZA=1 and RESO = 0 THEN QTA1UM ELSE 0 END)+
	 SUM(CASE WHEN GIACENZA=1 and RESO = 1 THEN QTA1UM ELSE 0 END)-
     SUM(CASE WHEN GIACENZA=-1 and RESO = 0 THEN QTA1UM ELSE 0 END)-
     SUM(CASE WHEN GIACENZA=-1 and RESO = 1 THEN QTA1UM ELSE 0 END)) AS GIAC,
    ((SUM(CASE WHEN GIACENZA=1 and RESO = 0 THEN QTA1UM ELSE 0 END)+
	  SUM(CASE WHEN GIACENZA=1 and RESO = 1 THEN QTA1UM ELSE 0 END)-
      SUM(CASE WHEN GIACENZA=-1 and RESO = 0 THEN QTA1UM ELSE 0 END)-
      SUM(CASE WHEN GIACENZA=-1 and RESO = 1 THEN QTA1UM ELSE 0 END))  + SUM(QTA1UM*ORDINATO) - SUM(QTA1UM*IMPEGNATO)) AS DISP
                                
   FROM STORICOMAG LEFT JOIN TABUBICAZIONIDEPOSITI ON STORICOMAG.CODDEPOSITO=TABUBICAZIONIDEPOSITI.CODDEPOSITO AND STORICOMAG.CODUBICAZIONE=TABUBICAZIONIDEPOSITI.CODUBICAZIONE
   WHERE STORICOMAG.CODART=@ARTICOLO AND STORICOMAG.CODDEPOSITO=@DEPOSITO
         AND ISNULL(TABUBICAZIONIDEPOSITI.TIPOUBICAZIONE,1000) = (CASE WHEN @TIPOUBICAZIONE=-1 THEN ISNULL(TABUBICAZIONIDEPOSITI.TIPOUBICAZIONE,1000) ELSE @TIPOUBICAZIONE END)   
   GROUP BY ISNULL(NRIFPARTITA,'')         


  RETURN

END


GO
GRANT SELECT
    ON OBJECT::[dbo].[FunGIACDISPLOTTILOG] TO [Metodo98]
    AS [dbo];

