
CREATE FUNCTION [dbo].[FUNNUMEROORDINE](@PROGRESSIVORP DECIMAL(10,0),@IDRIGARP INT)
RETURNS VARCHAR(18)
AS
BEGIN

DECLARE @NUMEROORDINE VARCHAR(18)
	
	SET @NUMEROORDINE = '0'

	SELECT @NUMEROORDINE=NUMRIFDOC FROM TESTEDOCUMENTI 
	WHERE PROGRESSIVO=(SELECT IDTESTARP FROM RIGHEDOCUMENTI WHERE IDTESTA=@PROGRESSIVORP AND IDRIGA=@IDRIGARP)
	
	RETURN(@NUMEROORDINE)
END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[FUNNUMEROORDINE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FUNNUMEROORDINE] TO [Metodo98]
    AS [dbo];

