
create FUNCTION FunULTIMIPREZZI (@CODCONTO nVARCHAR(7), 
					@ESERCIZIO INT)
	RETURNS @Results TABLE (RIFERIMENTO nVARCHAR(50) ,
				        CODARTICOLO nVARCHAR(50)  ,
				        DESCRIZIONE nVARCHAR(250)  ,
				        PREZZOLST DECIMAL(19,4),				        
				        UMGEST nVARCHAR(5) ,
				        QTAGEST DECIMAL(19,6),
				        DATADOC DATETIME,
				        SCONTOESTESO nVARCHAR(50) , 
				        GRUPPO DECIMAL(5,0),
				        CATEGORIA DECIMAL(5,0),
				        CODCATEGORIASTAT DECIMAL(5,0),
				        GRUPPOPRZPART DECIMAL(5,0),
				        DATAFINESEGN DATETIME,
				        CODFAMIGLIAPOS DECIMAL(5,0),
				        CODREPARTOPOS DECIMAL(5,0))
AS

    BEGIN
	DECLARE @CODARTICOLO nVARCHAR(50)

	DECLARE Articoli_Cursor CURSOR FOR
			SELECT  DISTINCT
				TP_PREZZIVENDITA.CODARTICOLO
			FROM TP_PREZZIVENDITA 
			WHERE TP_PREZZIVENDITA.CODCONTO=@CODCONTO
	OPEN Articoli_Cursor

	FETCH NEXT FROM Articoli_Cursor 
		INTO @CODARTICOLO

	WHILE @@FETCH_STATUS = 0
		BEGIN
		    INSERT INTO @Results 
			SELECT TOP 1
				(CASE WHEN RELAZIONICFV.RIFERIMENTO is null THEN '' ELSE RELAZIONICFV.RIFERIMENTO END) AS RIFERIMENTO, 
				TP_PREZZIVENDITA.CODARTICOLO, 
				ANAGRAFICAARTICOLI.DESCRIZIONE,
				TP_PREZZIVENDITA.PREZZOLST,
				TP_PREZZIVENDITA.UMGEST,
				TP_PREZZIVENDITA.QTAGEST,
				TP_PREZZIVENDITA.DATADOC,
				TP_PREZZIVENDITA.SCONTOESTESO,
				ANAGRAFICAARTICOLI.GRUPPO,
				ANAGRAFICAARTICOLI.CATEGORIA,
				ANAGRAFICAARTICOLI.CODCATEGORIASTAT,
				ANAGRAFICAARTICOLICOMM.GRUPPOPRZPART,
				TP_EXTRAMAG.DATAFINESEGN,
				TP_EXTRAMAG.CODFAMIGLIAPOS,
				TP_EXTRAMAG.CODREPARTOPOS
			FROM TP_PREZZIVENDITA 
			INNER JOIN ANAGRAFICAARTICOLI ON ANAGRAFICAARTICOLI.CODICE=TP_PREZZIVENDITA.CODARTICOLO 
			INNER JOIN ANAGRAFICAARTICOLICOMM ON ANAGRAFICAARTICOLI.CODICE=ANAGRAFICAARTICOLICOMM.CODICEART AND 
							    	            ANAGRAFICAARTICOLI.ARTTIPOLOGIA=0 AND 
								            ANAGRAFICAARTICOLICOMM.ESERCIZIO=@ESERCIZIO
			INNER JOIN TP_EXTRAMAG ON TP_EXTRAMAG.CODART= TP_PREZZIVENDITA.CODARTICOLO
			LEFT JOIN RELAZIONICFV ON (CASE WHEN RELAZIONICFV.Varianti = '' or RELAZIONICFV.Varianti is null 
							THEN RELAZIONICFV.Articolo 
							ELSE (RELAZIONICFV.Articolo+'#'+ RELAZIONICFV.Varianti) END)=ANAGRAFICAARTICOLI.CODICE AND 
					RELAZIONICFV.CODCLIFOR=TP_PREZZIVENDITA.CODCONTO 
			WHERE TP_PREZZIVENDITA.CODCONTO=@CODCONTO  AND
				 TP_PREZZIVENDITA.CODARTICOLO=@CODARTICOLO
			ORDER BY TP_PREZZIVENDITA.DATADOC DESC

		    FETCH NEXT FROM Articoli_Cursor 
					INTO @CODARTICOLO
		END

	CLOSE Articoli_Cursor

	DEALLOCATE Articoli_Cursor
    
    RETURN
END

GO
GRANT SELECT
    ON OBJECT::[dbo].[FunULTIMIPREZZI] TO [Metodo98]
    AS [dbo];

