CREATE FUNCTION RighePrelevate(@PROGRESSIVO DECIMAL(10, 0),@RIGHE VARCHAR(MAX)) RETURNS VARCHAR(MAX)  
AS
BEGIN
	DECLARE CUR_DOC CURSOR FAST_FORWARD READ_ONLY FOR SELECT IDRIGA,IDRIGARP FROM RIGHEDOCUMENTI WHERE IDTESTA=@PROGRESSIVO AND IDTESTARP IS NOT NULL 
	DECLARE @RIGAPREL DECIMAL(10, 0)
	DECLARE @IDRIGA DECIMAL(10, 0)
	DECLARE @RIFDOC VARCHAR(MAX)

	SET @RIFDOC = ','
	OPEN CUR_DOC
	FETCH CUR_DOC INTO @IDRIGA, @RIGAPREL
	WHILE @@FETCH_STATUS = 0
		BEGIN
		IF (CHARINDEX(','+CAST(@IDRIGA AS VARCHAR(4))+',', @RIGHE) > 0) OR (@RIGHE = '')
			BEGIN
			SET @RIFDOC = @RIFDOC + CAST(@RIGAPREL AS VARCHAR(4)) + ','
			END
		FETCH NEXT FROM CUR_DOC INTO @IDRIGA, @RIGAPREL
		END
	CLOSE CUR_DOC
	DEALLOCATE CUR_DOC
	RETURN @RIFDOC
END	

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[RighePrelevate] TO [Metodo98]
    AS [dbo];

