


/****** Oggetto: funzione definita dall'utente dbo.SplitCCVMCAU    Data dello script: 22/04/2005 10.39.49 ******/

CREATE FUNCTION SplitCCVMCAUProd(@Parameter NVARCHAR(500))
RETURNS @Results TABLE (Items Int)
AS


    BEGIN

    DECLARE @CAU1 NVARCHAR(60)
    DECLARE @CAU2 NVARCHAR(60)
    DECLARE @CAU3 NVARCHAR(60)
    DECLARE @CAU4 NVARCHAR(60)

    DECLARE @Delimiter NCHAR(1)
    DECLARE @INDEX INT
    DECLARE @SLICE NVARCHAR(500)

    DECLARE @String NVARCHAR(185)

    --Prelevo i Documenti
	IF @Parameter='CON' 
	    BEGIN
		SELECT  @CAU1=CAUSMAGCONSDAPROD1 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
		SELECT  @CAU2=CAUSMAGCONSDAPROD2 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
		SELECT  @CAU3=CAUSMAGCONSDADOC3 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
		SELECT  @CAU4=CAUSMAGCONSDADOC4 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
	    END
	
	IF @Parameter='CAR' 
	    BEGIN
		SELECT  @CAU1=CAUSMAGCARICHIDAPROD5 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
		SELECT  @CAU2=CAUSMAGCARICHIDAPROD6 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
		SELECT  @CAU3=CAUSMAGCARICHIDADOC7 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
		SELECT  @CAU4=CAUSMAGCARICHIDADOC8 FROM TP_VINCOLIPIANIFICATORE WHERE PROGRESSIVO=1
	    END

	IF ((@CAU1 IS NULL)) 
		BEGIN
			SET @CAU1 = ''
		END

	IF ((@CAU2 IS NULL)) 
		BEGIN
			SET @CAU2 = ''
		END

	IF ((@CAU3 IS NULL)) 
		BEGIN
			SET @CAU3 = ''
		END

	IF ((@CAU4 IS NULL)) 
		BEGIN
			SET @CAU4 = ''
		END

    -- HAVE TO SET TO 1 SO IT DOESNT EQUAL Z
    --     ERO FIRST TIME IN LOOP
    SELECT @INDEX = 1
    SELECT @Delimiter=','
    SELECT @String=@CAU1 + CASE WHEN @CAU2<>''
			  THEN (',' + @CAU2)
			  ELSE @CAU2 END
		   	 + CASE WHEN @CAU3<>''
			  THEN (',' + @CAU3)
			  ELSE @CAU3 END
		   	 + CASE WHEN @CAU4<>''
			  THEN (',' + @CAU4)
			  ELSE @CAU4 END

    WHILE @INDEX !=0


        BEGIN
            -- GET THE INDEX OF THE FIRST OCCURENCE OF THE SPLIT NCHARACTER
            SELECT @INDEX = CHARINDEX(@Delimiter,@STRING)

            -- NOW PUSH EVERYTHING TO THE LEFT OF IT INTO THE SLICE VARIABLE
            IF @INDEX !=0
                SELECT @SLICE = LEFT(@STRING,@INDEX - 1)
            ELSE
	        SELECT @SLICE = @STRING
        	-- PUT THE ITEM INTO THE RESULTS SET
	        INSERT INTO @Results(Items) VALUES(@SLICE)

		-- CHOP THE ITEM REMOVED OFF THE MAIN STRING
	        SELECT @STRING = RIGHT(@STRING,LEN(@STRING) - @INDEX)

		-- BREAK OUT IF WE ARE DONE
	        IF LEN(@STRING) = 0 BREAK
	END

    RETURN
END


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[SplitCCVMCAUProd] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SplitCCVMCAUProd] TO [Metodo98]
    AS [dbo];

