
CREATE VIEW VISTARIGHECAUSALE AS
SELECT  PROGRIGHE,
		MASTRO,
		(SELECT DESCRIZIONE FROM TABMASTRI WHERE CODICE=CAUSALICONTABILIRIGHE.MASTRO) AS DSCMASTRO,
		CONTO,
		(CASE WHEN SUBSTRING(CAUSALICONTABILIRIGHE.CONTO,1,1)<>'G' THEN (SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO=CAUSALICONTABILIRIGHE.CONTO) ELSE (SELECT DSCCONTO1 FROM ANAGRAFICAGENERICI WHERE CODCONTO=CAUSALICONTABILIRIGHE.CONTO) END) AS DSCCONTO,
		(CASE WHEN SEGNO=0 THEN 'DARE' ELSE 'AVERE' END) AS DSCSEZIONE,
		SEGNO,
		CODICECAUSALE
		FROM CAUSALICONTABILIRIGHE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARIGHECAUSALE] TO [Metodo98]
    AS [dbo];

