CREATE VIEW VISTATABCENTRIDICOSTO AS
        SELECT TABCENTRICOSTO.CODICE, TABCENTRICOSTO.DESCRIZIONE, 
        TABCENTRICOSTO.NOTE, TABCENTRICOSTO.DATAINIVALIDITA, 
        TABCENTRICOSTO.DATAFINEVALIDITA, TABCENTRICOSTO.UTENTEMODIFICA, 
        TABCENTRICOSTO.DATAMODIFICA, TABESERCIZI.DATAINICONT, 
        TABESERCIZI.DATAFINECONT
        FROM TABCENTRICOSTO, TABESERCIZI
        WHERE TABCENTRICOSTO.DATAFINEVALIDITA >= TABESERCIZI.DATAINICONT
        AND TABCENTRICOSTO.DATAINIVALIDITA <= TABESERCIZI.DATAFINECONT
        AND TABESERCIZI.CODICE = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB=CAST(USER_NAME() AS VARCHAR(25)))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATABCENTRIDICOSTO] TO [Metodo98]
    AS [dbo];

