CREATE VIEW VISTASITUAZIONEFASI_EXT AS
        SELECT 
            -- CAMPI CHIAVE
            FASI.NOMEPIANIF AS NOMEPIANIF_J
            ,FASI.PROG_ID AS PROG_ID_J
            ,FASI.FASE_ID AS FASE_ID_J
            ,FASI.TIPO AS TIPO_J
        FROM PROGPRODUZIONEFASI FASI
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASITUAZIONEFASI_EXT] TO [Metodo98]
    AS [dbo];

