
CREATE VIEW
   VISTASALDISITCONT
      AS SELECT RC.CONTO,RC.ESERCIZIO,TC.PROVVISORIO,
      SUM((CASE WHEN RC.SEGNO = 0 THEN IMPORTO ELSE 0 END)) AS DARE,
      SUM((CASE WHEN RC.SEGNO = 0 THEN IMPORTOEURO ELSE 0 END)) AS DAREEURO,
      SUM((CASE WHEN RC.SEGNO = 0 THEN IMPORTOVALUTA ELSE 0 END)) AS DAREVALUTA,
      SUM((CASE WHEN RC.SEGNO = 1 THEN IMPORTO ELSE 0 END)) AS AVERE,
      SUM((CASE WHEN RC.SEGNO = 1 THEN IMPORTOEURO ELSE 0 END)) AS AVEREEURO,
      SUM((CASE WHEN RC.SEGNO = 1 THEN IMPORTOVALUTA ELSE 0 END)) AS AVEREVALUTA,
      SUM((CASE WHEN RC.SEGNO = 0 THEN IMPORTO ELSE 0 END)-(CASE WHEN RC.SEGNO = 1 THEN IMPORTO ELSE 0 END)) AS SALDO,
      SUM((CASE WHEN RC.SEGNO = 0 THEN IMPORTOEURO ELSE 0 END)-(CASE WHEN RC.SEGNO = 1 THEN IMPORTOEURO ELSE 0 END)) AS SALDOEURO,
      SUM((CASE WHEN RC.SEGNO = 0 THEN IMPORTOVALUTA ELSE 0 END)-(CASE WHEN RC.SEGNO = 1 THEN IMPORTOVALUTA ELSE 0 END)) AS SALDOVALUTA 
      FROM RIGHECONTABILITA AS RC,TESTECONTABILITA AS TC WHERE RC.NRREG = TC.PROGRESSIVO AND 
      TC.CAUSALE <> (SELECT GIC.CAUSCONTAP FROM TABVINCOLIGIC AS GIC WHERE GIC.ESERCIZIO = TC.ESERCIZIO) AND
      TC.CAUSALE <> (SELECT GIC.CAUSCONTCH FROM TABVINCOLIGIC AS GIC WHERE GIC.ESERCIZIO = TC.ESERCIZIO) 
      GROUP BY RC.CONTO,RC.ESERCIZIO,TC.PROVVISORIO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASALDISITCONT] TO [Metodo98]
    AS [dbo];

