CREATE VIEW VISTAPROVENIENZA
AS
	SELECT TOP 1 0 CODICE, 'Acquisti' DESCRIZIONE FROM NUMERI
	UNION SELECT TOP 1 1 CODICE, 'Produzione' DESCRIZIONE FROM NUMERI
	UNION SELECT TOP 1 2 CODICE, 'Conto Lavoro' DESCRIZIONE FROM NUMERI

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPROVENIENZA] TO [Metodo98]
    AS [dbo];

