
CREATE VIEW VISTASPESEFATTPA AS
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+1 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
 'Spese Effetto' AS DescrizioneRiga,
TOTSPESEEFFETTO AS PrezzoUnitario,
TOTSPESEEFFETTO AS PrezzoTotale,
CODIVASPEFF AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPEFF),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPEFF),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPEFF,0)=0 THEN 'N2' ELSE
COALESCE((SELECT NATURAESENZPA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPEFF),'') END) AS NATURAESENZ
FROM TESTEDOCUMENTI 
WHERE TOTSPESEEFFETTO<>0
UNION ALL
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+2 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
'Spese Imballo' AS DescrizioneRiga,
TOTSPESEIMBALLO AS PrezzoUnitario,
TOTSPESEIMBALLO AS PrezzoTotale,
CODIVASPIMB AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPIMB),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPIMB),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPIMB,0)=0 THEN 'N2' ELSE
COALESCE((SELECT NATURAESENZPA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPIMB),'') END) AS NATURAESENZ
FROM dbo.TESTEDOCUMENTI 
WHERE TOTSPESEIMBALLO<>0
UNION ALL
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+3 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
'Spese Trasporto' AS DescrizioneRiga,
TOTSPESETRASP AS PrezzoUnitario,
TOTSPESETRASP AS PrezzoTotale,
CODIVASPTRASP AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPTRASP),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPTRASP),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPTRASP,0)=0 THEN 'N2' ELSE
COALESCE((SELECT NATURAESENZPA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPTRASP),'') END) AS NATURAESENZ
FROM dbo.TESTEDOCUMENTI 
WHERE TOTSPESETRASP<>0
UNION ALL
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+4 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
'Spese Bollo' AS DescrizioneRiga,
TOTSPESEDOC AS PrezzoUnitario,
TOTSPESEDOC AS PrezzoTotale,
CODIVASPDOC AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPDOC),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPDOC),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPDOC,0)=0 THEN 'N2' ELSE
COALESCE((SELECT NATURAESENZPA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPDOC),'') END) AS NATURAESENZ
FROM dbo.TESTEDOCUMENTI 
WHERE TOTSPESEDOC<>0


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASPESEFATTPA] TO [Metodo98]
    AS [dbo];

