CREATE VIEW VISTARISTAMPADISTINTEEFF AS
SELECT VS.*,DE.DATAEMISS,DE.DESCRIZIONE AS DSCDISTINTA,DE.CODBANCA AS CODBANCADIST,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN 
       VDCF.RAGIONESOCIALE ELSE 
       (SELECT RAGIONESOCIALE FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS RAGIONESOCIALE,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       VDCF.RAGIONESOCIALE2 ELSE
       (SELECT RAGIONESOCIALE2 FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS RAGIONESOCIALE2,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       VDCF.INDIRIZZO ELSE
       (SELECT INDIRIZZO FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS INDIRIZZO,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       VDCF.CAP ELSE
       (SELECT CAP FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS CAP,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       VDCF.LOCALITA ELSE
       (SELECT LOCALITA FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS LOCALITA,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       VDCF.PROVINCIA ELSE
       (SELECT PROVINCIA FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS PROVINCIA,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       (SELECT ABI FROM BANCAAPPCF WHERE CODCONTO=VS.CODCLIFOR AND CODICE=VS.BANCAAPPOGGIO)
       ELSE
       (SELECT ABI FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS ABI,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       (SELECT CAB FROM BANCAAPPCF WHERE CODCONTO=VS.CODCLIFOR AND CODICE=VS.BANCAAPPOGGIO) 
       ELSE
       (SELECT CAB FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS CAB,
   (CASE WHEN (SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)=0 THEN
       VDCF.FAX ELSE
       (SELECT FAX FROM VISTADESTINAZIONIDDIV WHERE CODCONTO=VS.CODCLIFOR AND NUMERO=(SELECT DESTDIVDOCUMENTI FROM VISTACLIFOR WHERE CODCONTO=VS.CODCLIFOR)) END) AS FAXDD,
   (SELECT BANCAAPPOGGIO FROM BANCAAPPCF WHERE CODCONTO=VS.CODCLIFOR AND CODICE=VS.BANCAAPPOGGIO) AS BANCAANAGR,
   (SELECT PARTITAIVA FROM ANAGRAFICACF WHERE CODCONTO=VS.CODCLIFOR) AS PARTITAIVA,
   (SELECT CODFISCALE FROM ANAGRAFICACF WHERE CODCONTO=VS.CODCLIFOR) AS CODFISCALE,
   (SELECT CONTOCORRENTE FROM BANCAAPPCF WHERE CODCONTO=VS.CODCLIFOR AND CODICE=VS.BANCAAPPOGGIO) AS CCANAGRAFICA,
   (SELECT CODICEIBAN FROM BANCAAPPCF WHERE CODCONTO=VS.CODCLIFOR AND CODICE=VS.BANCAAPPOGGIO) AS CODICEIBAN,   
   (SELECT TOP 1 RAGSOCCOGNOME + ' ' + RAGSOCNOME FROM TABDITTE) AS RAGSOCDITTA,
   (SELECT TOP 1 VIASEDEFISCALE + ', ' + NUMSEDEFISCALE FROM TABDITTE) AS SEDEFISCALE,
   (SELECT TOP 1 CAPSEDEFISCALE + ' ' + COMUNESEDEFISCALE + ' (' + PROVSEDEFISCALE + ')' FROM TABDITTE) AS CAPLOCDITTA
   FROM VISTASCADENZE VS, DISTINTEEFFETTI DE, VISTADESTINAZIONICF VDCF
   WHERE VS.NRDISTINTA=DE.PROGRESSIVO AND VDCF.CODCONTO=VS.CODCLIFOR


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARISTAMPADISTINTEEFF] TO [Metodo98]
    AS [dbo];

