CREATE VIEW VISTARIGHERATEIRISCONTI AS
SELECT TRR.*,
    (SELECT DSCCONTO1 FROM ANAGRAFICAGENERICI WHERE ANAGRAFICAGENERICI.CODCONTO=TRR.CODCONTO) AS DSCCODCONTO,
    (SELECT DSCCONTO1 FROM ANAGRAFICAGENERICI WHERE ANAGRAFICAGENERICI.CODCONTO=TRR.CONTO) AS DSCCONTO
    FROM TABRIPARTIZRATEIRISCONTI TRR WHERE TIPORIGA=1

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARIGHERATEIRISCONTI] TO [Metodo98]
    AS [dbo];

