create view [VISTASTORICOACQUISTI] as
select 
	STP.CODARTICOLO,
	STP.CODCLIFOR,
	CF.DSCCONTO1 as RAGSOCFOR,
	STP.DATA,
	STP.QUANTITA,STP.UM,
	STP.PREZZOEURO,
	STP.ULTIMO,
	STP.CODPAGAMENTO,
	PAG.DESCRIZIONE as DSCPAGAMENTO,	
	STM.RIFERIMENTI
from 
	STORICOPREZZIARTICOLO STP 
	inner join STORICOMAG STM on STM.PROGRESSIVO=STP.RIFSTORICOMAG
	inner join ANAGRAFICACF CF on CF.CODCONTO=STP.CODCLIFOR
	left outer join TABPAGAMENTI PAG on PAG.CODICE=STP.CODPAGAMENTO
where 
	STP.TIPOPREZZO='F'

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOACQUISTI] TO [Metodo98]
    AS [dbo];

