CREATE VIEW VISTAPARAMCOSTIPRODOTTO AS
SELECT 
	IDCOSTO,
	DESCRIZIONE,
	TIPOCOSTO,
 	(CASE TIPOCOSTO WHEN 0 THEN 'Standard' ELSE 'Corrente' END) AS DESTIPOCOSTO,
	CRITERIOVAL,
	(CASE CRITERIOVAL WHEN 0 THEN 'Tecnico' ELSE 'Gestionale' END) AS DESCRITERIOVAL,
	FLG_GESTCOSTI,
	FLG_CONSIDERACICLI,
	FLG_ARTCICLODISTINTA,
	FLG_AGGCOSTIPROD,
	TIPOAGGCOMPONENTI,
	(CASE TIPOAGGCOMPONENTI WHEN 0 THEN 'Agg. Sempre' ELSE (CASE TIPOAGGCOMPONENTI WHEN 1 THEN 'Agg. Costi a zero' ELSE 'Non Agg.' END) END) AS DESTIPOAGGCOMPONENTI,
	TIPOVALORIZMAT_1,
	LISTMAT_1,
	COSTOSTD_1,
	COSTOCORR_1,
	TIPOVALORIZMAT_2,
	LISTMAT_2,
	COSTOSTD_2,
	COSTOCORR_2,
	TIPOVALORIZMAT_3,
	LISTMAT_3,
	COSTOSTD_3,
	COSTOCORR_3,
	(CASE TIPOVALORIZMAT_1 WHEN -1 THEN 'nessun criterio' ELSE 
		(CASE TIPOVALORIZMAT_1 WHEN 0 THEN 'Ultimo Prezzo Acq.' ELSE 
			(CASE TIPOVALORIZMAT_1 WHEN 2 THEN 'Costo Medio' ELSE 
				(CASE TIPOVALORIZMAT_1 WHEN 3 THEN 'Lifo' ELSE 
					(CASE TIPOVALORIZMAT_1 WHEN 5 THEN 'Listino ' + CAST(LISTMAT_1 AS VARCHAR) ELSE 
						(CASE TIPOVALORIZMAT_1 WHEN 6 THEN 'Costo Std ' + COSTOSTD_1 ELSE 
							(CASE TIPOVALORIZMAT_1 WHEN 7 THEN 'Costo Corr ' + COSTOCORR_1 ELSE '' END) 
						END) 
					END) 
				END) 
			END)
		END)
	END) AS DESORIGINECOSTO1,	
	(CASE TIPOVALORIZMAT_2 WHEN -1 THEN 'nessun criterio' ELSE 
		(CASE TIPOVALORIZMAT_2 WHEN 0 THEN 'Ultimo Prezzo Acq.' ELSE 
			(CASE TIPOVALORIZMAT_2 WHEN 2 THEN 'Costo Medio' ELSE 
				(CASE TIPOVALORIZMAT_2 WHEN 3 THEN 'Lifo' ELSE 
					(CASE TIPOVALORIZMAT_2 WHEN 5 THEN 'Listino ' + CAST(LISTMAT_2 AS VARCHAR) ELSE 
						(CASE TIPOVALORIZMAT_2 WHEN 6 THEN 'Costo Std ' + COSTOSTD_2 ELSE 
							(CASE TIPOVALORIZMAT_2 WHEN 7 THEN 'Costo Corr ' + COSTOCORR_2 ELSE '' END) 
						END) 
					END) 
				END) 
			END)
		END)
	END) AS DESORIGINECOSTO2,	
	(CASE TIPOVALORIZMAT_3 WHEN -1 THEN 'nessun criterio' ELSE 
		(CASE TIPOVALORIZMAT_3 WHEN 0 THEN 'Ultimo Prezzo Acq.' ELSE 
			(CASE TIPOVALORIZMAT_3 WHEN 2 THEN 'Costo Medio' ELSE 
				(CASE TIPOVALORIZMAT_3 WHEN 3 THEN 'Lifo' ELSE 
					(CASE TIPOVALORIZMAT_3 WHEN 5 THEN 'Listino ' + CAST(LISTMAT_3 AS VARCHAR) ELSE 
						(CASE TIPOVALORIZMAT_3 WHEN 6 THEN 'Costo Std ' + COSTOSTD_3 ELSE 
							(CASE TIPOVALORIZMAT_3 WHEN 7 THEN 'Costo Corr ' + COSTOCORR_3 ELSE '' END) 
						END) 
					END) 
				END) 
			END)
		END)
	END) AS DESORIGINECOSTO3,
	FLG_USALISTTRASF,
	TIPOVALTRASF,
	FLG_VALUTACICLO,
	TIPOVALCICLO,
	LISTTRASF,
	COSTOSTD,
	COSTOCORR,
	UTENTEMODIFICA,
	DATAMODIFICA
FROM
	PARAMCOSTIPRODOTTO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPARAMCOSTIPRODOTTO] TO [Metodo98]
    AS [dbo];

