
CREATE VIEW [dbo].[VISTASELPARAMETRIDOCPREL] AS
SELECT  
    PDC.* 
FROM 
    PARAMETRIDOC PDC 
    INNER JOIN  TABUTENTI ON USERDB = USER_NAME()
WHERE 
    (SUPERVISOR = 1 OR 
        (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSIDOCUMENTI WHERE CODDOCUMENTO = PDC.CODICE AND FLAGPRELEVA=1))
    )

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASELPARAMETRIDOCPREL] TO [Metodo98]
    AS [dbo];

