CREATE VIEW VISTASTORICOCONSEGNEUM AS
SELECT STORICOCONSEGNE.IDSTORICO, 
    STORICOCONSEGNE.IDTESTA, STORICOCONSEGNE.IDRIGA, 
    STORICOCONSEGNE.TIPODOC, 
    STORICOCONSEGNE.NUMERODOC, STORICOCONSEGNE.BIS, 
    STORICOCONSEGNE.VARIANTI, 
    STORICOCONSEGNE.DESCRIZIONEART, 
    STORICOCONSEGNE.ESERCIZIO, 
    STORICOCONSEGNE.CODARTICOLO, 
    STORICOCONSEGNE.CODCLIENTE, 
    STORICOCONSEGNE.CODPARTITA, 
    STORICOCONSEGNE.UBICAZIONE, 
    STORICOCONSEGNE.CODDEPOSITO, 
    STORICOCONSEGNE.UM, 
    STORICOCONSEGNE.QUANTITA, 
    STORICOCONSEGNE.QTACONSIDERATA, 
    STORICOCONSEGNE.CAMPOCONSIDERATO, 
    STORICOCONSEGNE.IDENTIFICATIVOCONS,
    TESTEDOCUMENTI.DATADOC,
    TESTEDOCUMENTI.DATARIFDOC,
    TESTEDOCUMENTI.NUMRIFDOC,
    VISTAFATTORICONVERSIONE.UMRIC, 
    VISTAFATTORICONVERSIONE.FORMULAFC,
    STORICOCONSEGNE.CODARTICOLO AS CODART
FROM (STORICOCONSEGNE LEFT OUTER JOIN VISTAFATTORICONVERSIONE ON STORICOCONSEGNE.UM = VISTAFATTORICONVERSIONE.UMJOIN AND STORICOCONSEGNE.CODARTICOLO = VISTAFATTORICONVERSIONE.CODART) 
    LEFT OUTER JOIN TESTEDOCUMENTI ON TESTEDOCUMENTI.PROGRESSIVO=STORICOCONSEGNE.IDTESTA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOCONSEGNEUM] TO [Metodo98]
    AS [dbo];

