
CREATE VIEW VISTATP_ARTICOLIESPOSITORE
AS
SELECT     ANAGRAFICAARTICOLI.CODICE, ANAGRAFICAARTICOLI.DESCRIZIONE, TP_ExtraMag.TP_Espositore
FROM         ANAGRAFICAARTICOLI INNER JOIN
                      TP_ExtraMag ON ANAGRAFICAARTICOLI.CODICE = TP_ExtraMag.CodArt
WHERE     (TP_ExtraMag.TP_Espositore <> '') AND (TP_ExtraMag.TP_Espositore <> '0')


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTATP_ARTICOLIESPOSITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTATP_ARTICOLIESPOSITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTATP_ARTICOLIESPOSITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATP_ARTICOLIESPOSITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTATP_ARTICOLIESPOSITORE] TO [Metodo98]
    AS [dbo];

