create view VISTAMODIFICHEPIANO as
	select 	
		PP.NOMEPIANIF,PP.RIFERIMENTI,PP.PROG_ID,PP.TIPO,PP.TIPODOC,PP.CODART,
		PP.CODFOR as CODFOR_PIAN, TD.CODCLIFOR as CODFOR_ATT,
		PP.DATACONS as DATACONS_PIAN, dbo.MaxDate(RD.DATACONSEGNA,GetDate()) as DATACONS_ATT,
		PP.QTADOCBASE as QUANTITA_PIAN, RD.QTA1MAGRES as QUANTITA_ATT,
		PP.VERDBA as VERDBA_PIAN, RD.VERSIONEDIBA as VERDBA_ATT,
		(case when RD.IDTESTA is null then
			0
		else
			1
		end) as CONFERMATO,
		(case when PP.CODFOR<>TD.CODCLIFOR then 1 else 0 end) as CODFOR_MOD,
		(case when PP.DATACONS<>dbo.MaxDate(RD.DATACONSEGNA,GetDate()) then 1 else 0 end) as DATACONS_MOD,
		(case when PP.VERDBA<>RD.VERSIONEDIBA then 1 else 0 end) as VERDBA_MOD,
		(case when PP.QTADOCBASE<>RD.QTA1MAGRES then 1 else 0 end) as QUANTITA_MOD
	from 
		PROGPRODUZIONE PP 
		left outer join TESTEDOCUMENTI TD on TD.PROGRESSIVO=PP.IDTESTADOC
		left outer join RIGHEDOCUMENTI RD on RD.IDTESTA=PP.IDTESTADOC and RD.IDRIGA=PP.IDRIGADOC
	where 
		TIPO in (3,5,4)
		and ((RD.IDTESTA is null) 
			or (PP.CODFOR<>TD.CODCLIFOR)
			or (PP.DATACONS<>dbo.MaxDate(RD.DATACONSEGNA,GetDate())) 
			or (PP.QTADOCBASE<>RD.QTA1MAGRES) 
			or (RD.VERSIONEDIBA<>'' and PP.VERDBA<>RD.VERSIONEDIBA))

	union all 

	select 
		PP.NOMEPIANIF,PP.RIFERIMENTI,PP.PROG_ID,PP.TIPO,PP.TIPODOC,PP.CODART,	
		PP.CODFOR as CODFOR_PIAN, RD.CODFORDEST as CODFOR_ATT,
		PP.DATACONS as DATACONS_PIAN, dbo.MaxDate(RD.DATAFINERICH,GetDate()) as DATACONS_ATT,
		PP.QTADOCBASE as QUANTITA_PIAN, RD.QTA1MAGRES as QUANTITA_ATT,
		PP.VERDBA as VERDBA_PIAN, RD.VERSIONEDBA as VERDBA_ATT,
		(case when RD.IDTESTA is null then
			0
		else
			1
		end) as CONFERMATO,
		(case when PP.CODFOR<>RD.CODFORDEST then 1 else 0 end) as CODFOR_MOD,
		(case when PP.DATACONS<>dbo.MaxDate(RD.DATAFINERICH,GetDate()) then 1 else 0 end) as DATACONS_MOD,
		(case when PP.VERDBA<>RD.VERSIONEDBA then 1 else 0 end) as VERDBA_MOD,
		(case when PP.QTADOCBASE<>RD.QTA1MAGRES then 1 else 0 end) as QUANTITA_MOD
	from 
		PROGPRODUZIONE PP inner join RIGHEORDPROD RD on RD.IDTESTA=PP.IDTESTADOC and RD.IDRIGA=PP.IDRIGADOC
	where 
		TIPO = 6
		and ((RD.IDTESTA is null) 
			or (PP.CODFOR<>RD.CODFORDEST)
			or (PP.DATACONS<>dbo.MaxDate(RD.DATAFINERICH,GetDate())) 
			or (PP.QTADOCBASE<>RD.QTA1MAGRES) 
			or (PP.VERDBA<>RD.VERSIONEDBA))

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMODIFICHEPIANO] TO [Metodo98]
    AS [dbo];

