CREATE VIEW VISTATESTECONTABILITATF AS
SELECT TC.*
FROM TESTECONTABILITATF TC INNER JOIN TABUTENTI ON USERDB = CAST(USER_NAME() AS VARCHAR(25))
WHERE
    ((SUPERVISOR=1) OR (SUPERVISOR=0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSICAUSCONT WHERE CODCAUSALE=TC.CAUSALE AND FLAGVISUALIZZA=1)))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTECONTABILITATF] TO [Metodo98]
    AS [dbo];

