
CREATE VIEW [dbo].[VISTAPRELIEVO]
  AS SELECT TESTEDOCUMENTI.*,
    (CASE WHEN DATADEC = DATADOC THEN NULL ELSE DATADEC END) AS DECORRENZA,
    (CASE WHEN (PD.DOCTRASPORTO <>0 AND PD.CLIFOR ='C') THEN (CASE WHEN ANNOLIQUIDAZ=0 THEN YEAR(TESTEDOCUMENTI.DATADOC)  ELSE ANNOLIQUIDAZ END) ELSE NULL END) AS FLAGANNOLIQUIDAZ,
    (CASE WHEN (PD.DOCTRASPORTO <>0 AND PD.CLIFOR ='C') THEN (CASE WHEN MESELIQUIDAZ=0 THEN MONTH(TESTEDOCUMENTI.DATADOC) ELSE MESELIQUIDAZ END) ELSE NULL END) AS FLAGMESELIQUIDAZ,
    (CASE WHEN (PD.CLIFOR ='F') THEN (CASE WHEN ANNOPLAFOND=0  THEN YEAR(TESTEDOCUMENTI.DATADOC)  ELSE ANNOPLAFOND  END) ELSE NULL END) AS FLAGANNOPLAFOND,
    (CASE WHEN (PD.CLIFOR ='F') THEN (CASE WHEN MESEPLAFOND=0  THEN MONTH(TESTEDOCUMENTI.DATADOC) ELSE MESEPLAFOND  END) ELSE NULL END) AS FLAGMESEPLAFOND,
    PD.VersaCompetenze AS VERSACOMPETENZE
--introdotto nella vista std Prelievo il campo ExTD.IdDivisione
                                    , isnull(ExTD.IdDivisione, 0) as IdDivisione
--Fine introdotto nella vista std Prelievo il campo ExTD.IdDivisione
-- EC PD1500231 PUNTO 5.5.5.5
                                    , isnull(ExTD.AldCodIva, 0) as AldCodIva
-- FINE EC PD1500231 PUNTO 5.5.5.5

FROM (TESTEDOCUMENTI INNER JOIN PARAMETRIDOC PD ON TESTEDOCUMENTI.TIPODOC=PD.CODICE) INNER JOIN  TABUTENTI ON USERDB = CAST(USER_NAME() AS VARCHAR(25))
    -- join esterna con tbl extratestedoc per campo EXTRATESTEDOC.idDivisione
LEFT OUTER JOIN EXTRATESTEDOC AS ExTD ON TESTEDOCUMENTI.PROGRESSIVO = ExTD.IDTESTA
-- fine join esterna con tbl extratestedoc per campo EXTRATESTEDOC.idDivisione


    WHERE TESTEDOCUMENTI.BLOCCATO=0 AND TESTEDOCUMENTI.DOCCHIUSO=0
    AND (SUPERVISOR = 1 OR 
        (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSIDOCUMENTI WHERE CODDOCUMENTO = TESTEDOCUMENTI.TIPODOC AND FLAGPRELEVA=1)))
    AND ((TESTEDOCUMENTI.CODCLIFOR=TABUTENTI.CODCLIFOR) OR (TABUTENTI.CODCLIFOR=''))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPRELIEVO] TO [Metodo98]
    AS [dbo];

