
CREATE VIEW VISTAPOSFILEDATIFATTURA AS
SELECT TDF.*,
FDF.NOMEFILEXML,FDF.FLGINVIATO,FDF.FLGANNULLATO,FDF.IDFILESDI,FDF.TIPO,
PF.PROGFILEDF,PF.POSIZIONEDF,PF.PROGRESSIVO AS PROGRPOSFILE,PF.PROGFILEANN,PF.PROGFILERETT,
(SELECT SUM(IMPONIBILEEURO) FROM RIGHEIVADATIFATTURA WHERE IDTESTA=TDF.PROGRESSIVO) AS TOTIMPONIBILE,
(SELECT SUM(IMPOSTAEURO) FROM RIGHEIVADATIFATTURA WHERE IDTESTA=TDF.PROGRESSIVO) AS TOTIMPOSTA,
(SELECT NOMEFILEXML FROM FILEDATIFATTURA FDA WHERE FDA.PROGRESSIVO=PF.PROGFILEANN) AS NOMEFILEANN,
(SELECT NOMEFILEXML FROM FILEDATIFATTURA FDR WHERE FDR.PROGRESSIVO=PF.PROGFILERETT) AS NOMEFILERETT
FROM TESTEDATIFATTURA TDF LEFT OUTER JOIN (POSFILEDATIFATTURA PF INNER JOIN FILEDATIFATTURA FDF ON PF.PROGFILEDF=FDF.PROGRESSIVO) ON TDF.PROGRESSIVO=PF.IDTESTADF


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPOSFILEDATIFATTURA] TO [Metodo98]
    AS [dbo];

