
CREATE VIEW VISTARIGHEBILANCI AS
SELECT TCONT.ESERCIZIO,
    TCONT.DATAREG,
    TCONT.PROVVISORIO,
    TCONT.CAUSALE,
    TCONT.NRGIORNALE,
    RCONT.CONTO,
    RCONT.SEGNO,
    (CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTO ELSE 0 END) AS DARE,
    (CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOEURO ELSE 0 END) AS DAREEURO,
    (CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS DAREVALUTA,
    (CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTO ELSE 0 END) AS AVERE,
    (CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOEURO ELSE 0 END) AS AVEREEURO,
    (CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS AVEREVALUTA
    FROM RIGHECONTABILITA AS RCONT,TESTECONTABILITA AS TCONT
    WHERE RCONT.NRREG=TCONT.PROGRESSIVO
    AND TCONT.CAUSALE<>(SELECT GIC.CAUSCONTAP FROM TABVINCOLIGIC AS GIC WHERE GIC.ESERCIZIO=TCONT.ESERCIZIO)


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARIGHEBILANCI] TO [Metodo98]
    AS [dbo];

