create view VISTAMOVORDINILOTTI AS
SELECT
    1 AS TIPOMOV,
    SMP.DATAMOV AS DATASESSIONE,
    SMP.ESERCIZIO AS ESERCIZIOSESSIONE,
    (TOPR.TIPOCOM+'/'+LTRIM(STR(TOPR.ESERCIZIO))+'/'+LTRIM(STR(TOPR.NUMEROCOM))) AS RIFCOMMESSA,    
    SMOP.RIFPROGRESSIVO,
    SMOP.RIGAMOVORD,
    0 AS RIGAMOVIMP,
    SMOP.RIGAMOVORD AS NUMMOV,
    SMOP.POSIZIONE,
    SMOP.RIFTESTA AS IDTESTA,
    SMOP.RIFRIGA AS IDRIGA,
    0 AS IDIMPEGNO,
    TOPR.TIPOCOM AS TIPOCOM,
    TOPR.ESERCIZIO AS ESERCIZIO,
    TOPR.NUMEROCOM AS NUMEROCOM,
    TOPR.DATAEMISSIONE AS DATAEMISSIONE,
    SMOP.CODART,
    AA.DESCRIZIONE AS DESCRART,
    SMOP.QTAMOVGESTIONE,
    SMOP.UMGEST,
    SMOP.QTAMOVPREZZO,
    SMOP.UMPREZZO,
    SMOP.QTAMOV1MAG,
    SMOP.QTAMOV2MAG,
    SMOP.UMSCARTO,
    SMOP.QTAMOVSCARTO,
    SMOP.PARTITAASSEGNATA,
    SMOP.CODCLIDEST,
    SMOP.CAUSALEMOV,
    SMOP.DEPOSITO,
    SMOP.UBICAZIONE,
    SMOP.CONTOCDC,
    SMOP.CAUSALEMOVCOLL,
    SMOP.DEPOSITOCOLL,
    SMOP.UBICAZIONECOLL,
    SMOP.CONTOCDCCOLL,
    SMOP.CAUSALESCARTO,
    SMOP.DEPOSITOSCARTO,
    SMOP.UBICAZIONESCARTO,
    SMOP.CONTOCDCSCARTO,
    SMOP.COSTOUNITMOV,
    SMOP.COSTOTOTMOV,
    SMOP.COSTOUNITMOVEURO,
    SMOP.COSTOTOTMOVEURO,
    SMOP.NOTE,
    SMOP.COSTOMATERIALE,
    SMOP.COSTOMATERIALEEURO,
    SMOP.COSTOLAVINTERNA,
    SMOP.COSTOLAVINTERNAEURO,
    SMOP.COSTOLAVESTERNA,
    SMOP.COSTOLAVESTERNAEURO,
    SMOP.COSTOINDIRETTO,
    SMOP.COSTOINDIRETTOEURO,
    SMOP.CODFORDEST,
    SMOP.RIFCOMMCLI,
    SMOP.UM1MAG,
    SMOP.UM2MAG,
    SMOP.IDCOSTOPRODOTTO,
    POP.TIPOORDINE  AS TIPOORD,      
    ROPR.CODICEORD

FROM
    STORICOMOVPROD SMP
    INNER JOIN STORICOMOVORDPROD SMOP ON SMOP.RIFPROGRESSIVO=SMP.PROGRESSIVO
    INNER JOIN TESTEORDINIPROD TOPR ON TOPR.PROGRESSIVO=SMOP.RIFTESTA
    INNER JOIN RIGHEORDPROD ROPR ON ROPR.IDTESTA=SMOP.RIFTESTA AND ROPR.IDRIGA=SMOP.RIFRIGA
    INNER JOIN PARAMETRIORDPROD POP ON POP.CODICE=ROPR.CODICEORD
    INNER JOIN ANAGRAFICAARTICOLI AA ON AA.CODICE=SMOP.CODART
    

UNION ALL

SELECT 
    -1 AS TIPOMOV,
    SMP.DATAMOV AS DATASESSIONE,
    SMP.ESERCIZIO AS ESERCIZIOSESSIONE,
    (TOPR.TIPOCOM+'/'+LTRIM(STR(TOPR.ESERCIZIO))+'/'+LTRIM(STR(TOPR.NUMEROCOM))) AS RIFCOMMESSA,   
    SMIP.RIFPROGRESSIVO,
    SMIP.RIGAMOVORD,
    SMIP.RIGAMOVIMP,
    SMIP.RIGAMOVIMP AS NUMMOV,
    SMIP.POSIZIONE,
    SMIP.RIFTESTA AS IDTESTA,
    SMIP.RIFRIGA AS IDRIGA,
    SMIP.RIFIMPEGNO AS IDIMPEGNO,
    TOPR.TIPOCOM AS TIPOCOM,
    TOPR.ESERCIZIO AS ESERCIZIO,
    TOPR.NUMEROCOM AS NUMEROCOM,
    TOPR.DATAEMISSIONE AS DATAEMISSIONE,
    SMIP.CODART,
    AA.DESCRIZIONE AS DESCRART,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.QTAMOVGESTIONE ELSE SMIP_PART.QTAMOVGESTIONE END) AS QTAMOVGESTIONE,
    SMIP.UMGEST,
    SMIP.QTAMOVPREZZO,
    SMIP.UMPREZZO,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.QTAMOV1MAG ELSE SMIP_PART.QTAMOV1MAG END) AS QTAMOV1MAG,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.QTAMOV2MAG ELSE SMIP_PART.QTAMOV2MAG END) AS QTAMOV2MAG,
    SMIP.UMSCARTO,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.QTAMOVSCARTO ELSE SMIP_PART.QTAMOVSCARTO END) AS QTAMOVSCARTO,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.PARTITAASSEGNATA ELSE SMIP_PART.PARTITA END) AS PARTITAASSEGNATA,    
    '' AS CODCLIDEST,
    SMIP.CAUSALEMOV,
    SMIP.DEPOSITO,
    SMIP.UBICAZIONE,
    SMIP.CONTOCDC,
    SMIP.CAUSALEMOVCOLL,
    SMIP.DEPOSITOCOLL,
    SMIP.UBICAZIONECOLL,
    SMIP.CONTOCDCCOLL,
    SMIP.CAUSALESCARTO,
    SMIP.DEPOSITOSCARTO,
    SMIP.UBICAZIONESCARTO,
    SMIP.CONTOCDCSCARTO,
    SMIP.COSTOUNITMOV,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.COSTOTOTMOV ELSE (SMIP.COSTOUNITMOV * SMIP_PART.QTAMOVGESTIONE) END) AS COSTOTOTMOV,
    SMIP.COSTOUNITMOVEURO,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.COSTOTOTMOVEURO ELSE (SMIP.COSTOUNITMOVEURO * SMIP_PART.QTAMOVGESTIONE) END) AS COSTOTOTMOVEURO,
    SMIP.NOTE,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.COSTOTOTMOV ELSE (SMIP.COSTOUNITMOV * SMIP_PART.QTAMOVGESTIONE) END) AS COSTOMATERIALE,
    (CASE WHEN SMIP_PART.PARTITA IS NULL THEN SMIP.COSTOTOTMOVEURO ELSE (SMIP.COSTOUNITMOVEURO * SMIP_PART.QTAMOVGESTIONE) END) AS COSTOMATERIALEEURO,
    0 AS COSTOLAVINTERNA,
    0 AS COSTOLAVINTERNAEURO,
    0 AS COSTOLAVESTERNA,
    0 AS COSTOLAVESTERNAEURO,
    0 AS COSTOINDIRETTO,
    0 AS COSTOINDIRETTOEURO,
    SMIP.CODFORPREL AS CODFORDEST,
    SMIP.RIFCOMMCLI,
    SMIP.UM1MAG,
    SMIP.UM2MAG,'' AS IDCOSTOPRODOTTO,
    POP.TIPOORDINE  AS TIPOORD,      
    ROPR.CODICEORD    
FROM
    STORICOMOVPROD SMP
    INNER JOIN STORICOMOVORDPROD SMOP ON SMOP.RIFPROGRESSIVO=SMP.PROGRESSIVO
    INNER JOIN STORICOMOVIMPPROD SMIP ON SMIP.RIFPROGRESSIVO=SMP.PROGRESSIVO AND SMIP.RIGAMOVORD=SMOP.RIGAMOVORD
    INNER JOIN TESTEORDINIPROD TOPR ON TOPR.PROGRESSIVO=SMOP.RIFTESTA
    INNER JOIN RIGHEORDPROD ROPR ON ROPR.IDTESTA=SMOP.RIFTESTA AND ROPR.IDRIGA=SMOP.RIFRIGA
    INNER JOIN PARAMETRIORDPROD POP ON POP.CODICE=ROPR.CODICEORD
    INNER JOIN ANAGRAFICAARTICOLI AA ON AA.CODICE=SMIP.CODART    
    LEFT OUTER JOIN STORICOMOVPARTITEIMP SMIP_PART ON SMIP.RIFPROGRESSIVO=SMIP_PART.RIFPROGRESSIVO AND SMIP.RIGAMOVORD=SMIP_PART.RIFRIGAMOVORD AND SMIP.RIGAMOVIMP=SMIP_PART.RIFRIGAMOVIMP

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMOVORDINILOTTI] TO [Metodo98]
    AS [dbo];

