create view VISTARIFERIMENTIPIANO as
	select 
		PP.NOMEPIANIF,
		PP.PROG_ID,
		PP.CODART,
		PP.RIFERIMENTI,
		PP.RIFID,
		(case when PLS.CODART is null then '' else PLS.CODART end) as CODARTPADRE
	from PROGPRODUZIONE PP left outer join PROGPRODUZIONE PLS
		on PLS.NOMEPIANIF=PP.NOMEPIANIF and PLS.PROG_ID=PP.RIFID

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARIFERIMENTIPIANO] TO [Metodo98]
    AS [dbo];

