

CREATE VIEW VISTASTAMPAAPCHSOLLDOC AS
SELECT TD.CODCLIFOR,TD.DATADOC,TD.CODCAMBIO,TD.VALCAMBIO,
TD.CODAGENTE1,TD.CODAGENTE2,TD.CODAGENTE3,TD.TOTDOCUMENTO,TD.TOTDOCUMENTORES,TD.TOTDOCUMENTOEURO,TD.TOTDOCUMENTOEURORES,
TD.NUMRIFDOC,TD.DATARIFDOC,
RD.*,CF.DSCCONTO1,CF.DSCCONTO2,CF.INDIRIZZO,CF.CAP,CF.LOCALITA,CF.PROVINCIA,CF.CODNAZIONE,CF.FAX,CF.TELEFONO,
(SELECT DESCRIZIONE FROM TABNAZIONI WHERE CODICE=CF.CODNAZIONE) AS DSCNAZIONE,
CAST(IDTESTA AS VARCHAR)+'|'+CAST(IDRIGA AS VARCHAR) AS IDTESTARIGA
FROM TESTEDOCUMENTI TD, RIGHEDOCUMENTI RD, ANAGRAFICACF CF
WHERE TD.PROGRESSIVO=RD.IDTESTA AND TD.CODCLIFOR=CF.CODCONTO
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTAMPAAPCHSOLLDOC] TO [Metodo98]
    AS [dbo];

