

CREATE VIEW VISTASTAMPAPROMOCONDIZIONIMERCEOLOGICHE
AS
SELECT     ART.RIFPROGRESSIVO, 0 AS CONFMERC, ART.CODICE, TAB.DESCRIZIONE, CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA, 
                      DETT.NRRIGA
FROM         dbo.PROMOZIONI_ARTICOLO AS ART INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = ART.RIFPROGRESSIVO AND 
                      ART.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE ART.NRRIGA END) LEFT JOIN
                      dbo.ANAGRAFICAARTICOLI AS TAB ON TAB.CODICE = ART.CODICE 
UNION
SELECT     GRP.RIFPROGRESSIVO, 1 AS CONFMERC, CAST(GRP.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA, DETT.NRRIGA
FROM         dbo.PROMOZIONI_GRUPPO AS GRP INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = GRP.RIFPROGRESSIVO AND 
                      GRP.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE GRP.NRRIGA END) INNER JOIN
                      dbo.TABGRUPPI AS TAB ON TAB.CODICE = GRP.CODICE 
UNION
SELECT     CAT.RIFPROGRESSIVO, 2 AS CONFMERC, CAST(CAT.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA, DETT.NRRIGA
FROM         dbo.PROMOZIONI_CATEGORIA AS CAT INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = CAT.RIFPROGRESSIVO AND 
                      CAT.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE CAT.NRRIGA END) INNER JOIN
                      dbo.TABCATEGORIE AS TAB ON TAB.CODICE = CAT.CODICE 
UNION
SELECT     CATS.RIFPROGRESSIVO, 3 AS CONFMERC, CAST(CATS.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA, DETT.NRRIGA
FROM         dbo.PROMOZIONI_CATEGORIAS AS CATS INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = CATS.RIFPROGRESSIVO AND 
                      CATS.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE CATS.NRRIGA END) INNER JOIN
                      dbo.TABCATEGORIESTAT AS TAB ON TAB.CODICE = CATS.CODICE 
UNION
SELECT     PRZ.RIFPROGRESSIVO, 4 AS CONFMERC, CAST(PRZ.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA, DETT.NRRIGA
FROM         dbo.PROMOZIONI_GRUPPO_PREZZI AS PRZ INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = PRZ.RIFPROGRESSIVO AND 
                      PRZ.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE PRZ.NRRIGA END) INNER JOIN
                      dbo.TABRAGGRUPPAPREZZI AS TAB ON TAB.CODICE = PRZ.CODICE 
UNION
SELECT     FR.RIFPROGRESSIVO, 5 AS CONFMERC, 'MetFam:' + CAST(FR.FAMIGLIA AS VARCHAR) + ' - MetRep:' + CAST(FR.REPARTO AS VARCHAR) AS CODICE, 
                      'MetFam:' + FAM.Descrizione + '- MetRep:' + REP.Descrizione AS DESCRIZIONE, CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA,
                       DETT.NRRIGA
FROM         dbo.PROMOZIONI_FAMREP AS FR INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = FR.RIFPROGRESSIVO AND 
                      FR.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE FR.NRRIGA END) INNER JOIN
                      dbo.TabFamigliePOS AS FAM ON FAM.Codice = FR.FAMIGLIA INNER JOIN
                      dbo.TabRepartiPOS AS REP ON REP.Codice = FR.REPARTO 
UNION
SELECT     LIV.RIFPROGRESSIVO, 6 AS CONFMERC, LIV.CODICE, TAB.Descrizione, CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, 
                      DETT.NRRIGA
FROM         dbo.PROMOZIONI_LIVELLIMERCEOLOGICI AS LIV INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = LIV.RIFPROGRESSIVO INNER JOIN
                      dbo.Tp_LivelliMerceologici AS TAB ON TAB.Codice = REPLACE(LIV.CODICE, '''', '') 
UNION
SELECT     FT.RIFPROGRESSIVO, 7 AS CONFMERC, (CAST(FT.CODFEATURE  AS VARCHAR) + ' - Varianti:' + FT.VARESPLICITE) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 1 ELSE 0 END AS TIPOLOGIA, DETT.NRRIGA
FROM         dbo.PROMOZIONI_FEATURE AS FT INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = FT.RIFPROGRESSIVO AND 
                      FT.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE FT.NRRIGA END) INNER JOIN
                      dbo.FEATURE AS TAB ON TAB.CODICE = FT.CODFEATURE


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTAMPAPROMOCONDIZIONIMERCEOLOGICHE] TO [Metodo98]
    AS [dbo];

