create view VISTAPRODUZIONEMANCANTEBASE as
	select 
		IMP.IDTESTA as RIFTESTA,IMP.IDRIGA as RIFRIGA,IMP.IDIMPEGNO as RIFIMPEGNO,
		IMP.CODART,DEPOSITO,UM.UM1 as UM,
		QTA1MAGRES as FABBISOGNO,
		(select sum(GIAC.ORDINATO) from VISTAGIACENZE GIAC WHERE IMP.CODART=GIAC.CODART AND IMP.DEPOSITO=GIAC.CODDEPOSITO) as ORDINATO,
		(select sum(GIAC.IMPEGNATO) from VISTAGIACENZE GIAC WHERE IMP.CODART=GIAC.CODART AND IMP.DEPOSITO=GIAC.CODDEPOSITO) as IMPEGNATO,
		(select sum(GIAC.CARICO)+sum(GIAC.RESODASCARICO) from VISTAGIACENZE GIAC WHERE IMP.CODART=GIAC.CODART AND IMP.DEPOSITO=GIAC.CODDEPOSITO) as CARICHI,
		(select sum(GIAC.SCARICO)+sum(GIAC.RESODACARICO) from VISTAGIACENZE GIAC WHERE IMP.CODART=GIAC.CODART AND IMP.DEPOSITO=GIAC.CODDEPOSITO) as SCARICHI,
		((select sum(GIAC.IMPEGNATO) from VISTAGIACENZE GIAC WHERE IMP.CODART=GIAC.CODART AND IMP.DEPOSITO=GIAC.CODDEPOSITO) - QTA1MAGRES) as ALTRIIMPEGNI
	from 
		IMPEGNIORDPROD IMP inner join VISTAARTICOLIUMBASE UM
		on IMP.CODART=UM.CODICE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPRODUZIONEMANCANTEBASE] TO [Metodo98]
    AS [dbo];

