
CREATE VIEW VISTASTORICOMAGMATRICOLE AS
SELECT 
    STMAG.BIS,
    STMAG.CODART,
    STMAG.CODCAMBIO,
    STMAG.CODCAUSALE,
    STMAG.CODCLIFOR,
    STMAG.CODCOMMESSA,
    STMAG.CODDEPOSITO,
    STMAG.CODPAG,
    STMAG.CODUBICAZIONE,
    STMAG.CONTOCDCMOV,
    STMAG.DATAMOV,
    STMAG.DATARIFDOC,
    STMAG.DESTDIV,
    STMAG.GENVENACQ,
    STMAG.IDDISTINTABASE,
    STMAG.IDTESTA,
    STMAG.IMPORTOTOTLORDO,
    STMAG.IMPORTOTOTLORDOEURO,
    STMAG.IMPORTOTOTLORDOVAL,
    STMAG.IMPORTOTOTNETTO,
    STMAG.IMPORTOTOTNETTOEURO,
    STMAG.IMPORTOTOTNETTOVAL,
    STMAG.LISTINO,
    STMAG.NRIFDOC,
    STMAG.NRIFPARTITA,
    STMAG.NUMERODOC,
    STMAG.PROGRCOLLEGATO,
    STMAG.PROGRESSIVO,
    STMAG.QTA1UM,
    STMAG.QTA2UM,
    STMAG.RIFERIMENTI,
    STMAG.RIGACOMP,
    STMAG.RIGADOC,
    STMAG.SCONTO,
    STMAG.TIPODOC,
    STMAG.TIPOMOV,
    STMAG.VALCAMBIO,
    STMAG.VARIANTE,
    STMAG.ESERCIZIO,
    (CASE WHEN (STMAG.TIPOMOV = 0) THEN
    0
    ELSE
        (CASE WHEN (STMAG.TIPOMOV IN (1,2,3,4,13,14,15,16)) THEN 
        1 
         ELSE 
        (CASE WHEN (STMAG.TIPOMOV IN(5,6,9,10,17,18)) THEN 
            2 
        ELSE 
            (CASE WHEN (STMAG.TIPOMOV IN (7,8,11,12,19,20)) THEN 
                3 
            END) 
        END) 
         END)
     END) AS ORIGINEMOV,
     STM.CODMATRICOLA
FROM 
    STORICOMAG AS STMAG INNER JOIN STORICOMAGMATRICOLE STM ON STMAG.PROGRESSIVO=STM.PROGRESSIVO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOMAGMATRICOLE] TO [Metodo98]
    AS [dbo];

