

CREATE VIEW VISTAMOVIMENTICES AS SELECT
    Progressivo,
    Cespite,
    Tipo,
    Descrizione,
    DtaMovimento,
    (CASE WHEN Tipo IN (7,13) THEN DtaEffettiva ELSE DtaDocumento END) AS DtaDocumento,
    (CASE WHEN Tipo IN (7,13) THEN DtaMovimento ELSE DtaEffettiva END) AS DtaEffettiva,
    NumDocumento,
    CodFornitore,
    DesFornitore,
    CompQtaRes,
    CompQtaEli,
    PercAmmOrd,
    PercAmmAnt,
    PercAmmRid,
    PercRivSva,
    PercAmpOrd,
    PercAmpAnt,
    CompetenzaImp,
    CompetenzaOrd,
    CompetenzaAnt,
    CompetenzaNon,
    ImpDocumento,
    ImpResiduo,
    PMValenze,
    ImpImmRes,
    FdoOrdRes,
    FdoAntRes,
    QteNonRes,
    ImpImmEli,
    FdoOrdEli,
    FdoAntEli,
    QteNonEli,
    CompetenzaImpEuro,
    CompetenzaOrdEuro,
    CompetenzaAntEuro,
    CompetenzaNonEuro,
    ImpDocumentoEuro,
    ImpResiduoEuro,
    PMValenzeEuro,
    ImpImmResEuro,
    FdoOrdResEuro,
    FdoAntResEuro,
    QteNonResEuro,
    ImpImmEliEuro,
    FdoOrdEliEuro,
    FdoAntEliEuro,
    QteNonEliEuro,
    TotQtaRes,
    TotQtaEli,
    FlgMinUti,
    CompetenzaImpMax,
    CompetenzaImpMaxEuro,
    DataIniziale,
    ImpImmResMax,
    ImpImmResMaxEuro,
    ImpImmEliMax,
    ImpImmEliMaxEuro,
    UTENTEMODIFICA,
    DATAMODIFICA,
    ImpDocumentoIniz,
    ImpDocumentoInizEuro,
    ImpDocumentoVend,
    ImpDocumentoVendEuro,
    FDOANNOPREC,
    CodUbicazione,
    CodNuovaUbic,
    PrcDetrai,
    NuovaPrcDetrai,
    ESERCIZIO,
    ESERCIZIOSTP,
    TIPORIV,
    FLAGSTP,
    COMPSUPERAMMEURO,
    COMPIPERAMMEURO,
    PRCSUPERAMM,
    PRCIPERAMM
FROM MovimentiCes

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMOVIMENTICES] TO [Metodo98]
    AS [dbo];

