CREATE VIEW VISTASTORICOMAGPRODBASE_COMMCLI AS 
SELECT 
	STMAG.PROGRESSIVO,
	STMAG.CODART,
	STMAG.CODCAMBIO,
	STMAG.CODCAUSALE,
	STMAG.CODCLIFOR,
	STMAG.CODCOMMESSA,
	STMAG.CODDEPOSITO,
	STMAG.DATAMOV,
	STMAG.QTA1UM,
	STMAG.QTA2UM,
	(SELECT UM FROM ARTICOLIUMPREFERITE AUM WHERE STMAG.CODART=AUM.CODART AND AUM.TIPOUM=1)  AS UM1,
	(SELECT UM FROM ARTICOLIUMPREFERITE AUM WHERE STMAG.CODART=AUM.CODART AND AUM.TIPOUM=2)  AS UM2,
	STMAG.IDTESTA,
	STMAG.RIGADOC,
	STMAG.TIPODOC,
	STMAG.TIPOMOV,
	STMAG.ESERCIZIO,
	STMAG.IMPORTOTOTNETTO,
    STMAG.IMPORTOTOTNETTOEURO,
	(SELECT TIPO FROM PARAMETRIDOC WHERE CODICE=STMAG.TIPODOC) AS TIPOPAR,	
	(CASE WHEN STMAG.TIPOMOV between 5 and 8 then STMAG.IDTESTA else (select RIFTESTA from STORICOMOVPROD where STORICOMOVPROD.PROGRESSIVO=STMAG.IDTESTA) end) as IDTESTAORD,
	(CASE WHEN STMAG.TIPOMOV between 5 and 8 then STMAG.RIGADOC else (select RIFRIGA from STORICOMOVORDPROD where STORICOMOVORDPROD.RIFPROGRESSIVO=STMAG.IDTESTA and STORICOMOVORDPROD.RIGAMOVORD=STMAG.RIGADOC) end) as IDRIGAORD,
	(CASE WHEN STMAG.TIPOMOV between 5 and 8 then STMAG.RIGACOMP else (select RIFIMPEGNO from STORICOMOVIMPPROD where STORICOMOVIMPPROD.RIFPROGRESSIVO=STMAG.IDTESTA and STORICOMOVIMPPROD.RIGAMOVORD=STMAG.RIGADOC and STORICOMOVIMPPROD.RIGAMOVIMP=STMAG.RIGACOMP) end) as IDIMPEGNOORD,
	(SELECT CODICEORD FROM RIGHEORDPROD ROP WHERE ROP.IDTESTA=(CASE WHEN STMAG.TIPOMOV between 5 and 8 then STMAG.IDTESTA else (select RIFTESTA from STORICOMOVPROD where STORICOMOVPROD.PROGRESSIVO=STMAG.IDTESTA) end) AND ROP.IDRIGA=(CASE WHEN STMAG.TIPOMOV between 5 and 8 then STMAG.RIGADOC else (select RIFRIGA from STORICOMOVORDPROD where STORICOMOVORDPROD.RIFPROGRESSIVO=STMAG.IDTESTA and STORICOMOVORDPROD.RIGAMOVORD=STMAG.RIGADOC) end)) AS CODICEORD
FROM 
	STORICOMAG STMAG
WHERE 
	STMAG.TIPOMOV in (5,6,7,8,9,10,11,12,17,18,19,20)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOMAGPRODBASE_COMMCLI] TO [Metodo98]
    AS [dbo];

