CREATE VIEW VISTAOMAGGIB2B AS
SELECT 
   IDTESTA,
   IDRIGA,
   POSIZIONE,
   PREZZOUNITLORDO*-1 AS PREZZOUNITARIO,
   TOTNETTORIGA*-1 AS TOTNETTORIGA,
   QTAPREZZO AS QUANTITA,
   0 AS ALIQIVA,
   COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=(SELECT TOP 1 CODICE FROM TRATTAMENTOIVA WHERE UPPER(DESCRIZIONE) LIKE 'ART. 2' OR UPPER(DESCRIZIONE) LIKE 'ART.2' AND CODICE BETWEEN 200 AND 299) AND TIPOCICLO IN (0,2)),'') AS NATURA,
   COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=(SELECT TOP 1 CODICE FROM TRATTAMENTOIVA WHERE UPPER(DESCRIZIONE) LIKE 'ART. 2' OR UPPER(DESCRIZIONE) LIKE 'ART.2' AND CODICE BETWEEN 200 AND 299) AND TIPOCICLO IN (1,2)),'') AS NATURAPASS,
   (CASE WHEN (SELECT RIVIVAOMAGGI FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA)=0 THEN 'Omaggio senza rivalsa' ELSE 'Omaggio con rivalsa' END) AS  DESCRIZIONE
    FROM RIGHEDOCUMENTI 
    WHERE TIPORIGA='O'

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAOMAGGIB2B] TO [Metodo98]
    AS [dbo];

