CREATE VIEW VISTATABCAUSALIMAG AS
        SELECT TABCAUSALIMAG.CODICE, TABCAUSALIMAG.DESCRIZIONE, 
        TABCAUSALIMAG.CLIFOR, TABCAUSALIMAG.QUANTITACARICO, 
        TABCAUSALIMAG.VALORECARICO, TABCAUSALIMAG.QUANTITASCARICO, 
        TABCAUSALIMAG.VALORESCARICO, TABCAUSALIMAG.GIACENZA, 
        TABCAUSALIMAG.ORDINATO, TABCAUSALIMAG.IMPEGNATO, 
        TABCAUSALIMAG.GIACENZA2UM, TABCAUSALIMAG.ORDINATO2UM, 
        TABCAUSALIMAG.IMPEGNATO2UM, TABCAUSALIMAG.NRGIORNALE, 
        TABCAUSALIMAG.FLGCONSCOMMCLI, TABCAUSALIMAG.CODCAUSCOMMCLI, 
        TABCAUSALIMAG.DATAINIVALIDITA, TABCAUSALIMAG.DATAFINEVALIDITA,TABCAUSALIMAG.RESO,
        TABCAUSALIMAG.UTENTEMODIFICA, TABCAUSALIMAG.DATAMODIFICA
        FROM TABCAUSALIMAG, TABESERCIZI
        WHERE TABCAUSALIMAG.DATAFINEVALIDITA >= TABESERCIZI.DATAINIMAG
        AND TABCAUSALIMAG.DATAINIVALIDITA <= TABESERCIZI.DATAFINEMAG
        AND TABESERCIZI.CODICE = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB=USER_NAME())

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATABCAUSALIMAG] TO [Metodo98]
    AS [dbo];

