

CREATE VIEW VISTATESTECONTRATTI_DESTDIVERSE
AS
SELECT     dbo.TESTE_CONTRATTI.PROGRESSIVO, dbo.TESTE_CONTRATTI.TIPONODO, dbo.TESTE_CONTRATTI.CODICE, 
                      dbo.VISTATESTE_CONTRATTI_CF.CODICE AS CODCF, dbo.DESTINAZIONIDIVERSE.RAGIONESOCIALE
FROM         dbo.TESTE_CONTRATTI INNER JOIN
                      dbo.VISTATESTE_CONTRATTI_CF ON dbo.TESTE_CONTRATTI.NODOPARENT = dbo.VISTATESTE_CONTRATTI_CF.PROGRESSIVO INNER JOIN
                      dbo.DESTINAZIONIDIVERSE ON dbo.VISTATESTE_CONTRATTI_CF.CODICE = dbo.DESTINAZIONIDIVERSE.CODCONTO AND 
                      dbo.TESTE_CONTRATTI.CODICE = dbo.DESTINAZIONIDIVERSE.CODICE
WHERE     (dbo.TESTE_CONTRATTI.TIPONODO = 3)


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTATESTECONTRATTI_DESTDIVERSE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTATESTECONTRATTI_DESTDIVERSE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTATESTECONTRATTI_DESTDIVERSE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTECONTRATTI_DESTDIVERSE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTATESTECONTRATTI_DESTDIVERSE] TO [Metodo98]
    AS [dbo];

