CREATE VIEW VISTAMOVCONTCOMP AS
SELECT RCONT.NRREG,RCONT.NRRIGA,TCONT.PROGRESSIVO,
    TCONT.ESERCIZIO,
    TCONT.DATAREG,
    TCONT.NRRIFER,
    TCONT.PROVVISORIO,
    TCONT.MOVIVA,
    TCONT.CAUSALE,
    TCONT.MESEPLAFOND,
    TCONT.DESCRIZIONE,
    TCONT.APPUNTI,
    TCONT.TOTDOCLIRE,
    TCONT.TOTDOCVALUTA,
    TCONT.TOTDOCEURO,
    TCONT.NRGIORNALE,
    TCONT.IDTESTADOC,
    RCONT.DATARIF,
    RCONT.NRRIF,
    RCONT.NRPARTITA,
    RCONT.CONTO,
    RCONT.SEGNO,
    RCONT.IMPORTO,RCONT.IMPORTOVALUTA,
    RCONT.IMPORTOEURO,
    RCONT.VALORECAMBIO,
    RCONT.DESCRIZIONE as DESCRIZIONERIGHE,
    RCONT.DATAVALUTA,
    RCONT.CPARTITA,RCONT.RIGACAUSALE,RCONT.CODCOMMESSA,
    RCONT.CODCAMBIO,
    (SELECT TOP 1 NUMDOC FROM RIGHEIVA WHERE NRREG=TCONT.PROGRESSIVO AND TIPOREGISTRO=TCONT.MOVIVA) NUMDOC,
    (SELECT TOP 1 DATADOC FROM RIGHEIVA WHERE NRREG=TCONT.PROGRESSIVO AND TIPOREGISTRO=TCONT.MOVIVA) DATADOC,
    CAUCONT.Descrizione DescrCauCont, 
    TABCFG.DscConto1,
    (CASE WHEN RCONT.SEGNO=0 then RCONT.IMPORTO else 0 end) as DARE,
    (CASE WHEN RCONT.SEGNO=0 then RCONT.IMPORTOEURO else 0 end) as DAREEURO,
    (CASE WHEN RCONT.SEGNO=0 then RCONT.IMPORTOVALUTA else 0 end) as DAREVALUTA,
    (CASE WHEN RCONT.SEGNO=1 then RCONT.IMPORTO else 0 end) as AVERE,
    (CASE WHEN RCONT.SEGNO=1 then RCONT.IMPORTOEURO else 0 end) as AVEREEURO,
    (CASE WHEN RCONT.SEGNO=1 then RCONT.IMPORTOVALUTA else 0 end) as AVEREVALUTA,
    SUBSTRING('01-GEN02-FEB03-MAR04-APR05-MAG06-GIU07-LUG08-AGO09-SET10-OTT11-NOV12-DIC',(Month(TCONT.DATAREG)-1)*6+1,6) AS Mese    
FROM 
    (RIGHECONTABILITA AS RCONT LEFT OUTER JOIN TESTECONTABILITA AS TCONT ON RCONT.NRREG=TCONT.PROGRESSIVO),
    CAUSALICONTABILI CAUCONT, TABCFG, TABUTENTI
WHERE 
    USERDB = CAST(USER_NAME() AS VARCHAR(25)) 
    AND CAUCONT.CodiceCausale=TCONT.Causale 
    AND TABCFG.CodConto=RCONT.Conto 
    AND (SUPERVISOR = 1 OR (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSICAUSCONT WHERE CODCAUSALE = CAUSALE AND FLAGVISUALIZZA=1)))

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMOVCONTCOMP] TO [Metodo98]
    AS [dbo];

