
CREATE VIEW [dbo].[zzDiffGiorniConsegna]
AS
SELECT     TESTEDOCUMENTI_1.TIPODOC, TESTEDOCUMENTI_1.CODCLIFOR, RIGHEDOCUMENTI_1.DATACONSEGNA AS DCORDINE, 
                      dbo.RIGHEDOCUMENTI.DATACONSEGNA AS DCBOLLA, 
case
when dbo.RIGHEDOCUMENTI.DATACONSEGNA>RIGHEDOCUMENTI_1.DATACONSEGNA then
DATEDIFF(D, RIGHEDOCUMENTI_1.DATACONSEGNA, dbo.RIGHEDOCUMENTI.DATACONSEGNA)
when not(dbo.RIGHEDOCUMENTI.DATACONSEGNA>RIGHEDOCUMENTI_1.DATACONSEGNA) then 0                      
end
AS DIFF, RIGHEDOCUMENTI_1.CODART, dbo.TESTEDOCUMENTI.TIPODOC AS Expr1, dbo.PARAMETRIDOC.TIPO, 
                      RIGHEDOCUMENTI_1.TIPORIGA
FROM         dbo.RIGHEDOCUMENTI AS RIGHEDOCUMENTI_1 INNER JOIN
                      dbo.TESTEDOCUMENTI AS TESTEDOCUMENTI_1 ON RIGHEDOCUMENTI_1.IDTESTA = TESTEDOCUMENTI_1.PROGRESSIVO INNER JOIN
                      dbo.RIGHEDOCUMENTI INNER JOIN
                      dbo.TESTEDOCUMENTI ON dbo.RIGHEDOCUMENTI.IDTESTA = dbo.TESTEDOCUMENTI.PROGRESSIVO ON 
                      RIGHEDOCUMENTI_1.IDTESTA = dbo.RIGHEDOCUMENTI.IDTESTARP AND 
                      RIGHEDOCUMENTI_1.IDRIGA = dbo.RIGHEDOCUMENTI.IDRIGARP INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.TESTEDOCUMENTI.TIPODOC = dbo.PARAMETRIDOC.CODICE
WHERE     (TESTEDOCUMENTI_1.TIPODOC = 'ORC' OR
                      TESTEDOCUMENTI_1.TIPODOC = 'OCR') AND (RIGHEDOCUMENTI_1.CODART <> '') AND (dbo.PARAMETRIDOC.TIPO = 'b') AND 
                      (RIGHEDOCUMENTI_1.TIPORIGA = 'n')


GO
GRANT SELECT
    ON OBJECT::[dbo].[zzDiffGiorniConsegna] TO [Metodo98]
    AS [dbo];

