CREATE TABLE [dbo].[ACQ_RIGHEOFFERTA] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [IDRIGA]         INT             NOT NULL,
    [ARTICOLO]       VARCHAR (50)    NULL,
    [UM]             VARCHAR (3)     NULL,
    [QTAMINIMA]      DECIMAL (16, 6) NULL,
    [PREZZO]         DECIMAL (19, 4) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [NUMLISTINO]     DECIMAL (5)     NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ACQ_RIGHEOFFERTA_TESTAOFFERTA] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[ACQ_TESTAOFFERTA] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ACQ_RIGHEOFFERTA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ACQ_RIGHEOFFERTA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ACQ_RIGHEOFFERTA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ACQ_RIGHEOFFERTA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ACQ_RIGHEOFFERTA] TO [Metodo98]
    AS [dbo];

