CREATE TABLE [dbo].[ALD_STORICOMODIFICHECAMPI] (
    [PROGRESSIVO]    DECIMAL (10)   NOT NULL,
    [NOMETABELLA]    VARCHAR (50)   NULL,
    [IdTesta]        DECIMAL (10)   NULL,
    [NOMECAMPO]      VARCHAR (50)   NULL,
    [CODICE]         NVARCHAR (300) NULL,
    [VALORE]         NVARCHAR (250) NULL,
    [UTENTEMODIFICA] VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]   DATETIME       NOT NULL,
    CONSTRAINT [PK_ALD_STORICOMODIFICHECAMPI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ALD_STORICOMODIFICHECAMPI_IdTesta]
    ON [dbo].[ALD_STORICOMODIFICHECAMPI]([IdTesta] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ALD_STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALD_STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALD_STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];

