CREATE TABLE [dbo].[ALD_TEMP_ANAGRAFICACF] (
    [DATAAZIONE]     DATETIME     NOT NULL,
    [CODCONTO]       VARCHAR (7)  NOT NULL,
    [CODMASTROOLD]   DECIMAL (5)  NULL,
    [CODMASTRONEW]   DECIMAL (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_ALD_TEMP_ANAGRAFICACF] PRIMARY KEY CLUSTERED ([UTENTEMODIFICA] ASC, [DATAMODIFICA] ASC, [CODCONTO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ALD_TEMP_ANAGRAFICACF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALD_TEMP_ANAGRAFICACF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALD_TEMP_ANAGRAFICACF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_TEMP_ANAGRAFICACF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_TEMP_ANAGRAFICACF] TO [Metodo98]
    AS [dbo];

