CREATE TABLE [dbo].[ALLEGATIFATTUREPA] (
    [IDTESTADOC]            DECIMAL (10)  NOT NULL,
    [NRRIGA]                SMALLINT      NOT NULL,
    [NOMEFILEALLEGATO]      VARCHAR (200) NULL,
    [NOMEALLEGATO]          VARCHAR (60)  NULL,
    [ALGORITMOCOMPRESSIONE] VARCHAR (10)  NULL,
    [FORMATOFILE]           VARCHAR (10)  NULL,
    [DESCRIZIONEALLEGATO]   VARCHAR (100) NULL,
    [UTENTEMODIFICA]        VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]          DATETIME      NOT NULL,
    CONSTRAINT [PK_ALLEGATIFATTUREPA] PRIMARY KEY CLUSTERED ([IDTESTADOC] ASC, [NRRIGA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ALLEGATIFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALLEGATIFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALLEGATIFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALLEGATIFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALLEGATIFATTUREPA] TO [Metodo98]
    AS [dbo];

