CREATE TABLE [dbo].[ANACAROPERAZIONI] (
    [OPERAZIONE]     VARCHAR (5)   NOT NULL,
    [NRRIGA]         INT           NOT NULL,
    [VALORE]         VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_ANACAROPERAZIONI] PRIMARY KEY CLUSTERED ([OPERAZIONE] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_ANACAROPERAZIONI" FOR TABLE "ANACAROPERAZIONI"  */
CREATE TRIGGER TI_ANACAROPERAZIONI ON ANACAROPERAZIONI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABELLAOPERAZIONI" MUST EXIST WHEN INSERTING A CHILD IN "ANACAROPERAZIONI"  */
    IF UPDATE(OPERAZIONE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABELLAOPERAZIONI T1, INSERTED T2
           WHERE  T1.CODICE = T2.OPERAZIONE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABELLAOPERAZIONI". Cannot create child in "ANACAROPERAZIONI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_ANACAROPERAZIONI" FOR TABLE "ANACAROPERAZIONI"  */
CREATE TRIGGER TU_ANACAROPERAZIONI ON ANACAROPERAZIONI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABELLAOPERAZIONI" MUST EXIST WHEN UPDATING A CHILD IN "ANACAROPERAZIONI"  */
      IF UPDATE(OPERAZIONE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABELLAOPERAZIONI T1, INSERTED T2
             WHERE  T1.CODICE = T2.OPERAZIONE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABELLAOPERAZIONI" does not exist. Cannot ALTER COLUMN child in "ANACAROPERAZIONI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[ANACAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ANACAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ANACAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ANACAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ANACAROPERAZIONI] TO [Metodo98]
    AS [dbo];

