CREATE TABLE [dbo].[ANAGRAFICAARTICOLIPROD] (
    [CODICEART]            VARCHAR (50)    NOT NULL,
    [ESERCIZIO]            DECIMAL (5)     NOT NULL,
    [SCORTAMIN]            DECIMAL (16, 6) DEFAULT (0) NULL,
    [SCORTAMAX]            DECIMAL (16, 6) DEFAULT (0) NULL,
    [LIVPRODUZIONE]        VARCHAR (1)     NULL,
    [RAGGRPRODUZIONE]      VARCHAR (1)     NULL,
    [LIVPRODPREC]          VARCHAR (1)     NULL,
    [TIPOGESTIONE]         SMALLINT        DEFAULT (0) NULL,
    [LIVRIORDINO]          DECIMAL (16, 6) DEFAULT (0) NULL,
    [PROVENIENZA]          SMALLINT        DEFAULT (0) NULL,
    [ARTALTERNATIVO]       VARCHAR (50)    NULL,
    [QMINRIORDACQ]         DECIMAL (16, 6) DEFAULT (0) NULL,
    [QMAXRIORDACQ]         DECIMAL (16, 6) DEFAULT (0) NULL,
    [QDELTARIORDACQ]       DECIMAL (16, 6) DEFAULT (0) NULL,
    [TAPPRONTACQ]          SMALLINT        NULL,
    [TAPPROVVACQ]          SMALLINT        NULL,
    [LOTTORIFACQ]          DECIMAL (16, 6) DEFAULT (0) NULL,
    [ARROTLOTTOACQ]        SMALLINT        DEFAULT (0) NULL,
    [FORNPREFACQ]          VARCHAR (7)     NULL,
    [QMINRIORDPROD]        DECIMAL (16, 6) DEFAULT (0) NULL,
    [QMAXRIORDPROD]        DECIMAL (16, 6) DEFAULT (0) NULL,
    [QDELTARIORDPROD]      DECIMAL (16, 6) DEFAULT (0) NULL,
    [TAPPRONTPROD]         SMALLINT        NULL,
    [TAPPROVVPROD]         SMALLINT        NULL,
    [LOTTORIFPROD]         DECIMAL (16, 6) DEFAULT (0) NULL,
    [ARROTLOTTOPROD]       SMALLINT        DEFAULT (0) NULL,
    [QMINRIORDLAV]         DECIMAL (16, 6) DEFAULT (0) NULL,
    [QMAXRIORDLAV]         DECIMAL (16, 6) DEFAULT (0) NULL,
    [QDELTARIORDLAV]       DECIMAL (16, 6) DEFAULT (0) NULL,
    [TAPPRONTLAV]          SMALLINT        NULL,
    [TAPPROVVLAV]          SMALLINT        NULL,
    [LOTTORIFLAV]          DECIMAL (16, 6) DEFAULT (0) NULL,
    [ARROTLOTTOLAV]        SMALLINT        DEFAULT (0) NULL,
    [FORNPREFLAV]          VARCHAR (7)     NULL,
    [LOTTORIORDINO]        DECIMAL (16, 6) DEFAULT (0) NULL,
    [UMLOTTOACQ]           VARCHAR (3)     NOT NULL,
    [UMLOTTOPROD]          VARCHAR (3)     NOT NULL,
    [UMLOTTOLAV]           VARCHAR (3)     NOT NULL,
    [UTENTEMODIFICA]       VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]         DATETIME        NOT NULL,
    [TIPOPRODUZIONE]       SMALLINT        NULL,
    [FLOORSTOCK]           SMALLINT        CONSTRAINT [DF_ANAGRAFICAARTICOLIPROD_FLOORSTOCK] DEFAULT (0) NULL,
    [GRUPPOAPPROV]         NUMERIC (5)     NULL,
    [COSTOORDINEACQ]       DECIMAL (19, 6) NULL,
    [COSTOORDINELAV]       DECIMAL (19, 6) NULL,
    [COSTOORDINEPROD]      DECIMAL (19, 6) NULL,
    [FATTORESCOSTAMENTO]   DECIMAL (8, 5)  NULL,
    [TEMPOCOPERTURA]       SMALLINT        NULL,
    [CONSUMOPREVISTO]      DECIMAL (16, 6) NULL,
    [MADPREVISTO]          DECIMAL (16, 6) NULL,
    [FATTORESICUREZZA]     DECIMAL (8, 5)  NULL,
    [TIPOPRODOTTO]         SMALLINT        DEFAULT (1) NOT NULL,
    [GESTIONEMATERIALI]    SMALLINT        DEFAULT (0) NOT NULL,
    [FATTORECOMPRESSIONE]  NUMERIC (8, 5)  NULL,
    [GRUPPOPREVISIONE]     DECIMAL (5)     NULL,
    [FORMULAFRONTIERA]     VARCHAR (255)   NULL,
    [LIVELLOSERVIZIO]      INT             NULL,
    [FLAGMPS]              SMALLINT        CONSTRAINT [DF_ANAGRAFICAARTICOLIPROD_FLAGMPS] DEFAULT (0) NOT NULL,
    [FLAGNETTIFICAMPS]     SMALLINT        CONSTRAINT [DF_ANAGRAFICAARTICOLIPROD_FLAGNETTIFICAMPS] DEFAULT (0) NOT NULL,
    [CODICEMPS]            VARCHAR (50)    NULL,
    [LOTTOFABBRICAZIONE]   DECIMAL (16, 6) NULL,
    [UMLOTTOFABBRICAZIONE] VARCHAR (3)     NULL,
    [KS_GGScadenza]        INT             DEFAULT (0) NULL,
    [INTERVALLOPIANIF]     SMALLINT        NULL,
    [DATAULTANALISI]       DATETIME        NULL,
    [GGORIZZONTEDISP]      SMALLINT        NULL,
    [FlgLottoPeriodoCoper] SMALLINT        CONSTRAINT [DF_ANAGRAFICAARTICOLIPROD_FLGLOTTOPERIODOCOPER] DEFAULT ((0)) NOT NULL,
    [GGPeriodoCoper]       SMALLINT        CONSTRAINT [DF_ANAGRAFICAARTICOLIPROD_GGPERIODOCOPER] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ANAGRAFICAARTICOLIPROD] PRIMARY KEY CLUSTERED ([CODICEART] ASC, [ESERCIZIO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_GESTIONEMATERIALI] CHECK ([GESTIONEMATERIALI] = 1 or [GESTIONEMATERIALI] = 0),
    CONSTRAINT [CHK_TIPOPRODOTTO] CHECK ([TIPOPRODOTTO] = 2 or [TIPOPRODOTTO] = 1 or [TIPOPRODOTTO] = 0)
);


GO

/*  INSERT TRIGGER "TI_ANAGRAFICAARTICOLIPROD" FOR TABLE "ANAGRAFICAARTICOLIPROD"  */
CREATE TRIGGER TI_ANAGRAFICAARTICOLIPROD ON ANAGRAFICAARTICOLIPROD FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN INSERTING A CHILD IN "ANAGRAFICAARTICOLIPROD"  */
    IF UPDATE(CODICEART)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ANAGRAFICAARTICOLI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODICEART) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ANAGRAFICAARTICOLI". Cannot create child in "ANAGRAFICAARTICOLIPROD".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_ANAGRAFICAARTICOLIPROD" FOR TABLE "ANAGRAFICAARTICOLIPROD"  */
CREATE TRIGGER TU_ANAGRAFICAARTICOLIPROD ON ANAGRAFICAARTICOLIPROD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN UPDATING A CHILD IN "ANAGRAFICAARTICOLIPROD"  */
      IF UPDATE(CODICEART)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   ANAGRAFICAARTICOLI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODICEART) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"ANAGRAFICAARTICOLI" does not exist. Cannot modify child in "ANAGRAFICAARTICOLIPROD".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[ANAGRAFICAARTICOLIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ANAGRAFICAARTICOLIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ANAGRAFICAARTICOLIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ANAGRAFICAARTICOLIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ANAGRAFICAARTICOLIPROD] TO [Metodo98]
    AS [dbo];

