CREATE TABLE [dbo].[ANAGRAFICAGENERICI] (
    [CODCONTO]              VARCHAR (7)   NOT NULL,
    [DSCCONTO1]             VARCHAR (80)  NULL,
    [CODMASTRO]             DECIMAL (5)   NOT NULL,
    [DATAINIVALIDITA]       DATETIME      NOT NULL,
    [DATAFINEVALIDITA]      DATETIME      NOT NULL,
    [NOTE]                  VARCHAR (255) NULL,
    [NOTE1]                 VARCHAR (255) NULL,
    [UTENTEMODIFICA]        VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]          DATETIME      NOT NULL,
    [FLGRATEIRISCONTI]      SMALLINT      CONSTRAINT [DF_ANAGRAFICAGENERICI_FLGRATEIRISCONTI] DEFAULT (0) NULL,
    [GESTPARTITE]           SMALLINT      NULL,
    [CtrlQuadCdC]           SMALLINT      DEFAULT (0) NULL,
    [UTILIZZOINGOLD]        SMALLINT      NULL,
    [TIPOSPESASANITARIA]    VARCHAR (2)   NULL,
    [FLGTIPOSPESASANITARIA] SMALLINT      NULL,
    CONSTRAINT [PK_ANAGRAFICAGENERICI] PRIMARY KEY CLUSTERED ([CODCONTO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [ANAGRAFICAGENERICI_CtrlQuadCdC_CHK] CHECK ([CtrlQuadCdC] = 1 or [CtrlQuadCdC] = 0),
    CONSTRAINT [CHK_ANAGRAFICAGENERICI_FLGTIPOSPESASANITARIA] CHECK ([FLGTIPOSPESASANITARIA]=(2) OR [FLGTIPOSPESASANITARIA]=(1) OR [FLGTIPOSPESASANITARIA]=(0)),
    CONSTRAINT [CHK_ANAGRAFICAGENERICI_GESTPARTITE] CHECK ([GESTPARTITE] = 1 or [GESTPARTITE] = 0),
    CONSTRAINT [CHK_ANAGRAFICAGENERICI_UTILIZZOINGOLD] CHECK ([UTILIZZOINGOLD]=(1) OR [UTILIZZOINGOLD]=(0)),
    CONSTRAINT [FK_ANAGRAFICAGENERICI_CODMASTRO] FOREIGN KEY ([CODMASTRO]) REFERENCES [dbo].[TABMASTRI] ([CODICE])
);


GO
CREATE NONCLUSTERED INDEX [CODMASTRO4]
    ON [dbo].[ANAGRAFICAGENERICI]([CODMASTRO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [DSCGENERICO]
    ON [dbo].[ANAGRAFICAGENERICI]([DSCCONTO1] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ANAGRAFICAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ANAGRAFICAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ANAGRAFICAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ANAGRAFICAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ANAGRAFICAGENERICI] TO [Metodo98]
    AS [dbo];

