CREATE TABLE [dbo].[ANAGRAFICAAUTOMEZZI] (
    [CODICE]                DECIMAL (10)    NOT NULL,
    [DESCRIZIONE]           VARCHAR (25)    NULL,
    [TARGA]                 VARCHAR (10)    NULL,
    [PROPRIETARIO]          VARCHAR (7)     NULL,
    [AUTISTA]               VARCHAR (25)    NULL,
    [LUOGOPARTENZA]         VARCHAR (100)   NULL,
    [LARGHEZZA]             DECIMAL (16, 6) NULL,
    [ALTEZZA]               DECIMAL (16, 6) NULL,
    [PROFONDITA]            DECIMAL (16, 6) NULL,
    [CARICOMAX]             DECIMAL (16, 6) NULL,
    [ORAPARTENZA]           DATETIME        NULL,
    [ORAARRIVO]             DATETIME        NULL,
    [DURATASOSTA]           DECIMAL (5)     NULL,
    [DURATAGUIDA]           DECIMAL (5)     NULL,
    [VELOCITAAUTOSTRADE]    SMALLINT        NULL,
    [VELOCITASUPERSTRADE]   SMALLINT        NULL,
    [VELOCITASTATALI]       SMALLINT        NULL,
    [VELOCITAPROVINCIALI]   SMALLINT        NULL,
    [VELOCITAURBANE]        SMALLINT        NULL,
    [CONSUMIAUTOSTRADA]     SMALLINT        NULL,
    [CONSUMICITTA]          SMALLINT        NULL,
    [FLAGCOSTOVIAGGIO]      SMALLINT        NULL,
    [COSTOUNITARIO]         DECIMAL (19, 4) NULL,
    [FLAGCALCOLOITINERARIO] SMALLINT        NULL,
    [PREFAUTOSTRADE]        SMALLINT        NULL,
    [PREFSUPERSTRADE]       SMALLINT        NULL,
    [PREFSTATALI]           SMALLINT        NULL,
    [PREFPROVINCIALI]       SMALLINT        NULL,
    [PREFTRAGHETTI]         SMALLINT        NULL,
    [NOTE]                  VARCHAR (100)   NULL,
    [UTENTEMODIFICA]        VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]          DATETIME        NOT NULL,
    CONSTRAINT [PK_ANAGRAFICAAUTOMEZZI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ANAGRAFICAAUTOMEZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ANAGRAFICAAUTOMEZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ANAGRAFICAAUTOMEZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ANAGRAFICAAUTOMEZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ANAGRAFICAAUTOMEZZI] TO [Metodo98]
    AS [dbo];

