CREATE TABLE [dbo].[ARTICOLIFATTORICONVERSIONE] (
    [CODART]         VARCHAR (50)     NOT NULL,
    [UM1]            VARCHAR (3)      NOT NULL,
    [UM2]            VARCHAR (3)      NOT NULL,
    [FORMULAFC]      VARCHAR (255)    NULL,
    [FATTORE]        DECIMAL (20, 10) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)     NOT NULL,
    [DATAMODIFICA]   DATETIME         NOT NULL,
    CONSTRAINT [PK_ARTICOLIFATTORICONVERSIONE] PRIMARY KEY CLUSTERED ([CODART] ASC, [UM1] ASC, [UM2] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_ARTICOLIFATTORICONVERSIONE" FOR TABLE "ARTICOLIFATTORICONVERSIONE"  */
CREATE TRIGGER TI_ARTICOLIFATTORICONVERSIONE ON ARTICOLIFATTORICONVERSIONE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "ARTICOLIUNITAMISURA" MUST EXIST WHEN INSERTING A CHILD IN "ARTICOLIFATTORICONVERSIONE"  */
    IF UPDATE(CODART) OR
       UPDATE(UM1)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ARTICOLIUNITAMISURA T1, INSERTED T2
           WHERE  T1.CODART = T2.CODART
            AND   T1.UM = T2.UM1) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ARTICOLIUNITAMISURA". Cannot create child in "ARTICOLIFATTORICONVERSIONE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_ARTICOLIFATTORICONVERSIONE" FOR TABLE "ARTICOLIFATTORICONVERSIONE"  */
CREATE TRIGGER TU_ARTICOLIFATTORICONVERSIONE ON ARTICOLIFATTORICONVERSIONE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "ARTICOLIUNITAMISURA" MUST EXIST WHEN UPDATING A CHILD IN "ARTICOLIFATTORICONVERSIONE"  */
      IF UPDATE(CODART) OR
         UPDATE(UM1)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   ARTICOLIUNITAMISURA T1, INSERTED T2
             WHERE  T1.CODART = T2.CODART
              AND   T1.UM = T2.UM1) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"ARTICOLIUNITAMISURA" does not exist. Cannot modify child in "ARTICOLIFATTORICONVERSIONE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[ARTICOLIFATTORICONVERSIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ARTICOLIFATTORICONVERSIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ARTICOLIFATTORICONVERSIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ARTICOLIFATTORICONVERSIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ARTICOLIFATTORICONVERSIONE] TO [Metodo98]
    AS [dbo];

