CREATE TABLE [dbo].[ARTICOLIUNITAMISURA] (
    [CODART]         VARCHAR (50) NOT NULL,
    [UM]             VARCHAR (3)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_ARTICOLIUNITAMISURA] PRIMARY KEY CLUSTERED ([CODART] ASC, [UM] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [UM]
    ON [dbo].[ARTICOLIUNITAMISURA]([UM] ASC) WITH (FILLFACTOR = 90);


GO

/*  DELETE TRIGGER "TD_ARTICOLIUNITAMISURA" FOR TABLE "ARTICOLIUNITAMISURA"  */
CREATE TRIGGER TD_ARTICOLIUNITAMISURA ON ARTICOLIUNITAMISURA FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "ARTICOLIUMPREFERITE"  */
    DELETE ARTICOLIUMPREFERITE
    FROM   ARTICOLIUMPREFERITE T2, DELETED T1
    WHERE  T2.CODART = T1.CODART
     AND   T2.UM = T1.UM
    
    /*  DELETE ALL CHILDREN IN "ARTICOLIFATTORICONVERSIONE"  */
    DELETE ARTICOLIFATTORICONVERSIONE
    FROM   ARTICOLIFATTORICONVERSIONE T2, DELETED T1
    WHERE  T2.CODART = T1.CODART
     AND   T2.UM1 = T1.UM

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  INSERT TRIGGER "TI_ARTICOLIUNITAMISURA" FOR TABLE "ARTICOLIUNITAMISURA"  */
CREATE TRIGGER TI_ARTICOLIUNITAMISURA ON ARTICOLIUNITAMISURA FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN INSERTING A CHILD IN "ARTICOLIUNITAMISURA"  */
    IF UPDATE(CODART)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ANAGRAFICAARTICOLI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODART) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ANAGRAFICAARTICOLI". Cannot create child in "ARTICOLIUNITAMISURA".'
             GOTO ERROR
          END
    END
    
    /*  PARENT "TABUNITAMISURA" MUST EXIST WHEN INSERTING A CHILD IN "ARTICOLIUNITAMISURA"  */
    IF UPDATE(UM)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABUNITAMISURA T1, INSERTED T2
           WHERE  T1.CODICE = T2.UM) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABUNITAMISURA". Cannot create child in "ARTICOLIUNITAMISURA".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

--end

-- INIZIO A#10970
/*  UPDATE TRIGGER "TU_ARTICOLIUNITAMISURA" FOR TABLE "ARTICOLIUNITAMISURA"  */
CREATE TRIGGER [dbo].[TU_ARTICOLIUNITAMISURA] ON [dbo].[ARTICOLIUNITAMISURA] FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN UPDATING A CHILD IN "ARTICOLIUNITAMISURA"  */
      IF UPDATE(CODART)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   ANAGRAFICAARTICOLI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODART) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"ANAGRAFICAARTICOLI" does not exist. Cannot modify child in "ARTICOLIUNITAMISURA".'
               GOTO ERROR
            END
      END
      
      /*  PARENT "TABUNITAMISURA" MUST EXIST WHEN UPDATING A CHILD IN "ARTICOLIUNITAMISURA"  */
      IF UPDATE(UM)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABUNITAMISURA T1, INSERTED T2
             WHERE  T1.CODICE = T2.UM) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABUNITAMISURA" does not exist. Cannot modify child in "ARTICOLIUNITAMISURA".'
               GOTO ERROR
            END
      END


      /*  DELETE ALL CHILDREN IN "ARTICOLIFATTORICONVERSIONE" OF OLD UM */
      IF UPDATE(UM)
      BEGIN
        DELETE ARTICOLIFATTORICONVERSIONE
        FROM   ARTICOLIFATTORICONVERSIONE T2, DELETED T1
        WHERE  T2.CODART = T1.CODART
         AND   T2.UM1 = T1.UM
      
      END
      RETURN

/*  ERRORS HANDLING  */
ERROR:
    raiserror (@errmsg, 1, 1)
    ROLLBACK  TRANSACTION
END
-- FINE A#10970

GO
GRANT DELETE
    ON OBJECT::[dbo].[ARTICOLIUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ARTICOLIUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ARTICOLIUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ARTICOLIUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ARTICOLIUNITAMISURA] TO [Metodo98]
    AS [dbo];

