CREATE TABLE [dbo].[BiriHelp_SEzionicontratto] (
    [IDCONTRATTO]             VARCHAR (13)    NOT NULL,
    [SEZIONECONTRATTO]        DECIMAL (5)     NOT NULL,
    [OLD_RifSezioneGemma]     VARCHAR (13)    NOT NULL,
    [CODDEST]                 DECIMAL (5)     NOT NULL,
    [DESCRIZIONESEZIONE]      VARCHAR (80)    NULL,
    [idTipoFatt]              DECIMAL (5)     NOT NULL,
    [idTipologMezzo]          DECIMAL (5)     NOT NULL,
    [IdStrutturaOpPr]         DECIMAL (5)     NOT NULL,
    [Revisione]               DECIMAL (5)     NOT NULL,
    [CodiceMezzo]             VARCHAR (50)    NOT NULL,
    [CodTecnicoRisorsa]       VARCHAR (7)     NULL,
    [PAGAMENTO]               VARCHAR (4)     NULL,
    [DATAPVISITA]             DATETIME        NULL,
    [FLG_OperDeroga]          VARCHAR (4)     NULL,
    [NrOperazInDeroga]        DECIMAL (5)     NOT NULL,
    [CadenzeInDeroga]         DECIMAL (5)     NOT NULL,
    [NOTE]                    NTEXT           NULL,
    [NOTE_TECNICO]            NTEXT           NULL,
    [REFERENTE]               VARCHAR (50)    NULL,
    [TEL_REF]                 VARCHAR (50)    NULL,
    [DATAMODIFICA]            DATETIME        NOT NULL,
    [UTENTEMODIFICA]          NVARCHAR (25)   NOT NULL,
    [FLAG_ELIMINATO]          VARCHAR (1)     NULL,
    [DATAEliminato]           DATETIME        NULL,
    [RESP_MANU]               VARCHAR (50)    NULL,
    [RESP_CONTR]              VARCHAR (50)    NULL,
    [TIPO_PIATTAFORMA]        VARCHAR (3)     NULL,
    [REPARTO]                 VARCHAR (50)    NULL,
    [ORE_INT]                 DECIMAL (10, 2) NULL,
    [GIORNI_PIATT]            DECIMAL (6, 2)  NULL,
    [flg_mat_dafatt]          CHAR (1)        NULL,
    [FLG_RIC_SCA_AUTO]        CHAR (1)        NULL,
    [RIFCLIENTE]              VARCHAR (50)    NULL,
    [EMAIL_RESPONSABILE]      VARCHAR (100)   NULL,
    [FLGUSAPRZGEMMA]          CHAR (1)        NULL,
    [idGListinoContr]         DECIMAL (10)    NULL,
    [FLAG_PROV]               CHAR (1)        NULL,
    [CodSezioniAggregate]     DECIMAL (5)     NULL,
    [SezioneAggrPrimaria]     SMALLINT        NULL,
    [ImportoContrattoSezione] NUMERIC (10, 2) NULL,
    [Provvigione1]            NUMERIC (10, 2) NULL,
    [ImportoVisita]           NUMERIC (10, 2) NULL,
    [NrVisiteTot]             NUMERIC (10, 2) NULL,
    [SEZIONECONTRATTO_Prec]   DECIMAL (5)     NULL,
    [IdDivisione]             SMALLINT        NULL,
    [Periodicita]             VARCHAR (30)    NULL,
    [FlgOblLetturaNote]       SMALLINT        NOT NULL,
    [FlgOblPiattaforma]       SMALLINT        NULL,
    [FlgPrevistoAllegato]     SMALLINT        NULL,
    [CodIva]                  DECIMAL (5)     NULL,
    [CodAgente2]              VARCHAR (7)     NULL,
    [PROVVAg2]                DECIMAL (10, 2) NULL,
    [RifLinkImmagine]         VARCHAR (300)   NULL,
    [CodiceEdificio]          VARCHAR (30)    NULL,
    [CodiceLivello]           VARCHAR (50)    NULL,
    [CodiceVano]              VARCHAR (50)    NULL,
    [PosizioneMappa]          VARCHAR (50)    NULL,
    [CodiceBarre]             VARCHAR (50)    NULL,
    [TipologiaBarre]          SMALLINT        NULL,
    [Flag_SezAggr]            SMALLINT        NOT NULL,
    [FLG_ProvvExtraContratto] CHAR (1)        NULL,
    [Provv1Materiali]         NUMERIC (10, 2) NULL,
    [Provv1OreAdd]            NUMERIC (10, 2) NULL,
    [FLG_AttRipristCompr]     CHAR (1)        NULL,
    [ValoreSogliaRiprist]     NUMERIC (10, 2) NULL,
    [NrTecniciPrev]           NUMERIC (5)     NULL,
    [FLG_AmbientiConf]        SMALLINT        NULL,
    [FLG_LavoriInQuota]       SMALLINT        NULL
);

