CREATE TABLE [dbo].[CAROPERAZIONEFASE] (
    [PROGRESSIVO]    DECIMAL (10)  NOT NULL,
    [NUMEROFASE]     INT           NOT NULL,
    [POSIZIONE]      INT           NOT NULL,
    [VALORE]         VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NULL,
    [DATAMODIFICA]   DATETIME      NULL,
    CONSTRAINT [CAROPERAZIONEFASE_PK] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC, [NUMEROFASE] ASC, [POSIZIONE] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_CAROPERAZIONEFASE" FOR TABLE "CAROPERAZIONEFASE"  */
CREATE TRIGGER TI_CAROPERAZIONEFASE ON CAROPERAZIONEFASE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "RIGHECICLOPROD" MUST EXIST WHEN INSERTING A CHILD IN "CAROPERAZIONEFASE"  */
    IF UPDATE(PROGRESSIVO) OR
       UPDATE(NUMEROFASE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   RIGHECICLOPROD T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO
            AND   T1.NUMEROFASE = T2.NUMEROFASE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "RIGHECICLOPROD". Cannot create child in "CAROPERAZIONEFASE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_CAROPERAZIONEFASE" FOR TABLE "CAROPERAZIONEFASE"  */
CREATE TRIGGER TU_CAROPERAZIONEFASE ON CAROPERAZIONEFASE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "RIGHECICLOPROD" MUST EXIST WHEN UPDATING A CHILD IN "CAROPERAZIONEFASE"  */
      IF UPDATE(PROGRESSIVO) OR
         UPDATE(NUMEROFASE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   RIGHECICLOPROD T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO
              AND   T1.NUMEROFASE = T2.NUMEROFASE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"RIGHECICLOPROD" does not exist. Cannot modify child in "CAROPERAZIONEFASE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[CAROPERAZIONEFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CAROPERAZIONEFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CAROPERAZIONEFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CAROPERAZIONEFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CAROPERAZIONEFASE] TO [Metodo98]
    AS [dbo];

