CREATE TABLE [dbo].[CATALOGOPRODOTTI] (
    [ID_PRODOTTO]       VARCHAR (50)    NOT NULL,
    [ALLEGATO]          VARCHAR (255)   NOT NULL,
    [DESCRIZIONE]       VARCHAR (255)   NULL,
    [MACROCATEGORIA_ID] DECIMAL (5)     NULL,
    [CATEGORIA_ID]      DECIMAL (5)     NULL,
    [UM]                VARCHAR (3)     NULL,
    [PREZZO_UNITARIO]   DECIMAL (19, 6) NULL,
    [PREZZO_UNIT_EURO]  DECIMAL (19, 6) NULL,
    [PEZZI_CONFEZIONE]  DECIMAL (5)     NULL,
    [NUOVA_ENTRATA]     SMALLINT        DEFAULT (0) NULL,
    [IN_ESAURIMENTO]    SMALLINT        DEFAULT (0) NULL,
    [GIACENZA]          DECIMAL (16, 6) NULL,
    [SCONTO]            DECIMAL (8, 5)  NULL,
    [INIZIO_OFFERTA]    DATETIME        NULL,
    [IMGFILE]           VARCHAR (100)   NULL,
    [FINE_OFFERTA]      DATETIME        NULL,
    [PUBBLICA]          SMALLINT        DEFAULT (0) NULL,
    [MODINS]            SMALLINT        DEFAULT (0) NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [TIPOLOGIA]         SMALLINT        DEFAULT (0) NULL,
    [BARCODE]           VARCHAR (50)    NULL,
    [CHKEURO]           SMALLINT        DEFAULT (0) NULL,
    [CHKLIRE]           SMALLINT        DEFAULT (0) NULL,
    PRIMARY KEY CLUSTERED ([ID_PRODOTTO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHKEURO1] CHECK ([CHKEURO] = 0 or [CHKEURO] = 1),
    CONSTRAINT [CHKLIRE1] CHECK ([CHKLIRE] = 0 or [CHKLIRE] = 1),
    CONSTRAINT [CKC_IN_ESAURIMENTO] CHECK ([IN_ESAURIMENTO] = 0 or [IN_ESAURIMENTO] = 1),
    CONSTRAINT [CKC_MODINS] CHECK ([MODINS] = 0 or [MODINS] = 1),
    CONSTRAINT [CKC_NUOVA_ENTRATA] CHECK ([NUOVA_ENTRATA] = 0 or [NUOVA_ENTRATA] = 1),
    CONSTRAINT [CKC_PUBBLICA] CHECK ([PUBBLICA] = 0 or [PUBBLICA] = 1)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATALOGOPRODOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATALOGOPRODOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATALOGOPRODOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATALOGOPRODOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATALOGOPRODOTTI] TO [Metodo98]
    AS [dbo];

