CREATE TABLE [dbo].[CATALOGO_PARAMETRI] (
    [PROGRESSIVO]          SMALLINT     NOT NULL,
    [TIPOCREAZIONECODICE]  SMALLINT     DEFAULT ((1)) NOT NULL,
    [CODCONTATORE]         DECIMAL (5)  DEFAULT ((0)) NOT NULL,
    [LUNGHEZZACODICE]      SMALLINT     DEFAULT ((0)) NOT NULL,
    [CARATTERERIEMPIMENTO] CHAR (1)     DEFAULT ('') NOT NULL,
    [UTENTEMODIFICA]       VARCHAR (25) NOT NULL,
    [DATAMODIFICA]         DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATALOGO_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATALOGO_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATALOGO_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATALOGO_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATALOGO_PARAMETRI] TO [Metodo98]
    AS [dbo];

