CREATE TABLE [dbo].[CATALOGO_FILTRI_CATALOGO] (
    [CODFORNITORE]    INT          NOT NULL,
    [CODCATALOGO]     INT          NOT NULL,
    [REVISIONE]       SMALLINT     NOT NULL,
    [TIPO]            SMALLINT     NOT NULL,
    [FLAGABILITATO]   SMALLINT     NOT NULL,
    [NRLISTINOMETODO] DECIMAL (5)  DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODFORNITORE] ASC, [CODCATALOGO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATALOGO_FILTRI_CATALOGO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATALOGO_FILTRI_CATALOGO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATALOGO_FILTRI_CATALOGO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATALOGO_FILTRI_CATALOGO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATALOGO_FILTRI_CATALOGO] TO [Metodo98]
    AS [dbo];

