CREATE TABLE [dbo].[CATALOGO_ACCESSI_UTENTE] (
    [ID]             INT          NOT NULL,
    [CODTIPO]        INT          NOT NULL,
    [USERDB]         VARCHAR (25) NOT NULL,
    [FLAGABILITA]    SMALLINT     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC, [CODTIPO] ASC, [USERDB] ASC),
    CONSTRAINT [FK_CATALOGO_ACCESSI_UTENTE_CATALOGO_TIPI_ENTITA] FOREIGN KEY ([CODTIPO]) REFERENCES [dbo].[CATALOGO_TIPI_ENTITA] ([CODICE]) ON DELETE CASCADE,
    CONSTRAINT [FK_CATALOGO_ACCESSI_UTENTE_TABUTENTI] FOREIGN KEY ([USERDB]) REFERENCES [dbo].[TABUTENTI] ([USERDB]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_UTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_UTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_UTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_UTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_UTENTE] TO [Metodo98]
    AS [dbo];

