CREATE TABLE [dbo].[CATALOGO_SCONTI] (
    [IDDISCOUNTTYPE] INT          NOT NULL,
    [CODSCONTO]      VARCHAR (5)  NOT NULL,
    [POSIZIONE]      INT          NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([IDDISCOUNTTYPE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATALOGO_SCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATALOGO_SCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATALOGO_SCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATALOGO_SCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATALOGO_SCONTI] TO [Metodo98]
    AS [dbo];

