CREATE TABLE [dbo].[CATEGORIECF] (
    [CODCATEGORIA]   DECIMAL (5)    NOT NULL,
    [DSCCATEGORIA]   VARCHAR (25)   NULL,
    [NOTE]           VARCHAR (100)  NULL,
    [UTENTEMODIFICA] VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]   DATETIME       NOT NULL,
    [Budget]         DECIMAL (4, 2) CONSTRAINT [DF_CATEGORIECF_BUDGET] DEFAULT (0) NULL,
    [exportCRM]      SMALLINT       DEFAULT ((0)) NULL,
    CONSTRAINT [PK_CATEGORIECF] PRIMARY KEY CLUSTERED ([CODCATEGORIA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [DSCCAT]
    ON [dbo].[CATEGORIECF]([DSCCATEGORIA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATEGORIECF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATEGORIECF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATEGORIECF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATEGORIECF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATEGORIECF] TO [Metodo98]
    AS [dbo];

