CREATE TABLE [dbo].[CAUSALICONTABILI] (
    [CODICECAUSALE]       DECIMAL (5)   NOT NULL,
    [DESCRIZIONE]         VARCHAR (80)  NULL,
    [NRREGISTRO]          DECIMAL (5)   NULL,
    [SCADENZE]            SMALLINT      DEFAULT (0) NOT NULL,
    [NOTAACCRADD]         DECIMAL (5)   NULL,
    [NOTE]                VARCHAR (255) NULL,
    [INVALUTA]            SMALLINT      DEFAULT (0) NULL,
    [RIPCDC]              SMALLINT      DEFAULT (0) NOT NULL,
    [COMPETENZE]          SMALLINT      DEFAULT (0) NOT NULL,
    [NRGIORNALE]          DECIMAL (5)   NULL,
    [CAUSCOLLEGATA]       DECIMAL (5)   NULL,
    [SCADOBBL]            SMALLINT      DEFAULT (0) NULL,
    [CDCOBBL]             SMALLINT      DEFAULT (0) NULL,
    [COMPOBBL]            SMALLINT      DEFAULT (0) NULL,
    [QSCADOBBL]           SMALLINT      DEFAULT (0) NULL,
    [QCDCOBBL]            SMALLINT      DEFAULT (0) NULL,
    [QCOMPOBBL]           SMALLINT      DEFAULT (0) NULL,
    [CONTNACCR]           SMALLINT      DEFAULT (0) NULL,
    [GESTRITACC]          SMALLINT      DEFAULT (0) NULL,
    [CAUSALEAUTOMATICA]   SMALLINT      DEFAULT (0) NULL,
    [CODCAUSCOMMCLI]      SMALLINT      DEFAULT (0) NULL,
    [DATAINIVALIDITA]     DATETIME      NOT NULL,
    [DATAFINEVALIDITA]    DATETIME      NOT NULL,
    [VISDSCCONTO]         SMALLINT      DEFAULT (0) NULL,
    [VISDSCRIGA]          SMALLINT      DEFAULT (0) NULL,
    [VISIMPEURO]          SMALLINT      DEFAULT (0) NULL,
    [VISIMPLIRE]          SMALLINT      DEFAULT (0) NULL,
    [VISNUMFATT]          SMALLINT      DEFAULT (0) NULL,
    [VISNUMPART]          SMALLINT      DEFAULT (0) NULL,
    [VISDTFATT]           SMALLINT      DEFAULT (0) NULL,
    [VISDTVAL]            SMALLINT      DEFAULT (0) NULL,
    [VISRIFCOMMCLI]       SMALLINT      DEFAULT (0) NULL,
    [UTENTEMODIFICA]      VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]        DATETIME      NOT NULL,
    [CodCausMovCes]       DECIMAL (5)   DEFAULT (0) NULL,
    [FLGRATEIRISCONTI]    SMALLINT      CONSTRAINT [DF_CAUSALICONTABILI_FLGRATEIRISCONTI] DEFAULT (0) NULL,
    [CODCONTORR]          VARCHAR (7)   CONSTRAINT [DF_CAUSALICONTABILI_CODCONTORR] DEFAULT ('') NULL,
    [GESTPARTITEGENERICI] SMALLINT      NULL,
    [GESTIVASOSP]         SMALLINT      NULL,
    [UTILIZZOINGOLD]      SMALLINT      NULL,
    [GESTRICONEC]         SMALLINT      NULL,
    [CODCAUSABIEC]        VARCHAR (5)   NULL,
    [GGSTESSABANCAEC]     SMALLINT      CONSTRAINT [DF_CAUSALICONTABILI_GGSTESSABANCAEC] DEFAULT ((0)) NULL,
    [GGALTRABANCAEC]      SMALLINT      CONSTRAINT [DF_CAUSALICONTABILI_GGALTRABANCAEC] DEFAULT ((0)) NULL,
    [CODCALENDARIOEC]     DECIMAL (5)   CONSTRAINT [DF_CAUSALICONTABILI_CODCALENDARIOEC] DEFAULT ((0)) NULL,
    [TIPODOCDF]           VARCHAR (4)   NULL,
    [REGIVAVENDINTEGR]    DECIMAL (5)   NULL,
    CONSTRAINT [PK_CAUSALICONTABILI] PRIMARY KEY CLUSTERED ([CODICECAUSALE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_CAUSALICONTABILI_GESTIVASOSP] CHECK ([GESTIVASOSP]=(1) OR [GESTIVASOSP]=(0)),
    CONSTRAINT [CHK_CAUSALICONTABILI_GESTRICONEC] CHECK ([GESTRICONEC]=(1) OR [GESTRICONEC]=(0)),
    CONSTRAINT [CHK_CAUSALICONTABILI_UTILIZZOINGOLD] CHECK ([UTILIZZOINGOLD]=(1) OR [UTILIZZOINGOLD]=(0)),
    CONSTRAINT [CKC_CAUSALEAUTOMATICA_CAUSALIC] CHECK ([CAUSALEAUTOMATICA] = 0 or [CAUSALEAUTOMATICA] = 1),
    CONSTRAINT [CKC_CDCOBBL_CAUSALIC] CHECK ([CDCOBBL] = 0 or [CDCOBBL] = 1),
    CONSTRAINT [CKC_CODCAUSCOMMCLI_CAUSALIC] CHECK ([CODCAUSCOMMCLI] = 0 or [CODCAUSCOMMCLI] = 1),
    CONSTRAINT [CKC_COMPOBBL_CAUSALIC] CHECK ([COMPOBBL] = 0 or [COMPOBBL] = 1),
    CONSTRAINT [CKC_INVALUTA_CAUSALIC] CHECK ([INVALUTA] = 0 or [INVALUTA] = 1),
    CONSTRAINT [CKC_QCDCOBBL_CAUSALIC] CHECK ([QCDCOBBL] = 0 or [QCDCOBBL] = 1),
    CONSTRAINT [CKC_QCOMPOBBL_CAUSALIC] CHECK ([QCOMPOBBL] = 0 or [QCOMPOBBL] = 1),
    CONSTRAINT [CKC_QSCADOBBL_CAUSALIC] CHECK ([QSCADOBBL] = 0 or [QSCADOBBL] = 1),
    CONSTRAINT [CKC_SCADOBBL_CAUSALIC] CHECK ([SCADOBBL] = 0 or [SCADOBBL] = 1),
    CONSTRAINT [CKC_VISDSCCONTO_CAUSALIC] CHECK ([VISDSCCONTO] = 0 or [VISDSCCONTO] = 1),
    CONSTRAINT [CKC_VISDSCRIGA_CAUSALIC] CHECK ([VISDSCRIGA] = 0 or [VISDSCRIGA] = 1),
    CONSTRAINT [CKC_VISDTFATT_CAUSALIC] CHECK ([VISDTFATT] = 0 or [VISDTFATT] = 1),
    CONSTRAINT [CKC_VISDTVAL_CAUSALIC] CHECK ([VISDTVAL] = 0 or [VISDTVAL] = 1),
    CONSTRAINT [CKC_VISIMPEURO_CAUSALIC] CHECK ([VISIMPEURO] = 0 or [VISIMPEURO] = 1),
    CONSTRAINT [CKC_VISIMPLIRE_CAUSALIC] CHECK ([VISIMPLIRE] = 0 or [VISIMPLIRE] = 1),
    CONSTRAINT [CKC_VISNUMFATT_CAUSALIC] CHECK ([VISNUMFATT] = 0 or [VISNUMFATT] = 1),
    CONSTRAINT [CKC_VISNUMPART_CAUSALIC] CHECK ([VISNUMPART] = 0 or [VISNUMPART] = 1),
    CONSTRAINT [CKC_VISRIFCOMMCLI_CAUSALIC] CHECK ([VISRIFCOMMCLI] = 0 or [VISRIFCOMMCLI] = 1)
);


GO
CREATE NONCLUSTERED INDEX [DSCCAUSALE]
    ON [dbo].[CAUSALICONTABILI]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CAUSALICONTABILI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CAUSALICONTABILI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CAUSALICONTABILI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CAUSALICONTABILI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CAUSALICONTABILI] TO [Metodo98]
    AS [dbo];

