CREATE TABLE [dbo].[CCBILANCIOCONSCOSTIMATERIALE] (
    [IDCOMMCLI]          DECIMAL (10)    NOT NULL,
    [NRRIGA]             INT             NOT NULL,
    [IDTESTADOC]         DECIMAL (10)    NULL,
    [IDRIGADOC]          INT             NULL,
    [IDTESTAFATT]        DECIMAL (10)    NULL,
    [IDRIGAFATT]         INT             NULL,
    [CODART]             VARCHAR (50)    NULL,
    [UMBASE]             VARCHAR (3)     NULL,
    [QUANTITA]           DECIMAL (16, 6) DEFAULT (0) NULL,
    [UMVAL]              VARCHAR (3)     NULL,
    [QTAVAL]             DECIMAL (16, 6) DEFAULT (0) NULL,
    [COSTOUNITARIO]      DECIMAL (19, 4) DEFAULT (0) NULL,
    [NATURARILEVAZIONE]  SMALLINT        NULL,
    [TIPOREC]            VARCHAR (2)     NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [VOCEBASE]           VARCHAR (3)     DEFAULT ('') NULL,
    [IDVOCE]             VARCHAR (3)     DEFAULT ('') NULL,
    [COSTOUNITARIOEURO]  DECIMAL (19, 4) CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_COSTOUNITARIOEURO] DEFAULT (0) NULL,
    [TIPOCOSTO]          VARCHAR (4)     CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_TIPOCOSTO] DEFAULT ('CMAT') NULL,
    [IDTABELLA]          VARCHAR (10)    CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_IDTABELLA] DEFAULT ('CMAT') NULL,
    [IDStoricoMag]       DECIMAL (10)    CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_IDSTORICOMAG] DEFAULT (0) NULL,
    [ORIGINEEVENTO]      SMALLINT        NULL,
    [TIPOINSERIMENTO]    SMALLINT        NULL,
    [DATAELAB_CONS]      DATETIME        NULL,
    [DATAELAB_VAL]       DATETIME        NULL,
    [DATAMOVIMENTO]      DATETIME        NULL,
    [DATADISPONIBILITA]  DATETIME        NULL,
    [DATACOMPETENZA]     DATETIME        NULL,
    [DATARIFVALORIZ]     DATETIME        NULL,
    [TIPORECDETT]        VARCHAR (2)     NULL,
    [CONTOCDC]           VARCHAR (10)    NULL,
    [QTABUDGET]          DECIMAL (16, 6) NULL,
    [PESO]               DECIMAL (8, 5)  NULL,
    [NOTE]               VARCHAR (500)   NULL,
    [IDIMPEGNO]          INT             CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_IDIMPEGNO] DEFAULT (0) NULL,
    [FLGMOVPROD]         SMALLINT        CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_FLGMOVPROD] DEFAULT (0) NULL,
    [ESERCIZIOMOV]       SMALLINT        NULL,
    [NUMEROMOV]          INT             NULL,
    [IDTESTA_DEST]       DECIMAL (10)    NULL,
    [IDRIGA_DEST]        INT             NULL,
    [IDTESTAFATT_DEST]   DECIMAL (10)    NULL,
    [IDRIGAFATT_DEST]    INT             NULL,
    [IDIMPEGNO_DEST]     INT             CONSTRAINT [DF_CCBILANCIOCONSCOSTIMATERIALE_IDIMPEGNO_DEST] DEFAULT (0) NULL,
    [ORIGINEEVENTO_DEST] SMALLINT        NULL,
    [TIPORECVAL_DEST]    VARCHAR (2)     NULL,
    [TIPODOC]            VARCHAR (3)     NULL,
    [NUMERODOC]          DECIMAL (10)    NULL,
    [BIS]                CHAR (1)        NULL,
    [ESERCIZIO]          DECIMAL (5)     NULL,
    [CODCLIFOR]          VARCHAR (7)     NULL,
    [TIPODOCFATT]        VARCHAR (3)     NULL,
    [NUMERODOCFATT]      DECIMAL (10)    NULL,
    [BISFATT]            CHAR (1)        NULL,
    [ESERCIZIOFATT]      DECIMAL (5)     NULL,
    [CODCLIFORFATT]      VARCHAR (7)     NULL,
    [TIPODOC_DEST]       VARCHAR (3)     NULL,
    [NUMERODOC_DEST]     DECIMAL (10)    NULL,
    [BIS_DEST]           CHAR (1)        NULL,
    [ESERCIZIO_DEST]     DECIMAL (5)     NULL,
    [CODCLIFOR_DEST]     VARCHAR (7)     NULL,
    [TIPODOCFATT_DEST]   VARCHAR (3)     NULL,
    [NUMERODOCFATT_DEST] DECIMAL (10)    NULL,
    [BISFATT_DEST]       CHAR (1)        NULL,
    [ESERCIZIOFATT_DEST] DECIMAL (5)     NULL,
    [CODCLIFORFATT_DEST] VARCHAR (7)     NULL,
    [ESERCIZIOMOV_DEST]  SMALLINT        NULL,
    [NUMEROMOV_DEST]     INT             NULL,
    [FLGMOVPROD_DEST]    SMALLINT        NULL,
    CONSTRAINT [PK_CCBILANCIOCONSCOSTIMATERIALE] PRIMARY KEY CLUSTERED ([IDCOMMCLI] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CCBILANCIOCONSCOSTIMATERIALE_IDCOMMCLI] FOREIGN KEY ([IDCOMMCLI]) REFERENCES [dbo].[AnagraficaCommesse] ([Progressivo]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CCBILANCIOCONSCOSTIMATERIALE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CCBILANCIOCONSCOSTIMATERIALE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CCBILANCIOCONSCOSTIMATERIALE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CCBILANCIOCONSCOSTIMATERIALE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CCBILANCIOCONSCOSTIMATERIALE] TO [Metodo98]
    AS [dbo];

