CREATE TABLE [dbo].[CESCCOSTO] (
    [CODCESPITE]      VARCHAR (10)    NOT NULL,
    [NRRIGA]          DECIMAL (5)     NOT NULL,
    [CODCCOSTO]       VARCHAR (10)    NOT NULL,
    [PRCRIPARTIZIONE] NUMERIC (19, 4) DEFAULT (0) NULL,
    [TIPOPERC]        SMALLINT        DEFAULT (0) NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    CONSTRAINT [CESCCOSTO_PK] PRIMARY KEY CLUSTERED ([CODCESPITE] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90),
    CHECK ([TIPOPERC] is null or [TIPOPERC] = 0 or [TIPOPERC] = 1),
    CONSTRAINT [FK_CESCCOSTO_CODCESPITE] FOREIGN KEY ([CODCESPITE]) REFERENCES [dbo].[AnagraficaCespiti] ([Codice]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CESCCOSTO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CESCCOSTO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CESCCOSTO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CESCCOSTO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CESCCOSTO] TO [Metodo98]
    AS [dbo];

