CREATE TABLE [dbo].[CODICIEQUIVALENTI] (
    [CODICEART]      VARCHAR (50)   NOT NULL,
    [CODICEEQUI]     VARCHAR (50)   NOT NULL,
    [RESA]           DECIMAL (8, 5) DEFAULT (0) NOT NULL,
    [DATA]           DATETIME       NULL,
    [UTENTEMODIFICA] VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]   DATETIME       NOT NULL,
    CONSTRAINT [PK_CODICIEQUIVALENTI] PRIMARY KEY CLUSTERED ([CODICEART] ASC, [CODICEEQUI] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [CODEQUI]
    ON [dbo].[CODICIEQUIVALENTI]([CODICEEQUI] ASC) WITH (FILLFACTOR = 90);


GO

/*  INSERT TRIGGER "TI_CODICIEQUIVALENTI" FOR TABLE "CODICIEQUIVALENTI"  */
CREATE TRIGGER TI_CODICIEQUIVALENTI ON CODICIEQUIVALENTI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN INSERTING A CHILD IN "CODICIEQUIVALENTI"  */
    IF UPDATE(CODICEART)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ANAGRAFICAARTICOLI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODICEART) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ANAGRAFICAARTICOLI". Cannot create child in "CODICIEQUIVALENTI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_CODICIEQUIVALENTI" FOR TABLE "CODICIEQUIVALENTI"  */
CREATE TRIGGER TU_CODICIEQUIVALENTI ON CODICIEQUIVALENTI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN UPDATING A CHILD IN "CODICIEQUIVALENTI"  */
      IF UPDATE(CODICEART)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   ANAGRAFICAARTICOLI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODICEART) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"ANAGRAFICAARTICOLI" does not exist. Cannot modify child in "CODICIEQUIVALENTI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[CODICIEQUIVALENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CODICIEQUIVALENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CODICIEQUIVALENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CODICIEQUIVALENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CODICIEQUIVALENTI] TO [Metodo98]
    AS [dbo];

