CREATE TABLE [dbo].[COMPONENTISQUADRA] (
    [SQUADRA]        VARCHAR (5)  NOT NULL,
    [DIPENDENTE]     VARCHAR (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [COMPONENTISQUADRA_PK] PRIMARY KEY CLUSTERED ([SQUADRA] ASC, [DIPENDENTE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[COMPONENTISQUADRA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[COMPONENTISQUADRA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[COMPONENTISQUADRA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[COMPONENTISQUADRA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[COMPONENTISQUADRA] TO [Metodo98]
    AS [dbo];

