CREATE TABLE [dbo].[CONSEGNEAGENTE] (
    [IDSESSIONE]         INT             NOT NULL,
    [IDTESTA]            DECIMAL (10)    NOT NULL,
    [IDRIGA]             INT             NOT NULL,
    [PROGAGENTE]         INT             NOT NULL,
    [TIPODOC]            VARCHAR (3)     NULL,
    [NUMERODOC]          INT             NOT NULL,
    [BIS]                CHAR (1)        NULL,
    [VARIANTI]           VARCHAR (255)   NOT NULL,
    [ESERCIZIO]          DECIMAL (5)     NOT NULL,
    [UM]                 VARCHAR (3)     NOT NULL,
    [QTADACONS]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QUANTITA]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QTACONSIDERATA]     DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CAMPOCONSIDERATO]   SMALLINT        DEFAULT (0) NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [IDENTIFICATIVOCONS] INT             NULL,
    [CODART]             VARCHAR (50)    NULL,
    [NRRIFPARTITA]       VARCHAR (15)    NULL,
    [UBICAZIONE]         VARCHAR (10)    NULL,
    [CODDEPOSITO]        VARCHAR (10)    NULL,
    CONSTRAINT [PK_CONSEGNEAGENTE] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [IDTESTA] ASC, [IDRIGA] ASC, [PROGAGENTE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_CAMPOCONSIDERATO_CONSEGNE] CHECK ([CAMPOCONSIDERATO] = 2 or [CAMPOCONSIDERATO] = 0 or [CAMPOCONSIDERATO] = 1)
);


GO
CREATE NONCLUSTERED INDEX [CONSAG_DOC]
    ON [dbo].[CONSEGNEAGENTE]([ESERCIZIO] ASC, [TIPODOC] ASC, [NUMERODOC] ASC, [BIS] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONSEGNEAGENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONSEGNEAGENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONSEGNEAGENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONSEGNEAGENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONSEGNEAGENTE] TO [Metodo98]
    AS [dbo];

