CREATE TABLE [dbo].[CONTRATTI_PARAMETRI] (
    [PROGRESSIVO]            DECIMAL (10)  NOT NULL,
    [CONTATORE]              DECIMAL (5)   NOT NULL,
    [MODULOSTAMPA]           VARCHAR (50)  NULL,
    [DEVICESTAMPA]           VARCHAR (255) NULL,
    [NRCOPIE]                SMALLINT      NULL,
    [UTENTEMODIFICA]         VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]           DATETIME      NOT NULL,
    [GESTGRPACQ]             SMALLINT      NULL,
    [TIPOCONS]               SMALLINT      DEFAULT (0) NOT NULL,
    [ANNOCOMP]               INT           DEFAULT (0) NOT NULL,
    [tracecons]              SMALLINT      NULL,
    [LIQRIPNOTECTR]          SMALLINT      NULL,
    [LIQRIPNOTECONTRIBUTO]   SMALLINT      NULL,
    [LIQRIPNOTECLIFORFATT]   SMALLINT      NULL,
    [considerasconti]        SMALLINT      DEFAULT ((0)) NULL,
    [considerascontipiede]   SMALLINT      DEFAULT ((0)) NULL,
    [considerascontiincond]  SMALLINT      DEFAULT ((0)) NULL,
    [CAUSALECONTABILE]       DECIMAL (5)   NULL,
    [DESCRIZIONECONTABILE]   VARCHAR (80)  NULL,
    [NRGIORNALECONTABILE]    DECIMAL (5)   NULL,
    [PARTITA]                VARCHAR (7)   NULL,
    [CONTROPARTITA]          VARCHAR (7)   NULL,
    [CAUSALECONTABILEP]      DECIMAL (5)   NULL,
    [PARTITAP]               VARCHAR (7)   NULL,
    [CONTROPARTITAP]         VARCHAR (7)   NULL,
    [MODULOSTAMPA_CONTABILE] VARCHAR (100) DEFAULT ('') NULL,
    [DEVICESTAMPA_CONTABILE] VARCHAR (100) DEFAULT ('') NULL,
    [NUMCOPIE_CONTABILE]     SMALLINT      NULL,
    [CAUSALEACCONTI]         DECIMAL (5)   DEFAULT ((0)) NULL,
    [GENERICOATTIVO]         VARCHAR (7)   NULL,
    [GENERICOPASSIVO]        VARCHAR (7)   NULL,
    [LIQRIPFATTQTAVAL]       SMALLINT      NULL,
    [DATADOCCONSATT]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [DATADOCCONSPASS]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [DOCATTTUTTI]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [DOCPASSTUTTI]           SMALLINT      DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_PARAMETRI] TO [Metodo98]
    AS [dbo];

