CREATE TABLE [dbo].[CONTRATTIAV_PROGRESSIVOBUDGETCONDICUI] (
    [RIFPROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [CONTRATTO]             DECIMAL (10)    NOT NULL,
    [RIFCONDIZIONATO]       DECIMAL (10)    NOT NULL,
    [RIGACONDIZIONATO]      INT             NOT NULL,
    [RIGACONDIZIONATODICUI] INT             NOT NULL,
    [RIGABUDGET]            INT             NOT NULL,
    [CONSUNTIVATOQTA]       DECIMAL (19, 6) NOT NULL,
    [CONSUNTIVATOVALORE]    DECIMAL (19, 6) NOT NULL,
    [UTENTEMODIFICA]        VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]          DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [CONTRATTO] ASC, [RIFCONDIZIONATO] ASC, [RIGACONDIZIONATO] ASC, [RIGACONDIZIONATODICUI] ASC, [RIGABUDGET] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTIAV_PROGRESSIVOBUDGETCONDICUI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTIAV_PROGRESSIVOBUDGETCONDICUI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTIAV_PROGRESSIVOBUDGETCONDICUI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTIAV_PROGRESSIVOBUDGETCONDICUI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTIAV_PROGRESSIVOBUDGETCONDICUI] TO [Metodo98]
    AS [dbo];

