CREATE TABLE [dbo].[CONTROPARTITECLP] (
    [PROGRESSIVO]        DECIMAL (10) NOT NULL,
    [TIPO]               SMALLINT     NOT NULL,
    [CODGRUPPOPREZZIFOR] DECIMAL (5)  NULL,
    [CODFOR]             VARCHAR (7)  NULL,
    [CODARTRIC]          VARCHAR (50) NULL,
    [CODART]             VARCHAR (50) NULL,
    [CODGRUPPOPREZZIMAG] DECIMAL (5)  NULL,
    [TIPOOPERAZIONE]     DECIMAL (5)  NULL,
    [CODOPERAZIONE]      VARCHAR (5)  NULL,
    [CONTROPARTITA]      VARCHAR (7)  NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    CONSTRAINT [PK_CONTROPARTITECLP] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTROPARTITECLP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTROPARTITECLP] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTROPARTITECLP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTROPARTITECLP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTROPARTITECLP] TO [Metodo98]
    AS [dbo];

