CREATE TABLE [dbo].[CONTRATTI_DETTCONSUNTIVGRUPPIACQ] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [IDSOCIO]        INT             NOT NULL,
    [UM]             VARCHAR (3)     NOT NULL,
    [QTA]            DECIMAL (19, 6) DEFAULT (0) NULL,
    [VALORE]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [QTAPREC]        DECIMAL (19, 6) NULL,
    [VALOREPREC]     DECIMAL (19, 6) NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [IDSOCIO] ASC, [UM] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_DETTCONSUNTIVGRUPPIACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_DETTCONSUNTIVGRUPPIACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_DETTCONSUNTIVGRUPPIACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_DETTCONSUNTIVGRUPPIACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_DETTCONSUNTIVGRUPPIACQ] TO [Metodo98]
    AS [dbo];

