CREATE TABLE [dbo].[CONTRATTI_ASSOCIAZIONIGRPACQ] (
    [COMMITTENTE]    INT          NOT NULL,
    [AFFILIATO]      INT          NOT NULL,
    [GRUPPO]         VARCHAR (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([COMMITTENTE] ASC, [AFFILIATO] ASC, [GRUPPO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_ASSOCIAZIONIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_ASSOCIAZIONIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_ASSOCIAZIONIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_ASSOCIAZIONIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_ASSOCIAZIONIGRPACQ] TO [Metodo98]
    AS [dbo];

