CREATE TABLE [dbo].[CONTRATTICL_QTAVALORE] (
    [RIFPROGRESSIVOCL] DECIMAL (10)    NOT NULL,
    [RIFPROGRESSIVO]   DECIMAL (10)    NOT NULL,
    [NRRIGA]           INT             NOT NULL,
    [FLAGRIGA]         SMALLINT        NULL,
    [POSIZIONE]        INT             NULL,
    [ARTICOLO]         VARCHAR (50)    NULL,
    [UM]               VARCHAR (3)     NULL,
    [QTA]              DECIMAL (19, 6) DEFAULT (0) NULL,
    [UTENTEMODIFICA]   VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]     DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVOCL] ASC, [RIFPROGRESSIVO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTICL_QTAVALORE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTICL_QTAVALORE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTICL_QTAVALORE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTICL_QTAVALORE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTICL_QTAVALORE] TO [Metodo98]
    AS [dbo];

