CREATE TABLE [dbo].[CONTRATTIPNTF] (
    [NRREG]          DECIMAL (10) NOT NULL,
    [NRRIGA]         INT          NOT NULL,
    [RIFCONTRATTO]   VARCHAR (50) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [CONTO]          VARCHAR (7)  NULL,
    CONSTRAINT [PK_CONTRATTIPNTF] PRIMARY KEY CLUSTERED ([NRREG] ASC, [NRRIGA] ASC),
    CONSTRAINT [FK_CONTRATTIPNTF] FOREIGN KEY ([NRREG]) REFERENCES [dbo].[TESTECONTABILITATF] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTIPNTF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTIPNTF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTIPNTF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTIPNTF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTIPNTF] TO [Metodo98]
    AS [dbo];

