CREATE TABLE [dbo].[CONTRATTIPN] (
    [NRREG]          DECIMAL (10) NOT NULL,
    [NRRIGA]         INT          NOT NULL,
    [RIFCONTRATTO]   VARCHAR (50) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [CONTO]          VARCHAR (7)  NULL,
    CONSTRAINT [PK_CONTRATTIPN] PRIMARY KEY CLUSTERED ([NRREG] ASC, [NRRIGA] ASC),
    CONSTRAINT [FK_CONTRATTIPN] FOREIGN KEY ([NRREG]) REFERENCES [dbo].[TESTECONTABILITA] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [CONTRATTIPN_NRREGCONTO]
    ON [dbo].[CONTRATTIPN]([NRREG] ASC, [CONTO] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTIPN] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTIPN] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTIPN] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTIPN] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTIPN] TO [Metodo98]
    AS [dbo];

