CREATE TABLE [dbo].[CONTRATTI_VINCOLIESERCIZIOFOR] (
    [CODCONTO]       VARCHAR (7)  NOT NULL,
    [ESERCIZIO]      DECIMAL (5)  NOT NULL,
    [DADATA]         DATETIME     NOT NULL,
    [ADATA]          DATETIME     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NULL,
    [DATAMODIFICA]   DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([CODCONTO] ASC, [ESERCIZIO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_VINCOLIESERCIZIOFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_VINCOLIESERCIZIOFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_VINCOLIESERCIZIOFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_VINCOLIESERCIZIOFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_VINCOLIESERCIZIOFOR] TO [Metodo98]
    AS [dbo];

