CREATE TABLE [dbo].[DIPENDENTILISTAMOV] (
    [IDTESTA]        DECIMAL (10) NOT NULL,
    [IDRIGA]         INT          NOT NULL,
    [PRIORITA]       INT          NOT NULL,
    [POSIZIONE]      INT          NOT NULL,
    [FLAGRIGA]       SMALLINT     CONSTRAINT [DF_DIPENDENTILISTAMOV_FLAGRIGA] DEFAULT (0) NULL,
    [DIPENDENTE]     VARCHAR (5)  NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    PRIMARY KEY CLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC, [PRIORITA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[DIPENDENTILISTAMOV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[DIPENDENTILISTAMOV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[DIPENDENTILISTAMOV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[DIPENDENTILISTAMOV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[DIPENDENTILISTAMOV] TO [Metodo98]
    AS [dbo];

