CREATE TABLE [dbo].[DOCDAPRELEVARE] (
    [CODICE]         VARCHAR (3)  NOT NULL,
    [DOCPRELIEVO]    VARCHAR (3)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [RIGHEVALORE]    SMALLINT     CONSTRAINT [DF_DOCDAPRELEVARE_RIGHEVALORE] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_DOCDAPRELEVARE] PRIMARY KEY CLUSTERED ([CODICE] ASC, [DOCPRELIEVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DOCDAPRELEVARE_CODICE] FOREIGN KEY ([CODICE]) REFERENCES [dbo].[PARAMETRIDOC] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[DOCDAPRELEVARE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[DOCDAPRELEVARE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[DOCDAPRELEVARE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[DOCDAPRELEVARE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[DOCDAPRELEVARE] TO [Metodo98]
    AS [dbo];

