CREATE TABLE [dbo].[DOCUMENTICLPASSIVO] (
    [CODORDINE]      VARCHAR (3)  NOT NULL,
    [CODDOCUMENTO]   VARCHAR (3)  NOT NULL,
    [POSIZIONE]      DECIMAL (5)  NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    CONSTRAINT [PK_DOCUMENTICLPASSIVO] PRIMARY KEY CLUSTERED ([CODORDINE] ASC, [CODDOCUMENTO] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_DOCUMENTICLPASSIVO" FOR TABLE "DOCUMENTICLPASSIVO"  */
CREATE TRIGGER TI_DOCUMENTICLPASSIVO ON DOCUMENTICLPASSIVO FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "PARAMETRIORDPROD" MUST EXIST WHEN INSERTING A CHILD IN "DOCUMENTICLPASSIVO"  */
    IF UPDATE(CODORDINE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   PARAMETRIORDPROD T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODORDINE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "PARAMETRIORDPROD". Cannot create child in "DOCUMENTICLPASSIVO".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_DOCUMENTICLPASSIVO" FOR TABLE "DOCUMENTICLPASSIVO"  */
CREATE TRIGGER TU_DOCUMENTICLPASSIVO ON DOCUMENTICLPASSIVO FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "PARAMETRIORDPROD" MUST EXIST WHEN UPDATING A CHILD IN "DOCUMENTICLPASSIVO"  */
      IF UPDATE(CODORDINE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   PARAMETRIORDPROD T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODORDINE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"PARAMETRIORDPROD" does not exist. Cannot ALTER COLUMN child in "DOCUMENTICLPASSIVO".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[DOCUMENTICLPASSIVO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[DOCUMENTICLPASSIVO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[DOCUMENTICLPASSIVO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[DOCUMENTICLPASSIVO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[DOCUMENTICLPASSIVO] TO [Metodo98]
    AS [dbo];

