CREATE TABLE [dbo].[EMISSIONEEFF] (
    [NRTERMINALE]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [PROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [TIPODOC]            VARCHAR (3)     NULL,
    [NUMDOC]             DECIMAL (10)    NULL,
    [BIS]                CHAR (1)        NULL,
    [NUMSCAD]            INT             NULL,
    [DATASCADENZA]       DATETIME        NULL,
    [CODCLIFOR]          VARCHAR (7)     NULL,
    [DATAFATTURA]        DATETIME        NULL,
    [BANCAINC]           VARCHAR (7)     NULL,
    [BANCAAPPOGGIO]      DECIMAL (5)     NULL,
    [NUMRIF]             VARCHAR (15)    NULL,
    [NUMEROPROT]         VARCHAR (12)    NULL,
    [IMPORTOSCLIT]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPORTOSCVAL]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPORTOSCEURO]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPONIBSCLIT]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPONIBSCVAL]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPONIBSCEURO]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [TOTFATTLIT]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [TOTFATTVAL]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [TOTFATTEURO]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPFATTLIT]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPFATTVAL]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPFATTEURO]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [TIPOEFFETTO]        DECIMAL (5)     NULL,
    [ESITO]              DECIMAL (5)     NULL,
    [NUMEFF]             INT             NULL,
    [SCADATTPASS]        SMALLINT        DEFAULT (0) NULL,
    [IMPORTOLETTERE]     VARCHAR (255)   NULL,
    [CARTIPOEFF]         VARCHAR (1)     NULL,
    [EFFRAGGRUPPATO]     SMALLINT        DEFAULT (0) NULL,
    [DESTCORRISPONDENZA] DECIMAL (5)     NULL,
    [RAGIONESOCIALE]     VARCHAR (80)    NULL,
    [RAGIONESOCIALE2]    VARCHAR (100)   NULL,
    [INDIRIZZO]          VARCHAR (80)    NULL,
    [CAP]                VARCHAR (8)     NULL,
    [LOCALITA]           VARCHAR (80)    NULL,
    [PROVINCIA]          VARCHAR (4)     NULL,
    [FAX]                VARCHAR (25)    NULL,
    [BANCAANAGR]         VARCHAR (80)    NULL,
    [CAB]                VARCHAR (6)     NULL,
    [ABI]                VARCHAR (6)     NULL,
    [ANNODOC]            SMALLINT        DEFAULT (0) NULL,
    [CODCAMBIO]          DECIMAL (5)     NULL,
    [DATAEMISSIONE]      DATETIME        NULL,
    [CCANAGRAFICA]       VARCHAR (15)    NULL,
    [VALFISSABENEF]      DATETIME        NULL,
    [PARTITAIVA]         VARCHAR (16)    NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [CODICEIBAN]         VARCHAR (34)    NULL,
    [Telefono]           VARCHAR (25)    NULL,
    [CODICECIG]          VARCHAR (10)    CONSTRAINT [DF_EMISSIONEEFF_CODICECIG] DEFAULT ('') NULL,
    [CODICECUP]          VARCHAR (15)    CONSTRAINT [DF_EMISSIONEEFF_CODICECUP] DEFAULT ('') NULL,
    CONSTRAINT [PK_EMISSIONEEFF] PRIMARY KEY CLUSTERED ([NRTERMINALE] ASC, [PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_EFFRAGGRUPPATO_EMISSION] CHECK ([EFFRAGGRUPPATO] = 0 or [EFFRAGGRUPPATO] = 1),
    CONSTRAINT [CKC_SCADATTPASS_EMISSION] CHECK ([SCADATTPASS] = 0 or [SCADATTPASS] = 1)
);


GO
CREATE NONCLUSTERED INDEX [CODCLIFOR]
    ON [dbo].[EMISSIONEEFF]([CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [EMISSEFF_DOC]
    ON [dbo].[EMISSIONEEFF]([ANNODOC] ASC, [TIPODOC] ASC, [NUMDOC] ASC, [BIS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [ABICAB]
    ON [dbo].[EMISSIONEEFF]([ABI] ASC, [CAB] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EMISSIONEEFF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EMISSIONEEFF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EMISSIONEEFF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EMISSIONEEFF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EMISSIONEEFF] TO [Metodo98]
    AS [dbo];

