CREATE TABLE [dbo].[EURIS_PRO_CLA_MAC] (
    [COD_AZIENDA]      NVARCHAR (3)  NULL,
    [COD_CLASSE]       NVARCHAR (12) NULL,
    [COD_RISORSA]      NVARCHAR (12) NULL,
    [PRIORITA]         DECIMAL (3)   NULL,
    [ULTIMA_MODIFICA]  DECIMAL (8)   NULL,
    [ULTIMO_UTENTE]    NVARCHAR (10) NULL,
    [COD_STABILIMENTO] NVARCHAR (3)  NULL,
    CONSTRAINT [FK_EURIS_PRO_CLA_MAC_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_PRO_CLA_MAC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_PRO_CLA_MAC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_PRO_CLA_MAC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_PRO_CLA_MAC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_PRO_CLA_MAC] TO [Metodo98]
    AS [dbo];

