CREATE TABLE [dbo].[EURIS_BAS_ART_MRP] (
    [COD_AZIENDA]     NVARCHAR (3)  NULL,
    [COD_ARTICOLO]    NVARCHAR (20) NULL,
    [DES_ARTICOLO]    NVARCHAR (30) NULL,
    [SECONDA_DES]     NVARCHAR (30) NULL,
    [ULTIMA_MODIFICA] DATETIME      NULL,
    [ULTIMO_UTENTE]   NVARCHAR (20) NULL,
    CONSTRAINT [FK_EURIS_BAS_ART_MRP_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_BAS_ART_MRP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_BAS_ART_MRP] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_BAS_ART_MRP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_BAS_ART_MRP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_BAS_ART_MRP] TO [Metodo98]
    AS [dbo];

