CREATE TABLE [dbo].[EURIS_BAS_CAL_LAV] (
    [COD_AZIENDA]     NVARCHAR (3)  NULL,
    [COD_CALENDARIO]  NVARCHAR (5)  NULL,
    [DT_CALENDARIO]   DECIMAL (8)   NULL,
    [PRO_GIORNO]      DECIMAL (5)   NULL,
    [PRO_GIORNO_LAV]  DECIMAL (5)   NULL,
    [NUM_SETTIMANA]   DECIMAL (3)   NULL,
    [FLG_GIORNO_LAV]  NVARCHAR (1)  NULL,
    [COD_GIORNO_SETT] NVARCHAR (1)  NULL,
    [NUM_ORE_LAV]     DECIMAL (3)   NULL,
    [COD_TAB_FASCE]   NVARCHAR (3)  NULL,
    [ULTIMA_MODIFICA] DECIMAL (8)   NULL,
    [ULTIMO_UTENTE]   NVARCHAR (10) NULL,
    CONSTRAINT [FK_EURIS_BAS_CAL_LAV_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_BAS_CAL_LAV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_BAS_CAL_LAV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_BAS_CAL_LAV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_BAS_CAL_LAV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_BAS_CAL_LAV] TO [Metodo98]
    AS [dbo];

