CREATE TABLE [dbo].[EURIS_PRO_ASS_RIS] (
    [COD_AZIENDA]      NVARCHAR (3)     NULL,
    [COD_STABILIMENTO] NVARCHAR (3)     NULL,
    [TIPO_ORDINE]      NVARCHAR (3)     NULL,
    [NUM_ORDINE]       NVARCHAR (15)    NULL,
    [COD_FASE]         DECIMAL (5)      NULL,
    [COD_SOTTO_FASE]   DECIMAL (3)      NULL,
    [COD_ALTERNATIVA]  NVARCHAR (2)     NULL,
    [COD_RISORSA]      NVARCHAR (12)    NULL,
    [TIPO_FASE]        NVARCHAR (1)     NULL,
    [COD_RISORSA_ASS]  NVARCHAR (12)    NULL,
    [NUM_MACCHINA]     DECIMAL (3)      NULL,
    [PER_UTILIZZO]     DECIMAL (3)      NULL,
    [T_FISSO]          DECIMAL (15, 10) NULL,
    [T_VARIABILE]      DECIMAL (15, 10) NULL,
    [VALPRI]           DECIMAL (18, 10) NULL,
    [ULTIMA_MODIFICA]  DECIMAL (8)      NULL,
    [ULTIMO_UTENTE]    NVARCHAR (10)    NULL,
    CONSTRAINT [FK_EURIS_PRO_ASS_RIS_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_PRO_ASS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_PRO_ASS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_PRO_ASS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_PRO_ASS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_PRO_ASS_RIS] TO [Metodo98]
    AS [dbo];

