CREATE TABLE [dbo].[EURIS_BAS_COM] (
    [COD_AZIENDA]     NVARCHAR (3)  NULL,
    [COD_COMMESSA]    NVARCHAR (12) NULL,
    [DES_COMMESSA]    NVARCHAR (30) NULL,
    [COD_ENTE]        NVARCHAR (8)  NULL,
    [STATO_COM]       NVARCHAR (2)  NULL,
    [TIPO_PRI_COM]    NVARCHAR (1)  NULL,
    [PRIORITA]        DECIMAL (6)   NULL,
    [DT_ACQUISIZIONE] DATETIME      NULL,
    [DT_SPEDIZIONE]   DATETIME      NULL,
    [DT_CONSEGNA]     DATETIME      NULL,
    [RIF_CONTRATTO]   NVARCHAR (3)  NULL,
    [ULTIMA_MODIFICA] DATETIME      NULL,
    [ULTIMO_UTENTE]   NVARCHAR (20) NULL,
    CONSTRAINT [FK_EURIS_BAS_COM_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_BAS_COM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_BAS_COM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_BAS_COM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_BAS_COM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_BAS_COM] TO [Metodo98]
    AS [dbo];

