CREATE TABLE [dbo].[EXTRACICLI] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [EXTRACICLI_PK] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_EXTRACICLI" FOR TABLE "EXTRACICLI"  */
CREATE TRIGGER TI_EXTRACICLI ON EXTRACICLI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TESTACICLOPROD" MUST EXIST WHEN INSERTING A CHILD IN "EXTRACICLI"  */
    IF UPDATE(PROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TESTACICLOPROD T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TESTACICLOPROD". Cannot create child in "EXTRACICLI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_EXTRACICLI" FOR TABLE "EXTRACICLI"  */
CREATE TRIGGER TU_EXTRACICLI ON EXTRACICLI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TESTACICLOPROD" MUST EXIST WHEN UPDATING A CHILD IN "EXTRACICLI"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TESTACICLOPROD T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TESTACICLOPROD" does not exist. Cannot modify child in "EXTRACICLI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRACICLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRACICLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRACICLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRACICLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRACICLI] TO [Metodo98]
    AS [dbo];

