CREATE TABLE [dbo].[EXTRAAVANZAMENTI] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_EXTRAAVANZAMENTI] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO

/* INSERT TRIGGER "TI_EXTRAAVANZAMENTI" FOR TABLE "EXTRAAVANZAMENTI" */
CREATE TRIGGER TI_EXTRAAVANZAMENTI ON  EXTRAAVANZAMENTI FOR INSERT AS
BEGIN

DECLARE
@MAXCARD INT,
@NUMROWS INT,
@NUMNULL INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* INTEGRITY */  /* per OGNI Tabella PARENT in Relazione */
/* PARENT "STORICOAVANZAMENTI" MUST EXIST WHEN INSERTING A CHILD IN "EXTRAAVANZAMENTI" */
IF UPDATE(RIFPROGRESSIVO)
BEGIN

IF (SELECT COUNT(*) FROM STORICOAVANZAMENTI T1, INSERTED T2
WHERE T1.PROGRESSIVO = T2.RIFPROGRESSIVO) != @NUMROWS
BEGIN
   SELECT @ERRNO = 30002,
   @ERRMSG = 'Parent does not exist in "STORICOAVANZAMENTI". Cannot create child in "EXTRAAVANZAMENTI".'
GOTO ERROR

END

END

RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRAAVANZAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRAAVANZAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRAAVANZAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRAAVANZAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRAAVANZAMENTI] TO [Metodo98]
    AS [dbo];

