CREATE TABLE [dbo].[FEATURELIST] (
    [CodFeature]     INT          NOT NULL,
    [CodTipologia]   VARCHAR (3)  NOT NULL,
    [UtenteModifica] VARCHAR (25) NOT NULL,
    [DataModifica]   DATETIME     NOT NULL,
    [NRRIGA]         INT          DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([CodFeature] ASC, [CodTipologia] ASC),
    FOREIGN KEY ([CodTipologia]) REFERENCES [dbo].[TABTIPOLOGIE] ([TIPOLOGIA])
);


GO


CREATE TRIGGER TD_FEATURELIST ON FEATURELIST FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)
 
    SELECT  @NUMROWS = @@ROWCOUNT

    IF @NUMROWS = 0
       RETURN
  
    IF EXISTS (SELECT 1 FROM FEATURELIST T2 , DELETED T1 WHERE T2.CODFEATURE = T1.CODFEATURE)  
       RETURN
  
    /*  AGGIORNAMENTO VARESPLICITE SU "GESTIONEPREZZI"  */ 
    UPDATE GESTIONEPREZZI SET VARESPLICITE = '' 
    WHERE CODART IN 
    ( SELECT T2.CODICE FROM ANAGRAFICAARTICOLI T2 , DELETED T1 
      WHERE T2.CODFEATURE = T1.CODFEATURE ) 
    
    /*  AGGIORNAMENTO VARESPLICITE SU "REGOLEPREZZIESTESI"  */ 
    UPDATE REGOLEPREZZIESTESI  SET VARESPLICITE = '' 
    WHERE CODART IN 
    ( SELECT T2.CODICE FROM ANAGRAFICAARTICOLI T2 , DELETED T1 
      WHERE T2.CODFEATURE = T1.CODFEATURE )
    
    /*  AGGIORNAMENTO VARESPLICITE SU "TABPROVVIGIONI"  */ 
    UPDATE TABPROVVIGIONI  SET VARESPLICITE = '' 
    WHERE CODARTICOLO  IN 
    ( SELECT T2.CODICE FROM ANAGRAFICAARTICOLI T2 , DELETED T1 
      WHERE T2.CODFEATURE = T1.CODFEATURE )
    
    /*  AGGIORNAMENTO "ANAGRAFICAARTICOLI"  */
    UPDATE ANAGRAFICAARTICOLI
    SET    CODFEATURE  = 0,VARESPLICITE=''
    FROM   ANAGRAFICAARTICOLI T2, DELETED T1
    WHERE  T2.CODFEATURE  = T1.CodFeature 
    
    /*  DELETE ALL CHILDREN IN "FEATUREARTICOLO"  */
    DELETE FEATUREARTICOLO
    FROM   FEATUREARTICOLO T2, DELETED T1
    WHERE  T2.CodFeature  = T1.CodFeature 
 
    RETURN

 
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END


GO
GRANT DELETE
    ON OBJECT::[dbo].[FEATURELIST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FEATURELIST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FEATURELIST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FEATURELIST] TO [Metodo98]
    AS [dbo];

