CREATE TABLE [dbo].[FEPA_TIPIDOCUMENTI] (
    [TIPODOCPA]      VARCHAR (10)  NOT NULL,
    [DSCTIPODOCPA]   VARCHAR (50)  NULL,
    [TIPODOC]        VARCHAR (3)   DEFAULT ('') NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [PERCORSO]       VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([TIPODOCPA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[FEPA_TIPIDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FEPA_TIPIDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FEPA_TIPIDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FEPA_TIPIDOCUMENTI] TO [Metodo98]
    AS [dbo];

