CREATE TABLE [dbo].[FETS_CODIFICHEUNITAMISURA] (
    [TIPOCICLO]      SMALLINT     NOT NULL,
    [CODICEMET]      VARCHAR (10) NOT NULL,
    [CODICEB2B]      VARCHAR (10) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_FETS_CODIFICHEUNITAMISURA] PRIMARY KEY CLUSTERED ([TIPOCICLO] ASC, [CODICEMET] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[FETS_CODIFICHEUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FETS_CODIFICHEUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FETS_CODIFICHEUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FETS_CODIFICHEUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FETS_CODIFICHEUNITAMISURA] TO [Metodo98]
    AS [dbo];

