CREATE TABLE [dbo].[FETS_CODICISPESEACC_B2B] (
    [CODICE]         VARCHAR (10)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [GENERICO]       VARCHAR (7)   DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[FETS_CODICISPESEACC_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FETS_CODICISPESEACC_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FETS_CODICISPESEACC_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FETS_CODICISPESEACC_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FETS_CODICISPESEACC_B2B] TO [Metodo98]
    AS [dbo];

