CREATE TABLE [dbo].[GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE] (
    [IDCONTRATTO]       VARCHAR (13)    NOT NULL,
    [SEZIONECONTRATTO]  DECIMAL (5)     NOT NULL,
    [IDRAPPORTO]        VARCHAR (14)    NOT NULL,
    [IdRiga]            DECIMAL (5)     NOT NULL,
    [IDRAPPORTO_RIF]    VARCHAR (14)    NOT NULL,
    [TipologiaElemento] VARCHAR (1)     NULL,
    [idRigaAttvita]     DECIMAL (5)     DEFAULT ((0)) NOT NULL,
    [idRigaMateriali]   DECIMAL (5)     DEFAULT ((0)) NOT NULL,
    [idRigaOreLav]      DECIMAL (5)     DEFAULT ((0)) NOT NULL,
    [idRigaRata]        DECIMAL (5)     DEFAULT ((0)) NOT NULL,
    [CodArticolo]       VARCHAR (50)    NULL,
    [DscrizioneRiga]    VARCHAR (80)    NULL,
    [QTA]               NUMERIC (10, 2) DEFAULT ((0)) NOT NULL,
    [PREZZO]            NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [SCONTO]            NUMERIC (10, 5) NULL,
    [PROVVIGIONE1]      NUMERIC (18, 2) NULL,
    [PROVVIGIONE2]      NUMERIC (18, 2) NULL,
    [PROVVIGIONE3]      NUMERIC (18, 2) NULL,
    [TipoFatturazione]  VARCHAR (20)    NULL,
    [Validita]          VARCHAR (20)    NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [Posizione]         INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE] PRIMARY KEY CLUSTERED ([IDRAPPORTO] ASC, [IDCONTRATTO] ASC, [SEZIONECONTRATTO] ASC, [IdRiga] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE_Attivita]
    ON [dbo].[GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE]([IDRAPPORTO] ASC, [CodArticolo] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE] TO [Metodo98]
    AS [dbo];

