CREATE TABLE [dbo].[GEM_TMP_SEZIONECONTRATTO_RATE] (
    [idSESSIONE]       INT          NOT NULL,
    [IDCONTRATTO]      VARCHAR (13) NOT NULL,
    [NUMERORATA]       NUMERIC (18) NOT NULL,
    [UTENTEMODIFICA]   VARCHAR (25) NULL,
    [DATAMODIFICA]     DATETIME     NULL,
    [RAGR]             VARCHAR (4)  DEFAULT ('') NULL,
    [data_prev]        DATETIME     NULL,
    [datainizCompRata] DATETIME     NULL,
    [DataFineCompRata] DATETIME     NULL,
    [STATO]            CHAR (1)     NULL,
    CONSTRAINT [PK_GEM_TMP_SEZIONECONTRATTO_RATE] PRIMARY KEY CLUSTERED ([idSESSIONE] ASC, [IDCONTRATTO] ASC, [NUMERORATA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[GEM_TMP_SEZIONECONTRATTO_RATE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GEM_TMP_SEZIONECONTRATTO_RATE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GEM_TMP_SEZIONECONTRATTO_RATE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GEM_TMP_SEZIONECONTRATTO_RATE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GEM_TMP_SEZIONECONTRATTO_RATE] TO [Metodo98]
    AS [dbo];

