CREATE TABLE [dbo].[GEM_TEMP_STP_AnalisiRate] (
    [IDCONTRATTO]    VARCHAR (13) NOT NULL,
    [NUMERORATA]     NUMERIC (18) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [GEM_TEMP_STP_AnalisiRate_PK] PRIMARY KEY CLUSTERED ([IDCONTRATTO] ASC, [NUMERORATA] ASC, [UTENTEMODIFICA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[GEM_TEMP_STP_AnalisiRate] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GEM_TEMP_STP_AnalisiRate] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GEM_TEMP_STP_AnalisiRate] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GEM_TEMP_STP_AnalisiRate] TO [Metodo98]
    AS [dbo];

