CREATE TABLE [dbo].[GESTIONEPREZZI] (
    [PROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [CODGRUPPOPREZZICF]  DECIMAL (5)     NULL,
    [CODCLIFOR]          VARCHAR (7)     NULL,
    [CODART]             VARCHAR (50)    NULL,
    [CODGRUPPOPREZZIMAG] DECIMAL (5)     NULL,
    [INIZIOVALIDITA]     DATETIME        NULL,
    [FINEVALIDITA]       DATETIME        NULL,
    [USANRLISTINO]       SMALLINT        DEFAULT (0) NULL,
    [TIPOARROT]          VARCHAR (1)     DEFAULT ('C') NULL,
    [ARROTALIRE]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [ARROTAEURO]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [CODARTRIC]          VARCHAR (50)    NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [PROGRESSIVOCTR]     DECIMAL (10)    CONSTRAINT [DF_GESTIONEPREZZI_PROGRESSIVOCTR] DEFAULT (0) NULL,
    [CODICEPRIMARIO]     VARCHAR (50)    DEFAULT ('') NULL,
    [VARESPLICITE]       VARCHAR (255)   DEFAULT ('') NULL,
    [CODFEATURE]         INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_GESTIONEPREZZI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOARROT_GESTIONE] CHECK ([TIPOARROT] = 'N' or [TIPOARROT] = 'D' or [TIPOARROT] = 'E' or [TIPOARROT] = 'C'),
    CONSTRAINT [CKC_USANRLISTINO_GESTIONE] CHECK ([USANRLISTINO] = 0 or [USANRLISTINO] = 1)
);


GO
CREATE NONCLUSTERED INDEX [GPRZ_ARTCATCF]
    ON [dbo].[GESTIONEPREZZI]([CODART] ASC, [CODGRUPPOPREZZICF] ASC, [CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CATCFGRART]
    ON [dbo].[GESTIONEPREZZI]([CODGRUPPOPREZZICF] ASC, [CODCLIFOR] ASC, [CODGRUPPOPREZZIMAG] ASC, [CODART] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CFGRART]
    ON [dbo].[GESTIONEPREZZI]([CODCLIFOR] ASC, [CODGRUPPOPREZZIMAG] ASC, [CODART] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODART]
    ON [dbo].[GESTIONEPREZZI]([CODART] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODCATEGORIACF]
    ON [dbo].[GESTIONEPREZZI]([CODGRUPPOPREZZICF] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODCLIFOR]
    ON [dbo].[GESTIONEPREZZI]([CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODGRUPPO]
    ON [dbo].[GESTIONEPREZZI]([CODGRUPPOPREZZIMAG] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_FINEVALIDITA]
    ON [dbo].[GESTIONEPREZZI]([FINEVALIDITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_GRARTCATCF]
    ON [dbo].[GESTIONEPREZZI]([CODGRUPPOPREZZIMAG] ASC, [CODART] ASC, [CODGRUPPOPREZZICF] ASC, [CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_INIZIOVALIDITA]
    ON [dbo].[GESTIONEPREZZI]([INIZIOVALIDITA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[GESTIONEPREZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GESTIONEPREZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GESTIONEPREZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GESTIONEPREZZI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GESTIONEPREZZI] TO [Metodo98]
    AS [dbo];

