CREATE TABLE [dbo].[GESTIONEPREZZIRIGHECTR] (
    [IDRIGA]            DECIMAL (10)    NOT NULL,
    [RIFPROGRESSIVO]    DECIMAL (10)    NOT NULL,
    [NRLISTINO]         DECIMAL (5)     NOT NULL,
    [UM]                VARCHAR (3)     NOT NULL,
    [QTAMINIMA]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [PREZZO_MAGG]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [PREZZO_MAGGEURO]   DECIMAL (19, 6) DEFAULT (0) NULL,
    [SCONTO_UNICO]      VARCHAR (10)    NULL,
    [SCONTO_AGGIUNTIVO] VARCHAR (10)    NULL,
    [TIPO]              DECIMAL (5)     DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [TP_QTASCONTO]      NUMERIC (16, 6) NULL,
    [TP_QTACOEFF]       NUMERIC (16, 6) NULL,
    PRIMARY KEY CLUSTERED ([IDRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPO_GESTIONECTR] CHECK ([TIPO] >= (-3) and [TIPO] <= 99999)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GPRIGHE]
    ON [dbo].[GESTIONEPREZZIRIGHECTR]([RIFPROGRESSIVO] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90);


GO


CREATE TRIGGER TI_GESTIONEPREZZIRIGHECTR ON GESTIONEPREZZIRIGHECTR FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "GESTIONEPREZZI" MUST EXIST WHEN INSERTING A CHILD IN "GESTIONEPREZZIRIGHE"  */
    IF UPDATE(RIFPROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   GESTIONEPREZZICTR T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.RIFPROGRESSIVO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "GESTIONEPREZZICTR". Cannot create child in "GESTIONEPREZZIRIGHECTR".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

CREATE TRIGGER TU_GESTIONEPREZZIRIGHECTR ON GESTIONEPREZZIRIGHECTR FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "GESTIONEPREZZI" MUST EXIST WHEN UPDATING A CHILD IN "GESTIONEPREZZIRIGHE"  */
      IF UPDATE(RIFPROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   GESTIONEPREZZICTR T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.RIFPROGRESSIVO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"GESTIONEPREZZICTR" does not exist. Cannot modify child in "GESTIONEPREZZIRIGHECTR".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHECTR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHECTR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHECTR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHECTR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHECTR] TO [Metodo98]
    AS [dbo];

