CREATE TABLE [dbo].[IMPOSTAZIONITRASFFASE] (
    [NOMEIMPOSTAZIONE]        VARCHAR (80)   NOT NULL,
    [FLGANALISITRASFERIMENTO] SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGANALISITRASFERIMENTO] DEFAULT (0) NULL,
    [FLGTIPOANALISIDEPDEST]   SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGTIPOANALISIDEPDEST] DEFAULT (0) NULL,
    [FLGTIPOANALISIDEPPROV]   SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGTIPOANALISIDEPPROV] DEFAULT (0) NULL,
    [FLGNETTIFICAALTRELISTE]  SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGNETTIFICAALTRELISTE] DEFAULT (0) NULL,
    [FLGRIPORTANONSERVITI]    SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGRIPORTANONSERVITI] DEFAULT (0) NULL,
    [FLGTIPOEMISSIONE]        SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGTIPOEMISSIONE] DEFAULT (0) NULL,
    [TIPODOCUMENTO]           VARCHAR (3)    NULL,
    [RIFDOCUMENTO]            DECIMAL (10)   CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_RIFDOCUMENTO] DEFAULT (0) NULL,
    [TIPOLISTATRASF]          VARCHAR (3)    NULL,
    [RIFLISTATRASF]           DECIMAL (10)   CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_RIFLISTATRASF] DEFAULT (0) NULL,
    [FLGEMETTIACCODA]         SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGEMETTIACCODA] DEFAULT (0) NULL,
    [FLGINSERISCIRIF]         SMALLINT       CONSTRAINT [DF_IMPOSTAZIONITRASFFASE_FLGINSERISCIRIF] DEFAULT (0) NULL,
    [LISTADEPOSITI]           VARCHAR (5000) NULL,
    [UTENTEMODIFICA]          VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]            DATETIME       NOT NULL,
    CONSTRAINT [PK_IMPOSTAZIONITRASFFASE] PRIMARY KEY CLUSTERED ([NOMEIMPOSTAZIONE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[IMPOSTAZIONITRASFFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[IMPOSTAZIONITRASFFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[IMPOSTAZIONITRASFFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[IMPOSTAZIONITRASFFASE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[IMPOSTAZIONITRASFFASE] TO [Metodo98]
    AS [dbo];

