CREATE TABLE [dbo].[IMPOSTAZIONIVISIONI] (
    [PROGRESSIVO]      DECIMAL (10)  IDENTITY (1, 1) NOT NULL,
    [NOMEVISIONE]      VARCHAR (80)  NOT NULL,
    [NOMEIMPOSTAZIONE] VARCHAR (50)  NOT NULL,
    [TIPOCAMPO]        SMALLINT      NOT NULL,
    [ID]               SMALLINT      NOT NULL,
    [NOMECAMPO]        VARCHAR (100) NULL,
    [UTENTEMODIFICA]   VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]     DATETIME      NOT NULL,
    CONSTRAINT [PK_IMPOSTAZIONIVISIONI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[IMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[IMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[IMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[IMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[IMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];

