CREATE TABLE [dbo].[IMPOSTAZIONIVARLIST] (
    [IMPOSTAZIONE]   VARCHAR (50)  NOT NULL,
    [TIPOVARIAZIONE] SMALLINT      NOT NULL,
    [RIGA]           SMALLINT      NOT NULL,
    [COLONNA]        SMALLINT      NOT NULL,
    [CODLISTINO]     DECIMAL (5)   NOT NULL,
    [VALORE]         VARCHAR (255) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([IMPOSTAZIONE] ASC, [TIPOVARIAZIONE] ASC, [RIGA] ASC, [COLONNA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[IMPOSTAZIONIVARLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[IMPOSTAZIONIVARLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[IMPOSTAZIONIVARLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[IMPOSTAZIONIVARLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[IMPOSTAZIONIVARLIST] TO [Metodo98]
    AS [dbo];

