CREATE TABLE [dbo].[IMPOSTAZIONIMAGAZZINIPROD] (
    [NOMEPIANIF]      VARCHAR (30) NOT NULL,
    [CODICEMAGAZZINO] VARCHAR (10) NOT NULL,
    [TIPOMAG]         SMALLINT     DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    CONSTRAINT [PK_IMPOSTAZIONIMAGAZZINIPROD] PRIMARY KEY CLUSTERED ([NOMEPIANIF] ASC, [CODICEMAGAZZINO] ASC, [TIPOMAG] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IMPOSTAZIONIPROGPROD_FK]
    ON [dbo].[IMPOSTAZIONIMAGAZZINIPROD]([NOMEPIANIF] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MAGPROD]
    ON [dbo].[IMPOSTAZIONIMAGAZZINIPROD]([CODICEMAGAZZINO] ASC) WITH (FILLFACTOR = 90);


GO

/*  INSERT TRIGGER "TI_IMPOSTAZIONIMAGAZZINIPROD" FOR TABLE "IMPOSTAZIONIMAGAZZINIPROD"  */
CREATE TRIGGER TI_IMPOSTAZIONIMAGAZZINIPROD ON IMPOSTAZIONIMAGAZZINIPROD FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "IMPOSTAZIONIPROGPROD" MUST EXIST WHEN INSERTING A CHILD IN "IMPOSTAZIONIMAGAZZINIPROD"  */
    IF UPDATE(NOMEPIANIF)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   IMPOSTAZIONIPROGPROD T1, INSERTED T2
           WHERE  T1.NOMEPIANIF = T2.NOMEPIANIF) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "IMPOSTAZIONIPROGPROD". Cannot create child in "IMPOSTAZIONIMAGAZZINIPROD".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_IMPOSTAZIONIMAGAZZINIPROD" FOR TABLE "IMPOSTAZIONIMAGAZZINIPROD"  */
CREATE TRIGGER TU_IMPOSTAZIONIMAGAZZINIPROD ON IMPOSTAZIONIMAGAZZINIPROD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "IMPOSTAZIONIPROGPROD" MUST EXIST WHEN UPDATING A CHILD IN "IMPOSTAZIONIMAGAZZINIPROD"  */
      IF UPDATE(NOMEPIANIF)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   IMPOSTAZIONIPROGPROD T1, INSERTED T2
             WHERE  T1.NOMEPIANIF = T2.NOMEPIANIF) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"IMPOSTAZIONIPROGPROD" does not exist. Cannot modify child in "IMPOSTAZIONIMAGAZZINIPROD".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[IMPOSTAZIONIMAGAZZINIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[IMPOSTAZIONIMAGAZZINIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[IMPOSTAZIONIMAGAZZINIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[IMPOSTAZIONIMAGAZZINIPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[IMPOSTAZIONIMAGAZZINIPROD] TO [Metodo98]
    AS [dbo];

