CREATE TABLE [dbo].[IMPOSTAZIONIAGGCAMPIART] (
    [NOMEIMPOSTAZIONE] VARCHAR (50) NOT NULL,
    [NOMETABELLA]      VARCHAR (80) NOT NULL,
    [NOMECAMPO]        VARCHAR (80) NOT NULL,
    [AGGIORNAFIGLIO]   SMALLINT     NULL,
    [UTENTEMODIFICA]   VARCHAR (25) NOT NULL,
    [DATAMODIFICA]     DATETIME     NOT NULL,
    CONSTRAINT [PK_IMPOSTAZIONIAGGCAMPIART] PRIMARY KEY CLUSTERED ([NOMEIMPOSTAZIONE] ASC, [NOMETABELLA] ASC, [NOMECAMPO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_IMPOSTAZIONIAGGCAMPIART_AGGIORNAF] CHECK ([AGGIORNAFIGLIO] = 0 or [AGGIORNAFIGLIO] = 1)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[IMPOSTAZIONIAGGCAMPIART] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[IMPOSTAZIONIAGGCAMPIART] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[IMPOSTAZIONIAGGCAMPIART] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[IMPOSTAZIONIAGGCAMPIART] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[IMPOSTAZIONIAGGCAMPIART] TO [Metodo98]
    AS [dbo];

