CREATE TABLE [dbo].[LIFOARTICOLI] (
    [CODICEART]      VARCHAR (50)    NOT NULL,
    [ESERCIZIO]      DECIMAL (5)     NOT NULL,
    [ANNO]           SMALLINT        NOT NULL,
    [QUANTITA1]      DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [VALORELIFO1]    DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [VALORELIFOEURO] DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_LIFOARTICOLI] PRIMARY KEY CLUSTERED ([CODICEART] ASC, [ESERCIZIO] ASC, [ANNO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[LIFOARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[LIFOARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[LIFOARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[LIFOARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[LIFOARTICOLI] TO [Metodo98]
    AS [dbo];

