CREATE TABLE [dbo].[LISTAARTICOLICTRLINV] (
    [NOMEIMPOSTAZIONE] VARCHAR (80)    NOT NULL,
    [PROGRESSIVO]      NUMERIC (6)     NOT NULL,
    [ARTICOLO]         VARCHAR (50)    NULL,
    [NRRIFPARTITA]     VARCHAR (15)    NULL,
    [QUANTITA]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CODUBICAZIONE]    VARCHAR (10)    NULL,
    [UTENTEMODIFICA]   VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]     DATETIME        NOT NULL,
    CONSTRAINT [PK_LISTAARTICOLICTRLINV] PRIMARY KEY CLUSTERED ([NOMEIMPOSTAZIONE] ASC, [PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [CODARTICOLO]
    ON [dbo].[LISTAARTICOLICTRLINV]([ARTICOLO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [CODUBICAZIONE]
    ON [dbo].[LISTAARTICOLICTRLINV]([CODUBICAZIONE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [NRRIFPARTITAINV]
    ON [dbo].[LISTAARTICOLICTRLINV]([NRRIFPARTITA] ASC) WITH (FILLFACTOR = 90);


GO

/*  INSERT TRIGGER "TI_LISTAARTICOLICTRLINV" FOR TABLE "LISTAARTICOLICTRLINV"  */
CREATE TRIGGER TI_LISTAARTICOLICTRLINV ON LISTAARTICOLICTRLINV FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "IMPOSTAZIONICTRLINV" MUST EXIST WHEN INSERTING A CHILD IN "LISTAARTICOLICTRLINV"  */
    IF UPDATE(NOMEIMPOSTAZIONE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   IMPOSTAZIONICTRLINV T1, INSERTED T2
           WHERE  T1.NOMEIMPOSTAZIONE = T2.NOMEIMPOSTAZIONE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "IMPOSTAZIONICTRLINV". Cannot create child in "LISTAARTICOLICTRLINV".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_LISTAARTICOLICTRLINV" FOR TABLE "LISTAARTICOLICTRLINV"  */
CREATE TRIGGER TU_LISTAARTICOLICTRLINV ON LISTAARTICOLICTRLINV FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "IMPOSTAZIONICTRLINV" MUST EXIST WHEN UPDATING A CHILD IN "LISTAARTICOLICTRLINV"  */
      IF UPDATE(NOMEIMPOSTAZIONE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   IMPOSTAZIONICTRLINV T1, INSERTED T2
             WHERE  T1.NOMEIMPOSTAZIONE = T2.NOMEIMPOSTAZIONE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"IMPOSTAZIONICTRLINV" does not exist. Cannot modify child in "LISTAARTICOLICTRLINV".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[LISTAARTICOLICTRLINV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[LISTAARTICOLICTRLINV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[LISTAARTICOLICTRLINV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[LISTAARTICOLICTRLINV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[LISTAARTICOLICTRLINV] TO [Metodo98]
    AS [dbo];

