CREATE TABLE [dbo].[LISTINIARTICOLITRASF] (
    [NRLISTINO]      DECIMAL (5)     NOT NULL,
    [CODART]         VARCHAR (50)    NOT NULL,
    [UM]             VARCHAR (3)     NOT NULL,
    [PREZZO]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [PREZZOEURO]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [CODOPERAZIONE]  VARCHAR (5)     DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_LISTINIARTICOLITRASF] PRIMARY KEY CLUSTERED ([NRLISTINO] ASC, [CODART] ASC, [UM] ASC, [CODOPERAZIONE] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_LISTINIARTICOLITRASF" FOR TABLE "LISTINIARTICOLITRASF"  */
CREATE TRIGGER TI_LISTINIARTICOLITRASF ON LISTINIARTICOLITRASF FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABLISTINITRASFORMAZIONE" MUST EXIST WHEN INSERTING A CHILD IN "LISTINIARTICOLITRASF"  */
    IF UPDATE(NRLISTINO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABLISTINITRASFORMAZIONE T1, INSERTED T2
           WHERE  T1.NRLISTINO = T2.NRLISTINO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABLISTINITRASFORMAZIONE". Cannot create child in "LISTINIARTICOLITRASF".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_LISTINIARTICOLITRASF" FOR TABLE "LISTINIARTICOLITRASF"  */
CREATE TRIGGER TU_LISTINIARTICOLITRASF ON LISTINIARTICOLITRASF FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABLISTINITRASFORMAZIONE" MUST EXIST WHEN UPDATING A CHILD IN "LISTINIARTICOLITRASF"  */
      IF UPDATE(NRLISTINO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABLISTINITRASFORMAZIONE T1, INSERTED T2
             WHERE  T1.NRLISTINO = T2.NRLISTINO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABLISTINITRASFORMAZIONE" does not exist. Cannot ALTER COLUMN child in "LISTINIARTICOLITRASF".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[LISTINIARTICOLITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[LISTINIARTICOLITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[LISTINIARTICOLITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[LISTINIARTICOLITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[LISTINIARTICOLITRASF] TO [Metodo98]
    AS [dbo];

