CREATE TABLE [dbo].[MAGGIORAZIONITARIFFARIO] (
    [RIFTESTA]       DECIMAL (10)    NOT NULL,
    [RIFRIGA]        INT             NOT NULL,
    [IDMAGG]         INT             NOT NULL,
    [CODMAGG]        DECIMAL (5)     NULL,
    [TIPO]           SMALLINT        NULL,
    [MAGGIORAZIONE]  DECIMAL (16, 6) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_MAGGIORAZIONITARIFFARIO] PRIMARY KEY CLUSTERED ([RIFTESTA] ASC, [RIFRIGA] ASC, [IDMAGG] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MAGGIORAZIONITARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MAGGIORAZIONITARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MAGGIORAZIONITARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MAGGIORAZIONITARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MAGGIORAZIONITARIFFARIO] TO [Metodo98]
    AS [dbo];

