CREATE TABLE [dbo].[MB_PARAMETRIDOC] (
    [TIPODOC]        VARCHAR (3)  NOT NULL,
    [TIPO]           SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NULL,
    [DATAMODIFICA]   DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([TIPODOC] ASC)
);


GO

CREATE TRIGGER [dbo].[TD_MB_PARAMETRIDOC] ON [dbo].[MB_PARAMETRIDOC] FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)
 
    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
	/*  DELETE ALL CHILDREN IN "MB_PARAMETRIDEP"  */
    DELETE MB_PARAMETRIDEP
    FROM   MB_PARAMETRIDEP T2, DELETED T1
    WHERE  T2.TIPODOC = T1.TIPODOC
 
    RETURN
 
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END


GO
GRANT DELETE
    ON OBJECT::[dbo].[MB_PARAMETRIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MB_PARAMETRIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MB_PARAMETRIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MB_PARAMETRIDOC] TO [Metodo98]
    AS [dbo];

