CREATE TABLE [dbo].[MB_PARAMETRI] (
    [PROGRESSIVO]              DECIMAL (10) NOT NULL,
    [TIPOCALCOLOACQ]           SMALLINT     NULL,
    [NRLISTINO]                DECIMAL (5)  NULL,
    [TIPOUM1]                  VARCHAR (3)  NULL,
    [TIPOUM2]                  VARCHAR (3)  NULL,
    [NUMRISALITE]              INT          DEFAULT ((0)) NOT NULL,
    [BLOCCASENULL]             INT          DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA]           VARCHAR (25) NULL,
    [DATAMODIFICA]             DATETIME     NULL,
    [NUMMOVIMENTI]             INT          CONSTRAINT [DF_MB_PARAMETRI_NUMMOVIMENTI] DEFAULT ((0)) NULL,
    [CONSIDERACAUSALIVALORE]   SMALLINT     DEFAULT ((0)) NULL,
    [CALCOLASENZARIFPARTITA]   SMALLINT     DEFAULT ((0)) NULL,
    [TIPOCALCOLOACQRIFPARTITA] SMALLINT     DEFAULT ((0)) NULL,
    [NUMMOVIMENTIRIFPARTITA]   INT          DEFAULT ((0)) NULL,
    [NRLISTINORIFPARTITA]      DECIMAL (5)  NULL,
    [UMLISTINO]                VARCHAR (3)  NULL,
    [UMLISTINORIFPARTITA]      VARCHAR (3)  NULL,
    [TIPOCALCOLOCONTRATTIACQ]  SMALLINT     CONSTRAINT [DF_MB_PARAMETRI_TIPOCALCOLOCONTRATTIACQ] DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO

/*  INSERT TRIGGER "TU_MB_PARAMETRI" FOR TABLE "MB_PARAMETRI"  */
CREATE TRIGGER [dbo].TU_MB_PARAMETRI ON [dbo].[MB_PARAMETRI] AFTER UPDATE AS
BEGIN
    
	IF (UPDATE(TIPOCALCOLOACQ))
	DELETE FROM MB_ACQUISTATO_STORICO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    ROLLBACK  TRANSACTION
END


GO
GRANT DELETE
    ON OBJECT::[dbo].[MB_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MB_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MB_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MB_PARAMETRI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MB_PARAMETRI] TO [Metodo98]
    AS [dbo];

