CREATE TABLE [dbo].[MB_RAGGRUPPAMENTO_DOCUMENTI] (
    [CODICEDOC]         VARCHAR (3)  NOT NULL,
    [CODRAGGRUPPAMENTO] DECIMAL (10) NOT NULL,
    [CODDEPOSITO]       VARCHAR (10) NULL,
    [UTENTEMODIFICA]    VARCHAR (25) NULL,
    [DATAMODIFICA]      DATETIME     NULL,
    [PROVVIGIONI]       SMALLINT     DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODICEDOC] ASC, [CODRAGGRUPPAMENTO] ASC),
    CONSTRAINT [FK_MD_RAGGRUPPAMENTO] FOREIGN KEY ([CODRAGGRUPPAMENTO]) REFERENCES [dbo].[MB_RAGGRUPPAMENTI] ([CODICE])
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MB_RAGGRUPPAMENTO_DOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MB_RAGGRUPPAMENTO_DOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MB_RAGGRUPPAMENTO_DOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MB_RAGGRUPPAMENTO_DOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MB_RAGGRUPPAMENTO_DOCUMENTI] TO [Metodo98]
    AS [dbo];

