CREATE TABLE [dbo].[MODIFICHECAMPI] (
    [NOMETABELLA]    VARCHAR (50) NOT NULL,
    [NOMECAMPO]      VARCHAR (50) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_MODIFICHECAMPI] PRIMARY KEY CLUSTERED ([NOMETABELLA] ASC, [NOMECAMPO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MODIFICHECAMPI] TO [Metodo98]
    AS [dbo];

