CREATE TABLE [dbo].[MOVBLACKLISTQUADRI] (
    [ANNO]           SMALLINT        NOT NULL,
    [NRRIGA]         INT             NOT NULL,
    [TIPOAC]         VARCHAR (1)     NOT NULL,
    [IDTESTADOC]     DECIMAL (10)    NULL,
    [CODCLIFOR]      VARCHAR (7)     NULL,
    [DATADOC]        DATETIME        NULL,
    [IMPONIBILEEURO] DECIMAL (19, 4) NULL,
    [IMPOSTAEURO]    DECIMAL (19, 4) NULL,
    [CODIVA]         DECIMAL (5)     NULL,
    [TIPOOPERAZIONE] SMALLINT        NULL,
    [FLGBENISERVIZI] SMALLINT        NULL,
    [PARTITAIVA]     VARCHAR (12)    NULL,
    [CODFISCALE]     VARCHAR (16)    NULL,
    [PIVACF]         VARCHAR (25)    NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_MOVBLACKLISTQUADRI] PRIMARY KEY CLUSTERED ([ANNO] ASC, [TIPOAC] ASC, [NRRIGA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MOVBLACKLISTQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MOVBLACKLISTQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MOVBLACKLISTQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MOVBLACKLISTQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MOVBLACKLISTQUADRI] TO [Metodo98]
    AS [dbo];

