CREATE TABLE [dbo].[MOVELENCOCLIFORQUADRI] (
    [ANNO]                SMALLINT        NOT NULL,
    [TIPOQUADRO]          VARCHAR (2)     NOT NULL,
    [NRRIGA]              INT             NOT NULL,
    [NRREG]               DECIMAL (10)    NULL,
    [CODCLIFOR]           VARCHAR (7)     NULL,
    [DATAREG]             DATETIME        NULL,
    [DATADOC]             DATETIME        NULL,
    [IMPONIBILEEURO]      DECIMAL (19, 4) NULL,
    [IMPOSTAEURO]         DECIMAL (19, 4) NULL,
    [FLGCORRISPETTIVO]    SMALLINT        DEFAULT ((0)) NULL,
    [NUMFATTURA]          VARCHAR (15)    NULL,
    [FLGAUTOFATTURA]      SMALLINT        DEFAULT ((0)) NULL,
    [FLGREVERSECHARGE]    SMALLINT        DEFAULT ((0)) NULL,
    [FLGIVANONESPOSTAFT]  SMALLINT        DEFAULT ((0)) NULL,
    [FLGDOCRIEPILOGATIVO] SMALLINT        DEFAULT ((0)) NULL,
    [NRDOCRIEPILOGO]      SMALLINT        DEFAULT ((0)) NULL,
    [UTENTEMODIFICA]      VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]        DATETIME        NOT NULL,
    [MESERIFSANMARINO]    SMALLINT        CONSTRAINT [DF_MOVELENCOCLIFORQUADRI_MESERIFSANMARINO] DEFAULT ((0)) NOT NULL,
    [PARTITAIVA]          VARCHAR (12)    NULL,
    [CODFISCALE]          VARCHAR (16)    NULL,
    [PIVACF]              VARCHAR (25)    NULL,
    [TIPONOLEGGIO]        VARCHAR (1)     NULL,
    CONSTRAINT [PK_MOVELENCOCLIFORQUADRI] PRIMARY KEY CLUSTERED ([ANNO] ASC, [TIPOQUADRO] ASC, [NRRIGA] ASC, [MESERIFSANMARINO] ASC),
    CONSTRAINT [CHK_MOVELENCOCLIFORQUADRI_FLGAUTOFATTURA] CHECK ([FLGAUTOFATTURA]=(1) OR [FLGAUTOFATTURA]=(0)),
    CONSTRAINT [CHK_MOVELENCOCLIFORQUADRI_FLGCORRISPETTIVO] CHECK ([FLGCORRISPETTIVO]=(1) OR [FLGCORRISPETTIVO]=(0)),
    CONSTRAINT [CHK_MOVELENCOCLIFORQUADRI_FLGDOCRIEPILOGATIVO] CHECK ([FLGDOCRIEPILOGATIVO]=(1) OR [FLGDOCRIEPILOGATIVO]=(0)),
    CONSTRAINT [CHK_MOVELENCOCLIFORQUADRI_FLGIVANONESPOSTAFT] CHECK ([FLGIVANONESPOSTAFT]=(1) OR [FLGIVANONESPOSTAFT]=(0)),
    CONSTRAINT [CHK_MOVELENCOCLIFORQUADRI_FLGREVERSECHARGE] CHECK ([FLGREVERSECHARGE]=(1) OR [FLGREVERSECHARGE]=(0))
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MOVELENCOCLIFORQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MOVELENCOCLIFORQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MOVELENCOCLIFORQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MOVELENCOCLIFORQUADRI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MOVELENCOCLIFORQUADRI] TO [Metodo98]
    AS [dbo];

