CREATE TABLE [dbo].[PARAMCLASSLAVEST] (
    [CODICE]         VARCHAR (3)  NOT NULL,
    [OPERAZIONE]     VARCHAR (5)  CONSTRAINT [DF_PARAMCLASSLAVEST_OPERAZIONE] DEFAULT ('') NOT NULL,
    [VOCEBASE]       VARCHAR (3)  CONSTRAINT [DF_PARAMCLASSLAVEST_VOCEBASE] DEFAULT ('') NOT NULL,
    [IDVOCE]         VARCHAR (3)  CONSTRAINT [DF_PARAMCLASSLAVEST_IDVOCE] DEFAULT ('') NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [FK_PARAMCLASSLAVEST_CODICE] FOREIGN KEY ([CODICE]) REFERENCES [dbo].[TABPARAMETRICOMMCLI] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PARAMCLASSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARAMCLASSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARAMCLASSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARAMCLASSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARAMCLASSLAVEST] TO [Metodo98]
    AS [dbo];

