CREATE TABLE [dbo].[PARAMETRIMPS] (
    [CODICE]             VARCHAR (3)   NOT NULL,
    [DESCRIZIONE]        VARCHAR (80)  NULL,
    [CONTATORE]          DECIMAL (5)   NULL,
    [TIPORIGA]           VARCHAR (3)   NULL,
    [TIPOUM]             DECIMAL (5)   NULL,
    [NUMEROPERIODI]      SMALLINT      NULL,
    [TIPOPERIODORADICE]  SMALLINT      NULL,
    [TIPOPERIODONODO]    SMALLINT      NULL,
    [TIPOPERIODOFOGLIA]  SMALLINT      NULL,
    [TIPODATAPERIODO]    SMALLINT      NULL,
    [FLAGACCODAPERIODO]  SMALLINT      NULL,
    [AGENTEPREVISIONE]   VARCHAR (50)  NULL,
    [AGENTESPLIT]        VARCHAR (50)  NULL,
    [AGENTERIPORTO]      VARCHAR (50)  NULL,
    [AGENTEACCODA]       VARCHAR (50)  NULL,
    [NOTE]               VARCHAR (100) NULL,
    [UTENTEMODIFICA]     VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]       DATETIME      NOT NULL,
    [AGENTEARROTONDA]    VARCHAR (50)  NULL,
    [AGENTEARROTONDAMPP] VARCHAR (50)  NULL,
    CONSTRAINT [PK_PARAMETRIMPS] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PARAMETRIMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARAMETRIMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARAMETRIMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARAMETRIMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARAMETRIMPS] TO [Metodo98]
    AS [dbo];

