CREATE TABLE [dbo].[PARAMETRILISTECONS] (
    [CODICE]          VARCHAR (3)   NOT NULL,
    [DESCRIZIONE]     VARCHAR (80)  NULL,
    [CONTATORELISTA]  DECIMAL (5)   NULL,
    [TIPORIGA]        VARCHAR (3)   NULL,
    [TIPOINSERIMENTO] VARCHAR (3)   NULL,
    [CAUSALEDFLT]     SMALLINT      NULL,
    [NOTE]            VARCHAR (100) NULL,
    [UTENTEMODIFICA]  VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]    DATETIME      NOT NULL,
    CONSTRAINT [PK_PARAMETRILISTECONS] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE TRIGGER TD_PARAMETRILISTECONS ON  PARAMETRILISTECONS FOR DELETE AS
BEGIN

DECLARE
@NUMROWS INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* DELETE CASCADE */   /* per OGNI ACCESSILISTECONS in Relazione */
/* DELETE ALL CHILDREN IN "ACCESSILISTECONS" */
DELETE ACCESSILISTECONS
FROM ACCESSILISTECONS T2, DELETED T1
WHERE T2.CODLISTA = T1.CODICE

RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[PARAMETRILISTECONS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARAMETRILISTECONS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARAMETRILISTECONS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARAMETRILISTECONS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARAMETRILISTECONS] TO [Metodo98]
    AS [dbo];

