CREATE TABLE [dbo].[PARAMCLASSCOSTIDIR] (
    [PROGRESSIVO]    NUMERIC (10) NOT NULL,
    [CODICE]         VARCHAR (3)  NOT NULL,
    [CODGEN]         VARCHAR (7)  NULL,
    [CODCDC]         VARCHAR (10) NULL,
    [VOCEBASE]       VARCHAR (3)  CONSTRAINT [DF_PARAMCLASSCOSTIDIR_VOCEBASE] DEFAULT ('') NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [FK_PARAMCLASSCOSTIDIR_CODICE] FOREIGN KEY ([CODICE]) REFERENCES [dbo].[TABPARAMETRICOMMCLI] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PARAMCLASSCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARAMCLASSCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARAMCLASSCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARAMCLASSCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARAMCLASSCOSTIDIR] TO [Metodo98]
    AS [dbo];

