CREATE TABLE [dbo].[PARAMETRIORDPROD] (
    [CODICE]                 VARCHAR (3)   NOT NULL,
    [DESCRIZIONE]            VARCHAR (80)  NULL,
    [TIPOORDINE]             SMALLINT      DEFAULT (0) NULL,
    [TIPOUMORDINE]           DECIMAL (5)   NULL,
    [TIPOUMIMPEGNI]          DECIMAL (5)   NULL,
    [FLGCONSIDERASCARTI]     SMALLINT      DEFAULT (0) NULL,
    [CAUSALEORDINE]          DECIMAL (5)   NULL,
    [CODDEPOSITOORD]         VARCHAR (10)  NULL,
    [SEQDEPORD]              VARCHAR (5)   NULL,
    [CAUSALEORDCOLL]         DECIMAL (5)   NULL,
    [CODDEPORDCOLL]          VARCHAR (10)  NULL,
    [SEQDEPORDCOLL]          VARCHAR (5)   NULL,
    [CAUSALEIMPEGNO]         DECIMAL (5)   NULL,
    [CODDEPOSITOIMP]         VARCHAR (10)  NULL,
    [SEQDEPIMP]              VARCHAR (5)   NULL,
    [CAUSALEIMPCOLL]         DECIMAL (5)   NULL,
    [CODDEPIMPCOLL]          VARCHAR (10)  NULL,
    [SEQDEPIMPCOLL]          VARCHAR (5)   NULL,
    [CAUSALEMOVORD]          DECIMAL (5)   NULL,
    [CODDEPOSITOMOVORD]      VARCHAR (10)  NULL,
    [SEQDEPMOVORD]           VARCHAR (5)   NULL,
    [CAUSALEMOVORDCOLL]      DECIMAL (5)   NULL,
    [CODDEPMOVORDCOLL]       VARCHAR (10)  NULL,
    [SEQDEPMOVORDCOLL]       VARCHAR (5)   NULL,
    [CAUSALEMOVIMP]          DECIMAL (5)   NULL,
    [CODDEPOSITOMOVIMP]      VARCHAR (10)  NULL,
    [SEQDEPMOVIMP]           VARCHAR (5)   NULL,
    [CAUSALEMOVIMPCOLL]      DECIMAL (5)   NULL,
    [CODDEPMOVIMPCOLL]       VARCHAR (10)  NULL,
    [SEQDEPMOVIMPCOLL]       VARCHAR (5)   NULL,
    [CAUSSCARTOORD]          DECIMAL (5)   NULL,
    [CODDEPOSITOSCRORD]      VARCHAR (10)  NULL,
    [SEQDEPSCRORD]           VARCHAR (5)   NULL,
    [CAUSSCARTOORDCOLL]      DECIMAL (5)   NULL,
    [CODDEPSCRORDCOLL]       VARCHAR (10)  NULL,
    [SEQDEPSCRORDCOLL]       VARCHAR (5)   NULL,
    [CAUSSCARTOIMP]          DECIMAL (5)   NULL,
    [CODDEPOSITOSCRIMP]      VARCHAR (10)  NULL,
    [SEQDEPSCRIMP]           VARCHAR (5)   NULL,
    [CAUSSCARTOIMPCOLL]      DECIMAL (5)   NULL,
    [CODDEPSCRIMPCOLL]       VARCHAR (10)  NULL,
    [SEQDEPSCRIMPCOLL]       VARCHAR (5)   NULL,
    [ANNOTAZIONI]            VARCHAR (255) NULL,
    [DATAMODIFICA]           DATETIME      NOT NULL,
    [UTENTEMODIFICA]         VARCHAR (25)  NOT NULL,
    [TIPOVALPREVORD]         SMALLINT      NULL,
    [LISTINOVALPREVORD]      DECIMAL (5)   NULL,
    [LISTINOTRASFVALPREVORD] DECIMAL (5)   NULL,
    [IDCOSTOVALPREVORD]      VARCHAR (10)  NULL,
    [TIPOVALCONSORD]         SMALLINT      NULL,
    [LISTINOVALCONSORD]      DECIMAL (5)   NULL,
    [LISTINOTRASFVALCONSORD] DECIMAL (5)   NULL,
    [IDCOSTOVALCONSORD]      VARCHAR (10)  NULL,
    [TIPOVALPREVIMP]         SMALLINT      NULL,
    [LISTINOVALPREVIMP]      DECIMAL (5)   NULL,
    [IDCOSTOVALPREVIMP]      VARCHAR (10)  NULL,
    [TIPOVALCONSIMP]         SMALLINT      NULL,
    [LISTINOVALCONSIMP]      DECIMAL (5)   NULL,
    [IDCOSTOVALCONSIMP]      VARCHAR (10)  NULL,
    [CONSLISTINOVALPREVORD]  SMALLINT      NULL,
    [CONSLISTINOVALCONSORD]  SMALLINT      NULL,
    [CONSLISTINOVALCONSIMP]  SMALLINT      NULL,
    [CONSLISTINOVALPREVIMP]  SMALLINT      NULL,
    [VALORIZZAPREVENTIVI]    SMALLINT      NULL,
    [VALORIZZACONSUNTIVI]    SMALLINT      NULL,
    [QUADRATURAPARTITE]      SMALLINT      DEFAULT (0) NULL,
    [TIPOUMPREZZO]           DECIMAL (5)   CONSTRAINT [DF_PARAMETRIORDPROD_TIPOUMPREZZO] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_PARAMETRIORDPROD] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_CONSLISTINOVALCON_PARAMETR] CHECK ([CONSLISTINOVALCONSORD] = 2 or [CONSLISTINOVALCONSORD] = 1 or [CONSLISTINOVALCONSORD] = 0),
    CONSTRAINT [CKC_CONSLISTINOVALCONSIMP_PARA] CHECK ([CONSLISTINOVALCONSIMP] = 2 or [CONSLISTINOVALCONSIMP] = 1 or [CONSLISTINOVALCONSIMP] = 0),
    CONSTRAINT [CKC_CONSLISTINOVALPRE_PARAMETR] CHECK ([CONSLISTINOVALPREVORD] = 2 or [CONSLISTINOVALPREVORD] = 1 or [CONSLISTINOVALPREVORD] = 0),
    CONSTRAINT [CKC_CONSLISTINOVALPREVIMP_PARA] CHECK ([CONSLISTINOVALPREVIMP] = 2 or [CONSLISTINOVALPREVIMP] = 1 or [CONSLISTINOVALPREVIMP] = 0),
    CONSTRAINT [CKC_FLGCONSIDERASCART_PARAMETR] CHECK ([FLGCONSIDERASCARTI] = 0 or [FLGCONSIDERASCARTI] = 1),
    CONSTRAINT [CKC_TIPOORDINE_PARAMETR] CHECK ([TIPOORDINE] >= 0 and [TIPOORDINE] <= 2 and ([TIPOORDINE] = 2 or [TIPOORDINE] = 1 or [TIPOORDINE] = 0)),
    CONSTRAINT [CKC_TIPOVALCONSIMP_PARAMETR] CHECK ([TIPOVALCONSIMP] = 5 or [TIPOVALCONSIMP] = 4 or [TIPOVALCONSIMP] = 3 or [TIPOVALCONSIMP] = 2 or [TIPOVALCONSIMP] = 1 or [TIPOVALCONSIMP] = 0),
    CONSTRAINT [CKC_TIPOVALCONSORD_PARAMETR] CHECK ([TIPOVALCONSORD] = 5 or [TIPOVALCONSORD] = 4 or [TIPOVALCONSORD] = 3 or [TIPOVALCONSORD] = 2 or [TIPOVALCONSORD] = 1 or [TIPOVALCONSORD] = 0),
    CONSTRAINT [CKC_TIPOVALPREVIMP_PARAMETR] CHECK ([TIPOVALPREVIMP] = 5 or [TIPOVALPREVIMP] = 4 or [TIPOVALPREVIMP] = 3 or [TIPOVALPREVIMP] = 2 or [TIPOVALPREVIMP] = 1 or [TIPOVALPREVIMP] = 0),
    CONSTRAINT [CKC_TIPOVALPREVORD_PARAMETR] CHECK ([TIPOVALPREVORD] = 5 or [TIPOVALPREVORD] = 4 or [TIPOVALPREVORD] = 3 or [TIPOVALPREVORD] = 2 or [TIPOVALPREVORD] = 1 or [TIPOVALPREVORD] = 0),
    CONSTRAINT [CKC_VALORIZZACONSUNTI_PARAMETR] CHECK ([VALORIZZACONSUNTIVI] = 2 or [VALORIZZACONSUNTIVI] = 1 or [VALORIZZACONSUNTIVI] = 0),
    CONSTRAINT [CKC_VALORIZZAPREVENTI_PARAMETR] CHECK ([VALORIZZAPREVENTIVI] = 2 or [VALORIZZAPREVENTIVI] = 1 or [VALORIZZAPREVENTIVI] = 0)
);


GO

/*  UPDATE TRIGGER "TU_PARAMETRIORDPROD" FOR TABLE "PARAMETRIORDPROD"  */
CREATE TRIGGER TU_PARAMETRIORDPROD ON PARAMETRIORDPROD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  ALTER COLUMN PARENT CODE OF "PARAMETRIORDPROD" FOR ALL CHILDREN IN "DOCUMENTICLATTIVO"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE DOCUMENTICLATTIVO
          SET   CODORDINE = I1.CODICE
         FROM   DOCUMENTICLATTIVO T2, INSERTED I1, DELETED D1
         WHERE  T2.CODORDINE = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "PARAMETRIORDPROD" FOR ALL CHILDREN IN "DOCUMENTICLPASSIVO"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE DOCUMENTICLPASSIVO
          SET   CODORDINE = I1.CODICE
         FROM   DOCUMENTICLPASSIVO T2, INSERTED I1, DELETED D1
         WHERE  T2.CODORDINE = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "PARAMETRIORDPROD" FOR ALL CHILDREN IN "RIGHEORDPROD"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE RIGHEORDPROD
          SET   CODICEORD = I1.CODICE
         FROM   RIGHEORDPROD T2, INSERTED I1, DELETED D1
         WHERE  T2.CODICEORD = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
CREATE TRIGGER TD_PARAMETRIORDPROD ON PARAMETRIORDPROD FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "DOCUMENTICLATTIVO"  */
    DELETE DOCUMENTICLATTIVO
    FROM   DOCUMENTICLATTIVO T2, DELETED T1
    WHERE  T2.CODORDINE = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "DOCUMENTICLPASSIVO"  */
    DELETE DOCUMENTICLPASSIVO
    FROM   DOCUMENTICLPASSIVO T2, DELETED T1
    WHERE  T2.CODORDINE = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "DOCUMENTICLFASE"  */
    DELETE DOCUMENTICLFASE
    FROM   DOCUMENTICLFASE T2, DELETED T1
    WHERE  T2.CODORDINE = T1.CODICE

    /*  DELETE ALL CHILDREN IN "RIGHEORDPROD"  */
    DELETE RIGHEORDPROD
    FROM   RIGHEORDPROD T2, DELETED T1
    WHERE  T2.CODICEORD = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[PARAMETRIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARAMETRIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARAMETRIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARAMETRIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARAMETRIORDPROD] TO [Metodo98]
    AS [dbo];

