CREATE TABLE [dbo].[PARDOCCC] (
    [CODDOC]         VARCHAR (3)  NOT NULL,
    [CODSPESA]       SMALLINT     NOT NULL,
    [CODGENERICO]    VARCHAR (7)  NULL,
    [CODIVA]         DECIMAL (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_PARDOCCC] PRIMARY KEY CLUSTERED ([CODDOC] ASC, [CODSPESA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PARDOCCC_CODDOC] FOREIGN KEY ([CODDOC]) REFERENCES [dbo].[PARAMETRIDOC] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PARDOCCC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARDOCCC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARDOCCC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARDOCCC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARDOCCC] TO [Metodo98]
    AS [dbo];

