CREATE TABLE [dbo].[PRIORITADEPOSITIPROGPROD] (
    [NOMEPIANIF]     VARCHAR (30) NOT NULL,
    [CODDEPOSITO]    VARCHAR (10) NOT NULL,
    [PRIORITA]       INT          NULL,
    [UTENTEMODIFICA] VARCHAR (25) NULL,
    [DATAMODIFICA]   DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([NOMEPIANIF] ASC, [CODDEPOSITO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PRIORITADEPOSITIPROGPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PRIORITADEPOSITIPROGPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PRIORITADEPOSITIPROGPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PRIORITADEPOSITIPROGPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PRIORITADEPOSITIPROGPROD] TO [Metodo98]
    AS [dbo];

