CREATE TABLE [dbo].[PROGPRODUZIONEDOC] (
    [NOMEPIANIF]     VARCHAR (30) NOT NULL,
    [PROG_ID]        DECIMAL (10) NOT NULL,
    [IDTESTA]        DECIMAL (10) NOT NULL,
    [IDRIGA]         INT          NOT NULL,
    [VALIDO]         SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [IDIMPEGNO]      INT          DEFAULT ((0)) NOT NULL,
    [RIF_ID]         DECIMAL (10) DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([NOMEPIANIF] ASC, [PROG_ID] ASC, [IDTESTA] ASC, [IDRIGA] ASC, [IDIMPEGNO] ASC, [RIF_ID] ASC),
    CONSTRAINT [CKC_VALIDO_PROGPROD] CHECK ([VALIDO] = 0 or [VALIDO] = 1)
);


GO

/*  INSERT TRIGGER "TI_PROGPRODUZIONEDOC" FOR TABLE "PROGPRODUZIONEDOC"  */
CREATE TRIGGER TI_PROGPRODUZIONEDOC ON PROGPRODUZIONEDOC FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "IMPOSTAZIONIPROGPROD" MUST EXIST WHEN INSERTING A CHILD IN "PROGPRODUZIONEDOC"  */
    IF UPDATE(NOMEPIANIF)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   IMPOSTAZIONIPROGPROD T1, INSERTED T2
           WHERE  T1.NOMEPIANIF = T2.NOMEPIANIF) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "IMPOSTAZIONIPROGPROD". Cannot create child in "PROGPRODUZIONEDOC".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_PROGPRODUZIONEDOC" FOR TABLE "PROGPRODUZIONEDOC"  */
CREATE TRIGGER TU_PROGPRODUZIONEDOC ON PROGPRODUZIONEDOC FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "IMPOSTAZIONIPROGPROD" MUST EXIST WHEN UPDATING A CHILD IN "PROGPRODUZIONEDOC"  */
      IF UPDATE(NOMEPIANIF)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   IMPOSTAZIONIPROGPROD T1, INSERTED T2
             WHERE  T1.NOMEPIANIF = T2.NOMEPIANIF) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"IMPOSTAZIONIPROGPROD" does not exist. Cannot modify child in "PROGPRODUZIONEDOC".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[PROGPRODUZIONEDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PROGPRODUZIONEDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PROGPRODUZIONEDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PROGPRODUZIONEDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PROGPRODUZIONEDOC] TO [Metodo98]
    AS [dbo];

