CREATE TABLE [dbo].[PROGRESSIVISTAMPA] (
    [NRREGISTRO]      DECIMAL (5)     NOT NULL,
    [PROGREG]         DECIMAL (10)    NULL,
    [PAGINAFIN]       DECIMAL (9)     NULL,
    [SALDO]           DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SALDOEURO]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [DATAFIN]         DATETIME        NULL,
    [NUMRECSEL]       INT             NULL,
    [NOTE]            VARCHAR (25)    NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    [Esercizio]       DECIMAL (5)     NOT NULL,
    [CREDRESIDUO]     DECIMAL (19, 4) DEFAULT (0) NULL,
    [CREDRESIDUOEURO] DECIMAL (19, 4) DEFAULT (0) NULL,
    [DATAFINRELIVA]   DATETIME        NULL,
    CONSTRAINT [PK_PROGRESSIVISTAMPA] PRIMARY KEY CLUSTERED ([Esercizio] ASC, [NRREGISTRO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PROGRESSIVISTAMPA_NRREGISTRO] FOREIGN KEY ([NRREGISTRO]) REFERENCES [dbo].[TIPOREGISTROIVA] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PROGRESSIVISTAMPA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PROGRESSIVISTAMPA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PROGRESSIVISTAMPA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PROGRESSIVISTAMPA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PROGRESSIVISTAMPA] TO [Metodo98]
    AS [dbo];

