CREATE TABLE [dbo].[PROMOZIONI_LIVELLIMERCEOLOGICI] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [CODICE]         VARCHAR (50) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PROMOZIONI_LIVELLIMERCEOLOGICI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PROMOZIONI_LIVELLIMERCEOLOGICI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PROMOZIONI_LIVELLIMERCEOLOGICI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PROMOZIONI_LIVELLIMERCEOLOGICI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PROMOZIONI_LIVELLIMERCEOLOGICI] TO [Metodo98]
    AS [dbo];

