CREATE TABLE [dbo].[REGOLEPREZZIESTESI] (
    [PROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [CODGRUPPOPREZZICF]  DECIMAL (5)     CONSTRAINT [DF__REGOLEPRE__CODGR] DEFAULT ((0)) NOT NULL,
    [CODCLIFOR]          VARCHAR (7)     CONSTRAINT [DF__REGOLEPRE__CODCL] DEFAULT ('') NOT NULL,
    [CODDESTINAZIONE]    DECIMAL (5)     CONSTRAINT [DF__REGOLEPRE__CODDE] DEFAULT ((0)) NOT NULL,
    [CODART]             VARCHAR (50)    CONSTRAINT [DF__REGOLEPRE__CODAR] DEFAULT ('') NOT NULL,
    [CODGRUPPOPREZZIMAG] DECIMAL (5)     CONSTRAINT [DF_REGOLEPREZZITESTE_CODGRUPPOPREZZIMAG] DEFAULT ((0)) NULL,
    [INIZIOVALIDITA]     DATETIME        CONSTRAINT [DF__REGOLEPRE__INIZI] DEFAULT (getdate()) NOT NULL,
    [FINEVALIDITA]       DATETIME        CONSTRAINT [DF__REGOLEPRE__FINEV] DEFAULT (getdate()) NOT NULL,
    [FAMIGLIA]           DECIMAL (5)     CONSTRAINT [DF_REGOLEPREZZIESTESI_FAMIGLIA] DEFAULT ((0)) NOT NULL,
    [REPARTO]            DECIMAL (5)     CONSTRAINT [DF_REGOLEPREZZIESTESI_REPARTO] DEFAULT ((0)) NOT NULL,
    [TIPOARROT]          VARCHAR (1)     CONSTRAINT [DF__REGOLEPRE__TIPOA] DEFAULT ('N') NULL,
    [ARROTAVALUTA]       DECIMAL (19, 4) CONSTRAINT [DF__REGOLEPRE__ARROT] DEFAULT ((0)) NOT NULL,
    [ARROTONDA]          DECIMAL (19, 4) NOT NULL,
    [CODARTTIPOLOGIA]    VARCHAR (50)    NULL,
    [VARIANTI]           SMALLINT        CONSTRAINT [DF__REGOLEPRE__VARIA] DEFAULT ((0)) NULL,
    [UM]                 VARCHAR (3)     CONSTRAINT [DF__REGOLEPREZZI__UM] DEFAULT ('') NOT NULL,
    [TIPORIGA]           SMALLINT        CONSTRAINT [DF__REGOLEPRE__TIPOR] DEFAULT ((0)) NOT NULL,
    [QTAMINIMA]          DECIMAL (16, 6) CONSTRAINT [DF__REGOLEPRE__QTAMI] DEFAULT ((1)) NOT NULL,
    [IMPORTOVALUTA]      DECIMAL (19, 6) NULL,
    [IMPORTO]            DECIMAL (19, 6) NULL,
    [TIPOSCONTO]         SMALLINT        NOT NULL,
    [PROGRESSIVOCTR]     DECIMAL (5)     CONSTRAINT [DF__REGOLEPRE__PROGR] DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [CODSETTORE]         DECIMAL (5)     DEFAULT ((0)) NULL,
    [CODZONA]            DECIMAL (5)     DEFAULT ((0)) NULL,
    [CODCATEGORIA]       DECIMAL (5)     DEFAULT ((0)) NULL,
    [CLIFOR]             SMALLINT        DEFAULT ((0)) NULL,
    [TipoEspositore]     SMALLINT        DEFAULT ((0)) NULL,
    [CODICEPRIMARIO]     VARCHAR (50)    DEFAULT ('') NULL,
    [VARESPLICITE]       VARCHAR (255)   DEFAULT ('') NULL,
    [CODFEATURE]         INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_REGOLEPREZZIESTESI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOARROT_REGOLEPREZZIESTESI] CHECK ([TIPOARROT]='N' OR [TIPOARROT]='D' OR [TIPOARROT]='E' OR [TIPOARROT]='C')
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[REGOLEPREZZIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[REGOLEPREZZIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[REGOLEPREZZIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[REGOLEPREZZIESTESI] TO [Metodo98]
    AS [dbo];

