CREATE TABLE [dbo].[REGOLESCONTIESTESI] (
    [PROGRESSIVOREGOLETESTE] DECIMAL (10) NOT NULL,
    [IDRIGA]                 DECIMAL (10) NOT NULL,
    [CODSCONTO]              VARCHAR (5)  NOT NULL,
    [SCONTO]                 VARCHAR (20) CONSTRAINT [DF__REGOLESCO__SCONT] DEFAULT ('') NOT NULL,
    [POSIZIONE]              INT          NULL,
    [UTENTEMODIFICA]         VARCHAR (25) NOT NULL,
    [DATAMODIFICA]           DATETIME     NOT NULL,
    [INIZIOVALIDITA]         DATETIME     NOT NULL,
    [FINEVALIDITA]           DATETIME     NOT NULL,
    CONSTRAINT [PK_REGOLESCONTIIRIGHE] PRIMARY KEY CLUSTERED ([IDRIGA] ASC),
    CONSTRAINT [FK_REGOLESCONTIESTESI_REGOLEPREZZIESTESI] FOREIGN KEY ([PROGRESSIVOREGOLETESTE]) REFERENCES [dbo].[REGOLEPREZZIESTESI] ([PROGRESSIVO]) ON DELETE CASCADE,
    CONSTRAINT [FK_REGOLESCONTIESTESI_SCONTIESTESI] FOREIGN KEY ([CODSCONTO]) REFERENCES [dbo].[SCONTIESTESI] ([CODSCONTO])
);


GO
CREATE NONCLUSTERED INDEX [IX_REGOLESCONTIESTESI]
    ON [dbo].[REGOLESCONTIESTESI]([CODSCONTO] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[REGOLESCONTIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[REGOLESCONTIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[REGOLESCONTIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[REGOLESCONTIESTESI] TO [Metodo98]
    AS [dbo];

