CREATE TABLE [dbo].[REPOSITORYIMGS] (
    [CODART]            VARCHAR (80)  NOT NULL,
    [CODREPOSITORYPATH] VARCHAR (20)  NOT NULL,
    [ESTENSIONE]        VARCHAR (30)  NOT NULL,
    [NOMEFILE]          VARCHAR (250) NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]      DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([CODART] ASC, [CODREPOSITORYPATH] ASC, [NOMEFILE] ASC, [ESTENSIONE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[REPOSITORYIMGS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[REPOSITORYIMGS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[REPOSITORYIMGS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[REPOSITORYIMGS] TO [Metodo98]
    AS [dbo];

