CREATE TABLE [dbo].[RETTINTRASERVIZI] (
    [TIPO]           SMALLINT        NOT NULL,
    [NRRIGA]         DECIMAL (10)    NOT NULL,
    [ESERCIZIO]      DECIMAL (5)     NOT NULL,
    [MESESTAMPA]     SMALLINT        NULL,
    [TRIMSTAMPA]     SMALLINT        NULL,
    [ANNOSTAMPA]     SMALLINT        NULL,
    [SEZDOGANALE]    DECIMAL (6)     NULL,
    [ANNO]           SMALLINT        NULL,
    [PROTDICH]       DECIMAL (6)     NULL,
    [PROGSEZ3]       DECIMAL (5)     NULL,
    [ISOST]          VARCHAR (3)     NULL,
    [PARTIVACF]      VARCHAR (12)    NULL,
    [VALEURO]        DECIMAL (19, 4) CONSTRAINT [DF_RETTINTRSERV_VALEURO] DEFAULT ((0)) NULL,
    [VALVALUTA]      DECIMAL (19, 4) CONSTRAINT [DF_RETTINTRSERV_VALVALUTA] DEFAULT ((0)) NULL,
    [NRFATTURA]      VARCHAR (15)    NULL,
    [DATAFATTURA]    DATETIME        NULL,
    [CODSERVIZIO]    VARCHAR (6)     NULL,
    [MODEROGAZIONE]  VARCHAR (1)     NULL,
    [MODINCASSO]     VARCHAR (1)     NULL,
    [PAESEPAG]       VARCHAR (2)     NULL,
    [IDTESTADOC]     DECIMAL (10)    NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_RETTINTRASERVIZI] PRIMARY KEY CLUSTERED ([TIPO] ASC, [NRRIGA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RETTINTRASERVIZI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RETTINTRASERVIZI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RETTINTRASERVIZI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RETTINTRASERVIZI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RETTINTRASERVIZI] TO [Metodo98]
    AS [dbo];

