CREATE TABLE [dbo].[RETTIFICHEINTRA] (
    [TIPO]           SMALLINT        NOT NULL,
    [NRRIGA]         DECIMAL (10)    NOT NULL,
    [ESERCIZIO]      DECIMAL (5)     NOT NULL,
    [MESESTAMPA]     SMALLINT        NULL,
    [TRIMSTAMPA]     SMALLINT        NULL,
    [ANNOSTAMPA]     SMALLINT        NULL,
    [MESE]           SMALLINT        NULL,
    [TRIM]           SMALLINT        NULL,
    [ANNO]           SMALLINT        NULL,
    [ISOST]          VARCHAR (3)     NULL,
    [PARTIVACF]      VARCHAR (12)    NULL,
    [SEGNO]          SMALLINT        NULL,
    [VALLIRE]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [VALVALUTA]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [NATTRANS]       VARCHAR (1)     NULL,
    [NOMENCLCOMB]    VARCHAR (8)     NULL,
    [VALSTAT]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IDTESTADOC]     DECIMAL (10)    NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [VALEURO]        DECIMAL (19, 4) DEFAULT (0) NULL,
    [VALSTATEURO]    DECIMAL (19, 4) DEFAULT (0) NULL,
    CONSTRAINT [PK_RETTIFICHEINTRA] PRIMARY KEY CLUSTERED ([TIPO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [RETINT_ANNSTP]
    ON [dbo].[RETTIFICHEINTRA]([ANNOSTAMPA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RETINT_MESTP]
    ON [dbo].[RETTIFICHEINTRA]([MESESTAMPA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RETINT_TRSTP]
    ON [dbo].[RETTIFICHEINTRA]([TRIMSTAMPA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RETTIFICHEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RETTIFICHEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RETTIFICHEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RETTIFICHEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RETTIFICHEINTRA] TO [Metodo98]
    AS [dbo];

