CREATE TABLE [dbo].[RIGHELISTATRASF] (
    [IDTESTA]            DECIMAL (10)    NOT NULL,
    [IDRIGA]             INT             NOT NULL,
    [POSIZIONE]          INT             NULL,
    [RIFTESTACOMM]       DECIMAL (10)    NULL,
    [RIFRIGAORD]         INT             NULL,
    [RIFRIGAIMP]         INT             NULL,
    [CODART]             VARCHAR (50)    NULL,
    [QTATRASFGESTIONE]   DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UMGEST]             VARCHAR (3)     NOT NULL,
    [QTATRASFPREZZO]     DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UMPREZZO]           VARCHAR (3)     NOT NULL,
    [QTAPREZZOMAN]       SMALLINT        DEFAULT (0) NULL,
    [QTATRASF1MAG]       DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QTA1MAGMAN]         SMALLINT        DEFAULT (0) NULL,
    [QTATRASF2MAG]       DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QTA2MAGMAN]         SMALLINT        DEFAULT (0) NULL,
    [PARTITAASSEGNATA]   VARCHAR (15)    NULL,
    [CODCLIFOR]          VARCHAR (7)     NULL,
    [DEPOSITO]           VARCHAR (10)    NULL,
    [UBICAZIONE]         VARCHAR (10)    NULL,
    [CONTOCDC]           VARCHAR (10)    NULL,
    [DEPOSITOCOLL]       VARCHAR (10)    NULL,
    [UBICAZIONECOLL]     VARCHAR (10)    NULL,
    [CONTOCDCCOLL]       VARCHAR (10)    NULL,
    [COSTOUNITTRASF]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [COSTOTOTTRASF]      DECIMAL (19, 6) DEFAULT (0) NULL,
    [COSTOUNITTRASFEURO] DECIMAL (19, 6) DEFAULT (0) NULL,
    [COSTOTOTTRASFEURO]  DECIMAL (19, 6) DEFAULT (0) NULL,
    [STATORIGA]          SMALLINT        DEFAULT (0) NULL,
    [NOTE]               VARCHAR (100)   NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [QTAGESTIONEDOC]     NUMERIC (16, 6) DEFAULT (0) NULL,
    [QTAGESTIONERES]     NUMERIC (16, 6) DEFAULT (0) NULL,
    [QTAPREZZORES]       NUMERIC (16, 6) DEFAULT (0) NULL,
    [QTA1MAGRES]         NUMERIC (16, 6) DEFAULT (0) NULL,
    [QTA2MAGRES]         NUMERIC (16, 6) DEFAULT (0) NULL,
    [FLAGRIGA]           SMALLINT        NULL,
    [UM1MAG]             VARCHAR (3)     NULL,
    [UM2MAG]             VARCHAR (3)     NULL,
    [DATADISPONIBILITA]  DATETIME        NULL,
    [RIFCOMMCLI]         VARCHAR (30)    NULL,
    [RIFERIMENTI]        VARCHAR (100)   CONSTRAINT [DF_RIFERIMENTI] DEFAULT ('') NULL,
    [RIFANNOBOLLA]       SMALLINT        CONSTRAINT [DF_PARAMETRILISTETRASF_RIFANNOBOLLA] DEFAULT (0) NULL,
    [RIFNUMEROBOLLA]     INT             CONSTRAINT [DF_PARAMETRILISTETRASF_RIFNUMEROBOLLA] DEFAULT (0) NULL,
    [TIPOMATERIALE]      SMALLINT        CONSTRAINT [DF_PARAMETRILISTETRASF_TIPOMATERIALE] DEFAULT (0) NULL,
    [DESCRIZIONEART]     VARCHAR (255)   CONSTRAINT [DF_PARAMETRILISTETRASF_DESCRIZIONEART] DEFAULT ('') NULL,
    CONSTRAINT [PK_RIGHELISTATRASF] PRIMARY KEY CLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_QTA1MAGMAN_RIGHELISTR] CHECK ([QTA1MAGMAN] = 0 or [QTA1MAGMAN] = 1),
    CONSTRAINT [CKC_QTA2MAGMAN_RIGHELISTR] CHECK ([QTA2MAGMAN] = 0 or [QTA2MAGMAN] = 1),
    CONSTRAINT [CKC_QTAPREZZOMAN_RIGHELISTR] CHECK ([QTAPREZZOMAN] = 0 or [QTAPREZZOMAN] = 1),
    CONSTRAINT [CKC_STATORIGA_RIGHELISTRASF] CHECK ([STATORIGA] = 3 or [STATORIGA] = 2 or [STATORIGA] = 1 or [STATORIGA] = 0)
);


GO

/*  UPDATE TRIGGER "TU_RIGHELISTATRASF" FOR TABLE "RIGHELISTATRASF"  */
CREATE TRIGGER TU_RIGHELISTATRASF ON RIGHELISTATRASF FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TESTELISTATRASF" MUST EXIST WHEN UPDATING A CHILD IN "RIGHELISTATRASF"  */
      IF UPDATE(IDTESTA)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TESTELISTATRASF T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.IDTESTA) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TESTELISTATRASF" does not exist. Cannot ALTER COLUMN child in "RIGHELISTATRASF".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
CREATE TRIGGER TD_RIGHELISTATRASF ON RIGHELISTATRASF FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
    /*  DELETE ALL CHILDREN IN "RIGHELSTTRASFMATRICOLE"  */
    DELETE RIGHELSTTRASFMATRICOLE
    FROM   RIGHELSTTRASFMATRICOLE T2, DELETED T1
    WHERE  T2.IDTESTA = T1.IDTESTA
     AND   T2.IDRIGA = T1.IDRIGA
    
    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  INSERT TRIGGER "TI_RIGHELISTATRASF" FOR TABLE "RIGHELISTATRASF"  */
CREATE TRIGGER TI_RIGHELISTATRASF ON RIGHELISTATRASF FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TESTELISTATRASF" MUST EXIST WHEN INSERTING A CHILD IN "RIGHELISTATRASF"  */
    IF UPDATE(IDTESTA)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TESTELISTATRASF T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.IDTESTA) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TESTELISTATRASF". Cannot create child in "RIGHELISTATRASF".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHELISTATRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHELISTATRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHELISTATRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHELISTATRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHELISTATRASF] TO [Metodo98]
    AS [dbo];

