CREATE TABLE [dbo].[RIGHEDETTAGLIOPACKINGLIST] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [RIFNRRIGA]      INT             NOT NULL,
    [NRRIGA]         INT             NOT NULL,
    [CODARTICOLO]    VARCHAR (50)    NULL,
    [PESONETTO]      DECIMAL (16, 6) CONSTRAINT [DF_RIGHEDETTAGLIOPACKINGLIST_PESONETTO] DEFAULT (0) NULL,
    [QTA]            DECIMAL (16, 6) CONSTRAINT [DF_RIGHEDETTAGLIOPACKINGLIST_QUANTITA] DEFAULT (0) NULL,
    [UM]             VARCHAR (3)     NULL,
    [CUBATURA]       DECIMAL (16, 6) CONSTRAINT [DF_RIGHEDETTAGLIOPACKINGLIST_CUBATURA] DEFAULT (0) NULL,
    [POSIZIONE]      INT             NULL,
    [FLAGRIGA]       SMALLINT        NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHEDETTAGLIOPACKINGLIST] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [RIFNRRIGA] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEDETTAGLIOPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEDETTAGLIOPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEDETTAGLIOPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEDETTAGLIOPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEDETTAGLIOPACKINGLIST] TO [Metodo98]
    AS [dbo];

