CREATE TABLE [dbo].[RIGHECONFRD] (
    [RIFPROGRESSIVO] DECIMAL (10)  NOT NULL,
    [IDCOL]          SMALLINT      NOT NULL,
    [NASCONDI]       SMALLINT      NULL,
    [OBBLIGATORIO]   DECIMAL (5)   NULL,
    [ESEGUI]         VARCHAR (300) NULL,
    [PERCORSO]       VARCHAR (500) NULL,
    [IDCOL_A]        SMALLINT      NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_RIGHECONFRD] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [IDCOL] ASC),
    CONSTRAINT [FK_RIGHECONFRD_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTECONFRD] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHECONFRD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHECONFRD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHECONFRD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHECONFRD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHECONFRD] TO [Metodo98]
    AS [dbo];

