CREATE TABLE [dbo].[RIGHEIMPOSTAZIONIRICERCHE] (
    [RIFPROGRESSIVO] DECIMAL (10)  NOT NULL,
    [SEZIONE]        SMALLINT      NOT NULL,
    [PARAP]          SMALLINT      NULL,
    [PARCH]          SMALLINT      NULL,
    [ID]             SMALLINT      NOT NULL,
    [TABELLADB]      VARCHAR (200) NULL,
    [CAMPODB]        VARCHAR (200) NULL,
    [OPERATORE]      SMALLINT      NULL,
    [VALORE]         VARCHAR (200) NULL,
    [CONG]           SMALLINT      NULL,
    [ESCLUDI]        SMALLINT      NULL,
    [CONGSEZ]        SMALLINT      NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [PROGRESSIVOIMP] DECIMAL (10)  NULL,
    [INPUT_NOME]     VARCHAR (200) NULL,
    [INPUT_INDICE]   SMALLINT      NULL,
    [CAMPODBIMP]     VARCHAR (200) NULL,
    CONSTRAINT [PK_RIGHEIMPOSTAZIONIRICERCHE] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [SEZIONE] ASC, [ID] ASC),
    CONSTRAINT [FK_RIGHEIMPOSTAZIONIRICERCHE_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTEIMPOSTAZIONIRICERCHE] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIRICERCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIRICERCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIRICERCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIRICERCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIRICERCHE] TO [Metodo98]
    AS [dbo];

