CREATE TABLE [dbo].[RIGHEORDPRODMATRICOLE] (
    [IDTESTA]        DECIMAL (10) NOT NULL,
    [IDRIGA]         INT          NOT NULL,
    [CODMATRICOLA]   VARCHAR (30) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    CONSTRAINT [PK_RIGHEORDPRODMATRICOLE] PRIMARY KEY CLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC, [CODMATRICOLA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_RIGHEORDPRODMATRICOLE" FOR TABLE "RIGHEORDPRODMATRICOLE"  */
CREATE TRIGGER TI_RIGHEORDPRODMATRICOLE ON RIGHEORDPRODMATRICOLE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "RIGHEORDPROD" MUST EXIST WHEN INSERTING A CHILD IN "RIGHEORDPRODMATRICOLE"  */
    IF UPDATE(IDTESTA) OR
       UPDATE(IDRIGA)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   RIGHEORDPROD T1, INSERTED T2
           WHERE  T1.IDTESTA = T2.IDTESTA
            AND   T1.IDRIGA = T2.IDRIGA) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "RIGHEORDPROD". Cannot create child in "RIGHEORDPRODMATRICOLE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_RIGHEORDPRODMATRICOLE" FOR TABLE "RIGHEORDPRODMATRICOLE"  */
CREATE TRIGGER TU_RIGHEORDPRODMATRICOLE ON RIGHEORDPRODMATRICOLE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "RIGHEORDPROD" MUST EXIST WHEN UPDATING A CHILD IN "RIGHEORDPRODMATRICOLE"  */
      IF UPDATE(IDTESTA) OR
         UPDATE(IDRIGA)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   RIGHEORDPROD T1, INSERTED T2
             WHERE  T1.IDTESTA = T2.IDTESTA
              AND   T1.IDRIGA = T2.IDRIGA) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"RIGHEORDPROD" does not exist. Cannot ALTER COLUMN child in "RIGHEORDPRODMATRICOLE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];

