CREATE TABLE [dbo].[RIGHECICLOPIANORISORSE] (
    [NOMEPIANORIS]           VARCHAR (10)    NOT NULL,
    [PROGRESSIVO]            DECIMAL (10)    NOT NULL,
    [NUMEROFASE]             INT             NOT NULL,
    [POSIZIONE]              INT             NULL,
    [FLAGRIGA]               SMALLINT        DEFAULT (0) NULL,
    [ANNOBOLLA]              SMALLINT        DEFAULT (0) NOT NULL,
    [NUMEROBOLLA]            INT             DEFAULT (0) NOT NULL,
    [TIPOFASE]               SMALLINT        DEFAULT (0) NULL,
    [SEGMENTOCONS]           VARCHAR (5)     NULL,
    [RIFSOVRAPP]             VARCHAR (9)     NULL,
    [INDICESOVRAPP]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [TIPOSOVRAPP]            SMALLINT        DEFAULT (0) NULL,
    [OPERAZIONE]             VARCHAR (5)     NULL,
    [TIPOOPERAZIONE]         SMALLINT        DEFAULT (0) NULL,
    [STATOOPERAZIONE]        SMALLINT        DEFAULT (0) NULL,
    [STATODOCUMENTAZIONE]    SMALLINT        DEFAULT (0) NULL,
    [CDLAVORO]               VARCHAR (5)     NULL,
    [MACCHINA]               VARCHAR (5)     NULL,
    [CODASTANDARD]           DECIMAL (15, 6) DEFAULT (0) NULL,
    [TEMPOMOVSTANDARD]       DECIMAL (15, 6) DEFAULT (0) NULL,
    [LOTTOSTANDARDMOV]       DECIMAL (15, 6) DEFAULT (0) NULL,
    [ARROTONDATEMPOMOV]      SMALLINT        DEFAULT (0) NULL,
    [CALCOLOTEMPOSETUP]      VARCHAR (255)   NULL,
    [UMTEMPOSETUP]           VARCHAR (1)     DEFAULT ('O') NULL,
    [LOTTOSTNSETUP]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [NUMOPERAISETUP]         SMALLINT        DEFAULT (0) NULL,
    [CALCOLOTEMPOMACCHINA]   VARCHAR (255)   NULL,
    [UMTEMPOMACCHINA]        VARCHAR (1)     DEFAULT ('O') NULL,
    [LOTTOSTNMACCHINA]       DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [FATTOREABBINAMENTO]     SMALLINT        DEFAULT (0) NOT NULL,
    [CALCOLOTEMPOUOMO]       VARCHAR (255)   NULL,
    [LOTTOSTNUOMO]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UMTEMPOUOMO]            VARCHAR (1)     DEFAULT ('O') NULL,
    [CALCOLOTEMPOTOTALE]     VARCHAR (255)   NULL,
    [UMTEMPOTOTALE]          VARCHAR (1)     DEFAULT ('O') NULL,
    [LOTTOSTNTOTALE]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [VALUTATEMPI]            VARCHAR (3)     NULL,
    [SOLOSE]                 VARCHAR (255)   NULL,
    [COSTOLAVORAZIONE]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [LOTTORIFCOSTO]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [COSTOTEMPOUNITARIO]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [TEMPORIFCOSTO]          VARCHAR (255)   NULL,
    [TEMPOATTRAVERSAMENTO]   DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [LOTTOATTRAVERSAMENTO]   DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [ARROTTEMPOATTR]         SMALLINT        DEFAULT (0) NULL,
    [VALUTATEMPOATTR]        SMALLINT        DEFAULT (0) NULL,
    [FOGLIOISTRUZIONI]       VARCHAR (80)    NULL,
    [ATTREZZATURA]           VARCHAR (80)    NULL,
    [STRUMENTICONTROLLO]     VARCHAR (80)    NULL,
    [PIANOCONTROLLO]         VARCHAR (80)    NULL,
    [NOTERIGA]               VARCHAR (100)   NULL,
    [DISPRISORSE]            SMALLINT        DEFAULT (1) NULL,
    [INDICECAPACITA]         SMALLINT        DEFAULT (1) NULL,
    [ORELAVOROGIORNO]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [TEMPOPREVSETUP]         VARCHAR (15)    NULL,
    [TEMPOPREVMACCHINA]      VARCHAR (15)    NULL,
    [TEMPOPREVUOMO]          VARCHAR (15)    NULL,
    [TEMPOPREVDURATA]        VARCHAR (15)    NULL,
    [TEMPOPREVMOV]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [TEMPOPREVCODA]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [TEMPOPREVATTRAV]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [TEMPOEFFSETUP]          VARCHAR (15)    NULL,
    [TEMPOEFFMACCHINA]       VARCHAR (15)    NULL,
    [TEMPOEFFUOMO]           VARCHAR (15)    NULL,
    [TEMPOEFFDURATA]         VARCHAR (15)    NULL,
    [TEMPOEFFMOV]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVSETUP]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVMACCHINA]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVUOMO]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVDURATA]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVMOV]             DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVCODA]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREPREVATTRAV]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREEFFSETUP]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREEFFMACCHINA]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREEFFUOMO]             DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREEFFDURATA]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [OREEFFMOV]              DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [FORNITOREASSEGNATO]     VARCHAR (7)     NULL,
    [LISTINOTRASF]           DECIMAL (5)     NULL,
    [UTENSILEASSEGNATO]      VARCHAR (15)    NULL,
    [QUC_ATTREZZAGGIO]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [UMC_ATTREZZAGGIO]       VARCHAR (1)     DEFAULT ('O') NULL,
    [CA_ATTREZZAGGIO]        VARCHAR (255)   NULL,
    [QUC_MACCHINA]           DECIMAL (19, 6) DEFAULT (0) NULL,
    [UMC_MACCHINA]           VARCHAR (1)     DEFAULT ('O') NULL,
    [CA_MACCHINA]            VARCHAR (255)   NULL,
    [QUC_UOMO]               DECIMAL (19, 6) DEFAULT (0) NULL,
    [UMC_UOMO]               VARCHAR (1)     DEFAULT ('O') NULL,
    [CA_UOMO]                VARCHAR (255)   NULL,
    [QUC_INDVARIABILE]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [UMC_INDVARIABILE]       VARCHAR (1)     DEFAULT ('O') NULL,
    [CA_INDVARIABILE]        VARCHAR (255)   NULL,
    [QUC_INDFISSO]           DECIMAL (19, 6) DEFAULT (0) NULL,
    [UMC_INDFISSO]           VARCHAR (1)     DEFAULT ('O') NULL,
    [ELEM_CA_INDFISSO]       SMALLINT        DEFAULT (0) NULL,
    [VALUTACOSTI]            VARCHAR (5)     DEFAULT ('12345') NULL,
    [CP_ATTREZZAGGIO]        DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_MACCHINA]            DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_UOMO]                DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_INDVARIABILE]        DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_INDFISSO]            DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_TOTESTERNI]          DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_ATTREZZAGGIO]        DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_MACCHINA]            DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_UOMO]                DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_INDVARIABILE]        DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_INDFISSO]            DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_TOTESTERNI]          DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_EU_ATTREZZAGGIO]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_EU_MACCHINA]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_EU_UOMO]             DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_EU_INDVARIABILE]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_EU_INDFISSO]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [CP_EU_TOTESTERNI]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_EU_ATTREZZAGGIO]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_EU_MACCHINA]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_EU_UOMO]             DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_EU_INDVARIABILE]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_EU_INDFISSO]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [CC_EU_TOTESTERNI]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [QTAPREVISTA]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QTAVERSATA]             DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QTASCARTATA]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UMFASE]                 VARCHAR (3)     DEFAULT ('') NOT NULL,
    [DATAINIZIOOPSCHEDULATA] DATETIME        NULL,
    [ORAINIZIOOPSCHEDULATA]  DATETIME        NULL,
    [DATAFINEOPSCHEDULATA]   DATETIME        NULL,
    [ORAFINEOPSCHEDULATA]    DATETIME        NULL,
    [DATAINIZIOOPEFFETTIVA]  DATETIME        NULL,
    [ORAINIZIOOPEFFETTIVA]   DATETIME        NULL,
    [DATAFINEOPEFFETTIVA]    DATETIME        NULL,
    [ORAFINEOPEFFETTIVA]     DATETIME        NULL,
    [VALORESOLOSE]           SMALLINT        DEFAULT ((-1)) NULL,
    [TIPOATTREZZAGGIO]       VARCHAR (5)     NULL,
    [SEGMENTOSCHED]          VARCHAR (5)     NULL,
    [UTENTEMODIFICA]         VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]           DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHECICLOPIANORISORSE] PRIMARY KEY CLUSTERED ([NOMEPIANORIS] ASC, [PROGRESSIVO] ASC, [NUMEROFASE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_UMC_ATTREZZAGGIO_RIGHECIC] CHECK ([UMC_ATTREZZAGGIO] = 'P' or [UMC_ATTREZZAGGIO] = 'T' or [UMC_ATTREZZAGGIO] = 'C' or [UMC_ATTREZZAGGIO] = 'S' or [UMC_ATTREZZAGGIO] = 'M' or [UMC_ATTREZZAGGIO] = 'O' or [UMC_ATTREZZAGGIO] = 'G'),
    CONSTRAINT [CKC_UMC_INDFISSO_RIGHECIC] CHECK ([UMC_INDFISSO] = 'P' or [UMC_INDFISSO] = 'T' or [UMC_INDFISSO] = 'C' or [UMC_INDFISSO] = 'S' or [UMC_INDFISSO] = 'M' or [UMC_INDFISSO] = 'O' or [UMC_INDFISSO] = 'G'),
    CONSTRAINT [CKC_UMC_INDVARIABILE_RIGHECIC] CHECK ([UMC_INDVARIABILE] = 'P' or [UMC_INDVARIABILE] = 'T' or [UMC_INDVARIABILE] = 'C' or [UMC_INDVARIABILE] = 'S' or [UMC_INDVARIABILE] = 'M' or [UMC_INDVARIABILE] = 'O' or [UMC_INDVARIABILE] = 'G'),
    CONSTRAINT [CKC_UMC_MACCHINA_RIGHECIC] CHECK ([UMC_MACCHINA] = 'P' or [UMC_MACCHINA] = 'T' or [UMC_MACCHINA] = 'C' or [UMC_MACCHINA] = 'S' or [UMC_MACCHINA] = 'M' or [UMC_MACCHINA] = 'O' or [UMC_MACCHINA] = 'G'),
    CONSTRAINT [CKC_UMC_UOMO_RIGHECIC] CHECK ([UMC_UOMO] = 'P' or [UMC_UOMO] = 'T' or [UMC_UOMO] = 'C' or [UMC_UOMO] = 'S' or [UMC_UOMO] = 'M' or [UMC_UOMO] = 'O' or [UMC_UOMO] = 'G'),
    CONSTRAINT [CKC_UMTEMPOMACCHINA_RIGHECIC] CHECK ([UMTEMPOMACCHINA] = 'P' or [UMTEMPOMACCHINA] = 'T' or [UMTEMPOMACCHINA] = 'C' or [UMTEMPOMACCHINA] = 'S' or [UMTEMPOMACCHINA] = 'M' or [UMTEMPOMACCHINA] = 'O' or [UMTEMPOMACCHINA] = 'G'),
    CONSTRAINT [CKC_UMTEMPOSETUP_RIGHECIC] CHECK ([UMTEMPOSETUP] = 'P' or [UMTEMPOSETUP] = 'T' or [UMTEMPOSETUP] = 'C' or [UMTEMPOSETUP] = 'S' or [UMTEMPOSETUP] = 'M' or [UMTEMPOSETUP] = 'O' or [UMTEMPOSETUP] = 'G'),
    CONSTRAINT [CKC_UMTEMPOTOTALE_RIGHECIC] CHECK ([UMTEMPOTOTALE] = 'P' or [UMTEMPOTOTALE] = 'T' or [UMTEMPOTOTALE] = 'C' or [UMTEMPOTOTALE] = 'S' or [UMTEMPOTOTALE] = 'M' or [UMTEMPOTOTALE] = 'O' or [UMTEMPOTOTALE] = 'G'),
    CONSTRAINT [CKC_UMTEMPOUOMO_RIGHECIC] CHECK ([UMTEMPOUOMO] = 'P' or [UMTEMPOUOMO] = 'T' or [UMTEMPOUOMO] = 'C' or [UMTEMPOUOMO] = 'S' or [UMTEMPOUOMO] = 'M' or [UMTEMPOUOMO] = 'O' or [UMTEMPOUOMO] = 'G'),
    CONSTRAINT [CKC_VALUTATEMPOATTR_RIGHECIC] CHECK ([VALUTATEMPOATTR] = 0 or [VALUTATEMPOATTR] = 1)
);


GO

/*  UPDATE TRIGGER "TU_RIGHECICLOPIANORISORSE" FOR TABLE "RIGHECICLOPIANORISORSE"  */
CREATE TRIGGER TU_RIGHECICLOPIANORISORSE ON RIGHECICLOPIANORISORSE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TESTACICLOPIANORISORSE" MUST EXIST WHEN UPDATING A CHILD IN "RIGHECICLOPIANORISORSE"  */
      IF UPDATE(NOMEPIANORIS) OR
         UPDATE(PROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TESTACICLOPIANORISORSE T1, INSERTED T2
             WHERE  T1.NOMEPIANORIS = T2.NOMEPIANORIS
              AND   T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TESTACICLOPIANORISORSE" does not exist. Cannot modify child in "RIGHECICLOPIANORISORSE".'
               GOTO ERROR
            END
      END
      
      /*  MODIFY PARENT CODE OF "RIGHECICLOPIANORISORSE" FOR ALL CHILDREN IN "TABUTENSILICICLOPIANORISORSE"  */
      IF UPDATE(NOMEPIANORIS) OR
         UPDATE(PROGRESSIVO) OR
         UPDATE(NUMEROFASE)
      BEGIN
         UPDATE TABUTENSILICICLOPIANORISORSE
          SET   NOMEPIANORIS = I1.NOMEPIANORIS,
                PROGRESSIVO = I1.PROGRESSIVO,
                NUMEROFASE = I1.NUMEROFASE
         FROM   TABUTENSILICICLOPIANORISORSE T2, INSERTED I1, DELETED D1
         WHERE  T2.NOMEPIANORIS = D1.NOMEPIANORIS
          AND   T2.PROGRESSIVO = D1.PROGRESSIVO
          AND   T2.NUMEROFASE = D1.NUMEROFASE
          AND  (I1.NOMEPIANORIS != D1.NOMEPIANORIS OR
                I1.PROGRESSIVO != D1.PROGRESSIVO OR
                I1.NUMEROFASE != D1.NUMEROFASE)
      END
      
      /*  MODIFY PARENT CODE OF "RIGHECICLOPIANORISORSE" FOR ALL CHILDREN IN "CAROPERAZIONEFASEPIANORISORSE"  */
      IF UPDATE(NOMEPIANORIS) OR
         UPDATE(PROGRESSIVO) OR
         UPDATE(NUMEROFASE)
      BEGIN
         UPDATE CAROPERAZIONEFASEPIANORISORSE
          SET   NOMEPIANORIS = I1.NOMEPIANORIS,
                PROGRESSIVO = I1.PROGRESSIVO,
                NUMEROFASE = I1.NUMEROFASE
         FROM   CAROPERAZIONEFASEPIANORISORSE T2, INSERTED I1, DELETED D1
         WHERE  T2.NOMEPIANORIS = D1.NOMEPIANORIS
          AND   T2.PROGRESSIVO = D1.PROGRESSIVO
          AND   T2.NUMEROFASE = D1.NUMEROFASE
          AND  (I1.NOMEPIANORIS != D1.NOMEPIANORIS OR
                I1.PROGRESSIVO != D1.PROGRESSIVO OR
                I1.NUMEROFASE != D1.NUMEROFASE)
      END
      
      /*  MODIFY PARENT CODE OF "RIGHECICLOPIANORISORSE" FOR ALL CHILDREN IN "TABDBACICLOPIANORISORSE"  */
      IF UPDATE(NOMEPIANORIS) OR
         UPDATE(PROGRESSIVO) OR
         UPDATE(NUMEROFASE)
      BEGIN
         UPDATE TABDBACICLOPIANORISORSE
          SET   NOMEPIANORIS = I1.NOMEPIANORIS,
                PROGRESSIVO = I1.PROGRESSIVO,
                NUMEROFASE = I1.NUMEROFASE
         FROM   TABDBACICLOPIANORISORSE T2, INSERTED I1, DELETED D1
         WHERE  T2.NOMEPIANORIS = D1.NOMEPIANORIS
          AND   T2.PROGRESSIVO = D1.PROGRESSIVO
          AND   T2.NUMEROFASE = D1.NUMEROFASE
          AND  (I1.NOMEPIANORIS != D1.NOMEPIANORIS OR
                I1.PROGRESSIVO != D1.PROGRESSIVO OR
                I1.NUMEROFASE != D1.NUMEROFASE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_RIGHECICLOPIANORISORSE" FOR TABLE "RIGHECICLOPIANORISORSE"  */
CREATE TRIGGER TD_RIGHECICLOPIANORISORSE ON RIGHECICLOPIANORISORSE FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "TABUTENSILICICLOPIANORISORSE"  */
    DELETE TABUTENSILICICLOPIANORISORSE
    FROM   TABUTENSILICICLOPIANORISORSE T2, DELETED T1
    WHERE  T2.NOMEPIANORIS = T1.NOMEPIANORIS
     AND   T2.PROGRESSIVO = T1.PROGRESSIVO
     AND   T2.NUMEROFASE = T1.NUMEROFASE
    
    /*  DELETE ALL CHILDREN IN "CAROPERAZIONEFASEPIANORISORSE"  */
    DELETE CAROPERAZIONEFASEPIANORISORSE
    FROM   CAROPERAZIONEFASEPIANORISORSE T2, DELETED T1
    WHERE  T2.NOMEPIANORIS = T1.NOMEPIANORIS
     AND   T2.PROGRESSIVO = T1.PROGRESSIVO
     AND   T2.NUMEROFASE = T1.NUMEROFASE
    
    /*  DELETE ALL CHILDREN IN "TABDBACICLOPIANORISORSE"  */
    DELETE TABDBACICLOPIANORISORSE
    FROM   TABDBACICLOPIANORISORSE T2, DELETED T1
    WHERE  T2.NOMEPIANORIS = T1.NOMEPIANORIS
     AND   T2.PROGRESSIVO = T1.PROGRESSIVO
     AND   T2.NUMEROFASE = T1.NUMEROFASE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  INSERT TRIGGER "TI_RIGHECICLOPIANORISORSE" FOR TABLE "RIGHECICLOPIANORISORSE"  */
CREATE TRIGGER TI_RIGHECICLOPIANORISORSE ON RIGHECICLOPIANORISORSE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TESTACICLOPIANORISORSE" MUST EXIST WHEN INSERTING A CHILD IN "RIGHECICLOPIANORISORSE"  */
    IF UPDATE(NOMEPIANORIS) OR
       UPDATE(PROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TESTACICLOPIANORISORSE T1, INSERTED T2
           WHERE  T1.NOMEPIANORIS = T2.NOMEPIANORIS
            AND   T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TESTACICLOPIANORISORSE". Cannot create child in "RIGHECICLOPIANORISORSE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHECICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHECICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHECICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHECICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHECICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];

