CREATE TABLE [dbo].[RIGHETARIFFARIO] (
    [RIFTESTA]       DECIMAL (10)    NOT NULL,
    [IDRIGA]         INT             NOT NULL,
    [ZONA]           DECIMAL (5)     NULL,
    [DESTINAZIONE]   VARCHAR (100)   NULL,
    [MINIMO]         DECIMAL (16, 6) NULL,
    [SCAGLIONEDA]    DECIMAL (16, 6) NULL,
    [SCAGLIONEA]     DECIMAL (16, 6) NULL,
    [TARIFFAEURO]    DECIMAL (19, 4) NULL,
    [TARIFFALIRE]    DECIMAL (19, 4) NULL,
    [POSIZIONE]      INT             NULL,
    [TIPOCALCOLO]    SMALLINT        CONSTRAINT [DF_RIGHETARIFFARIO_TIPOCALCOLO] DEFAULT (0) NOT NULL,
    [FLAGRIGA]       SMALLINT        NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHETARIFFARIO] PRIMARY KEY CLUSTERED ([RIFTESTA] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/* DELETE TRIGGER "TD_RIGHETARIFFARIO" FOR TABLE "RIGHETARIFFARIO" */
CREATE TRIGGER TD_RIGHETARIFFARIO ON  RIGHETARIFFARIO FOR DELETE AS
BEGIN


DECLARE

@NUMROWS INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* DELETE CASCADE */   /* per OGNI Tabella CHILD in Relazione */
/* DELETE ALL CHILDREN IN "MAGGIORAZIONITARIFFARIO" */
DELETE MAGGIORAZIONITARIFFARIO
FROM MAGGIORAZIONITARIFFARIO T2, DELETED T1
WHERE (T2.RIFTESTA = T1.RIFTESTA AND T2.RIFRIGA = T1.IDRIGA)

RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHETARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHETARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHETARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHETARIFFARIO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHETARIFFARIO] TO [Metodo98]
    AS [dbo];

