CREATE TABLE [dbo].[RIGHECONFAZ] (
    [RIFPROGRESSIVO]   DECIMAL (10)   NOT NULL,
    [IDRIGA]           SMALLINT       NOT NULL,
    [TABELLADB]        VARCHAR (200)  NOT NULL,
    [CAMPODB]          VARCHAR (300)  NOT NULL,
    [INPUT_NOME]       VARCHAR (200)  NOT NULL,
    [INPUT_INDICE]     SMALLINT       NOT NULL,
    [RIGA]             SMALLINT       NULL,
    [COLONNA]          SMALLINT       NULL,
    [NASCONDI]         SMALLINT       NULL,
    [BLOCCA]           SMALLINT       NULL,
    [OBBLIGATORIO]     SMALLINT       NULL,
    [ESEGUI]           VARCHAR (300)  NULL,
    [PERCORSO]         VARCHAR (500)  NULL,
    [TABELLADB_VAI]    VARCHAR (200)  NULL,
    [CAMPODB_VAI]      VARCHAR (300)  NULL,
    [INPUT_NOME_VAI]   VARCHAR (200)  NULL,
    [INPUT_INDICE_VAI] SMALLINT       NULL,
    [RIGA_VAI]         SMALLINT       NULL,
    [COLONNA_VAI]      SMALLINT       NULL,
    [IDVISIONE]        SMALLINT       NULL,
    [IDSITUAZIONE]     SMALLINT       NULL,
    [UTENTEMODIFICA]   VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]     DATETIME       NOT NULL,
    [VALOREDEFAULT]    NVARCHAR (250) NULL,
    [SEQUENZADEFAULT]  INT            NULL,
    CONSTRAINT [PK_RIGHECONFAZ] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [IDRIGA] ASC),
    CONSTRAINT [FK_RIGHECONFAZ_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTECONFAZ] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHECONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHECONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHECONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHECONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHECONFAZ] TO [Metodo98]
    AS [dbo];

