CREATE TABLE [dbo].[SL_RIGHEDOCUMENTIDBA] (
    [IDTESTA]        DECIMAL (10)    NOT NULL,
    [IDRIGA]         INT             NOT NULL,
    [IDRIGACOMP]     INT             NOT NULL,
    [CODART]         VARCHAR (50)    NULL,
    [DESCRIZIONEART] VARCHAR (255)   NULL,
    [UMGEST]         VARCHAR (3)     NULL,
    [QTAGEST]        DECIMAL (16, 6) NULL,
    CONSTRAINT [PK_SL_RIGHEDOCUMENTIDBA] PRIMARY KEY NONCLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC, [IDRIGACOMP] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[SL_RIGHEDOCUMENTIDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SL_RIGHEDOCUMENTIDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[SL_RIGHEDOCUMENTIDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SL_RIGHEDOCUMENTIDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SL_RIGHEDOCUMENTIDBA] TO [Metodo98]
    AS [dbo];

