CREATE TABLE [dbo].[SST_IMG_TABCONFIGURAZIONE] (
    [Codice]         DECIMAL (5)  NOT NULL,
    [CodiceAzienda]  VARCHAR (2)  DEFAULT ('') NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) DEFAULT (user_name()) NOT NULL,
    [DATAMODIFICA]   DATETIME     CONSTRAINT [DF_SST_IMG_TABCONFIGURAZIONE_DATAMODIFICA] DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([Codice] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[SST_IMG_TABCONFIGURAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SST_IMG_TABCONFIGURAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[SST_IMG_TABCONFIGURAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SST_IMG_TABCONFIGURAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SST_IMG_TABCONFIGURAZIONE] TO [Metodo98]
    AS [dbo];

