CREATE TABLE [dbo].[STAMPALISTINIPARTICOLARI] (
    [IDSESSIONE]     INT             NOT NULL,
    [CLIFOR]         VARCHAR (7)     NOT NULL,
    [CODART]         VARCHAR (50)    NOT NULL,
    [PREZZO]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [SCONTO]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [SCESTESO]       VARCHAR (30)    DEFAULT ('') NULL,
    [QUANTITA]       DECIMAL (16, 6) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [PREZZOEURO]     DECIMAL (19, 6) DEFAULT (0) NULL,
    [SCONTOCALCCF]   DECIMAL (19, 6) NULL,
    [SCONTOCF]       VARCHAR (30)    NULL,
    [SCONTOAGGCALC]  DECIMAL (19, 6) NULL,
    [SCONTOAGG]      VARCHAR (30)    NULL,
    [DESCRIZIONE]    VARCHAR (255)   NULL
);


GO
CREATE NONCLUSTERED INDEX [ID_STPLISTINIPART]
    ON [dbo].[STAMPALISTINIPARTICOLARI]([CLIFOR] ASC, [CODART] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[STAMPALISTINIPARTICOLARI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STAMPALISTINIPARTICOLARI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STAMPALISTINIPARTICOLARI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STAMPALISTINIPARTICOLARI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STAMPALISTINIPARTICOLARI] TO [Metodo98]
    AS [dbo];

