CREATE TABLE [dbo].[STORICOMOVORDPRODMATRICOLE] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [RIFRIGAMOVORD]  INT          NOT NULL,
    [CODMATRICOLA]   VARCHAR (30) NOT NULL,
    [RIFTESTA]       DECIMAL (10) NULL,
    [RIFRIGA]        INT          NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    CONSTRAINT [PK_STORICOMOVORDPRODMATRICOLE] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [RIFRIGAMOVORD] ASC, [CODMATRICOLA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_STORICOMOVORDPRODMATRICOLE" FOR TABLE "STORICOMOVORDPRODMATRICOLE"  */
CREATE TRIGGER TI_STORICOMOVORDPRODMATRICOLE ON STORICOMOVORDPRODMATRICOLE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "STORICOMOVORDPROD" MUST EXIST WHEN INSERTING A CHILD IN "STORICOMOVORDPRODMATRICOLE"  */
    IF UPDATE(RIFPROGRESSIVO) OR
       UPDATE(RIFRIGAMOVORD)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   STORICOMOVORDPROD T1, INSERTED T2
           WHERE  T1.RIFPROGRESSIVO = T2.RIFPROGRESSIVO
            AND   T1.RIGAMOVORD = T2.RIFRIGAMOVORD) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "STORICOMOVORDPROD". Cannot create child in "STORICOMOVORDPRODMATRICOLE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_STORICOMOVORDPRODMATRICOLE" FOR TABLE "STORICOMOVORDPRODMATRICOLE"  */
CREATE TRIGGER TU_STORICOMOVORDPRODMATRICOLE ON STORICOMOVORDPRODMATRICOLE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "STORICOMOVORDPROD" MUST EXIST WHEN UPDATING A CHILD IN "STORICOMOVORDPRODMATRICOLE"  */
      IF UPDATE(RIFPROGRESSIVO) OR
         UPDATE(RIFRIGAMOVORD)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   STORICOMOVORDPROD T1, INSERTED T2
             WHERE  T1.RIFPROGRESSIVO = T2.RIFPROGRESSIVO
              AND   T1.RIGAMOVORD = T2.RIFRIGAMOVORD) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"STORICOMOVORDPROD" does not exist. Cannot ALTER COLUMN child in "STORICOMOVORDPRODMATRICOLE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[STORICOMOVORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STORICOMOVORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STORICOMOVORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STORICOMOVORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STORICOMOVORDPRODMATRICOLE] TO [Metodo98]
    AS [dbo];

