CREATE TABLE [dbo].[STORICOMODIFICHECAMPI] (
    [PROGRESSIVO]    DECIMAL (10)   IDENTITY (1, 1) NOT NULL,
    [NOMETABELLA]    VARCHAR (50)   NULL,
    [NOMECAMPO]      VARCHAR (50)   NULL,
    [CODICE]         NVARCHAR (300) NULL,
    [VALORE]         NVARCHAR (250) NULL,
    [UTENTEMODIFICA] VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]   DATETIME       NOT NULL,
    CONSTRAINT [PK_STORICOMODIFICHECAMPI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC),
    CONSTRAINT [FK_STORICOMODIFICHECAMPI] FOREIGN KEY ([NOMETABELLA], [NOMECAMPO]) REFERENCES [dbo].[MODIFICHECAMPI] ([NOMETABELLA], [NOMECAMPO]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [STORICOMODIFICHECAMPI_CODICE]
    ON [dbo].[STORICOMODIFICHECAMPI]([NOMETABELLA] ASC, [NOMECAMPO] ASC, [CODICE] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STORICOMODIFICHECAMPI] TO [Metodo98]
    AS [dbo];

