CREATE TABLE [dbo].[STORICOMAGMATRICOLEARCH] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [CODMATRICOLA]   VARCHAR (30) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[STORICOMAGMATRICOLEARCH] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STORICOMAGMATRICOLEARCH] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STORICOMAGMATRICOLEARCH] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STORICOMAGMATRICOLEARCH] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STORICOMAGMATRICOLEARCH] TO [Metodo98]
    AS [dbo];

