CREATE TABLE [dbo].[STORICOMOVPARTITEIMP] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [RIFRIGAMOVORD]  INT             NOT NULL,
    [RIFRIGAMOVIMP]  INT             NOT NULL,
    [RIFTESTA]       DECIMAL (10)    NULL,
    [RIFRIGA]        INT             NULL,
    [RIFIMPEGNO]     INT             NULL,
    [PRIORITA]       INT             NOT NULL,
    [PARTITA]        VARCHAR (15)    NULL,
    [QTAMOVGESTIONE] DECIMAL (16, 6) DEFAULT (0) NULL,
    [QTAGESTIONERES] DECIMAL (16, 6) DEFAULT (0) NULL,
    [QTAMOV1MAG]     DECIMAL (16, 6) DEFAULT (0) NULL,
    [QTAMOV2MAG]     DECIMAL (16, 6) DEFAULT (0) NULL,
    [TIPORIGA]       SMALLINT        DEFAULT (0) NULL,
    [POSIZIONE]      INT             NULL,
    [FLAGRIGA]       SMALLINT        NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [QTAMOVSCARTO]   DECIMAL (16, 6) NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [RIFRIGAMOVORD] ASC, [RIFRIGAMOVIMP] ASC, [PRIORITA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE TRIGGER TI_STORICOMOVPARTITEIMP ON STORICOMOVPARTITEIMP FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "STORICOMOVIMPPROD" MUST EXIST WHEN INSERTING A CHILD IN "STORICOMOVPARTITEIMP"  */
    IF UPDATE(RIFPROGRESSIVO) OR
       UPDATE(RIFRIGAMOVORD) OR
       UPDATE(RIFRIGAMOVIMP)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   STORICOMOVIMPPROD T1, INSERTED T2
           WHERE  T1.RIFPROGRESSIVO = T2.RIFPROGRESSIVO
            AND   T1.RIGAMOVORD = T2.RIFRIGAMOVORD
            AND   T1.RIGAMOVIMP = T2.RIFRIGAMOVIMP) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "STORICOMOVIMPPROD". Cannot create child in "STORICOMOVPARTITEIMP".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
CREATE TRIGGER TU_STORICOMOVPARTITEIMP ON STORICOMOVPARTITEIMP FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "STORICOMOVIMPPROD" MUST EXIST WHEN UPDATING A CHILD IN "STORICOMOVPARTITEIMP"  */
      IF UPDATE(RIFPROGRESSIVO) OR
         UPDATE(RIFRIGAMOVORD) OR
         UPDATE(RIFRIGAMOVIMP)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   STORICOMOVIMPPROD T1, INSERTED T2
             WHERE  T1.RIFPROGRESSIVO = T2.RIFPROGRESSIVO
              AND   T1.RIGAMOVORD = T2.RIFRIGAMOVORD
              AND   T1.RIGAMOVIMP = T2.RIFRIGAMOVIMP) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"STORICOMOVIMPPROD" does not exist. Cannot modify child in "STORICOMOVPARTITEIMP".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[STORICOMOVPARTITEIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STORICOMOVPARTITEIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STORICOMOVPARTITEIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STORICOMOVPARTITEIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STORICOMOVPARTITEIMP] TO [Metodo98]
    AS [dbo];

