CREATE TABLE [dbo].[TABAGENTIUTENTE] (
    [CODUTENTE]      VARCHAR (25)  NOT NULL,
    [FORMID]         INT           DEFAULT (0) NOT NULL,
    [AGENTE]         VARCHAR (128) DEFAULT ('') NULL,
    [ESEGUIGRUPPO]   SMALLINT      DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABAGENTIUTENTE] PRIMARY KEY CLUSTERED ([CODUTENTE] ASC, [FORMID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_ESEGUIGRUPPO_TABAGENT] CHECK ([ESEGUIGRUPPO] = 2 or [ESEGUIGRUPPO] = 1 or [ESEGUIGRUPPO] = 0)
);


GO
CREATE NONCLUSTERED INDEX [CODUTENTEAGENTI]
    ON [dbo].[TABAGENTIUTENTE]([CODUTENTE] ASC) WITH (FILLFACTOR = 90);


GO

/*  INSERT TRIGGER "TI_TABAGENTIUTENTE" FOR TABLE "TABAGENTIUTENTE"  */
CREATE TRIGGER TI_TABAGENTIUTENTE ON TABAGENTIUTENTE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABUTENTI" MUST EXIST WHEN INSERTING A CHILD IN "TABAGENTIUTENTE"  */
    IF UPDATE(CODUTENTE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABUTENTI T1, INSERTED T2
           WHERE  T1.USERID = T2.CODUTENTE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABUTENTI". Cannot create child in "TABAGENTIUTENTE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABAGENTIUTENTE" FOR TABLE "TABAGENTIUTENTE"  */
CREATE TRIGGER TU_TABAGENTIUTENTE ON TABAGENTIUTENTE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABUTENTI" MUST EXIST WHEN UPDATING A CHILD IN "TABAGENTIUTENTE"  */
      IF UPDATE(CODUTENTE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABUTENTI T1, INSERTED T2
             WHERE  T1.USERID = T2.CODUTENTE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABUTENTI" does not exist. Cannot modify child in "TABAGENTIUTENTE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABAGENTIUTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABAGENTIUTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABAGENTIUTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABAGENTIUTENTE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABAGENTIUTENTE] TO [Metodo98]
    AS [dbo];

