CREATE TABLE [dbo].[TABASSEGNAZIONICONSCOMM] (
    [IDRIGASTRUTTCONS] DECIMAL (10)   NOT NULL,
    [IDTESTA]          DECIMAL (10)   NOT NULL,
    [IDRIGA]           INT            NOT NULL,
    [RIFCOMMCLI]       VARCHAR (30)   NOT NULL,
    [ORIGINEEVENTO]    SMALLINT       NOT NULL,
    [PERCRIPARTIZIONE] DECIMAL (9, 6) NULL,
    [UTENTEMODIFICA]   VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]     DATETIME       NOT NULL,
    [TIPORIP]          SMALLINT       CONSTRAINT [DF_TABASSEGNAZIONICONSCOMM_TIPORIP] DEFAULT (0) NULL,
    [DECRIPQTA]        SMALLINT       CONSTRAINT [DF_TABASSEGNAZIONICONSCOMM_DECRIPQTA] DEFAULT (2) NOT NULL,
    [DECRIPVALORE]     SMALLINT       CONSTRAINT [DF_TABASSEGNAZIONICONSCOMM_DECRIPVALORE] DEFAULT (2) NOT NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];

