CREATE TABLE [dbo].[TABASSOC_CLI_TIPART62] (
    [CODCLI]         VARCHAR (7)  NOT NULL,
    [TIPART62]       SMALLINT     DEFAULT ((0)) NOT NULL,
    [CODPAG]         VARCHAR (4)  DEFAULT ('') NULL,
    [GIORNISCAD]     SMALLINT     DEFAULT ((0)) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODCLI] ASC, [TIPART62] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABASSOC_CLI_TIPART62] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABASSOC_CLI_TIPART62] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABASSOC_CLI_TIPART62] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABASSOC_CLI_TIPART62] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABASSOC_CLI_TIPART62] TO [Metodo98]
    AS [dbo];

