CREATE TABLE [dbo].[TABCOMMCLICLASSMAT] (
    [TIPOPRODOTTO]     SMALLINT     NOT NULL,
    [CODCATEGORIASTAT] DECIMAL (5)  NOT NULL,
    [VOCEBASE]         VARCHAR (3)  DEFAULT ('') NOT NULL,
    [IDVOCE]           VARCHAR (3)  DEFAULT ('') NOT NULL,
    [DESCRIZIONE]      VARCHAR (80) NULL,
    [UTENTEMODIFICA]   VARCHAR (25) NOT NULL,
    [DATAMODIFICA]     DATETIME     NOT NULL,
    CONSTRAINT [PK_TABCOMMCLICLASSMAT] PRIMARY KEY CLUSTERED ([TIPOPRODOTTO] ASC, [CODCATEGORIASTAT] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCOMMCLICLASSMAT] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCOMMCLICLASSMAT] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCOMMCLICLASSMAT] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCOMMCLICLASSMAT] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCOMMCLICLASSMAT] TO [Metodo98]
    AS [dbo];

