CREATE TABLE [dbo].[TABCCCOSTIDIR] (
    [PROGRESSIVO]    NUMERIC (10) DEFAULT (0) NOT NULL,
    [CODGEN]         VARCHAR (7)  NULL,
    [CODCDC]         VARCHAR (10) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [VOCEBASE]       VARCHAR (3)  DEFAULT ('') NULL,
    CONSTRAINT [PK_TABCCCOSTIDIR] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCCCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCCCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCCCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCCCOSTIDIR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCCCOSTIDIR] TO [Metodo98]
    AS [dbo];

