CREATE TABLE [dbo].[TABCOMMCLIVOCICOSTOBASE] (
    [TIPOVOCE]       SMALLINT     NOT NULL,
    [VOCEBASE]       VARCHAR (3)  DEFAULT ('') NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABCOMMCLIVOCICOSTOBASE] PRIMARY KEY CLUSTERED ([TIPOVOCE] ASC, [VOCEBASE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCOMMCLIVOCICOSTOBASE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCOMMCLIVOCICOSTOBASE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCOMMCLIVOCICOSTOBASE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCOMMCLIVOCICOSTOBASE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCOMMCLIVOCICOSTOBASE] TO [Metodo98]
    AS [dbo];

