CREATE TABLE [dbo].[TABCAROPERAZIONI] (
    [CODICE]          DECIMAL (5)  NOT NULL,
    [NRRIGA]          INT          NOT NULL,
    [CARDESCRIZIONE]  VARCHAR (80) NULL,
    [CARTIPO]         SMALLINT     NULL,
    [CARNUMCARATTERI] SMALLINT     NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    CONSTRAINT [PK_TABCAROPERAZIONI] PRIMARY KEY CLUSTERED ([CODICE] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_TABCAROPERAZIONI" FOR TABLE "TABCAROPERAZIONI"  */
CREATE TRIGGER TI_TABCAROPERAZIONI ON TABCAROPERAZIONI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABTIPIOPERAZIONI" MUST EXIST WHEN INSERTING A CHILD IN "TABCAROPERAZIONI"  */
    IF UPDATE(CODICE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABTIPIOPERAZIONI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODICE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABTIPIOPERAZIONI". Cannot create child in "TABCAROPERAZIONI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABCAROPERAZIONI" FOR TABLE "TABCAROPERAZIONI"  */
CREATE TRIGGER TU_TABCAROPERAZIONI ON TABCAROPERAZIONI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABTIPIOPERAZIONI" MUST EXIST WHEN UPDATING A CHILD IN "TABCAROPERAZIONI"  */
      IF UPDATE(CODICE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABTIPIOPERAZIONI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODICE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABTIPIOPERAZIONI" does not exist. Cannot ALTER COLUMN child in "TABCAROPERAZIONI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCAROPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCAROPERAZIONI] TO [Metodo98]
    AS [dbo];

