CREATE TABLE [dbo].[TABCARUTENSILI] (
    [CODICE]          DECIMAL (5)  NOT NULL,
    [NRRIGA]          INT          NOT NULL,
    [CARDESCRIZIONE]  VARCHAR (80) NULL,
    [CARTIPO]         SMALLINT     NULL,
    [CARNUMCARATTERI] SMALLINT     NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    CONSTRAINT [PK_TABCARUTENSILI] PRIMARY KEY CLUSTERED ([CODICE] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_TABCARUTENSILI" FOR TABLE "TABCARUTENSILI"  */
CREATE TRIGGER TI_TABCARUTENSILI ON TABCARUTENSILI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABCATEGORIEUTENSILI" MUST EXIST WHEN INSERTING A CHILD IN "TABCARUTENSILI"  */
    IF UPDATE(CODICE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABCATEGORIEUTENSILI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODICE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABCATEGORIEUTENSILI". Cannot create child in "TABCARUTENSILI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABCARUTENSILI" FOR TABLE "TABCARUTENSILI"  */
CREATE TRIGGER TU_TABCARUTENSILI ON TABCARUTENSILI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABCATEGORIEUTENSILI" MUST EXIST WHEN UPDATING A CHILD IN "TABCARUTENSILI"  */
      IF UPDATE(CODICE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABCATEGORIEUTENSILI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODICE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABCATEGORIEUTENSILI" does not exist. Cannot ALTER COLUMN child in "TABCARUTENSILI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCARUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCARUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCARUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCARUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCARUTENSILI] TO [Metodo98]
    AS [dbo];

