CREATE TABLE [dbo].[TABCAMBI] (
    [CODICE]            DECIMAL (5)     NOT NULL,
    [DIVISA]            VARCHAR (3)     NULL,
    [DESCRIZIONE]       VARCHAR (25)    NULL,
    [NOTE]              VARCHAR (100)   NULL,
    [TIPOEURO]          SMALLINT        DEFAULT (0) NULL,
    [NDECIMALIUNITARIO] SMALLINT        DEFAULT (6) NULL,
    [NDECIMALITOTALE]   SMALLINT        DEFAULT (3) NULL,
    [CAMBIOEURO]        DECIMAL (13, 6) DEFAULT (1) NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [ControDivisa]      SMALLINT        DEFAULT ((0)) NULL,
    [GOLD_DIVI_DIO4CE]  VARCHAR (3)     NULL,
    CONSTRAINT [PK_TABCAMBI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOEURO_TABCAMBI] CHECK ([TIPOEURO] = 0 or [TIPOEURO] = 1)
);


GO
CREATE NONCLUSTERED INDEX [TABCAMBI_DSC]
    ON [dbo].[TABCAMBI]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [TABCAMBI_DIVISA]
    ON [dbo].[TABCAMBI]([DIVISA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCAMBI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCAMBI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCAMBI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCAMBI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCAMBI] TO [Metodo98]
    AS [dbo];

