CREATE TABLE [dbo].[TABCOSTIPRODOTTO] (
    [PROGRESSIVO]         DECIMAL (10)    NOT NULL,
    [IDCOSTO]             VARCHAR (10)    NULL,
    [DESCRIZIONE]         VARCHAR (25)    NULL,
    [TIPOVALUTAZIONE]     SMALLINT        NOT NULL,
    [TIPOCOSTO]           SMALLINT        NOT NULL,
    [DATACALCOLO]         DATETIME        NULL,
    [ARTICOLO]            VARCHAR (50)    NULL,
    [UMRIF]               VARCHAR (3)     NOT NULL,
    [VERSIONEDBA]         VARCHAR (10)    NULL,
    [VERSIONECICLO]       VARCHAR (10)    NULL,
    [IDDISTINTA]          DECIMAL (10)    NULL,
    [IDCICLO]             DECIMAL (10)    NULL,
    [CP_MATERIALE]        DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_LAVINTERNA]       DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_LAVESTERNA]       DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_INDVARIABILE]     DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_INDFISSO]         DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_MATERIALE]        DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_LAVINTERNA]       DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_LAVESTERNA]       DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_INDVARIABILE]     DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_INDFISSO]         DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_MATERIALEEURO]    DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_LAVINTERNAEURO]   DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_LAVESTERNAEURO]   DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_INDVARIABILEEURO] DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CP_INDFISSOEURO]     DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_MATERIALEEURO]    DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_LAVINTERNAEURO]   DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_LAVESTERNAEURO]   DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_INDVARIABILEEURO] DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [CA_INDFISSOEURO]     DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]      VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]        DATETIME        NOT NULL,
    [CRITERIOVALUTAZIONE] SMALLINT        CONSTRAINT [DF_TABCOSTIPRODOTTO_CRITERIOVALUTAZIONE] DEFAULT (0) NULL,
    [ORIGINECOSTO]        SMALLINT        NULL,
    [LISTINO]             INT             NULL,
    [COSTOSTD]            VARCHAR (10)    NULL,
    [COSTOCORR]           VARCHAR (10)    NULL,
    CONSTRAINT [PK_TABCOSTIPRODOTTO] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABCOSTIPRODOTTO_ARTICOLO]
    ON [dbo].[TABCOSTIPRODOTTO]([ARTICOLO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_TABCOSTIPRODOTTO99]
    ON [dbo].[TABCOSTIPRODOTTO]([IDCOSTO] ASC, [ARTICOLO] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCOSTIPRODOTTO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCOSTIPRODOTTO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCOSTIPRODOTTO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCOSTIPRODOTTO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCOSTIPRODOTTO] TO [Metodo98]
    AS [dbo];

