CREATE TABLE [dbo].[TABESCLPRECOMPILATACU] (
    [CODICE]         SMALLINT      NOT NULL,
    [DESCRIZIONE]    VARCHAR (500) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABESCLPRECOMPILATACU] PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABESCLPRECOMPILATACU] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABESCLPRECOMPILATACU] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABESCLPRECOMPILATACU] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABESCLPRECOMPILATACU] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABESCLPRECOMPILATACU] TO [Metodo98]
    AS [dbo];

