CREATE TABLE [dbo].[TABESERCIZIEURITMO] (
    [CODICE]         DECIMAL (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) DEFAULT ('') NULL,
    [DATAMODIFICA]   DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABESERCIZIEURITMO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABESERCIZIEURITMO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABESERCIZIEURITMO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABESERCIZIEURITMO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABESERCIZIEURITMO] TO [Metodo98]
    AS [dbo];

