CREATE TABLE [dbo].[TABELLAREPARTI] (
    [CODICE]         DECIMAL (5)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (80)  NULL,
    [CONTOCDC]       VARCHAR (10)  NULL,
    [RESPONSABILE]   VARCHAR (5)   NULL,
    [NOTE]           VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [FLGQUALITY]     SMALLINT      CONSTRAINT [DF_TABELLAREPARTI_FLGQUALITY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TABELLAREPARTI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  UPDATE TRIGGER "TU_TABELLAREPARTI" FOR TABLE "TABELLAREPARTI"  */
CREATE TRIGGER TU_TABELLAREPARTI ON TABELLAREPARTI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  ALTER COLUMN PARENT CODE OF "TABELLAREPARTI" FOR ALL CHILDREN IN "TABELLACDLAVORO"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TABELLACDLAVORO
          SET   REPARTO = I1.CODICE
         FROM   TABELLACDLAVORO T2, INSERTED I1, DELETED D1
         WHERE  T2.REPARTO = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TABELLAREPARTI" FOR TABLE "TABELLAREPARTI"  */
CREATE TRIGGER TD_TABELLAREPARTI ON TABELLAREPARTI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "TABELLACDLAVORO"  */
    DELETE TABELLACDLAVORO
    FROM   TABELLACDLAVORO T2, DELETED T1
    WHERE  T2.REPARTO = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABELLAREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABELLAREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABELLAREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABELLAREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABELLAREPARTI] TO [Metodo98]
    AS [dbo];

