CREATE TABLE [dbo].[TabellaGruppiBolle] (
    [ANNOBOLLA]      SMALLINT     NOT NULL,
    [NUMEROBOLLA]    INT          NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [STATOBOLLA]     SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [TabellaGruppiBolle_PK] PRIMARY KEY CLUSTERED ([ANNOBOLLA] ASC, [NUMEROBOLLA] ASC) WITH (FILLFACTOR = 90)
);


GO
/* DELETE TRIGGER "TD_TABELLAGRUPPIBOLLE" FOR TABLE "TABELLAGRUPPIBOLLE" */
CREATE TRIGGER TD_TABELLAGRUPPIBOLLE ON TABELLAGRUPPIBOLLE FOR DELETE AS
BEGIN

DECLARE
@NUMROWS INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* DELETE CASCADE */   /* per OGNI Tabella CHILD in Relazione */
/* DELETE ALL CHILDREN IN "BOLLECOLLEGATE" */
DELETE BOLLECOLLEGATE
FROM BOLLECOLLEGATE T2, DELETED T1
WHERE T2.RIFANNOBOLLA = T1.ANNOBOLLA 
AND T2.RIFNUMEROBOLLA = T1.NUMEROBOLLA

RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TabellaGruppiBolle] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TabellaGruppiBolle] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TabellaGruppiBolle] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TabellaGruppiBolle] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TabellaGruppiBolle] TO [Metodo98]
    AS [dbo];

