CREATE TABLE [dbo].[TABGRUPPIAPPROVV] (
    [CODICE]             NUMERIC (5)     NOT NULL,
    [DESCRIZIONE]        VARCHAR (80)    NULL,
    [COSTOORDINEACQ]     DECIMAL (19, 6) NULL,
    [COSTOORDINELAV]     DECIMAL (19, 6) NULL,
    [COSTOORDINEPROD]    DECIMAL (19, 6) NULL,
    [FATTORESCOSTAMENTO] DECIMAL (8, 5)  NULL,
    [FATTORESICUREZZA]   DECIMAL (8, 5)  NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    CONSTRAINT [PK_TABGRUPPIAPPROVV] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABGRUPPIAPPROVV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABGRUPPIAPPROVV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABGRUPPIAPPROVV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABGRUPPIAPPROVV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABGRUPPIAPPROVV] TO [Metodo98]
    AS [dbo];

