CREATE TABLE [dbo].[TABGENCOMPRIMB] (
    [TIPO]           SMALLINT     NOT NULL,
    [CODGENERICO]    VARCHAR (7)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABGENCOMPRIMB] PRIMARY KEY CLUSTERED ([TIPO] ASC, [CODGENERICO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABGENCOMPRIMB] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABGENCOMPRIMB] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABGENCOMPRIMB] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABGENCOMPRIMB] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABGENCOMPRIMB] TO [Metodo98]
    AS [dbo];

