CREATE TABLE [dbo].[TABIMMAGINI] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [TABELLA]        VARCHAR (50) NOT NULL,
    [CHIAVE1]        VARCHAR (50) NOT NULL,
    [CHIAVE2]        VARCHAR (55) NULL,
    [CHIAVE3]        VARCHAR (50) NULL,
    [IMMAGINE]       IMAGE        NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABIMMAGINI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABIMMAGINI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABIMMAGINI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABIMMAGINI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABIMMAGINI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABIMMAGINI] TO [Metodo98]
    AS [dbo];

