CREATE TABLE [dbo].[TABMAPPALICENZE] (
    [CODLICENZA]  DECIMAL (4)   NOT NULL,
    [LISTINO]     VARCHAR (50)  NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_TABMAPPALICENZE] PRIMARY KEY CLUSTERED ([CODLICENZA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABMAPPALICENZE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABMAPPALICENZE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABMAPPALICENZE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABMAPPALICENZE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABMAPPALICENZE] TO [Metodo98]
    AS [dbo];

