CREATE TABLE [dbo].[TABOGGETTI] (
    [SCHEDARIO]      VARCHAR (100) NOT NULL,
    [CARTELLA]       VARCHAR (100) NOT NULL,
    [DSCDOCUMENTO]   VARCHAR (100) NOT NULL,
    [PATHDOCUMENTO]  VARCHAR (100) NULL,
    [CLASSE]         VARCHAR (100) NULL,
    [RIFCARTELLA]    VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABOGGETTI] PRIMARY KEY CLUSTERED ([SCHEDARIO] ASC, [CARTELLA] ASC, [DSCDOCUMENTO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABOGGETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABOGGETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABOGGETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABOGGETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABOGGETTI] TO [Metodo98]
    AS [dbo];

