CREATE TABLE [dbo].[TABPROFILI] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [CODGRUPPO]      DECIMAL (5)  NULL,
    [CODUTENTE]      VARCHAR (25) NULL,
    [CODRUOLO]       DECIMAL (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABPROFILI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC),
    CONSTRAINT [FK_TABPROFILI_TABRUOLI] FOREIGN KEY ([CODRUOLO]) REFERENCES [dbo].[TABRUOLI] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABPROFILI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABPROFILI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABPROFILI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABPROFILI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABPROFILI] TO [Metodo98]
    AS [dbo];

