CREATE TABLE [dbo].[TABPARAMABBSCAFF] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [TIPOUM]         DECIMAL (5)  DEFAULT (0) NULL,
    [MAGSCORTA]      VARCHAR (10) DEFAULT ('') NULL,
    [MAGPRESA]       VARCHAR (10) DEFAULT ('') NULL,
    [CODDOC]         VARCHAR (3)  DEFAULT ('') NULL,
    [CAUS_CARICO]    DECIMAL (5)  DEFAULT (0) NULL,
    [CAUS_SCARICO]   DECIMAL (5)  DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [FORAZIENDA]     VARCHAR (7)  DEFAULT ('') NULL,
    CONSTRAINT [PK_TABPARAMABBSCAFF] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABPARAMABBSCAFF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABPARAMABBSCAFF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABPARAMABBSCAFF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABPARAMABBSCAFF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABPARAMABBSCAFF] TO [Metodo98]
    AS [dbo];

