CREATE TABLE [dbo].[TABPROVVIGIONI] (
    [PROGRESSIVO]      DECIMAL (10)  NOT NULL,
    [CODAGENTE]        VARCHAR (7)   NULL,
    [CODGRUPPOPROVCF]  DECIMAL (5)   NULL,
    [CODCLIENTE]       VARCHAR (7)   NULL,
    [CODGRUPPOPROVMAG] DECIMAL (5)   NULL,
    [CODARTICOLO]      VARCHAR (50)  NULL,
    [INIZIOVALIDITA]   DATETIME      NULL,
    [FINEVALIDITA]     DATETIME      NULL,
    [CODARTRIC]        VARCHAR (50)  NULL,
    [UTENTEMODIFICA]   VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]     DATETIME      NOT NULL,
    [CODICEPRIMARIO]   VARCHAR (50)  DEFAULT ('') NULL,
    [VARESPLICITE]     VARCHAR (255) DEFAULT ('') NULL,
    [CODFEATURE]       INT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TABPROVVIGIONI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [PRV_AGECATCLI]
    ON [dbo].[TABPROVVIGIONI]([CODAGENTE] ASC, [CODGRUPPOPROVCF] ASC, [CODCLIENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_ARTAGE]
    ON [dbo].[TABPROVVIGIONI]([CODARTICOLO] ASC, [CODAGENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CATCLIAGE]
    ON [dbo].[TABPROVVIGIONI]([CODGRUPPOPROVCF] ASC, [CODCLIENTE] ASC, [CODAGENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CLIAGE]
    ON [dbo].[TABPROVVIGIONI]([CODCLIENTE] ASC, [CODAGENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CODAGENTE]
    ON [dbo].[TABPROVVIGIONI]([CODAGENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CODARTICOLO]
    ON [dbo].[TABPROVVIGIONI]([CODARTICOLO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CODCATEGORIACF]
    ON [dbo].[TABPROVVIGIONI]([CODGRUPPOPROVCF] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CODCLIENTE]
    ON [dbo].[TABPROVVIGIONI]([CODCLIENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_CODGRUPPO]
    ON [dbo].[TABPROVVIGIONI]([CODGRUPPOPROVMAG] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_FINEVALIDITA]
    ON [dbo].[TABPROVVIGIONI]([FINEVALIDITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_GRPARTAGE]
    ON [dbo].[TABPROVVIGIONI]([CODGRUPPOPROVMAG] ASC, [CODARTICOLO] ASC, [CODAGENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PRV_INIZIOVALIDITA]
    ON [dbo].[TABPROVVIGIONI]([INIZIOVALIDITA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABPROVVIGIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABPROVVIGIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABPROVVIGIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABPROVVIGIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABPROVVIGIONI] TO [Metodo98]
    AS [dbo];

