CREATE TABLE [dbo].[TABPORTO] (
    [CODICE]             DECIMAL (5)  NOT NULL,
    [DESCRIZIONE]        VARCHAR (50) NULL,
    [DESCRIZIONELINGUA1] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA2] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA3] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA4] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA5] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA6] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA7] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA8] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA9] VARCHAR (25) NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    [IdCommittente]      VARCHAR (1)  DEFAULT ('') NULL,
    [IdLuogoCarico]      VARCHAR (1)  DEFAULT ('') NULL,
    [TIPO]               SMALLINT     DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TABPORTO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABPORTO_DSC]
    ON [dbo].[TABPORTO]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABPORTO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABPORTO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABPORTO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABPORTO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABPORTO] TO [Metodo98]
    AS [dbo];

