CREATE TABLE [dbo].[TABRUOLI] (
    [CODICE]         DECIMAL (5)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABRUOLI] PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
CREATE TRIGGER [TUD_SPECIALROLE] ON [TABRUOLI] FOR UPDATE, DELETE AS
BEGIN
	DECLARE @NUMROWS  INT
	
	SELECT @NUMROWS = @@ROWCOUNT
	IF @NUMROWS = 0
		RETURN
	
	IF EXISTS(SELECT CODICE FROM DELETED WHERE CODICE IN (-1,0))
	BEGIN
		RAISERROR ('RUOLI SPECIALI NON MODIFICABILI', 1, 1)
		ROLLBACK  TRANSACTION
	END
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABRUOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABRUOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABRUOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABRUOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABRUOLI] TO [Metodo98]
    AS [dbo];

