CREATE TABLE [dbo].[TABRICLASSIF] (
    [NOME]           VARCHAR (20) NOT NULL,
    [TIPO]           SMALLINT     DEFAULT (0) NOT NULL,
    [STAMPAE]        SMALLINT     DEFAULT (0) NULL,
    [STAMPAPA]       SMALLINT     DEFAULT (0) NULL,
    [STAMPAPP]       SMALLINT     DEFAULT (0) NULL,
    [STAMPAINTESTA]  SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABRICLASSIF] PRIMARY KEY CLUSTERED ([NOME] ASC, [TIPO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_STAMPAE_TABRICLA] CHECK ([STAMPAE] = 0 or [STAMPAE] = 1),
    CONSTRAINT [CKC_STAMPAPA_TABRICLA] CHECK ([STAMPAPA] = 0 or [STAMPAPA] = 1),
    CONSTRAINT [CKC_STAMPAPP_TABRICLA] CHECK ([STAMPAPP] = 0 or [STAMPAPP] = 1)
);


GO

/*  UPDATE TRIGGER "TU_TABRICLASSIF" FOR TABLE "TABRICLASSIF"  */
CREATE TRIGGER TU_TABRICLASSIF ON TABRICLASSIF FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  MODIFY PARENT CODE OF "TABRICLASSIF" FOR ALL CHILDREN IN "RIGHERICLASSIFICAZIONE"  */
      IF UPDATE(NOME) OR
         UPDATE(TIPO)
      BEGIN
         UPDATE RIGHERICLASSIFICAZIONE
          SET   NOME = I1.NOME,
                TIPORIC = I1.TIPO
         FROM   RIGHERICLASSIFICAZIONE T2, INSERTED I1, DELETED D1
         WHERE  T2.NOME = D1.NOME
          AND   T2.TIPORIC = D1.TIPO
          AND  (I1.NOME != D1.NOME OR
                I1.TIPO != D1.TIPO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TABRICLASSIF" FOR TABLE "TABRICLASSIF"  */
CREATE TRIGGER TD_TABRICLASSIF ON TABRICLASSIF FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "RIGHERICLASSIFICAZIONE"  */
    DELETE RIGHERICLASSIFICAZIONE
    FROM   RIGHERICLASSIFICAZIONE T2, DELETED T1
    WHERE  T2.NOME = T1.NOME
     AND   T2.TIPORIC = T1.TIPO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABRICLASSIF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABRICLASSIF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABRICLASSIF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABRICLASSIF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABRICLASSIF] TO [Metodo98]
    AS [dbo];

