CREATE TABLE [dbo].[TABSTRUTTCONSUNTIVOCOMMCLI] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [RIFCOMMCLI]     VARCHAR (30) NOT NULL,
    [SOTTOCOMMESSA]  VARCHAR (10) NULL,
    [GRUPPO]         VARCHAR (10) NULL,
    [NRRIGA]         DECIMAL (10) NULL,
    [DESCRIZIONE]    VARCHAR (50) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_PROGRESSIVO] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABSTRUTTCONSUNTIVOCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABSTRUTTCONSUNTIVOCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABSTRUTTCONSUNTIVOCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABSTRUTTCONSUNTIVOCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABSTRUTTCONSUNTIVOCOMMCLI] TO [Metodo98]
    AS [dbo];

