CREATE TABLE [dbo].[TABTESTEBORDERAUX] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [ESERCIZIO]      DECIMAL (5)  NOT NULL,
    [NUMBORDERAUX]   DECIMAL (9)  NOT NULL,
    [DATA]           DATETIME     NULL,
    [CODSPED]        DECIMAL (5)  DEFAULT (0) NULL,
    [CODAUTOMEZ]     DECIMAL (5)  DEFAULT (0) NULL,
    [TARGA]          VARCHAR (25) DEFAULT ('') NULL,
    [TIPODOC]        VARCHAR (3)  DEFAULT ('') NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABTESTEBORDERAUX] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO


CREATE TRIGGER TD_TABTESTEBORDERAUX ON TABTESTEBORDERAUX
FOR DELETE 
AS



BEGIN

    /*  DELETE ALL CHILDREN IN "TABRIGHEBORDERAUX"  */
    DELETE TABRIGHEBORDERAUX
    FROM     TABRIGHEBORDERAUX T2, DELETED T1
    WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO


END


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABTESTEBORDERAUX] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABTESTEBORDERAUX] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABTESTEBORDERAUX] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABTESTEBORDERAUX] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABTESTEBORDERAUX] TO [Metodo98]
    AS [dbo];

