CREATE TABLE [dbo].[TABUTENSILICICLOORD] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [NUMEROFASE]     INT          NOT NULL,
    [POSIZIONE]      INT          NOT NULL,
    [CODICEUTENSILE] VARCHAR (15) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NULL,
    [DATAMODIFICA]   DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC, [NUMEROFASE] ASC, [POSIZIONE] ASC) WITH (FILLFACTOR = 90)
);


GO
/*  INSERT TRIGGER "TI_TABUTENSILICICLOORD" FOR TABLE "TABUTENSILICICLOORD"  */
CREATE TRIGGER TI_TABUTENSILICICLOORD ON TABUTENSILICICLOORD FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "RIGHECICLOORDINE" MUST EXIST WHEN INSERTING A CHILD IN "TABUTENSILICICLOORD"  */
    IF UPDATE(PROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   RIGHECICLOORDINE T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO AND T1.NUMEROFASE=T2.NUMEROFASE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "RIGHECICLOORDINE". Cannot create child in "TABUTENSILICICLOORD".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABUTENSILICICLOORD" FOR TABLE "TABUTENSILICICLOORD"  */
CREATE TRIGGER TU_TABUTENSILICICLOORD ON TABUTENSILICICLOORD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "RIGHECICLOORDINE" MUST EXIST WHEN UPDATING A CHILD IN "TABUTENSILICICLOORD"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   RIGHECICLOORDINE T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO AND T1.NUMEROFASE=T2.NUMEROFASE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"RIGHECICLOORDINE" does not exist. Cannot modify child in "TABUTENSILICICLOORD".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABUTENSILICICLOORD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABUTENSILICICLOORD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABUTENSILICICLOORD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABUTENSILICICLOORD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABUTENSILICICLOORD] TO [Metodo98]
    AS [dbo];

