CREATE TABLE [dbo].[TABUBICAZIONIDEPOSITI] (
    [CODDEPOSITO]    VARCHAR (10) NOT NULL,
    [CODUBICAZIONE]  VARCHAR (10) NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [TIPOUBICAZIONE] SMALLINT     CONSTRAINT [DF_TABUBICAZIONIDEPOSITI_TIPOUBICAZIONE] DEFAULT (0) NULL,
    CONSTRAINT [PK_TABUBICAZIONIDEPOSITI] PRIMARY KEY CLUSTERED ([CODDEPOSITO] ASC, [CODUBICAZIONE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABUBIC_UBICAZIONE]
    ON [dbo].[TABUBICAZIONIDEPOSITI]([CODUBICAZIONE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [TABUBIC_DSC]
    ON [dbo].[TABUBICAZIONIDEPOSITI]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO

/*  INSERT TRIGGER "TI_TABUBICAZIONIDEPOSITI" FOR TABLE "TABUBICAZIONIDEPOSITI"  */
CREATE TRIGGER TI_TABUBICAZIONIDEPOSITI ON TABUBICAZIONIDEPOSITI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "ANAGRAFICADEPOSITI" MUST EXIST WHEN INSERTING A CHILD IN "TABUBICAZIONIDEPOSITI"  */
    IF UPDATE(CODDEPOSITO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ANAGRAFICADEPOSITI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODDEPOSITO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ANAGRAFICADEPOSITI". Cannot create child in "TABUBICAZIONIDEPOSITI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABUBICAZIONIDEPOSITI" FOR TABLE "TABUBICAZIONIDEPOSITI"  */
CREATE TRIGGER TU_TABUBICAZIONIDEPOSITI ON TABUBICAZIONIDEPOSITI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "ANAGRAFICADEPOSITI" MUST EXIST WHEN UPDATING A CHILD IN "TABUBICAZIONIDEPOSITI"  */
      IF UPDATE(CODDEPOSITO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   ANAGRAFICADEPOSITI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODDEPOSITO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"ANAGRAFICADEPOSITI" does not exist. Cannot modify child in "TABUBICAZIONIDEPOSITI".'
               GOTO ERROR
            END
      END
      
      /*  CANNOT MODIFY PARENT CODE IN "TABUBICAZIONIDEPOSITI" IF CHILDREN STILL EXIST IN "UBICAZIONIARTICOLI"  */
      IF UPDATE(CODDEPOSITO) OR
         UPDATE(CODUBICAZIONE)
      BEGIN
         IF EXISTS (SELECT 1
                    FROM   UBICAZIONIARTICOLI T2, INSERTED I1, DELETED D1
                    WHERE  T2.CODDEPOSITO = D1.CODDEPOSITO
                     AND   T2.CODUBICAZIONE = D1.CODUBICAZIONE
                     AND  (I1.CODDEPOSITO != D1.CODDEPOSITO
                      OR   I1.CODUBICAZIONE != D1.CODUBICAZIONE))
            BEGIN
               SELECT @ERRNO  = 30005,
                      @ERRMSG = 'Children still exist in "UBICAZIONIARTICOLI". Cannot modify parent code in "TABUBICAZIONIDEPOSITI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TABUBICAZIONIDEPOSITI" FOR TABLE "TABUBICAZIONIDEPOSITI"  */
CREATE TRIGGER TD_TABUBICAZIONIDEPOSITI ON TABUBICAZIONIDEPOSITI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  CANNOT DELETE PARENT "TABUBICAZIONIDEPOSITI" IF CHILDREN STILL EXIST IN "UBICAZIONIARTICOLI"  */
    IF EXISTS (SELECT 1
               FROM   UBICAZIONIARTICOLI T2, DELETED T1
               WHERE  T2.CODDEPOSITO = T1.CODDEPOSITO
                AND   T2.CODUBICAZIONE = T1.CODUBICAZIONE)
       BEGIN
          SELECT @ERRNO  = 30006,
                 @ERRMSG = 'Children still exist in "UBICAZIONIARTICOLI". Cannot delete parent "TABUBICAZIONIDEPOSITI".'
          GOTO ERROR
       END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABUBICAZIONIDEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABUBICAZIONIDEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABUBICAZIONIDEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABUBICAZIONIDEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABUBICAZIONIDEPOSITI] TO [Metodo98]
    AS [dbo];

