CREATE TABLE [dbo].[TARGETAGENTI] (
    [CODAGENTE]      VARCHAR (7)     NOT NULL,
    [ANNO]           SMALLINT        NOT NULL,
    [MESE]           SMALLINT        NOT NULL,
    [TARGET]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [TARGETEURO]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TARGETAGENTI] PRIMARY KEY CLUSTERED ([CODAGENTE] ASC, [ANNO] ASC, [MESE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TARGETAGENTI_CODAGENTE] FOREIGN KEY ([CODAGENTE]) REFERENCES [dbo].[ANAGRAFICAAGENTI] ([CODAGENTE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO

/*  UPDATE TRIGGER "TU_TARGETAGENTI" FOR TABLE "TARGETAGENTI"  */
CREATE TRIGGER TU_TARGETAGENTI ON TARGETAGENTI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "ANAGRAFICAAGENTI" MUST EXIST WHEN UPDATING A CHILD IN "TARGETAGENTI"  */
      IF UPDATE(CODAGENTE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   ANAGRAFICAAGENTI T1, INSERTED T2
             WHERE  T1.CODAGENTE = T2.CODAGENTE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"ANAGRAFICAAGENTI" does not exist. Cannot modify child in "TARGETAGENTI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  INSERT TRIGGER "TI_TARGETAGENTI" FOR TABLE "TARGETAGENTI"  */
CREATE TRIGGER TI_TARGETAGENTI ON TARGETAGENTI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "ANAGRAFICAAGENTI" MUST EXIST WHEN INSERTING A CHILD IN "TARGETAGENTI"  */
    IF UPDATE(CODAGENTE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ANAGRAFICAAGENTI T1, INSERTED T2
           WHERE  T1.CODAGENTE = T2.CODAGENTE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ANAGRAFICAAGENTI". Cannot create child in "TARGETAGENTI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TARGETAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TARGETAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TARGETAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TARGETAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TARGETAGENTI] TO [Metodo98]
    AS [dbo];

