CREATE TABLE [dbo].[TDA_DETTFEEDBACK_VERSAMENTO] (
    [RIFPROGRESSIVO]  DECIMAL (10)    NOT NULL,
    [IDRIGA]          INT             NOT NULL,
    [QTACONSUNTIVO]   DECIMAL (16, 6) NULL,
    [FLAGSALDA]       SMALLINT        NULL,
    [PARTITA]         VARCHAR (15)    NULL,
    [STATO]           SMALLINT        NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    [QTASCARTO]       DECIMAL (16, 6) DEFAULT ((0)) NULL,
    [CODDEPOSITO]     VARCHAR (10)    DEFAULT ('') NULL,
    [CODDEPOSITOCOLL] VARCHAR (10)    DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_VERSAMENTO_FEEDBACK] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TDA_FEEDBACK] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_VERSAMENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_VERSAMENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_VERSAMENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_VERSAMENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_VERSAMENTO] TO [Metodo98]
    AS [dbo];

