CREATE TABLE [dbo].[TDA_PARAMETRICONSPRODLISTE] (
    [RIFPLUGIN]      DECIMAL (5)  NOT NULL,
    [TIPOORDINE]     VARCHAR (3)  NOT NULL,
    [TIPOLISTA]      VARCHAR (3)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPLUGIN] ASC, [TIPOORDINE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_PARAMETRICONSPRODLISTE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_PARAMETRICONSPRODLISTE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_PARAMETRICONSPRODLISTE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_PARAMETRICONSPRODLISTE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_PARAMETRICONSPRODLISTE] TO [Metodo98]
    AS [dbo];

