CREATE TABLE [dbo].[TDA_ACCESSICAUSALIFEEDBACK] (
    [RIFCAUSALE]     DECIMAL (5)  NOT NULL,
    [TERMINALE]      DECIMAL (5)  NOT NULL,
    [FLAGACCESSO]    SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFCAUSALE] ASC, [TERMINALE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_ACCESSICAUSALIFEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_ACCESSICAUSALIFEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_ACCESSICAUSALIFEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_ACCESSICAUSALIFEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_ACCESSICAUSALIFEEDBACK] TO [Metodo98]
    AS [dbo];

