CREATE TABLE [dbo].[TDA_FEEDBACK] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [TIPO]           DECIMAL (5)  NOT NULL,
    [CAUSALE]        DECIMAL (5)  NULL,
    [STATO]          SMALLINT     CONSTRAINT [DF_FEEDBACK_STATO] DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_FEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_FEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_FEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_FEEDBACK] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_FEEDBACK] TO [Metodo98]
    AS [dbo];

