CREATE TABLE [dbo].[TDA_FILTROBOLLE] (
    [RIFCAUSALE]     DECIMAL (5)  NOT NULL,
    [NUMERORIGA]     INT          NOT NULL,
    [TIPOOPERAZIONE] DECIMAL (5)  NULL,
    [OPERAZIONE]     VARCHAR (5)  NULL,
    [FLAGACCESSO]    SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFCAUSALE] ASC, [NUMERORIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_FILTROBOLLE_CAUSALIFEEDBACK] FOREIGN KEY ([RIFCAUSALE]) REFERENCES [dbo].[TDA_CAUSALIFEEDBACK] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_FILTROBOLLE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_FILTROBOLLE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_FILTROBOLLE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_FILTROBOLLE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_FILTROBOLLE] TO [Metodo98]
    AS [dbo];

