CREATE TABLE [dbo].[TDA_DETTFEEDBACK_PRESENZA] (
    [RIFPROGRESSIVO]  DECIMAL (10) NOT NULL,
    [IDRIGA]          INT          NOT NULL,
    [DATARILEVAMENTO] DATETIME     NULL,
    [STATO]           SMALLINT     NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRESENZA_FEEDBACK] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TDA_FEEDBACK] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRESENZA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRESENZA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRESENZA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRESENZA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRESENZA] TO [Metodo98]
    AS [dbo];

