CREATE TABLE [dbo].[TEMPSTAMPACONFRONTOCES] (
    [NRTERMINALE]    DECIMAL (5)     NOT NULL,
    [CESPITE]        VARCHAR (10)    NOT NULL,
    [VALOREIMM_AF]   DECIMAL (19, 4) NULL,
    [VALOREORD_AF]   DECIMAL (19, 4) NULL,
    [VALOREANT_AF]   DECIMAL (19, 4) NULL,
    [RESIDUO_AF]     DECIMAL (19, 4) NULL,
    [VALOREIMM_AC]   DECIMAL (19, 4) NULL,
    [VALOREAMM_AC]   DECIMAL (19, 4) NULL,
    [RESIDUO_AC]     DECIMAL (19, 4) NULL,
    [TIPOCALC]       SMALLINT        NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TEMPSTAMPACFRCES] PRIMARY KEY CLUSTERED ([NRTERMINALE] ASC, [CESPITE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTAMPACONFRONTOCES] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTAMPACONFRONTOCES] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTAMPACONFRONTOCES] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTAMPACONFRONTOCES] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTAMPACONFRONTOCES] TO [Metodo98]
    AS [dbo];

