CREATE TABLE [dbo].[TEMPRIGHEMOVINTRABLACKLIST] (
    [IDSESSIONE]      SMALLINT     NOT NULL,
    [CODCLIFOR]       VARCHAR (7)  NOT NULL,
    [COGNOME]         VARCHAR (80) NULL,
    [NOME]            VARCHAR (80) NULL,
    [DATANASCITA]     DATETIME     NULL,
    [COMUNENASCITA]   VARCHAR (80) NULL,
    [PROVNASCITA]     VARCHAR (2)  NULL,
    [CODSTATOESTERO]  SMALLINT     NULL,
    [STATOPROVCONTEA] VARCHAR (80) NULL,
    [LOCRESIDENZA]    VARCHAR (80) NULL,
    [INDESTERO]       VARCHAR (80) NULL,
    [CODICEIVA]       VARCHAR (16) NULL,
    [CODFISCALE]      VARCHAR (16) NULL,
    [IMPORTOA2]       DECIMAL (10) NULL,
    [IMPORTOA3]       DECIMAL (10) NULL,
    [IMPORTOA4]       DECIMAL (10) NULL,
    [IMPORTOA5]       DECIMAL (10) NULL,
    [IMPORTOA6]       DECIMAL (10) NULL,
    [IMPORTOA7]       DECIMAL (10) NULL,
    [IMPORTOA8]       DECIMAL (10) NULL,
    [IMPORTOA9]       DECIMAL (10) NULL,
    [IMPORTOA10]      DECIMAL (10) NULL,
    [IMPORTOA11]      DECIMAL (10) NULL,
    [IMPORTOA12]      DECIMAL (10) NULL,
    [IMPORTOA13]      DECIMAL (10) NULL,
    [IMPORTOA14]      DECIMAL (10) NULL,
    [IMPORTOA15]      DECIMAL (10) NULL,
    [IMPORTOA16]      DECIMAL (10) NULL,
    [IMPORTOA17]      DECIMAL (10) NULL,
    [IMPORTOA18]      DECIMAL (10) NULL,
    [IMPORTOA19]      DECIMAL (10) NULL,
    [IMPORTOA20]      DECIMAL (10) NULL,
    [IMPORTOA21]      DECIMAL (10) NULL,
    [IMPORTOA22]      DECIMAL (10) NULL,
    [IMPORTOA23]      DECIMAL (10) NULL,
    [IMPORTOA24]      DECIMAL (10) NULL,
    [IMPORTOA25]      DECIMAL (10) NULL,
    [IMPORTOA26]      DECIMAL (10) NULL,
    [IMPORTOA27]      DECIMAL (10) NULL,
    [IMPORTOA28]      DECIMAL (10) NULL,
    [IMPORTOA29]      DECIMAL (10) NULL,
    [IMPORTOA30]      DECIMAL (10) NULL,
    [IMPORTOA31]      DECIMAL (10) NULL,
    [IMPORTOA32]      DECIMAL (10) NULL,
    [IMPORTOA33]      DECIMAL (10) NULL,
    [IMPORTOA34]      DECIMAL (10) NULL,
    [IMPORTOA35]      DECIMAL (10) NULL,
    CONSTRAINT [PK_TEMPRIGHEMOVINTRABLACKLIST] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CODCLIFOR] ASC),
    CONSTRAINT [FK_TEMPRIGHEBLACKLIST_TEMPTESTEBLACKLIST] FOREIGN KEY ([IDSESSIONE]) REFERENCES [dbo].[TEMPTESTEMOVINTRABLACKLIST] ([IDSESSIONE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPRIGHEMOVINTRABLACKLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPRIGHEMOVINTRABLACKLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPRIGHEMOVINTRABLACKLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPRIGHEMOVINTRABLACKLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPRIGHEMOVINTRABLACKLIST] TO [Metodo98]
    AS [dbo];

