CREATE TABLE [dbo].[TEMPDISPDAPENNA] (
    [IDSESSIONE]     SMALLINT        NOT NULL,
    [IDRIGA]         SMALLINT        NOT NULL,
    [CODART]         VARCHAR (50)    NOT NULL,
    [NRRIFPARTITA]   VARCHAR (15)    NULL,
    [UBICAZIONE]     VARCHAR (10)    NULL,
    [UM]             VARCHAR (2)     NULL,
    [GIACENZA]       DECIMAL (16, 6) DEFAULT (0) NULL,
    [ESERCIZIO]      DECIMAL (5)     NULL,
    [TIPODOC]        VARCHAR (3)     NULL,
    [NUMERODOC]      INT             NULL,
    [BIS]            VARCHAR (1)     NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [CODDEPOSITO]    VARCHAR (10)    NULL,
    CONSTRAINT [PK_TEMPDISPDAPENNA] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPDISPDAPENNA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPDISPDAPENNA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPDISPDAPENNA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPDISPDAPENNA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPDISPDAPENNA] TO [Metodo98]
    AS [dbo];

