CREATE TABLE [dbo].[TEMP_FEEDBACK_PRELIEVOLOTTI] (
    [IDSESSIONE]      DECIMAL (5)     NOT NULL,
    [RIFRIGA]         INT             NOT NULL,
    [IDRIGA]          INT             NOT NULL,
    [POSIZIONE]       INT             NOT NULL,
    [FLAGRIGA]        SMALLINT        NULL,
    [QTAGESTIONEPREL] DECIMAL (16, 6) NULL,
    [PARTITA]         VARCHAR (15)    NULL,
    [TIPOPARTITA]     SMALLINT        NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    [QTAGESTIONE]     DECIMAL (16, 6) NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [IDRIGA] ASC, [RIFRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMP_FEEDBACK_PRELIEVOLOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMP_FEEDBACK_PRELIEVOLOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMP_FEEDBACK_PRELIEVOLOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMP_FEEDBACK_PRELIEVOLOTTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMP_FEEDBACK_PRELIEVOLOTTI] TO [Metodo98]
    AS [dbo];

