CREATE TABLE [dbo].[TEMPLIVPROD_LEGAMI] (
    [CODCOMPOSTO]   VARCHAR (50) NULL,
    [CODCOMPONENTE] VARCHAR (50) NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPLIVPROD_LEGAMI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPLIVPROD_LEGAMI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPLIVPROD_LEGAMI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPLIVPROD_LEGAMI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPLIVPROD_LEGAMI] TO [Metodo98]
    AS [dbo];

