CREATE TABLE [dbo].[TEMPPARTITARIPARTITEVALUTA] (
    [CONTO]              VARCHAR (7)     NOT NULL,
    [NRPARTITA]          VARCHAR (19)    NOT NULL,
    [CODCAMBIO]          DECIMAL (5)     NOT NULL,
    [NRTERMINALE]        SMALLINT        NOT NULL,
    [DSCCONTO1]          VARCHAR (80)    NULL,
    [NRDOC]              VARCHAR (15)    NULL,
    [DATAAPERTURA]       DATETIME        NULL,
    [VALCAMBIO]          DECIMAL (13, 6) NULL,
    [DIVISA]             VARCHAR (3)     NULL,
    [SALDOPARTITAVALUTA] DECIMAL (19, 4) NULL,
    [SALDOPARTITAEURO]   DECIMAL (19, 4) NULL,
    [VALCAMBIOATT]       DECIMAL (13, 6) NULL,
    [VALCAMBIOINIZIO]    DECIMAL (13, 6) NULL,
    [UTILE]              DECIMAL (19, 4) NULL,
    [PERDITA]            DECIMAL (19, 4) NULL,
    CONSTRAINT [PK_TEMPPARTITARIPARTITEVALUTA] PRIMARY KEY CLUSTERED ([CONTO] ASC, [NRPARTITA] ASC, [CODCAMBIO] ASC, [NRTERMINALE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPPARTITARIPARTITEVALUTA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPPARTITARIPARTITEVALUTA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPPARTITARIPARTITEVALUTA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPPARTITARIPARTITEVALUTA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPPARTITARIPARTITEVALUTA] TO [Metodo98]
    AS [dbo];

