CREATE TABLE [dbo].[TEMPCONFRONTORIGHEPREV] (
    [IDSESSIONE]           INT              NOT NULL,
    [RIFPROGRESSIVO1]      DECIMAL (10)     NOT NULL,
    [RIFPROGRESSIVO2]      DECIMAL (10)     NOT NULL,
    [NRRIGA]               DECIMAL (5)      NOT NULL,
    [POSIZIONENODO]        DECIMAL (5)      NOT NULL,
    [CODLIVS1]             VARCHAR (24)     NULL,
    [CODLIVELLO]           VARCHAR (20)     NULL,
    [LIVS1]                SMALLINT         NULL,
    [LIVPADRES1]           VARCHAR (24)     NULL,
    [LIV5]                 VARCHAR (50)     NULL,
    [FLGTIPOLIV5]          SMALLINT         NULL,
    [FLGARTICOLOVALIDO]    SMALLINT         NULL,
    [TIPONODO]             SMALLINT         NULL,
    [DESCRIZIONE]          VARCHAR (100)    NULL,
    [DESCRESTESA]          VARCHAR (3000)   NULL,
    [VOCECOSTO]            VARCHAR (3)      NULL,
    [VERSDBA]              VARCHAR (10)     NULL,
    [UMGEST]               VARCHAR (3)      NULL,
    [QTAGESTIONE]          DECIMAL (16, 6)  NULL,
    [UMCOSTO]              VARCHAR (3)      NULL,
    [QTACOSTO]             DECIMAL (16, 6)  NULL,
    [QTAPREZZO]            DECIMAL (16, 6)  NULL,
    [UMPREZZO]             VARCHAR (3)      NULL,
    [QTARILASCIATA]        DECIMAL (16, 6)  NULL,
    [FATTCONV]             DECIMAL (20, 10) NULL,
    [FATTCONVPR]           DECIMAL (20, 10) NULL,
    [COSTOUNITARIOEURO1]   DECIMAL (19, 6)  NULL,
    [COSTOTOTALEPREVEURO1] DECIMAL (19, 6)  NULL,
    [PREZZOFFERTAUNIEURO1] DECIMAL (19, 6)  NULL,
    [PREZZOFFERTATOTEURO1] DECIMAL (19, 6)  NULL,
    [COSTOUNITARIOEURO2]   DECIMAL (19, 6)  NULL,
    [COSTOTOTALEPREVEURO2] DECIMAL (19, 6)  NULL,
    [PREZZOFFERTAUNIEURO2] DECIMAL (19, 6)  NULL,
    [PREZZOFFERTATOTEURO2] DECIMAL (19, 6)  NULL,
    [PATHNODO]             VARCHAR (1000)   NULL,
    [FLGCOSTOVAR]          SMALLINT         NULL,
    [FLGPREZZOVAR]         SMALLINT         NULL,
    [UTENTEMODIFICA]       VARCHAR (25)     NULL,
    [DATAMODIFICA]         DATETIME         NOT NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPCONFRONTORIGHEPREV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPCONFRONTORIGHEPREV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPCONFRONTORIGHEPREV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPCONFRONTORIGHEPREV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPCONFRONTORIGHEPREV] TO [Metodo98]
    AS [dbo];

