CREATE TABLE [dbo].[TEMPADDEBITOINTERESSI] (
    [IDSESSIONE]      DECIMAL (5)     NOT NULL,
    [PROGRESSIVOSCAD] DECIMAL (10)    NOT NULL,
    [NRGIORNI1]       SMALLINT        NULL,
    [NRGIORNI2]       SMALLINT        NULL,
    [IMPINTERESSI1]   DECIMAL (19, 4) NULL,
    [IMPINTERESSI2]   DECIMAL (19, 4) NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    CONSTRAINT [PK_TEMPADDEBITOINTERESSI] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [PROGRESSIVOSCAD] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPADDEBITOINTERESSI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPADDEBITOINTERESSI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPADDEBITOINTERESSI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPADDEBITOINTERESSI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPADDEBITOINTERESSI] TO [Metodo98]
    AS [dbo];

