CREATE TABLE [dbo].[TEMPLIVELLIPRODUZIONE] (
    [NRTERMINALE]    DECIMAL (5)  NOT NULL,
    [CODICE]         VARCHAR (50) NULL,
    [LIVELLO]        DECIMAL (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_TEMPLIVELLIPRODUZIONE]
    ON [dbo].[TEMPLIVELLIPRODUZIONE]([NRTERMINALE] ASC, [CODICE] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPLIVELLIPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPLIVELLIPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPLIVELLIPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPLIVELLIPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPLIVELLIPRODUZIONE] TO [Metodo98]
    AS [dbo];

