CREATE TABLE [dbo].[TEMPSTPQUADROFRELENCHICF] (
    [IDSESSIONE]           DECIMAL (5)  NOT NULL,
    [NRPAGINA]             SMALLINT     NOT NULL,
    [CODFISCDITTA]         VARCHAR (16) NULL,
    [NRMODELLO]            VARCHAR (8)  NULL,
    [PARTITAIVA1]          VARCHAR (11) NULL,
    [FLGDOCRIEPILOGATIVO1] VARCHAR (1)  NULL,
    [DATADOC1]             DATETIME     NULL,
    [DATAREG1]             DATETIME     NULL,
    [FLGIVANONESPOSTAFT1]  VARCHAR (1)  NULL,
    [FLGREVERSECHARGE1]    VARCHAR (1)  NULL,
    [FLGAUTOFATTURA1]      VARCHAR (1)  NULL,
    [IMPONIB1]             DECIMAL (10) NULL,
    [IMPOSTA1]             DECIMAL (10) NULL,
    [PARTITAIVA2]          VARCHAR (11) NULL,
    [FLGDOCRIEPILOGATIVO2] VARCHAR (1)  NULL,
    [DATADOC2]             DATETIME     NULL,
    [DATAREG2]             DATETIME     NULL,
    [FLGIVANONESPOSTAFT2]  VARCHAR (1)  NULL,
    [FLGREVERSECHARGE2]    VARCHAR (1)  NULL,
    [FLGAUTOFATTURA2]      VARCHAR (1)  NULL,
    [IMPONIB2]             DECIMAL (10) NULL,
    [IMPOSTA2]             DECIMAL (10) NULL,
    [PARTITAIVA3]          VARCHAR (11) NULL,
    [FLGDOCRIEPILOGATIVO3] VARCHAR (1)  NULL,
    [DATADOC3]             DATETIME     NULL,
    [DATAREG3]             DATETIME     NULL,
    [FLGIVANONESPOSTAFT3]  VARCHAR (1)  NULL,
    [FLGREVERSECHARGE3]    VARCHAR (1)  NULL,
    [FLGAUTOFATTURA3]      VARCHAR (1)  NULL,
    [IMPONIB3]             DECIMAL (10) NULL,
    [IMPOSTA3]             DECIMAL (10) NULL,
    [PARTITAIVA4]          VARCHAR (11) NULL,
    [FLGDOCRIEPILOGATIVO4] VARCHAR (1)  NULL,
    [DATADOC4]             DATETIME     NULL,
    [DATAREG4]             DATETIME     NULL,
    [FLGIVANONESPOSTAFT4]  VARCHAR (1)  NULL,
    [FLGREVERSECHARGE4]    VARCHAR (1)  NULL,
    [FLGAUTOFATTURA4]      VARCHAR (1)  NULL,
    [IMPONIB4]             DECIMAL (10) NULL,
    [IMPOSTA4]             DECIMAL (10) NULL,
    [PARTITAIVA5]          VARCHAR (11) NULL,
    [FLGDOCRIEPILOGATIVO5] VARCHAR (1)  NULL,
    [DATADOC5]             DATETIME     NULL,
    [DATAREG5]             DATETIME     NULL,
    [FLGIVANONESPOSTAFT5]  VARCHAR (1)  NULL,
    [FLGREVERSECHARGE5]    VARCHAR (1)  NULL,
    [FLGAUTOFATTURA5]      VARCHAR (1)  NULL,
    [IMPONIB5]             DECIMAL (10) NULL,
    [IMPOSTA5]             DECIMAL (10) NULL,
    [PARTITAIVA6]          VARCHAR (11) NULL,
    [FLGDOCRIEPILOGATIVO6] VARCHAR (1)  NULL,
    [DATADOC6]             DATETIME     NULL,
    [DATAREG6]             DATETIME     NULL,
    [FLGIVANONESPOSTAFT6]  VARCHAR (1)  NULL,
    [FLGREVERSECHARGE6]    VARCHAR (1)  NULL,
    [FLGAUTOFATTURA6]      VARCHAR (1)  NULL,
    [IMPONIB6]             DECIMAL (10) NULL,
    [IMPOSTA6]             DECIMAL (10) NULL,
    [UTENTEMODIFICA]       VARCHAR (25) NOT NULL,
    [DATAMODIFICA]         DATETIME     NOT NULL,
    CONSTRAINT [PK_TEMPSTPQUADROFRELENCHICF] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [NRPAGINA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPQUADROFRELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPQUADROFRELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPQUADROFRELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPQUADROFRELENCHICF] TO [Metodo98]
    AS [dbo];

