CREATE TABLE [dbo].[TEMPPROSPENASARCO] (
    [IDSESSIONE]     INT             NOT NULL,
    [POSIZIONE]      SMALLINT        NOT NULL,
    [PROGSCADENZA]   NUMERIC (10)    NOT NULL,
    [CODAGENTE]      VARCHAR (7)     NULL,
    [IMPPROVV]       NUMERIC (19, 4) NULL,
    [IMPPROVVEURO]   NUMERIC (19, 4) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [IMPPROVVVAL]    DECIMAL (19, 4) NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [POSIZIONE] ASC, [PROGSCADENZA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPPROSPENASARCO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPPROSPENASARCO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPPROSPENASARCO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPPROSPENASARCO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPPROSPENASARCO] TO [Metodo98]
    AS [dbo];

