CREATE TABLE [dbo].[TEMPSTPFRONTESPELENCHICF] (
    [IDSESSIONE]         DECIMAL (5)  NOT NULL,
    [CODFISCDITTA]       VARCHAR (16) NULL,
    [ANNO]               SMALLINT     NULL,
    [MESETRIM]           VARCHAR (2)  NULL,
    [FLGORDINARIA]       VARCHAR (1)  NULL,
    [FLGSOSTITUTIVA]     VARCHAR (1)  NULL,
    [FLGANNULLAMENTO]    VARCHAR (1)  NULL,
    [PROTCOMUNSOST]      VARCHAR (17) NULL,
    [PROTDOCSOST]        VARCHAR (6)  NULL,
    [FLGAGGR]            VARCHAR (1)  NULL,
    [FLGANALITICA]       VARCHAR (1)  NULL,
    [FLGQUADROFA]        VARCHAR (1)  NULL,
    [FLGQUADROSA]        VARCHAR (1)  NULL,
    [FLGQUADROBL]        VARCHAR (1)  NULL,
    [FLGQUADROFE]        VARCHAR (1)  NULL,
    [FLGQUADROFR]        VARCHAR (1)  NULL,
    [FLGQUADRONE]        VARCHAR (1)  NULL,
    [FLGQUADRONR]        VARCHAR (1)  NULL,
    [FLGQUADRODF]        VARCHAR (1)  NULL,
    [FLGQUADROFN]        VARCHAR (1)  NULL,
    [FLGQUADROSE]        VARCHAR (1)  NULL,
    [FLGQUADROTU]        VARCHAR (1)  NULL,
    [PARTITAIVA]         VARCHAR (11) NULL,
    [CODFISCALE]         VARCHAR (16) NULL,
    [CODATTIVITA]        VARCHAR (6)  NULL,
    [EMAIL]              VARCHAR (50) NULL,
    [TELEFONO]           VARCHAR (12) NULL,
    [FAX]                VARCHAR (12) NULL,
    [COGNOMEPF]          VARCHAR (24) NULL,
    [NOMEPF]             VARCHAR (20) NULL,
    [SESSOM]             VARCHAR (1)  NULL,
    [SESSOF]             VARCHAR (1)  NULL,
    [DATANASCITA]        DATETIME     NULL,
    [COMUNENASCITA]      VARCHAR (40) NULL,
    [PROVNASCITA]        VARCHAR (2)  NULL,
    [RAGIONESOCPG]       VARCHAR (60) NULL,
    [CODFISCDICH]        VARCHAR (16) NULL,
    [CODCARICADICH]      SMALLINT     NULL,
    [DATAINIZIOPROC]     DATETIME     NULL,
    [DATAFINEPROC]       DATETIME     NULL,
    [COGNOMEDICH]        VARCHAR (24) NULL,
    [NOMEDICH]           VARCHAR (20) NULL,
    [SESSODICHM]         VARCHAR (1)  NULL,
    [SESSODICHF]         VARCHAR (1)  NULL,
    [DATANASCITADICH]    DATETIME     NULL,
    [COMUNENASCITADICH]  VARCHAR (40) NULL,
    [PROVNASCITADICH]    VARCHAR (2)  NULL,
    [RAGIONESOCDICH]     VARCHAR (60) NULL,
    [CODFISCINTERM]      VARCHAR (16) NULL,
    [FLGIMPTRASMISSIONE] VARCHAR (1)  NULL,
    [NUMISCRIZALBO]      DECIMAL (5)  NULL,
    [DATAIMPEGNO]        DATETIME     NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    CONSTRAINT [PK_TEMPSTPFRONTESPELENCHICF] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPFRONTESPELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPFRONTESPELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPFRONTESPELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPFRONTESPELENCHICF] TO [Metodo98]
    AS [dbo];

