CREATE TABLE [dbo].[TEMPLOOPDBA] (
    [NRTERMINALE] DECIMAL (5)  NOT NULL,
    [PROGRESSIVO] DECIMAL (10) NOT NULL,
    [RIFDISTINTA] DECIMAL (10) NULL,
    [RIFCOMPOSTO] DECIMAL (10) NULL,
    [NRRIGA]      DECIMAL (10) NULL,
    [CODARTICOLO] VARCHAR (50) NULL,
    [TIPOLOOP]    SMALLINT     DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_TEMPLOOPDBA] PRIMARY KEY CLUSTERED ([NRTERMINALE] ASC, [PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOLOOP_TEMPLOOP] CHECK ([TIPOLOOP] = 3 or [TIPOLOOP] = 2 or [TIPOLOOP] = 1 or [TIPOLOOP] = 0)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPLOOPDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPLOOPDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPLOOPDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPLOOPDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPLOOPDBA] TO [Metodo98]
    AS [dbo];

