CREATE TABLE [dbo].[TEMPSTPFIRR] (
    [IDSESSIONE]     INT             NOT NULL,
    [CODAGENTE]      VARCHAR (7)     NOT NULL,
    [DSCAGENTE]      VARCHAR (80)    NULL,
    [MATRICOLAAGE]   VARCHAR (12)    NOT NULL,
    [CODFISCALE]     VARCHAR (16)    NULL,
    [BASEIMPTOT]     DECIMAL (19, 4) DEFAULT (0) NULL,
    [IMPFIRRTOT]     DECIMAL (19, 4) DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CODAGENTE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPFIRR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPFIRR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTPFIRR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPFIRR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPFIRR] TO [Metodo98]
    AS [dbo];

