CREATE TABLE [dbo].[TEMPSTPPREVCOMMCLI] (
    [RIFPROGRESSIVO]    DECIMAL (10)    NULL,
    [NRRIGA]            DECIMAL (5)     NULL,
    [DESCRIZIONE]       VARCHAR (100)   NULL,
    [DESCRIZIONE_SC]    VARCHAR (100)   NULL,
    [DESCRIZIONE_GRP]   VARCHAR (100)   NULL,
    [SC]                VARCHAR (24)    NULL,
    [GRP]               VARCHAR (24)    NULL,
    [LIV5]              VARCHAR (50)    NULL,
    [COSTOTOTLIRE]      DECIMAL (19, 6) NULL,
    [COSTOTOTEURO]      DECIMAL (19, 6) NULL,
    [PREZZOTOTLIRE]     DECIMAL (19, 6) NULL,
    [PREZZOTOTEURO]     DECIMAL (19, 6) NULL,
    [COSTOTOTLIRE_SC]   DECIMAL (19, 6) NULL,
    [COSTOTOTEURO_SC]   DECIMAL (19, 6) NULL,
    [PREZZOTOTLIRE_SC]  DECIMAL (19, 6) NULL,
    [PREZZOTOTEURO_SC]  DECIMAL (19, 6) NULL,
    [COSTOTOTLIRE_GRP]  DECIMAL (19, 6) NULL,
    [COSTOTOTEURO_GRP]  DECIMAL (19, 6) NULL,
    [PREZZOTOTLIRE_GRP] DECIMAL (19, 6) NULL,
    [PREZZOTOTEURO_GRP] DECIMAL (19, 6) NULL,
    [IDSESSIONE]        INT             NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [RAGGR1]            VARCHAR (30)    NULL,
    [RAGGR2]            VARCHAR (30)    NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTPPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPPREVCOMMCLI] TO [Metodo98]
    AS [dbo];

