CREATE TABLE [dbo].[TEMPASSEGNAZIONICONSCOMM] (
    [IDSESSIONE]       DECIMAL (5)    NOT NULL,
    [IDRIGASTRUTTCONS] DECIMAL (10)   NOT NULL,
    [IDTESTA]          DECIMAL (10)   NOT NULL,
    [IDRIGA]           INT            NOT NULL,
    [RIFCOMMCLI]       VARCHAR (30)   NOT NULL,
    [ORIGINEEVENTO]    SMALLINT       NULL,
    [PERCRIPARTIZIONE] DECIMAL (9, 6) NULL,
    [UTENTEMODIFICA]   VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]     DATETIME       NOT NULL,
    [TIPORIP]          SMALLINT       NULL,
    [STATO]            VARCHAR (1)    NULL,
    [DECRIPQTA]        SMALLINT       NULL,
    [DECRIPVALORE]     SMALLINT       NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];

