CREATE TABLE [dbo].[TEMPTIPIDOC] (
    [TIPODOC]        VARCHAR (3)  NOT NULL,
    [IDSESSIONE]     INT          NOT NULL,
    [DESCRIZIONE]    VARCHAR (25) NULL,
    [BLOCCATO]       SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TEMPTIPIDOC] PRIMARY KEY CLUSTERED ([TIPODOC] ASC, [IDSESSIONE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_BLOCCATO_TEMPTIPI] CHECK ([BLOCCATO] = 0 or [BLOCCATO] = 1)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPTIPIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPTIPIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPTIPIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPTIPIDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPTIPIDOC] TO [Metodo98]
    AS [dbo];

