CREATE TABLE [dbo].[TEMPSTPBOLLELAV] (
    [IDSESSIONE]     INT          NOT NULL,
    [ANNOBOLLA]      SMALLINT     NOT NULL,
    [NUMEROBOLLA]    INT          NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [ANNOBOLLA] ASC, [NUMEROBOLLA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPBOLLELAV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPBOLLELAV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTPBOLLELAV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPBOLLELAV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPBOLLELAV] TO [Metodo98]
    AS [dbo];

