CREATE TABLE [dbo].[TEMPLIVPROD_ARTICOLI] (
    [CODART]      VARCHAR (50) NOT NULL,
    [LIVPRODNUM]  SMALLINT     NOT NULL,
    [LIVPRODALFA] VARCHAR (1)  NULL,
    PRIMARY KEY CLUSTERED ([CODART] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPLIVPROD_ARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPLIVPROD_ARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPLIVPROD_ARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPLIVPROD_ARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPLIVPROD_ARTICOLI] TO [Metodo98]
    AS [dbo];

