CREATE TABLE [dbo].[TESTESTIMAFINIRE] (
    [PROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [RIFCOMMCLI]         VARCHAR (30)    NOT NULL,
    [PREVCOMMCLI]        DECIMAL (10)    NOT NULL,
    [DATACALCOLO]        DATETIME        NOT NULL,
    [DATAMAXRILEVAZIONE] DATETIME        NULL,
    [CONSNONASSEGNATO]   DECIMAL (19, 6) NULL,
    [TIPOAVANZAMENTO]    SMALLINT        NOT NULL,
    [VALORECONTRATTO]    DECIMAL (19, 6) NULL,
    [RICAVO]             DECIMAL (19, 6) NULL,
    [TOTAVANZAMENTO]     DECIMAL (8, 5)  NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [CONSUNTIVO]         DECIMAL (19, 6) NULL,
    [RATEORISCONTO]      DECIMAL (19, 6) NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTESTIMAFINIRE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTESTIMAFINIRE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTESTIMAFINIRE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTESTIMAFINIRE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTESTIMAFINIRE] TO [Metodo98]
    AS [dbo];

