CREATE TABLE [dbo].[TESTEDOCUMENTI] (
    [PROGRESSIVO]               DECIMAL (10)     NOT NULL,
    [ESERCIZIO]                 DECIMAL (5)      NOT NULL,
    [TIPODOC]                   VARCHAR (3)      NOT NULL,
    [NUMERODOC]                 DECIMAL (10)     NOT NULL,
    [BIS]                       CHAR (1)         NULL,
    [DATADOC]                   DATETIME         NULL,
    [DOCCHIUSO]                 SMALLINT         DEFAULT (0) NULL,
    [SEGNO]                     SMALLINT         DEFAULT (0) NOT NULL,
    [CODCLIFOR]                 VARCHAR (7)      NULL,
    [NUMRIFDOC]                 VARCHAR (15)     NULL,
    [DATARIFDOC]                DATETIME         NULL,
    [CODLISTINO]                DECIMAL (5)      NULL,
    [CODCAMBIO]                 DECIMAL (5)      NULL,
    [VALCAMBIO]                 DECIMAL (13, 6)  DEFAULT (1) NOT NULL,
    [ADDSPESEDOCUM]             SMALLINT         DEFAULT (0) NULL,
    [ADDSPESEEFFETTO]           SMALLINT         DEFAULT (0) NULL,
    [ADDSPESETRASPORTO]         SMALLINT         DEFAULT (0) NULL,
    [ADDSPESEIMBALLO]           SMALLINT         DEFAULT (0) NULL,
    [CODLINGUA]                 DECIMAL (5)      NULL,
    [CODAGENTE1]                VARCHAR (7)      NULL,
    [PRCPROVVAG1]               VARCHAR (20)     NULL,
    [PRCPROVVFINALEAG1]         VARCHAR (20)     NULL,
    [TOTPROVVAG1]               DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAGEURO1]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAG1RES]            NUMERIC (19, 4)  NULL,
    [TOTPROVVAGEURO1RES]        NUMERIC (19, 4)  NULL,
    [CODAGENTE2]                VARCHAR (7)      NULL,
    [PRCPROVVAG2]               VARCHAR (20)     NULL,
    [PRCPROVVFINALEAG2]         VARCHAR (20)     NULL,
    [TOTPROVVAG2]               DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAGEURO2]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAG2RES]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAGEURO2RES]        DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [CODAGENTE3]                VARCHAR (7)      NULL,
    [PRCPROVVAG3]               VARCHAR (20)     NULL,
    [PRCPROVVFINALEAG3]         VARCHAR (20)     NULL,
    [TOTPROVVAG3]               DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAGEURO3]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAG3RES]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTPROVVAGEURO3RES]        DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [NUMDESTDIVERSACORR]        DECIMAL (5)      NULL,
    [NUMDESTDIVERSAMERCI]       DECIMAL (5)      NULL,
    [RAGSOCDDM]                 VARCHAR (80)     NULL,
    [INDIRIZZODDM]              VARCHAR (80)     NULL,
    [CAPDDM]                    VARCHAR (8)      NULL,
    [LOCALITADDM]               VARCHAR (80)     NULL,
    [PROVINCIADDM]              VARCHAR (4)      NULL,
    [SCONTOFINALE]              VARCHAR (20)     NULL,
    [CODBANCAINCASSO]           VARCHAR (7)      NULL,
    [CODBANCAAPPOGGIO]          DECIMAL (5)      NULL,
    [CODPAGAMENTO]              VARCHAR (4)      NULL,
    [SPESEDOC]                  DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [SPESEEFFETTO]              DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEDOC]               DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEEFFETTO]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEDOC]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEEFFETTO]        DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVAALTRESPESE]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVAALTRESPESERES]       DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTALTRESPESE]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTALTRESPESERES]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPONIBILE]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPONIBILERES]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPOSTA]                DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPOSTARES]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTDOCUMENTO]              DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTDOCUMENTORES]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESETRASP]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESETRASPRES]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEIMBALLO]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEIMBALLORES]        DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEIMBALLO]        DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEIMBALLORES]     DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESETRASP]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESETRASPRES]       DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [SPESEDOCEURO]              DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [SPESEEFFETTOEURO]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEDOCEURO]           DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEEFFETTOEURO]       DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEDOCEURO]        DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEEFFETTOEURO]    DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVAALTRESPESEEURO]      DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVAALTRESPESEEURORES]   DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTALTRESPESEEURO]         DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTALTRESPESEEURORES]      DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPONIBILEEURO]         DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPONIBILEEURORES]      DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPOSTAEURO]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIMPOSTAEURORES]         DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTNONIMPONIBILE]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTNONIMPONIBILERES]       DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTNONIMPONIBILEEURO]      DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTNONIMPONIBILEEURORES]   DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTDOCUMENTOEURO]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTDOCUMENTOEURORES]       DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESETRASPEURO]         DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESETRASPEURORES]      DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEIMBALLOEURO]       DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTSPESEIMBALLOEURORES]    DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEIMBALLOEURO]    DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESEIMBALLOEURORES] DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESETRASPEURO]      DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTIVASPESETRASPEURORES]   DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [PRCSPESEIMBALLO]           VARCHAR (10)     NULL,
    [PRCSPESETRASP]             VARCHAR (10)     NULL,
    [CODIVASPTRASP]             DECIMAL (5)      NULL,
    [DATACONSEGNA]              DATETIME         NULL,
    [DATAMOVMAGAZZINO]          DATETIME         NULL,
    [TRASPACURA]                DECIMAL (5)      NULL,
    [CAUSALETRASP]              DECIMAL (5)      NULL,
    [DATAINIZIOTRASP]           DATETIME         NULL,
    [ORAINIZIOTRASP]            VARCHAR (5)      NULL,
    [MODOTRASP]                 DECIMAL (5)      NULL,
    [ASPETTOBENI]               VARCHAR (80)     NULL,
    [ASPETTOBENIINLINGUA]       VARCHAR (80)     NULL,
    [PORTO]                     DECIMAL (5)      NULL,
    [NUMCOLLI]                  DECIMAL (16, 6)  DEFAULT (0) NOT NULL,
    [ANNOTAZIONI]               VARCHAR (500)    NULL,
    [TOTPESONETTO]              DECIMAL (16, 6)  DEFAULT (0) NOT NULL,
    [TOTPESOLORDO]              DECIMAL (16, 6)  DEFAULT (0) NOT NULL,
    [TOTPESOIMBALLO]            DECIMAL (16, 6)  DEFAULT (0) NOT NULL,
    [TOTSUPERFICIE]             DECIMAL (16, 6)  DEFAULT (0) NOT NULL,
    [TOTVOLUME]                 DECIMAL (16, 6)  DEFAULT (0) NOT NULL,
    [NATURATRANS]               DECIMAL (5)      NULL,
    [CONDCONSINTRA]             VARCHAR (1)      NULL,
    [ORIGINEINTRACEE]           VARCHAR (3)      NULL,
    [DESTINAZIONE]              VARCHAR (3)      NULL,
    [VALSTATCEE]                DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [VALSTATCEEEURO]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [NUMLETTERACREDITO]         VARCHAR (25)     NULL,
    [DATALETTERACREDITO]        DATETIME         NULL,
    [SCONTOINCOND]              DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [SCONTOINCONDEURO]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [PRCSCONTOINCOND]           VARCHAR (10)     NULL,
    [INCIDENZASCONTI]           DECIMAL (20, 10) NULL,
    [IMPORTOPAGATO]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [IMPORTOPAGATOEURO]         DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [CODCFFATT]                 VARCHAR (7)      NULL,
    [DATADEC]                   DATETIME         NULL,
    [BLOCCATO]                  SMALLINT         DEFAULT (0) NULL,
    [FLAGCONT]                  SMALLINT         DEFAULT (0) NULL,
    [TOTOMAGGI]                 DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTOMAGGIRES]              DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTOMAGGIEURO]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TOTOMAGGIEURORES]          DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [RIVIVAOMAGGI]              SMALLINT         DEFAULT (0) NULL,
    [MESELIQUIDAZ]              SMALLINT         DEFAULT (0) NULL,
    [ANNOLIQUIDAZ]              DECIMAL (5)      NULL,
    [IMPORTIPRELEVATI]          INT              DEFAULT (0) NULL,
    [UTENTEMODIFICA]            VARCHAR (25)     NOT NULL,
    [DATAMODIFICA]              DATETIME         NOT NULL,
    [MESEPLAFOND]               SMALLINT         DEFAULT (0) NULL,
    [ANNOPLAFOND]               DECIMAL (5)      DEFAULT (0) NULL,
    [flgImpExp]                 SMALLINT         NULL,
    [TotCauz]                   DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotCauzEuro]               DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotCauzRes]                DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotCauzEuroRes]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotIVACauz]                DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotIVACauzEuro]            DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotIVACauzRes]             DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [TotIVACauzEuroRes]         DECIMAL (19, 4)  DEFAULT (0) NOT NULL,
    [Legame]                    VARCHAR (50)     NULL,
    [SPESERIPMAG]               DECIMAL (19, 4)  CONSTRAINT [DF_TESTEDOCUMENTI_SPESERIPMAG] DEFAULT (0) NULL,
    [SPESERIPMAGEURO]           DECIMAL (19, 4)  CONSTRAINT [DF_TESTEDOCUMENTI_SPESERIPMAGEURO] DEFAULT (0) NULL,
    [DOCREPLICATO]              SMALLINT         NULL,
    [Stagione]                  VARCHAR (3)      CONSTRAINT [DF_TESTEDOCUMENTI_STAGIONE] DEFAULT ('') NULL,
    [AnnoStagione]              VARCHAR (3)      CONSTRAINT [DF_TESTEDOCUMENTI_ANNOSTAGIONE] DEFAULT ('') NULL,
    [PROGRESSIVOCTR]            DECIMAL (10)     CONSTRAINT [DF_TESTEDOCUMENTI_PROGRESSIVOCTR] DEFAULT (0) NULL,
    [RifTransferOrder]          DECIMAL (10)     NULL,
    [RIFDOCPERIFERIA]           VARCHAR (30)     NULL,
    [ESISTEPROMOTOTALE]         SMALLINT         DEFAULT (0) NULL,
    [VALORESCONTOPROMOTOTALE]   DECIMAL (19, 6)  DEFAULT (0) NULL,
    [NOTEMAG]                   VARCHAR (256)    NULL,
    [NOTECOMM]                  VARCHAR (256)    NULL,
    [NOTEALTRO]                 VARCHAR (256)    NULL,
    [RIFTESTAPL]                DECIMAL (10)     NULL,
    [NUMCOLLIPL]                INT              NULL,
    [TIPOORDINE]                SMALLINT         NULL,
    [RifBollaDoganale]          VARCHAR (20)     NULL,
    [NumColliDoganale]          DECIMAL (16, 6)  DEFAULT ((0)) NULL,
    [PesoSpedDoganale]          DECIMAL (16, 6)  DEFAULT ((0)) NULL,
    [SpuntaDocCarico]           SMALLINT         DEFAULT ((0)) NULL,
    [COMMITTENTELOGISTICA]      VARCHAR (7)      NULL,
    [FLGBLACKLIST]              SMALLINT         NULL,
    [CODICECIG]                 VARCHAR (10)     CONSTRAINT [DF_TESTEDOCUMENTI_CODICECIG] DEFAULT ('') NOT NULL,
    [CODICECUP]                 VARCHAR (15)     CONSTRAINT [DF_TESTEDOCUMENTI_CODICECUP] DEFAULT ('') NOT NULL,
    [TIPODOCBLACKLIST]          SMALLINT         NULL,
    [IMPORTORITENUTA]           DECIMAL (19, 4)  DEFAULT ((0)) NOT NULL,
    [IMPORTORITENUTAEURO]       DECIMAL (19, 4)  DEFAULT ((0)) NOT NULL,
    [IMPORTOALTRORA]            DECIMAL (19, 4)  DEFAULT ((0)) NOT NULL,
    [IMPORTOALTRORAEURO]        DECIMAL (19, 4)  DEFAULT ((0)) NOT NULL,
    [PROGRESSIVOSSP]            DECIMAL (10)     DEFAULT ((0)) NOT NULL,
    [NAZIONEDDM]                DECIMAL (5)      NULL,
    [CODICEBUYER]               VARCHAR (7)      NULL,
    [DATAVALLIST]               DATETIME         NULL,
    [TIPOVALLIST]               SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TIPOVALLIST] DEFAULT ((0)) NOT NULL,
    [NRBANCALI]                 INT              NULL,
    [CONSEGNAURGENTE]           SMALLINT         DEFAULT ((0)) NULL,
    [TOTIMPOSTAART17]           DECIMAL (19, 4)  DEFAULT ((0)) NULL,
    [TOTIMPOSTAART17EURO]       DECIMAL (19, 4)  DEFAULT ((0)) NULL,
    [CODIVASPDOC]               DECIMAL (5)      NULL,
    [CODIVASPIMB]               DECIMAL (5)      NULL,
    [CODIVASPEFF]               DECIMAL (5)      NULL,
    [TOTMERCE]                  DECIMAL (19, 4)  DEFAULT ((0)) NULL,
    [TOTMERCERES]               DECIMAL (19, 4)  DEFAULT ((0)) NULL,
    [TOTMERCEEURO]              DECIMAL (19, 4)  DEFAULT ((0)) NULL,
    [TOTMERCEEURORES]           DECIMAL (19, 4)  DEFAULT ((0)) NULL,
    [IMPORTOCASSA]              DECIMAL (19, 4)  CONSTRAINT [DF_TESTEDOCUMENTI_IMPORTOCASSA] DEFAULT ((0)) NULL,
    [IMPORTOCASSAEURO]          DECIMAL (19, 4)  CONSTRAINT [DF_TESTEDOCUMENTI_IMPORTOCASSAEURO] DEFAULT ((0)) NULL,
    [PRCCASSA]                  DECIMAL (19, 4)  CONSTRAINT [DF_TESTEDOCUMENTI_PRCCASSA] DEFAULT ((0)) NULL,
    [PRCRITACC]                 DECIMAL (19, 4)  CONSTRAINT [DF_TESTEDOCUMENTI_PRCRITACC] DEFAULT ((0)) NULL,
    [PROGDICHINTENTO]           DECIMAL (10)     CONSTRAINT [DF_TESTEDOCUMENTI_PROGDICHINTENTO] DEFAULT ((0)) NULL,
    [SPLITPAYMENT]              SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_SPLITPAYMENT] DEFAULT ((0)) NULL,
    [DATADOCBOLLADOG]           DATETIME         NULL,
    [NUMRIFBOLLADOG]            VARCHAR (15)     NULL,
    [SEZIONALEIVA]              VARCHAR (1)      NULL,
    [ASPETTOBENIMAN]            SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_ASPETTOBENIMAN] DEFAULT ((0)) NULL,
    [NUMCOLLIMAN]               SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_NUMCOLLIMAN] DEFAULT ((0)) NULL,
    [TOTPESONETTOMAN]           SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTPESONETTOMAN] DEFAULT ((0)) NULL,
    [TOTPESOLORDOMAN]           SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTPESOLORDOMAN] DEFAULT ((0)) NULL,
    [TOTPESOIMBALLOMAN]         SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTPESOIMBALLOMAN] DEFAULT ((0)) NULL,
    [TOTSUPERFICIEMAN]          SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTSUPERFICIEMAN] DEFAULT ((0)) NULL,
    [TOTVOLUMEMAN]              SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTVOLUMEMAN] DEFAULT ((0)) NULL,
    [SPESERIPMAGMAN]            SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_SPESERIPMAGMAN] DEFAULT ((0)) NULL,
    [IMPORTORITENUTAMAN]        SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_IMPORTORITENUTAMAN] DEFAULT ((0)) NULL,
    [TOTSPESETRASPMAN]          SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTSPESETRASPMAN] DEFAULT ((0)) NULL,
    [TOTSPESEIMBALLOMAN]        SMALLINT         CONSTRAINT [DF_TESTEDOCUMENTI_TOTSPESEIMBALLOMAN] DEFAULT ((0)) NULL,
    [FLGBOLLOVIRTUALE]          SMALLINT         DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TESTEDOCUMENTI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_TD_flgImpExp] CHECK ([flgImpExp] is null or [flgImpExp] = 2 or [flgImpExp] = 1 or [flgImpExp] = 0),
    CONSTRAINT [CHK_TESTEDOCUMENTI_FLGBLACKLIST] CHECK ([FLGBLACKLIST]=(1) OR [FLGBLACKLIST]=(0)),
    CONSTRAINT [CHK_TESTEDOCUMENTI_FLGBOLLOVIRTUALE] CHECK ([FLGBOLLOVIRTUALE]=(1) OR [FLGBOLLOVIRTUALE]=(0)),
    CONSTRAINT [CHK_TESTEDOCUMENTI_SPLITPAYMENT] CHECK ([SPLITPAYMENT]=(1) OR [SPLITPAYMENT]=(0)),
    CONSTRAINT [CHK_TESTEDOCUMENTI_TIPODOCBLACKLIST] CHECK ([TIPODOCBLACKLIST]=(2) OR [TIPODOCBLACKLIST]=(1) OR [TIPODOCBLACKLIST]=(0)),
    CONSTRAINT [CKC_ADDSPESEDOCUM_TESTEDOC] CHECK ([ADDSPESEDOCUM] = 0 or [ADDSPESEDOCUM] = 1),
    CONSTRAINT [CKC_ADDSPESEEFFETTO_TESTEDOC] CHECK ([ADDSPESEEFFETTO] = 0 or [ADDSPESEEFFETTO] = 1),
    CONSTRAINT [CKC_ADDSPESEIMBALLO_TESTEDOC] CHECK ([ADDSPESEIMBALLO] = 0 or [ADDSPESEIMBALLO] = 1),
    CONSTRAINT [CKC_ADDSPESETRASPORTO_TESTEDOC] CHECK ([ADDSPESETRASPORTO] = 0 or [ADDSPESETRASPORTO] = 1),
    CONSTRAINT [CKC_BLOCCATO_TESTEDOC] CHECK ([BLOCCATO] = 0 or [BLOCCATO] = 1),
    CONSTRAINT [CKC_DOCCHIUSO_TESTEDOC] CHECK ([DOCCHIUSO] = 0 or [DOCCHIUSO] = 1),
    CONSTRAINT [CKC_FLAGCONT_TESTEDOC] CHECK ([FLAGCONT] = 0 or [FLAGCONT] = 1),
    CONSTRAINT [CKC_RIVIVAOMAGGI_TESTEDOC] CHECK ([RIVIVAOMAGGI] = 0 or [RIVIVAOMAGGI] = 1),
    CONSTRAINT [CKC_SEGNO_TESTEDOC] CHECK ([SEGNO] = 1 or [SEGNO] = 0 or [SEGNO] = (-1)),
    CONSTRAINT [FK_TESTEDOCUMENTI_CODCLIFOR] FOREIGN KEY ([CODCLIFOR]) REFERENCES [dbo].[ANAGRAFICACF] ([CODCONTO]),
    CONSTRAINT [FK_TESTEDOCUMENTI_TIPODOC] FOREIGN KEY ([TIPODOC]) REFERENCES [dbo].[PARAMETRIDOC] ([CODICE])
);


GO
CREATE NONCLUSTERED INDEX [TESTEDOCUMENTI_CLIFOR]
    ON [dbo].[TESTEDOCUMENTI]([CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [TESTEDOCUMENTI_TIPDOC]
    ON [dbo].[TESTEDOCUMENTI]([TIPODOC] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [TESTEDOCUMENTI_KEY]
    ON [dbo].[TESTEDOCUMENTI]([ESERCIZIO] ASC, [TIPODOC] ASC, [NUMERODOC] ASC, [BIS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IDX_TESTEDOCUMENTI_TIPODOC]
    ON [dbo].[TESTEDOCUMENTI]([TIPODOC] ASC)
    INCLUDE([PROGRESSIVO], [ESERCIZIO], [NUMERODOC], [CODCLIFOR]);


GO
CREATE NONCLUSTERED INDEX [TESTEDOCUMENTI_DataDocumento]
    ON [dbo].[TESTEDOCUMENTI]([DATADOC] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_TESTEDOCUMENTI_9_256719967__K9_K1_K3_K7_K2_4_6_43_44_45_46]
    ON [dbo].[TESTEDOCUMENTI]([CODCLIFOR] ASC, [PROGRESSIVO] ASC, [TIPODOC] ASC, [DOCCHIUSO] ASC, [ESERCIZIO] ASC)
    INCLUDE([NUMERODOC], [DATADOC], [RAGSOCDDM], [INDIRIZZODDM], [CAPDDM], [LOCALITADDM]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_TESTEDOCUMENTI_9_256719967__K1_K3_K2_4_6]
    ON [dbo].[TESTEDOCUMENTI]([PROGRESSIVO] ASC, [TIPODOC] ASC, [ESERCIZIO] ASC)
    INCLUDE([NUMERODOC], [DATADOC]);


GO
CREATE STATISTICS [_dta_stat_256719967_1_3_7]
    ON [dbo].[TESTEDOCUMENTI]([PROGRESSIVO], [TIPODOC], [DOCCHIUSO]);


GO
CREATE STATISTICS [_dta_stat_256719967_7_9_1]
    ON [dbo].[TESTEDOCUMENTI]([DOCCHIUSO], [CODCLIFOR], [PROGRESSIVO]);


GO
CREATE STATISTICS [_dta_stat_256719967_2_9_1_3]
    ON [dbo].[TESTEDOCUMENTI]([ESERCIZIO], [CODCLIFOR], [PROGRESSIVO], [TIPODOC]);


GO
CREATE STATISTICS [_dta_stat_256719967_3_7_2_9]
    ON [dbo].[TESTEDOCUMENTI]([TIPODOC], [DOCCHIUSO], [ESERCIZIO], [CODCLIFOR]);


GO
CREATE STATISTICS [_dta_stat_256719967_3_2_7_1]
    ON [dbo].[TESTEDOCUMENTI]([TIPODOC], [ESERCIZIO], [DOCCHIUSO], [PROGRESSIVO]);


GO

CREATE TRIGGER TD_TESTEDOCUMENTIFORPRENOTATI ON TESTEDOCUMENTI FOR DELETE AS

BEGIN
    
    DECLARE
       @NUMROWS  INT
 
       SELECT  @NUMROWS = @@ROWCOUNT
       IF @NUMROWS = 0
          RETURN
    
       /*  AGGIORNAMENTO PRENOTATI SULLA CANCELLAZIONE DOCUMENTI DI USCITA*/
       UPDATE TP_PRENOTATI
       SET IDTESTAE=NULL,IDRIGAE=NULL,STATO='O' 
       FROM TP_PRENOTATI T2, DELETED T1         
       WHERE T2.IDTESTAE = T1.PROGRESSIVO       

       DELETE TP_BOLLESUPRENPRELEVATE 
       FROM TP_BOLLESUPRENPRELEVATE T2, DELETED T1         
       WHERE T2.IDTESTAE = T1.PROGRESSIVO       
        

    RETURN
 

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR ('Errore Cancellazione TESTEDOCUMENTIFORPRENOTATI.', 16, 1);
    ROLLBACK  TRANSACTION
END


GO


CREATE TRIGGER [dbo].[Biri_TIDU_TESTEDOCUMENTI] ON [dbo].[TESTEDOCUMENTI] FOR INSERT AS
BEGIN
    DECLARE
       @NUMROWS  INT,
	   @PROGR INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255),
	   @UTENTECORRENTE VARCHAR (12)
 
	SELECT @UTENTECORRENTE=CURRENT_USER
    SELECT  @NUMROWS = @@ROWCOUNT
	SELECT @PROGR= [PROGRESSIVO] from INSERTED

    IF @NUMROWS = 0
       RETURN
    IF EXISTS (SELECT [TIPODOC] FROM INSERTED WHERE [TIPODOC] in ('RFW','RFJ','RFI','RFX'))
	BEGIN
   	
					If NOT EXISTS (SELECT PROGRESSIVO FROM BIRI_TESTEDOC_DOUBLE WHERE (PROGRESSIVO = @PROGR))
								
						BEGIN
						INSERT INTO BIRI_TESTEDOC_DOUBLE(PROGRESSIVO, ESERCIZIO, TIPODOC, NUMERODOC, NUMRIFDOC, UTENTEMODIFICA, DATAMODIFICA)
						SELECT  PROGRESSIVO, ESERCIZIO, TIPODOC, NUMERODOC, NUMRIFDOC, @UTENTECORRENTE, getdate() FROM   inserted T1
					END

    RETURN
 
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END
END


GO

CREATE TRIGGER TD_TESTEDOCUMENTIFORVBANCO ON TESTEDOCUMENTI FOR DELETE AS

BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)
 
       SELECT  @NUMROWS = @@ROWCOUNT
       IF @NUMROWS = 0
          RETURN
    
    
       /*  AGGIORNAMENTO "RigheVBanco"  */
       UPDATE RigheVBanco
       SET   RIFTESTEDOC = 0
       FROM   RIGHEVBANCO T2, DELETED T1
       WHERE  T2.RIFTESTEDOC = T1.PROGRESSIVO
 
    
    RETURN
 

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "Ald_TD_TESTEDOCUMENTI" FOR TABLE "TESTEDOCUMENTI"  */
CREATE TRIGGER Ald_TD_TESTEDOCUMENTI ON TESTEDOCUMENTI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)
 
    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
    /*  Accoda record testa cancellata su tbl temporanea ALD_TestCancTesteDoc*/
    insert into ALD_TestCancTesteDoc (PROGRESSIVO ,ESERCIZIO, TIPODOC, NUMERODOC, CODCLIFOR, DescrAzione, UTENTEMODIFICA, DATAMODIFICA)
   select PROGRESSIVO ,ESERCIZIO, TIPODOC, NUMERODOC, CODCLIFOR, 'cancellazione documento', user, GETDATE()
    FROM   DELETED T1

    
    /* tenere questa sezione DELETE ALL CHILDREN IN "RIGHEDOCUMENTI"  */
    -- DELETE RIGHEDOCUMENTI 
    -- FROM   RIGHEDOCUMENTI T2, DELETED T1 
    -- WHERE  T2.IDTESTA = T1.PROGRESSIVO 
    
 
    RETURN
 
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END


GO
CREATE TRIGGER TD_TESTEDOCUMENTI ON TESTEDOCUMENTI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)
 
    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
    /*  AGGIORNAMENTO "PIANOFATTCOMMCLI"  */
	UPDATE PIANOFATTCOMMCLI
	SET   IDTESTADOCEMFATT = 0, STATOFATTURAZIONE = 0
	FROM   PIANOFATTCOMMCLI T2, DELETED T1
	WHERE  T2.IDTESTADOCEMFATT = T1.PROGRESSIVO
	
	/*  DELETE ALL CHILDREN IN "RettificheIntra"  */
	DELETE RettificheIntra
    FROM   RettificheIntra T2, DELETED T1
    WHERE  T2.IDTESTADOC = T1.PROGRESSIVO	
    
	 /*  DELETE ALL CHILDREN IN "RettIntraServizi"  */
    DELETE RettIntraServizi
    FROM   RettIntraServizi T2, DELETED T1
    WHERE  T2.IDTESTADOC = T1.PROGRESSIVO    
 
    RETURN
 
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTEDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTEDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTEDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTEDOCUMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTEDOCUMENTI] TO [Metodo98]
    AS [dbo];

