CREATE TABLE [dbo].[TESTATARAGENTI] (
    [PROGRESSIVO]     DECIMAL (9)  NOT NULL,
    [CODAGENTE]       VARCHAR (7)  NOT NULL,
    [ESERCIZIO]       DECIMAL (5)  NOT NULL,
    [RAGGRUPPA]       SMALLINT     NOT NULL,
    [TIPOFILTRO]      INT          NOT NULL,
    [TIPOCARICAMENTO] INT          NOT NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    CONSTRAINT [PK_TESTATARAGENTI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTATARAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTATARAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTATARAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTATARAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTATARAGENTI] TO [Metodo98]
    AS [dbo];

