CREATE TABLE [dbo].[TESTAPIANORISORSE] (
    [CODICE]         VARCHAR (10)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (80)  NULL,
    [ALTEZZARIGA]    SMALLINT      DEFAULT (16) NULL,
    [BARRAORARIA]    SMALLINT      DEFAULT (1) NULL,
    [VISIONEPIANO]   VARCHAR (1)   DEFAULT ('R') NULL,
    [NOTE]           VARCHAR (255) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TESTAPIANORISORSE] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_VISIONEPIANO_TESTAPIA] CHECK ([VISIONEPIANO] = 'C' or [VISIONEPIANO] = 'R')
);


GO

/*  DELETE TRIGGER "TD_TESTAPIANORISORSE" FOR TABLE "TESTAPIANORISORSE"  */
CREATE TRIGGER TD_TESTAPIANORISORSE ON TESTAPIANORISORSE FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "TESTACICLOPIANORISORSE"  */
    DELETE TESTACICLOPIANORISORSE
    FROM   TESTACICLOPIANORISORSE T2, DELETED T1
    WHERE  T2.NOMEPIANORIS = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TESTAPIANORISORSE" FOR TABLE "TESTAPIANORISORSE"  */
CREATE TRIGGER TU_TESTAPIANORISORSE ON TESTAPIANORISORSE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  MODIFY PARENT CODE OF "TESTAPIANORISORSE" FOR ALL CHILDREN IN "TESTACICLOPIANORISORSE"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TESTACICLOPIANORISORSE
          SET   NOMEPIANORIS = I1.CODICE
         FROM   TESTACICLOPIANORISORSE T2, INSERTED I1, DELETED D1
         WHERE  T2.NOMEPIANORIS = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTAPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTAPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTAPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTAPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTAPIANORISORSE] TO [Metodo98]
    AS [dbo];

