CREATE TABLE [dbo].[TESTACOSTISPEDIZIONE] (
    [SPEDIZIONIERE]  DECIMAL (5)   NOT NULL,
    [NOTE]           VARCHAR (255) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TESTACOSTISPEDIZIONE] PRIMARY KEY CLUSTERED ([SPEDIZIONIERE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TESTACOSTISPEDIZIONE_SPEDIZIONIERE] FOREIGN KEY ([SPEDIZIONIERE]) REFERENCES [dbo].[TABSPEDIZ] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTACOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTACOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTACOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTACOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTACOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];

