CREATE TABLE [dbo].[TMP_TES_PROGRSCADIMP] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [IDSESSIONE]     DECIMAL (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TMP_TES_PROGRSCADIMP] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC, [IDSESSIONE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TMP_TES_PROGRSCADIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TMP_TES_PROGRSCADIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TMP_TES_PROGRSCADIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TMP_TES_PROGRSCADIMP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TMP_TES_PROGRSCADIMP] TO [Metodo98]
    AS [dbo];

