CREATE TABLE [dbo].[TP_CONF_SPUNTA_USCITA_TESTE] (
    [Codice]         INT          NOT NULL,
    [Descrizione]    VARCHAR (50) NOT NULL,
    [Deposito]       VARCHAR (10) NOT NULL,
    [Attiva]         SMALLINT     NULL,
    [UtenteModifica] VARCHAR (25) NOT NULL,
    [DataModifica]   DATETIME     NOT NULL,
    CONSTRAINT [PK__TP_CONF_SPUNTA_USCITA_TESTE] PRIMARY KEY CLUSTERED ([Codice] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE TRIGGER DELETE_TP_CONF_SPUNTA_USCITA_DETT   ON TP_CONF_SPUNTA_USCITA_TESTE 
FOR DELETE 
AS
 DELETE TP_CONF_SPUNTA_USCITA_DETT
    FROM   TP_CONF_SPUNTA_USCITA_DETT T2, DELETED T1
    WHERE  T2.codicetesta = T1.codice


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CONF_SPUNTA_USCITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CONF_SPUNTA_USCITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CONF_SPUNTA_USCITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CONF_SPUNTA_USCITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CONF_SPUNTA_USCITA_TESTE] TO [Metodo98]
    AS [dbo];

