CREATE TABLE [dbo].[TP_CONFIGURAZIONIBUYER] (
    [CODBUYER]       VARCHAR (7)  NOT NULL,
    [CODDEPOSITO]    VARCHAR (10) NOT NULL,
    [CODFORNITORE]   VARCHAR (7)  NOT NULL,
    [TUTTIARTICOLI]  SMALLINT     DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODBUYER] ASC, [CODDEPOSITO] ASC, [CODFORNITORE] ASC)
);


GO

CREATE TRIGGER [dbo].[TD_TP_CONFIGURAZIONIBUYER] ON [dbo].[TP_CONFIGURAZIONIBUYER] FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    /*  DELETE ALL CHILDREN IN "TP_CONFIGURAZIONIBUYER_GRUPPI"  */
    DELETE TP_CONFIGURAZIONIBUYER_GRUPPI
    FROM   TP_CONFIGURAZIONIBUYER_GRUPPI T2, DELETED T1
    WHERE  T2.CODBUYER = T1.CODBUYER AND
		   T2.CODDEPOSITO = T1.CODDEPOSITO AND
		   T2.CODFORNITORE = T1.CODFORNITORE

    /*  DELETE ALL CHILDREN IN "TP_CONFIGURAZIONIBUYER_CATEGORIE"  */
    DELETE TP_CONFIGURAZIONIBUYER_CATEGORIE
    FROM   TP_CONFIGURAZIONIBUYER_CATEGORIE T2, DELETED T1
    WHERE  T2.CODBUYER = T1.CODBUYER AND
		   T2.CODDEPOSITO = T1.CODDEPOSITO AND
		   T2.CODFORNITORE = T1.CODFORNITORE
    
    /*  DELETE ALL CHILDREN IN "TP_CONFIGURAZIONIBUYER_CATEGORIEST"  */
    DELETE TP_CONFIGURAZIONIBUYER_CATEGORIEST
    FROM   TP_CONFIGURAZIONIBUYER_CATEGORIEST T2, DELETED T1
    WHERE  T2.CODBUYER = T1.CODBUYER AND
		   T2.CODDEPOSITO = T1.CODDEPOSITO AND
		   T2.CODFORNITORE = T1.CODFORNITORE
    
    /*  DELETE ALL CHILDREN IN "TP_CONFIGURAZIONIBUYER_GRUPPIPRZ"  */
    DELETE TP_CONFIGURAZIONIBUYER_GRUPPIPRZ
    FROM   TP_CONFIGURAZIONIBUYER_GRUPPIPRZ T2, DELETED T1
    WHERE  T2.CODBUYER = T1.CODBUYER AND
		   T2.CODDEPOSITO = T1.CODDEPOSITO AND
		   T2.CODFORNITORE = T1.CODFORNITORE
    
    /*  DELETE ALL CHILDREN IN "TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI"  */
    DELETE TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI
    FROM   TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI T2, DELETED T1
    WHERE  T2.CODBUYER = T1.CODBUYER AND
		   T2.CODDEPOSITO = T1.CODDEPOSITO AND
		   T2.CODFORNITORE = T1.CODFORNITORE
    
    /*  DELETE ALL CHILDREN IN "TP_CONFIGURAZIONIBUYER_LIVELLIMERC"  */
    DELETE TP_CONFIGURAZIONIBUYER_LIVELLIMERC
    FROM   TP_CONFIGURAZIONIBUYER_LIVELLIMERC T2, DELETED T1
    WHERE  T2.CODBUYER = T1.CODBUYER AND
		   T2.CODDEPOSITO = T1.CODDEPOSITO AND
		   T2.CODFORNITORE = T1.CODFORNITORE
	
    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER] TO [Metodo98]
    AS [dbo];

