CREATE TABLE [dbo].[TP_CLIENTIEXPORT] (
    [MODCHIAVE]           VARCHAR (25) NOT NULL,
    [CODCONTO]            VARCHAR (7)  NOT NULL,
    [CODGRUPPOPREZZIPART] DECIMAL (5)  NULL,
    [LISTINO]             DECIMAL (5)  NULL,
    CONSTRAINT [PK_TP_CLIENTIEXPORT] PRIMARY KEY CLUSTERED ([MODCHIAVE] ASC, [CODCONTO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CLIENTIEXPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CLIENTIEXPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CLIENTIEXPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CLIENTIEXPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CLIENTIEXPORT] TO [Metodo98]
    AS [dbo];

