CREATE TABLE [dbo].[TP_CONFIGURAZIONIPUNTOFISSORIORDINO] (
    [CODDEPOSITO]    VARCHAR (10) NOT NULL,
    [CODFORNITORE]   VARCHAR (7)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODDEPOSITO] ASC, [CODFORNITORE] ASC)
);


GO

CREATE TRIGGER TD_TP_CONFIGURAZIONIPUNTOFISSORIORDINO ON TP_CONFIGURAZIONIPUNTOFISSORIORDINO FOR DELETE AS

BEGIN
    
    DECLARE
       @NUMROWS  INT
 
       SELECT  @NUMROWS = @@ROWCOUNT
       IF @NUMROWS = 0
          RETURN
    
       DELETE TP_CONFIGURAZIONIPUNTOFISSORIORDINO_RIORDINO 
       FROM TP_CONFIGURAZIONIPUNTOFISSORIORDINO_RIORDINO T2, DELETED T1         
       WHERE T2.CODDEPOSITO = T1.CODDEPOSITO AND T2.CODFORNITORE = T1.CODFORNITORE
        
	   DELETE TP_CONFIGURAZIONIPUNTOFISSORIORDINO_PERIODI
       FROM TP_CONFIGURAZIONIPUNTOFISSORIORDINO_PERIODI T2, DELETED T1         
       WHERE T2.CODDEPOSITO = T1.CODDEPOSITO AND T2.CODFORNITORE = T1.CODFORNITORE

    RETURN
 

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR ('Errore Cancellazione TP_CONFIGURAZIONIPUNTOFISSORIORDINO.', 16, 1);
    ROLLBACK  TRANSACTION
END


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIPUNTOFISSORIORDINO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIPUNTOFISSORIORDINO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIPUNTOFISSORIORDINO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIPUNTOFISSORIORDINO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIPUNTOFISSORIORDINO] TO [Metodo98]
    AS [dbo];

