CREATE TABLE [dbo].[TP_DOCTRASFAG] (
    [CODAGENTE]          VARCHAR (7)  NOT NULL,
    [CODICEDOC]          VARCHAR (3)  NOT NULL,
    [TipoGriglia]        VARCHAR (50) CONSTRAINT [DF_TP_DOCTRASFAG_TipoGriglia] DEFAULT ('') NOT NULL,
    [GiacDisp]           VARCHAR (50) CONSTRAINT [DF_TP_DOCTRASFAG_GiacDisp] DEFAULT ('') NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NULL,
    [DATAMODIFICA]       DATETIME     NULL,
    [TIPO]               CHAR (1)     NOT NULL,
    [TIPODOCEXP]         VARCHAR (3)  NULL,
    [DESCDOCEXP]         VARCHAR (25) NULL,
    [DOCPREDEF]          SMALLINT     NULL,
    [ORDINETABLET]       SMALLINT     NULL,
    [RISPETTADOCORIGINE] SMALLINT     DEFAULT ((0)) NULL,
    [PRELEVABILE]        SMALLINT     DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TP_DOCTRASFAG] PRIMARY KEY CLUSTERED ([CODAGENTE] ASC, [CODICEDOC] ASC, [TIPO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_DOCTRASFAG] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_DOCTRASFAG] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_DOCTRASFAG] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_DOCTRASFAG] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_DOCTRASFAG] TO [Metodo98]
    AS [dbo];

