CREATE TABLE [dbo].[TP_DETTAGLIO_RIGAOFN] (
    [IDSESSIONE]     NUMERIC (18)    NOT NULL,
    [IDRIGA]         INT             NOT NULL,
    [ARTICOLO]       VARCHAR (50)    NULL,
    [FORNITORE]      VARCHAR (7)     NULL,
    [FORNITOREFATT]  VARCHAR (7)     NULL,
    [MAGAZZINO]      VARCHAR (10)    NULL,
    [QUANTITAORD]    DECIMAL (18, 6) NULL,
    [QUANTITA13a]    DECIMAL (18, 6) NULL,
    [DATACONSEGNA]   DATETIME        NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [IDRIGA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_DETTAGLIO_RIGAOFN] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_DETTAGLIO_RIGAOFN] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_DETTAGLIO_RIGAOFN] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_DETTAGLIO_RIGAOFN] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_DETTAGLIO_RIGAOFN] TO [Metodo98]
    AS [dbo];

