CREATE TABLE [dbo].[TP_LISTINICALCREDD] (
    [TIPODOC]        VARCHAR (3)  NOT NULL,
    [NRLISTINO]      DECIMAL (5)  NOT NULL,
    [OFLSTValIvato]  SMALLINT     DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([TIPODOC] ASC, [NRLISTINO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_LISTINICALCREDD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_LISTINICALCREDD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_LISTINICALCREDD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_LISTINICALCREDD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_LISTINICALCREDD] TO [Metodo98]
    AS [dbo];

