CREATE TABLE [dbo].[TP_PERIODO_OSSERVAZIONE] (
    [Progressivo]    DECIMAL (18) IDENTITY (1, 1) NOT NULL,
    [Giorni]         NUMERIC (10) NOT NULL,
    [Descrizione]    VARCHAR (50) NOT NULL,
    [UtenteModifica] VARCHAR (25) NULL,
    [DataModifica]   DATETIME     NULL,
    CONSTRAINT [PK_TP_PERIODO_OSSERVAZIONE] PRIMARY KEY CLUSTERED ([Progressivo] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_PERIODO_OSSERVAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_PERIODO_OSSERVAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_PERIODO_OSSERVAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_PERIODO_OSSERVAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_PERIODO_OSSERVAZIONE] TO [Metodo98]
    AS [dbo];

