CREATE TABLE [dbo].[TP_PARTITE_VBANCO] (
    [PROGRESSIVO]    DECIMAL (10)    NOT NULL,
    [IDMov]          DECIMAL (10)    DEFAULT (0) NOT NULL,
    [IDRiga]         DECIMAL (10)    DEFAULT (0) NOT NULL,
    [NRRifPartita]   VARCHAR (15)    DEFAULT ('') NULL,
    [QTA]            DECIMAL (16, 6) DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TP_PARTITE_VBANCO] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_PARTITE_VBANCO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_PARTITE_VBANCO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_PARTITE_VBANCO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_PARTITE_VBANCO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_PARTITE_VBANCO] TO [Metodo98]
    AS [dbo];

