CREATE TABLE [dbo].[TP_ULTIMOPREZZO] (
    [CODAGENTE]      VARCHAR (7)     NOT NULL,
    [CODCONTO]       VARCHAR (7)     NOT NULL,
    [CODARTICOLO]    VARCHAR (50)    NOT NULL,
    [TIPODOC]        VARCHAR (3)     NOT NULL,
    [ESERCIZIO]      DECIMAL (5)     NOT NULL,
    [NUMERODOC]      DECIMAL (10)    NOT NULL,
    [NUMRIFDOC]      VARCHAR (15)    NULL,
    [UMGEST]         VARCHAR (3)     NOT NULL,
    [QTAGEST]        NUMERIC (19, 6) NOT NULL,
    [DATADOC]        DATETIME        NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TP_ULTIMOPREZZO] PRIMARY KEY CLUSTERED ([CODAGENTE] ASC, [CODCONTO] ASC, [CODARTICOLO] ASC, [TIPODOC] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_ULTIMOPREZZO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_ULTIMOPREZZO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_ULTIMOPREZZO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_ULTIMOPREZZO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_ULTIMOPREZZO] TO [Metodo98]
    AS [dbo];

