CREATE TABLE [dbo].[TRASPORTO_CAD_REGOLE] (
    [PROGRESSIVO]    DECIMAL (5)  NOT NULL,
    [PROGRESSIVOTV]  DECIMAL (5)  DEFAULT ((0)) NULL,
    [CODGruppo]      DECIMAL (5)  DEFAULT ((0)) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [AGG_SOST]       SMALLINT     CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_AGG_SOST] DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC),
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_TRASPORTO_CAD_GRUPPO] FOREIGN KEY ([CODGruppo]) REFERENCES [dbo].[TRASPORTO_CAD_GRUPPO] ([CODICE]) ON DELETE SET NULL,
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_TRASPORTO_CAD_TREEVIEW] FOREIGN KEY ([PROGRESSIVOTV]) REFERENCES [dbo].[TRASPORTO_CAD_TREEVIEW] ([PROGRESSIVO]) ON DELETE SET NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE] TO [Metodo98]
    AS [dbo];

