CREATE TABLE [dbo].[TRASPORTO_CAD_TIPOLOGIE] (
    [PROGRESSIVO]      DECIMAL (5)   NOT NULL,
    [DESCRIZIONE]      VARCHAR (250) NOT NULL,
    [Dettaglio]        SMALLINT      NULL,
    [CODTIPO]          SMALLINT      NOT NULL,
    [CODLIVELLO]       SMALLINT      NOT NULL,
    [CODTIPOCOSTO]     SMALLINT      NOT NULL,
    [CODTIPODOCUMENTO] SMALLINT      NOT NULL,
    [UTENTEMODIFICA]   VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]     DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC),
    CONSTRAINT [FK_TRASPORTO_CAD_TIPOLOGIE_TRASPORTO_CAD_TIPIDOCUMENTO] FOREIGN KEY ([CODTIPODOCUMENTO]) REFERENCES [dbo].[TRASPORTO_CAD_TIPIDOCUMENTO] ([PROGRESSIVO]) ON DELETE CASCADE,
    CONSTRAINT [FK_TRASPORTO_CAD_TIPOLOGIE_TRASPORTO_CAD_TIPOCOSTO] FOREIGN KEY ([CODTIPOCOSTO]) REFERENCES [dbo].[TRASPORTO_CAD_TIPOCOSTO] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TRASPORTO_CAD_TIPOLOGIE]
    ON [dbo].[TRASPORTO_CAD_TIPOLOGIE]([CODTIPO] ASC, [CODLIVELLO] ASC, [CODTIPOCOSTO] ASC, [Dettaglio] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRASPORTO_CAD_TIPOLOGIE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRASPORTO_CAD_TIPOLOGIE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TRASPORTO_CAD_TIPOLOGIE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRASPORTO_CAD_TIPOLOGIE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRASPORTO_CAD_TIPOLOGIE] TO [Metodo98]
    AS [dbo];

