CREATE TABLE [dbo].[TRASPORTO_CL_RIGHE] (
    [RIFPROGRESSIVO]       DECIMAL (18)    NOT NULL,
    [RIFPROGRESSIVODOC]    DECIMAL (10)    NOT NULL,
    [ESERCIZIO]            DECIMAL (5)     NOT NULL,
    [TIPODOC]              VARCHAR (3)     NOT NULL,
    [NUMERODOC]            DECIMAL (10)    NOT NULL,
    [UM]                   VARCHAR (3)     NOT NULL,
    [TOTALEQUANTITA]       DECIMAL (16, 6) NOT NULL,
    [TOTALECOSTOCALCOLATO] DECIMAL (19, 6) DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA]       VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]         DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [RIFPROGRESSIVODOC] ASC),
    CONSTRAINT [FK_TRASPORTO_CL_RIGHE_TRASPORTO_CL_TESTE] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TRASPORTO_CL_TESTE] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
GRANT ALTER
    ON OBJECT::[dbo].[TRASPORTO_CL_RIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRASPORTO_CL_RIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRASPORTO_CL_RIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRASPORTO_CL_RIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRASPORTO_CL_RIGHE] TO [Metodo98]
    AS [dbo];

