CREATE TABLE [dbo].[TRASPORTO_CAD_REGOLE_QUANTITA] (
    [PROGRESSIVO]        DECIMAL (5)     NOT NULL,
    [PROGRESSIVOREGOLA]  DECIMAL (5)     NOT NULL,
    [CODICE]             VARCHAR (5)     DEFAULT ('') NOT NULL,
    [TIPOCALCOLO]        DECIMAL (5)     DEFAULT ((0)) NOT NULL,
    [AGG_SOST]           SMALLINT        NOT NULL,
    [UM]                 VARCHAR (3)     NOT NULL,
    [USACOLLO]           SMALLINT        NOT NULL,
    [QUANTITA_DA]        DECIMAL (16, 6) DEFAULT ((0)) NOT NULL,
    [QUANTITA]           DECIMAL (16, 6) DEFAULT ((0)) NOT NULL,
    [PREZZO]             DECIMAL (19, 6) NOT NULL,
    [ASCAGLIONE]         NCHAR (10)      DEFAULT ((0)) NOT NULL,
    [RAGGRUPPAMENTO]     SMALLINT        DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [ARROTONDAA]         DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_QUANTITA_ARROTONDAA] DEFAULT ((0)) NOT NULL,
    [PREZZOQTA]          DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [PREZZOIFS]          DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [PREZZOBAN]          DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [QUANTITAQTA]        DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [QUANTITASCA]        DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [QUANTITABAN]        DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [ARROTONDAFINOA]     DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_ARROTONDAFINOA] DEFAULT ((0)) NOT NULL,
    [ARROTONDAOLTRE]     DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_ARROTONDAOLTRE] DEFAULT ((0)) NOT NULL,
    [RAPPORTOQTABANCALE] DECIMAL (16, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_RAPPORTOQTABANCALE] DEFAULT ((0)) NOT NULL,
    [QUANTITAQTB]        DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_QUANTITAQTB] DEFAULT ((0)) NULL,
    [ARROTONDAA_QTA]     DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_ARROTONDAA_QTA] DEFAULT ((0)) NOT NULL,
    [ARROTONDAA_QTB]     DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_ARROTONDAA_QTB] DEFAULT ((0)) NOT NULL,
    [PREZZOTOTALE]       SMALLINT        CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_PREZZOTOTALE] DEFAULT ((0)) NOT NULL,
    [VALORE_DA]          DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_CAD_REGOLE_QUANTITA_VALORE_DA] DEFAULT ((0)) NOT NULL,
    [PREZZOQTB]          DECIMAL (19, 6) CONSTRAINT [DF_TRASPORTO_PREZZOQTB] DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC),
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_QUANTITA_TRASPORTO_CAD_REGOLE] FOREIGN KEY ([PROGRESSIVOREGOLA]) REFERENCES [dbo].[TRASPORTO_CAD_REGOLE] ([PROGRESSIVO]) ON DELETE CASCADE,
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_QUANTITA_TRASPORTO_CAD_TIPOCALCOLO] FOREIGN KEY ([TIPOCALCOLO]) REFERENCES [dbo].[TRASPORTO_CAD_TIPOCALCOLO] ([CODICE]) ON DELETE SET DEFAULT,
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_QUANTITA_TRASPORTO_CDA_CODICI] FOREIGN KEY ([CODICE]) REFERENCES [dbo].[TRASPORTO_CAD_CODICI] ([CODICE]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_TRASPORTO_CAD_REGOLE_QUANTITA]
    ON [dbo].[TRASPORTO_CAD_REGOLE_QUANTITA]([PROGRESSIVOREGOLA] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_QUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_QUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_QUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_QUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_QUANTITA] TO [Metodo98]
    AS [dbo];

