
-- EXEC _FEGetDDT '577', '2'
-- select * from [ALD_B2B_VISTARIFBOVPA] where IDTESTADOC = '577'
CREATE PROCEDURE _FEGetDDT       (@Chiave1 as varchar(100),@Chiave2 as varchar(100)) AS

	--SELECT * FROM [ALD_B2B_VISTARIFBOVPA] where IDTESTADOC = @Chiave1 and PosFatt = @Chiave2
	
	WITH CTERIGHEDOC AS
	(
	   SELECT Posizione AS PosFatt,IDTESTA AS IDTESTADOC,  
	   (CASE
			WHEN CHARINDEX(';',dbo.GETRIFBOV(IDTESTARP,IDRIGARP,0))<=0 THEN 0
	   ELSE 
			LEFT(dbo.GETRIFBOV(IDTESTARP,IDRIGARP,0),CHARINDEX(';',dbo.GETRIFBOV(IDTESTARP,IDRIGARP,0))-1) 
	   END) AS IDTestaDDT,
	   (CASE
		WHEN CHARINDEX(';',dbo.GETRIFBOV(IDTESTARP,IDRIGARP,0))<=0 THEN 0   
	   ELSE
			SUBSTRING(dbo.GETRIFBOV(IDTESTARP,IDRIGARP,0),CHARINDEX(';',dbo.GETRIFBOV(IDTESTARP,IDRIGARP,0))+1, 15) 
	   END) AS IDRigaDDT
	   FROM dbo.RIGHEDOCUMENTI WHERE TIPORIGA<>'R' AND (IDTESTARP<>0 AND IDRIGARP<>0)
	)
	SELECT CTERIGHEDOC.PosFatt,CTERIGHEDOC.IDTESTADOC,CTERIGHEDOC.IDRigaDDT AS HRIISCRRbaisPr, --RigaDoc DDT
	(SELECT progressivo FROM dbo.TESTEDOCUMENTI WHERE PROGRESSIVO=CTERIGHEDOC.IDTestaDDT) AS HRIISCRMbaisPr, -- NumeroDoc DDT
	(SELECT DataDoc FROM dbo.TESTEDOCUMENTI WHERE PROGRESSIVO=CTERIGHEDOC.IDTestaDDT) AS DataDoc -- Data DDT

	FROM CTERIGHEDOC
	WHERE CTERIGHEDOC.IDTestaDDT>0	AND IDTESTADOC = @Chiave1 and PosFatt = @Chiave2	

