

CREATE PROCEDURE [dbo].[CAD_ProcDuplicaTrasportoRegolaQuantita](@PROGRESSIVO_RGL_UP_OLD DECIMAL(10,0),
                                                                 @PROGRESSIVO_RGL_UP_NEW DECIMAL(10,0))
AS

BEGIN

-- SET NOCOUNT ON added to prevent extra result sets from
-- interfering with SELECT statements.
SET NOCOUNT ON;

DECLARE @PROGRESSIVO_RGL_CUR        DECIMAL(10,0)
DECLARE @PROGRESSIVO_RGL_NEW        DECIMAL(10,0)
    
    SET @PROGRESSIVO_RGL_CUR = 0
    SET @PROGRESSIVO_RGL_NEW = 0

    /*Regole Quantita Inizio*/
    DECLARE Trasporti_RGL_Cursor CURSOR LOCAL FORWARD_ONLY FOR
        SELECT ISNULL(PROGRESSIVO,0) 
        FROM TRASPORTO_CAD_REGOLE_QUANTITA
        WHERE PROGRESSIVOREGOLA = @PROGRESSIVO_RGL_UP_OLD
    OPEN Trasporti_RGL_Cursor

    FETCH NEXT FROM Trasporti_RGL_Cursor
        INTO @PROGRESSIVO_RGL_CUR

    WHILE @@FETCH_STATUS = 0
        BEGIN
            EXEC NUOVOPROGRESSIVO 'TRASPORTO_CAD_REGOLE_QUANTITA',1,@PROGRESSIVO_RGL_NEW OUTPUT
            
            INSERT INTO [TRASPORTO_CAD_REGOLE_QUANTITA]([PROGRESSIVO],[PROGRESSIVOREGOLA],[CODICE],[TIPOCALCOLO],[AGG_SOST],[UM],[USACOLLO],[QUANTITA_DA],[QUANTITA],[QUANTITABAN],[QUANTITAQTA],[QUANTITAQTB],[QUANTITASCA],[PREZZO],[PREZZOBAN],[PREZZOIFS],[PREZZOQTA],[ASCAGLIONE],[RAGGRUPPAMENTO],[ARROTONDAA],[ARROTONDAFINOA],[ARROTONDAOLTRE],[ARROTONDAA_QTA],[ARROTONDAA_QTB],[RAPPORTOQTABANCALE],[PREZZOTOTALE],[VALORE_DA],[UTENTEMODIFICA],[DATAMODIFICA])
            SELECT @PROGRESSIVO_RGL_NEW,@PROGRESSIVO_RGL_UP_NEW,[CODICE],[TIPOCALCOLO],[AGG_SOST],[UM],[USACOLLO],[QUANTITA_DA],[QUANTITA],[QUANTITABAN],[QUANTITAQTA],[QUANTITAQTB],[QUANTITASCA],[PREZZO],[PREZZOBAN],[PREZZOIFS],[PREZZOQTA],[ASCAGLIONE],[RAGGRUPPAMENTO],[ARROTONDAA],[ARROTONDAFINOA],[ARROTONDAOLTRE],[ARROTONDAA_QTA],[ARROTONDAA_QTB],[RAPPORTOQTABANCALE],[PREZZOTOTALE],[VALORE_DA],USER_NAME(),GETDATE() FROM [TRASPORTO_CAD_REGOLE_QUANTITA] WHERE [PROGRESSIVO] = @PROGRESSIVO_RGL_CUR
            
            FETCH NEXT FROM Trasporti_RGL_Cursor
                INTO @PROGRESSIVO_RGL_CUR
        END
    CLOSE Trasporti_RGL_Cursor
    DEALLOCATE Trasporti_RGL_Cursor
    /*Regole Quantita Fine*/
    
RETURN
END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[CAD_ProcDuplicaTrasportoRegolaQuantita] TO [Metodo98]
    AS [dbo];

