
CREATE PROCEDURE [dbo].[CAD_ProcDuplicaTrasportoTreeview_NodoPadre](@PROGRESSIVO_CFG_CUR DECIMAL(10,0),
															         @PROGRESSIVO_CFG_NEW DECIMAL(10,0))
AS

BEGIN

-- SET NOCOUNT ON added to prevent extra result sets from
-- interfering with SELECT statements.
SET NOCOUNT ON;


DECLARE @PROGRESSIVO_TRV_CUR		DECIMAL(10,0)
DECLARE @PROGRESSIVO_TRV_NEW		DECIMAL(10,0)
	
	SET @PROGRESSIVO_TRV_CUR = 0
	SET @PROGRESSIVO_TRV_NEW = 0
	
	/*TreeView Inizio*/
	DECLARE Trasporti_Trv_Padre_Cursor CURSOR LOCAL FORWARD_ONLY FOR
		SELECT ISNULL(PROGRESSIVO,0) 
		FROM TRASPORTO_CAD_TREEVIEW 
		WHERE RIFPROGRESSIVO = @PROGRESSIVO_CFG_CUR AND 
			  RIFPROGPADRE = 0
	OPEN Trasporti_Trv_Padre_Cursor

	FETCH NEXT FROM Trasporti_Trv_Padre_Cursor
		INTO @PROGRESSIVO_TRV_CUR

	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC NUOVOPROGRESSIVO 'TRASPORTO_CAD_TREEVIEW',1,@PROGRESSIVO_TRV_NEW OUTPUT

			INSERT INTO [TRASPORTO_CAD_TREEVIEW] ([PROGRESSIVO],[RIFPROGRESSIVO],[RIFPROGPADRE],[RIFNODOPADRE],[RIFNODO],[TIPONODO],[LIVELLONODO],[RIFTIPOLOGIE],[UTENTEMODIFICA],[DATAMODIFICA])
										   SELECT @PROGRESSIVO_TRV_NEW,@PROGRESSIVO_CFG_NEW,[RIFPROGPADRE],[RIFNODOPADRE],[RIFNODO],[TIPONODO],[LIVELLONODO],[RIFTIPOLOGIE],USER_NAME(),GETDATE() FROM [TRASPORTO_CAD_TREEVIEW] WHERE [PROGRESSIVO] = @PROGRESSIVO_TRV_CUR
			
			EXEC CAD_ProcDuplicaTrasportoRegola @PROGRESSIVO_TRV_CUR, @PROGRESSIVO_TRV_NEW
			EXEC CAD_ProcDuplicaTrasportoFiltro @PROGRESSIVO_CFG_NEW, @PROGRESSIVO_TRV_CUR, @PROGRESSIVO_TRV_NEW
			EXEC CAD_ProcDuplicaTrasportoTreeview_NodoFiglio @PROGRESSIVO_CFG_NEW, @PROGRESSIVO_TRV_CUR, @PROGRESSIVO_TRV_NEW
			
			FETCH NEXT FROM Trasporti_Trv_Padre_Cursor
				INTO @PROGRESSIVO_TRV_CUR
		END
	CLOSE Trasporti_Trv_Padre_Cursor
	DEALLOCATE Trasporti_Trv_Padre_Cursor
	/*TreeView Fine*/
	
RETURN
END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[CAD_ProcDuplicaTrasportoTreeview_NodoPadre] TO [Metodo98]
    AS [dbo];

