
CREATE PROCEDURE [dbo].[GEM_RAPPORTI_FATTURAZIONE] (@IDRAPPORTO AS VARCHAR(30), @IDSESSIONE AS INT) AS
/* --- TEST
DECLARE @IDRAPPORTO			AS VARCHAR(30)
DECLARE @IDSESSIONE			AS INT
SET @IDRAPPORTO			= '2010OR000540SI'
SET @IDSESSIONE			= 3131
*/

	-- Cancellazione tabella temporanea RECORD PRECEDENTI 
	DELETE [GEM_TMP_OPER_FATT_ANTICIP] WHERE IDSESSIONE = @IDSESSIONE
	-- Cancellazione elementi da fatturare di elaborazioni precendenti
	DELETE GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE	WHERE  [IDRAPPORTO] = @IDRAPPORTO
	-- Inserimento record di elaborazione per guidare selezione della visione successiva all'elaborazione
	EXECUTE [dbo].[GEM_InsLogRapportoRataEab]  @idSessione ,@IDRAPPORTO ,'' ,0


	-- VARIABILI DELLA STORED
	DECLARE @IDCONTRATTO			AS VARCHAR(13)
	DECLARE @SEZIONECONTRATTO		AS DECIMAL (5,0)
	DECLARE @MESSAGGIOERRORE		AS VARCHAR(255)
	DECLARE @RADICEMESS				AS VARCHAR(255)
	DECLARE @DESCR_INT				AS VARCHAR(255)
	DECLARE @CODICEMEZZOCONTRATTO	AS VARCHAR(50)
	DECLARE @CODICEARTICOLO			AS VARCHAR(50)
	DECLARE @CODARTICOLOFATT		AS VARCHAR(50)
	DECLARE @IDMODFATT				AS DECIMAL (5,0)
	DECLARE @IDTIPOFATT				AS DECIMAL (5,0)
	DECLARE @IDTIPOLOGMEZZO			AS DECIMAL (5,0)
	DECLARE @IDRIGAMEZZO			AS DECIMAL (5,0)
	DECLARE @IDATTIVITA				AS DECIMAL (5,0)
	DECLARE @IDRIGAATTIVITA			AS DECIMAL (5,0)
	DECLARE @DA_FATT				AS VARCHAR(1)
	DECLARE @TIPOLOGIARAPPORTO		AS VARCHAR(2)
	DECLARE @RIFCLIENTE				AS VARCHAR(50)
	DECLARE @NUMOPERAZIONITOTALI	AS INT
	DECLARE @NUMOPERAZIONIANNO		AS INT
	DECLARE @NUMOPERAZIONIDEROGA	AS INT
	DECLARE @ATTIVITADAFATTURARE	AS INT
	DECLARE @QUANTITA				DECIMAL(12,4)
	DECLARE @RET_CODART				AS INT
	DECLARE @POS_PREZZO				AS INT
	DECLARE @IMPORTOAT1				AS DECIMAL(12,4)
	DECLARE @IMPORTOAT2				AS DECIMAL(12,4)
	DECLARE @IMPORTOAT3				AS DECIMAL(12,4)
	DECLARE @IMPORTOAT4				AS DECIMAL(12,4)
	DECLARE @IMPORTOAT5				AS DECIMAL(12,4)
	DECLARE @IMPORTOINS				AS DECIMAL(12,4)
	DECLARE @SCONTOAT1				AS DECIMAL(10,2)
	DECLARE @SCONTOAT2				AS DECIMAL(10,2)
	DECLARE @SCONTOAT3				AS DECIMAL(10,2)
	DECLARE @SCONTOAT4				AS DECIMAL(10,2)
	DECLARE @SCONTOAT5				AS DECIMAL(10,2)
	DECLARE @SCONTOINS				AS DECIMAL(10,2)
	DECLARE @PROV1AT1				AS DECIMAL(10,2)
	DECLARE @PROV1AT2				AS DECIMAL(10,2)
	DECLARE @PROV1AT3				AS DECIMAL(10,2)
	DECLARE @PROV1AT4				AS DECIMAL(10,2)
	DECLARE @PROV1AT5				AS DECIMAL(10,2)
	DECLARE @PROV1INS				AS DECIMAL(10,2)
	DECLARE @PROV2AT1				AS DECIMAL(10,2)
	DECLARE @PROV2AT2				AS DECIMAL(10,2)
	DECLARE @PROV2AT3				AS DECIMAL(10,2)
	DECLARE @PROV2AT4				AS DECIMAL(10,2)
	DECLARE @PROV2AT5				AS DECIMAL(10,2)
	DECLARE @PROV2INS				AS DECIMAL(10,2)
	DECLARE @TIPOFATTURAZIONE		AS VARCHAR(20)
	DECLARE @VALIDITA				AS VARCHAR(20)
	DECLARE @DATA_INTERVENTO		AS DATETIME
	DECLARE @IDRAPPORTO_STATO_ENNE	AS VARCHAR(30)
	DECLARE @ELEMENTI_INSERITI		AS INT
	DECLARE @SEDEDESC				AS VARCHAR(120)
	DECLARE @SEDEINDIRIZZO			AS VARCHAR(120)
	DECLARE @SEDELOC				AS VARCHAR(120)
	DECLARE @SEDEPROV				AS VARCHAR(5)
	DECLARE @DESCRAPP				AS VARCHAR(80)
	DECLARE @DESCTIPOFATT			AS VARCHAR(80)
	DECLARE @DESCINSERITA			as smallint
	DECLARE @RAPPORTO_RIF			AS VARCHAR(30)
	DECLARE @idRigaMateriali        AS decimal(5, 0)
	DECLARE @CodArticolo     		AS VARCHAR(50)
	DECLARE @PROVVIGIONE1           AS numeric(10,2)
	DECLARE @CodAgente1             AS varchar(7) 
	DECLARE @DSCAGENTE              AS varchar(80)
	DECLARE @idRigaOreLav           AS decimal(5, 0)	 
	--INT DI PC  del 2-3-2011 BUG OPERAZIONI PRIMARIE 
	DECLARE @IDSTRUTTURAOPPR		AS DECIMAL(5,0)
	DECLARE @REVISIONE				AS DECIMAL(5,0)

	--RECUPERO IDCONTRATT, SEZIONECONTRATTO E FLAG_FATT SUL RAPPORTO
	SELECT @IDCONTRATTO=IDCONTRATTO, @SEZIONECONTRATTO=SEZIONECONTRATTO, @DA_FATT=DA_FATT, 
		@DATA_INTERVENTO=DATA_EFF, @TIPOLOGIARAPPORTO=TIPOLOGIARAPPORTO, @DESCR_INT=ISNULL(DESCR_INT,'') ,
		@RIFCLIENTE	= ISNULL(RifCLiente,'')
	FROM dbo.GEM_SEZIONECONTRATTORAPPORTI
	where IDRAPPORTO = @IDRAPPORTO

	--IMPOSTAZIONE MESSAGGIO DI ERRORE
	SET @RADICEMESS = 'ELAB RAPPORTO: [' +  @IDRAPPORTO + '] '
	SET @ELEMENTI_INSERITI = 0
	SET @DESCINSERITA = 0

------------------------------------------------------------------------
	IF @DA_FATT = 'E' BEGIN 
		SET @MESSAGGIOERRORE = @RADICEMESS  + 'RAPPORTO CON FATTURAZIONE ESCLUSA. GEM_SEZIONECONTRATTORAPPORTI.DA_FATT=[E]'
		EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
		return 0 
	END -- NON ELABORA I RAPP IN STATO DA FATT = 'E'
------------------------------------------------------------------------

	--LEGGO TIPO FATTURAZIONE E TIPOLOGIA MEZZO
	-- 2-3-2011 @IDSTRUTTURAOPPR		@REVISIONE				

	SELECT @IDMODFATT=vc.IDMODFATT, @DESCTIPOFATT= tf.Descrizione ,@IDTIPOFATT=vc.SEZ_IDTIPOFATT, @IDTIPOLOGMEZZO=vc.IDTIPOLOGMEZZO
			,@NUMOPERAZIONIDEROGA= ISNULL(vc.NrOperazInDeroga,0)
			,@IDSTRUTTURAOPPR= ISNULL(vc.IDSTRUTTURAOPPR,0)
			,@REVISIONE= ISNULL(vc.REVISIONE,0)
			,@CODICEMEZZOCONTRATTO=vc.CODICEMEZZO, @SEDEDESC=left(vc.SedeRagSoc,71), @SEDEINDIRIZZO= left(vc.SedeIndirizzo,69), @SEDELOC= left(vc.SedeLocalita,70), @SEDEPROV =	ISNULL(vc.sedeprovincia,'')
	FROM GEM_Vistacontratti vc INNER JOIN dbo.GEM_Vista_ModalitaFatturazione mf on vc.IDMODFATT = mf.IDMODFATT
			INNER JOIN dbo.GEM_Vista_TipologieFatturazione tf ON vc.SEZ_IDTIPOFATT=tf.IDTipoFatt
	WHERE IDCONTRATTO = @IDCONTRATTO AND SEZIONECONTRATTO = @SEZIONECONTRATTO

	SET @DESCRAPP = 'Rapportino nr: ' + @IDRAPPORTO + ' del ' + LTRIM(STR(DAY(@DATA_INTERVENTO))) + '-' + LTRIM(STR(MONTH(@DATA_INTERVENTO)))+'-' +LTRIM(STR(YEAR(@DATA_INTERVENTO)))
	
		--RIGA DI DESCRIZIONE RAPPORTO
		EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
				,@SEZIONECONTRATTO 
				,@IDRAPPORTO 
				,@IDRAPPORTO
				,'D' 
				,0
				,0						--@idRigaMateriali
				,0						--@idRigaOreLav 
				,0						--@idRigaRata
				,''						--CODART
				,@DESCRAPP				--DSCART
				,0						--@QTA 
				,0						--@PREZZO 
				,0						--@SCONTO 
				,0						--@PROVVIGIONE1 
				,0						--@PROVVIGIONE2 
				,0						--@PROVVIGIONE3 
				,''						--@TipoFatturazione 
				,''						--@Validita 
				,10						--@Posizione
				,@IDSESSIONE			-- per i LOG

		--INT PC 13-01-2011 commessa 2 
		IF @RIFCLIENTE <> '' BEGIN

			SET @DESCRAPP = 'Rif. Cliente : ' + @RIFCLIENTE	

				--RIGA DI DESCRIZIONE RAPPORTO
				EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
						,@SEZIONECONTRATTO 
						,@IDRAPPORTO 
						,@IDRAPPORTO
						,'D' 
						,0
						,0						--@idRigaMateriali
						,0						--@idRigaOreLav 
						,0						--@idRigaRata
						,''						--CODART
						,@DESCRAPP				--DSCART
						,0						--@QTA 
						,0						--@PREZZO 
						,0						--@SCONTO 
						,0						--@PROVVIGIONE1 
						,0						--@PROVVIGIONE2 
						,0						--@PROVVIGIONE3 
						,''						--@TipoFatturazione 
						,''						--@Validita 
						,12						--@Posizione
						,@IDSESSIONE			-- per i LOG
		END
		--FINE INT PC 13-01-2011 commessa 2 

		
		SET @SEDEDESC = 'Presso: ' + LEFT(@SEDEDESC,71)

			--RIGA DI DESCRIZIONE SEDE
			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,@SEDEDESC				--DSCART
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,20						--@Posizione
					,@IDSESSIONE			-- per i LOG

		SET @SEDEINDIRIZZO = 'Indirizzo: ' + LEFT(@SEDEINDIRIZZO,69)

			--RIGA DI DESCRIZIONE SEDE
			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,@SEDEINDIRIZZO				--DSCART
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,22						--@Posizione
					,@IDSESSIONE			-- per i LOG




		SET @SEDELOC = 'Localita: ' + LEFT(@SEDELOC,65) + ' ' + @SEDEPROV 

			--RIGA DI DESCRIZIONE SEDE
			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,@SEDELOC				--DSCART
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,24						--@Posizione
					,@IDSESSIONE			-- per i LOG


		SET @DESCTIPOFATT = left('Tipo Fatt.Contrattuale: ' + @DESCTIPOFATT,80)

			--RIGA DI DESCRIZIONE TIPOFATTURAZIONE
			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,@DESCTIPOFATT			--DSCART
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,30						--@Posizione
					,@IDSESSIONE	-- per i LOG

		
		-- Moreno Feletto - 05.03.2018
		-- Modifica descrizione righe rapporti (TV1800022)
		IF (@TIPOLOGIARAPPORTO = 'S' OR @TIPOLOGIARAPPORTO = 'O') AND LEN(@DESCR_INT) > 0  BEGIN

			IF (@TIPOLOGIARAPPORTO = 'S' ) 
				SET @DESCR_INT = 'Descrizione Intervento Straordinario: ' + @DESCR_INT
			ELSE
				SET @DESCR_INT = 'Descrizione Intervento: ' + @DESCR_INT
			
			SET @DESCRAPP = LEFT(@DESCR_INT,80)

			--RIGA DI DESCRIZIONE INTERVENTO
			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,@DESCRAPP				--DSCART
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,32						--@Posizione
					,@IDSESSIONE			-- per i LOG

			IF LEN(@DESCR_INT) > 80 BEGIN

				SET @DESCRAPP = SUBSTRING(@DESCR_INT,81,80)

				--RIGA DI DESCRIZIONE INTERVENTO
				EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
						,@SEZIONECONTRATTO 
						,@IDRAPPORTO 
						,@IDRAPPORTO
						,'D' 
						,0
						,0						--@idRigaMateriali
						,0						--@idRigaOreLav 
						,0						--@idRigaRata
						,''						--CODART
						,@DESCRAPP				--DSCART
						,0						--@QTA 
						,0						--@PREZZO 
						,0						--@SCONTO 
						,0						--@PROVVIGIONE1 
						,0						--@PROVVIGIONE2 
						,0						--@PROVVIGIONE3 
						,''						--@TipoFatturazione 
						,''						--@Validita 
						,33						--@Posizione
						,@IDSESSIONE			-- per i LOG
			END 
			
			IF LEN(@DESCR_INT) > 160 BEGIN

				SET @DESCRAPP = SUBSTRING(@DESCR_INT,161,80)

				--RIGA DI DESCRIZIONE INTERVENTO
				EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
						,@SEZIONECONTRATTO 
						,@IDRAPPORTO 
						,@IDRAPPORTO
						,'D' 
						,0
						,0						--@idRigaMateriali
						,0						--@idRigaOreLav 
						,0						--@idRigaRata
						,''						--CODART
						,@DESCRAPP				--DSCART
						,0						--@QTA 
						,0						--@PREZZO 
						,0						--@SCONTO 
						,0						--@PROVVIGIONE1 
						,0						--@PROVVIGIONE2 
						,0						--@PROVVIGIONE3 
						,''						--@TipoFatturazione 
						,''						--@Validita 
						,34						--@Posizione
						,@IDSESSIONE			-- per i LOG
			END 
		END 



---------------------------------------------------------------------------------------------
--SE DA FATTURARE ALLORA E' DA FATTURARE SUBITO
---------------------------------------------------------------------------------------------
	IF @DA_FATT = 'S' BEGIN

----------------------------------------------------------------------------------------------------
-- FATTURAZIONE AD ACCUMULO -- ATTIVITA' ESEGUITE
----------------------------------------------------------------------------------------------------

		--PER TUTTI I MEZZI ATTIVI e visitati INSERISCO UN RECORD NELL'ARRAY
		DECLARE CURR_RIGHE CURSOR  LOCAL  FAST_FORWARD FOR

		SELECT AE.IDRIGAMEZZO, VCF.IDATTIVITA
		FROM dbo.GEM_SEZIONECONTRATTORAPPORTIMEZZI AE
		INNER JOIN GEM_Vista_Controllo_Fatturazione VCF ON  VCF.IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND VCF.IDTIPOFATT= @IDTIPOFATT AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO AND VCF.PERIODIACCUMULO = 1
		WHERE AE.IDCONTRATTO=@IDCONTRATTO AND AE.SEZIONECONTRATTO=@SEZIONECONTRATTO AND AE.IDRAPPORTO = @IDRAPPORTO 
		AND ISNULL(DATAELIMINAZIONE,DATEADD(YY,+2,GETDATE() )) > GETDATE()
		and exists ( select 1 from 	GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG SM where AE.IDCONTRATTO=SM.IDCONTRATTO AND AE.SEZIONECONTRATTO=SM.SEZIONECONTRATTO AND AE.IDRAPPORTO = SM.IDRAPPORTO AND AE.IDRIGAMEZZO = SM.IDRIGAMEZZO )


		OPEN CURR_RIGHE
		FETCH NEXT FROM CURR_RIGHE INTO @IDRIGAMEZZO, @IDATTIVITA
		WHILE @@FETCH_STATUS = 0
		BEGIN


			--LEGGO I MEZZI ATTIVI DELLA SEZIONE CONTRATTO
				--SELECT @NUMOPERAZIONITOTALI=ISNULL(nrOPerazioniTotali,0)

				DECLARE CURR_RIGHE_TMP CURSOR  LOCAL  FAST_FORWARD FOR
				SELECT ISNULL(NrOperazioniTotali,0), ISNULL(NumOperazioniAnno,0)
				FROM GEM_Vista_T_TabStruttureOperazioniPrimarie op  inner join GEM_Vista_T_TabStruttureOperazioniPrimarieRighe  opr 
					on op.idStrutturaOpPr=opr.idStrutturaOpPr
				WHERE op.idtipologmezzo = @IDTIPOLOGMEZZO AND opr.IDATTIVITA = @IDATTIVITA
--2-3-2011 BUG OPERAZIONI PRIMARIE
				and op.IDSTRUTTURAOPPR= @IDSTRUTTURAOPPR AND op.REVISIONE = @REVISIONE				
--2-3-2011 BUG OPERAZIONI PRIMARIE
				OPEN CURR_RIGHE_TMP
				FETCH NEXT FROM CURR_RIGHE_TMP INTO @NUMOPERAZIONITOTALI, @NUMOPERAZIONIANNO
				WHILE @@FETCH_STATUS = 0
				BEGIN
print '@NUMOPERAZIONIANNO'
print @NUMOPERAZIONIANNO
					--calcolo Indice count down - operazionida fatturare
					IF @NUMOPERAZIONIDEROGA > 0 AND @NUMOPERAZIONITOTALI > 0 BEGIN
						SET @ATTIVITADAFATTURARE = @NUMOPERAZIONIDEROGA / @NUMOPERAZIONITOTALI
					END
					ELSE BEGIN
						SET @ATTIVITADAFATTURARE = @NUMOPERAZIONIANNO				
					END


					--inserisco l'array temporaneo
					INSERT INTO [GEM_TMP_OPER_FATT_ANTICIP]
						   ([IDSESSIONE]
						   ,[IDRAPPORTO]
						   ,[idAttivita]
						   ,[idTipologMezzo]
						   ,[IDCONTRATTO]
						   ,[SEZIONECONTRATTO]
						   ,[IdRigaMezzo]
						   ,[AttivitaAncoraDaFatturare])
					 VALUES
						   (@IDSESSIONE
						   ,@IDRAPPORTO
						   ,@IDATTIVITA
						   ,@IDTIPOLOGMEZZO
						   ,@IDCONTRATTO
						   ,@SEZIONECONTRATTO
						   ,@IDRIGAMEZZO			
						   ,@ATTIVITADAFATTURARE)

					IF @@ERROR <> 0 BEGIN
						SET @MESSAGGIOERRORE = @RADICEMESS + 'ERRORE INS. GEM_TMP_OPER_FATT_ANTICIP'
						PRINT '2'
						PRINT @MESSAGGIOERRORE

						EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
						return 1
					END 

				FETCH NEXT FROM CURR_RIGHE_TMP INTO  @NUMOPERAZIONITOTALI, @NUMOPERAZIONIANNO
			END

			CLOSE CURR_RIGHE_TMP
			DEALLOCATE CURR_RIGHE_TMP
		

			FETCH NEXT FROM CURR_RIGHE INTO @IDRIGAMEZZO, @IDATTIVITA
		END

		CLOSE CURR_RIGHE
		DEALLOCATE CURR_RIGHE


-------------------------------------------------------------------
--ATTIVITA' AD ACCUMULO
--INSERIMENTO TABELLA ELEMENTI DA FATTURARE 
--PER LE ATTIVITA' ESEGUITE SU TUTTI I MEZZI ATTIVI 
-------------------------------------------------------------------

		SET @DESCINSERITA = 0
print '@IDTIPOLOGMEZZO'
print @IDTIPOLOGMEZZO
print '@SEZIONECONTRATTO'
print @SEZIONECONTRATTO
print '@TIPOLOGIARAPPORTO'
print @TIPOLOGIARAPPORTO
print '@IDTIPOFATT'
print @IDTIPOFATT
		DECLARE CURR_MEZZI CURSOR  LOCAL  FAST_FORWARD FOR
		SELECT AE.IDRIGAMEZZO, AE.IDRIGA, SM.CODMEZZO, AE.IDATTIVITA, ISNULL(SM.QUANTITA,1),
			ISNULL(SM.IMPORTOAT1,0),	ISNULL(SM.IMPORTOAT2,0),	ISNULL(SM.IMPORTOAT3,0),	ISNULL(SM.IMPORTOAT4,0),	ISNULL(SM.IMPORTOAT5,0),	
			ISNULL(SM.SCONTOAT1,0),		ISNULL(SM.SCONTOAT2,0),		ISNULL(SM.SCONTOAT3,0),		ISNULL(SM.SCONTOAT4,0),		ISNULL(SM.SCONTOAT5,0),	
			ISNULL(SM.PROV1AT1,0),		ISNULL(SM.PROV1AT2,0),		ISNULL(SM.PROV1AT3,0),		ISNULL(SM.PROV1AT4,0),		ISNULL(SM.PROV1AT5,0), 
			ISNULL(SM.PROV2AT1,0),		ISNULL(SM.PROV2AT2,0),		ISNULL(SM.PROV2AT3,0),		ISNULL(SM.PROV2AT4,0),		ISNULL(SM.PROV2AT5,0)
		FROM GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG AE 
			INNER JOIN dbo.GEM_SEZIONECONTRATTORAPPORTIMEZZI SM
				on AE.IDCONTRATTO=SM.IDCONTRATTO AND AE.SEZIONECONTRATTO=SM.SEZIONECONTRATTO AND AE.IDRAPPORTO = SM.IDRAPPORTO AND AE.IDRIGAMEZZO = SM.IDRIGAMEZZO
			INNER JOIN GEM_Vista_Controllo_Fatturazione VCF ON  VCF.IDATTIVITA=AE.IDATTIVITA
				AND VCF.IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND VCF.IDTIPOFATT= @IDTIPOFATT AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO AND VCF.PERIODIACCUMULO  = 1
		WHERE AE.IDCONTRATTO=@IDCONTRATTO AND AE.SEZIONECONTRATTO=@SEZIONECONTRATTO AND AE.IDRAPPORTO = @IDRAPPORTO 
		AND ISNULL(DATAELIMINAZIONE,DATEADD(YY,+2,GETDATE() )) > GETDATE()
		ORDER BY AE.IDRIGAMEZZO

		OPEN CURR_MEZZI
		FETCH NEXT FROM CURR_MEZZI INTO @IDRIGAMEZZO, @IDRIGAATTIVITA, @CODICEARTICOLO, @IDATTIVITA	, @QUANTITA,
			@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
			@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
			@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
			@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 

		WHILE @@FETCH_STATUS = 0
		BEGIN

			
			EXECUTE @RET_CODART = [GEM_GET_CODART] 
				@CODICEMEZZOCONTRATTO
				,@CODICEARTICOLO
				,@IDMODFATT
				,@IDATTIVITA
				,@CODARTICOLOFATT OUTPUT

			IF ISNULL(@CODARTICOLOFATT,'') = '' BEGIN
					SET @MESSAGGIOERRORE = @RADICEMESS  + 'ERRORE- NON ESISTE REGOLA PER COSTRUZIONE DEL CODICE ARTICOLO FATT: ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] MOD. FATT=[' + LTRIM(STR(@IDMODFATT)) +'] - COD.MEZZO=[' + (@CODICEMEZZOCONTRATTO) + ']  tabella: GEM_Vista_T_DeterminaAttivita '
					PRINT '3'
					PRINT @MESSAGGIOERRORE
					EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
--DA SCOMMENTARE
					--return 1					
			END
			--ELSE BEGIN
			--	print 'COD-ART: ' + @CODARTICOLOFATT
			--END

			--IMPOMSTO I VALORI DELLA RIGA ELEMENTI_FATTURAZIONE
			SELECT @POS_PREZZO = Posizione 
			FROM GEM_Vista_TipologMezziAttivita
			WHERE IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND IDATTIVITA = @IDATTIVITA
			IF @@ERROR <> 0 BEGIN
				SET @MESSAGGIOERRORE = @RADICEMESS + 'ERRORE: NON TROVATA RELAZIONE POSZIONI NELLA TABELLA [GEM_Vista_TipologMezziAttivita] PER ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] TIPOLOG MEZZO[' + LTRIM(STR(@IDTIPOLOGMEZZO)) +']'
				PRINT '4'
				PRINT @MESSAGGIOERRORE

				EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
--DA SCOMMENTARE
				--return 1
			END 

			--IMPOSTAZIONE PREZZO 
			SET @IMPORTOINS = 
			CASE @POS_PREZZO  
				WHEN 1 THEN @IMPORTOAT1
				WHEN 2 THEN @IMPORTOAT2
				WHEN 3 THEN @IMPORTOAT3
				WHEN 4 THEN @IMPORTOAT4
				WHEN 5 THEN @IMPORTOAT5
			END

			--IMPOSTAZIONE SCONTO
			SET @SCONTOINS = 
			CASE @POS_PREZZO  
				WHEN 1 THEN @SCONTOAT1
				WHEN 2 THEN @SCONTOAT2
				WHEN 3 THEN @SCONTOAT3
				WHEN 4 THEN @SCONTOAT4
				WHEN 5 THEN @SCONTOAT5
			END

			--IMPOSTAZIONE PROVV1
			SET @PROV1INS = 
			CASE @POS_PREZZO  
				WHEN 1 THEN @PROV1AT1
				WHEN 2 THEN @PROV1AT2
				WHEN 3 THEN @PROV1AT3
				WHEN 4 THEN @PROV1AT4
				WHEN 5 THEN @PROV1AT5
			END

			--IMPOSTAZIONE PROVV2
			SET @PROV2INS = 
			CASE @POS_PREZZO  
				WHEN 1 THEN @PROV2AT1
				WHEN 2 THEN @PROV2AT2
				WHEN 3 THEN @PROV2AT3
				WHEN 4 THEN @PROV2AT4
				WHEN 5 THEN @PROV2AT5
			END


			--IMPOSTAZIONE TIPOFATTURAZIONE
			SELECT  @TIPOFATTURAZIONE = ISNULL(TIPOFATTURAZIONE,''),@VALIDITA=ISNULL(VALIDITA,'')
			FROM GEM_Vista_Controllo_Fatturazione VCF
			WHERE IDATTIVITA = @IDATTIVITA 
				AND IDTIPOLOGMEZZO=@IDTIPOLOGMEZZO
				AND IDTIPOFATT = @IDTIPOFATT
				AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO
			--inserimento riga che descrive il prossimo elenco
			IF @DESCINSERITA = 0 BEGIN

				EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
						,@SEZIONECONTRATTO 
						,@IDRAPPORTO 
						,@IDRAPPORTO
						,'D' 
						,0
						,0						--@idRigaMateriali
						,0						--@idRigaOreLav 
						,0						--@idRigaRata
						,''						--CODART
						,'Riepilogo Attività'	--DSCART		Rif vista GEM_VISTA_ELEMENTI_FATT
						,0						--@QTA 
						,0						--@PREZZO 
						,0						--@SCONTO 
						,0						--@PROVVIGIONE1 
						,0						--@PROVVIGIONE2 
						,0						--@PROVVIGIONE3 
						,''						--@TipoFatturazione 
						,''						--@Validita 
						,1000					--@Posizione
						,@IDSESSIONE			-- per i LOG

				SET @DESCINSERITA = 1

			END 

			--CONTROLLO SE QTA INFERIORE A ZERO
			IF @QUANTITA < 1 BEGIN
				SET @QUANTITA = 1
			END

			--inserimento riga attivita
			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'A' 
					,@IDRIGAATTIVITA		
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,@CODARTICOLOFATT		--CODART
					,@CODARTICOLOFATT		--DSCART
					,@QUANTITA				--@QTA 
					,@IMPORTOINS			--@PREZZO 
					,@SCONTOINS 			--@SCONTO 
					,@PROV1INS				--@PROVVIGIONE1 
					,@PROV2INS				--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,@TIPOFATTURAZIONE		--@TipoFatturazione 
					,@VALIDITA				--@Validita 
					,1000					--@Posizione
					,@IDSESSIONE			-- per i LOG


				IF @@ERROR = 0 BEGIN
					SET @ELEMENTI_INSERITI = @ELEMENTI_INSERITI  + 1
				END 					


			--DECREMENTO L'ATTIVITA INSERITA NELLA TABELLA TEMPORANEA
				UPDATE [GEM_TMP_OPER_FATT_ANTICIP]
				SET ATTIVITAANCORADAFATTURARE = ATTIVITAANCORADAFATTURARE -1
				WHERE IDSESSIONE = @IDSESSIONE 
					AND IDRAPPORTO = @IDRAPPORTO
					AND IDCONTRATTO= @IDCONTRATTO
					AND SEZIONECONTRATTO= @SEZIONECONTRATTO
					AND IDATTIVITA=	@IDATTIVITA
					AND IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO
					AND IDRIGAMEZZO = @IDRIGAMEZZO
				
				UPDATE GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG
				SET STATO_FATTURAZIONE= 'S'
				WHERE IDCONTRATTO = @IDCONTRATTO
					AND SEZIONECONTRATTO= @SEZIONECONTRATTO
					AND IDRAPPORTO = @IDRAPPORTO
					AND IDRIGAMEZZO = @IDRIGAMEZZO
					AND IDATTIVITA=	@IDATTIVITA


			FETCH NEXT FROM CURR_MEZZI INTO @IDRIGAMEZZO, @IDRIGAATTIVITA, @CODICEARTICOLO,@IDATTIVITA, @QUANTITA,
				@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
				@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
				@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
				@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 
		END

		CLOSE CURR_MEZZI
		DEALLOCATE CURR_MEZZI




-------------------------------------------------------------------
--ATTIVITA FUTURE DA INSERIRE NEGLI ELEMENTI DI FATTURAZIONE
--INSERIMENTO TABELLA ELEMENTI DA FATTURARE 
--PER LE ATTIVITA' AD ACCUMULO DA ESEGUIRE NEL PERIODO FUTURO 
-------------------------------------------------------------------

		--DETERMINO IL NUMERO DI RAPPORTI DA CONSIDERARE
		SELECT @NUMOPERAZIONITOTALI= ISNULL(NrOperazioniTotali,0), @NUMOPERAZIONIANNO=sum(ISNULL(NumOperazioniAnno,0))
		--select ISNULL(NrOperazioniTotali,0), sum(ISNULL(NumOperazioniAnno,0))
		FROM GEM_Vista_T_TabStruttureOperazioniPrimarie op  inner join GEM_Vista_T_TabStruttureOperazioniPrimarieRighe  opr 
			on op.idStrutturaOpPr=opr.idStrutturaOpPr
		WHERE op.idtipologmezzo = @IDTIPOLOGMEZZO
--2-3-2011 BUG OPERAZIONI PRIMARIE
				and op.IDSTRUTTURAOPPR= @IDSTRUTTURAOPPR AND op.REVISIONE = @REVISIONE				
--2-3-2011 BUG OPERAZIONI PRIMARIE

		group by NrOperazioniTotali

		--calcolo Indice count down - operazionida fatturare
		IF @NUMOPERAZIONIDEROGA > 0  BEGIN
			SET @ATTIVITADAFATTURARE = @NUMOPERAZIONIDEROGA -1 
		END
		ELSE BEGIN
			SET @ATTIVITADAFATTURARE = @NUMOPERAZIONIANNO -1 
		END
		
		--CREAZIONE DEL CURSOR PER RAPPORTI DA FATT IN STATO ENNE
		DECLARE CURR_RIGHE_ENNE CURSOR  LOCAL  FAST_FORWARD FOR
		SELECT IDRAPPORTO
		FROM GEM_SEZIONECONTRATTORAPPORTI RP
		WHERE RP.IDCONTRATTO = @IDCONTRATTO AND RP.SEZIONECONTRATTO = @SEZIONECONTRATTO
			AND RP.DA_FATT = 'N' 
			and RP.IDRAPPORTO <> @IDRAPPORTO
			AND DATA_PREV >  @DATA_INTERVENTO --AND DATEADD(YY,+1,@DATA_INTERVENTO )
			AND STATO IN ('G','X','T')
		OPEN CURR_RIGHE_ENNE
		FETCH NEXT FROM CURR_RIGHE_ENNE INTO @IDRAPPORTO_STATO_ENNE
		WHILE @@FETCH_STATUS = 0
		BEGIN



--print ' @ATTIVITADAFATTURARE  ' + str(@ATTIVITADAFATTURARE)

			IF @ATTIVITADAFATTURARE > 0 BEGIN
				
 
				--CREAZIONE DEL CURSOR PER ATTIVITA NELL'ARRAY TEMPORANEO 
				DECLARE CURR_RIGHE_ARRAY CURSOR  LOCAL  FAST_FORWARD FOR
				SELECT IDATTIVITA, IDTIPOLOGMEZZO, IDRIGAMEZZO
				FROM [GEM_TMP_OPER_FATT_ANTICIP]
				WHERE IDSESSIONE = @idSESSIONE AND AttivitaAncoraDaFatturare > 0
				OPEN CURR_RIGHE_ARRAY
				FETCH NEXT FROM CURR_RIGHE_ARRAY INTO @IDATTIVITA, @IDTIPOLOGMEZZO, @IDRIGAMEZZO
				WHILE @@FETCH_STATUS = 0
				BEGIN



				DECLARE CURR_MEZZI CURSOR  LOCAL  FAST_FORWARD FOR
				SELECT SM.CODMEZZO, ISNULL(SM.QUANTITA,1),
					ISNULL(SM.IMPORTOAT1,0),	ISNULL(SM.IMPORTOAT2,0),	ISNULL(SM.IMPORTOAT3,0),	ISNULL(SM.IMPORTOAT4,0),	ISNULL(SM.IMPORTOAT5,0),	
					ISNULL(SM.SCONTOAT1,0),		ISNULL(SM.SCONTOAT2,0),		ISNULL(SM.SCONTOAT3,0),		ISNULL(SM.SCONTOAT4,0),		ISNULL(SM.SCONTOAT5,0),	
					ISNULL(SM.PROV1AT1,0),		ISNULL(SM.PROV1AT2,0),		ISNULL(SM.PROV1AT3,0),		ISNULL(SM.PROV1AT4,0),		ISNULL(SM.PROV1AT5,0), 
					ISNULL(SM.PROV2AT1,0),		ISNULL(SM.PROV2AT2,0),		ISNULL(SM.PROV2AT3,0),		ISNULL(SM.PROV2AT4,0),		ISNULL(SM.PROV2AT5,0)
				FROM 		dbo.GEM_SEZIONECONTRATTORAPPORTIMEZZI SM
				WHERE SM.IDCONTRATTO= @IDCONTRATTO 
					AND SM.SEZIONECONTRATTO= @SEZIONECONTRATTO 
					AND SM.IDRAPPORTO =  @IDRAPPORTO
					--AND AE.IDATTIVITA = 5
					AND SM.IDRIGAMEZZO = @IDRIGAMEZZO
					and dataeliminazione is null

					OPEN CURR_MEZZI
					FETCH NEXT FROM CURR_MEZZI INTO @CODICEARTICOLO, @QUANTITA,
						@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
						@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
						@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
						@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 
					WHILE @@FETCH_STATUS = 0
					BEGIN

						EXECUTE @RET_CODART = [GEM_GET_CODART] 
							@CODICEMEZZOCONTRATTO
							,@CODICEARTICOLO
							,@IDMODFATT
							,@IDATTIVITA
							,@CODARTICOLOFATT OUTPUT

print ' @RET_CODART  ' + @CODARTICOLOFATT

						IF ISNULL(@CODARTICOLOFATT,'') = '' BEGIN
								SET @MESSAGGIOERRORE = @RADICEMESS  + 'ERRORE- NON ESISTE REGOLA PER COSTRUZIONE DEL CODICE ARTICOLO FATT: ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] MOD. FATT=[' + LTRIM(STR(@IDMODFATT)) +'] - COD.MEZZO=[' + (@CODICEMEZZOCONTRATTO) + ']  tabella: GEM_Vista_T_DeterminaAttivita '
								PRINT '6'
								PRINT @MESSAGGIOERRORE
								EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
								PRINT @MESSAGGIOERRORE					
			--DA SCOMMENTARE
								--return 1					
						END
						--ELSE BEGIN
						--	print 'COD-ART: ' + @CODARTICOLOFATT
						--END

						--IMPOMSTO I VALORI DELLA RIGA ELEMENTI_FATTURAZIONE
						SELECT @POS_PREZZO = Posizione 
						FROM GEM_Vista_TipologMezziAttivita
						WHERE IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND IDATTIVITA = @IDATTIVITA
						IF @@ERROR <> 0 BEGIN
							SET @MESSAGGIOERRORE = @RADICEMESS + 'ERRORE: NON TROVATA RELAZIONE POSZIONI NELLA TABELLA [GEM_Vista_TipologMezziAttivita] PER ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] TIPOLOG MEZZO[' + LTRIM(STR(@IDTIPOLOGMEZZO)) +']'
							PRINT '7'
							PRINT @MESSAGGIOERRORE
							EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
			--DA SCOMMENTARE
							--return 1
						END 

						--IMPOSTAZIONE PREZZO 
						SET @IMPORTOINS = 
						CASE @POS_PREZZO  
							WHEN 1 THEN @IMPORTOAT1
							WHEN 2 THEN @IMPORTOAT2
							WHEN 3 THEN @IMPORTOAT3
							WHEN 4 THEN @IMPORTOAT4
							WHEN 5 THEN @IMPORTOAT5
						END

						--IMPOSTAZIONE SCONTO
						SET @SCONTOINS = 
						CASE @POS_PREZZO  
							WHEN 1 THEN @SCONTOAT1
							WHEN 2 THEN @SCONTOAT2
							WHEN 3 THEN @SCONTOAT3
							WHEN 4 THEN @SCONTOAT4
							WHEN 5 THEN @SCONTOAT5
						END

						--IMPOSTAZIONE PROVV1
						SET @PROV1INS = 
						CASE @POS_PREZZO  
							WHEN 1 THEN @PROV1AT1
							WHEN 2 THEN @PROV1AT2
							WHEN 3 THEN @PROV1AT3
							WHEN 4 THEN @PROV1AT4
							WHEN 5 THEN @PROV1AT5
						END

						--IMPOSTAZIONE PROVV2
						SET @PROV2INS = 
						CASE @POS_PREZZO  
							WHEN 1 THEN @PROV2AT1
							WHEN 2 THEN @PROV2AT2
							WHEN 3 THEN @PROV2AT3
							WHEN 4 THEN @PROV2AT4
							WHEN 5 THEN @PROV2AT5
						END


						--IMPOSTAZIONE TIPOFATTURAZIONE
						SELECT  @TIPOFATTURAZIONE = ISNULL(TIPOFATTURAZIONE,''),@VALIDITA=ISNULL(VALIDITA,'')
						FROM GEM_Vista_Controllo_Fatturazione VCF
						WHERE IDATTIVITA = @IDATTIVITA 
							AND IDTIPOLOGMEZZO=@IDTIPOLOGMEZZO
							AND IDTIPOFATT = @IDTIPOFATT
							AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO

						--inserimento riga che descrive il prossimo elenco
						IF @DESCINSERITA = 0 BEGIN

							EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
									,@SEZIONECONTRATTO 
									,@IDRAPPORTO 
									,@IDRAPPORTO
									,'D' 
									,0
									,0						--@idRigaMateriali
									,0						--@idRigaOreLav 
									,0						--@idRigaRata
									,''						--CODART
									,'Riepilogo Attività'	--DSCART	Rif vista GEM_VISTA_ELEMENTI_FATT
									,0						--@QTA 
									,0						--@PREZZO 
									,0						--@SCONTO 
									,0						--@PROVVIGIONE1 
									,0						--@PROVVIGIONE2 
									,0						--@PROVVIGIONE3 
									,''						--@TipoFatturazione 
									,''						--@Validita 
									,1000					--@Posizione
									,@IDSESSIONE			-- per i LOG


							SET @DESCINSERITA = 1

						END 


						--CONTROLLO SE QTA INFERIORE A ZERO
print '@QUANTITA'
print @QUANTITA
						IF @QUANTITA < 1 BEGIN
							SET @QUANTITA = 1
						END

						--inserimento attivit future
						EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
								,@SEZIONECONTRATTO 
								,@IDRAPPORTO 
								,@IDRAPPORTO_STATO_ENNE
								,'A' 
								,@IDRIGAATTIVITA		
								,0						--@idRigaMateriali
								,0						--@idRigaOreLav 
								,0						--@idRigaRata
								,@CODARTICOLOFATT		--CODART
								,@CODARTICOLOFATT					--DSCART
								,@QUANTITA				--@QTA 
								,@IMPORTOINS			--@PREZZO 
								,@SCONTOINS 			--@SCONTO 
								,@PROV1INS				--@PROVVIGIONE1 
								,@PROV2INS				--@PROVVIGIONE2 
								,0						--@PROVVIGIONE3 
								,@TIPOFATTURAZIONE		--@TipoFatturazione 
								,@VALIDITA				--@Validita 
								,1000					--@Posizione
								,@IDSESSIONE			-- per i LOG


						IF @@ERROR = 0 BEGIN
							SET @ELEMENTI_INSERITI = @ELEMENTI_INSERITI  + 1
						END 					
								
					FETCH NEXT FROM CURR_MEZZI INTO @CODICEARTICOLO, @QUANTITA,
						@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
						@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
						@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
						@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 
					END

					CLOSE CURR_MEZZI
					DEALLOCATE CURR_MEZZI



					UPDATE [GEM_TMP_OPER_FATT_ANTICIP]
					SET ATTIVITAANCORADAFATTURARE = ATTIVITAANCORADAFATTURARE -1
					WHERE IDSESSIONE = @IDSESSIONE 
						AND IDRAPPORTO = @IDRAPPORTO
						AND IDCONTRATTO= @IDCONTRATTO
						AND SEZIONECONTRATTO= @SEZIONECONTRATTO
						AND IDATTIVITA=	@IDATTIVITA
						AND IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO
						AND IDRIGAMEZZO = @IDRIGAMEZZO
						

					FETCH NEXT FROM CURR_RIGHE_ARRAY INTO @IDATTIVITA, @IDTIPOLOGMEZZO, @IDRIGAMEZZO

				END

				CLOSE CURR_RIGHE_ARRAY
				DEALLOCATE CURR_RIGHE_ARRAY

				SET @ATTIVITADAFATTURARE = @ATTIVITADAFATTURARE -1
			END 
			FETCH NEXT FROM CURR_RIGHE_ENNE INTO @IDRAPPORTO_STATO_ENNE

		END

		CLOSE CURR_RIGHE_ENNE
		DEALLOCATE CURR_RIGHE_ENNE

	end 

--------------------------------------------------------------------------------------------------------------------------------------
--SE DA FATTURARE = 'N0 DEVO VERIFCARE POSSIBILITA' DI CONGUAGLIO A CAUSA DELL'AUMENTO DEL NUMERO DI MEZZO NELLA SEZIONE CONTRATTO
-- POI DEVO FATTURARE IL RESTO 
--------------------------------------------------------------------------------------------------------------------------------------

	IF @DA_FATT = 'N' BEGIN

	DECLARE @NUMMEZZIATTUALI	AS INT
	DECLARE @NUMFATTURATI		AS INT
	DECLARE @CONTATORE			AS INT



		--numero Mezzi visitati
		select  @NUMMEZZIATTUALI = ISNULL(count(*),0) 
		FROM GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG AE 
--PC15102010
--segnalazione bug Annualità
				INNER JOIN GEM_Vista_Controllo_Fatturazione VCF ON  VCF.IDATTIVITA=AE.IDATTIVITA
					AND VCF.IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND VCF.IDTIPOFATT= @IDTIPOFATT 	AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO AND VCF.PERIODIACCUMULO  = 1
--PC15102010
--segnalazione bug Annualità
		WHERE AE.IDCONTRATTO=@IDCONTRATTO AND AE.SEZIONECONTRATTO=@SEZIONECONTRATTO AND AE.IDRAPPORTO = @IDRAPPORTO 


		--numero mezzi fatturati 
		select @RAPPORTO_RIF = ISNULL(IDRAPPORTO,'----'), @NUMFATTURATI = ISNULL(count(*),0) 
		FROM dbo.GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE
		WHERE IDRAPPORTO_RIF = @IDRAPPORTO AND TipologiaElemento = 'A' and IDRAPPORTO <> @IDRAPPORTO 
		GROUP BY IDRAPPORTO

		--SE IL NUMERO DEI MEZZI ATTUALI E' SUPERIORE A QUELLI FATTURATI A SUO TEMPO ... INSERISCO UN'ATTIVITA' DA FATT PER OGNI MEZZO IN PIU'
		IF @NUMMEZZIATTUALI > @NUMFATTURATI BEGIN

		----------------------------------------------------------------------------------------------------
		-- CONGUAGLIO ATTIVITA'
		----------------------------------------------------------------------------------------------------

			SET @CONTATORE = 0

			DECLARE CURR_MEZZI CURSOR  LOCAL  FAST_FORWARD FOR
			SELECT AE.IDRIGAMEZZO, AE.IDRIGA, SM.CODMEZZO, AE.IDATTIVITA, ISNULL(SM.QUANTITA,1),
				ISNULL(SM.IMPORTOAT1,0),	ISNULL(SM.IMPORTOAT2,0),	ISNULL(SM.IMPORTOAT3,0),	ISNULL(SM.IMPORTOAT4,0),	ISNULL(SM.IMPORTOAT5,0),	
				ISNULL(SM.SCONTOAT1,0),		ISNULL(SM.SCONTOAT2,0),		ISNULL(SM.SCONTOAT3,0),		ISNULL(SM.SCONTOAT4,0),		ISNULL(SM.SCONTOAT5,0),	
				ISNULL(SM.PROV1AT1,0),		ISNULL(SM.PROV1AT2,0),		ISNULL(SM.PROV1AT3,0),		ISNULL(SM.PROV1AT4,0),		ISNULL(SM.PROV1AT5,0), 
				ISNULL(SM.PROV2AT1,0),		ISNULL(SM.PROV2AT2,0),		ISNULL(SM.PROV2AT3,0),		ISNULL(SM.PROV2AT4,0),		ISNULL(SM.PROV2AT5,0)
			FROM GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG AE 
				INNER JOIN dbo.GEM_SEZIONECONTRATTORAPPORTIMEZZI SM
					on AE.IDCONTRATTO=SM.IDCONTRATTO AND AE.SEZIONECONTRATTO=SM.SEZIONECONTRATTO AND AE.IDRAPPORTO = SM.IDRAPPORTO AND AE.IDRIGAMEZZO = SM.IDRIGAMEZZO
				INNER JOIN GEM_Vista_Controllo_Fatturazione VCF ON  VCF.IDATTIVITA=AE.IDATTIVITA
					AND VCF.IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND VCF.IDTIPOFATT= @IDTIPOFATT 	AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO AND VCF.PERIODIACCUMULO  = 1
			WHERE AE.IDCONTRATTO=@IDCONTRATTO AND AE.SEZIONECONTRATTO=@SEZIONECONTRATTO AND AE.IDRAPPORTO = @IDRAPPORTO 
			AND ISNULL(DATAELIMINAZIONE,DATEADD(YY,+2,GETDATE() )) > GETDATE()
--PC 20-12-2010
--bug annualità
-- escludo dalla select i mezzi per le attivita già fatturate

			and not exists ( select 1 
					from dbo.GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG 
					where idrapporto =   @RAPPORTO_RIF and idattivita = AE.IDATTIVITA and idrigamezzo  =AE.IDRIGAMEZZO )
--
			ORDER BY AE.IDRIGAMEZZO 

			OPEN CURR_MEZZI
			FETCH NEXT FROM CURR_MEZZI INTO @IDRIGAMEZZO, @IDRIGAATTIVITA, @CODICEARTICOLO, @IDATTIVITA	, @QUANTITA,
				@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
				@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
				@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
				@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 

			WHILE @@FETCH_STATUS = 0
			BEGIN

				IF  ( @NUMMEZZIATTUALI - @NUMFATTURATI) > @CONTATORE  BEGIN

					
					EXECUTE @RET_CODART = [GEM_GET_CODART] 
						@CODICEMEZZOCONTRATTO
						,@CODICEARTICOLO
						,@IDMODFATT
						,@IDATTIVITA
						,@CODARTICOLOFATT OUTPUT

					IF ISNULL(@CODARTICOLOFATT,'') = '' BEGIN
							SET @MESSAGGIOERRORE = @RADICEMESS  + 'ERRORE- NON ESISTE REGOLA PER COSTRUZIONE DEL CODICE ARTICOLO FATT: ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] MOD. FATT=[' + LTRIM(STR(@IDMODFATT)) +'] - COD.MEZZO=[' + (@CODICEMEZZOCONTRATTO) + ']  tabella: GEM_Vista_T_DeterminaAttivita '
						PRINT '3'
						PRINT @MESSAGGIOERRORE
											EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
						--DA SCOMMENTARE
											--return 1					
					END
					--ELSE BEGIN
					--	print 'COD-ART: ' + @CODARTICOLOFATT
					--END

					--IMPOMSTO I VALORI DELLA RIGA ELEMENTI_FATTURAZIONE
					SELECT @POS_PREZZO = Posizione 
					FROM GEM_Vista_TipologMezziAttivita
					WHERE IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND IDATTIVITA = @IDATTIVITA
					IF @@ERROR <> 0 BEGIN
						SET @MESSAGGIOERRORE = @RADICEMESS + 'ERRORE: NON TROVATA RELAZIONE POSZIONI NELLA TABELLA [GEM_Vista_TipologMezziAttivita] PER ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] TIPOLOG MEZZO[' + LTRIM(STR(@IDTIPOLOGMEZZO)) +']'
						PRINT '4'
						PRINT @MESSAGGIOERRORE

						EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
		--DA SCOMMENTARE
						--return 1
					END 

					--IMPOSTAZIONE PREZZO 
					SET @IMPORTOINS = 
					CASE @POS_PREZZO  
						WHEN 1 THEN @IMPORTOAT1
						WHEN 2 THEN @IMPORTOAT2
						WHEN 3 THEN @IMPORTOAT3
						WHEN 4 THEN @IMPORTOAT4
						WHEN 5 THEN @IMPORTOAT5
					END

					--IMPOSTAZIONE SCONTO
					SET @SCONTOINS = 
					CASE @POS_PREZZO  
						WHEN 1 THEN @SCONTOAT1
						WHEN 2 THEN @SCONTOAT2
						WHEN 3 THEN @SCONTOAT3
						WHEN 4 THEN @SCONTOAT4
						WHEN 5 THEN @SCONTOAT5
					END

					--IMPOSTAZIONE PROVV1
					SET @PROV1INS = 
					CASE @POS_PREZZO  
						WHEN 1 THEN @PROV1AT1
						WHEN 2 THEN @PROV1AT2
						WHEN 3 THEN @PROV1AT3
						WHEN 4 THEN @PROV1AT4
						WHEN 5 THEN @PROV1AT5
					END

					--IMPOSTAZIONE PROVV2
					SET @PROV2INS = 
					CASE @POS_PREZZO  
						WHEN 1 THEN @PROV2AT1
						WHEN 2 THEN @PROV2AT2
						WHEN 3 THEN @PROV2AT3
						WHEN 4 THEN @PROV2AT4
						WHEN 5 THEN @PROV2AT5
					END


					--IMPOSTAZIONE TIPOFATTURAZIONE
					SELECT  @TIPOFATTURAZIONE = ISNULL(TIPOFATTURAZIONE,''),@VALIDITA=ISNULL(VALIDITA,'')
					FROM GEM_Vista_Controllo_Fatturazione VCF
					WHERE IDATTIVITA = @IDATTIVITA 
						AND IDTIPOLOGMEZZO=@IDTIPOLOGMEZZO
						AND IDTIPOFATT = @IDTIPOFATT
						AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO


					--inserimento riga che descrive il prossimo elenco
					IF @DESCINSERITA = 0 BEGIN


							EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
									,@SEZIONECONTRATTO 
									,@IDRAPPORTO 
									,@IDRAPPORTO
									,'D' 
									,0
									,0						--@idRigaMateriali
									,0						--@idRigaOreLav 
									,0						--@idRigaRata
									,''						--CODART
									,'Riepilogo Attività'	--DSCART	Rif vista GEM_VISTA_ELEMENTI_FATT
									,0						--@QTA 
									,0						--@PREZZO 
									,0						--@SCONTO 
									,0						--@PROVVIGIONE1 
									,0						--@PROVVIGIONE2 
									,0						--@PROVVIGIONE3 
									,''						--@TipoFatturazione 
									,''						--@Validita 
									,1000					--@Posizione
									,@IDSESSIONE			-- per i LOG


						SET @DESCINSERITA = 1

					END 


					--CONTROLLO SE QTA INFERIORE A ZERO
					IF @QUANTITA < 1 BEGIN
						SET @QUANTITA = 1
					END

					EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
							,@SEZIONECONTRATTO 
							,@IDRAPPORTO 
							,@IDRAPPORTO
							,'A' 
							,@IDRIGAATTIVITA		
							,0						--@idRigaMateriali
							,0						--@idRigaOreLav 
							,0						--@idRigaRata
							,@CODARTICOLOFATT		--CODART
							,@CODARTICOLOFATT						--DSCART
							,@QUANTITA				--@QTA 
							,@IMPORTOINS			--@PREZZO 
							,@SCONTOINS 			--@SCONTO 
							,@PROV1INS				--@PROVVIGIONE1 
							,@PROV2INS				--@PROVVIGIONE2 
							,0						--@PROVVIGIONE3 
							,@TIPOFATTURAZIONE		--@TipoFatturazione 
							,@VALIDITA				--@Validita 
							,1000					--@Posizione
							,@IDSESSIONE			-- per i LOG

						IF @@ERROR = 0 BEGIN
							SET @ELEMENTI_INSERITI = @ELEMENTI_INSERITI  + 1
						END 					

					SET @CONTATORE = @CONTATORE +1 
				END

				FETCH NEXT FROM CURR_MEZZI INTO @IDRIGAMEZZO, @IDRIGAATTIVITA, @CODICEARTICOLO,@IDATTIVITA, @QUANTITA,
					@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
					@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
					@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
					@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 
			END

			CLOSE CURR_MEZZI
			DEALLOCATE CURR_MEZZI

		
		END 

	END 


-------------------------------------------------------------------
--ATTIVITA' CONSUNTIVA
-- a prescindere dal flag DAFATT per le attivita a CONSUNTIVE RILASCIO ELEMENTI DA FATTURARE 
--PER LE ATTIVITA' ESEGUITE SU TUTTI I MEZZI ATTIVI 
-------------------------------------------------------------------

	DECLARE CURR_MEZZI CURSOR  LOCAL  FAST_FORWARD FOR
	SELECT AE.IDRIGAMEZZO, AE.IDRIGA, SM.CODMEZZO, AE.IDATTIVITA, ISNULL(SM.QUANTITA,1),
		ISNULL(SM.IMPORTOAT1,0),	ISNULL(SM.IMPORTOAT2,0),	ISNULL(SM.IMPORTOAT3,0),	ISNULL(SM.IMPORTOAT4,0),	ISNULL(SM.IMPORTOAT5,0),	
		ISNULL(SM.SCONTOAT1,0),		ISNULL(SM.SCONTOAT2,0),		ISNULL(SM.SCONTOAT3,0),		ISNULL(SM.SCONTOAT4,0),		ISNULL(SM.SCONTOAT5,0),	
		ISNULL(SM.PROV1AT1,0),		ISNULL(SM.PROV1AT2,0),		ISNULL(SM.PROV1AT3,0),		ISNULL(SM.PROV1AT4,0),		ISNULL(SM.PROV1AT5,0), 
		ISNULL(SM.PROV2AT1,0),		ISNULL(SM.PROV2AT2,0),		ISNULL(SM.PROV2AT3,0),		ISNULL(SM.PROV2AT4,0),		ISNULL(SM.PROV2AT5,0)
	FROM GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG AE 
		INNER JOIN dbo.GEM_SEZIONECONTRATTORAPPORTIMEZZI SM
			on AE.IDCONTRATTO=SM.IDCONTRATTO AND AE.SEZIONECONTRATTO=SM.SEZIONECONTRATTO AND AE.IDRAPPORTO = SM.IDRAPPORTO AND AE.IDRIGAMEZZO = SM.IDRIGAMEZZO
		INNER JOIN GEM_Vista_Controllo_Fatturazione VCF ON  VCF.IDATTIVITA=AE.IDATTIVITA
			AND VCF.IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND VCF.IDTIPOFATT= @IDTIPOFATT AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO AND  VCF.VISITACONSUNTIVA = 1
	WHERE AE.IDCONTRATTO=@IDCONTRATTO AND AE.SEZIONECONTRATTO=@SEZIONECONTRATTO AND AE.IDRAPPORTO = @IDRAPPORTO 
	AND ISNULL(DATAELIMINAZIONE,DATEADD(YY,+2,GETDATE() )) > GETDATE()
	ORDER BY AE.IDRIGAMEZZO

	OPEN CURR_MEZZI
	FETCH NEXT FROM CURR_MEZZI INTO @IDRIGAMEZZO, @IDRIGAATTIVITA, @CODICEARTICOLO, @IDATTIVITA	, @QUANTITA,
		@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
		@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
		@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
		@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 

	WHILE @@FETCH_STATUS = 0
	BEGIN

		
		EXECUTE @RET_CODART = [GEM_GET_CODART] 
			@CODICEMEZZOCONTRATTO
			,@CODICEARTICOLO
			,@IDMODFATT
			,@IDATTIVITA
			,@CODARTICOLOFATT OUTPUT

		IF ISNULL(@CODARTICOLOFATT,'') = '' BEGIN
				SET @MESSAGGIOERRORE = @RADICEMESS  + 'ERRORE- NON ESISTE REGOLA PER COSTRUZIONE DEL CODICE ARTICOLO FATT: ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] MOD. FATT=[' + LTRIM(STR(@IDMODFATT)) +'] - COD.MEZZO=[' + (@CODICEMEZZOCONTRATTO) + ']  tabella: GEM_Vista_T_DeterminaAttivita '
				PRINT '8'
				PRINT @MESSAGGIOERRORE
				EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
				PRINT @MESSAGGIOERRORE					
--DA SCOMMENTARE
				--return 1					
		END
		--ELSE BEGIN
		--	print 'COD-ART: ' + @CODARTICOLOFATT
		--END

		--IMPOMSTO I VALORI DELLA RIGA ELEMENTI_FATTURAZIONE
		SELECT @POS_PREZZO = Posizione 
		FROM GEM_Vista_TipologMezziAttivita
		WHERE IDTIPOLOGMEZZO = @IDTIPOLOGMEZZO AND IDATTIVITA = @IDATTIVITA
		IF @@ERROR <> 0 BEGIN
			SET @MESSAGGIOERRORE = @RADICEMESS + 'ERRORE: NON TROVATA RELAZIONE POSZIONI NELLA TABELLA [GEM_Vista_TipologMezziAttivita] PER ATTIVITA=[' + LTRIM(STR(@IDATTIVITA)) +'] TIPOLOG MEZZO[' + LTRIM(STR(@IDTIPOLOGMEZZO)) +']'
			PRINT '9'
			PRINT @MESSAGGIOERRORE
			EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
--DA SCOMMENTARE
			--return 1
		END 

		--IMPOSTAZIONE PREZZO 
		SET @IMPORTOINS = 
		CASE @POS_PREZZO  
			WHEN 1 THEN @IMPORTOAT1
			WHEN 2 THEN @IMPORTOAT2
			WHEN 3 THEN @IMPORTOAT3
			WHEN 4 THEN @IMPORTOAT4
			WHEN 5 THEN @IMPORTOAT5
		END

		--IMPOSTAZIONE SCONTO
		SET @SCONTOINS = 
		CASE @POS_PREZZO  
			WHEN 1 THEN @SCONTOAT1
			WHEN 2 THEN @SCONTOAT2
			WHEN 3 THEN @SCONTOAT3
			WHEN 4 THEN @SCONTOAT4
			WHEN 5 THEN @SCONTOAT5
		END

		--IMPOSTAZIONE PROVV1
		SET @PROV1INS = 
		CASE @POS_PREZZO  
			WHEN 1 THEN @PROV1AT1
			WHEN 2 THEN @PROV1AT2
			WHEN 3 THEN @PROV1AT3
			WHEN 4 THEN @PROV1AT4
			WHEN 5 THEN @PROV1AT5
		END

		--IMPOSTAZIONE PROVV2
		SET @PROV2INS = 
		CASE @POS_PREZZO  
			WHEN 1 THEN @PROV2AT1
			WHEN 2 THEN @PROV2AT2
			WHEN 3 THEN @PROV2AT3
			WHEN 4 THEN @PROV2AT4
			WHEN 5 THEN @PROV2AT5
		END


		--IMPOSTAZIONE TIPOFATTURAZIONE
		SELECT  @TIPOFATTURAZIONE = ISNULL(TIPOFATTURAZIONE,''),@VALIDITA=ISNULL(VALIDITA,'')
		FROM GEM_Vista_Controllo_Fatturazione VCF
		WHERE IDATTIVITA = @IDATTIVITA 
			AND IDTIPOLOGMEZZO=@IDTIPOLOGMEZZO
			AND IDTIPOFATT = @IDTIPOFATT
			AND VCF.TIPORAPPORTO= @TIPOLOGIARAPPORTO


		--inserimento riga che descrive il prossimo elenco
		IF @DESCINSERITA = 0 BEGIN


			EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
					,@SEZIONECONTRATTO 
					,@IDRAPPORTO 
					,@IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,'Riepilogo Attività'	--DSCART	Rif vista GEM_VISTA_ELEMENTI_FATT
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,1000					--@Posizione
					,@IDSESSIONE			-- per i LOG

			SET @DESCINSERITA = 1


		END 

		--CONTROLLO SE QTA INFERIORE A ZERO
print '@QUANTITA'
print @QUANTITA
		IF @QUANTITA < 1 BEGIN
			SET @QUANTITA = 1
		END

		EXEC GEM_PC_INS_ELEMENTIFATT_ANN @IDCONTRATTO 
				,@SEZIONECONTRATTO 
				,@IDRAPPORTO 
				,@IDRAPPORTO
				,'A' 
				,@IDRIGAATTIVITA		
				,0						--@idRigaMateriali
				,0						--@idRigaOreLav 
				,0						--@idRigaRata
				,@CODARTICOLOFATT		--CODART
				,@CODARTICOLOFATT					--DSCART
				,@QUANTITA				--@QTA 
				,@IMPORTOINS			--@PREZZO 
				,@SCONTOINS 			--@SCONTO 
				,@PROV1INS				--@PROVVIGIONE1 
				,@PROV2INS				--@PROVVIGIONE2 
				,0						--@PROVVIGIONE3 
				,@TIPOFATTURAZIONE		--@TipoFatturazione 
				,@VALIDITA				--@Validita 
				,1000					--@Posizione
				,@IDSESSIONE			-- per i LOG

			IF @@ERROR = 0 BEGIN
				SET @ELEMENTI_INSERITI = @ELEMENTI_INSERITI  + 1
			END 					
			
			UPDATE GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG
			SET STATO_FATTURAZIONE= 'S'
			WHERE IDCONTRATTO = @IDCONTRATTO
				AND SEZIONECONTRATTO= @SEZIONECONTRATTO
				AND IDRAPPORTO = @IDRAPPORTO
				AND IDRIGAMEZZO = @IDRIGAMEZZO
				AND IDATTIVITA=	@IDATTIVITA


		FETCH NEXT FROM CURR_MEZZI INTO @IDRIGAMEZZO, @IDRIGAATTIVITA, @CODICEARTICOLO,@IDATTIVITA, @QUANTITA,
			@IMPORTOAT1, @IMPORTOAT2, @IMPORTOAT3, @IMPORTOAT4, @IMPORTOAT5,
			@SCONTOAT1, @SCONTOAT2, @SCONTOAT3, @SCONTOAT4, @SCONTOAT5,
			@PROV1AT1,@PROV1AT2,@PROV1AT3,@PROV1AT4,@PROV1AT5, 
			@PROV2AT1,@PROV2AT2,@PROV2AT3,@PROV2AT4,@PROV2AT5 
	END

	CLOSE CURR_MEZZI
	DEALLOCATE CURR_MEZZI


	-----------------------------------------------------------------------------
	--GESTIONE MATERIALI
	-----------------------------------------------------------------------------

	DECLARE @RET_MATERIALI AS INT
	SET @RET_MATERIALI = 0
	EXECUTE @RET_MATERIALI = [GEM_RAPPORTI_FATTURAZIONE_MATERIALI] @IDRAPPORTO, @IDSESSIONE
    SET @MESSAGGIOERRORE=''
    -- CONTROLLO PROVVIGIONE SU MATERIALI pachetto 9.6 i
    DECLARE CURR_RAPFAT CURSOR  LOCAL  FAST_FORWARD FOR
	SELECT GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.idRigaMateriali, 
       ISNULL(GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.CodArticolo,'') AS CodArticolo, 
       ISNULL(GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.PROVVIGIONE1, 0) AS PROVVIGIONE1,
       ISNULL(GEM_TESTACONTRATTO.CodAgente1,'') AS CodAgente1, 
       ISNULL(ANAGRAFICAAGENTI.DSCAGENTE,'') AS DSCAGENTE
	FROM ANAGRAFICAAGENTI RIGHT OUTER JOIN
	  GEM_TESTACONTRATTO ON ANAGRAFICAAGENTI.CODAGENTE = GEM_TESTACONTRATTO.CodAgente1 RIGHT OUTER JOIN
	  GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE ON 
	  GEM_TESTACONTRATTO.IDCONTRATTO = GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.IDCONTRATTO
	WHERE IDRAPPORTO = @IDRAPPORTO AND TipologiaElemento='M' AND PROVVIGIONE1=0
	OPEN CURR_RAPFAT
	FETCH NEXT FROM CURR_RAPFAT INTO @idRigaMateriali, @CodArticolo, @PROVVIGIONE1, @CodAgente1, @DSCAGENTE
	WHILE @@FETCH_STATUS = 0
	BEGIN
      SET @MESSAGGIOERRORE = 'Attenzione per la riga ' + LTRIM(@idRigaMateriali) + ' di addebito materiale ' + RTRIM(@CodArticolo) + ' la provvigione dell'' agente ' + RTRIM(@CodAgente1) + '-' + RTRIM(@DSCAGENTE) + ' è a ZERO' 
      PRINT '12'
	  PRINT @MESSAGGIOERRORE
      EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
      FETCH NEXT FROM CURR_RAPFAT INTO @idRigaMateriali, @CodArticolo, @PROVVIGIONE1, @CodAgente1, @DSCAGENTE
	END

	CLOSE CURR_RAPFAT
	DEALLOCATE CURR_RAPFAT
    -- CONTROLLO PROVVIGIONE SU MATERIALI pachetto 9.6 f
    
	DECLARE @RET_ORE AS INT
	SET @RET_ORE = 0
	EXECUTE @RET_ORE = [GEM_RAPPORTI_FATTURAZIONE_ORE] @IDRAPPORTO, @IDSESSIONE
	
    -- CONTROLLO PROVVIGIONE SU Ore pachetto 9.6 i
    DECLARE CURR_RAPFATO CURSOR  LOCAL  FAST_FORWARD FOR
       SELECT GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.idRigaOreLav, 
          ISNULL(GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.CodArticolo,'') AS CodArticolo, 
          ISNULL(GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.PROVVIGIONE1, 0) AS PROVVIGIONE1,
          ISNULL(GEM_TESTACONTRATTO.CodAgente1,'') AS CodAgente1, 
          ISNULL(ANAGRAFICAAGENTI.DSCAGENTE,'') AS DSCAGENTE
       FROM ANAGRAFICAAGENTI RIGHT OUTER JOIN
	  GEM_TESTACONTRATTO ON ANAGRAFICAAGENTI.CODAGENTE = GEM_TESTACONTRATTO.CodAgente1 RIGHT OUTER JOIN
	  GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE ON 
	  GEM_TESTACONTRATTO.IDCONTRATTO = GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.IDCONTRATTO
       WHERE IDRAPPORTO = @IDRAPPORTO AND TipologiaElemento='O' AND PROVVIGIONE1=0
       OPEN CURR_RAPFATO
       FETCH NEXT FROM CURR_RAPFATO INTO @idRigaOreLav, @CodArticolo, @PROVVIGIONE1, @CodAgente1, @DSCAGENTE
       WHILE @@FETCH_STATUS = 0
       BEGIN
        SET @MESSAGGIOERRORE = 'Attenzione per la riga ' + LTRIM(@idRigaOreLav) + ' di addebito ore ' + RTRIM(@CodArticolo) + ' la provvigione dell'' agente ' + RTRIM(@CodAgente1) + '-' + RTRIM(@DSCAGENTE) + ' è a ZERO' 
        PRINT 'xx'
        PRINT @MESSAGGIOERRORE
        EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
        FETCH NEXT FROM CURR_RAPFATO INTO @idRigaOreLav, @CodArticolo, @PROVVIGIONE1, @CodAgente1, @DSCAGENTE
       END

	CLOSE CURR_RAPFATO
	DEALLOCATE CURR_RAPFATO
    -- CONTROLLO PROVVIGIONE SU ORE pachetto 9.6 f

	-----------------------------------------------------------------------------
	--MESSAGGIO FINALE 
	--MESSAGGIO FINALE TUTTO OK
	-----------------------------------------------------------------------------
	IF @ELEMENTI_INSERITI = 0 BEGIN
		SET @MESSAGGIOERRORE = @RADICEMESS + ' NESSUN ELEMENTO ATTIVITA INSERITO '
	END
	ELSE BEGIN
		SET @MESSAGGIOERRORE = @RADICEMESS + ' ELABORAZIONE OK - INSERITE [' + LTRIM(STR(@ELEMENTI_INSERITI)) +'] ATTIVITA '
	END
	IF @RET_MATERIALI > 0 BEGIN
		SET @MESSAGGIOERRORE = @MESSAGGIOERRORE + ' +  [' + LTRIM(STR(@RET_MATERIALI)) +'] RECORD MATERIALI '
	END
	IF @RET_ORE > 0 BEGIN
		SET @MESSAGGIOERRORE = @MESSAGGIOERRORE + ' +  [' + LTRIM(STR(@RET_ORE)) +'] RECORD ORE '
	END

	EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 

--DA SCOMMENTARE
	RETURN 0

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GEM_RAPPORTI_FATTURAZIONE] TO [Metodo98]
    AS [dbo];

