
CREATE PROCEDURE [dbo].[GEM_METSIC_TO_INT_SEZIONECONTRATTORAPPORTI_Materiali] (@IDRAPPORTO as varchar(14),@TIPOOPERAZIONE as char(1),@Progressivo as decimal(10,0),@Stato as varchar(1)) AS
BEGIN

	declare @IdAzienda varchar(3)

	select @IdAzienda = IdSocieta
	from GEM_TabParametriAziendaGemma
	
	-- UPDATE PER AZIENDA METODO SICURA
	IF @Stato = 'T'
	BEGIN
		
		UPDATE INS 
			SET INS.[IDCONTRATTO] = MET.[IDCONTRATTO]
			  ,INS.[SEZIONECONTRATTO] = MET.[SEZIONECONTRATTO]
			  ,INS.[IDMATERIALE] = MET.[IDMATERIALE]
			  ,INS.[PREZZO] = MET.[PREZZO]
			  ,INS.[SCONTO] = MET.[SCONTO]
			  ,INS.[QTA] = MET.[QTA]
			  ,INS.[PROVVIGIONE1] = MET.[PROVVIGIONE1]
			  ,INS.[PROVVIGIONE2] = MET.[PROVVIGIONE2]
			  ,INS.[PROVVIGIONE3] = MET.[PROVVIGIONE3]
			  ,INS.[flg_mat_dafatt] = MET.[flg_mat_dafatt]
			  ,INS.[NoMovimentaMagazzino] = MET.[NoMovimentaMagazzino]
			  ,INS.[UTENTEMODIFICA] = MET.[UTENTEMODIFICA]
			  ,INS.[DATAMODIFICA] = MET.[DATAMODIFICA]
			  ,INS.AZRIF = @IdAzienda
			FROM GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_Materiali INS
			INNER JOIN GEM_SEZIONECONTRATTORAPPORTI_Materiali MET ON
			INS.IDRAPPORTO = MET.IDRAPPORTO COLLATE Latin1_General_CI_AS 
			AND INS.IDRIGA = MET.IDRIGA AND INS.AZRIF = @IdAzienda
			WHERE INS.IDRAPPORTO = @IDRAPPORTO 
              AND INS.Progressivo = @Progressivo
	END
	ELSE
	BEGIN
		INSERT INTO GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_Materiali
		(
		[PROGRESSIVO]
		,[IDRIGA]
		,[IDRAPPORTO]
		,[IDCONTRATTO]
		,[SEZIONECONTRATTO]
		,[IDMATERIALE]
		,[PREZZO]
		,[SCONTO]
		,[QTA]
		,[PROVVIGIONE1]
		,[PROVVIGIONE2]
		,[PROVVIGIONE3]
		,[flg_mat_dafatt]
		,[NoMovimentaMagazzino]
		,[UTENTEMODIFICA]
		,[DATAMODIFICA]
		,[AZRIF]
		)
		SELECT
		@Progressivo
		,MET.[IDRIGA]
		,MET.[IDRAPPORTO]
		,MET.[IDCONTRATTO]
		,MET.[SEZIONECONTRATTO]
		,MET.[IDMATERIALE]
		,MET.[PREZZO]
		,MET.[SCONTO]
		,MET.[QTA]
		,MET.[PROVVIGIONE1]
		,MET.[PROVVIGIONE2]
		,MET.[PROVVIGIONE3]
		,MET.[flg_mat_dafatt]
		,MET.[NoMovimentaMagazzino]
		,MET.[UTENTEMODIFICA]
		,MET.[DATAMODIFICA]
		,@IdAzienda
		FROM
		GEM_SEZIONECONTRATTORAPPORTI_Materiali MET
		WHERE MET.IDRAPPORTO = @IDRAPPORTO
	END
		
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GEM_METSIC_TO_INT_SEZIONECONTRATTORAPPORTI_Materiali] TO [Metodo98]
    AS [dbo];

