CREATE PROCEDURE [dbo].[GEM_RAPPORTI_FATTURAZIONE_RATE] (@IDCONTRATTO AS VARCHAR(30), @NUMRATA AS INT,@IDRAPPORTO_RIF AS VARCHAR(4),@IDSESSIONE	AS INT)
AS
/*
DECLARE @IDCONTRATTO		AS VARCHAR(30)
DECLARE @NUMRATA			AS INT
DECLARE @IDSESSIONE			AS INT


SET @IDCONTRATTO		= 'S-09-00001490'  -- idranti
SET @NUMRATA			= 1
SET @IDSESSIONE			= 3131
*/


DECLARE @STRNUMRATA			AS VARCHAR(4)
DECLARE @IMPORTORATA		AS DECIMAL(12,4)
DECLARE @SCONTO				AS DECIMAL(10,2)
DECLARE @PROVVIGIONE1		AS DECIMAL(10,2)
DECLARE @PROVVIGIONE2		AS DECIMAL(10,2)
DECLARE @IDMODFATT			AS INT
DECLARE @CODICEARTICOLO		AS VARCHAR(50)
DECLARE @REFERENTE			AS VARCHAR(80)
DECLARE @TIPOFATT			AS VARCHAR(80)
DECLARE @DESCRIZIONERATA	AS VARCHAR(80)
DECLARE @DESCRIZIONE    	AS VARCHAR(500)
DECLARE @DESC               AS VARCHAR(255)
DECLARE @idRigaRata             AS decimal(5, 0)
DECLARE @CodArticolo     	    AS VARCHAR(50)
DECLARE @CodAgente1             AS varchar(7) 
DECLARE @DSCAGENTE              AS varchar(80)

--DECLARE @DESCRATA			AS VARCHAR(80)
DECLARE @DESCRATA			AS VARCHAR(255)
DECLARE @DATACONTRATTO		AS DATETIME
DECLARE @STRMaxNUMRATA		AS VARCHAR(4)
DECLARE @STPDATE   		    AS INT
DECLARE @idLOCompRata       AS INT
DECLARE @IDRAPPORTO         AS VARCHAR(14)
DECLARE @DATA_EFF           AS VARCHAR(10)
DECLARE @DATA_ORD           AS DATETIME
DECLARE @DATA_EFF_OLD       AS VARCHAR(10)
DECLARE @CODDEST            AS INT   
DECLARE @CODDEST_OLD        AS INT   
DECLARE @DESCRART           AS VARCHAR(80)
DECLARE @RAGSOC             AS VARCHAR(80)
DECLARE @SEDLOC             AS VARCHAR(80)
DECLARE @SEDPROV            AS VARCHAR(80)
DECLARE @NR_SEDI            AS INT   

--COSTRUZIONE NUMERO RATA STRING
SET @STRNUMRATA	= right('0000' + ltrim(rtrim(str(@NUMRATA))),4)

print @STRNUMRATA
print '@IDRAPPORTO_RIF'
print @IDRAPPORTO_RIF

--IMPOSTAZIONE MESSAGGIO DI ERRORE
DECLARE  @ELEMENTI_INSERITI	AS INT
DECLARE  @MESSAGGIOERRORE		AS VARCHAR(255)
DECLARE  @RADICEMESS		AS VARCHAR(255)


DECLARE @DSCCONTO1			AS VARCHAR(80)
DECLARE @INDIRIZZO			AS VARCHAR(80)
DECLARE @LOCALITA			AS VARCHAR(80)
DECLARE @PROVINCIA			AS VARCHAR(4)
DECLARE @CAP				AS VARCHAR(8)
DECLARE @INTESTA			AS INT
DECLARE @INTESTA_SEDE   	AS INT
DECLARE @DATAINIZCOMPRATA   AS VARCHAR(10)
DECLARE @DATAFINECOMPRATA   AS VARCHAR(10)
DECLARE @MEZZI_ATT          AS VARCHAR(5)
DECLARE @idtipologmezzo     AS INT
DECLARE @CodiceMezzo        AS VARCHAR(50)
--INIZIALIZZAZIONE MESSAGGI E NUM RECORD INSERITI
SET @RADICEMESS = 'ELAB RATA PER CONTRATTO: [' +  @IDCONTRATTO + '] - NUM RATA: [' + @STRNUMRATA + ']'
SET @ELEMENTI_INSERITI = 0


--CANCELLAZIONE RECORD PRECEDENTI NEL LOG DEI MESSAGGI
DELETE [GEM_TMP_OPER_FATT_ANTICIP]
WHERE IDSESSIONE = @IDSESSIONE

--CANCELLAZIONE RECORD PRECEDENTI IN ELEMENTI DA FATTURARE
DELETE GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE
WHERE  IDCONTRATTO = @IDCONTRATTO AND IDRAPPORTO =  @STRNUMRATA

--inserimento record di elaborazione per guidare selezione della visione successiva all'elaborazione
EXECUTE [dbo].[GEM_InsLogRapportoRataEab]  @IDSESSIONE ,'' ,@IDCONTRATTO , @NUMRATA

--SELEZIONE ELEMENTI DELLA RATA
SELECT @IDMODFATT = C.IDMODFATT, 
		@IMPORTORATA = R.IMPRATASFS, 
		@SCONTO = R.SCONTO, 
		@PROVVIGIONE1 = R.PROVVIGIONE1,
		@PROVVIGIONE2 = R.PROVVIGIONE2,
		@REFERENTE = C.REFERENTE, 
		@TIPOFATT = MF.Descrizione,
		@DATACONTRATTO = DATAEFFICACIA,
		@DSCCONTO1 = DSCCONTO1, 
		@INDIRIZZO = INDIRIZZO, 
		@LOCALITA = LOCALITA, 
		@PROVINCIA =PROVINCIA, 
		@CAP = CAP,
		@DESCRIZIONERATA = RTRIM(LTRIM(DESCRIZIONERATA)),
		@DATAINIZCOMPRATA = convert(varchar(10),R.DATAINIZCOMPRATA  ,103),
		@DATAFINECOMPRATA = convert(varchar(10),R.DATAFINECOMPRATA  ,103)
from dbo.GEM_SEZIONECONTRATTO_RATE R INNER JOIN GEM_TESTACONTRATTO C ON R.IDCONTRATTO = C.IDCONTRATTO
	inner join GEM_Vista_TipologieFatturazione MF on C.idTipoFatt = MF.idTipoFatt
	inner join anagraficacf a on C.codcliente = a.codconto
where R.IDCONTRATTO= @IDCONTRATTO
and R.NUMERORATA = @NUMRATA

SELECT @STRMaxNUMRATA=MAX(NUMERORATA) FROM GEM_TMP_SEZIONECONTRATTO_RATE WHERE IDCONTRATTO=@IDCONTRATTO AND RAGR=@IDRAPPORTO_RIF AND idSESSIONE=@IDSESSIONE
SET @STRMaxNUMRATA	= right('0000' + ltrim(rtrim(str(@STRMaxNUMRATA))),4)
PRINT '@STRMaxNUMRATA'
PRINT @STRMaxNUMRATA

IF @IDRAPPORTO_RIF=@NUMRATA
  SET @INTESTA=1
ELSE
  SET @INTESTA=0;

print '@INTESTA'
print @INTESTA

--SELEZIONE CODICE ARTICOLO
SET @CODICEARTICOLO = ''
SELECT @CODICEARTICOLO=CODICEFATTURAZIONE
FROM dbo.GEM_ContrPFatturazione
WHERE IDMODFATT = @IDMODFATT 
IF @CODICEARTICOLO = '' BEGIN
			SET @MESSAGGIOERRORE = @RADICEMESS  + ' - ERRORE- NON ESISTE REGOLA PER COSTRUZIONE DEL CODICE ARTICOLO FATT: MOD. FATT=[' + LTRIM(STR(@IDMODFATT)) + ']  tabella: GEM_ContrPFatturazione '
			EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
END
ELSE 
BEGIN

		IF @ELEMENTI_INSERITI = 0 
		BEGIN
			IF @INTESTA=1
			BEGIN
				--INSERISCO LE DESCRIZIONI
				SET @DESCRATA = 'Canone Manutenzione Contratto Rateale Nr. ' + @IDCONTRATTO + ' del ' + LTRIM(STR(DAY(@DATACONTRATTO))) + '-' + LTRIM(STR(MONTH(@DATACONTRATTO)))+'-' +LTRIM(STR(YEAR(@DATACONTRATTO)))

				--RIGA DI DESCRIZIONE CONTRATTO
				EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO 
					,0						--SEZIONECONTRATTO 
					,@STRNUMRATA			--IDRAPPORTO 
					,@IDRAPPORTO_RIF			--IDRAPPORTO
					,'D' 
					,0
					,0						--@idRigaMateriali
					,0						--@idRigaOreLav 
					,0						--@idRigaRata
					,''						--CODART
					,@DESCRATA				--DSCART
					,0						--@QTA 
					,0						--@PREZZO 
					,0						--@SCONTO 
					,0						--@PROVVIGIONE1 
					,0						--@PROVVIGIONE2 
					,0						--@PROVVIGIONE3 
					,''						--@TipoFatturazione 
					,''						--@Validita 
					,10						--@Posizione
					,@IDSESSIONE			-- per i LOG


					--SET @DESCRATA = left('Presso : ' + @DSCCONTO1,80)
					SET @DESCRATA = left('Presso : ' + @DSCCONTO1,255)

					--RIGA DI DESCRIZIONE CONTRATTO
					EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO 
						,0						--SEZIONECONTRATTO 
						,@STRNUMRATA			--IDRAPPORTO 
						,@IDRAPPORTO_RIF			--IDRAPPORTO
						,'D' 
						,0
						,0						--@idRigaMateriali
						,0						--@idRigaOreLav 
						,0						--@idRigaRata
						,''						--CODART
						,@DESCRATA				--DSCART
						,0						--@QTA 
						,0						--@PREZZO 
						,0						--@SCONTO 
						,0						--@PROVVIGIONE1 
						,0						--@PROVVIGIONE2 
						,0						--@PROVVIGIONE3 
						,''						--@TipoFatturazione 
						,''						--@Validita 
						,20						--@Posizione
						,@IDSESSIONE			-- per i LOG
			END


			--INSERISCO LE DESCRIZIONI
			SET @DESCRATA = 'Riferimento Rata Nr. ' + rtrim(LTRIM(STR(@NUMRATA))) 

			--RIGA DI DESCRIZIONE CONTRATTO
			EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO 
				,0						--SEZIONECONTRATTO 
				,@STRNUMRATA			--IDRAPPORTO 
				,@IDRAPPORTO_RIF			--IDRAPPORTO
				,'D' 
				,0
				,0						--@idRigaMateriali
				,0						--@idRigaOreLav 
				,0						--@idRigaRata
				,''						--CODART
				,@DESCRATA				--DSCART
				,0						--@QTA 
				,0						--@PREZZO 
				,0						--@SCONTO 
				,0						--@PROVVIGIONE1 
				,0						--@PROVVIGIONE2 
				,0						--@PROVVIGIONE3 
				,''						--@TipoFatturazione 
				,''						--@Validita 
				,30						--@Posizione
				,@IDSESSIONE			-- per i LOG


				IF @DESCRIZIONERATA <> '' BEGIN

					--RIGA DI DESCRIZIONE CONTRATTO
					EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO 
						,0						--SEZIONECONTRATTO 
						,@STRNUMRATA			--IDRAPPORTO 
						,@IDRAPPORTO_RIF			--IDRAPPORTO
						,'D' 
						,0
						,0						--@idRigaMateriali
						,0						--@idRigaOreLav 
						,0						--@idRigaRata
						,''						--CODART
						,@DESCRIZIONERATA		--DSCART
						,0						--@QTA 
						,0						--@PREZZO 
						,0						--@SCONTO 
						,0						--@PROVVIGIONE1 
						,0						--@PROVVIGIONE2 
						,0						--@PROVVIGIONE3 
						,''						--@TipoFatturazione 
						,''						--@Validita 
						,40						--@Posizione
						,@IDSESSIONE			-- per i LOG

				END

		END 



		-- INSERIMENTO 
		EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO 
				,0						--SEZIONECONTRATTO 
				,@STRNUMRATA			--IDRAPPORTO 
				,@IDRAPPORTO_RIF			--IDRAPPORTO
				,'R' 
				,0						--IDRIGAATTIVITA		
				,0						--@idRigaMateriali
				,0						--@idRigaOreLav 
				,@NUMRATA				--@idRigaRata
				,@CODICEARTICOLO 		--CODART
				,@CODICEARTICOLO 		--DSCART
				,1						--@QTA 
				,@IMPORTORATA			--@PREZZO 
				,@SCONTO 				--@SCONTO 
				,@PROVVIGIONE1			--@PROVVIGIONE1 
				,@PROVVIGIONE2			--@PROVVIGIONE2 
				,0						--@PROVVIGIONE3 
				,'Rateale'				--@TipoFatturazione 
				,'Da Contratto'			--@Validita 
				,50  					--@Posizione
				,@IDSESSIONE			-- per i LOG

 -- 79 5.1.4.1
            IF @STRNUMRATA=@STRMaxNUMRATA
			BEGIN
print @STRMaxNUMRATA
				SELECT @STPDATE=flgStpCompRate FROM GEM_TESTACONTRATTO WHERE IDCONTRATTO=@IDCONTRATTO
				IF @STPDATE=1
				BEGIN
					IF ISNULL(@DATAINIZCOMPRATA,'')<>'' AND ISNULL(@DATAFINECOMPRATA,'')<>''
					BEGIN
						SET @DESCRIZIONE='Periodo competenza rata: da ' + @DATAINIZCOMPRATA + ' a ' + @DATAFINECOMPRATA
print @DESCRIZIONE
						EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
						    ,@DESCRIZIONE,0
							,0,0,0,0,0,'','',60,@IDSESSIONE	
					END
				END

 -- 79 5.1.4.2
				SELECT @idLOCompRata=idLOCompRata FROM GEM_TESTACONTRATTO WHERE IDCONTRATTO= @IDCONTRATTO
				--SE =1 NON FA NIENTE
				IF @idLOCompRata=2
				BEGIN
PRINT 'ENTRATO 2'
					DECLARE CURR_RIGHE CURSOR  LOCAL  FAST_FORWARD FOR
					SELECT  DISTINCT CR.IDRAPPORTO,CR.DATA_EFF,convert(varchar(10),CR.DATA_EFF  ,103),AA.DESCRIZIONE,SedeRagSoc,SedeLocalita,SedeProvincia
					FROM GEM_SEZIONECONTRATTORAPPORTI CR
						INNER JOIN GEM_SEZIONICONTRATTO SC ON CR.IDCONTRATTO=SC.IDCONTRATTO AND CR.SEZIONECONTRATTO=SC.SEZIONECONTRATTO
						INNER JOIN GEM_VistaContratti VC ON CR.IDCONTRATTO=VC.IDCONTRATTO AND CR.SEZIONECONTRATTO=VC.SEZIONECONTRATTO
						INNER JOIN ANAGRAFICAARTICOLI AA ON AA.CODICE=SC.CodiceMezzo
						INNER JOIN GEM_SEZIONECONTRATTO_RATE SCR ON CR.IDCONTRATTO=SCR.IDCONTRATTO
						INNER JOIN GEM_TMP_SEZIONECONTRATTO_RATE TSC ON SCR.IDCONTRATTO=TSC.IDCONTRATTO AND SCR.NUMERORATA=TSC.NUMERORATA AND TSC.RAGR=@IDRAPPORTO_RIF AND TSC.idSESSIONE=@IDSESSIONE AND CR.DATA_EFF>=SCR.DataInizCompRata AND CR.DATA_EFF<=SCR.DataFineCompRata
					WHERE CR.IDCONTRATTO= @IDCONTRATTO AND CR.TIPOLOGIARAPPORTO='O' AND CR.STATO IN ('E','D','V','F')
					order by CR.DATA_EFF,SedeRagSoc,AA.DESCRIZIONE
					OPEN CURR_RIGHE
					FETCH NEXT FROM CURR_RIGHE 
					INTO @IDRAPPORTO,@DATA_ORD,@DATA_EFF,@DESCRART,@RAGSOC,@SEDLOC,@SEDPROV
					WHILE @@FETCH_STATUS = 0
					BEGIN
						SET @DESCRIZIONE='Rapportino nr: ' + @IDRAPPORTO + ' del ' + @DATA_EFF + ' per ' + @DESCRART + ' Presso: ' +  @RAGSOC + ' - ' + @SEDLOC + ' - ' + @SEDPROV
						IF LEN(@DESCRIZIONE)>80
						BEGIN
							SELECT @DESC=LEFT(@DESCRIZIONE,80)
							EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''						
								,@DESC,0,0,0,0,0,0,'','',60,@IDSESSIONE	
							IF len(@DESCRIZIONE)-80<=80
							BEGIN
								SELECT @DESC=substring(@DESCRIZIONE,81,len(@DESCRIZIONE)-80)
								EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
									,@DESC,0,0,0,0,0,0,'','',60,@IDSESSIONE
							END	
							ELSE
							BEGIN
							--	SELECT @DESC=substring(@DESCRIZIONE,81,len(@DESCRIZIONE)-80)
							--	EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
							--		,@DESC,0,0,0,0,0,0,'','',60,@IDSESSIONE
							--	SELECT @DESC=substring(@DESCRIZIONE,161,len(@DESCRIZIONE)-160)
							--	EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
							--		,@DESC,0,0,0,0,0,0,'','',60,@IDSESSIONE
								SELECT @DESC=substring(@DESCRIZIONE,81,80)
								EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
									,@DESC,0,0,0,0,0,0,'','',60,@IDSESSIONE
								SELECT @DESC=substring(@DESCRIZIONE,161,len(@DESCRIZIONE)-160)
								EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
									,@DESC,0,0,0,0,0,0,'','',60,@IDSESSIONE
							END
						END
						ELSE
						BEGIN
							EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''					
								,@DESCRIZIONE,0,0,0,0,0,0,'','',60,@IDSESSIONE		
						END
						FETCH NEXT FROM CURR_RIGHE INTO @IDRAPPORTO,@DATA_ORD,@DATA_EFF,@DESCRART,@RAGSOC,@SEDLOC,@SEDPROV
					END
					CLOSE CURR_RIGHE
					DEALLOCATE CURR_RIGHE
				END
				ELSE
				BEGIN
					IF @idLOCompRata=3
					BEGIN
                        SET @INTESTA=0
						SET @CODDEST_OLD=0
						SET @DATA_EFF_OLD=''
						SET @NR_SEDI=0
						DECLARE CURR_RIGHE CURSOR  LOCAL  FAST_FORWARD FOR
						SELECT Distinct VC.CODDEST,SedeRagSoc,SedeLocalita,SedeProvincia
						FROM GEM_SEZIONECONTRATTORAPPORTI CR
							INNER JOIN GEM_SEZIONICONTRATTO SC ON CR.IDCONTRATTO=SC.IDCONTRATTO AND CR.SEZIONECONTRATTO=SC.SEZIONECONTRATTO
							INNER JOIN GEM_VistaContratti VC ON CR.IDCONTRATTO=VC.IDCONTRATTO AND CR.SEZIONECONTRATTO=VC.SEZIONECONTRATTO
							INNER JOIN GEM_SEZIONECONTRATTO_RATE SCR ON CR.IDCONTRATTO=SCR.IDCONTRATTO
							INNER JOIN GEM_TMP_SEZIONECONTRATTO_RATE TSC ON SCR.IDCONTRATTO=TSC.IDCONTRATTO AND SCR.NUMERORATA=TSC.NUMERORATA AND TSC.RAGR=@IDRAPPORTO_RIF AND TSC.idSESSIONE=@IDSESSIONE AND CR.DATA_EFF>=SCR.DataInizCompRata AND CR.DATA_EFF<=SCR.DataFineCompRata
						WHERE CR.IDCONTRATTO= @IDCONTRATTO AND CR.TIPOLOGIARAPPORTO='O' AND CR.STATO IN ('E','D','V','F')
						GROUP BY VC.CODDEST,CR.DATA_EFF,SedeRagSoc,SedeLocalita,SedeProvincia
						OPEN CURR_RIGHE
						FETCH NEXT FROM CURR_RIGHE 
						INTO @CODDEST,@RAGSOC,@SEDLOC,@SEDPROV
						WHILE @@FETCH_STATUS = 0
						BEGIN
PRINT @CODDEST
							IF @INTESTA=0 
							BEGIN
								SET @DESCRIZIONE='Rapportini di riferimento e mezzi di riferimento'
	print @DESCRIZIONE						
								EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''						
									,@DESCRIZIONE,0,0,0,0,0,0,'','',70,@IDSESSIONE			
							END
							SET @INTESTA=1
							SET @INTESTA_SEDE=0
							DECLARE CURR_RAPP CURSOR  LOCAL  FAST_FORWARD FOR
							SELECT  DISTINCT CR.IDRAPPORTO,convert(varchar(10),CR.DATA_EFF  ,103),AA.DESCRIZIONE,isnull((SELECT cast(SUM(CASE WHEN ISNULL(Eliminato,0)=0 THEN ISNULL(Quantita,0) ELSE 0 END) AS VARCHAR(5)) Attivi FROM GEM_SEZIONECONTRATTORAPPORTIMEZZI WHERE IDRapporto=CR.IDRAPPORTO AND ISNULL(CodMezzo,'')<>''),0) AS MEZZI_ATT
							FROM GEM_SEZIONECONTRATTORAPPORTI CR
								INNER JOIN GEM_SEZIONICONTRATTO SC ON CR.IDCONTRATTO=SC.IDCONTRATTO AND CR.SEZIONECONTRATTO=SC.SEZIONECONTRATTO
								INNER JOIN GEM_VistaContratti VC ON CR.IDCONTRATTO=VC.IDCONTRATTO AND CR.SEZIONECONTRATTO=VC.SEZIONECONTRATTO
								INNER JOIN ANAGRAFICAARTICOLI AA ON AA.CODICE=SC.CodiceMezzo
								INNER JOIN GEM_SEZIONECONTRATTO_RATE SCR ON CR.IDCONTRATTO=SCR.IDCONTRATTO
								INNER JOIN GEM_TMP_SEZIONECONTRATTO_RATE TSC ON SCR.IDCONTRATTO=TSC.IDCONTRATTO AND SCR.NUMERORATA=TSC.NUMERORATA AND TSC.RAGR=@IDRAPPORTO_RIF AND TSC.idSESSIONE=@IDSESSIONE AND CR.DATA_EFF>=SCR.DataInizCompRata AND CR.DATA_EFF<=SCR.DataFineCompRata
							WHERE CR.IDCONTRATTO= @IDCONTRATTO AND CR.TIPOLOGIARAPPORTO='O' AND CR.STATO IN ('E','D','V','F') AND VC.CODDEST=@CODDEST order by convert(varchar(10),CR.DATA_EFF  ,103)
							OPEN CURR_RAPP
							FETCH NEXT FROM CURR_RAPP 
							INTO @IDRAPPORTO,@DATA_EFF,@DESCRART,@MEZZI_ATT
							WHILE @@FETCH_STATUS = 0
							BEGIN
								IF @INTESTA_SEDE=0 
								BEGIN
									IF @NR_SEDI>0
									BEGIN
										SET @DESCRIZIONE='.' 
										EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''					
											,@DESCRIZIONE,0,0,0,0,0,0,'','',80,@IDSESSIONE	
									END
									SET @DESCRIZIONE='Presso: ' +  @RAGSOC + ' - ' + @SEDLOC + ' - ' + @SEDPROV
									EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''					
										,@DESCRIZIONE,0,0,0,0,0,0,'','',80,@IDSESSIONE	
								END
								set @INTESTA_SEDE=1
								SET @DESCRIZIONE='Rapportino nr: ' + @IDRAPPORTO + ' del ' + @DATA_EFF + ' per ' + @DESCRART + ' - Mezzi/impianti attivi nella visita:  ' +  @MEZZI_ATT
	print @DESCRIZIONE						
								IF LEN(@DESCRIZIONE)>80
								BEGIN
									SELECT @DESC=LEFT(@DESCRIZIONE,80)
									EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
										,@DESC,0,0,0,0,0,0,'','',80,@IDSESSIONE			
									IF len(@DESCRIZIONE)-80<=80
									BEGIN
										SELECT @DESC=substring(@DESCRIZIONE,81,len(@DESCRIZIONE)-80)
										EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
											,@DESC,0,0,0,0,0,0,'','',80,@IDSESSIONE
									END	
									ELSE
									BEGIN
										SELECT @DESC=substring(@DESCRIZIONE,81,len(@DESCRIZIONE)-80)
										EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
											,@DESC,0,0,0,0,0,0,'','',80,@IDSESSIONE
										SELECT @DESC=substring(@DESCRIZIONE,161,len(@DESCRIZIONE)-160)
										EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
											,@DESC,0,0,0,0,0,0,'','',80,@IDSESSIONE
									END
								END
								ELSE
								BEGIN
									EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''
										,@DESCRIZIONE,0,0,0,0,0,0,'','',80,@IDSESSIONE	
								END
								SET @NR_SEDI=@NR_SEDI + 1
								FETCH NEXT FROM CURR_RAPP INTO @IDRAPPORTO,@DATA_EFF,@DESCRART,@MEZZI_ATT
							END
							CLOSE CURR_RAPP
						    DEALLOCATE CURR_RAPP					    
							FETCH NEXT FROM CURR_RIGHE INTO @CODDEST,@RAGSOC,@SEDLOC,@SEDPROV
						END
						CLOSE CURR_RIGHE
						DEALLOCATE CURR_RIGHE					    
					END
					ELSE
					BEGIN
						IF @idLOCompRata=4
						BEGIN
							SET @INTESTA=0
							DECLARE CURR_RIGHE CURSOR  LOCAL  FAST_FORWARD FOR
							SELECT Sc.idtipologmezzo,sc.CodiceMezzo,MA.DescrizioneMezzo,cast(sum(cTM.MezziAttivi) as varchar(5)) 
							FROM GEM_SEZIONICONTRATTO SC 
							   INNER JOIN (select IDCONTRATTO,SEZIONECONTRATTO,eliminato,Count(eliminato) as MezziAttivi from GEM_SEZIONICONTRATTODETTMEZZI group by IDCONTRATTO,SEZIONECONTRATTO,eliminato) CTM ON SC.IDCONTRATTO=CTM.IDCONTRATTO AND SC.SEZIONECONTRATTO=CTM.SEZIONECONTRATTO AND Eliminato=0
							   INNER JOIN GEMMADBG..GEM_VistaCodiciMezziAssegnati MA on MA.CodiceMezzo=SC.CodiceMezzo collate SQL_Latin1_General_CP1_CI_AS
							WHERE SC.IDCONTRATTO=@IDCONTRATTO 
							GROUP BY Sc.idtipologmezzo,sc.CodiceMezzo,MA.DescrizioneMezzo
							OPEN CURR_RIGHE
							FETCH NEXT FROM CURR_RIGHE 
							INTO @idtipologmezzo,@CodiceMezzo,@DESCRART,@MEZZI_ATT
							WHILE @@FETCH_STATUS = 0
							BEGIN
								IF @INTESTA=0 
								BEGIN
									SET @DESCRIZIONE='Riepilogo Mezzi/Impianti attivi nel contratto alla data del presente documento.'
		print @DESCRIZIONE						
									EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''						
										,@DESCRIZIONE,0,0,0,0,0,0,'','',70,@IDSESSIONE			
								END
								SET @INTESTA=1
								SELECT @DESC=ISNULL(DESCTIPOQUANTITA,'') FROM GEM_Vista_CodiciMezziAssegnati WHERE idTipologMezzo=@idtipologmezzo AND CodiceMezzo=@CodiceMezzo
								SET @DESCRIZIONE=@DESCRART + ': ' + @MEZZI_ATT + ' ' + @DESC
								EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''						
										,@DESCRIZIONE,0,0,0,0,0,0,'','',80,@IDSESSIONE
								FETCH NEXT FROM CURR_RIGHE INTO @idtipologmezzo,@CodiceMezzo,@DESCRART,@MEZZI_ATT
							END
							CLOSE CURR_RIGHE
							DEALLOCATE CURR_RIGHE
							SELECT  @DESC=cast(isnull(NrSediInManuntezione,0) as varchar(5)) FROM GEM_VISTA_VALORICONTRATTIGEMMA WHERE IDCONTRATTO= @IDCONTRATTO	
							SET @DESCRIZIONE='Nr. Sedi Attive nel presente contratto: ' + @DESC
							EXEC GEM_PC_INS_ELEMENTIFATT @IDCONTRATTO,0,@STRNUMRATA,@IDRAPPORTO_RIF,'F',0,0,0,0,''						
										,@DESCRIZIONE,0,0,0,0,0,0,'','',90,@IDSESSIONE							 			    
					    END
					END
				END
			END



			IF @@ERROR = 0 
			BEGIN
				SET @ELEMENTI_INSERITI = @ELEMENTI_INSERITI  + 1
			END
			ELSE 
			BEGIN
					SET @MESSAGGIOERRORE = @RADICEMESS  + ' - ERRORE- IMPOSSIBILE INSERIMENTO RECORD IN TABELLA dbo.GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE '
					EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
			END 					
			-- CONTROLLO PROVVIGIONE SU rate pachetto 9.6 i
			DECLARE CURR_RAPFAT CURSOR  LOCAL  FAST_FORWARD FOR
			SELECT GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.idRigaRata, 
				ISNULL(GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.CodArticolo,'') AS CodArticolo, 
				ISNULL(GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.PROVVIGIONE1, 0) AS PROVVIGIONE1,
				ISNULL(GEM_TESTACONTRATTO.CodAgente1,'') AS CodAgente1, 
				ISNULL(ANAGRAFICAAGENTI.DSCAGENTE,'') AS DSCAGENTE
			FROM ANAGRAFICAAGENTI RIGHT OUTER JOIN
				GEM_TESTACONTRATTO ON ANAGRAFICAAGENTI.CODAGENTE = GEM_TESTACONTRATTO.CodAgente1 RIGHT OUTER JOIN
				GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE ON 
				GEM_TESTACONTRATTO.IDCONTRATTO = GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.IDCONTRATTO
			WHERE GEM_SEZIONE_CONTRATTO_RAPPORTI_ELEMENTI_DA_FATTURARE.IDCONTRATTO = @IDCONTRATTO AND TipologiaElemento='R' AND PROVVIGIONE1=0 and idRigaRata = @NUMRATA
			OPEN CURR_RAPFAT
			FETCH NEXT FROM CURR_RAPFAT INTO @idRigaRata, @CodArticolo, @PROVVIGIONE1, @CodAgente1, @DSCAGENTE
			WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @MESSAGGIOERRORE = 'Attenzione per la riga ' + LTRIM(@idRigaRata) + ' di addebito rata la provvigione dell'' agente ' + RTRIM(@CodAgente1) + '-' + RTRIM(@DSCAGENTE) + ' è a ZERO' 
				PRINT '12'
				PRINT @MESSAGGIOERRORE
				EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
				FETCH NEXT FROM CURR_RAPFAT INTO @idRigaRata, @CodArticolo, @PROVVIGIONE1, @CodAgente1, @DSCAGENTE
			END

			CLOSE CURR_RAPFAT
			DEALLOCATE CURR_RAPFAT
			-- CONTROLLO PROVVIGIONE SU rate pachetto 9.6 f
		SET @MESSAGGIOERRORE = @RADICEMESS  + ' - INSERITO ' + rtrim(ltrim(str(@ELEMENTI_INSERITI))) + ' ELEMENTO DI FATTURAZIONE '
		EXEC GEM_REG_ERRORLOG @IDSESSIONE, @MESSAGGIOERRORE 
END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GEM_RAPPORTI_FATTURAZIONE_RATE] TO [Metodo98]
    AS [dbo];

