
CREATE PROCEDURE INCREMENTACONTATORE @PCODICE DECIMAL(5),@PESERCIZIO DECIMAL(5),@PUTENTE VARCHAR(25),@PAGGIORNA SMALLINT, @PPROG DECIMAL(10,0) OUTPUT AS
BEGIN
  IF @PAGGIORNA=0
    BEGIN
        DECLARE @PP DECIMAL(10)
      SELECT @PP = PROGR  FROM TABCONTATORI WHERE ESERCIZIO = @PESERCIZIO AND CODICE = @PCODICE
        SELECT @PPROG = ISNULL(@PP, 0) + 1
    END
  ELSE
    BEGIN
        DECLARE @R TABLE (PP DECIMAL(10));

        UPDATE 
            TABCONTATORI
        SET  
            PROGR = PROGR + 1, UTENTEMODIFICA = @PUTENTE, DATAMODIFICA = GETDATE() 
        OUTPUT 
            INSERTED.PROGR INTO @R
        WHERE 
            ESERCIZIO = @PESERCIZIO AND CODICE = @PCODICE

        SELECT TOP 1 @PPROG = PP FROM @R;
        SELECT @PPROG = ISNULL(@PPROG, 1) 
    END
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[INCREMENTACONTATORE] TO [Metodo98]
    AS [dbo];

