
CREATE PROCEDURE Mytho_AddOrderDetailEntity(
	@OrderOxId INT,
	@Attribute1Name	nvarchar(50),
	@Attribute1Value	nvarchar(50),
	@Attribute2Name	nvarchar(50),
	@Attribute2Value	nvarchar(50),
	@AttributeTextName	nvarchar(100),
	@AttributeTextValue	nvarchar(100),
	@DiscountCoupon	nvarchar(20),
	@DiscountRate	decimal(19, 6),
	@EcoTaxValueTaxIncl	decimal(19, 6),
	@GrossAmount	decimal(19, 6),
	@GrossPrice	decimal(19, 6),
	@ItemMainImageUrl	nvarchar(MAX),
	@ItemName	nvarchar(100),
	@ItemOxID	INT,
	@ItemSKU	nvarchar(40),
	@ItemSKUOriginal	nvarchar(40),
	@ItemThumbnailImageUrl	nvarchar(MAX),
	@NetAmount	decimal(19, 6),
	@NetPrice	decimal(19, 6),
	@Offered	BIT,
	@Option1Name	nvarchar(50),
	@Option1Value	nvarchar(50),
	@Option2Name	nvarchar(50),
	@Option2Value	nvarchar(50),
	@Option3Name	nvarchar(50),
	@Option3Value	nvarchar(50),
	@Quantity	INT,
	@TaxRate	decimal(19, 6),
	@VATAmount	decimal(19, 6)
)AS

INSERT INTO dbo.Mytho_OrderDetailEntities(
	OrderOxId,
    Attribute1Name,
    Attribute1Value,
    Attribute2Name,
    Attribute2Value,
    AttributeTextName,
    AttributeTextValue,
    DiscountCoupon,
    DiscountRate,
    EcoTaxValueTaxIncl,
    GrossAmount,
    GrossPrice,
    ItemMainImageUrl,
    ItemName,
    ItemOxID,
    ItemSKU,
    ItemSKUOriginal,
    ItemThumbnailImageUrl,
    NetAmount,
    NetPrice,
    Offered,
    Option1Name,
    Option1Value,
    Option2Name,
    Option2Value,
    Option3Name,
    Option3Value,
    Quantity,
    TaxRate,
    VATAmount
)VALUES (
	@OrderOxId,
    @Attribute1Name,
    @Attribute1Value,
    @Attribute2Name,
    @Attribute2Value,
    @AttributeTextName,
    @AttributeTextValue,
    @DiscountCoupon,
    @DiscountRate,
    @EcoTaxValueTaxIncl,
    @GrossAmount,
    @GrossPrice,
    @ItemMainImageUrl,
    @ItemName,
    @ItemOxID,
    @ItemSKU,
    @ItemSKUOriginal,
    @ItemThumbnailImageUrl,
    @NetAmount,
    @NetPrice,
    @Offered,
    @Option1Name,
    @Option1Value,
    @Option2Name,
    @Option2Value,
    @Option3Name,
    @Option3Value,
    @Quantity,
    @TaxRate,
    @VATAmount
)

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[Mytho_AddOrderDetailEntity] TO [Metodo98]
    AS [dbo];

