

CREATE PROCEDURE [dbo].[NUOVOPROGRESSIVO](@PTABELLA VARCHAR(80), @PAGGIORNA INTEGER, @PPROG DECIMAL(10) OUTPUT) AS
BEGIN
  IF @PAGGIORNA=0
    BEGIN
        DECLARE @PP DECIMAL(10)
        SELECT @PP = PROGR FROM TABPROGRESSIVI WHERE NOMETABELLA=@PTABELLA
        SELECT @PPROG = ISNULL(@PP, 0) + 1
    END
  ELSE
    BEGIN
        DECLARE @R TABLE (PP DECIMAL(10));

        MERGE INTO
            TABPROGRESSIVI T
        USING
            (SELECT @PTABELLA AS NOMETABELLA) AS S
        ON
            T.NOMETABELLA = S.NOMETABELLA
        WHEN
            NOT MATCHED THEN INSERT (NOMETABELLA, PROGR) VALUES (@PTABELLA, 1)
        WHEN
            MATCHED THEN UPDATE SET PROGR = PROGR + 1
        OUTPUT 
            INSERTED.PROGR INTO @R;

        SELECT TOP 1 @PPROG = PP FROM @R;
    END
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[NUOVOPROGRESSIVO] TO [Metodo98]
    AS [dbo];

