
CREATE PROCEDURE PR_TEMPBILANCIOVERIFICA (@strW NVARCHAR(1000), @Esercizio SMALLINT, @DATARINIZ VARCHAR(10), @DATARFINE VARCHAR(10), @NTerm SMALLINT, @STPSALDIZERO SMALLINT, @CODCAMBIOEURO SMALLINT) AS
BEGIN
  DECLARE @SQL NVARCHAR(2000) 
  DECLARE @TIPOSI SMALLINT
  DECLARE @STRWHERE NVARCHAR(1000)
    
  --Nel caso di campi data rimetto un apice singolo, altrimenti và in errore la query
  SET @STRWHERE = Replace(@strW, '{d '+char(39)+char(39), '{d '+char(39))
  SET @STRWHERE = Replace(@STRWHERE, char(39)+char(39)+'}', char(39)+'}')
  
  DELETE FROM TEMPBILANCIOVERIFICA WHERE NRTERMINALE=@NTerm

  /* DETERMINO IL TIPO DI SALDOINIZIALE E LA VISTA DA USARE */
  DECLARE CURCONT CURSOR FOR
  SELECT Progressivo FROM TesteContabilita WHERE Causale=(SELECT CausContAP FROM TabVincoliGIC WHERE Esercizio=@Esercizio) AND Esercizio=@Esercizio
  OPEN CURCONT
  
  FETCH NEXT FROM CURCONT 
  
  IF @@FETCH_STATUS = 0
     SET @TIPOSI=1
  ELSE
     BEGIN
        CLOSE CURCONT
    DEALLOCATE CURCONT
  
        DECLARE CURCONT CURSOR FOR
        SELECT Progressivo FROM TesteContabilita WHERE Causale=(SELECT CausContCH FROM TabVincoliGIC WHERE Esercizio=@Esercizio) AND Esercizio=@Esercizio-1
    OPEN CURCONT
  
    FETCH NEXT FROM CURCONT 
  
    IF @@FETCH_STATUS = 0
       SET @TIPOSI=2
    ELSE
       SET @TIPOSI=3
     END
     
  IF @TIPOSI<>1
     CLOSE CURCONT
     
  DEALLOCATE CURCONT

  DECLARE @NOMEVISTA NVARCHAR(20)
  
  SET @NOMEVISTA='VISTABILANCI' + CAST(@TIPOSI AS NVARCHAR(1))
  
  SET @SQL = 'INSERT INTO TEMPBILANCIOVERIFICA (CODMASTRO,CODCONTO,DSCCONTO1,DSCMASTRO,TIPOCONTO,SALDO,SALDOEURO,DARE,DAREEURO,AVERE,AVEREEURO,CAMBIOCONTRODIVISA,DATAREG,NRGIORNALE,ESERCIZIO,ESERCIZIOSI,PROVVISORIO,CAUSALE,DATAINIVALGEN,DATAFINEVALGEN,DATARINIZ,DATARFINE,CORDINE,NRTERMINALE) '
  SET @SQL = @SQL + 'SELECT CODMASTRO,CODCONTO,DSCCONTO1,DSCMASTRO,TIPOCONTO,SALDO,SALDOEURO,DARE,DAREEURO,AVERE,AVEREEURO,'
  SET @SQL = @SQL + '(SELECT CONTRODIVISA FROM TABCAMBI WHERE CODICE=' + CAST(@CODCAMBIOEURO AS NVARCHAR(5)) + '),'
  SET @SQL = @SQL + 'DATAREG,NRGIORNALE,ESERCIZIO,ESERCIZIOSI,PROVVISORIO,CAUSALE,'
  /* Per evitare problemi durante il confronto date all'interno della stored procedure, passo i campi data nel temporaneo ed eseguo il confronto nel report di stampa */
  SET @SQL = @SQL + '(CASE WHEN TIPOCONTO=''G'' THEN (SELECT DATAINIVALIDITA FROM ANAGRAFICAGENERICI WHERE CODCONTO=VISTABILANCI.CODCONTO) ELSE NULL END),'
  SET @SQL = @SQL + '(CASE WHEN TIPOCONTO=''G'' THEN (SELECT DATAFINEVALIDITA FROM ANAGRAFICAGENERICI WHERE CODCONTO=VISTABILANCI.CODCONTO) ELSE NULL END),'
  SET @SQL = @SQL + '{D ''' + RIGHT(@DATARINIZ,4) + '-' + SUBSTRING(@DATARINIZ,4,2) + '-' + LEFT(@DATARINIZ,2) + '''},'
  SET @SQL = @SQL + '{D ''' + RIGHT(@DATARFINE,4) + '-' + SUBSTRING(@DATARFINE,4,2) + '-' + LEFT(@DATARFINE,2) + '''},'
  SET @SQL = @SQL + '(CASE WHEN TIPOMASTRO=''O'' THEN 1 ELSE 0 END),'
  SET @SQL = @SQL + CAST(@NTerm AS NVARCHAR(10)) + ' FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
  EXEC(@SQL)

  IF @STPSALDIZERO<>0 
     BEGIN
      /* Nel caso di stampa saldi a zero, inserisco nel temporaneo gli eventuali conti che non rientrano nel filtro di stampa (Anomalia 5691) */
      SET @SQL = 'INSERT INTO TEMPBILANCIOVERIFICA (CODMASTRO,CODCONTO,DSCCONTO1,DSCMASTRO,TIPOCONTO,SALDO,SALDOEURO,DARE,DAREEURO,AVERE,AVEREEURO,DATAREG,NRGIORNALE,ESERCIZIO,ESERCIZIOSI,PROVVISORIO,CAUSALE,DATAINIVALGEN,DATAFINEVALGEN,DATARINIZ,DATARFINE,CORDINE,NRTERMINALE) '
      SET @SQL = @SQL + 'SELECT CODMASTRO,CODCONTO,DSCCONTO1,DSCMASTRO,TIPOCONTO,0,0,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,'
      SET @SQL = @SQL + '(CASE WHEN TIPOCONTO=''G'' THEN (SELECT DATAINIVALIDITA FROM ANAGRAFICAGENERICI WHERE CODCONTO=TABCFG.CODCONTO) ELSE NULL END),'
      SET @SQL = @SQL + '(CASE WHEN TIPOCONTO=''G'' THEN (SELECT DATAFINEVALIDITA FROM ANAGRAFICAGENERICI WHERE CODCONTO=TABCFG.CODCONTO) ELSE NULL END),'
     SET @SQL = @SQL + '{D ''' + RIGHT(@DATARINIZ,4) + '-' + SUBSTRING(@DATARINIZ,4,2) + '-' + LEFT(@DATARINIZ,2) + '''},'
     SET @SQL = @SQL + '{D ''' + RIGHT(@DATARFINE,4) + '-' + SUBSTRING(@DATARFINE,4,2) + '-' + LEFT(@DATARFINE,2) + '''},'
     SET @SQL = @SQL + '(CASE WHEN TIPOMASTRO=''O'' THEN 1 ELSE 0 END),'
      SET @SQL = @SQL + CAST(@NTerm AS NVARCHAR(10)) + ' FROM TABCFG WHERE '
      SET @SQL = @SQL + 'CODCONTO NOT IN (SELECT CODCONTO FROM TEMPBILANCIOVERIFICA WHERE NRTERMINALE=' + CAST(@NTerm AS NVARCHAR(10)) + ')'
      EXEC(@SQL)
     END  
END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PR_TEMPBILANCIOVERIFICA] TO [Metodo98]
    AS [dbo];

