
CREATE PROCEDURE PR_TEMPBILANCIOFISCALE(@strW NVARCHAR(1000), @Esercizio SMALLINT, @INCLUDISI SMALLINT, @TIPORIDOTTO SMALLINT, @STPDECIMALI SMALLINT, @IDSESSIONE SMALLINT) AS
BEGIN
    DECLARE @SQL NVARCHAR(2000) 
    DECLARE @TIPOSI SMALLINT
    DECLARE @STRWHERE NVARCHAR(1000)
    DECLARE @USAEURO SMALLINT

    SET @SQL = 'DELETE FROM TEMPBILANCIOFISCALE WHERE IDSESSIONE = ' + CAST(@IDSESSIONE AS NVARCHAR(10))
    PRINT(@SQL)
    EXEC(@SQL)

    --Nel caso di campi data rimetto un apice singolo, altrimenti vÓ in errore la query
    SET @STRWHERE = Replace(@strW, '{d '+char(39)+char(39), '{d '+char(39))
    SET @STRWHERE = Replace(@STRWHERE, char(39)+char(39)+'}', char(39)+'}')

    /* CREO UNA TABELLA TEMPORANEA SQL PER I DATI INTERMEDI */
    CREATE TABLE #TEMPSALDIBILANCIOCONTIDARE
    (
      TIPOPATRDARE           SMALLINT NOT NULL,
      TIPOMASTRODARE         VARCHAR(1),
      CODMASTRODARE          DECIMAL(5, 0) NOT NULL,
      CODCONTODARE           VARCHAR(7) NOT NULL,
      DSCCONTODARE           VARCHAR(80),
      SALDODARE              DECIMAL(19, 4) DEFAULT 0,
      SALDODAREEURO          DECIMAL(19, 4) DEFAULT 0,
      CONSTRAINT PK_TEMPSALDIBILANCIOCONTIDARE PRIMARY KEY (CODMASTRODARE,CODCONTODARE),
    )

    CREATE TABLE #TEMPSALDIBILANCIOCONTIAVERE
    (
      TIPOPATRAVERE           SMALLINT NOT NULL,
      TIPOMASTROAVERE         VARCHAR(1),
      CODMASTROAVERE          DECIMAL(5, 0) NOT NULL,
      CODCONTOAVERE           VARCHAR(7) NOT NULL,
      DSCCONTOAVERE           VARCHAR(80),
      SALDOAVERE              DECIMAL(19, 4) DEFAULT 0,
      SALDOAVEREEURO          DECIMAL(19, 4) DEFAULT 0,
      CONSTRAINT PK_TEMPSALDIBILANCIOCONTIAVERE PRIMARY KEY (CODMASTROAVERE,CODCONTOAVERE),
    )


    /* CONTROLLO SE L'ESERCIZIO E' IN EURO (ANOMALIA 10716) */
    DECLARE CURESERC CURSOR FOR
    SELECT USAEURO FROM TABESERCIZI WHERE CODICE=@Esercizio
    OPEN CURESERC
    
    FETCH NEXT FROM CURESERC INTO @USAEURO
    
    IF @@FETCH_STATUS <> 0
      SET @USAEURO=1
    
    CLOSE CURESERC
    DEALLOCATE CURESERC
    
    
    /* DETERMINO IL TIPO DI SALDOINIZIALE E LA VISTA DA USARE */
    DECLARE CURCONT CURSOR FOR
    SELECT Progressivo FROM TesteContabilita WHERE Causale=(SELECT CausContAP FROM TabVincoliGIC WHERE Esercizio=@Esercizio) AND Esercizio=@Esercizio
    OPEN CURCONT

    FETCH NEXT FROM CURCONT 

    IF @@FETCH_STATUS = 0
     SET @TIPOSI=1
    ELSE
     BEGIN
        CLOSE CURCONT
    DEALLOCATE CURCONT

        DECLARE CURCONT CURSOR FOR
        SELECT Progressivo FROM TesteContabilita WHERE Causale=(SELECT CausContCH FROM TabVincoliGIC WHERE Esercizio=@Esercizio) AND Esercizio=@Esercizio-1
    OPEN CURCONT

    FETCH NEXT FROM CURCONT 

    IF @@FETCH_STATUS = 0
       SET @TIPOSI=2
    ELSE
       SET @TIPOSI=3
    END
     
    IF @TIPOSI<>1
     CLOSE CURCONT
     
    DEALLOCATE CURCONT

    DECLARE @NOMEVISTA NVARCHAR(20)

    SET @NOMEVISTA='VISTABILANCI' + CAST(@TIPOSI AS NVARCHAR(1))


    /* INSERISCO I DATI PARZIALI CON I SALDI PER CONTO */
    -----------------------------------------------------

    /* DARE ECONOMICO */
    SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIDARE (TIPOPATRDARE,TIPOMASTRODARE,CODMASTRODARE,CODCONTODARE,DSCCONTODARE,SALDODARE,SALDODAREEURO) '

    IF @INCLUDISI=0   -- IncludiSI contiene l'indice del combo del filtro, quindi se zero significa Includi Saldi Iniziali=SI
     SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
    ELSE
     SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
     
    SET @SQL = @SQL + ' AND VISTABILANCI.TIPOMASTRO = ''E'''
    SET @SQL = @SQL + ' GROUP BY CODMASTRO,CODCONTO'

    
    IF @USAEURO = 1
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) > 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) > 0'
                END
        END
    ELSE
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) > 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) > 0'
                END
        END
        

    PRINT(@SQL)
    EXEC(@SQL)
    
    IF @TIPORIDOTTO<>0   --STAMPA RIDOTTA SENZA CLI/FOR O SOLO MASTRI: CALCOLO IL TOTALE PER MASTRO ED ELIMINO LE RIGHE DI DETTAGLIO DA NON VISUALIZZARE
        BEGIN
            SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIDARE (TIPOPATRDARE,TIPOMASTRODARE,CODMASTRODARE,CODCONTODARE,SALDODARE,SALDODAREEURO) '

            IF @STPDECIMALI=0
                SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTRODARE),CODMASTRODARE,''TOTMAST'',SUM(ROUND(SALDODARE,0)),SUM(ROUND(SALDODAREEURO,0)) FROM #TEMPSALDIBILANCIOCONTIDARE GROUP BY CODMASTRODARE'
            ELSE
                SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTRODARE),CODMASTRODARE,''TOTMAST'',SUM(SALDODARE),SUM(SALDODAREEURO) FROM #TEMPSALDIBILANCIOCONTIDARE GROUP BY CODMASTRODARE'                
            
            PRINT(@SQL)
            EXEC(@SQL)
            
        
            IF @TIPORIDOTTO=1    --RIDOTTO SENZA CLI/FOR
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIDARE WHERE CODCONTODARE<>'''' AND LEFT(CODCONTODARE,1)<>''G'' AND CODCONTODARE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END
            ELSE    --SOLO MASTRI
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIDARE WHERE CODCONTODARE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END             
        END 

    /* AVERE ECONOMICO */
    SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIAVERE (TIPOPATRAVERE,TIPOMASTROAVERE,CODMASTROAVERE,CODCONTOAVERE,DSCCONTOAVERE,SALDOAVERE,SALDOAVEREEURO) '

    IF @INCLUDISI=0   -- IncludiSI contiene l'indice del combo del filtro, quindi se zero significa Includi Saldi Iniziali=SI
     SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
    ELSE
     SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE

    SET @SQL = @SQL + ' AND VISTABILANCI.TIPOMASTRO = ''E'''
    SET @SQL = @SQL + ' GROUP BY CODMASTRO,CODCONTO'

    IF @USAEURO = 1
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) < 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) < 0'  
                END
        END
    ELSE
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) < 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) < 0'  
                END
        END

    PRINT(@SQL)
    EXEC(@SQL)

    IF @TIPORIDOTTO<>0   --STAMPA RIDOTTA SENZA CLI/FOR O SOLO MASTRI: CALCOLO IL TOTALE PER MASTRO ED ELIMINO LE RIGHE DI DETTAGLIO DA NON VISUALIZZARE
        BEGIN
            SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIAVERE (TIPOPATRAVERE,TIPOMASTROAVERE,CODMASTROAVERE,CODCONTOAVERE,SALDOAVERE,SALDOAVEREEURO) '
            
            IF @STPDECIMALI=0
                SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTROAVERE),CODMASTROAVERE,''TOTMAST'',SUM(ROUND(SALDOAVERE,0)),SUM(ROUND(SALDOAVEREEURO,0)) FROM #TEMPSALDIBILANCIOCONTIAVERE GROUP BY CODMASTROAVERE'
            ELSE
                SET @SQL = @SQL + 'SELECT 0,MIN(TIPOMASTROAVERE),CODMASTROAVERE,''TOTMAST'',SUM(SALDOAVERE),SUM(SALDOAVEREEURO) FROM #TEMPSALDIBILANCIOCONTIAVERE GROUP BY CODMASTROAVERE'
            
            PRINT(@SQL)
            EXEC(@SQL)
            
            
            IF @TIPORIDOTTO=1    --RIDOTTO SENZA CLI/FOR
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIAVERE WHERE CODCONTOAVERE<>'''' AND LEFT(CODCONTOAVERE,1)<>''G'' AND CODCONTOAVERE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END
            ELSE    --SOLO MASTRI
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIAVERE WHERE CODCONTOAVERE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END             
        END 

    /* DARE PATRIMONIALE */
    SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIDARE (TIPOPATRDARE,TIPOMASTRODARE,CODMASTRODARE,CODCONTODARE,DSCCONTODARE,SALDODARE,SALDODAREEURO) '

    IF @INCLUDISI=0   -- IncludiSI contiene l'indice del combo del filtro, quindi se zero significa Includi Saldi Iniziali=SI
     SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
    ELSE
     SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
     
    SET @SQL = @SQL + ' AND VISTABILANCI.TIPOMASTRO <> ''E'''
    SET @SQL = @SQL + ' GROUP BY CODMASTRO,CODCONTO'

    IF @USAEURO = 1
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) > 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) > 0'
                END
        END
    ELSE
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) > 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) > 0'
                END
        END
    
    
    
    PRINT(@SQL)
    EXEC(@SQL)
    
    IF @TIPORIDOTTO<>0   --STAMPA RIDOTTA SENZA CLI/FOR O SOLO MASTRI: CALCOLO IL TOTALE PER MASTRO ED ELIMINO LE RIGHE DI DETTAGLIO DA NON VISUALIZZARE
        BEGIN
            SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIDARE (TIPOPATRDARE,TIPOMASTRODARE,CODMASTRODARE,CODCONTODARE,SALDODARE,SALDODAREEURO) '
            
            IF @STPDECIMALI=0
                SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTRODARE),CODMASTRODARE,''TOTMAST'',SUM(ROUND(SALDODARE,0)),SUM(ROUND(SALDODAREEURO,0)) FROM #TEMPSALDIBILANCIOCONTIDARE WHERE TIPOPATRDARE=1 GROUP BY CODMASTRODARE'
            ELSE
                SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTRODARE),CODMASTRODARE,''TOTMAST'',SUM(SALDODARE),SUM(SALDODAREEURO) FROM #TEMPSALDIBILANCIOCONTIDARE WHERE TIPOPATRDARE=1 GROUP BY CODMASTRODARE'
            
            PRINT(@SQL)
            EXEC(@SQL)
        
            IF @TIPORIDOTTO=1    --RIDOTTO SENZA CLI/FOR
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIDARE WHERE CODCONTODARE<>'''' AND LEFT(CODCONTODARE,1)<>''G'' AND CODCONTODARE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END
            ELSE    --SOLO MASTRI
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIDARE WHERE CODCONTODARE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END             
        END     

    /* AVERE PATRIMONIALE */
    SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIAVERE (TIPOPATRAVERE,TIPOMASTROAVERE,CODMASTROAVERE,CODCONTOAVERE,DSCCONTOAVERE,SALDOAVERE,SALDOAVEREEURO) '

    IF @INCLUDISI=0   -- IncludiSI contiene l'indice del combo del filtro, quindi se zero significa Includi Saldi Iniziali=SI
     SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE
    ELSE
     SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTRO),CODMASTRO,CODCONTO,MIN(DSCCONTO1),(SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)),(SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) FROM ' + @NOMEVISTA + ' VISTABILANCI WHERE ' + @STRWHERE

    SET @SQL = @SQL + ' AND VISTABILANCI.TIPOMASTRO <> ''E'''
    SET @SQL = @SQL + ' GROUP BY CODMASTRO,CODCONTO'

    IF @USAEURO = 1
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDOEURO IS NULL THEN 0 ELSE SALDOEURO END) + SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) < 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DAREEURO IS NULL THEN 0 ELSE DAREEURO END) - SUM(CASE WHEN AVEREEURO IS NULL THEN 0 ELSE AVEREEURO END)) < 0'  
                END
        END
    ELSE
        BEGIN
            IF @INCLUDISI=0
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END) + SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) < 0'
                END
            ELSE
                BEGIN
                    SET @SQL = @SQL + ' HAVING (SUM(CASE WHEN DARE IS NULL THEN 0 ELSE DARE END) - SUM(CASE WHEN AVERE IS NULL THEN 0 ELSE AVERE END)) < 0'  
                END
        END
    
    
    PRINT(@SQL)
    EXEC(@SQL)

    IF @TIPORIDOTTO<>0   --STAMPA RIDOTTA SENZA CLI/FOR O SOLO MASTRI: CALCOLO IL TOTALE PER MASTRO ED ELIMINO LE RIGHE DI DETTAGLIO DA NON VISUALIZZARE
        BEGIN
            SET @SQL = 'INSERT INTO #TEMPSALDIBILANCIOCONTIAVERE (TIPOPATRAVERE,TIPOMASTROAVERE,CODMASTROAVERE,CODCONTOAVERE,SALDOAVERE,SALDOAVEREEURO) '
            
            IF @STPDECIMALI=0
                SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTROAVERE),CODMASTROAVERE,''TOTMAST'',SUM(ROUND(SALDOAVERE,0)),SUM(ROUND(SALDOAVEREEURO,0)) FROM #TEMPSALDIBILANCIOCONTIAVERE WHERE TIPOPATRAVERE=1 GROUP BY CODMASTROAVERE'
            ELSE
                SET @SQL = @SQL + 'SELECT 1,MIN(TIPOMASTROAVERE),CODMASTROAVERE,''TOTMAST'',SUM(SALDOAVERE),SUM(SALDOAVEREEURO) FROM #TEMPSALDIBILANCIOCONTIAVERE WHERE TIPOPATRAVERE=1 GROUP BY CODMASTROAVERE'

            PRINT(@SQL)
            EXEC(@SQL)
        
            IF @TIPORIDOTTO=1    --RIDOTTO SENZA CLI/FOR
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIAVERE WHERE CODCONTOAVERE<>'''' AND LEFT(CODCONTOAVERE,1)<>''G'' AND CODCONTOAVERE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END
            ELSE    --SOLO MASTRI
                BEGIN
                    SET @SQL = 'DELETE FROM #TEMPSALDIBILANCIOCONTIAVERE WHERE CODCONTOAVERE<>''TOTMAST''' 
                    PRINT(@SQL)
                    EXEC(@SQL)
                END             
        END 

    /* INSERISCO I DATI EFFETTIVI CON I SALDI PER MASTRO */
    -------------------------------------------------------

    DECLARE @MASTRODARE DECIMAL(5, 0)
    DECLARE @CONTODARE NVARCHAR(7)
    DECLARE @SALDODARE DECIMAL(19, 4)
    DECLARE @SALDODAREEURO DECIMAL(19, 4)
    DECLARE @DSCMASTRODARE NVARCHAR(80)
    DECLARE @DSCCONTODARE NVARCHAR(80)
    DECLARE @TIPOMASTRODARE NVARCHAR(1)
        
    DECLARE @MASTROAVERE DECIMAL(5, 0)
    DECLARE @CONTOAVERE NVARCHAR(7)

    DECLARE @SALDOAVERE DECIMAL(19, 4)
    DECLARE @SALDOAVEREEURO DECIMAL(19, 4)
    DECLARE @DSCMASTROAVERE NVARCHAR(80)
    DECLARE @DSCCONTOAVERE NVARCHAR(80)
    DECLARE @TIPOMASTROAVERE NVARCHAR(1)
    
    DECLARE @PROGRECORD INTEGER
    DECLARE @TIPOFISCALE SMALLINT
    
    DECLARE @TOTMASTRODARE DECIMAL(19, 4)
    DECLARE @TOTMASTROAVERE DECIMAL(19, 4)
    DECLARE @TOTMASTRODAREEURO DECIMAL(19, 4)
    DECLARE @TOTMASTROAVEREEURO DECIMAL(19, 4)
    DECLARE @TOTMASTRODAREEUROARROT DECIMAL(19, 4)
    DECLARE @TOTMASTROAVEREEUROARROT DECIMAL(19, 4)
    

    DECLARE @CODMASTRODAREPREC DECIMAL(5, 0)
    DECLARE @DSCMASTRODAREPREC NVARCHAR(80)
    DECLARE @TIPOMASTRODAREPREC NVARCHAR(1)
    DECLARE @CODMASTROAVEREPREC DECIMAL(5, 0)
    DECLARE @DSCMASTROAVEREPREC NVARCHAR(80)
    DECLARE @TIPOMASTROAVEREPREC NVARCHAR(1)
    
    /*MEMORIZZAZIONE VALORI DI FETCH DEI 2 CURSORI */
    DECLARE @FETCHVAL1 INTEGER
    DECLARE @FETCHVAL2 INTEGER
    
    DECLARE @INSERITOTOTDARE SMALLINT
    DECLARE @INSERITOTOTAVERE SMALLINT
    
    DECLARE @TOTALEDAREECO DECIMAL(19, 4)
    DECLARE @TOTALEDAREECOEURO DECIMAL(19, 4)
    DECLARE @TOTALEDAREECOEUROARROT DECIMAL(19, 4)
    DECLARE @TOTALEAVEREECO DECIMAL(19, 4)
    DECLARE @TOTALEAVEREECOEURO DECIMAL(19, 4)
    DECLARE @TOTALEAVEREECOEUROARROT DECIMAL(19, 4)
        
    
    /*********************************************************************************/
    /* DATI CONTO ECONOMICO */
    /*********************************************************************************/
    
    DECLARE CURSALDIDARE CURSOR FOR
    SELECT CODMASTRODARE,CODCONTODARE,SALDODARE,SALDODAREEURO,(SELECT DESCRIZIONE FROM TABMASTRI WHERE CODICE=TD.CODMASTRODARE) AS DSCMASTRODARE,DSCCONTODARE,(SELECT TIPO FROM TABMASTRI WHERE CODICE=TD.CODMASTRODARE) AS TIPOMASTRODARE FROM #TEMPSALDIBILANCIOCONTIDARE TD WHERE TIPOPATRDARE=0 ORDER BY CODMASTRODARE,CODCONTODARE
    OPEN CURSALDIDARE

    DECLARE CURSALDIAVERE CURSOR FOR
    SELECT CODMASTROAVERE,CODCONTOAVERE,SALDOAVERE,SALDOAVEREEURO,(SELECT DESCRIZIONE FROM TABMASTRI WHERE CODICE=TA.CODMASTROAVERE) AS DSCMASTROAVERE,DSCCONTOAVERE,(SELECT TIPO FROM TABMASTRI WHERE CODICE=TA.CODMASTROAVERE) AS TIPOMASTROAVERE FROM #TEMPSALDIBILANCIOCONTIAVERE TA WHERE TIPOPATRAVERE=0 ORDER BY CODMASTROAVERE,CODCONTOAVERE
    OPEN CURSALDIAVERE

    FETCH NEXT FROM CURSALDIDARE INTO @MASTRODARE,@CONTODARE,@SALDODARE,@SALDODAREEURO,@DSCMASTRODARE,@DSCCONTODARE,@TIPOMASTRODARE
    SET @FETCHVAL1 = @@FETCH_STATUS
    
    FETCH NEXT FROM CURSALDIAVERE INTO @MASTROAVERE,@CONTOAVERE,@SALDOAVERE,@SALDOAVEREEURO,@DSCMASTROAVERE,@DSCCONTOAVERE,@TIPOMASTROAVERE
    SET @FETCHVAL2 = @@FETCH_STATUS
    
    SET @PROGRECORD = 1

    SET @TOTMASTRODARE = 0
    SET @TOTMASTROAVERE = 0
    SET @TOTMASTRODAREEURO = 0
    SET @TOTMASTROAVEREEURO = 0
    SET @TOTMASTRODAREEUROARROT = 0
    SET @TOTMASTROAVEREEUROARROT = 0
    
    SET @CODMASTRODAREPREC = 0
    SET @CODMASTROAVEREPREC = 0
    SET @INSERITOTOTDARE = 0
    SET @INSERITOTOTAVERE = 0
    
    SET @TOTALEDAREECO = 0
    SET @TOTALEDAREECOEURO = 0
    SET @TOTALEDAREECOEUROARROT = 0
    SET @TOTALEAVEREECO = 0
    SET @TOTALEAVEREECOEURO = 0
    SET @TOTALEAVEREECOEUROARROT = 0
    
    WHILE NOT(@FETCHVAL1<>0 AND @FETCHVAL2<>0)
        BEGIN
            
            SET @SQL = 'INSERT INTO TEMPBILANCIOFISCALE (IDSESSIONE,TIPOFISCALE,PROGRECORD,MASTRODARE,DSCMASTRODARE,TIPOMASTRODARE,CONTODARE,DSCCONTODARE,IMPORTODARE,IMPORTODAREEURO,TOTMASTRODAREEUROARROT,MASTROAVERE,DSCMASTROAVERE,TIPOMASTROAVERE,CONTOAVERE,DSCCONTOAVERE,IMPORTOAVERE,IMPORTOAVEREEURO,TOTMASTROAVEREEUROARROT) VALUES ('
            SET @SQL = @SQL + CAST(@IDSESSIONE AS NVARCHAR(10)) + ',0,' + CAST(@PROGRECORD AS NVARCHAR(5)) 
            
            IF @FETCHVAL1 = 0 
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @MASTRODARE<>@CODMASTRODAREPREC AND @CODMASTRODAREPREC<>0
                            BEGIN
                                SET @SQL = @SQL + ',' + CAST(@CODMASTRODAREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODAREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODAREPREC + ''','''','''',' + CAST(@TOTMASTRODARE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEUROARROT AS NVARCHAR(23))
                                SET @INSERITOTOTDARE = 1
                                SET @TOTMASTRODARE = 0
                                SET @TOTMASTRODAREEURO = 0
                                SET @TOTMASTRODAREEUROARROT = 0
                            END
                        ELSE
                            BEGIN
                                SET @SQL = @SQL + ',' + CAST(@MASTRODARE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODARE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODARE + ''',''' + @CONTODARE + ''',''' + REPLACE(@DSCCONTODARE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDODARE AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',0'
                                SET @INSERITOTOTDARE = 0
                            END
                    END
                ELSE
                    BEGIN
                        IF @CONTODARE <> 'TOTMAST' 
                            SET @SQL = @SQL + ',' + CAST(@MASTRODARE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODARE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODARE + ''',''' + @CONTODARE + ''',''' + REPLACE(@DSCCONTODARE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDODARE AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',0'
                        ELSE
                            SET @SQL = @SQL + ',' + CAST(@MASTRODARE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODARE,CHAR(39),CHAR(39)+CHAR(39)) + ''',''' + @TIPOMASTRODARE + ''','''','''',' + CAST(@SALDODARE AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23))
                            
                        SET @INSERITOTOTDARE = 0
                    END
                
            ELSE
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @INSERITOTOTDARE = 0   -- INSERISCO IL TOTALE DELL'ULTIMO MASTRO STAMPATO
                            BEGIN
                                IF @TIPOMASTRODAREPREC IS NULL 
                                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                                ELSE
                                    BEGIN
                                        SET @SQL = @SQL + ',' + CAST(@CODMASTRODAREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODAREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODAREPREC + ''','''','''',' + CAST(@TOTMASTRODARE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEUROARROT AS NVARCHAR(23))
                                        SET @INSERITOTOTDARE = 1
                                        SET @TOTMASTRODARE = 0
                                        SET @TOTMASTRODAREEURO = 0
                                        SET @TOTMASTRODAREEUROARROT = 0
                                    END
                            END
                        ELSE
                            SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                    END
                ELSE
                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
            
            IF @FETCHVAL2 = 0 
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @MASTROAVERE<>@CODMASTROAVEREPREC AND @CODMASTROAVEREPREC<>0
                            BEGIN
                                SET @SQL = @SQL + ',' + CAST(@CODMASTROAVEREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVEREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVEREPREC + ''','''','''',' + CAST(@TOTMASTROAVERE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEUROARROT AS NVARCHAR(23))
                                SET @INSERITOTOTAVERE = 1
                                SET @TOTMASTROAVERE = 0
                                SET @TOTMASTROAVEREEURO = 0
                                SET @TOTMASTROAVEREEUROARROT = 0
                            END
                        ELSE
                            BEGIN
                                SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVERE + ''',''' + @CONTOAVERE + ''',''' + REPLACE(@DSCCONTOAVERE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',0'
                                SET @INSERITOTOTAVERE = 0
                            END
                    END
                ELSE
                    BEGIN
                        IF @CONTOAVERE <> 'TOTMAST'
                            SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVERE + ''',''' + @CONTOAVERE + ''',''' + REPLACE(@DSCCONTOAVERE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',0'
                        ELSE
                            SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,CHAR(39),CHAR(39)+CHAR(39)) + ''',''' + @TIPOMASTROAVERE + ''','''','''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23))
                        
                        SET @INSERITOTOTAVERE = 0
                    END                 
            ELSE
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @INSERITOTOTAVERE = 0   -- INSERISCO IL TOTALE DELL'ULTIMO MASTRO STAMPATO
                            BEGIN
                                IF @TIPOMASTROAVEREPREC IS NULL 
                                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                                ELSE
                                    BEGIN
                                        SET @SQL = @SQL + ',' + CAST(@CODMASTROAVEREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVEREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVEREPREC + ''','''','''',' + CAST(@TOTMASTROAVERE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEUROARROT AS NVARCHAR(23))
                                        SET @INSERITOTOTAVERE = 1
                                        SET @TOTMASTROAVERE = 0
                                        SET @TOTMASTROAVEREEURO = 0
                                        SET @TOTMASTROAVEREEUROARROT = 0
                                    END
                            END
                        ELSE
                            SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                    END
                ELSE
                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
            
            SET @SQL = @SQL + ')'
            
            PRINT(@SQL)
            EXEC(@SQL)
            
            IF @TIPORIDOTTO=0
                BEGIN
                    IF @INSERITOTOTDARE = 0 
                        BEGIN
                            IF NOT @SALDODAREEURO IS NULL
                                BEGIN
                                    SET @TOTMASTRODARE = @TOTMASTRODARE + @SALDODARE
                                    SET @TOTMASTRODAREEURO = @TOTMASTRODAREEURO + @SALDODAREEURO
                                    SET @TOTMASTRODAREEUROARROT = @TOTMASTRODAREEUROARROT + ROUND(@SALDODAREEURO,0)
                                    SET @TOTALEDAREECO = @TOTALEDAREECO + @SALDODARE
                                    SET @TOTALEDAREECOEURO = @TOTALEDAREECOEURO + @SALDODAREEURO
                                    SET @TOTALEDAREECOEUROARROT = @TOTALEDAREECOEUROARROT + ROUND(@SALDODAREEURO,0)
                                END
                        END 
                END
            ELSE
                IF @CONTODARE='TOTMAST' AND @FETCHVAL1 = 0 
                    BEGIN
                        SET @TOTALEDAREECO = @TOTALEDAREECO + @SALDODARE
                        SET @TOTALEDAREECOEURO = @TOTALEDAREECOEURO + @SALDODAREEURO
                        SET @TOTALEDAREECOEUROARROT = @TOTALEDAREECOEUROARROT + ROUND(@SALDODAREEURO,0)
                    END
            
            IF @TIPORIDOTTO=0
                BEGIN
                    IF @INSERITOTOTAVERE = 0 
                        BEGIN
                            IF NOT @SALDOAVEREEURO IS NULL
                                BEGIN
                                    SET @TOTMASTROAVERE = @TOTMASTROAVERE + @SALDOAVERE
                                    SET @TOTMASTROAVEREEURO = @TOTMASTROAVEREEURO + @SALDOAVEREEURO
                                    SET @TOTMASTROAVEREEUROARROT = @TOTMASTROAVEREEUROARROT + ROUND(@SALDOAVEREEURO,0)
                                    SET @TOTALEAVEREECO = @TOTALEAVEREECO + @SALDOAVERE
                                    SET @TOTALEAVEREECOEURO = @TOTALEAVEREECOEURO+ @SALDOAVEREEURO
                                    SET @TOTALEAVEREECOEUROARROT= @TOTALEAVEREECOEUROARROT + ROUND(@SALDOAVEREEURO,0)
                                END
                        END
                END
            ELSE
                IF @CONTOAVERE='TOTMAST' IF @FETCHVAL2 = 0 
                    BEGIN
                        SET @TOTALEAVEREECO = @TOTALEAVEREECO + @SALDOAVERE
                        SET @TOTALEAVEREECOEURO = @TOTALEAVEREECOEURO+ @SALDOAVEREEURO
                        SET @TOTALEAVEREECOEUROARROT= @TOTALEAVEREECOEUROARROT + ROUND(@SALDOAVEREEURO,0)
                    END
            
            SET @CODMASTRODAREPREC = @MASTRODARE
            SET @DSCMASTRODAREPREC = @DSCMASTRODARE
            SET @TIPOMASTRODAREPREC = @TIPOMASTRODARE
            SET @CODMASTROAVEREPREC = @MASTROAVERE
            SET @DSCMASTROAVEREPREC = @DSCMASTROAVERE
            SET @TIPOMASTROAVEREPREC = @TIPOMASTROAVERE
            
            IF @INSERITOTOTDARE = 0 OR @TIPORIDOTTO<>0
                BEGIN
                    FETCH NEXT FROM CURSALDIDARE INTO @MASTRODARE,@CONTODARE,@SALDODARE,@SALDODAREEURO,@DSCMASTRODARE,@DSCCONTODARE,@TIPOMASTRODARE
                    SET @FETCHVAL1 = @@FETCH_STATUS
                END
            
            IF @INSERITOTOTAVERE = 0 OR @TIPORIDOTTO<>0
                BEGIN
                    FETCH NEXT FROM CURSALDIAVERE INTO @MASTROAVERE,@CONTOAVERE,@SALDOAVERE,@SALDOAVEREEURO,@DSCMASTROAVERE,@DSCCONTOAVERE,@TIPOMASTROAVERE
                    SET @FETCHVAL2 = @@FETCH_STATUS
                END
            
            SET @PROGRECORD = @PROGRECORD + 1
        END
        
    /* INSERISCO L'EVENTUALE ULTIMO RECORDO CON IL TOTALE DELL'ULTIMO MASTRO LETTO */   
    IF @TIPORIDOTTO=0
        BEGIN
            IF @INSERITOTOTDARE = 0 OR @INSERITOTOTAVERE = 0
                BEGIN
                    SET @SQL = 'INSERT INTO TEMPBILANCIOFISCALE (IDSESSIONE,TIPOFISCALE,PROGRECORD,MASTRODARE,DSCMASTRODARE,TIPOMASTRODARE,CONTODARE,DSCCONTODARE,IMPORTODARE,IMPORTODAREEURO,TOTMASTRODAREEUROARROT,MASTROAVERE,DSCMASTROAVERE,TIPOMASTROAVERE,CONTOAVERE,DSCCONTOAVERE,IMPORTOAVERE,IMPORTOAVEREEURO,TOTMASTROAVEREEUROARROT) VALUES ('
                    SET @SQL = @SQL + CAST(@IDSESSIONE AS NVARCHAR(10)) + ',0,' + CAST(@PROGRECORD AS NVARCHAR(5)) 
                    

                    IF @INSERITOTOTDARE = 0   
                        BEGIN
                            IF @TIPOMASTRODAREPREC IS NULL
                                SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                            ELSE
                                BEGIN
                                    SET @SQL = @SQL + ',' + CAST(@CODMASTRODAREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODAREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODAREPREC + ''','''','''',' + CAST(@TOTMASTRODARE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEUROARROT AS NVARCHAR(23))
                                    SET @INSERITOTOTDARE = 1
                                    SET @TOTMASTRODARE = 0
                                    SET @TOTMASTRODAREEURO = 0
                                    SET @TOTMASTRODAREEUROARROT = 0
                                END
                        END
                    ELSE
                        SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                    
                    IF @INSERITOTOTAVERE = 0   
                        BEGIN
                            IF @TIPOMASTROAVEREPREC IS NULL
                                SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                            ELSE
                                BEGIN
                                    SET @SQL = @SQL + ',' + CAST(@CODMASTROAVEREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVEREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVEREPREC + ''','''','''',' + CAST(@TOTMASTROAVERE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEUROARROT AS NVARCHAR(23))
                                    SET @INSERITOTOTAVERE = 1
                                    SET @TOTMASTROAVERE = 0
                                    SET @TOTMASTROAVEREEURO = 0
                                    SET @TOTMASTROAVEREEUROARROT = 0
                                END
                        END
                    ELSE
                        SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0'
                    
                    SET @SQL = @SQL + ')'
                    
                    PRINT(@SQL)
                    EXEC(@SQL)
                END
        END
        
    CLOSE CURSALDIDARE
    DEALLOCATE CURSALDIDARE
    
    CLOSE CURSALDIAVERE
    DEALLOCATE CURSALDIAVERE
        
    /*********************************************************************************/
    /* DATI PATRIMONIALE */
    /*********************************************************************************/
    
    DECLARE CURSALDIDARE CURSOR FOR
    SELECT CODMASTRODARE,CODCONTODARE,SALDODARE,SALDODAREEURO,(SELECT DESCRIZIONE FROM TABMASTRI WHERE CODICE=TD.CODMASTRODARE) AS DSCMASTRODARE,DSCCONTODARE,TIPOMASTRODARE FROM #TEMPSALDIBILANCIOCONTIDARE TD WHERE TIPOPATRDARE=1 ORDER BY TIPOMASTRODARE DESC,CODMASTRODARE,CODCONTODARE
    OPEN CURSALDIDARE

    DECLARE CURSALDIAVERE CURSOR FOR
    SELECT CODMASTROAVERE,CODCONTOAVERE,SALDOAVERE,SALDOAVEREEURO,(SELECT DESCRIZIONE FROM TABMASTRI WHERE CODICE=TA.CODMASTROAVERE) AS DSCMASTROAVERE,DSCCONTOAVERE,TIPOMASTROAVERE FROM #TEMPSALDIBILANCIOCONTIAVERE TA WHERE TIPOPATRAVERE=1 ORDER BY TIPOMASTROAVERE DESC,CODMASTROAVERE,CODCONTOAVERE
    OPEN CURSALDIAVERE

    FETCH NEXT FROM CURSALDIDARE INTO @MASTRODARE,@CONTODARE,@SALDODARE,@SALDODAREEURO,@DSCMASTRODARE,@DSCCONTODARE,@TIPOMASTRODARE
    SET @FETCHVAL1 = @@FETCH_STATUS
    
    FETCH NEXT FROM CURSALDIAVERE INTO @MASTROAVERE,@CONTOAVERE,@SALDOAVERE,@SALDOAVEREEURO,@DSCMASTROAVERE,@DSCCONTOAVERE,@TIPOMASTROAVERE
    SET @FETCHVAL2 = @@FETCH_STATUS
    
    SET @PROGRECORD = 1
    
    SET @TOTMASTRODARE = 0
    SET @TOTMASTROAVERE = 0
    SET @TOTMASTRODAREEURO = 0
    SET @TOTMASTROAVEREEURO = 0
    SET @TOTMASTRODAREEUROARROT = 0
    SET @TOTMASTROAVEREEUROARROT = 0
    
    SET @CODMASTRODAREPREC = 0
    SET @CODMASTROAVEREPREC = 0
    SET @INSERITOTOTDARE = 0
    SET @INSERITOTOTAVERE = 0
    
    WHILE NOT(@FETCHVAL1<>0 AND @FETCHVAL2<>0)
        BEGIN
            SET @SQL = 'INSERT INTO TEMPBILANCIOFISCALE (IDSESSIONE,TIPOFISCALE,PROGRECORD,MASTRODARE,DSCMASTRODARE,TIPOMASTRODARE,CONTODARE,DSCCONTODARE,IMPORTODARE,IMPORTODAREEURO,TOTMASTRODAREEUROARROT,TOTALEDAREECO,TOTALEDAREECOEURO,TOTALEDAREECOEUROARROT,MASTROAVERE,DSCMASTROAVERE,TIPOMASTROAVERE,CONTOAVERE,DSCCONTOAVERE,IMPORTOAVERE,IMPORTOAVEREEURO,TOTMASTROAVEREEUROARROT,TOTALEAVEREECO,TOTALEAVEREECOEURO,TOTALEAVEREECOEUROARROT) VALUES ('
            SET @SQL = @SQL + CAST(@IDSESSIONE AS NVARCHAR(10)) + ',1,' + CAST(@PROGRECORD AS NVARCHAR(5)) 
            
            IF @FETCHVAL1 = 0 
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @MASTRODARE<>@CODMASTRODAREPREC AND @CODMASTRODAREPREC<>0
                            BEGIN
                                SET @SQL = @SQL + ',' + CAST(@CODMASTRODAREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODAREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODAREPREC + ''','''','''',' + CAST(@TOTMASTRODARE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEUROARROT AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                                SET @INSERITOTOTDARE = 1
                                SET @TOTMASTRODARE = 0
                                SET @TOTMASTRODAREEURO = 0
                                SET @TOTMASTRODAREEUROARROT = 0
                            END
                        ELSE
                            BEGIN
                                SET @SQL = @SQL + ',' + CAST(@MASTRODARE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODARE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODARE + ''',''' + @CONTODARE + ''',''' + REPLACE(@DSCCONTODARE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDODARE AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                                SET @INSERITOTOTDARE = 0
                            END
                    END
                ELSE
                    BEGIN
                        IF @CONTODARE <> 'TOTMAST'
                            SET @SQL = @SQL + ',' + CAST(@MASTRODARE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODARE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODARE + ''',''' + @CONTODARE + ''',''' + REPLACE(@DSCCONTODARE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDODARE AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                        ELSE
                            SET @SQL = @SQL + ',' + CAST(@MASTRODARE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODARE,CHAR(39),CHAR(39)+CHAR(39)) + ''',''' + @TIPOMASTRODARE + ''','''','''',' + CAST(@SALDODARE AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',' + CAST(@SALDODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                        
                        SET @INSERITOTOTDARE = 0
                    END
                
            ELSE
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @INSERITOTOTDARE = 0   -- INSERISCO IL TOTALE DELL'ULTIMO MASTRO STAMPATO
                            BEGIN
                                IF @TIPOMASTRODAREPREC IS NULL
                                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                                ELSE
                                    BEGIN
                                        SET @SQL = @SQL + ',' + CAST(@CODMASTRODAREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODAREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTRODAREPREC + ''','''','''',' + CAST(@TOTMASTRODARE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEUROARROT AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                                        SET @INSERITOTOTDARE = 1
                                        SET @TOTMASTRODARE = 0
                                        SET @TOTMASTRODAREEURO = 0
                                        SET @TOTMASTRODAREEUROARROT = 0
                                    END
                            END
                        ELSE
                            SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                    END
                ELSE
                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                    
            IF @FETCHVAL2 = 0 
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @MASTROAVERE<>@CODMASTROAVEREPREC AND @CODMASTROAVEREPREC<>0
                            BEGIN
                                IF @CODMASTROAVEREPREC IS NULL
                                    BEGIN               
                                        SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVERE + ''',''' + @CONTOAVERE + ''',''' + REPLACE(@DSCCONTOAVERE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                                        SET @INSERITOTOTAVERE = 0
                                    END
                                ELSE
                                    BEGIN                               
                                        SET @SQL = @SQL + ',' + CAST(@CODMASTROAVEREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVEREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVEREPREC + ''','''','''',' + CAST(@TOTMASTROAVERE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEUROARROT AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                                        SET @INSERITOTOTAVERE = 1
                                        SET @TOTMASTROAVERE = 0
                                        SET @TOTMASTROAVEREEURO = 0
                                        SET @TOTMASTROAVEREEUROARROT = 0
                                    END
                            END
                        ELSE
                            BEGIN               
                                SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVERE + ''',''' + @CONTOAVERE + ''',''' + REPLACE(@DSCCONTOAVERE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                                SET @INSERITOTOTAVERE = 0
                            END
                    END
                ELSE
                    BEGIN               
                        IF @CONTOAVERE <> 'TOTMAST'
                            SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVERE + ''',''' + @CONTOAVERE + ''',''' + REPLACE(@DSCCONTOAVERE,char(39),char(39)+char(39)) + ''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                        ELSE
                            SET @SQL = @SQL + ',' + CAST(@MASTROAVERE AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVERE,CHAR(39),CHAR(39)+CHAR(39)) + ''',''' + @TIPOMASTROAVERE + ''','''','''',' + CAST(@SALDOAVERE AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@SALDOAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                        
                        SET @INSERITOTOTAVERE = 0
                    END
                
            ELSE
                IF @TIPORIDOTTO=0
                    BEGIN
                        IF @INSERITOTOTAVERE = 0   -- INSERISCO IL TOTALE DELL'ULTIMO MASTRO STAMPATO
                            BEGIN
                                IF @TIPOMASTROAVEREPREC IS NULL
                                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                                ELSE
                                    BEGIN                               
                                        SET @SQL = @SQL + ',' + CAST(@CODMASTROAVEREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVEREPREC,char(39),char(39)+char(39)) + ''',''' + @TIPOMASTROAVEREPREC + ''','''','''',' + CAST(@TOTMASTROAVERE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEUROARROT AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                                        SET @INSERITOTOTAVERE = 1
                                        SET @TOTMASTROAVERE = 0
                                        SET @TOTMASTROAVEREEURO = 0
                                        SET @TOTMASTROAVEREEUROARROT = 0
                                    END
                            END
                        ELSE            
                            SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                    END
                ELSE
                    SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                
            SET @SQL = @SQL + ')'
            
            PRINT(@SQL)
            EXEC(@SQL)
            
            IF @TIPORIDOTTO=0
                BEGIN
                    IF @INSERITOTOTDARE = 0 
                        BEGIN
                            SET @TOTMASTRODARE = @TOTMASTRODARE + @SALDODARE
                            SET @TOTMASTRODAREEURO = @TOTMASTRODAREEURO + @SALDODAREEURO
                            SET @TOTMASTRODAREEUROARROT = @TOTMASTRODAREEUROARROT + ROUND(@SALDODAREEURO,0)
                        END 
            
                    IF @INSERITOTOTAVERE = 0 
                        BEGIN
                            SET @TOTMASTROAVERE = @TOTMASTROAVERE + @SALDOAVERE
                            SET @TOTMASTROAVEREEURO = @TOTMASTROAVEREEURO + @SALDOAVEREEURO
                            SET @TOTMASTROAVEREEUROARROT = @TOTMASTROAVEREEUROARROT + ROUND(@SALDOAVEREEURO,0)
                        END
                END
            
            SET @CODMASTRODAREPREC = @MASTRODARE
            SET @DSCMASTRODAREPREC = @DSCMASTRODARE
            SET @TIPOMASTRODAREPREC = @TIPOMASTRODARE
            SET @CODMASTROAVEREPREC = @MASTROAVERE
            SET @DSCMASTROAVEREPREC = @DSCMASTROAVERE
            SET @TIPOMASTROAVEREPREC = @TIPOMASTROAVERE
            
            IF @INSERITOTOTDARE = 0 OR @TIPORIDOTTO<>0
                BEGIN           
                    FETCH NEXT FROM CURSALDIDARE INTO @MASTRODARE,@CONTODARE,@SALDODARE,@SALDODAREEURO,@DSCMASTRODARE,@DSCCONTODARE,@TIPOMASTRODARE
                    SET @FETCHVAL1 = @@FETCH_STATUS
                END
            
            IF @INSERITOTOTAVERE= 0 OR @TIPORIDOTTO<>0
                BEGIN           
                    FETCH NEXT FROM CURSALDIAVERE INTO @MASTROAVERE,@CONTOAVERE,@SALDOAVERE,@SALDOAVEREEURO,@DSCMASTROAVERE,@DSCCONTOAVERE,@TIPOMASTROAVERE
                    SET @FETCHVAL2 = @@FETCH_STATUS
                END
            
            SET @PROGRECORD = @PROGRECORD + 1
        END     

    /* INSERISCO L'EVENTUALE ULTIMO RECORDO CON IL TOTALE DELL'ULTIMO MASTRO LETTO */   
    IF @TIPORIDOTTO=0
        BEGIN
            IF @INSERITOTOTDARE = 0 OR @INSERITOTOTAVERE = 0
                BEGIN
                    SET @SQL = 'INSERT INTO TEMPBILANCIOFISCALE (IDSESSIONE,TIPOFISCALE,PROGRECORD,MASTRODARE,DSCMASTRODARE,TIPOMASTRODARE,CONTODARE,DSCCONTODARE,IMPORTODARE,IMPORTODAREEURO,TOTMASTRODAREEUROARROT,TOTALEDAREECO,TOTALEDAREECOEURO,TOTALEDAREECOEUROARROT,MASTROAVERE,DSCMASTROAVERE,TIPOMASTROAVERE,CONTOAVERE,DSCCONTOAVERE,IMPORTOAVERE,IMPORTOAVEREEURO,TOTMASTROAVEREEUROARROT,TOTALEAVEREECO,TOTALEAVEREECOEURO,TOTALEAVEREECOEUROARROT) VALUES ('
                    SET @SQL = @SQL + CAST(@IDSESSIONE AS NVARCHAR(10)) + ',1,' + CAST(@PROGRECORD AS NVARCHAR(5)) 
                    
                    IF @INSERITOTOTDARE = 0   
                        BEGIN
                            IF @TIPOMASTRODAREPREC IS NULL
                                SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                            ELSE
                                BEGIN                           
                                    SET @SQL = @SQL + ',' + CAST(@CODMASTRODAREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTRODAREPREC,CHAR(39),CHAR(39)+CHAR(39)) + ''',''' + @TIPOMASTRODAREPREC + ''','''','''',' + CAST(@TOTMASTRODARE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTRODAREEUROARROT AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                                    SET @INSERITOTOTDARE = 1
                                    SET @TOTMASTRODARE = 0
                                    SET @TOTMASTRODAREEURO = 0
                                END
                        END
                    ELSE
                        SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEDAREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEDAREECOEUROARROT AS NVARCHAR(23))
                    
                    IF @INSERITOTOTAVERE = 0   
                        BEGIN
                            IF @TIPOMASTROAVEREPREC IS NULL
                                SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                            ELSE
                                BEGIN                           
                                    SET @SQL = @SQL + ',' + CAST(@CODMASTROAVEREPREC AS NVARCHAR(5)) + ',''' + REPLACE(@DSCMASTROAVEREPREC,CHAR(39),CHAR(39)+CHAR(39)) + ''',''' + @TIPOMASTROAVEREPREC + ''','''','''',' + CAST(@TOTMASTROAVERE AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEURO AS NVARCHAR(23)) + ',' + CAST(@TOTMASTROAVEREEUROARROT AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                                    SET @INSERITOTOTAVERE = 1
                                    SET @TOTMASTROAVERE = 0
                                    SET @TOTMASTROAVEREEURO = 0
                                END
                        END
                    ELSE
                        SET @SQL = @SQL + ',0,'''','''','''','''',0,0,0,' + CAST(@TOTALEAVEREECO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEURO AS NVARCHAR(23)) + ',' + CAST(@TOTALEAVEREECOEUROARROT AS NVARCHAR(23))
                    
                    SET @SQL = @SQL + ')'
                    
                    PRINT(@SQL)
                    EXEC(@SQL)
                END
        END

    
    CLOSE CURSALDIDARE
    DEALLOCATE CURSALDIDARE
    
    CLOSE CURSALDIAVERE
    DEALLOCATE CURSALDIAVERE

END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PR_TEMPBILANCIOFISCALE] TO [Metodo98]
    AS [dbo];

