

CREATE PROCEDURE [dbo].[PROC_CREA_PREVISIONI_WINTER]
--ENCRY--
AS

BEGIN

SET NOCOUNT ON
    
    Exec PROC_CREA_OF_WINTER_VERIFICA_ARTICOLI;
    Exec PROC_CREA_OF_WINTER_PREVISIONI_STORICHE;
    Exec PROC_CREA_OF_WINTER_MAD_ARTICOLI;
    Exec PROC_CREA_OF_WINTER_PREVISIONI_FUTURE;

    If @@ERROR <> 0 GoTo ErrorHandler
    Set NoCount OFF
    Return(0)
  
ErrorHandler:
    Return(@@ERROR)

END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_CREA_PREVISIONI_WINTER] TO [Metodo98]
    AS [dbo];

