

CREATE PROCEDURE [dbo].[PROC_CREA_OF_PREVISIONI]
AS

BEGIN

SET NOCOUNT ON

    /*STORICO*/
    EXEC PROC_CREA_OF_PREVISIONI_STORICO;
    
    /*PERIODI*/
    /*CALCOLA PREVISIONI MEDIA MOBILE PONDERATA*/
    EXEC PROC_CREA_PREVISIONI_MEDIAMOBILE;
    
    /*CALCOLA PREVISIONI EXPONENTIAL SMOOTHING*/
    EXEC PROC_CREA_PREVISIONI_EXPONENTIALSMOOTHING;
    
    /*STAGIONALI*/
    /*CALCOLA PREVISIONI WINTERS CON TREND*/
    EXEC PROC_CREA_PREVISIONI_WINTER;
    
    /*CALCOLA PREVISIONI MINIMI QUADRATI*/
    EXEC PROC_CREA_PREVISIONI_MINIMIQUADRATI;

END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_CREA_OF_PREVISIONI] TO [Metodo98]
    AS [dbo];

