

CREATE PROCEDURE dbo.PROC_TRASPORTO_ACQ_CHECK_COSTO_ARTICOLO
AS
DECLARE @COUNTRAGGRUPPA     INT
DECLARE @PROGRESSIVO        DECIMAL(10,0)
    SET @COUNTRAGGRUPPA = 0
    SET @PROGRESSIVO = 0
    
    SELECT @COUNTRAGGRUPPA = COUNT(RAGGRUPPA) FROM TP_TRASPORTOCOSTOACQARTICOLI WHERE RAGGRUPPA = 1
    
    IF (@COUNTRAGGRUPPA = 0)
        BEGIN
            PRINT 'INIZIO CALCOLO'
            
            DECLARE PERIODI_CUR CURSOR FAST_FORWARD FOR
                SELECT TP_TRASPORTOACQ.PROGRESSIVO FROM TP_TRASPORTOACQ 
            OPEN PERIODI_CUR    
                FETCH NEXT FROM PERIODI_CUR
                    INTO @PROGRESSIVO
                WHILE @@FETCH_STATUS = 0
                    BEGIN
                        EXEC PROC_TRASPORTO_ACQ_COSTO_ARTICOLO @PROGRESSIVO
                    END
                    FETCH NEXT FROM PERIODI_CUR
                    INTO @PROGRESSIVO
            CLOSE PERIODI_CUR
            DEALLOCATE PERIODI_CUR
            
            PRINT 'FINE CALCOLO'
        END
    ELSE
        BEGIN
            PRINT 'CALCOLI GIA EFFETTUATI'
        END
        

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_TRASPORTO_ACQ_CHECK_COSTO_ARTICOLO] TO [Metodo98]
    AS [dbo];

