CREATE PROCEDURE SP_TEMPPARTITARI(@strW NVARCHAR(1000), @DataIniz VARCHAR(20), @Esercizio SMALLINT, @NTerm SMALLINT) AS
BEGIN
  DECLARE @SQL NVARCHAR(2000) 
  DECLARE @TIPOSI SMALLINT
    
  DELETE FROM TEMPPARTITARICONT WHERE NRTERMINALE=@NTerm
  
  /* DETERMINO IL TIPO DI SALDOINIZIALE */
  DECLARE CURCONT CURSOR FOR
  SELECT Progressivo FROM TesteContabilita WHERE Causale=(SELECT CausContAP FROM TabVincoliGIC WHERE Esercizio=@Esercizio) AND Esercizio=@Esercizio
  OPEN CURCONT
  
  FETCH NEXT FROM CURCONT 
  
  IF @@FETCH_STATUS = 0
     SET @TIPOSI=1
  ELSE
     BEGIN
        CLOSE CURCONT
	DEALLOCATE CURCONT
  
        DECLARE CURCONT CURSOR FOR
        SELECT Progressivo FROM TesteContabilita WHERE Causale=(SELECT CausContCH FROM TabVincoliGIC WHERE Esercizio=@Esercizio) AND Esercizio=@Esercizio-1
	OPEN CURCONT
  
	FETCH NEXT FROM CURCONT 
  
  	IF @@FETCH_STATUS = 0
  	   SET @TIPOSI=2
  	ELSE
  	   SET @TIPOSI=3
     END
     
  IF @TIPOSI<>1
     CLOSE CURCONT
     
  DEALLOCATE CURCONT

  DECLARE @NOMEVISTA NVARCHAR(20)
  
  SET @NOMEVISTA='VISTAPARTITARIPN' + CAST(@TIPOSI AS NVARCHAR(1))
  SET @SQL = 'INSERT INTO TEMPPARTITARICONT (CONTO,DAREPREC,DAREPRECEURO,DAREPRECVALUTA,AVEREPREC,AVEREPRECEURO,AVEREPRECVALUTA,NRTERMINALE) '
  SET @SQL = @SQL + 'SELECT CONTO,SUM(DARE),SUM(DAREEURO),SUM(DAREVALUTA),SUM(AVERE),SUM(AVEREEURO),SUM(AVEREVALUTA),' + CAST(@NTerm AS NVARCHAR(5)) + ' FROM ' + @NOMEVISTA + ' VISTAPARTITARIPN WHERE ' + @strW
  SET @SQL = @SQL + ' AND (PROGRESSIVO=0 OR DATAREG<''' + CAST(YEAR(@DataIniz) AS NVarchar(4))+ '-' + RIGHT('00'+CAST(Day(@DataIniz) AS NVarchar(2)),2) + '-' + RIGHT('00'+CAST(Month(@DataIniz) AS NVarchar(2)),2) + ''') GROUP BY CONTO'
  EXEC(@SQL)

  /*Inserisco nel temporaneo gli eventuali conti che non hanno periodo precedente altrimenti in stampa non si vedono */
  SET @SQL = 'INSERT INTO TEMPPARTITARICONT (CONTO,DAREPREC,DAREPRECEURO,DAREPRECVALUTA,AVEREPREC,AVEREPRECEURO,AVEREPRECVALUTA,NRTERMINALE) '
  SET @SQL = @SQL + 'SELECT CONTO,0,0,0,0,0,0,' + CAST(@NTerm AS NVARCHAR(5)) + ' FROM ' + @NOMEVISTA + ' VISTAPARTITARIPN WHERE ' + @strW
  SET @SQL = @SQL + ' AND CONTO NOT IN (SELECT CONTO FROM TEMPPARTITARICONT WHERE NRTERMINALE=' + CAST(@NTerm AS NVARCHAR(5)) + ') GROUP BY CONTO'
  EXEC(@SQL)
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SP_TEMPPARTITARI] TO [Metodo98]
    AS [dbo];

