

CREATE PROCEDURE TP_NUOVONRRIGA(@PTABELLA VARCHAR(80),@PPROG DECIMAL(10),@PNRRIGA INT OUTPUT) AS

    BEGIN
        DECLARE @R TABLE (PNR INT);

        MERGE INTO
            TP_TABPROGRNRRIGA T
        USING
            (SELECT @PTABELLA AS NOMETABELLA, @PPROG AS PROGR) AS S
        ON
            T.NOMETABELLA = S.NOMETABELLA AND T.PROGR = S.PROGR
        WHEN
            NOT MATCHED THEN INSERT (NOMETABELLA, PROGR, NRRIGA) VALUES (@PTABELLA, @PPROG, 1)
        WHEN
            MATCHED THEN UPDATE SET NRRIGA = NRRIGA + 1
        OUTPUT 
            INSERTED.NRRIGA INTO @R;

        SELECT TOP 1 @PNRRIGA  = PNR  FROM @R;
    END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[TP_NUOVONRRIGA] TO [Metodo98]
    AS [dbo];

