CREATE TABLE [dbo].[MB_ACQUISTATO_DEPOSITI] (
    [CODDEPOSITO]     VARCHAR (10) NOT NULL,
    [CODDEPOSITOCOLL] VARCHAR (10) NOT NULL,
    [UtenteModifica]  VARCHAR (25) NOT NULL,
    [DataModifica]    DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODDEPOSITO] ASC, [CODDEPOSITOCOLL] ASC),
    CONSTRAINT [FK_MB_ACQUISTATO_DEPOSITI_DEPOSITO] FOREIGN KEY ([CODDEPOSITO]) REFERENCES [dbo].[ANAGRAFICADEPOSITI] ([CODICE]),
    CONSTRAINT [FK_MB_ACQUISTATO_DEPOSITI_DEPOSITOCOLL] FOREIGN KEY ([CODDEPOSITOCOLL]) REFERENCES [dbo].[ANAGRAFICADEPOSITI] ([CODICE])
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MB_ACQUISTATO_DEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MB_ACQUISTATO_DEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MB_ACQUISTATO_DEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MB_ACQUISTATO_DEPOSITI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MB_ACQUISTATO_DEPOSITI] TO [Metodo98]
    AS [dbo];

