CREATE TABLE [dbo].[MOVIMENTIELENCOCLIFOR] (
    [PROGRESSIVO]       DECIMAL (10)    NOT NULL,
    [NRRIGA]            INT             NOT NULL,
    [NRREG]             DECIMAL (10)    NULL,
    [TIPOAC]            VARCHAR (1)     NOT NULL,
    [CODCLIFOR]         VARCHAR (7)     NOT NULL,
    [DATAREG]           DATETIME        NULL,
    [ANNO]              SMALLINT        NULL,
    [IMPONIBILEEURO]    DECIMAL (19, 4) NULL,
    [IMPOSTAEURO]       DECIMAL (19, 4) NULL,
    [FLGCORRISPETTIVO]  SMALLINT        NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [MODPAGAMENTO]      SMALLINT        NULL,
    [NUMFATTURA]        VARCHAR (15)    NULL,
    [FLGNOTAVARIAZIONE] SMALLINT        NULL,
    [NUMFATTNOTAVAR]    VARCHAR (15)    NULL,
    [DATAFATTNOTAVAR]   DATETIME        NULL,
    [IMPONIBVARIAZ]     DECIMAL (19, 4) CONSTRAINT [DF_MOVIMENTIELENCOCLIFOR_IMPONIBVARIAZ] DEFAULT ((0)) NULL,
    [IMPOSTAVARIAZ]     DECIMAL (19, 4) CONSTRAINT [DF_MOVIMENTIELENCOCLIFOR_IMPOSTAVARIAZ] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_MOVIMENTIELENCOCLIFOR] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC, [NRRIGA] ASC),
    CONSTRAINT [CHK_MOVIMENTIELENCOCLIFOR_FLGCORRISPETTIVO] CHECK ([FLGCORRISPETTIVO]=(1) OR [FLGCORRISPETTIVO]=(0)),
    CONSTRAINT [CHK_MOVIMENTIELENCOCLIFOR_FLGNOTAVARIAZIONE] CHECK ([FLGNOTAVARIAZIONE]=(1) OR [FLGNOTAVARIAZIONE]=(0)),
    CONSTRAINT [CHK_MOVIMENTIELENCOCLIFOR_MODPAGAMENTO] CHECK ([MODPAGAMENTO]=(2) OR [MODPAGAMENTO]=(1) OR [MODPAGAMENTO]=(0))
);


GO
CREATE NONCLUSTERED INDEX [MOVIMENTIELENCOCLIFOR_ANNO]
    ON [dbo].[MOVIMENTIELENCOCLIFOR]([ANNO] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MOVIMENTIELENCOCLIFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MOVIMENTIELENCOCLIFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MOVIMENTIELENCOCLIFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MOVIMENTIELENCOCLIFOR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MOVIMENTIELENCOCLIFOR] TO [Metodo98]
    AS [dbo];

