CREATE TABLE [dbo].[MPSLOGATTIVITA] (
    [PROGRESSIVO]     DECIMAL (10)    NOT NULL,
    [RIFTESTAPIANO]   DECIMAL (10)    NULL,
    [RIFRIGAFORECAST] INT             NULL,
    [RIFRIGAPIANO]    INT             NULL,
    [RIFTESTADOC]     DECIMAL (10)    NULL,
    [RIFRIGADOC]      INT             NULL,
    [OPERAZIONE]      SMALLINT        NULL,
    [FLAGESITO]       SMALLINT        NULL,
    [MESSAGGIO]       VARCHAR (255)   NULL,
    [QUANTITA]        DECIMAL (16, 6) NULL,
    [UM]              VARCHAR (3)     NULL,
    [ARTICOLO]        VARCHAR (50)    NULL,
    [DATACONSEGNA]    DATETIME        NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    CONSTRAINT [PK_MPSLOGATTIVITA] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[MPSLOGATTIVITA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MPSLOGATTIVITA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[MPSLOGATTIVITA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MPSLOGATTIVITA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MPSLOGATTIVITA] TO [Metodo98]
    AS [dbo];

