CREATE TABLE [dbo].[PARAMETRICOMMPROD] (
    [CODICE]                   VARCHAR (3)   NOT NULL,
    [DESCRIZIONE]              VARCHAR (80)  NULL,
    [CODICETAPPO]              DECIMAL (5)   NULL,
    [CONTATORELOTTI]           DECIMAL (5)   NULL,
    [CONTATOREMATRICOLE]       DECIMAL (5)   NULL,
    [TIPORIGAORDINI]           VARCHAR (3)   NULL,
    [TIPORIGAIMPEGNI]          VARCHAR (3)   NULL,
    [TIPOPIEDECOMMESSA]        VARCHAR (3)   NULL,
    [FLAGCOLLEGAMENTI]         SMALLINT      DEFAULT (0) NULL,
    [FILTRODOCUMENTI]          VARCHAR (50)  NULL,
    [FILTROPIANO]              VARCHAR (50)  NULL,
    [FILTROARTSCORTA]          VARCHAR (50)  NULL,
    [TIPOORDPRODUZIONE]        VARCHAR (3)   NULL,
    [TIPOORDINECLATTIVO]       VARCHAR (3)   NULL,
    [TIPOORDINECLPASSIVO]      VARCHAR (3)   NULL,
    [ANNOTAZIONI]              VARCHAR (255) NULL,
    [DATAMODIFICA]             DATETIME      NOT NULL,
    [UTENTEMODIFICA]           VARCHAR (25)  NOT NULL,
    [ASSEGNAMATRICOLE]         SMALLINT      DEFAULT (0) NULL,
    [PREFISSOMATRICOLE]        VARCHAR (5)   NULL,
    [SUFFISSOMATRICOLE]        VARCHAR (5)   NULL,
    [FLAGGESTIONECICLI]        SMALLINT      DEFAULT (0) NULL,
    [FLAGQTAVARIANTE]          SMALLINT      DEFAULT (0) NULL,
    [TIPOORDINETRASFORMAZIONE] VARCHAR (7)   NULL,
    CONSTRAINT [PK_PARAMETRICOMMPROD] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_FLAGCOLLEGAMENTI_PARAMETR] CHECK ([FLAGCOLLEGAMENTI] = 0 or [FLAGCOLLEGAMENTI] = 1)
);


GO

/*  UPDATE TRIGGER "TU_PARAMETRICOMMPROD" FOR TABLE "PARAMETRICOMMPROD"  */
CREATE TRIGGER TU_PARAMETRICOMMPROD ON PARAMETRICOMMPROD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  ALTER COLUMN PARENT CODE OF "PARAMETRICOMMPROD" FOR ALL CHILDREN IN "TABORDINICOMMESSA"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TABORDINICOMMESSA
          SET   CODCOMMESSA = I1.CODICE
         FROM   TABORDINICOMMESSA T2, INSERTED I1, DELETED D1
         WHERE  T2.CODCOMMESSA = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "PARAMETRICOMMPROD" FOR ALL CHILDREN IN "ACCESSICOMMESSEPROD"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE ACCESSICOMMESSEPROD
          SET   CODCOMMESSA = I1.CODICE
         FROM   ACCESSICOMMESSEPROD T2, INSERTED I1, DELETED D1
         WHERE  T2.CODCOMMESSA = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "PARAMETRICOMMPROD" FOR ALL CHILDREN IN "TESTEORDINIPROD"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TESTEORDINIPROD
          SET   TIPOCOM = I1.CODICE
         FROM   TESTEORDINIPROD T2, INSERTED I1, DELETED D1
         WHERE  T2.TIPOCOM = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_PARAMETRICOMMPROD" FOR TABLE "PARAMETRICOMMPROD"  */
CREATE TRIGGER TD_PARAMETRICOMMPROD ON PARAMETRICOMMPROD FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "TABORDINICOMMESSA"  */
    DELETE TABORDINICOMMESSA
    FROM   TABORDINICOMMESSA T2, DELETED T1
    WHERE  T2.CODCOMMESSA = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "ACCESSICOMMESSEPROD"  */
    DELETE ACCESSICOMMESSEPROD
    FROM   ACCESSICOMMESSEPROD T2, DELETED T1
    WHERE  T2.CODCOMMESSA = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "TESTEORDINIPROD"  */
    DELETE TESTEORDINIPROD
    FROM   TESTEORDINIPROD T2, DELETED T1
    WHERE  T2.TIPOCOM = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[PARAMETRICOMMPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARAMETRICOMMPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARAMETRICOMMPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARAMETRICOMMPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARAMETRICOMMPROD] TO [Metodo98]
    AS [dbo];

