CREATE TABLE [dbo].[PARDOCVF] (
    [CODDOC]         VARCHAR (3)  NOT NULL,
    [CODSPESA]       SMALLINT     NOT NULL,
    [CODGENERICO]    VARCHAR (7)  NULL,
    [CODCAUSALE]     DECIMAL (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_PARDOCVF] PRIMARY KEY CLUSTERED ([CODDOC] ASC, [CODSPESA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PARDOCVF_CODDOC] FOREIGN KEY ([CODDOC]) REFERENCES [dbo].[PARAMETRIDOC] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [PARDOCVFGEN]
    ON [dbo].[PARDOCVF]([CODGENERICO] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PARDOCVF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PARDOCVF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PARDOCVF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PARDOCVF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PARDOCVF] TO [Metodo98]
    AS [dbo];

