CREATE TABLE [dbo].[PREZZIPARTICOLARI_XML_COMPLETO] (
    [IDREGOLA]          DECIMAL (18)    IDENTITY (1, 1) NOT NULL,
    [PROGRESSIVOREGOLA] DECIMAL (18)    NOT NULL,
    [TIPOREGOLA]        SMALLINT        NOT NULL,
    [CODCLIFOR]         VARCHAR (7)     NOT NULL,
    [CODART]            VARCHAR (50)    NOT NULL,
    [UM]                VARCHAR (3)     NOT NULL,
    [QTA]               DECIMAL (16, 6) NOT NULL,
    [PREZZO]            DECIMAL (19, 6) NOT NULL,
    [SCONTO]            VARCHAR (255)   NOT NULL,
    [INIZIOVALIDITA]    DATETIME        NOT NULL,
    [FINEVALIDITA]      DATETIME        NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [TIPO]              SMALLINT        DEFAULT ((0)) NULL,
    [SCONTIESTESIXML]   VARCHAR (1000)  DEFAULT ('') NOT NULL,
    [TipoPrezzo]        BIT             DEFAULT ((0)) NOT NULL,
    [Destinazione]      DECIMAL (5)     DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([IDREGOLA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PREZZIPARTICOLARI_XML_COMPLETO]
    ON [dbo].[PREZZIPARTICOLARI_XML_COMPLETO]([PROGRESSIVOREGOLA] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PREZZIPARTICOLARI_XML_COMPLETO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PREZZIPARTICOLARI_XML_COMPLETO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PREZZIPARTICOLARI_XML_COMPLETO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PREZZIPARTICOLARI_XML_COMPLETO] TO [Metodo98]
    AS [dbo];

