CREATE TABLE [dbo].[PROFILOORARIOSTANDARD] (
    [CODICE]         VARCHAR (25)   NOT NULL,
    [TIPOPO]         SMALLINT       DEFAULT (0) NOT NULL,
    [ORELAV]         NUMERIC (6, 4) DEFAULT (0) NULL,
    [DAORA1T]        DATETIME       NULL,
    [AORA1T]         DATETIME       NULL,
    [SOSTA1T]        DATETIME       NULL,
    [DAORA2T]        DATETIME       NULL,
    [AORA2T]         DATETIME       NULL,
    [SOSTA2T]        DATETIME       NULL,
    [DAORA3T]        DATETIME       NULL,
    [AORA3T]         DATETIME       NULL,
    [SOSTA3T]        DATETIME       NULL,
    [DAORA4T]        DATETIME       NULL,
    [AORA4T]         DATETIME       NULL,
    [SOSTA4T]        DATETIME       NULL,
    [UTENTEMODIFICA] VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]   DATETIME       NOT NULL,
    CONSTRAINT [PK_PROFILOORARIOSTANDARD] PRIMARY KEY CLUSTERED ([CODICE] ASC, [TIPOPO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOPO_PROFILO] CHECK ([TIPOPO] = 4 or [TIPOPO] = 3 or [TIPOPO] = 2 or [TIPOPO] = 1 or [TIPOPO] = 0)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PROFILOORARIOSTANDARD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PROFILOORARIOSTANDARD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PROFILOORARIOSTANDARD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PROFILOORARIOSTANDARD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PROFILOORARIOSTANDARD] TO [Metodo98]
    AS [dbo];

