CREATE TABLE [dbo].[PROMOZIONI_FAMREP] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [NRRIGA]         INT          NOT NULL,
    [FLAGRIGA]       SMALLINT     NULL,
    [POSIZIONE]      INT          NULL,
    [FAMIGLIA]       DECIMAL (5)  NULL,
    [REPARTO]        DECIMAL (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NRRIGA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[PROMOZIONI_FAMREP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[PROMOZIONI_FAMREP] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[PROMOZIONI_FAMREP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PROMOZIONI_FAMREP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PROMOZIONI_FAMREP] TO [Metodo98]
    AS [dbo];

