CREATE TABLE [dbo].[RELAZIONIPCF] (
    [CODCLIFOR]      VARCHAR (7)  NOT NULL,
    [ARTICOLO]       VARCHAR (50) NOT NULL,
    [VARIANTI]       VARCHAR (50) CONSTRAINT [DF_RELAZIONIPCF_VARIANTI] DEFAULT ('') NOT NULL,
    [TIPOEDI]        SMALLINT     CONSTRAINT [DF_RELAZIONIPCF_TIPOEDI] DEFAULT ((0)) NULL,
    [RIFERIMENTOEDI] VARCHAR (50) NOT NULL,
    [TIPOASS]        SMALLINT     CONSTRAINT [DF_RELAZIONIPCF_TIPOASS] DEFAULT ((0)) NULL,
    [RIFERIMENTOASS] VARCHAR (50) NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_RELAZIONIPCF] PRIMARY KEY CLUSTERED ([CODCLIFOR] ASC, [ARTICOLO] ASC, [VARIANTI] ASC),
    CONSTRAINT [CKC_RELAZIONOPCF_TIPOASS] CHECK ([TIPOASS]=(0) OR [TIPOASS]=(1)),
    CONSTRAINT [CKC_RELAZIONOPCF_TIPOEDI] CHECK ([TIPOEDI]=(0) OR [TIPOEDI]=(1))
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RELAZIONIPCF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RELAZIONIPCF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RELAZIONIPCF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RELAZIONIPCF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RELAZIONIPCF] TO [Metodo98]
    AS [dbo];

