CREATE TABLE [dbo].[RIFCONFRDCONFAZ] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [CODDOCUMENTO]   VARCHAR (3)  NOT NULL,
    [RIFPROGRCONFRD] DECIMAL (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_RIFCONFRDCONFAZ] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [CODDOCUMENTO] ASC),
    CONSTRAINT [FK_RIFCONFRDCONFAZ_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTECONFAZ] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIFCONFRDCONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIFCONFRDCONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIFCONFRDCONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIFCONFRDCONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIFCONFRDCONFAZ] TO [Metodo98]
    AS [dbo];

