CREATE TABLE [dbo].[RIGHECOSTISPEDIZIONE] (
    [CODSPED]           DECIMAL (5)     NOT NULL,
    [NUMERORIGA]        INT             NOT NULL,
    [POSIZIONE]         INT             NOT NULL,
    [PROVINCIA]         VARCHAR (10)    NULL,
    [DAPESO]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [APESO]             DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [PREZZOKG]          DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [PREZZOKGEURO]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SPINOLTRO]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SPINOLTROEURO]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SPVARIE]           DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SPVARIEEURO]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [ARROTONDA]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [NOTE]              VARCHAR (255)   NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [PRCTOTMERCE]       DECIMAL (8, 5)  CONSTRAINT [DF_RIGHECOSTISPEDIZIONE_PRCTOTMERCE] DEFAULT (0) NULL,
    [INOLTROUNITKG]     DECIMAL (19, 6) CONSTRAINT [DF_RIGHECOSTISPEDIZIONE_INOLTROUNITKG] DEFAULT (0) NULL,
    [INOLTROUNITKGEURO] DECIMAL (19, 6) CONSTRAINT [DF_RIGHECOSTISPEDIZIONE_INOLTROUNITKGEURO] DEFAULT (0) NULL,
    CONSTRAINT [PK_RIGHECOSTISPEDIZIONE] PRIMARY KEY CLUSTERED ([CODSPED] ASC, [NUMERORIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RIGHECOSTISPEDIZIONE_CODSPED] FOREIGN KEY ([CODSPED]) REFERENCES [dbo].[TESTACOSTISPEDIZIONE] ([SPEDIZIONIERE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [RCSED_POS]
    ON [dbo].[RIGHECOSTISPEDIZIONE]([CODSPED] ASC, [POSIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHECOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHECOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHECOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHECOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHECOSTISPEDIZIONE] TO [Metodo98]
    AS [dbo];

