CREATE TABLE [dbo].[RIGHECONTABILITA] (
    [NRREG]          DECIMAL (10)    NOT NULL,
    [ESERCIZIO]      DECIMAL (5)     NOT NULL,
    [NRRIGA]         SMALLINT        NOT NULL,
    [POSIZIONE]      SMALLINT        NOT NULL,
    [DATAREG]        DATETIME        NULL,
    [DATARIF]        DATETIME        NULL,
    [NRRIF]          VARCHAR (15)    NULL,
    [NRPARTITA]      VARCHAR (19)    NULL,
    [CONTO]          VARCHAR (7)     NULL,
    [SEGNO]          SMALLINT        DEFAULT (0) NULL,
    [IMPORTO]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPORTOVALUTA]  DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPORTOEURO]    DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [CODCAMBIO]      DECIMAL (5)     NULL,
    [VALORECAMBIO]   DECIMAL (13, 6) DEFAULT (1) NOT NULL,
    [DESCRIZIONE]    VARCHAR (80)    NULL,
    [DATAVALUTA]     DATETIME        NULL,
    [CPARTITA]       VARCHAR (7)     NULL,
    [RIGACAUSALE]    SMALLINT        NULL,
    [CODCOMMESSA]    VARCHAR (30)    NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHECONTABILITA] PRIMARY KEY CLUSTERED ([NRREG] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_SEGNO_RIGHECON] CHECK ([SEGNO] = 0 or [SEGNO] = 1),
    CONSTRAINT [FK_RIGHECONTABILITA_NRREG] FOREIGN KEY ([NRREG]) REFERENCES [dbo].[TESTECONTABILITA] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [RGC_CONTO]
    ON [dbo].[RIGHECONTABILITA]([CONTO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_CPARTITA]
    ON [dbo].[RIGHECONTABILITA]([CPARTITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_DATAREG]
    ON [dbo].[RIGHECONTABILITA]([DATAREG] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_DATAVALUTA]
    ON [dbo].[RIGHECONTABILITA]([DATAVALUTA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_NRPARTITA]
    ON [dbo].[RIGHECONTABILITA]([NRPARTITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_NRREG]
    ON [dbo].[RIGHECONTABILITA]([NRREG] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_SPARTITA]
    ON [dbo].[RIGHECONTABILITA]([CONTO] ASC, [NRPARTITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RGC_ESERCIZIO]
    ON [dbo].[RIGHECONTABILITA]([ESERCIZIO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [righecontabilita0]
    ON [dbo].[RIGHECONTABILITA]([CONTO] ASC, [NRREG] ASC, [SEGNO] ASC, [IMPORTO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [righecontabilita00]
    ON [dbo].[RIGHECONTABILITA]([ESERCIZIO] ASC, [NRREG] ASC, [CONTO] ASC, [SEGNO] ASC, [IMPORTO] ASC, [IMPORTOVALUTA] ASC, [IMPORTOEURO] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHECONTABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHECONTABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHECONTABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHECONTABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHECONTABILITA] TO [Metodo98]
    AS [dbo];

