CREATE TABLE [dbo].[RIGHESTRUTTURACOMMCLI] (
    [RIFPROGRESSIVO] DECIMAL (10)  NOT NULL,
    [NRRIGA]         DECIMAL (5)   NOT NULL,
    [POSIZIONE]      DECIMAL (5)   NOT NULL,
    [FLAGRIGA]       SMALLINT      NULL,
    [LIV1]           VARCHAR (25)  NULL,
    [LIV2]           VARCHAR (25)  NULL,
    [LIV3]           VARCHAR (25)  NULL,
    [LIV4]           VARCHAR (25)  NULL,
    [DESCRIZIONE]    VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_RIGHESTRUTTURACOMMCLI] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHESTRUTTURACOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHESTRUTTURACOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHESTRUTTURACOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHESTRUTTURACOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHESTRUTTURACOMMCLI] TO [Metodo98]
    AS [dbo];

