CREATE TABLE [dbo].[RIGHEIMPOSTAZIONIVISIONI] (
    [RIFPROGRESSIVO] DECIMAL (10)  NOT NULL,
    [TIPOCAMPO]      SMALLINT      NOT NULL,
    [ID]             SMALLINT      NOT NULL,
    [NOMECAMPO]      VARCHAR (100) NULL,
    [DATICONTESTO]   SMALLINT      NULL,
    [PROGRPARZ]      SMALLINT      NULL,
    [PROGRTOT]       SMALLINT      NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [VISTOTALE]      SMALLINT      NULL,
    [COLORETOTALE]   INT           NULL,
    CONSTRAINT [PK_RIGHEIMPOSTAZIONIVISIONI] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [TIPOCAMPO] ASC, [ID] ASC),
    CONSTRAINT [FK_RIGHEIMPOSTAZIONIVISIONI_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTEIMPOSTAZIONIVISIONI] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEIMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];

