CREATE TABLE [dbo].[RIGHEPACKINGLIST] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [NRRIGA]         INT             NOT NULL,
    [CODIMBALLO]     VARCHAR (10)    NULL,
    [NUMIMBALLI]     INT             NULL,
    [VOLUME]         DECIMAL (16, 6) CONSTRAINT [DF_RIGHEPACKINGLIST_VOLUME] DEFAULT (0) NULL,
    [POSIZIONE]      INT             NULL,
    [FLAGRIGA]       SMALLINT        NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHEPACKINGLIST] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEPACKINGLIST] TO [Metodo98]
    AS [dbo];

