CREATE TABLE [dbo].[RIGHELSTMOVMATRICOLE] (
    [IDTESTA]        DECIMAL (10) NOT NULL,
    [IDRIGA]         INT          NOT NULL,
    [CODMATRICOLA]   VARCHAR (30) NOT NULL,
    [DATAMODIFICA]   DATETIME     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NULL,
    PRIMARY KEY CLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC, [CODMATRICOLA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHELSTMOVMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHELSTMOVMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHELSTMOVMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHELSTMOVMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHELSTMOVMATRICOLE] TO [Metodo98]
    AS [dbo];

