CREATE TABLE [dbo].[RIGHEDOCUMENTI_BUDGET] (
    [PROGRESSIVO]     DECIMAL (18)    IDENTITY (1, 1) NOT NULL,
    [IDTESTA]         DECIMAL (10)    NOT NULL,
    [IDRIGA]          INT             NOT NULL,
    [Trasporto]       XML             NULL,
    [Contratti]       XML             NULL,
    [Sconti]          XML             NULL,
    [TOTPROVVAGEURO1] DECIMAL (19, 6) NULL,
    [TOTPROVVAGEURO2] DECIMAL (19, 6) NULL,
    [TOTPROVVAGEURO3] DECIMAL (19, 6) NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO
CREATE PRIMARY XML INDEX [IDX_CONTRATTI_PRIMARY]
    ON [dbo].[RIGHEDOCUMENTI_BUDGET]([Contratti])
    WITH (PAD_INDEX = OFF);


GO
CREATE PRIMARY XML INDEX [IDX_TRASPORTI_PRIMARY]
    ON [dbo].[RIGHEDOCUMENTI_BUDGET]([Trasporto])
    WITH (PAD_INDEX = OFF);


GO
CREATE XML INDEX [IDX_CONTRATTI_PATH]
    ON [dbo].[RIGHEDOCUMENTI_BUDGET]([Contratti])
    USING XML INDEX [IDX_CONTRATTI_PRIMARY] FOR PATH
    WITH (PAD_INDEX = OFF);


GO
CREATE XML INDEX [IDX_CONTRATTI_VALUES]
    ON [dbo].[RIGHEDOCUMENTI_BUDGET]([Contratti])
    USING XML INDEX [IDX_CONTRATTI_PRIMARY] FOR VALUE
    WITH (PAD_INDEX = OFF);


GO
CREATE XML INDEX [IDX_TRASPORTI_PATH]
    ON [dbo].[RIGHEDOCUMENTI_BUDGET]([Trasporto])
    USING XML INDEX [IDX_TRASPORTI_PRIMARY] FOR PATH
    WITH (PAD_INDEX = OFF);


GO
CREATE XML INDEX [IDX_TRASPORTI_VALUES]
    ON [dbo].[RIGHEDOCUMENTI_BUDGET]([Trasporto])
    USING XML INDEX [IDX_TRASPORTI_PRIMARY] FOR VALUE
    WITH (PAD_INDEX = OFF);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEDOCUMENTI_BUDGET] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEDOCUMENTI_BUDGET] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEDOCUMENTI_BUDGET] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEDOCUMENTI_BUDGET] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEDOCUMENTI_BUDGET] TO [Metodo98]
    AS [dbo];

