CREATE TABLE [dbo].[RIGHEIVADATIFATTURA] (
    [IDTESTA]        DECIMAL (10)    NOT NULL,
    [IDRIGA]         INT             NOT NULL,
    [CODIVA]         DECIMAL (5)     DEFAULT ((0)) NULL,
    [IMPONIBILEEURO] DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [IMPOSTAEURO]    DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHEIVADATIFATTURA] PRIMARY KEY CLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC),
    CONSTRAINT [FK_RIGHEIVADATIFATTURA_PROGRESSIVO] FOREIGN KEY ([IDTESTA]) REFERENCES [dbo].[TESTEDATIFATTURA] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEIVADATIFATTURA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEIVADATIFATTURA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEIVADATIFATTURA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEIVADATIFATTURA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEIVADATIFATTURA] TO [Metodo98]
    AS [dbo];

