CREATE TABLE [dbo].[RIGHEFORECAST] (
    [RIFPROGRESSIVO]  DECIMAL (10)    NOT NULL,
    [NUMERORIGA]      INT             NOT NULL,
    [POSIZIONE]       INT             NOT NULL,
    [ARTICOLO]        VARCHAR (50)    NOT NULL,
    [VERSIONEDBA]     VARCHAR (10)    NULL,
    [TIPOPERIODO]     SMALLINT        NULL,
    [UM]              VARCHAR (3)     NOT NULL,
    [QTAPREVISTA]     DECIMAL (16, 6) NULL,
    [TOTPREVISTO]     DECIMAL (16, 6) NULL,
    [TOTIMPEGNATO]    DECIMAL (16, 6) NULL,
    [FLAGGENERATOMPS] SMALLINT        NULL,
    [FLAGRIGA]        SMALLINT        NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    CONSTRAINT [PK_RIGHEFORECAST] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NUMERORIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/* DELETE TRIGGER "TD_RIGHEFORECAST" FOR TABLE "RIGHEFORECAST" */
CREATE TRIGGER TD_RIGHEFORECAST ON RIGHEFORECAST FOR DELETE AS
BEGIN

DECLARE
@NUMROWS INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* DELETE CASCADE */   /* per OGNI Tabella CHILD in Relazione */
/* DELETE ALL CHILDREN IN "Nome Tabella Child" */
DELETE RIGHEMPS
FROM RIGHEMPS T2, DELETED T1
WHERE T2.RIFPROGRESSIVO = T1.RIFPROGRESSIVO
AND T2.RIFRIGAFORECAST = T1.NUMERORIGA


DELETE RIGHEMPP
FROM RIGHEMPP T2, DELETED T1
WHERE T2.RIFPROGRESSIVO = T1.RIFPROGRESSIVO
AND T2.RIFRIGAFORECAST = T1.NUMERORIGA


RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHEFORECAST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHEFORECAST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHEFORECAST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHEFORECAST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHEFORECAST] TO [Metodo98]
    AS [dbo];

