CREATE TABLE [dbo].[RIGHELISTACONS] (
    [IDTESTA]            DECIMAL (10)    NOT NULL,
    [IDRIGA]             INT             NOT NULL,
    [POSIZIONE]          INT             NULL,
    [FLAGRIGA]           SMALLINT        CONSTRAINT [DF_RIGHELISTACONS_FLAGRIGA] DEFAULT (0) NULL,
    [RIFMOVIMENTO]       DECIMAL (10)    CONSTRAINT [DF_RIGHELISTACONS_RIFMOVIMENTO] DEFAULT (0) NULL,
    [DATAMOV]            DATETIME        NULL,
    [CODCAUSALE]         NUMERIC (5)     NOT NULL,
    [ANNOBOLLA]          SMALLINT        NOT NULL,
    [NUMEROBOLLA]        INT             NOT NULL,
    [TIPOBOLLA]          SMALLINT        CONSTRAINT [DF_RIGHELISTACONS_TIPOBOLLA] DEFAULT (0) NOT NULL,
    [CDLAVORO]           VARCHAR (5)     NULL,
    [MACCHINA]           VARCHAR (5)     NULL,
    [DATAINIZIOSETUP]    DATETIME        NULL,
    [ORAINIZIOSETUP]     DATETIME        NULL,
    [DATAFINESETUP]      DATETIME        NULL,
    [ORAFINESETUP]       DATETIME        NULL,
    [ORESETUP]           DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_ORESETUP] DEFAULT (0) NULL,
    [DATAINIZIOMACCHINA] DATETIME        NULL,
    [ORAINIZIOMACCHINA]  DATETIME        NULL,
    [DATAFINEMACCHINA]   DATETIME        NULL,
    [ORAFINEMACCHINA]    DATETIME        NULL,
    [OREMACCHINA]        DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_OREMACCHINA] DEFAULT (0) NULL,
    [DATAINIZIOUOMO]     DATETIME        NULL,
    [ORAINIZIOUOMO]      DATETIME        NULL,
    [DATAFINEUOMO]       DATETIME        NULL,
    [ORAFINEUOMO]        DATETIME        NULL,
    [OREUOMO]            DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_OREUOMO] DEFAULT (0) NULL,
    [DATAINIZIODURATA]   DATETIME        NULL,
    [ORAINIZIODURATA]    DATETIME        NULL,
    [DATAFINEDURATA]     DATETIME        NULL,
    [ORAFINEDURATA]      DATETIME        NULL,
    [OREDURATA]          DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_OREDURATA] DEFAULT (0) NULL,
    [DATAINIZIOMOVNE]    DATETIME        NULL,
    [ORAINIZIOMOVNE]     DATETIME        NULL,
    [DATAFINEMOVNE]      DATETIME        NULL,
    [ORAFINEMOVNE]       DATETIME        NULL,
    [OREMOVIMENTAZIONE]  DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_OREMOVIMENTAZIONE] DEFAULT (0) NULL,
    [COSTOSETUP]         DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOSETUP] DEFAULT (0) NULL,
    [COSTOSETUPEURO]     DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOSETUPEURO] DEFAULT (0) NULL,
    [DSCCOSTOSETUP]      VARCHAR (30)    NULL,
    [COSTOMACCHINA]      DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOMACCHINA] DEFAULT (0) NULL,
    [COSTOMACCHINAEURO]  DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOMACCHINAEURO] DEFAULT (0) NULL,
    [DSCCOSTOMACCHINA]   VARCHAR (30)    NULL,
    [COSTOUOMO]          DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOUOMO] DEFAULT (0) NULL,
    [COSTOUOMOEURO]      DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOUOMOEURO] DEFAULT (0) NULL,
    [DSCCOSTOUOMO]       VARCHAR (30)    NULL,
    [COSTOINDIRETTO]     DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOINDIRETTO] DEFAULT (0) NULL,
    [COSTOINDIRETTOEURO] DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOINDIRETTOEURO] DEFAULT (0) NULL,
    [DSCCOSTOINDIRETTO]  VARCHAR (30)    NULL,
    [COSTOESTERNO]       DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOESTERNO] DEFAULT (0) NULL,
    [COSTOESTERNOEURO]   DECIMAL (19, 6) CONSTRAINT [DF_RIGHELISTACONS_COSTOESTERNOEURO] DEFAULT (0) NULL,
    [DSCCOSTOESTERNO]    VARCHAR (30)    NULL,
    [QTAVERSATA]         DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_QTAVERSATA] DEFAULT (0) NULL,
    [QTARILAVORATA]      DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_QTARILAVORATA] DEFAULT (0) NULL,
    [QTASCARTATA]        DECIMAL (16, 6) CONSTRAINT [DF_RIGHELISTACONS_QTASCARTATA] DEFAULT (0) NULL,
    [UM]                 VARCHAR (3)     NOT NULL,
    [STATOOPERAZIONE]    SMALLINT        CONSTRAINT [DF_RIGHELISTACONS_STATOOPERAZIONE] DEFAULT (0) NULL,
    [CODSQUADRA]         VARCHAR (5)     NULL,
    [STATORIGA]          SMALLINT        CONSTRAINT [DF_RIGHELISTACONS_STATORIGA] DEFAULT (0) NULL,
    [NOTE]               VARCHAR (100)   NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [QTATRASFERITA]      DECIMAL (16, 6) NULL,
    [QTALAVORATA]        DECIMAL (16, 6) NULL,
    [PARTITA]            VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([IDTESTA] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
/* DELETE TRIGGER "TD_RIGHELISTACONS" FOR TABLE "RIGHELISTACONS" */
CREATE TRIGGER TD_RIGHELISTACONS ON RIGHELISTACONS FOR DELETE AS
BEGIN

DECLARE
@NUMROWS INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* DELETE CASCADE */   /* per OGNI Record CHILD in Relazione */
/* DELETE ALL CHILDREN IN "DIPENDENTILISTAMOV" */
DELETE DIPENDENTILISTAMOV
FROM DIPENDENTILISTAMOV T2, DELETED T1
WHERE T2.IDTESTA = T1.IDTESTA and T2.IDRIGA = T1.IDRIGA

RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHELISTACONS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHELISTACONS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHELISTACONS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHELISTACONS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHELISTACONS] TO [Metodo98]
    AS [dbo];

