CREATE TABLE [dbo].[RIGHESTRUTTPREVCOMMCLI] (
    [RIFPROGRESSIVO] DECIMAL (10)  NOT NULL,
    [NRRIGA]         DECIMAL (5)   NOT NULL,
    [POSIZIONE]      DECIMAL (5)   NOT NULL,
    [CODLIV]         VARCHAR (24)  NULL,
    [LIV]            SMALLINT      NULL,
    [LIVPADRE]       VARCHAR (24)  NULL,
    [TIPONODO]       SMALLINT      CONSTRAINT [DF_RIGHESTRUTTPREVCOMMCLI_TIPONODO] DEFAULT (0) NULL,
    [DESCRIZIONE]    VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [NRRIGAPADRE]    DECIMAL (5)   NULL,
    [CODLIVELLO]     VARCHAR (20)  NULL,
    CONSTRAINT [PK_RIGHESTRUTTPREVCOMMCLI] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RIGHESTRUTTPREVCOMMCLI_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTESTRUTTURACOMMCLI] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[RIGHESTRUTTPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[RIGHESTRUTTPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[RIGHESTRUTTPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[RIGHESTRUTTPREVCOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[RIGHESTRUTTPREVCOMMCLI] TO [Metodo98]
    AS [dbo];

