CREATE TABLE [dbo].[SALDIFINALIIMPORT] (
    [CONTO]          VARCHAR (7)     NOT NULL,
    [ESERCIZIO]      DECIMAL (5)     NOT NULL,
    [PROVVISORIO]    SMALLINT        DEFAULT (0) NULL,
    [DARE]           DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [DAREEURO]       DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [DAREVALUTA]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [AVERE]          DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [AVEREEURO]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [AVEREVALUTA]    DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SALDO]          DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SALDOEURO]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [SALDOVALUTA]    DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [NRPARTITA]      VARCHAR (19)    CONSTRAINT [DF_SALDIFINALIIMPORT_NRPARTITA] DEFAULT ('') NOT NULL,
    CONSTRAINT [SALDIFINALIIMPORT_PK] PRIMARY KEY CLUSTERED ([CONTO] ASC, [ESERCIZIO] ASC, [NRPARTITA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_PROVVISORIO_SALDIFIN] CHECK ([PROVVISORIO] = 0)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[SALDIFINALIIMPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SALDIFINALIIMPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[SALDIFINALIIMPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SALDIFINALIIMPORT] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SALDIFINALIIMPORT] TO [Metodo98]
    AS [dbo];

