CREATE TABLE [dbo].[SCONTIESTESI] (
    [CODSCONTO]         VARCHAR (5)   NOT NULL,
    [DESCRIZIONESCONTO] VARCHAR (255) NOT NULL,
    [TIPO]              VARCHAR (2)   CONSTRAINT [DF_SCONTIESTESI_TIPO] DEFAULT ('LI') NOT NULL,
    [BLOCCATO]          SMALLINT      CONSTRAINT [DF_SCONTIESTESI_BLOCCATO] DEFAULT ((0)) NOT NULL,
    [VALIDO]            SMALLINT      CONSTRAINT [DF__SCONTIEST__VALID] DEFAULT ((1)) NULL,
    [UTENTEMODIFICA]    VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]      DATETIME      NOT NULL,
    [CODCONTO]          VARCHAR (7)   DEFAULT ('') NULL,
    [CLIFOR]            SMALLINT      DEFAULT ((0)) NULL,
    [CodEuritmo]        VARCHAR (10)  DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_SCONTIESTESI] PRIMARY KEY CLUSTERED ([CODSCONTO] ASC),
    CONSTRAINT [FK_SCONTIESTESI_SCONTIESTESI] FOREIGN KEY ([TIPO]) REFERENCES [dbo].[TIPISCONTO] ([TIPO]),
    CONSTRAINT [FK_SCONTIESTESI_SCONTIESTESI1] FOREIGN KEY ([CODSCONTO]) REFERENCES [dbo].[SCONTIESTESI] ([CODSCONTO])
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[SCONTIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SCONTIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SCONTIESTESI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SCONTIESTESI] TO [Metodo98]
    AS [dbo];

