CREATE TABLE [dbo].[SL_ArticoliTEMPLEADTIME] (
    [CODICEART]       VARCHAR (50)    NOT NULL,
    [ESERCIZIO]       DECIMAL (5)     NOT NULL,
    [PROVENIENZA]     SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_PROVENIENZA] DEFAULT (0) NOT NULL,
    [QMINRIORDACQ]    DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QMINRIORDACQ] DEFAULT (0) NOT NULL,
    [QMAXRIORDACQ]    DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QMAXRIORDACQ] DEFAULT (0) NOT NULL,
    [QDELTARIORDACQ]  DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QDELTARIORDACQ] DEFAULT (0) NOT NULL,
    [TAPPRONTACQ]     SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_TAPPRONTACQ] DEFAULT (0) NOT NULL,
    [TAPPROVVACQ]     SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_TAPPROVVACQ] DEFAULT (0) NOT NULL,
    [LOTTORIFACQ]     DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_LOTTORIFACQ] DEFAULT (0) NOT NULL,
    [ARROTLOTTOACQ]   SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_ARROTLOTTOACQ] DEFAULT (0) NOT NULL,
    [UMLOTTOACQ]      VARCHAR (3)     NOT NULL,
    [QMINRIORDPROD]   DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QMINRIORDPROD] DEFAULT (0) NOT NULL,
    [QMAXRIORDPROD]   DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QMAXRIORDPROD] DEFAULT (0) NOT NULL,
    [QDELTARIORDPROD] DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QDELTARIORDPROD] DEFAULT (0) NOT NULL,
    [TAPPRONTPROD]    SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_TAPPRONTPROD] DEFAULT (0) NOT NULL,
    [TAPPROVVPROD]    SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_TAPPROVVPROD] DEFAULT (0) NOT NULL,
    [LOTTORIFPROD]    DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_LOTTORIFPROD] DEFAULT (0) NOT NULL,
    [ARROTLOTTOPROD]  SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_ARROTLOTTOPROD] DEFAULT (0) NOT NULL,
    [UMLOTTOPROD]     VARCHAR (3)     NOT NULL,
    [QMINRIORDLAV]    DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QMINRIORDLAV] DEFAULT (0) NOT NULL,
    [QMAXRIORDLAV]    DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QMAXRIORDLAV] DEFAULT (0) NOT NULL,
    [QDELTARIORDLAV]  DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_QDELTARIORDLAV] DEFAULT (0) NOT NULL,
    [TAPPRONTLAV]     SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_TAPPRONTLAV] DEFAULT (0) NOT NULL,
    [TAPPROVVLAV]     SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_TAPPROVVLAV] DEFAULT (0) NOT NULL,
    [LOTTORIFLAV]     DECIMAL (16, 6) CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_LOTTORIFLAV] DEFAULT (0) NOT NULL,
    [ARROTLOTTOLAV]   SMALLINT        CONSTRAINT [DF_SL_ArticoliTEMPLEADTIME_ARROTLOTTOLAV] DEFAULT (0) NOT NULL,
    [UMLOTTOLAV]      VARCHAR (3)     NOT NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NULL,
    CONSTRAINT [PK__SL_ArticoliTEMPL__170F250F] PRIMARY KEY CLUSTERED ([CODICEART] ASC, [ESERCIZIO] ASC, [UTENTEMODIFICA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[SL_ArticoliTEMPLEADTIME] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SL_ArticoliTEMPLEADTIME] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[SL_ArticoliTEMPLEADTIME] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SL_ArticoliTEMPLEADTIME] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SL_ArticoliTEMPLEADTIME] TO [Metodo98]
    AS [dbo];

