CREATE TABLE [dbo].[STAMPADELEGHEIVA] (
    [NTERM]            SMALLINT        NOT NULL,
    [FILIALEBANCA]     VARCHAR (80)    NULL,
    [PROVBANCA]        VARCHAR (4)     NULL,
    [CABBANCA]         VARCHAR (6)     NULL,
    [CONTOFISCDIT]     VARCHAR (25)    NULL,
    [PARTITAIVADIT]    VARCHAR (12)    NULL,
    [RAGSOCCOGNOMEDIT] VARCHAR (80)    NULL,
    [RAGSOCNOMEDIT]    VARCHAR (80)    NULL,
    [DATANASCITADIT]   DATETIME        NULL,
    [SESSODIT]         CHAR (1)        NULL,
    [COMUNENASCITADIT] VARCHAR (80)    NULL,
    [PROVNASCITADIT]   VARCHAR (4)     NULL,
    [COMUNESEDEDIT]    VARCHAR (80)    NULL,
    [PROVSEDEDIT]      VARCHAR (4)     NULL,
    [VIASEDEDIT]       VARCHAR (80)    NULL,
    [NUMSEDEDIT]       VARCHAR (4)     NULL,
    [IMPORTOTRIBUTO]   DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [INTERESSI]        DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [TOTALECIFRE]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]   VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]     DATETIME        NOT NULL,
    CONSTRAINT [PK_STAMPADELEGHEIVA] PRIMARY KEY CLUSTERED ([NTERM] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[STAMPADELEGHEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STAMPADELEGHEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STAMPADELEGHEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STAMPADELEGHEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STAMPADELEGHEIVA] TO [Metodo98]
    AS [dbo];

