CREATE TABLE [dbo].[STATOFATTUREPA] (
    [RIFPROGRESSIVO]       DECIMAL (10)  NOT NULL,
    [DATACREAZIONE]        DATETIME      NULL,
    [DATATRASMISSIONE]     DATETIME      NULL,
    [NOMEFILETRASMISSIONE] VARCHAR (50)  NULL,
    [STATO]                SMALLINT      NULL,
    [UTENTEMODIFICA]       VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]         DATETIME      NOT NULL,
    [STATOHUB]             INT           CONSTRAINT [DF_STATOFATTUREPA_STATOHUB] DEFAULT ((0)) NULL,
    [PATHFILE]             VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC),
    CONSTRAINT [FK_STATOFATTUREPA] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTEDOCUMENTI] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[STATOFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STATOFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STATOFATTUREPA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STATOFATTUREPA] TO [Metodo98]
    AS [dbo];

