CREATE TABLE [dbo].[STORICOCONSEGNE] (
    [IDSTORICO]          VARCHAR (10)    NOT NULL,
    [IDTESTA]            DECIMAL (10)    NOT NULL,
    [IDRIGA]             INT             NOT NULL,
    [TIPODOC]            VARCHAR (3)     NOT NULL,
    [NUMERODOC]          INT             NOT NULL,
    [BIS]                CHAR (1)        NULL,
    [VARIANTI]           VARCHAR (255)   NOT NULL,
    [DESCRIZIONEART]     VARCHAR (255)   NULL,
    [ESERCIZIO]          DECIMAL (5)     NOT NULL,
    [CODARTICOLO]        VARCHAR (50)    NULL,
    [CODCLIENTE]         VARCHAR (7)     NULL,
    [CODPARTITA]         VARCHAR (15)    NULL,
    [UBICAZIONE]         VARCHAR (10)    NULL,
    [UM]                 VARCHAR (3)     NOT NULL,
    [QUANTITA]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [QTACONSIDERATA]     DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CAMPOCONSIDERATO]   SMALLINT        NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [IDENTIFICATIVOCONS] INT             NULL,
    [RAGSOCCLI]          VARCHAR (80)    NULL,
    [QTADACONS]          DECIMAL (16, 6) NOT NULL,
    [PROGRRIGA]          INT             NOT NULL,
    [CODDEPOSITO]        VARCHAR (10)    NULL,
    CONSTRAINT [PK_STORICOCONSEGNE] PRIMARY KEY CLUSTERED ([IDSTORICO] ASC, [PROGRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [STCONS_DOC]
    ON [dbo].[STORICOCONSEGNE]([ESERCIZIO] ASC, [TIPODOC] ASC, [NUMERODOC] ASC, [BIS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [STCONS_ARTICOLO]
    ON [dbo].[STORICOCONSEGNE]([CODARTICOLO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [STCONS_CLIFOR]
    ON [dbo].[STORICOCONSEGNE]([CODCLIENTE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [STCONS_PARTITA]
    ON [dbo].[STORICOCONSEGNE]([CODPARTITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [STCONS_ESERCIZIO]
    ON [dbo].[STORICOCONSEGNE]([ESERCIZIO] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [STCONS_UBICAZIONE]
    ON [dbo].[STORICOCONSEGNE]([UBICAZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[STORICOCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STORICOCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STORICOCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STORICOCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STORICOCONSEGNE] TO [Metodo98]
    AS [dbo];

