CREATE TABLE [dbo].[STORICOMAGMATRICOLE] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [CODMATRICOLA]   VARCHAR (30) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_STORICOMAGMATRICOLE] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC, [CODMATRICOLA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [STMATRICOLE_COD]
    ON [dbo].[STORICOMAGMATRICOLE]([CODMATRICOLA] ASC) WITH (FILLFACTOR = 90);


GO

/*  INSERT TRIGGER "TI_STORICOMAGMATRICOLE" FOR TABLE "STORICOMAGMATRICOLE"  */
CREATE TRIGGER TI_STORICOMAGMATRICOLE ON STORICOMAGMATRICOLE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "STORICOMAG" MUST EXIST WHEN INSERTING A CHILD IN "STORICOMAGMATRICOLE"  */
    IF UPDATE(PROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   STORICOMAG T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "STORICOMAG". Cannot create child in "STORICOMAGMATRICOLE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_STORICOMAGMATRICOLE" FOR TABLE "STORICOMAGMATRICOLE"  */
CREATE TRIGGER TU_STORICOMAGMATRICOLE ON STORICOMAGMATRICOLE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "STORICOMAG" MUST EXIST WHEN UPDATING A CHILD IN "STORICOMAGMATRICOLE"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   STORICOMAG T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"STORICOMAG" does not exist. Cannot modify child in "STORICOMAGMATRICOLE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[STORICOMAGMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[STORICOMAGMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[STORICOMAGMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[STORICOMAGMATRICOLE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[STORICOMAGMATRICOLE] TO [Metodo98]
    AS [dbo];

