CREATE TABLE [dbo].[TABCARMACCHINE] (
    [CODICE]          VARCHAR (5)  NOT NULL,
    [NRRIGA]          INT          NOT NULL,
    [CARDESCRIZIONE]  VARCHAR (80) NULL,
    [CARTIPO]         SMALLINT     NULL,
    [CARNUMCARATTERI] SMALLINT     NULL,
    [UTENTEMODIFICA]  VARCHAR (25) NOT NULL,
    [DATAMODIFICA]    DATETIME     NOT NULL,
    CONSTRAINT [PK_TABCARMACCHINE] PRIMARY KEY CLUSTERED ([CODICE] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  UPDATE TRIGGER "TU_TABCARMACCHINE" FOR TABLE "TABCARMACCHINE"  */
CREATE TRIGGER TU_TABCARMACCHINE ON TABCARMACCHINE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABELLACDLAVORO" MUST EXIST WHEN UPDATING A CHILD IN "TABCARMACCHINE"  */
      IF UPDATE(CODICE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABELLACDLAVORO T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODICE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABELLACDLAVORO" does not exist. Cannot ALTER COLUMN child in "TABCARMACCHINE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  INSERT TRIGGER "TI_TABCARMACCHINE" FOR TABLE "TABCARMACCHINE"  */
CREATE TRIGGER TI_TABCARMACCHINE ON TABCARMACCHINE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABELLACDLAVORO" MUST EXIST WHEN INSERTING A CHILD IN "TABCARMACCHINE"  */
    IF UPDATE(CODICE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABELLACDLAVORO T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODICE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABELLACDLAVORO". Cannot create child in "TABCARMACCHINE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCARMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCARMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCARMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCARMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCARMACCHINE] TO [Metodo98]
    AS [dbo];

