CREATE TABLE [dbo].[TABCATEGORIEUTENSILI] (
    [CODICE]         DECIMAL (5)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (25)  NULL,
    [NOTE]           VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABCATEGORIEUTENSILI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  UPDATE TRIGGER "TU_TABCATEGORIEUTENSILI" FOR TABLE "TABCATEGORIEUTENSILI"  */
CREATE TRIGGER TU_TABCATEGORIEUTENSILI ON TABCATEGORIEUTENSILI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  CANNOT ALTER COLUMN PARENT CODE IN "TABCATEGORIEUTENSILI" IF CHILDREN STILL EXIST IN "TABUTENSILI"  */
      IF UPDATE(CODICE)
      BEGIN
         IF EXISTS (SELECT 1
                    FROM   TABUTENSILI T2, INSERTED I1, DELETED D1
                    WHERE  T2.CATEGORIA = D1.CODICE
                     AND  (I1.CODICE != D1.CODICE))
            BEGIN
               SELECT @ERRNO  = 30005,
                      @ERRMSG = 'Children still exist in "TABUTENSILI". Cannot ALTER COLUMN parent code in "TABCATEGORIEUTENSILI".'
               GOTO ERROR
            END
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABCATEGORIEUTENSILI" FOR ALL CHILDREN IN "TABCARUTENSILI"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TABCARUTENSILI
          SET   CODICE = I1.CODICE
         FROM   TABCARUTENSILI T2, INSERTED I1, DELETED D1
         WHERE  T2.CODICE = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TABCATEGORIEUTENSILI" FOR TABLE "TABCATEGORIEUTENSILI"  */
CREATE TRIGGER TD_TABCATEGORIEUTENSILI ON TABCATEGORIEUTENSILI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  CANNOT DELETE PARENT "TABCATEGORIEUTENSILI" IF CHILDREN STILL EXIST IN "TABUTENSILI"  */
    IF EXISTS (SELECT 1
               FROM   TABUTENSILI T2, DELETED T1
               WHERE  T2.CATEGORIA = T1.CODICE)
       BEGIN
          SELECT @ERRNO  = 30006,
                 @ERRMSG = 'Children still exist in "TABUTENSILI". Cannot delete parent "TABCATEGORIEUTENSILI".'
          GOTO ERROR
       END
    
    /*  DELETE ALL CHILDREN IN "TABCARUTENSILI"  */
    DELETE TABCARUTENSILI
    FROM   TABCARUTENSILI T2, DELETED T1
    WHERE  T2.CODICE = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABCATEGORIEUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABCATEGORIEUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABCATEGORIEUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABCATEGORIEUTENSILI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABCATEGORIEUTENSILI] TO [Metodo98]
    AS [dbo];

