CREATE TABLE [dbo].[TabCausaliAvanzamento] (
    [CODICE]                NUMERIC (5)  NOT NULL,
    [DESCRIZIONE]           VARCHAR (80) NULL,
    [SGNSETUP]              SMALLINT     DEFAULT (0) NULL,
    [TIPOATTIVITASETUP]     SMALLINT     DEFAULT (0) NULL,
    [SGNMACCHINA]           SMALLINT     DEFAULT (0) NULL,
    [TIPOATTIVITAMACCHINA]  SMALLINT     DEFAULT (0) NULL,
    [SGNUOMO]               SMALLINT     DEFAULT (0) NULL,
    [TIPOATTIVITAUOMO]      SMALLINT     DEFAULT (0) NULL,
    [SGNDURATA]             SMALLINT     DEFAULT (0) NULL,
    [TIPOATTIVITADURATA]    SMALLINT     DEFAULT (0) NULL,
    [SPALMADURATA]          SMALLINT     DEFAULT (0) NULL,
    [TIPOAVANZAMENTOTEMPI]  SMALLINT     DEFAULT (0) NULL,
    [SGNTEMPOMOV]           SMALLINT     DEFAULT (0) NULL,
    [SGNCOSTOSETUP]         SMALLINT     DEFAULT (0) NULL,
    [TIPOATTCOSTOSETUP]     SMALLINT     DEFAULT (0) NULL,
    [SGNCOSTOMACCHINA]      SMALLINT     DEFAULT (0) NULL,
    [TIPOATTCOSTOMACCHINA]  SMALLINT     DEFAULT (0) NULL,
    [SGNCOSTOUOMO]          SMALLINT     DEFAULT (0) NULL,
    [TIPOATTCOSTOUOMO]      SMALLINT     DEFAULT (0) NULL,
    [SGNCOSTOINDIRETTO]     SMALLINT     DEFAULT (0) NULL,
    [TIPOATTCOSTOINDIRETTO] SMALLINT     DEFAULT (0) NULL,
    [SGNCOSTOESTERNO]       SMALLINT     DEFAULT (0) NULL,
    [TIPOATTCOSTOESTERNO]   SMALLINT     DEFAULT (0) NULL,
    [SGNQTAVERSATA]         SMALLINT     DEFAULT (0) NULL,
    [SGNQTARILAVORATA]      SMALLINT     DEFAULT (0) NULL,
    [SGNQTASCARTATA]        SMALLINT     DEFAULT (0) NULL,
    [OBBLIGOMATRICOLA]      SMALLINT     DEFAULT ((-1)) NULL,
    [GESTSQUADRA]           SMALLINT     DEFAULT ((-1)) NULL,
    [MOVIMENTAORDPROD]      SMALLINT     DEFAULT (0) NULL,
    [OBBLIGOBOLLA]          SMALLINT     DEFAULT ((-1)) NULL,
    [FLGCONSCOMMCLI]        SMALLINT     DEFAULT ((-1)) NULL,
    [CODCAUSCOMMCLI]        SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA]        VARCHAR (25) NOT NULL,
    [DATAMODIFICA]          DATETIME     NOT NULL,
    [NUOVOSTATO]            SMALLINT     DEFAULT (0) NULL,
    [SGNQTALAVORATA]        SMALLINT     CONSTRAINT [DF_TABCAUSALIAVANZAMENTO_SGNQTALAVORATA] DEFAULT (0) NULL,
    [TIPOMOVQTALAVORATA]    SMALLINT     CONSTRAINT [DF_TABCAUSALIAVANZAMENTO_TIPOMOVQTALAVORATA] DEFAULT (0) NULL,
    [SGNQTATRASFERITA]      SMALLINT     CONSTRAINT [DF_TABCAUSALIAVANZAMENTO_SGNQTATRASFERITA] DEFAULT (0) NULL,
    [TIPOLISTAMOV]          SMALLINT     CONSTRAINT [DF_TABCAUSALIAVANZAMENTO_TIPOLISTAMOV] DEFAULT (0) NULL,
    [GESTPARTITA]           SMALLINT     NULL,
    [LISTAVERSAMENTO]       VARCHAR (3)  NULL,
    [LISTAPRELIEVO]         VARCHAR (3)  NULL,
    [LISTAVERSPREL]         VARCHAR (3)  NULL,
    CONSTRAINT [TabCausaliAvanzamento_PK] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TabCausaliAvanzamento] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TabCausaliAvanzamento] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TabCausaliAvanzamento] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TabCausaliAvanzamento] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TabCausaliAvanzamento] TO [Metodo98]
    AS [dbo];

