CREATE TABLE [dbo].[TABELLACONTATTI] (
    [CODICE]              VARCHAR (5)    NOT NULL,
    [RIFCODCONTO]         VARCHAR (7)    NOT NULL,
    [DATA]                DATETIME       NULL,
    [UTENTE]              VARCHAR (80)   NULL,
    [TIPO]                INT            NULL,
    [CODICEINTERLOCUTORE] VARCHAR (80)   NULL,
    [OGGETTO]             VARCHAR (250)  NULL,
    [NOTE]                VARCHAR (1000) NULL,
    [AVVENUTO]            SMALLINT       NULL,
    [ALLEGATO]            VARCHAR (255)  NULL,
    [UTENTEMODIFICA]      VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]        DATETIME       NOT NULL,
    CONSTRAINT [pk_tabellacontatti] PRIMARY KEY CLUSTERED ([CODICE] ASC, [RIFCODCONTO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TABELLACONTATTI_RIFCODCONTO] FOREIGN KEY ([RIFCODCONTO]) REFERENCES [dbo].[ANAGRAFICACF] ([CODCONTO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABELLACONTATTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABELLACONTATTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABELLACONTATTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABELLACONTATTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABELLACONTATTI] TO [Metodo98]
    AS [dbo];

