CREATE TABLE [dbo].[TABELLASQUADRE] (
    [CODICE]         VARCHAR (5)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (80)  NULL,
    [INIZIOVALIDITA] DATETIME      NULL,
    [FINEVALIDITA]   DATETIME      NULL,
    [NOTE]           VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [TABELLASQUADRE_PK] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
/*  DELETE TRIGGER "TD_TABSQUADRE" FOR TABLE "TABSQUADRE"  */
CREATE TRIGGER TD_TABELLASQUADRE ON TABELLASQUADRE FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
    /*  DELETE ALL CHILDREN IN "COMPONENTISQUADRA"  */
    DELETE COMPONENTISQUADRA
    FROM   COMPONENTISQUADRA T2, DELETED T1
    WHERE  T2.SQUADRA = T1.CODICE
    
    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABELLASQUADRE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABELLASQUADRE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABELLASQUADRE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABELLASQUADRE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABELLASQUADRE] TO [Metodo98]
    AS [dbo];

