CREATE TABLE [dbo].[TABELLACDLAVORO] (
    [CODICE]                VARCHAR (5)     NOT NULL,
    [DESCRIZIONE]           VARCHAR (80)    NULL,
    [TIPOCENTRO]            SMALLINT        DEFAULT (0) NULL,
    [TERZISTA]              VARCHAR (7)     NULL,
    [REPARTO]               DECIMAL (5)     NULL,
    [CONTOCDC]              VARCHAR (10)    NULL,
    [CODICEATTIVITA]        SMALLINT        DEFAULT (0) NULL,
    [RESPONSABILE]          VARCHAR (5)     NULL,
    [EFFSTANDARD]           DECIMAL (8, 5)  DEFAULT (0) NOT NULL,
    [EFFMEDIA]              DECIMAL (8, 5)  DEFAULT (0) NOT NULL,
    [RISORSACRITICA]        SMALLINT        DEFAULT (0) NULL,
    [CODASTANDARD]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CODAMEDIA]             DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [SQMCICLO]              DECIMAL (8, 5)  DEFAULT (0) NOT NULL,
    [TEMPOMOVSTANDARD]      DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CALCOLOTEMPOSETUP]     VARCHAR (255)   NULL,
    [UMTEMPOSETUP]          VARCHAR (1)     DEFAULT ('O') NULL,
    [CALCOLOTEMPOMACCHINA]  VARCHAR (255)   NULL,
    [UMTEMPOMACCHINA]       VARCHAR (1)     DEFAULT ('O') NULL,
    [CALCOLOTEMPOUOMO]      VARCHAR (255)   NULL,
    [UMTEMPOUOMO]           VARCHAR (1)     DEFAULT ('O') NULL,
    [CALCOLOTEMPOTOTALE]    VARCHAR (255)   NULL,
    [UMTEMPOTOTALE]         VARCHAR (1)     DEFAULT ('O') NULL,
    [QODIRETTASETUP]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CALCCOSTODSETUP]       VARCHAR (255)   NULL,
    [UMTCOSTOSETUP]         VARCHAR (1)     DEFAULT ('O') NULL,
    [QODIRETTAMACCHINA]     DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CALCCOSTODMACCHINA]    VARCHAR (255)   NULL,
    [UMTCOSTOMACCHINA]      VARCHAR (1)     DEFAULT ('O') NULL,
    [QODIRETTAUOMO]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CALCCOSTODUOMO]        VARCHAR (255)   NULL,
    [UMTCOSTOUOMO]          VARCHAR (1)     DEFAULT ('O') NULL,
    [QOINDVARIABILE]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [CALCCOSTOINDVAR]       VARCHAR (255)   NULL,
    [QOINDFISSA]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [ELEMENTICOSTOINDFISSO] SMALLINT        DEFAULT (0) NULL,
    [STDQODIRETTASETUP]     DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [STDQODIRETTAMACCHINA]  DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [STDQODIRETTAUOMO]      DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [STDQOINDIRETTAVAR]     DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [STDQOINDIRETTAFISSA]   DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [VALUTATEMPI]           VARCHAR (3)     DEFAULT ('123') NULL,
    [VALUTAQUOTEORARIE]     VARCHAR (5)     DEFAULT ('12345') NULL,
    [DISPRISORSE]           SMALLINT        DEFAULT (0) NULL,
    [DISPRISORSECM]         SMALLINT        DEFAULT (1) NULL,
    [NOTE]                  VARCHAR (100)   NULL,
    [UTENTEMODIFICA]        VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]          DATETIME        NOT NULL,
    [UMTCOSTOINDVAR]        VARCHAR (1)     NULL,
    [UMTCOSTOINDFISSA]      VARCHAR (1)     NULL,
    [FLGQUALITY]            SMALLINT        CONSTRAINT [DF_TABELLACDLAVORO_FLGQUALITY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TABELLACDLAVORO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_CODICEATTIVITA_TABELLAC] CHECK ([CODICEATTIVITA] = 2 or [CODICEATTIVITA] = 1 or [CODICEATTIVITA] = 0),
    CONSTRAINT [CKC_ELEMENTICOSTOINDF_TABELLAC] CHECK ([ELEMENTICOSTOINDFISSO] >= 0 and [ELEMENTICOSTOINDFISSO] <= 15),
    CONSTRAINT [CKC_RISORSACRITICA_TABELLAC] CHECK ([RISORSACRITICA] = 1 or [RISORSACRITICA] = 0),
    CONSTRAINT [CKC_TIPOCENTRO_TABELLAC] CHECK ([TIPOCENTRO] = 2 or [TIPOCENTRO] = 1 or [TIPOCENTRO] = 0),
    CONSTRAINT [CKC_UMTCOSTOINDFISSA_TABELLAC] CHECK ([UMTCOSTOINDFISSA] = 'P' or [UMTCOSTOINDFISSA] = 'T' or [UMTCOSTOINDFISSA] = 'C' or [UMTCOSTOINDFISSA] = 'S' or [UMTCOSTOINDFISSA] = 'M' or [UMTCOSTOINDFISSA] = 'O' or [UMTCOSTOINDFISSA] = 'G'),
    CONSTRAINT [CKC_UMTCOSTOINDVAR_TABELLAC] CHECK ([UMTCOSTOINDVAR] = 'P' or [UMTCOSTOINDVAR] = 'T' or [UMTCOSTOINDVAR] = 'C' or [UMTCOSTOINDVAR] = 'S' or [UMTCOSTOINDVAR] = 'M' or [UMTCOSTOINDVAR] = 'O' or [UMTCOSTOINDVAR] = 'G'),
    CONSTRAINT [CKC_UMTCOSTOMACCHINA_TABELLAC] CHECK ([UMTCOSTOMACCHINA] = 'P' or [UMTCOSTOMACCHINA] = 'T' or [UMTCOSTOMACCHINA] = 'C' or [UMTCOSTOMACCHINA] = 'S' or [UMTCOSTOMACCHINA] = 'M' or [UMTCOSTOMACCHINA] = 'O' or [UMTCOSTOMACCHINA] = 'G'),
    CONSTRAINT [CKC_UMTCOSTOSETUP_TABELLAC] CHECK ([UMTCOSTOSETUP] = 'P' or [UMTCOSTOSETUP] = 'T' or [UMTCOSTOSETUP] = 'C' or [UMTCOSTOSETUP] = 'S' or [UMTCOSTOSETUP] = 'M' or [UMTCOSTOSETUP] = 'O' or [UMTCOSTOSETUP] = 'G'),
    CONSTRAINT [CKC_UMTCOSTOUOMO_TABELLAC] CHECK ([UMTCOSTOUOMO] = 'P' or [UMTCOSTOUOMO] = 'T' or [UMTCOSTOUOMO] = 'C' or [UMTCOSTOUOMO] = 'S' or [UMTCOSTOUOMO] = 'M' or [UMTCOSTOUOMO] = 'O' or [UMTCOSTOUOMO] = 'G'),
    CONSTRAINT [CKC_UMTEMPOMACCHINA_TABELLAC] CHECK ([UMTEMPOMACCHINA] = 'P' or [UMTEMPOMACCHINA] = 'T' or [UMTEMPOMACCHINA] = 'C' or [UMTEMPOMACCHINA] = 'S' or [UMTEMPOMACCHINA] = 'M' or [UMTEMPOMACCHINA] = 'O' or [UMTEMPOMACCHINA] = 'G'),
    CONSTRAINT [CKC_UMTEMPOSETUP_TABELLAC] CHECK ([UMTEMPOSETUP] = 'P' or [UMTEMPOSETUP] = 'T' or [UMTEMPOSETUP] = 'C' or [UMTEMPOSETUP] = 'S' or [UMTEMPOSETUP] = 'M' or [UMTEMPOSETUP] = 'O' or [UMTEMPOSETUP] = 'G'),
    CONSTRAINT [CKC_UMTEMPOTOTALE_TABELLAC] CHECK ([UMTEMPOTOTALE] = 'P' or [UMTEMPOTOTALE] = 'T' or [UMTEMPOTOTALE] = 'C' or [UMTEMPOTOTALE] = 'S' or [UMTEMPOTOTALE] = 'M' or [UMTEMPOTOTALE] = 'O' or [UMTEMPOTOTALE] = 'G'),
    CONSTRAINT [CKC_UMTEMPOUOMO_TABELLAC] CHECK ([UMTEMPOUOMO] = 'P' or [UMTEMPOUOMO] = 'T' or [UMTEMPOUOMO] = 'C' or [UMTEMPOUOMO] = 'S' or [UMTEMPOUOMO] = 'M' or [UMTEMPOUOMO] = 'O' or [UMTEMPOUOMO] = 'G')
);


GO

/*  INSERT TRIGGER "TI_TABELLACDLAVORO" FOR TABLE "TABELLACDLAVORO"  */
CREATE TRIGGER TI_TABELLACDLAVORO ON TABELLACDLAVORO FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABELLAREPARTI" MUST EXIST WHEN INSERTING A CHILD IN "TABELLACDLAVORO"  */
    IF UPDATE(REPARTO)
    BEGIN
       SELECT @NUMNULL = (SELECT COUNT(*)
                          FROM   INSERTED
                          WHERE  REPARTO IS NULL)
       IF @NUMNULL != @NUMROWS
          IF (SELECT COUNT(*)
              FROM   TABELLAREPARTI T1, INSERTED T2
              WHERE  T1.CODICE = T2.REPARTO) != @NUMROWS - @NUMNULL
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABELLAREPARTI". Cannot create child in "TABELLACDLAVORO".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABELLACDLAVORO" FOR TABLE "TABELLACDLAVORO"  */
CREATE TRIGGER TU_TABELLACDLAVORO ON TABELLACDLAVORO FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABELLAREPARTI" MUST EXIST WHEN UPDATING A CHILD IN "TABELLACDLAVORO"  */
      IF UPDATE(REPARTO)
      BEGIN
         SELECT @NUMNULL = (SELECT COUNT(*)
                            FROM   INSERTED
                            WHERE  REPARTO IS NULL)
         IF @NUMNULL != @NUMROWS
            IF (SELECT COUNT(*)
                FROM   TABELLAREPARTI T1, INSERTED T2
                WHERE  T1.CODICE = T2.REPARTO) != @NUMROWS - @NUMNULL
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABELLAREPARTI" does not exist. Cannot ALTER COLUMN child in "TABELLACDLAVORO".'
               GOTO ERROR
            END
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABELLACDLAVORO" FOR ALL CHILDREN IN "EXTRACDLAVORO"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE EXTRACDLAVORO
          SET   CODCDL = I1.CODICE
         FROM   EXTRACDLAVORO T2, INSERTED I1, DELETED D1
         WHERE  T2.CODCDL = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABELLACDLAVORO" FOR ALL CHILDREN IN "CALCDLAVORO"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE CALCDLAVORO
          SET   CODCDL = I1.CODICE
         FROM   CALCDLAVORO T2, INSERTED I1, DELETED D1
         WHERE  T2.CODCDL = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABELLACDLAVORO" FOR ALL CHILDREN IN "TABCARMACCHINE"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TABCARMACCHINE
          SET   CODICE = I1.CODICE
         FROM   TABCARMACCHINE T2, INSERTED I1, DELETED D1
         WHERE  T2.CODICE = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
CREATE TRIGGER TD_TABELLACDLAVORO ON TABELLACDLAVORO FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "EXTRACDLAVORO"  */
    DELETE EXTRACDLAVORO
    FROM   EXTRACDLAVORO T2, DELETED T1
    WHERE  T2.CODCDL = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "CALCDLAVORO"  */
    DELETE CALCDLAVORO
    FROM   CALCDLAVORO T2, DELETED T1
    WHERE  T2.CODCDL = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "TABCARMACCHINE"  */
    DELETE TABCARMACCHINE
    FROM   TABCARMACCHINE T2, DELETED T1
    WHERE  T2.CODICE = T1.CODICE
    
    /*  DELETE ALL CHILDREN IN "PROFILOORARIOSTANDARD"  */
    DELETE PROFILOORARIOSTANDARD
    FROM   PROFILOORARIOSTANDARD T2, DELETED T1
    WHERE  T2.CODICE = T1.CODICE AND TIPOPO=1

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABELLACDLAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABELLACDLAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABELLACDLAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABELLACDLAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABELLACDLAVORO] TO [Metodo98]
    AS [dbo];

