CREATE TABLE [dbo].[TABELLAPERSONALE] (
    [CODICE]         VARCHAR (5)   NOT NULL,
    [RIFCODCONTO]    VARCHAR (7)   NOT NULL,
    [COGNOME]        VARCHAR (80)  NULL,
    [NOME]           VARCHAR (80)  NULL,
    [TITOLO]         INT           NULL,
    [TELEFONO]       VARCHAR (25)  NULL,
    [CELL]           VARCHAR (25)  NULL,
    [TELCASA]        VARCHAR (25)  NULL,
    [FAX]            VARCHAR (25)  NULL,
    [POSIZIONE]      VARCHAR (50)  NULL,
    [EMAIL]          VARCHAR (255) NULL,
    [NOTE]           VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [CODRUOLO]       VARCHAR (5)   NULL,
    [CodCrm]         VARCHAR (50)  NULL,
    [CONSENSO]       VARCHAR (1)   DEFAULT ('N') NOT NULL,
    [DATACONS]       DATETIME      NULL,
    [ATTESTCONS]     VARCHAR (300) NULL,
    CONSTRAINT [pk_codtabellapersonale] PRIMARY KEY CLUSTERED ([CODICE] ASC, [RIFCODCONTO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TABELLAPERSONALE_RIFCODCONTO] FOREIGN KEY ([RIFCODCONTO]) REFERENCES [dbo].[ANAGRAFICACF] ([CODCONTO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [ALD_ABELLAPERSONALE_ruolo]
    ON [dbo].[TABELLAPERSONALE]([CODRUOLO] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABELLAPERSONALE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABELLAPERSONALE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABELLAPERSONALE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABELLAPERSONALE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABELLAPERSONALE] TO [Metodo98]
    AS [dbo];

