CREATE TABLE [dbo].[TABELLAOPERAZIONI] (
    [CODICE]         VARCHAR (5)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (80)  NULL,
    [CODICECDL]      VARCHAR (5)   NULL,
    [MACCHINAPREF]   VARCHAR (5)   NULL,
    [TIPO]           DECIMAL (5)   NOT NULL,
    [NOTE]           VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [FLGQUALITY]     SMALLINT      CONSTRAINT [DF_TABELLAOPERAZIONI_FLGQUALITY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TABELLAOPERAZIONI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  UPDATE TRIGGER "TU_TABELLAOPERAZIONI" FOR TABLE "TABELLAOPERAZIONI"  */
CREATE TRIGGER TU_TABELLAOPERAZIONI ON TABELLAOPERAZIONI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABTIPIOPERAZIONI" MUST EXIST WHEN UPDATING A CHILD IN "TABELLAOPERAZIONI"  */
      IF UPDATE(TIPO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABTIPIOPERAZIONI T1, INSERTED T2
             WHERE  T1.CODICE = T2.TIPO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABTIPIOPERAZIONI" does not exist. Cannot ALTER COLUMN child in "TABELLAOPERAZIONI".'
               GOTO ERROR
            END
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABELLAOPERAZIONI" FOR ALL CHILDREN IN "ANACAROPERAZIONI"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE ANACAROPERAZIONI
          SET   OPERAZIONE = I1.CODICE
         FROM   ANACAROPERAZIONI T2, INSERTED I1, DELETED D1
         WHERE  T2.OPERAZIONE = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TABELLAOPERAZIONI" FOR TABLE "TABELLAOPERAZIONI"  */
CREATE TRIGGER TD_TABELLAOPERAZIONI ON TABELLAOPERAZIONI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "ANACAROPERAZIONI"  */
    DELETE ANACAROPERAZIONI
    FROM   ANACAROPERAZIONI T2, DELETED T1
    WHERE  T2.OPERAZIONE = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  INSERT TRIGGER "TI_TABELLAOPERAZIONI" FOR TABLE "TABELLAOPERAZIONI"  */
CREATE TRIGGER TI_TABELLAOPERAZIONI ON TABELLAOPERAZIONI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABTIPIOPERAZIONI" MUST EXIST WHEN INSERTING A CHILD IN "TABELLAOPERAZIONI"  */
    IF UPDATE(TIPO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABTIPIOPERAZIONI T1, INSERTED T2
           WHERE  T1.CODICE = T2.TIPO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABTIPIOPERAZIONI". Cannot create child in "TABELLAOPERAZIONI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABELLAOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABELLAOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABELLAOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABELLAOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABELLAOPERAZIONI] TO [Metodo98]
    AS [dbo];

