CREATE TABLE [dbo].[TABIMBALLI] (
    [CODICE]             VARCHAR (10)    NOT NULL,
    [DESCRIZIONE]        VARCHAR (80)    NULL,
    [LUNGHEZZA]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [LARGHEZZA]          DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [ALTEZZA]            DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [PESOIMBALLO]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [DESCRIZIONELINGUA1] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA2] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA3] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA4] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA5] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA6] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA7] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA8] VARCHAR (80)    NULL,
    [DESCRIZIONELINGUA9] VARCHAR (80)    NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    CONSTRAINT [PK_TABIMBALLI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABIMBALLI_DSC]
    ON [dbo].[TABIMBALLI]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABIMBALLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABIMBALLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABIMBALLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABIMBALLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABIMBALLI] TO [Metodo98]
    AS [dbo];

