CREATE TABLE [dbo].[TABLISTINITRASFORMAZIONE] (
    [NRLISTINO]      DECIMAL (5)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [CODCAMBIO]      DECIMAL (5)  NULL,
    [VINCOLAUM]      SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABLISTINITRASFORMAZIONE] PRIMARY KEY CLUSTERED ([NRLISTINO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_VINCOLAUM_TABLISTITRASF] CHECK ([VINCOLAUM] = 0 or [VINCOLAUM] = 1)
);


GO

/*  DELETE TRIGGER "TD_TABLISTINITRASFORMAZIONE" FOR TABLE "TABLISTINITRASFORMAZIONE"  */
CREATE TRIGGER TD_TABLISTINITRASFORMAZIONE ON TABLISTINITRASFORMAZIONE FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "LISTINIARTICOLITRASF"  */
    DELETE LISTINIARTICOLITRASF
    FROM   LISTINIARTICOLITRASF T2, DELETED T1
    WHERE  T2.NRLISTINO = T1.NRLISTINO
    
    /*  DELETE ALL CHILDREN IN "TABLISTINIFORTRASF"  */
    DELETE TABLISTINIFORTRASF
    FROM   TABLISTINIFORTRASF T2, DELETED T1
    WHERE  T2.NRLISTINO = T1.NRLISTINO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABLISTINITRASFORMAZIONE" FOR TABLE "TABLISTINITRASFORMAZIONE"  */
CREATE TRIGGER TU_TABLISTINITRASFORMAZIONE ON TABLISTINITRASFORMAZIONE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  ALTER COLUMN PARENT CODE OF "TABLISTINITRASFORMAZIONE" FOR ALL CHILDREN IN "LISTINIARTICOLITRASF"  */
      IF UPDATE(NRLISTINO)
      BEGIN
         UPDATE LISTINIARTICOLITRASF
          SET   NRLISTINO = I1.NRLISTINO
         FROM   LISTINIARTICOLITRASF T2, INSERTED I1, DELETED D1
         WHERE  T2.NRLISTINO = D1.NRLISTINO
          AND  (I1.NRLISTINO != D1.NRLISTINO)
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABLISTINITRASFORMAZIONE" FOR ALL CHILDREN IN "TABLISTINIFORTRASF"  */
      IF UPDATE(NRLISTINO)
      BEGIN
         UPDATE TABLISTINIFORTRASF
          SET   NRLISTINO = I1.NRLISTINO
         FROM   TABLISTINIFORTRASF T2, INSERTED I1, DELETED D1
         WHERE  T2.NRLISTINO = D1.NRLISTINO
          AND  (I1.NRLISTINO != D1.NRLISTINO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABLISTINITRASFORMAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABLISTINITRASFORMAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABLISTINITRASFORMAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABLISTINITRASFORMAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABLISTINITRASFORMAZIONE] TO [Metodo98]
    AS [dbo];

