CREATE TABLE [dbo].[TABLICENZENONAMENU] (
    [CODLICENZA]   DECIMAL (4)  NOT NULL,
    [KEYNODOPADRE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TABLICENZENONAMENU] PRIMARY KEY CLUSTERED ([CODLICENZA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABLICENZENONAMENU] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABLICENZENONAMENU] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABLICENZENONAMENU] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABLICENZENONAMENU] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABLICENZENONAMENU] TO [Metodo98]
    AS [dbo];

