CREATE TABLE [dbo].[TABMISSIONIUTENTI] (
    [TIPOPGM]        SMALLINT     NOT NULL,
    [USERID]         VARCHAR (25) NOT NULL,
    [CodDep]         VARCHAR (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [PROGRPSINFATT]  DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [IDSESSIONE]     DECIMAL (5)  DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TABMISSIONIUTENTI] PRIMARY KEY CLUSTERED ([TIPOPGM] ASC, [USERID] ASC, [CodDep] ASC, [PROGRPSINFATT] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABMISSIONIUTENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABMISSIONIUTENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABMISSIONIUTENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABMISSIONIUTENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABMISSIONIUTENTI] TO [Metodo98]
    AS [dbo];

