CREATE TABLE [dbo].[TABNAZIONI] (
    [CODICE]             DECIMAL (5)    NOT NULL,
    [DESCRIZIONE]        VARCHAR (25)   NULL,
    [CODICEISO]          VARCHAR (3)    NULL,
    [DESCRIZIONELINGUA1] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA2] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA3] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA4] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA5] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA6] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA7] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA8] VARCHAR (80)   NULL,
    [DESCRIZIONELINGUA9] VARCHAR (80)   NULL,
    [UTENTEMODIFICA]     VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]       DATETIME       NOT NULL,
    [CodiceUIC]          DECIMAL (4)    CONSTRAINT [DF_TABNAZIONI_CodiceUIC] DEFAULT (0) NULL,
    [Budget]             DECIMAL (4, 2) CONSTRAINT [DF_TABNAZIONI_BUDGET] DEFAULT (0) NULL,
    [NAZIONECE]          SMALLINT       NULL,
    [FLGBLACKLIST]       SMALLINT       NULL,
    [CODSTATOESTERO]     SMALLINT       NULL,
    CONSTRAINT [PK_TABNAZIONI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_TABNAZIONI_FLGBLACKLIST] CHECK ([FLGBLACKLIST]=(1) OR [FLGBLACKLIST]=(0)),
    CONSTRAINT [CHK_TABNAZIONI_NAZIONECR] CHECK ([NAZIONECE]=(1) OR [NAZIONECE]=(0))
);


GO
CREATE NONCLUSTERED INDEX [TABNAZIONI_DSC]
    ON [dbo].[TABNAZIONI]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABNAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABNAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABNAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABNAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABNAZIONI] TO [Metodo98]
    AS [dbo];

