CREATE TABLE [dbo].[TABNATURAGIURIDICA] (
    [CODICE]         SMALLINT      NOT NULL,
    [DESCRIZIONE]    VARCHAR (200) NULL,
    [TIPOSOGGETTO]   SMALLINT      NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABNATURAGIURIDICA] PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABNATURAGIURIDICA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABNATURAGIURIDICA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABNATURAGIURIDICA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABNATURAGIURIDICA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABNATURAGIURIDICA] TO [Metodo98]
    AS [dbo];

