CREATE TABLE [dbo].[TABORIGINEINTRA] (
    [CODICE]         VARCHAR (2)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (25) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABORIGINEINTRA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABORIGINTRA_DSC]
    ON [dbo].[TABORIGINEINTRA]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABORIGINEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABORIGINEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABORIGINEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABORIGINEINTRA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABORIGINEINTRA] TO [Metodo98]
    AS [dbo];

