CREATE TABLE [dbo].[TABPLAFOND] (
    [ANNO]            DECIMAL (5)     NOT NULL,
    [MESE]            SMALLINT        NOT NULL,
    [PLAFONDLIRE]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [PLAFONDEURO]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    [UTILIZZODOCLIRE] DECIMAL (19, 4) NULL,
    [UTILIZZODOCEURO] DECIMAL (19, 4) NULL,
    [PROGEXPORT]      DECIMAL (19, 4) CONSTRAINT [DF_TABPLAFOND_PROGEXPORT] DEFAULT (0) NULL,
    [PROGUTILIZZO]    DECIMAL (19, 4) CONSTRAINT [DF_TABPLAFOND_PROGUTILIZZO] DEFAULT (0) NULL,
    CONSTRAINT [PK_TABPLAFOND] PRIMARY KEY CLUSTERED ([ANNO] ASC, [MESE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABPLAFOND] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABPLAFOND] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABPLAFOND] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABPLAFOND] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABPLAFOND] TO [Metodo98]
    AS [dbo];

