CREATE TABLE [dbo].[TABPARAMETRICOMMCLI] (
    [CODICE]                      VARCHAR (3)    NOT NULL,
    [DESCRIZIONE]                 VARCHAR (100)  NULL,
    [CODICETAPPO]                 SMALLINT       NULL,
    [GENERAMAG]                   SMALLINT       NULL,
    [PREVENTIVATO]                SMALLINT       NULL,
    [FLG_ABILITA_DETTFORN]        SMALLINT       NULL,
    [FLG_ABILITA_SPEDIZ]          SMALLINT       NULL,
    [FLG_ABILITA_VARCONTR]        SMALLINT       NULL,
    [FLG_ABILITA_PENALI]          SMALLINT       NULL,
    [FLG_ABILITA_DESTINAZ]        SMALLINT       NULL,
    [FLG_ABILITA_EXTRA]           SMALLINT       NULL,
    [FLG_ABILITA_TOTALI]          SMALLINT       NULL,
    [FLG_ABILITA_RIF]             SMALLINT       NULL,
    [FLG_ABILITA_CONS]            SMALLINT       NULL,
    [FLG_ABILITA_TRASP]           SMALLINT       NULL,
    [FLG_ABILITA_MAG]             SMALLINT       NULL,
    [FLG_ABILITA_COMMCOLL]        SMALLINT       NULL,
    [FLG_ABILITA_TOTVAR]          SMALLINT       NULL,
    [FLG_ABILITA_CONDVAR]         SMALLINT       NULL,
    [FLG_ABILITA_PIANOFATT]       SMALLINT       NULL,
    [FLG_ABILITA_AGENTI]          SMALLINT       NULL,
    [FLG_ABILITA_TOTFORN]         SMALLINT       NULL,
    [CARSPECRIGHEDOC]             VARCHAR (3)    NULL,
    [TIPOCOMMCLIDEF]              VARCHAR (3)    NULL,
    [FORMATODEFRIFCOMM]           VARCHAR (30)   NULL,
    [MAGAZZINI]                   VARCHAR (200)  NULL,
    [TIPODOCDEFEMISSDOCPREV]      VARCHAR (3)    NULL,
    [TIPOORDDEFEMISSORDPROD]      VARCHAR (3)    NULL,
    [DEFCLASSMATMP]               VARCHAR (3)    NULL,
    [DEFCLASSMATSL]               VARCHAR (3)    NULL,
    [DEFCLASSMATPF]               VARCHAR (3)    NULL,
    [DEFCLASSLAVINT]              VARCHAR (3)    NULL,
    [DEFCLASSLAVEST]              VARCHAR (3)    NULL,
    [FLGPRELDADOC]                SMALLINT       NULL,
    [FLGTRASFPROD]                SMALLINT       NULL,
    [FLGORDENTRDAFORN]            SMALLINT       NULL,
    [FLGORDSPEDACLI]              SMALLINT       NULL,
    [COSTOSTANDCORRPRELDADOC]     VARCHAR (10)   NULL,
    [COSTODAORDBOLLATRASFPROD]    VARCHAR (10)   NULL,
    [COSTOSTANDCORRORDENTRDAFORN] VARCHAR (10)   NULL,
    [COSTOSTANDCORRORDSPEDACLI]   VARCHAR (10)   NULL,
    [LISTINOPRELDADOC]            NUMERIC (5)    NULL,
    [LISTINOTRASFPROD]            NUMERIC (5)    NULL,
    [LISTINOORDENTRDAFORN]        NUMERIC (5)    NULL,
    [LISTINOORDSPEDACLI]          NUMERIC (5)    NULL,
    [FLGCONSUNDACICLIORD]         SMALLINT       NULL,
    [FLGCONSUNDADOC]              SMALLINT       NULL,
    [FLGRILEVDACICLILAVEMESSI]    SMALLINT       NULL,
    [TIPODOCPRELDADOC1]           VARCHAR (200)  NULL,
    [TIPODOCPRELDADOC2]           VARCHAR (200)  NULL,
    [TIPODOCPRELDADOC3]           VARCHAR (200)  NULL,
    [TIPODOCPRELDADOC4]           VARCHAR (200)  NULL,
    [TIPOORDTRASFPROD1]           VARCHAR (200)  NULL,
    [TIPODOCTRASFPROD1]           VARCHAR (200)  NULL,
    [TIPODOCTRASFPROD2]           VARCHAR (200)  NULL,
    [TIPODOCORDENTRDAFORN1]       VARCHAR (200)  NULL,
    [TIPODOCORDENTRDAFORN2]       VARCHAR (200)  NULL,
    [TIPODOCORDENTRDAFORN3]       VARCHAR (200)  NULL,
    [TIPODOCORDSPEDACLI1]         VARCHAR (200)  NULL,
    [TIPODOCORDSPEDACLI2]         VARCHAR (200)  NULL,
    [TIPODOCORDSPEDACLI3]         VARCHAR (200)  NULL,
    [TIPODOCCONSLAVINT1]          VARCHAR (200)  NULL,
    [TIPODOCCONSLAVINT2]          VARCHAR (200)  NULL,
    [TIPODOCCONTOLAVTRASF1]       VARCHAR (200)  NULL,
    [TIPODOCCONTOLAVTRASF2]       VARCHAR (200)  NULL,
    [TIPOORDCONTOLAVTRASF1]       VARCHAR (200)  NULL,
    [TIPODOCCONTOLAVDIFASE1]      VARCHAR (200)  NULL,
    [TIPODOCCONTOLAVDIFASE2]      VARCHAR (200)  NULL,
    [TIPODOCALTRICOSTIDADOC1]     VARCHAR (200)  NULL,
    [TIPODOCALTRICOSTIDADOC2]     VARCHAR (200)  NULL,
    [CAUSMAGPRELDADOC1]           VARCHAR (35)   NULL,
    [CAUSMAGPRELDADOC2]           VARCHAR (35)   NULL,
    [CAUSMAGPRELDADOC3]           VARCHAR (35)   NULL,
    [CAUSMAGPRELDADOC4]           VARCHAR (35)   NULL,
    [CAUSMAGTRASFPRODORD1]        VARCHAR (35)   NULL,
    [CAUSMAGTRASFPRODDOC1]        VARCHAR (35)   NULL,
    [CAUSMAGTRASFPRODDOC2]        VARCHAR (35)   NULL,
    [CAUSMAGORDENTRDAFORN1]       VARCHAR (35)   NULL,
    [CAUSMAGORDENTRDAFORN2]       VARCHAR (35)   NULL,
    [CAUSMAGORDENTRDAFORN3]       VARCHAR (35)   NULL,
    [CAUSMAGORDSPEDACLI1]         VARCHAR (35)   NULL,
    [CAUSMAGORDSPEDACLI2]         VARCHAR (35)   NULL,
    [CAUSMAGORDSPEDACLI3]         VARCHAR (35)   NULL,
    [UTENTEMODIFICA]              VARCHAR (25)   NOT NULL,
    [DATAMODIFICA]                DATETIME       NOT NULL,
    [TIPODOCRICAVI1]              VARCHAR (200)  NULL,
    [TIPODOCRICAVI2]              VARCHAR (200)  NULL,
    [FLGORDSPEDRICAVO]            SMALLINT       NULL,
    [FLGRILEVARTICOLI]            SMALLINT       NULL,
    [TOLLRIPPERC]                 DECIMAL (8, 5) CONSTRAINT [DF_TABPARAMETRICOMMCLI_TOLLRIPPERC] DEFAULT (0.01) NOT NULL,
    [TOLLRIPQTA]                  DECIMAL (8, 5) CONSTRAINT [DF_TABPARAMETRICOMMCLI_TOLLRIPQTA] DEFAULT (0.01) NOT NULL,
    [TOLLRIPVALORE]               DECIMAL (8, 5) CONSTRAINT [DF_TABPARAMETRICOMMCLI_TOLLRIPVALORE] DEFAULT (0.01) NOT NULL,
    [DECRIPPERC]                  SMALLINT       CONSTRAINT [DF_TABPARAMETRICOMMCLI_DECRIPPERC] DEFAULT (2) NOT NULL,
    [DECRIPQTA]                   SMALLINT       CONSTRAINT [DF_TABPARAMETRICOMMCLI_DECRIPQTA] DEFAULT (2) NOT NULL,
    [DECRIPVALORE]                SMALLINT       CONSTRAINT [DF_TABPARAMETRICOMMCLI_DECRIPVALORE] DEFAULT (2) NOT NULL,
    [FLGBLOCCARIP]                SMALLINT       CONSTRAINT [DF_TABPARAMETRICOMMCLI_FLGBLOCCARIP] DEFAULT (0) NOT NULL,
    [FLGRILEVACODICILISTAPN]      SMALLINT       CONSTRAINT [DF_TABPARAMETRICOMMCLI_FLGRILEVACODICILISTAPN] DEFAULT (0) NOT NULL,
    [FLGRILEVADOCNONCONTAB]       SMALLINT       CONSTRAINT [DF_TABPARAMETRICOMMCLI_FLGRILEVADOCNONCONTAB] DEFAULT (0) NOT NULL,
    [DEFCLASSCOSTIDIR]            VARCHAR (3)    NULL,
    [FLGCONSUNDACICLIPREV]        DECIMAL (5)    NULL,
    [DEFCLASSRICAVI]              VARCHAR (3)    NULL,
    CONSTRAINT [PK_TABPARAMETRICOMMCLI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABPARAMETRICOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABPARAMETRICOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABPARAMETRICOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABPARAMETRICOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABPARAMETRICOMMCLI] TO [Metodo98]
    AS [dbo];

