CREATE TABLE [dbo].[TABRIPARTIZRATEIRISCONTI] (
    [PROGRESSIVO]    DECIMAL (9)     NOT NULL,
    [NRREG]          DECIMAL (9)     NULL,
    [NRRIGA]         SMALLINT        NULL,
    [CODCONTO]       VARCHAR (7)     NULL,
    [TIPORIGA]       SMALLINT        CONSTRAINT [DF_TABRIPARTIZRATEIRISCONTI_TIPORIGA] DEFAULT (0) NULL,
    [RIFRIGAPADRE]   DECIMAL (9)     CONSTRAINT [DF_TABRIPARTIZRATEIRISCONTI_RIFRIGAPADRE] DEFAULT (0) NULL,
    [TIPOOPERAZIONE] SMALLINT        NULL,
    [ESERCIZIO]      DECIMAL (5)     NULL,
    [IMPORTO]        DECIMAL (19, 4) NULL,
    [IMPORTOEURO]    DECIMAL (19, 4) NULL,
    [IMPORTORR]      DECIMAL (19, 4) NULL,
    [IMPORTORREURO]  DECIMAL (19, 4) NULL,
    [DATAINIZIO]     DATETIME        NULL,
    [DATAFINE]       DATETIME        NULL,
    [GIORNI]         SMALLINT        NULL,
    [CONTO]          VARCHAR (7)     NULL,
    [RIFMOVCON]      DECIMAL (9)     CONSTRAINT [DF_TABRIPARTIZRATEIRISCONTI_RIFMOVCON] DEFAULT (0) NULL,
    [RIFMOVSTO]      DECIMAL (9)     CONSTRAINT [DF_TABRIPARTIZRATEIRISCONTI_RIFMOVSTO] DEFAULT (0) NULL,
    [NOTE]           VARCHAR (250)   NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [DATAREG]        DATETIME        NULL,
    [DATADOC]        DATETIME        NULL,
    [DATARIF]        DATETIME        NULL,
    [NUMDOC]         VARCHAR (12)    NULL,
    [NUMRIF]         VARCHAR (15)    NULL,
    [CAUSALE]        DECIMAL (5)     NULL,
    [IDTESTADOC]     DECIMAL (10)    CONSTRAINT [DF_TABRIPARTIZRATEIRISCONTI_IDTESTADOC] DEFAULT ((0)) NULL,
    CONSTRAINT [pk_TabRipartizRateiRisconti] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABRIPARTIZRATEIRISCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABRIPARTIZRATEIRISCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABRIPARTIZRATEIRISCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABRIPARTIZRATEIRISCONTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABRIPARTIZRATEIRISCONTI] TO [Metodo98]
    AS [dbo];

