CREATE TABLE [dbo].[TABREGISTROSISTRI] (
    [NUMEROREG]      NUMERIC (10) NOT NULL,
    [CODICE_DITTA]   INT          NOT NULL,
    [IDTESTA]        INT          NOT NULL,
    [IDRIGA]         INT          NOT NULL,
    [TIPOCARICO]     SMALLINT     NULL,
    [STATO]          SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMEROREG] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABREGISTROSISTRI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABREGISTROSISTRI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABREGISTROSISTRI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABREGISTROSISTRI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABREGISTROSISTRI] TO [Metodo98]
    AS [dbo];

