CREATE TABLE [dbo].[TABSTATOVERSIONEDBA] (
    [CODICE]         DECIMAL (5)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (25) NULL,
    [USAVERSIONE]    SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TABSTATOVERSIONEDBA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_USAVERSIONE_TABSTATO] CHECK ([USAVERSIONE] = 2 or [USAVERSIONE] = 1 or [USAVERSIONE] = 0)
);


GO
CREATE NONCLUSTERED INDEX [TABSTATODBA_DSC]
    ON [dbo].[TABSTATOVERSIONEDBA]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABSTATOVERSIONEDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABSTATOVERSIONEDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABSTATOVERSIONEDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABSTATOVERSIONEDBA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABSTATOVERSIONEDBA] TO [Metodo98]
    AS [dbo];

