CREATE TABLE [dbo].[TABTIPIOPERAZIONI] (
    [CODICE]         DECIMAL (5)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (25)  NULL,
    [NOTE]           VARCHAR (100) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABTIPIOPERAZIONI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  DELETE TRIGGER "TD_TABTIPIOPERAZIONI" FOR TABLE "TABTIPIOPERAZIONI"  */
CREATE TRIGGER TD_TABTIPIOPERAZIONI ON TABTIPIOPERAZIONI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  CANNOT DELETE PARENT "TABTIPIOPERAZIONI" IF CHILDREN STILL EXIST IN "TABELLAOPERAZIONI"  */
    IF EXISTS (SELECT 1
               FROM   TABELLAOPERAZIONI T2, DELETED T1
               WHERE  T2.TIPO = T1.CODICE)
       BEGIN
          SELECT @ERRNO  = 30006,
                 @ERRMSG = 'Children still exist in "TABELLAOPERAZIONI". Cannot delete parent "TABTIPIOPERAZIONI".'
          GOTO ERROR
       END
    
    /*  DELETE ALL CHILDREN IN "TABCAROPERAZIONI"  */
    DELETE TABCAROPERAZIONI
    FROM   TABCAROPERAZIONI T2, DELETED T1
    WHERE  T2.CODICE = T1.CODICE

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TABTIPIOPERAZIONI" FOR TABLE "TABTIPIOPERAZIONI"  */
CREATE TRIGGER TU_TABTIPIOPERAZIONI ON TABTIPIOPERAZIONI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  CANNOT ALTER COLUMN PARENT CODE IN "TABTIPIOPERAZIONI" IF CHILDREN STILL EXIST IN "TABELLAOPERAZIONI"  */
      IF UPDATE(CODICE)
      BEGIN
         IF EXISTS (SELECT 1
                    FROM   TABELLAOPERAZIONI T2, INSERTED I1, DELETED D1
                    WHERE  T2.TIPO = D1.CODICE
                     AND  (I1.CODICE != D1.CODICE))
            BEGIN
               SELECT @ERRNO  = 30005,
                      @ERRMSG = 'Children still exist in "TABELLAOPERAZIONI". Cannot ALTER COLUMN parent code in "TABTIPIOPERAZIONI".'
               GOTO ERROR
            END
      END
      
      /*  ALTER COLUMN PARENT CODE OF "TABTIPIOPERAZIONI" FOR ALL CHILDREN IN "TABCAROPERAZIONI"  */
      IF UPDATE(CODICE)
      BEGIN
         UPDATE TABCAROPERAZIONI
          SET   CODICE = I1.CODICE
         FROM   TABCAROPERAZIONI T2, INSERTED I1, DELETED D1
         WHERE  T2.CODICE = D1.CODICE
          AND  (I1.CODICE != D1.CODICE)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABTIPIOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABTIPIOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABTIPIOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABTIPIOPERAZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABTIPIOPERAZIONI] TO [Metodo98]
    AS [dbo];

