CREATE TABLE [dbo].[TABTIPOSPESASANITARIA] (
    [CODICE]         VARCHAR (2)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (350) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TABTIPOSPESASANITARIA] PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABTIPOSPESASANITARIA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABTIPOSPESASANITARIA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABTIPOSPESASANITARIA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABTIPOSPESASANITARIA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABTIPOSPESASANITARIA] TO [Metodo98]
    AS [dbo];

