CREATE TABLE [dbo].[TABTRASPACURA] (
    [CODICE]             DECIMAL (5)  NOT NULL,
    [DESCRIZIONE]        VARCHAR (25) NULL,
    [DESCRIZIONELINGUA1] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA2] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA3] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA4] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA5] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA6] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA7] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA8] VARCHAR (25) NULL,
    [DESCRIZIONELINGUA9] VARCHAR (25) NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    CONSTRAINT [PK_TABTRASPACURA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABACURA_DSC]
    ON [dbo].[TABTRASPACURA]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABTRASPACURA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABTRASPACURA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABTRASPACURA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABTRASPACURA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABTRASPACURA] TO [Metodo98]
    AS [dbo];

