CREATE TABLE [dbo].[TABTIPORECORDCC] (
    [CODICE]         VARCHAR (2)  NOT NULL,
    [CODGEN]         VARCHAR (2)  NULL,
    [FLGMANUALE]     SMALLINT     NULL,
    [DESCRIZIONE]    VARCHAR (50) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABTIPORECORDCC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABTIPORECORDCC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABTIPORECORDCC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABTIPORECORDCC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABTIPORECORDCC] TO [Metodo98]
    AS [dbo];

