CREATE TABLE [dbo].[TABTEMPICAMBIO] (
    [CAT_DA]         DECIMAL (5)     NOT NULL,
    [CAT_A]          DECIMAL (5)     NOT NULL,
    [TEMPOCAMBIO]    DECIMAL (19, 4) DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TABTEMPICAMBIO] PRIMARY KEY CLUSTERED ([CAT_DA] ASC, [CAT_A] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABTEMPICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABTEMPICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABTEMPICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABTEMPICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABTEMPICAMBIO] TO [Metodo98]
    AS [dbo];

