CREATE TABLE [dbo].[TABUNITAMISURA] (
    [CODICE]         VARCHAR (3)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (25) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [FLGVALINTERI]   SMALLINT     CONSTRAINT [DF_TABUNITAMISURA_FLGVALINTERI] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_TABUNITAMISURA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TABUMISURA_DSC]
    ON [dbo].[TABUNITAMISURA]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO

/*  UPDATE TRIGGER "TU_TABUNITAMISURA" FOR TABLE "TABUNITAMISURA"  */
CREATE TRIGGER TU_TABUNITAMISURA ON TABUNITAMISURA FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  CANNOT MODIFY PARENT CODE IN "TABUNITAMISURA" IF CHILDREN STILL EXIST IN "ARTICOLIUNITAMISURA"  */
      IF UPDATE(CODICE)
      BEGIN
         IF EXISTS (SELECT 1
                    FROM   ARTICOLIUNITAMISURA T2, INSERTED I1, DELETED D1
                    WHERE  T2.UM = D1.CODICE
                     AND  (I1.CODICE != D1.CODICE))
            BEGIN
               SELECT @ERRNO  = 30005,
                      @ERRMSG = 'Children still exist in "ARTICOLIUNITAMISURA". Cannot modify parent code in "TABUNITAMISURA".'
               GOTO ERROR
            END
      END
      
      /*  CANNOT MODIFY PARENT CODE IN "TABUNITAMISURA" IF CHILDREN STILL EXIST IN "LISTINIARTICOLI"  */
      IF UPDATE(CODICE)
      BEGIN
         IF EXISTS (SELECT 1
                    FROM   LISTINIARTICOLI T2, INSERTED I1, DELETED D1
                    WHERE  T2.UM = D1.CODICE
                     AND  (I1.CODICE != D1.CODICE))
            BEGIN
               SELECT @ERRNO  = 30005,
                      @ERRMSG = 'Children still exist in "LISTINIARTICOLI". Cannot modify parent code in "TABUNITAMISURA".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TABUNITAMISURA" FOR TABLE "TABUNITAMISURA"  */
CREATE TRIGGER TD_TABUNITAMISURA ON TABUNITAMISURA FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  CANNOT DELETE PARENT "TABUNITAMISURA" IF CHILDREN STILL EXIST IN "ARTICOLIUNITAMISURA"  */
    IF EXISTS (SELECT 1
               FROM   ARTICOLIUNITAMISURA T2, DELETED T1
               WHERE  T2.UM = T1.CODICE)
       BEGIN
          SELECT @ERRNO  = 30006,
                 @ERRMSG = 'Children still exist in "ARTICOLIUNITAMISURA". Cannot delete parent "TABUNITAMISURA".'
          GOTO ERROR
       END
    
    /*  CANNOT DELETE PARENT "TABUNITAMISURA" IF CHILDREN STILL EXIST IN "LISTINIARTICOLI"  */
    IF EXISTS (SELECT 1
               FROM   LISTINIARTICOLI T2, DELETED T1
               WHERE  T2.UM = T1.CODICE)
       BEGIN
          SELECT @ERRNO  = 30006,
                 @ERRMSG = 'Children still exist in "LISTINIARTICOLI". Cannot delete parent "TABUNITAMISURA".'
          GOTO ERROR
       END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TABUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABUNITAMISURA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABUNITAMISURA] TO [Metodo98]
    AS [dbo];

