CREATE TABLE [dbo].[TABVINCOLIGIC] (
    [ESERCIZIO]             DECIMAL (5)  NOT NULL,
    [CAUSCONTAP]            DECIMAL (5)  NULL,
    [CAUSCONTCH]            DECIMAL (5)  NULL,
    [CAUSCONTINSOLUTO]      DECIMAL (5)  NULL,
    [SCIVADEB1]             VARCHAR (7)  NULL,
    [SCIVADEB2]             VARCHAR (7)  NULL,
    [SCIVADEB3]             VARCHAR (7)  NULL,
    [SCIVADEB4]             VARCHAR (7)  NULL,
    [SCIVADEB5]             VARCHAR (7)  NULL,
    [SCIVACRED1]            VARCHAR (7)  NULL,
    [SCIVACRED2]            VARCHAR (7)  NULL,
    [SCIVACRED3]            VARCHAR (7)  NULL,
    [SCIVACRED4]            VARCHAR (7)  NULL,
    [SCIVACRED5]            VARCHAR (7)  NULL,
    [SCIVASOSP1]            VARCHAR (7)  NULL,
    [SCIVASOSP2]            VARCHAR (7)  NULL,
    [SCIVASOSP3]            VARCHAR (7)  NULL,
    [SCIVASOSP4]            VARCHAR (7)  NULL,
    [SCIVASOSP5]            VARCHAR (7)  NULL,
    [SCIVAACQINTRA1]        VARCHAR (7)  NULL,
    [SCIVAACQINTRA2]        VARCHAR (7)  NULL,
    [SCIVAACQINTRA3]        VARCHAR (7)  NULL,
    [SCIVAACQINTRA4]        VARCHAR (7)  NULL,
    [SCIVAACQINTRA5]        VARCHAR (7)  NULL,
    [SCIVAVENDINTRA1]       VARCHAR (7)  NULL,
    [SCIVAVENDINTRA2]       VARCHAR (7)  NULL,
    [SCIVAVENDINTRA3]       VARCHAR (7)  NULL,
    [SCIVAVENDINTRA4]       VARCHAR (7)  NULL,
    [SCIVAVENDINTRA5]       VARCHAR (7)  NULL,
    [REGVENDINTRA]          DECIMAL (5)  NULL,
    [USAPROTREG]            SMALLINT     DEFAULT (0) NULL,
    [SCCLICORRISP]          VARCHAR (7)  NULL,
    [SCGENDAVENT]           VARCHAR (7)  NULL,
    [SCGENVENTI]            VARCHAR (7)  NULL,
    [NDECIMALIQUANTITA]     SMALLINT     DEFAULT (4) NULL,
    [NDECIMALIUNITARIOLIRE] SMALLINT     DEFAULT (0) NULL,
    [NDECIMALITOTALELIRE]   SMALLINT     DEFAULT (0) NULL,
    [DIVISALIRE]            DECIMAL (5)  NULL,
    [DIVISAEURO]            DECIMAL (5)  NULL,
    [CONTOPATRAP]           VARCHAR (7)  NULL,
    [CONTOPATRCH]           VARCHAR (7)  NULL,
    [CONTOECOCH]            VARCHAR (7)  NULL,
    [UTENTEMODIFICA]        VARCHAR (25) NOT NULL,
    [DATAMODIFICA]          DATETIME     NOT NULL,
    [NDECIMALIPESIVOL]      SMALLINT     CONSTRAINT [DF__TABVINCOL__NDECIPV] DEFAULT (4) NULL,
    [FLGPARTITA]            SMALLINT     CONSTRAINT [DF_TABVINCOLIGIC_FLGPARTITA] DEFAULT (0) NULL,
    [SCIVAAUTOFATT1]        VARCHAR (7)  NULL,
    [SCIVAAUTOFATT2]        VARCHAR (7)  NULL,
    [SCIVAAUTOFATT3]        VARCHAR (7)  NULL,
    [SCIVAAUTOFATT4]        VARCHAR (7)  NULL,
    [SCIVAAUTOFATT5]        VARCHAR (7)  NULL,
    [REGVENDAUTOFATT]       DECIMAL (5)  NULL,
    [USAPROTREGAUTOF]       SMALLINT     NULL,
    [CAUSCONTRILUTPERD]     DECIMAL (5)  CONSTRAINT [DF_TABVINCOLIGIC_CAUSCONTRILUTPERD] DEFAULT (0) NULL,
    [CONTOUTILEESERC]       VARCHAR (7)  NULL,
    [CONTOPERDESERC]        VARCHAR (7)  NULL,
    [AGTCALCOLOSSCC]        VARCHAR (50) CONSTRAINT [DF_VINCOLI_AGTCALCOLOSSCC] DEFAULT ('') NULL,
    [CONTATORESSCC]         DECIMAL (5)  CONSTRAINT [DF_VINCOLI_CONTATORESSCC] DEFAULT (0) NULL,
    [INCLUDISPRIP]          SMALLINT     CONSTRAINT [DF_TABVINCOLIGIC_INCLUDISPRIP] DEFAULT (0) NULL,
    [SCIvaSospCred1]        VARCHAR (7)  NULL,
    [SCIvaSospCred2]        VARCHAR (7)  NULL,
    [SCIvaSospCred3]        VARCHAR (7)  NULL,
    [SCIvaSospCred4]        VARCHAR (7)  NULL,
    [SCIvaSospCred5]        VARCHAR (7)  NULL,
    [USARIPCOMPCOMMERCIALE] SMALLINT     NULL,
    CONSTRAINT [PK_TABVINCOLIGIC] PRIMARY KEY CLUSTERED ([ESERCIZIO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_TABVINCOLIGIC_USAPROTREGAUTOF] CHECK ([USAPROTREGAUTOF] is null or [USAPROTREGAUTOF] = 0 or [USAPROTREGAUTOF] = 1),
    CONSTRAINT [CHK_TABVINCOLIGIC_USARIPCOMPCOMMERCIALE] CHECK ([USARIPCOMPCOMMERCIALE]=(1) OR [USARIPCOMPCOMMERCIALE]=(0)),
    CONSTRAINT [CKC_USAPROTREG_TABVINCO] CHECK ([USAPROTREG] = 0 or [USAPROTREG] = 1)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TABVINCOLIGIC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TABVINCOLIGIC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TABVINCOLIGIC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TABVINCOLIGIC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TABVINCOLIGIC] TO [Metodo98]
    AS [dbo];

