CREATE TABLE [dbo].[TDA_DETTFEEDBACK_PRELIEVOPARTITE] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [RIFRIGA]        INT             NOT NULL,
    [RIFIMPEGNO]     INT             NOT NULL,
    [PARTITA]        VARCHAR (15)    NOT NULL,
    [QTACONSUNTIVO]  DECIMAL (16, 6) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [RIFRIGA] ASC, [RIFIMPEGNO] ASC, [PARTITA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRELIEVOPARTITE_PRELIEVO] FOREIGN KEY ([RIFPROGRESSIVO], [RIFRIGA], [RIFIMPEGNO]) REFERENCES [dbo].[TDA_DETTFEEDBACK_PRELIEVO] ([RIFPROGRESSIVO], [IDRIGA], [IDIMPEGNO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRELIEVOPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRELIEVOPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRELIEVOPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRELIEVOPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_DETTFEEDBACK_PRELIEVOPARTITE] TO [Metodo98]
    AS [dbo];

