CREATE TABLE [dbo].[TDA_FUNZIONIQUANTITA] (
    [CODICE]         DECIMAL (5)   NOT NULL,
    [DESCRIZIONE]    VARCHAR (80)  NULL,
    [QTAVER]         SMALLINT      NULL,
    [QTASCAR]        SMALLINT      NULL,
    [QTATRASF]       SMALLINT      NULL,
    [QTARIL]         SMALLINT      NULL,
    [QTALAV]         SMALLINT      NULL,
    [PLUGINRIL]      DECIMAL (5)   NULL,
    [PLUGINCONS]     DECIMAL (5)   NULL,
    [NOTE]           VARCHAR (255) NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [PROPONIRESIDUO] SMALLINT      NULL,
    PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_FUNZIONIQUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_FUNZIONIQUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_FUNZIONIQUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_FUNZIONIQUANTITA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_FUNZIONIQUANTITA] TO [Metodo98]
    AS [dbo];

