CREATE TABLE [dbo].[TDA_SESSIONILAVORO] (
    [UTENTE]         VARCHAR (25) NOT NULL,
    [TERMINALE]      DECIMAL (5)  NULL,
    [TIPOFEEDBACK]   DECIMAL (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([UTENTE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TDA_SESSIONILAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TDA_SESSIONILAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TDA_SESSIONILAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_SESSIONILAVORO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TDA_SESSIONILAVORO] TO [Metodo98]
    AS [dbo];

