CREATE TABLE [dbo].[TEMPSTPQUADROFAELENCHICF] (
    [IDSESSIONE]             DECIMAL (5)  NOT NULL,
    [NRPAGINA]               SMALLINT     NOT NULL,
    [CODFISCDITTA]           VARCHAR (16) NULL,
    [NRMODELLO]              VARCHAR (8)  NULL,
    [PARTITAIVA1]            VARCHAR (11) NULL,
    [CODFISCALE1]            VARCHAR (16) NULL,
    [FLGDOCRIEPILOGATIVO1]   VARCHAR (1)  NULL,
    [NROPATTIVE1]            INT          NULL,
    [NROPASSIVE1]            INT          NULL,
    [FLGNOLEGGIO1]           VARCHAR (1)  NULL,
    [TOTIMPONIBATT1]         DECIMAL (10) NULL,
    [TOTIMPOSTAATT1]         DECIMAL (10) NULL,
    [TOTIVANONESPATT1]       DECIMAL (10) NULL,
    [TOTIMPONIBNOTEVARDEB1]  DECIMAL (10) NULL,
    [TOTIMPOSTANOTEVARDEB1]  DECIMAL (10) NULL,
    [TOTIMPONIBPASS1]        DECIMAL (10) NULL,
    [TOTIMPOSTAPASS1]        DECIMAL (10) NULL,
    [TOTIVANONESPPASS1]      DECIMAL (10) NULL,
    [TOTIMPONIBNOTEVARCRED1] DECIMAL (10) NULL,
    [TOTIMPOSTANOTEVARCRED1] DECIMAL (10) NULL,
    [PARTITAIVA2]            VARCHAR (11) NULL,
    [CODFISCALE2]            VARCHAR (16) NULL,
    [FLGDOCRIEPILOGATIVO2]   VARCHAR (1)  NULL,
    [NROPATTIVE2]            INT          NULL,
    [NROPASSIVE2]            INT          NULL,
    [FLGNOLEGGIO2]           VARCHAR (1)  NULL,
    [TOTIMPONIBATT2]         DECIMAL (10) NULL,
    [TOTIMPOSTAATT2]         DECIMAL (10) NULL,
    [TOTIVANONESPATT2]       DECIMAL (10) NULL,
    [TOTIMPONIBNOTEVARDEB2]  DECIMAL (10) NULL,
    [TOTIMPOSTANOTEVARDEB2]  DECIMAL (10) NULL,
    [TOTIMPONIBPASS2]        DECIMAL (10) NULL,
    [TOTIMPOSTAPASS2]        DECIMAL (10) NULL,
    [TOTIVANONESPPASS2]      DECIMAL (10) NULL,
    [TOTIMPONIBNOTEVARCRED2] DECIMAL (10) NULL,
    [TOTIMPOSTANOTEVARCRED2] DECIMAL (10) NULL,
    [PARTITAIVA3]            VARCHAR (11) NULL,
    [CODFISCALE3]            VARCHAR (16) NULL,
    [FLGDOCRIEPILOGATIVO3]   VARCHAR (1)  NULL,
    [NROPATTIVE3]            INT          NULL,
    [NROPASSIVE3]            INT          NULL,
    [FLGNOLEGGIO3]           VARCHAR (1)  NULL,
    [TOTIMPONIBATT3]         DECIMAL (10) NULL,
    [TOTIMPOSTAATT3]         DECIMAL (10) NULL,
    [TOTIVANONESPATT3]       DECIMAL (10) NULL,
    [TOTIMPONIBNOTEVARDEB3]  DECIMAL (10) NULL,
    [TOTIMPOSTANOTEVARDEB3]  DECIMAL (10) NULL,
    [TOTIMPONIBPASS3]        DECIMAL (10) NULL,
    [TOTIMPOSTAPASS3]        DECIMAL (10) NULL,
    [TOTIVANONESPPASS3]      DECIMAL (10) NULL,
    [TOTIMPONIBNOTEVARCRED3] DECIMAL (10) NULL,
    [TOTIMPOSTANOTEVARCRED3] DECIMAL (10) NULL,
    [UTENTEMODIFICA]         VARCHAR (25) NOT NULL,
    [DATAMODIFICA]           DATETIME     NOT NULL,
    CONSTRAINT [PK_TEMPSTPQUADROFAELENCHICF] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [NRPAGINA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPQUADROFAELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPQUADROFAELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPQUADROFAELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPQUADROFAELENCHICF] TO [Metodo98]
    AS [dbo];

