CREATE TABLE [dbo].[TEMPSTPQUADRONRELENCHICF] (
    [IDSESSIONE]     DECIMAL (5)  NOT NULL,
    [NRPAGINA]       SMALLINT     NOT NULL,
    [CODFISCDITTA]   VARCHAR (16) NULL,
    [NRMODELLO]      VARCHAR (8)  NULL,
    [PARTITAIVA1]    VARCHAR (11) NULL,
    [DATADOC1]       DATETIME     NULL,
    [DATAREG1]       DATETIME     NULL,
    [IMPONIB1]       DECIMAL (10) NULL,
    [IMPOSTA1]       DECIMAL (10) NULL,
    [PARTITAIVA2]    VARCHAR (11) NULL,
    [DATADOC2]       DATETIME     NULL,
    [DATAREG2]       DATETIME     NULL,
    [IMPONIB2]       DECIMAL (10) NULL,
    [IMPOSTA2]       DECIMAL (10) NULL,
    [PARTITAIVA3]    VARCHAR (11) NULL,
    [DATADOC3]       DATETIME     NULL,
    [DATAREG3]       DATETIME     NULL,
    [IMPONIB3]       DECIMAL (10) NULL,
    [IMPOSTA3]       DECIMAL (10) NULL,
    [PARTITAIVA4]    VARCHAR (11) NULL,
    [DATADOC4]       DATETIME     NULL,
    [DATAREG4]       DATETIME     NULL,
    [IMPONIB4]       DECIMAL (10) NULL,
    [IMPOSTA4]       DECIMAL (10) NULL,
    [PARTITAIVA5]    VARCHAR (11) NULL,
    [DATADOC5]       DATETIME     NULL,
    [DATAREG5]       DATETIME     NULL,
    [IMPONIB5]       DECIMAL (10) NULL,
    [IMPOSTA5]       DECIMAL (10) NULL,
    [PARTITAIVA6]    VARCHAR (11) NULL,
    [DATADOC6]       DATETIME     NULL,
    [DATAREG6]       DATETIME     NULL,
    [IMPONIB6]       DECIMAL (10) NULL,
    [IMPOSTA6]       DECIMAL (10) NULL,
    [PARTITAIVA7]    VARCHAR (11) NULL,
    [DATADOC7]       DATETIME     NULL,
    [DATAREG7]       DATETIME     NULL,
    [IMPONIB7]       DECIMAL (10) NULL,
    [IMPOSTA7]       DECIMAL (10) NULL,
    [PARTITAIVA8]    VARCHAR (11) NULL,
    [DATADOC8]       DATETIME     NULL,
    [DATAREG8]       DATETIME     NULL,
    [IMPONIB8]       DECIMAL (10) NULL,
    [IMPOSTA8]       DECIMAL (10) NULL,
    [PARTITAIVA9]    VARCHAR (11) NULL,
    [DATADOC9]       DATETIME     NULL,
    [DATAREG9]       DATETIME     NULL,
    [IMPONIB9]       DECIMAL (10) NULL,
    [IMPOSTA9]       DECIMAL (10) NULL,
    [PARTITAIVA10]   VARCHAR (11) NULL,
    [DATADOC10]      DATETIME     NULL,
    [DATAREG10]      DATETIME     NULL,
    [IMPONIB10]      DECIMAL (10) NULL,
    [IMPOSTA10]      DECIMAL (10) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TEMPSTPQUADRONRELENCHICF] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [NRPAGINA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPQUADRONRELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPQUADRONRELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPQUADRONRELENCHICF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPQUADRONRELENCHICF] TO [Metodo98]
    AS [dbo];

