CREATE TABLE [dbo].[TEMPSTPCONSSTRUTTSL] (
    [IDSESSIONE]        INT             NOT NULL,
    [RIFCOMMCLI]        VARCHAR (30)    NOT NULL,
    [IDCOMMCLI]         DECIMAL (10)    NOT NULL,
    [NRRIGA]            DECIMAL (5)     NOT NULL,
    [NRRIGAPADRE]       DECIMAL (5)     NOT NULL,
    [CODNODO]           VARCHAR (50)    NULL,
    [CODDETT]           VARCHAR (50)    NULL,
    [LIV]               SMALLINT        NULL,
    [DESCRIZIONE]       VARCHAR (100)   NULL,
    [IDSTRUTTURA]       DECIMAL (10)    NULL,
    [TIPONODO]          SMALLINT        NULL,
    [TIPOCOSTO]         VARCHAR (4)     NULL,
    [VOCEBASE]          VARCHAR (3)     NULL,
    [RIFTESTA]          DECIMAL (10)    NULL,
    [RIFRIGA]           INT             NULL,
    [ORIGINEEVENTO]     SMALLINT        NULL,
    [PRC]               DECIMAL (8, 5)  NULL,
    [CONSUMATORIPEURO]  DECIMAL (19, 6) NULL,
    [RISERVATORIPEURO]  DECIMAL (19, 6) NULL,
    [ORDINATORIPEURO]   DECIMAL (19, 6) NULL,
    [PREVISTORIPEURO]   DECIMAL (19, 6) NULL,
    [COSTOTOTRIPEURO]   DECIMAL (19, 6) NULL,
    [RICAVOEFFRIPEURO]  DECIMAL (19, 6) NULL,
    [RICAVOPREVRIPEURO] DECIMAL (19, 6) NULL,
    [POSIZIONENODO]     DECIMAL (5)     NULL,
    [POSIZIONESTP]      DECIMAL (5)     NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPCONSSTRUTTSL] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPCONSSTRUTTSL] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTPCONSSTRUTTSL] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPCONSSTRUTTSL] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPCONSSTRUTTSL] TO [Metodo98]
    AS [dbo];

