CREATE TABLE [dbo].[TEMPPREVCONSCC] (
    [FLGPREV]             INT             NULL,
    [IDCOMMCLI]           DECIMAL (10)    NULL,
    [RIFCOMM]             VARCHAR (30)    NULL,
    [SC]                  VARCHAR (24)    NULL,
    [GRP]                 VARCHAR (24)    NULL,
    [CODLIV]              VARCHAR (24)    NULL,
    [DESCRGRUPPO]         VARCHAR (100)   NULL,
    [NRRIGASTRUTT]        DECIMAL (10)    NULL,
    [VOCEBASECONS]        VARCHAR (3)     NULL,
    [IDVOCECONS]          VARCHAR (3)     NULL,
    [VOCEBASEPREV]        VARCHAR (3)     NULL,
    [IDVOCEPREV]          VARCHAR (3)     NULL,
    [TIPOCOSTO]           VARCHAR (4)     NULL,
    [RIFTESTA]            DECIMAL (10)    NULL,
    [RIFRIGA]             INT             NULL,
    [ORIGINEEVENTO]       SMALLINT        NULL,
    [CONSUNTIVATORIP]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_CONSUNTIVATORIP] DEFAULT ((0)) NULL,
    [RISERVATORIP]        DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_RISERVATORIP] DEFAULT ((0)) NULL,
    [ORDINATORIP]         DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_ORDINATORIP] DEFAULT ((0)) NULL,
    [PREVISTORIP]         DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_PREVISTORIP] DEFAULT ((0)) NULL,
    [COSTOTOTRIP]         DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_COSTOTOTRIP] DEFAULT ((0)) NULL,
    [CONSUNTIVATORIPEURO] DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_CONSUNTIVATORIPEURO] DEFAULT ((0)) NULL,
    [RISERVATORIPEURO]    DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_RISERVATORIPEURO] DEFAULT ((0)) NULL,
    [ORDINATORIPEURO]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_ORDINATORIPEURO] DEFAULT ((0)) NULL,
    [PREVISTORIPEURO]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_PREVISTORIPEURO] DEFAULT ((0)) NULL,
    [COSTOTOTRIPEURO]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_COSTOTOTRIPEURO] DEFAULT ((0)) NULL,
    [COSTOTOTPREV]        DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_COSTOTOTPREV] DEFAULT ((0)) NULL,
    [COSTOTOTPREVEURO]    DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_COSTOTOTPREVEURO] DEFAULT ((0)) NULL,
    [OFFERTATOTPREV]      DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_OFFERTATOTPREV] DEFAULT ((0)) NULL,
    [OFFERTATOTPREVEURO]  DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_OFFERTATOTPREVEURO] DEFAULT ((0)) NULL,
    [RICAVOEFFRIPEURO]    DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_RICAVOEFFRIPEURO] DEFAULT ((0)) NULL,
    [RICAVOPREVRIPEURO]   DECIMAL (19, 6) CONSTRAINT [DF_TEMPPREVCONSCC_RICAVOPREVRIPEURO] DEFAULT ((0)) NULL,
    [IDSESSIONE]          INT             NOT NULL,
    [RAGGR1]              VARCHAR (30)    NULL,
    [RAGGR2]              VARCHAR (30)    NULL,
    [UTENTEMODIFICA]      VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]        DATETIME        NOT NULL,
    [SC_EST]              VARCHAR (30)    NULL,
    [GRP_EST]             VARCHAR (30)    NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPPREVCONSCC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPPREVCONSCC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPPREVCONSCC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPPREVCONSCC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPPREVCONSCC] TO [Metodo98]
    AS [dbo];

