CREATE TABLE [dbo].[TEMPANALISILANCIABILITA] (
    [IDSESSIONE] INT          NOT NULL,
    [IDCOMMESSA] DECIMAL (10) NOT NULL,
    [IDORDINE]   INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [IDCOMMESSA] ASC, [IDORDINE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPANALISILANCIABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPANALISILANCIABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPANALISILANCIABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPANALISILANCIABILITA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPANALISILANCIABILITA] TO [Metodo98]
    AS [dbo];

