CREATE TABLE [dbo].[TEMPSTPCONSEGNE] (
    [IDSESSIONE]         INT             NOT NULL,
    [IDTESTA]            DECIMAL (10)    NOT NULL,
    [IDRIGA]             INT             NOT NULL,
    [IDSTORICO]          VARCHAR (10)    NOT NULL,
    [QUANTITA]           DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [IDENTIFICATIVOCONS] INT             NULL,
    CONSTRAINT [PK_TEMPSTPCONSEGNE] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [IDTESTA] ASC, [IDRIGA] ASC, [IDSTORICO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTPCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPCONSEGNE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPCONSEGNE] TO [Metodo98]
    AS [dbo];

