CREATE TABLE [dbo].[TEMPSTAMPAPIANOPRODUZIONE] (
    [IDSESSIONE] INT          NOT NULL,
    [NOMEPIANIF] VARCHAR (30) NOT NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTAMPAPIANOPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTAMPAPIANOPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTAMPAPIANOPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTAMPAPIANOPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTAMPAPIANOPRODUZIONE] TO [Metodo98]
    AS [dbo];

