CREATE TABLE [dbo].[TEMP_RIGHETARPREMIOAGENTI] (
    [IDSESSIONE]     INT             NOT NULL,
    [RIFPROGRESSIVO] DECIMAL (9)     NOT NULL,
    [CODICE]         VARCHAR (50)    NOT NULL,
    [CODICEDETT]     VARCHAR (50)    NOT NULL,
    [NRRIGA]         INT             NOT NULL,
    [VALOREMIN]      DECIMAL (16, 6) NULL,
    [VALOREMAX]      DECIMAL (16, 6) NULL,
    [PREMIO]         DECIMAL (16, 6) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TEMP_RIGHETARPREMIOAGENTI] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [RIFPROGRESSIVO] ASC, [CODICE] ASC, [CODICEDETT] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMP_RIGHETARPREMIOAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMP_RIGHETARPREMIOAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMP_RIGHETARPREMIOAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMP_RIGHETARPREMIOAGENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMP_RIGHETARPREMIOAGENTI] TO [Metodo98]
    AS [dbo];

