CREATE TABLE [dbo].[TEMPSTPFSDICHINTENTO] (
    [RAGSOCCOGNOME]      VARCHAR (80) NULL,
    [RAGSOCNOME]         VARCHAR (80) NULL,
    [CODFISCALE]         VARCHAR (16) NULL,
    [ANNORIF]            SMALLINT     NULL,
    [MESERIF]            SMALLINT     NULL,
    [PARTITAIVA]         VARCHAR (16) NULL,
    [CORRETTIVA]         SMALLINT     NULL,
    [EVENTIECC]          SMALLINT     NULL,
    [PERSONAFG]          VARCHAR (1)  NULL,
    [COMUNENASCITA]      VARCHAR (80) NULL,
    [PROVNASCITA]        VARCHAR (2)  NULL,
    [DATANASCITA]        DATETIME     NULL,
    [SESSO]              VARCHAR (1)  NULL,
    [SEDELEGALE]         VARCHAR (80) NULL,
    [PROVLEGALE]         VARCHAR (2)  NULL,
    [VIALEGALE]          VARCHAR (80) NULL,
    [CAPLEGALE]          VARCHAR (5)  NULL,
    [NATURAGIURIDICA]    VARCHAR (2)  NULL,
    [CODFISCRAPP]        VARCHAR (16) NULL,
    [CODFISCDITTARAPP]   VARCHAR (16) NULL,
    [CODCARICARAPP]      SMALLINT     NULL,
    [COGNOMERAPP]        VARCHAR (80) NULL,
    [NOMERAPP]           VARCHAR (80) NULL,
    [SESSORAPP]          VARCHAR (1)  NULL,
    [DATANASCITARAPP]    DATETIME     NULL,
    [COMUNENASCITARAPP]  VARCHAR (80) NULL,
    [PROVNASCITARAPP]    VARCHAR (2)  NULL,
    [COMUNERESANAGRAPP]  VARCHAR (80) NULL,
    [PROVRESANAGRAPP]    VARCHAR (2)  NULL,
    [CAPRAPP]            VARCHAR (5)  NULL,
    [VIARAPP]            VARCHAR (80) NULL,
    [PREFTELRAPP]        VARCHAR (4)  NULL,
    [NUMTELRAPP]         VARCHAR (8)  NULL,
    [NUMRIGHE]           SMALLINT     NULL,
    [IDSESSIONE]         SMALLINT     NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    [COMUNEFISCALE]      VARCHAR (80) NULL,
    [PROVFISCALE]        VARCHAR (2)  NULL,
    [VIAFISCALE]         VARCHAR (80) NULL,
    [CAPFISCALE]         VARCHAR (5)  NULL,
    [PROGRDICH]          DECIMAL (10) NOT NULL,
    [FLGIMPTRASMISSIONE] SMALLINT     NULL,
    [INTEGRATIVA]        SMALLINT     NULL,
    [CODFISCINTERM]      VARCHAR (16) NULL,
    [DATAIMPEGNO]        DATETIME     NULL,
    [PREFTEL]            VARCHAR (8)  NULL,
    [NUMTEL]             VARCHAR (25) NULL,
    [EMAIL]              VARCHAR (50) NULL,
    CONSTRAINT [PK_TEMPSTPFSDICHINTENTO] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [PROGRDICH] ASC),
    CONSTRAINT [CHK_TEMPSTPFSDICHINTENTO_CORRETTIVA] CHECK ([CORRETTIVA] = 1 or [CORRETTIVA] = 0),
    CONSTRAINT [CHK_TEMPSTPFSDICHINTENTO_EVENTIECC] CHECK ([EVENTIECC] = 1 or [EVENTIECC] = 0),
    CONSTRAINT [CHK_TEMPSTPFSDICHINTENTO_FLGIMPTRASMISSIONE] CHECK ([FLGIMPTRASMISSIONE]=(1) OR [FLGIMPTRASMISSIONE]=(0)),
    CONSTRAINT [CHK_TEMPSTPFSDICHINTENTO_INTEGRATIVA] CHECK ([INTEGRATIVA]=(1) OR [INTEGRATIVA]=(0))
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTPFSDICHINTENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTPFSDICHINTENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTPFSDICHINTENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTPFSDICHINTENTO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTPFSDICHINTENTO] TO [Metodo98]
    AS [dbo];

