CREATE TABLE [dbo].[TEMPSTIMAFINIRECOMMCLI] (
    [IDSESSIONE]          INT             NOT NULL,
    [RIFCOMMCLI]          VARCHAR (30)    NOT NULL,
    [CODLIV]              VARCHAR (50)    NULL,
    [LIV]                 SMALLINT        NULL,
    [LIVPADRE]            VARCHAR (50)    NULL,
    [NRRIGA]              DECIMAL (10)    NOT NULL,
    [NRRIGAPADRE]         DECIMAL (10)    NULL,
    [POSIZIONENODO]       DECIMAL (5)     NULL,
    [DESCRIZIONE]         VARCHAR (100)   NULL,
    [RIFERIMENTO]         VARCHAR (50)    CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_RIFERIMENTO] DEFAULT ('') NULL,
    [QTAVAL]              DECIMAL (16, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_QTAVAL] DEFAULT (0) NULL,
    [UMVAL]               VARCHAR (3)     CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_UMVAL] DEFAULT ('') NULL,
    [QTAVALPREV]          DECIMAL (16, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_QTAVALPREV] DEFAULT (0) NULL,
    [UMVALPREV]           VARCHAR (3)     CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_UMVALPREV] DEFAULT ('') NULL,
    [RIFTESTA]            DECIMAL (10)    NULL,
    [RIFRIGA]             INT             NULL,
    [ORIGINEEVENTO]       SMALLINT        NULL,
    [TIPONODO]            SMALLINT        NULL,
    [NATURARILEVAZIONE]   SMALLINT        CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_NATURARILEVAZIONE] DEFAULT (0) NULL,
    [VOCECOSTO]           VARCHAR (3)     NULL,
    [FORMULA]             VARCHAR (50)    NULL,
    [CONSUNTIVATORIP]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_CONSUNTIVATORIP] DEFAULT (0) NULL,
    [RISERVATORIP]        DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_RISERVATORIP] DEFAULT (0) NULL,
    [ORDINATORIP]         DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_ORDINATORIP] DEFAULT (0) NULL,
    [PREVISTORIP]         DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_PREVISTORIP] DEFAULT (0) NULL,
    [COSTOTOT]            DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_COSTOTOTRIP] DEFAULT (0) NULL,
    [CONSUNTIVATORIPEURO] DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_CONSUNTIVATORIPEURO] DEFAULT (0) NULL,
    [RISERVATORIPEURO]    DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_RISERVATORIPEURO] DEFAULT (0) NULL,
    [ORDINATORIPEURO]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_ORDINATORIPEURO] DEFAULT (0) NULL,
    [PREVISTORIPEURO]     DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_PREVISTORIPEURO] DEFAULT (0) NULL,
    [COSTOTOTEURO]        DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_COSTOTOTRIPEURO] DEFAULT (0) NULL,
    [COSTOUNIPREV]        DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_COSTOUNIPREV] DEFAULT (0) NULL,
    [COSTOUNIPREVEURO]    DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_COSTOUNIPREVEURO] DEFAULT (0) NULL,
    [COSTOTOTPREV]        DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_COSTOTOTPREV] DEFAULT (0) NULL,
    [COSTOTOTPREVEURO]    DECIMAL (19, 6) CONSTRAINT [DF_TEMPSTIMAFINIRECOMMCLI_COSTOTOTPREVEURO] DEFAULT (0) NULL,
    [UTENTEMODIFICA]      VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]        DATETIME        NOT NULL,
    [NRRIGAPREV]          DECIMAL (5)     NULL,
    [CODLIVELLO]          VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [RIFCOMMCLI] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSTIMAFINIRECOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSTIMAFINIRECOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSTIMAFINIRECOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSTIMAFINIRECOMMCLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSTIMAFINIRECOMMCLI] TO [Metodo98]
    AS [dbo];

