CREATE TABLE [dbo].[TEMPTOTALICONGRPARTITE] (
    [IDSESSIONE]          DECIMAL (5)     NOT NULL,
    [CONTO]               VARCHAR (7)     NOT NULL,
    [NRPARTITA]           VARCHAR (19)    NOT NULL,
    [DARE]                DECIMAL (19, 4) NULL,
    [DAREEURO]            DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [DAREVALUTA]          DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [AVERE]               DECIMAL (19, 4) NULL,
    [AVEREEURO]           DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [AVEREVALUTA]         DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADNONEMESSE]       DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADNONEMESSEEURO]   DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADNONEMESSEVALUTA] DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADEMESSE]          DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADEMESSEEURO]      DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADEMESSEVALUTA]    DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADINSOLUTE]        DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADINSOLUTEEURO]    DECIMAL (19, 4) DEFAULT ((0)) NULL,
    [SCADINSOLUTEVALUTA]  DECIMAL (19, 4) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TEMPTOTALICONGRPARTITE] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CONTO] ASC, [NRPARTITA] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPTOTALICONGRPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPTOTALICONGRPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPTOTALICONGRPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPTOTALICONGRPARTITE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPTOTALICONGRPARTITE] TO [Metodo98]
    AS [dbo];

