CREATE TABLE [dbo].[TEMPPROGPRODUZIONE] (
    [IDSESSIONE]        DECIMAL (10)    NOT NULL,
    [CODART]            VARCHAR (50)    NOT NULL,
    [PROG_ID]           DECIMAL (20)    NULL,
    [LIVELLO]           VARCHAR (1)     NULL,
    [SCMINIMA]          DECIMAL (16, 6) NULL,
    [SCMASSIMA]         DECIMAL (16, 6) NULL,
    [LIVRIORDINO]       DECIMAL (16, 6) NULL,
    [PROVENIENZA]       SMALLINT        NULL,
    [TIPOGESTIONE]      SMALLINT        NULL,
    [TIPOPRODOTTO]      SMALLINT        NULL,
    [ARTICOLOGHOST]     SMALLINT        NULL,
    [GESTIONEMATERIALI] SMALLINT        NULL,
    [VARESPLICITE]      VARCHAR (255)   NULL,
    [GIACENZA]          DECIMAL (16, 6) NULL,
    [UM]                VARCHAR (3)     NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [GGORIZZONTEART]    INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TEMPPROGPRODUZIONE] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CODART] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPPROGPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPPROGPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPPROGPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPPROGPRODUZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPPROGPRODUZIONE] TO [Metodo98]
    AS [dbo];

