CREATE TABLE [dbo].[TEMPEFFETTIPIANIFICAZIONE] (
    [IDSESSIONE] INT             NOT NULL,
    [FASE]       SMALLINT        NOT NULL,
    [TIPORECORD] SMALLINT        NULL,
    [CODART]     VARCHAR (50)    NULL,
    [CODCLIFOR]  VARCHAR (7)     NULL,
    [QUANTITA]   DECIMAL (16, 6) NULL
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPEFFETTIPIANIFICAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPEFFETTIPIANIFICAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPEFFETTIPIANIFICAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPEFFETTIPIANIFICAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPEFFETTIPIANIFICAZIONE] TO [Metodo98]
    AS [dbo];

