CREATE TABLE [dbo].[TEMPSALDIBILANCIO] (
    [CODMASTRO]   DECIMAL (5)     NOT NULL,
    [SALDO]       DECIMAL (19, 4) DEFAULT (0) NULL,
    [SALDOEURO]   DECIMAL (19, 4) DEFAULT (0) NULL,
    [DAREAVERE]   SMALLINT        NOT NULL,
    [NRTERMINALE] SMALLINT        NOT NULL,
    CONSTRAINT [PK_TEMPSALDIBILANCIO] PRIMARY KEY CLUSTERED ([CODMASTRO] ASC, [DAREAVERE] ASC, [NRTERMINALE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPSALDIBILANCIO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPSALDIBILANCIO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPSALDIBILANCIO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPSALDIBILANCIO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPSALDIBILANCIO] TO [Metodo98]
    AS [dbo];

