CREATE TABLE [dbo].[TEMPDOCPREL] (
    [PROGRESSIVO] DECIMAL (10) IDENTITY (1, 1) NOT NULL,
    [IDSESSIONE]  INT          NOT NULL,
    [IDTESTA]     DECIMAL (10) NOT NULL,
    [ESERCIZIO]   DECIMAL (5)  NOT NULL,
    [TIPO]        SMALLINT     NOT NULL,
    CONSTRAINT [PK_TEMPDOCPREL] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TEMPDOCPREL] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TEMPDOCPREL] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TEMPDOCPREL] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEMPDOCPREL] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TEMPDOCPREL] TO [Metodo98]
    AS [dbo];

