CREATE TABLE [dbo].[TESTAANALISIORDPROD] (
    [PROGRESSIVO]    DECIMAL (10)  NOT NULL,
    [NOMEANALISI]    VARCHAR (50)  NOT NULL,
    [DATAINIZIO]     DATETIME      NULL,
    [DATAFINE]       DATETIME      NULL,
    [NOTE]           VARCHAR (100) NULL,
    [DATAMODIFICA]   DATETIME      NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)  NOT NULL,
    CONSTRAINT [PK_TESTAANALISIORDPROD] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  UPDATE TRIGGER "TU_TESTAANALISIORDPROD" FOR TABLE "TESTAANALISIORDPROD"  */
CREATE TRIGGER TU_TESTAANALISIORDPROD ON TESTAANALISIORDPROD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  ALTER COLUMN PARENT CODE OF "TESTAANALISIORDPROD" FOR ALL CHILDREN IN "RIGHEANALISIORDPROD"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE RIGHEANALISIORDPROD
          SET   RIFTESTA = I1.PROGRESSIVO
         FROM   RIGHEANALISIORDPROD T2, INSERTED I1, DELETED D1
         WHERE  T2.RIFTESTA = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TESTAANALISIORDPROD" FOR TABLE "TESTAANALISIORDPROD"  */
CREATE TRIGGER TD_TESTAANALISIORDPROD ON TESTAANALISIORDPROD FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "RIGHEANALISIORDPROD"  */
    DELETE RIGHEANALISIORDPROD
    FROM   RIGHEANALISIORDPROD T2, DELETED T1
    WHERE  T2.RIFTESTA = T1.PROGRESSIVO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTAANALISIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTAANALISIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTAANALISIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTAANALISIORDPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTAANALISIORDPROD] TO [Metodo98]
    AS [dbo];

