CREATE TABLE [dbo].[TESTAPACKINGLIST] (
    [PROGRESSIVO]    DECIMAL (10)    NOT NULL,
    [CODCLIENTE]     VARCHAR (7)     NULL,
    [CODARTICOLO]    VARCHAR (50)    NULL,
    [QTARIF]         DECIMAL (16, 6) CONSTRAINT [DF_TESTAPACKINGLIST_QTARIF] DEFAULT (0) NULL,
    [UMRIF]          VARCHAR (3)     NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_TESTAPACKINGLIST] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTAPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTAPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTAPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTAPACKINGLIST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTAPACKINGLIST] TO [Metodo98]
    AS [dbo];

