CREATE TABLE [dbo].[TESTAMPS] (
    [PROGRESSIVO]     DECIMAL (10)  NOT NULL,
    [ESERCIZIO]       DECIMAL (5)   NULL,
    [CODICE]          VARCHAR (3)   NOT NULL,
    [NUMERO]          INT           NOT NULL,
    [RIFERIMENTO]     VARCHAR (30)  NOT NULL,
    [NUMEROFOGLIO]    INT           NOT NULL,
    [DATAEMISSIONE]   DATETIME      NULL,
    [FLGPRINCIPALE]   SMALLINT      NULL,
    [PERIODIRADICE]   SMALLINT      NULL,
    [NOTE]            VARCHAR (100) NULL,
    [UTENTEMODIFICA]  VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]    DATETIME      NOT NULL,
    [DATAINIZIOPIANO] DATETIME      NULL,
    CONSTRAINT [PK_TESTAMPS] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO

/* DELETE TRIGGER "TD_TESTAMPS" FOR TABLE "TESTAMPS" */
CREATE TRIGGER TD_TESTAMPS ON TESTAMPS FOR DELETE AS
BEGIN

DECLARE
@NUMROWS INT,
@ERRNO INT,
@ERRMSG VARCHAR(255)

SELECT @NUMROWS = @@ROWCOUNT
IF @NUMROWS = 0
RETURN

/* DELETE CASCADE */   /* per OGNI Tabella CHILD in Relazione */
/* DELETE ALL CHILDREN IN "Nome Tabella Child" */
DELETE RIGHEFORECAST
FROM RIGHEFORECAST T2, DELETED T1
WHERE T2.RIFPROGRESSIVO = T1.PROGRESSIVO

RETURN

/* ERRORS HANDLING */
ERROR:
RAISERROR (@ERRMSG, 1, 1)
ROLLBACK TRANSACTION

END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTAMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTAMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTAMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTAMPS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTAMPS] TO [Metodo98]
    AS [dbo];

