CREATE TABLE [dbo].[TESTACICLOPROD] (
    [PROGRESSIVO]         DECIMAL (10)    NOT NULL,
    [CODCICLO]            VARCHAR (50)    NULL,
    [VERSIONECICLO]       VARCHAR (10)    NULL,
    [DSCVERSIONE]         VARCHAR (80)    NULL,
    [STATOVERSIONE]       DECIMAL (5)     NOT NULL,
    [VALIDITACICLO]       DATETIME        NOT NULL,
    [VERSIONEDBA]         VARCHAR (10)    NULL,
    [CICLOSTANDARD]       SMALLINT        DEFAULT (0) NULL,
    [NOTECICLO]           VARCHAR (100)   NULL,
    [UM]                  VARCHAR (3)     NOT NULL,
    [QUANTITARIF]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]      VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]        DATETIME        NOT NULL,
    [FLGNOTRASFORMAZIONE] SMALLINT        NULL,
    [FLGCICLOCTRASF]      SMALLINT        NULL,
    CONSTRAINT [TESTACICLOPROD_PK] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CICLOSTANDARD_CHECK] CHECK ([CICLOSTANDARD] is null or [CICLOSTANDARD] = 0 or [CICLOSTANDARD] = 1)
);


GO
CREATE NONCLUSTERED INDEX [IX_TESTACICLOPROD99]
    ON [dbo].[TESTACICLOPROD]([CODCICLO] ASC);


GO

/*  INSERT TRIGGER "TI_TESTACICLOPROD" FOR TABLE "TESTACICLOPROD"  */
CREATE TRIGGER TI_TESTACICLOPROD ON TESTACICLOPROD FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABSTATOVERSIONECICLO" MUST EXIST WHEN INSERTING A CHILD IN "TESTACICLOPROD"  */
    IF UPDATE(STATOVERSIONE)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABSTATOVERSIONECICLO T1, INSERTED T2
           WHERE  T1.CODICE = T2.STATOVERSIONE) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABSTATOVERSIONECICLO". Cannot create child in "TESTACICLOPROD".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TESTACICLOPROD" FOR TABLE "TESTACICLOPROD"  */
CREATE TRIGGER TU_TESTACICLOPROD ON TESTACICLOPROD FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABSTATOVERSIONECICLO" MUST EXIST WHEN UPDATING A CHILD IN "TESTACICLOPROD"  */
      IF UPDATE(STATOVERSIONE)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABSTATOVERSIONECICLO T1, INSERTED T2
             WHERE  T1.CODICE = T2.STATOVERSIONE) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABSTATOVERSIONECICLO" does not exist. Cannot modify child in "TESTACICLOPROD".'
               GOTO ERROR
            END
      END
      
      /*  MODIFY PARENT CODE OF "TESTACICLOPROD" FOR ALL CHILDREN IN "RIGHECICLOPROD"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE RIGHECICLOPROD
          SET   PROGRESSIVO = I1.PROGRESSIVO
         FROM   RIGHECICLOPROD T2, INSERTED I1, DELETED D1
         WHERE  T2.PROGRESSIVO = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END
      
      /*  MODIFY PARENT CODE OF "TESTACICLOPROD" FOR ALL CHILDREN IN "EXTRACICLI"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE EXTRACICLI
          SET   PROGRESSIVO = I1.PROGRESSIVO
         FROM   EXTRACICLI T2, INSERTED I1, DELETED D1
         WHERE  T2.PROGRESSIVO = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_TESTACICLOPROD" FOR TABLE "TESTACICLOPROD"  */
CREATE TRIGGER TD_TESTACICLOPROD ON TESTACICLOPROD FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "RIGHECICLOPROD"  */
    DELETE RIGHECICLOPROD
    FROM   RIGHECICLOPROD T2, DELETED T1
    WHERE  T2.PROGRESSIVO = T1.PROGRESSIVO
    
    /*  DELETE ALL CHILDREN IN "EXTRACICLI"  */
    DELETE EXTRACICLI
    FROM   EXTRACICLI T2, DELETED T1
    WHERE  T2.PROGRESSIVO = T1.PROGRESSIVO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTACICLOPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTACICLOPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTACICLOPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTACICLOPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTACICLOPROD] TO [Metodo98]
    AS [dbo];

