CREATE TABLE [dbo].[TESTACICLOORDINE] (
    [PROGRESSIVO]      DECIMAL (10)    NOT NULL,
    [CODCICLO]         VARCHAR (50)    NULL,
    [VERSIONECICLO]    VARCHAR (10)    NULL,
    [DSCVERSIONE]      VARCHAR (80)    NULL,
    [STATOVERSIONE]    DECIMAL (5)     NOT NULL,
    [VALIDITACICLO]    DATETIME        NOT NULL,
    [VERSIONEDBA]      VARCHAR (10)    NULL,
    [CICLOSTANDARD]    SMALLINT        DEFAULT (0) NULL,
    [NOTECICLO]        VARCHAR (100)   NULL,
    [UM]               VARCHAR (3)     NOT NULL,
    [QUANTITARIF]      DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [TIPOCICLO]        SMALLINT        DEFAULT (0) NULL,
    [IDTESTACOMM]      DECIMAL (10)    NULL,
    [IDRIGACOMM]       INT             NULL,
    [LOTTOASSEGNATO]   VARCHAR (15)    NULL,
    [DATAINIZIOLAV]    DATETIME        NULL,
    [TIPOVALUTAZIONE]  SMALLINT        DEFAULT (1) NULL,
    [UTENTEMODIFICA]   VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]     DATETIME        NOT NULL,
    [FLGRIVALUTACICLO] SMALLINT        DEFAULT (0) NULL,
    [FLGCICLOCTRASF]   SMALLINT        NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CHECK ([CICLOSTANDARD] is null or [CICLOSTANDARD] = 0 or [CICLOSTANDARD] = 1)
);


GO

/*  DELETE TRIGGER "TD_TESTACICLOORDINE" FOR TABLE "TESTACICLOORDINE"  */
CREATE TRIGGER TD_TESTACICLOORDINE ON TESTACICLOORDINE FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "RIGHECICLOORDINE"  */
    DELETE RIGHECICLOORDINE
    FROM   RIGHECICLOORDINE T2, DELETED T1
    WHERE  T2.PROGRESSIVO = T1.PROGRESSIVO
    
    /*  DELETE ALL CHILDREN IN "EXTRACICLIORD"  */
    DELETE EXTRACICLIORD
    FROM   EXTRACICLIORD T2, DELETED T1
    WHERE  T2.PROGRESSIVO = T1.PROGRESSIVO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_TESTACICLOORDINE" FOR TABLE "TESTACICLOORDINE"  */
CREATE TRIGGER TU_TESTACICLOORDINE ON TESTACICLOORDINE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN
      
      /*  MODIFY PARENT CODE OF "TESTACICLOORDINE" FOR ALL CHILDREN IN "RIGHECICLOORDINE"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE RIGHECICLOORDINE
          SET   PROGRESSIVO = I1.PROGRESSIVO
         FROM   RIGHECICLOORDINE T2, INSERTED I1, DELETED D1
         WHERE  T2.PROGRESSIVO = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END
      
      /*  MODIFY PARENT CODE OF "TESTACICLOORDINE" FOR ALL CHILDREN IN "EXTRACICLIORD"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE EXTRACICLIORD
          SET   PROGRESSIVO = I1.PROGRESSIVO
         FROM   EXTRACICLIORD T2, INSERTED I1, DELETED D1
         WHERE  T2.PROGRESSIVO = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTACICLOORDINE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTACICLOORDINE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTACICLOORDINE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTACICLOORDINE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTACICLOORDINE] TO [Metodo98]
    AS [dbo];

