CREATE TABLE [dbo].[TESTEDISTINTAINCASSI] (
    [PROGRESSIVO]      DECIMAL (10)  NOT NULL,
    [ESERCIZIO]        DECIMAL (5)   NOT NULL,
    [DATADISTINTA]     DATETIME      NOT NULL,
    [CODAGENTE]        VARCHAR (7)   NULL,
    [DATAREG]          DATETIME      NULL,
    [NRREGCONT]        DECIMAL (10)  NULL,
    [NOTE]             VARCHAR (255) NULL,
    [UTENTEMODIFICA]   VARCHAR (25)  NOT NULL,
    [DATAMODIFICA]     DATETIME      NOT NULL,
    [NOMEIMPOSTAZIONE] VARCHAR (50)  NULL,
    CONSTRAINT [PK_TESTEDISTINTAINCASSI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TESTEDISTINTAINCASSI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TESTEDISTINTAINCASSI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TESTEDISTINTAINCASSI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TESTEDISTINTAINCASSI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TESTEDISTINTAINCASSI] TO [Metodo98]
    AS [dbo];

