CREATE TABLE [dbo].[TIPOREGISTROIVA] (
    [CODICE]         DECIMAL (5)  NOT NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [TAPPO]          DECIMAL (5)  NULL,
    [TIPO]           SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [SEZIONALEIVA]   VARCHAR (1)  NULL,
    CONSTRAINT [PK_TIPOREGISTROIVA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [TIPOREGIVA_DSC]
    ON [dbo].[TIPOREGISTROIVA]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TIPOREGISTROIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TIPOREGISTROIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TIPOREGISTROIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TIPOREGISTROIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TIPOREGISTROIVA] TO [Metodo98]
    AS [dbo];

