CREATE TABLE [dbo].[TIPOLOGIEDICARICO] (
    [CODICE]             VARCHAR (5)      NOT NULL,
    [DESCRIZIONE]        VARCHAR (80)     NULL,
    [UMOFFERTA]          VARCHAR (3)      NULL,
    [VOLUMEPERUNITA]     DECIMAL (16, 6)  NULL,
    [PESOSPECIFICO]      DECIMAL (16, 6)  NULL,
    [FLAGSOVRAPPONIBILE] SMALLINT         NULL,
    [FATTORECONVERSIONE] DECIMAL (20, 10) NULL,
    [UTENTEMODIFICA]     VARCHAR (25)     NOT NULL,
    [DATAMODIFICA]       DATETIME         NOT NULL,
    CONSTRAINT [PK_TIPOLOGIEDICARICO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TIPOLOGIEDICARICO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TIPOLOGIEDICARICO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TIPOLOGIEDICARICO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TIPOLOGIEDICARICO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TIPOLOGIEDICARICO] TO [Metodo98]
    AS [dbo];

