CREATE TABLE [dbo].[TMP_GIACENZEMAGAZZINIRAGG] (
    [IDSESSIONE]     DECIMAL (10)    NOT NULL,
    [CODARTICOLO]    VARCHAR (50)    NOT NULL,
    [RAGGRUPPAMENTO] VARCHAR (80)    NOT NULL,
    [GIACENZA]       DECIMAL (16, 6) DEFAULT ((0)) NOT NULL,
    [IMPEGNATO]      DECIMAL (16, 6) DEFAULT ((0)) NOT NULL,
    [ORDINATO]       DECIMAL (16, 6) DEFAULT ((0)) NOT NULL,
    [DISPONIBILITA]  DECIMAL (16, 6) DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CODARTICOLO] ASC, [RAGGRUPPAMENTO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TMP_GIACENZEMAGAZZINIRAGG] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TMP_GIACENZEMAGAZZINIRAGG] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TMP_GIACENZEMAGAZZINIRAGG] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TMP_GIACENZEMAGAZZINIRAGG] TO [Metodo98]
    AS [dbo];

