CREATE TABLE [dbo].[TMP_TABPAGAMENTI] (
    [CODICE]             VARCHAR (4)  NOT NULL,
    [DESCRIZIONE]        VARCHAR (80) NULL,
    [SCONTO]             VARCHAR (10) NULL,
    [NUMERORATE]         SMALLINT     NULL,
    [ANNOCOMMERCIALE]    SMALLINT     NULL,
    [DESCRIZIONELINGUA1] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA2] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA3] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA4] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA5] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA6] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA7] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA8] VARCHAR (80) NULL,
    [DESCRIZIONELINGUA9] VARCHAR (80) NULL,
    [INFRAZIONE]         SMALLINT     NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    [MODPAGINTRA]        VARCHAR (1)  NULL,
    PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TMP_TABPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TMP_TABPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TMP_TABPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TMP_TABPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TMP_TABPAGAMENTI] TO [Metodo98]
    AS [dbo];

