CREATE TABLE [dbo].[TMPCESAMM] (
    [IDSESSIONE]        INT             NOT NULL,
    [CESPITE]           VARCHAR (10)    NOT NULL,
    [ANNO]              SMALLINT        NOT NULL,
    [IMPORTOAMMEURO]    DECIMAL (19, 4) NULL,
    [IMPORTONONAMMEURO] DECIMAL (19, 4) NULL,
    [IMPORTOSAEURO]     DECIMAL (19, 4) NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [IMPORTOIAEURO]     DECIMAL (19, 4) NULL,
    CONSTRAINT [PK_TMPCESAMM] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CESPITE] ASC, [ANNO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TMPCESAMM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TMPCESAMM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TMPCESAMM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TMPCESAMM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TMPCESAMM] TO [Metodo98]
    AS [dbo];

