CREATE TABLE [dbo].[TMPPENNAORC] (
    [IDSESSIONE]     DECIMAL (5)     NOT NULL,
    [CODART]         VARCHAR (50)    NOT NULL,
    [QTA]            DECIMAL (19, 6) CONSTRAINT [DF_TMPPENNAORC_QTA] DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_TMPPENNAORC]
    ON [dbo].[TMPPENNAORC]([IDSESSIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TMPPENNAORC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TMPPENNAORC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TMPPENNAORC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TMPPENNAORC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TMPPENNAORC] TO [Metodo98]
    AS [dbo];

