CREATE TABLE [dbo].[TP_BORDERAUXRIGHE] (
    [PROGRESSIVO]    INT             NOT NULL,
    [IDTESTA]        INT             NOT NULL,
    [NUMERODOC]      DECIMAL (10)    NOT NULL,
    [TIPODOC]        VARCHAR (3)     NOT NULL,
    [CODCLIENTE]     VARCHAR (7)     NOT NULL,
    [TOTRIGAEURO]    DECIMAL (19, 4) NOT NULL,
    [TOTRIGAVALUTA]  DECIMAL (19, 4) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [DATADOC]        DATETIME        NULL,
    CONSTRAINT [PK_TP_BORDERAUXRIGHE] PRIMARY KEY NONCLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_BORDERAUXRIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_BORDERAUXRIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_BORDERAUXRIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_BORDERAUXRIGHE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_BORDERAUXRIGHE] TO [Metodo98]
    AS [dbo];

