CREATE TABLE [dbo].[TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI] (
    [CODBUYER]       VARCHAR (7)  NOT NULL,
    [CODDEPOSITO]    VARCHAR (10) NOT NULL,
    [CODFORNITORE]   VARCHAR (7)  NOT NULL,
    [CODFAMIGLIA]    DECIMAL (5)  NOT NULL,
    [CODREPARTO]     DECIMAL (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODBUYER] ASC, [CODDEPOSITO] ASC, [CODFORNITORE] ASC, [CODFAMIGLIA] ASC, [CODREPARTO] ASC),
    FOREIGN KEY ([CODFAMIGLIA]) REFERENCES [dbo].[TabFamigliePOS] ([Codice]),
    FOREIGN KEY ([CODREPARTO]) REFERENCES [dbo].[TabRepartiPOS] ([Codice])
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CONFIGURAZIONIBUYER_FAMIGLIEREPARTI] TO [Metodo98]
    AS [dbo];

