CREATE TABLE [dbo].[TP_CONFIGESPORTAZ] (
    [TIPO]                  CHAR (1)     NOT NULL,
    [CODICE]                VARCHAR (7)  NOT NULL,
    [TABELLEINESPORTAZIONE] VARCHAR (50) NULL,
    [GRUPPO]                DECIMAL (5)  NULL,
    [CATEGORIA]             DECIMAL (5)  NULL,
    [CATEGORIASTATISTICA]   DECIMAL (5)  NULL,
    [ARTICOLICONTIPOLOGIA]  VARCHAR (50) NULL,
    [TIPORIGA]              CHAR (1)     NOT NULL,
    [UTENTEMODIFICA]        VARCHAR (25) NULL,
    [DATAMODIFICA]          DATETIME     NULL,
    [FAMIGLIAPOS]           DECIMAL (5)  NULL,
    [REPARTOPOS]            DECIMAL (5)  NULL
);


GO
CREATE CLUSTERED INDEX [IX_TP_CONFIGESPORTAZ]
    ON [dbo].[TP_CONFIGESPORTAZ]([TIPORIGA] ASC, [TIPO] ASC, [CODICE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_TP_CONFIGESPORTAZ_1]
    ON [dbo].[TP_CONFIGESPORTAZ]([TIPORIGA] ASC, [TIPO] ASC, [CODICE] ASC, [GRUPPO] ASC, [CATEGORIA] ASC, [CATEGORIASTATISTICA] ASC, [ARTICOLICONTIPOLOGIA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CONFIGESPORTAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CONFIGESPORTAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CONFIGESPORTAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CONFIGESPORTAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CONFIGESPORTAZ] TO [Metodo98]
    AS [dbo];

