CREATE TABLE [dbo].[TP_CONFIG_LISTINI_VENDITA_TESTE] (
    [Progressivo]    DECIMAL (18) IDENTITY (1, 1) NOT NULL,
    [NOME]           VARCHAR (50) NOT NULL,
    [TIPO]           VARCHAR (50) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [ARROTONDAMENTO] SMALLINT     NULL,
    [ATTIVA]         SMALLINT     NULL,
    [DATAEFFETTO]    DATETIME     NULL,
    CONSTRAINT [PK_TP_CONFIG_LISTINI_VENDITA_TESTE] PRIMARY KEY CLUSTERED ([Progressivo] ASC, [NOME] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_CONFIG_LISTINI_VENDITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_CONFIG_LISTINI_VENDITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_CONFIG_LISTINI_VENDITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_CONFIG_LISTINI_VENDITA_TESTE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_CONFIG_LISTINI_VENDITA_TESTE] TO [Metodo98]
    AS [dbo];

