CREATE TABLE [dbo].[TP_DOCSTATAG] (
    [CODAGENTE]      VARCHAR (7)  NOT NULL,
    [DOCUMENTI_RG1]  VARCHAR (60) NULL,
    [DOCUMENTI_RG2]  VARCHAR (60) NULL,
    [DOCUMENTI_RG3]  VARCHAR (60) NULL,
    [CAUSALI_RG1]    VARCHAR (60) NULL,
    [CAUSALI_RG2]    VARCHAR (60) NULL,
    [CAUSALI_RG3]    VARCHAR (60) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODAGENTE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_DOCSTATAG] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_DOCSTATAG] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_DOCSTATAG] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_DOCSTATAG] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_DOCSTATAG] TO [Metodo98]
    AS [dbo];

