CREATE TABLE [dbo].[TP_EXTRAFORNITORI] (
    [CODCONTO]           VARCHAR (7)  NOT NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    [TP_Giorno_Riordino] NUMERIC (1)  NULL,
    [TP_TipoFor]         CHAR (1)     NULL,
    [TP_TRev]            NUMERIC (18) NULL,
    [TP_FMCasa]          NUMERIC (18) NULL,
    [TP_FMTab]           NUMERIC (18) NULL,
    [TP_Ofprezscm]       SMALLINT     NULL,
    [Tp_Esportabile]     SMALLINT     DEFAULT ((0)) NULL,
    [TP_USAPREZZIPART]   SMALLINT     DEFAULT ((0)) NOT NULL,
    [DISABGSTSCNTLOG]    SMALLINT     DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TP_EXTRAFORNITORI] PRIMARY KEY CLUSTERED ([CODCONTO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TP_EXTRAFORNITORI_CODCONTO] FOREIGN KEY ([CODCONTO]) REFERENCES [dbo].[ANAGRAFICACF] ([CODCONTO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_EXTRAFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_EXTRAFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_EXTRAFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_EXTRAFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_EXTRAFORNITORI] TO [Metodo98]
    AS [dbo];

