CREATE TABLE [dbo].[TP_PUNTIVENDITA] (
    [CODCONTO]           VARCHAR (7)   NOT NULL,
    [DSCCONTO]           VARCHAR (80)  NULL,
    [NRLISTINO]          NUMERIC (5)   NOT NULL,
    [AZIENDA]            VARCHAR (50)  NULL,
    [DEPOSITO]           VARCHAR (10)  NULL,
    [ORARIOCOLLEGAMENTO] VARCHAR (8)   NULL,
    [ULTPREPAR]          DATETIME      NULL,
    [ULTTRASF]           DATETIME      NULL,
    [ULTRIC]             DATETIME      NULL,
    [ATTIVO]             BIT           NULL,
    [FORNITORE]          VARCHAR (7)   NULL,
    [RANGEDA]            INT           NULL,
    [RANGEA]             INT           NULL,
    [TIPOCODIFICA]       CHAR (1)      NULL,
    [TIPOELABORAZIONE]   CHAR (3)      NULL,
    [PRIORITA]           SMALLINT      NULL,
    [PATHR]              VARCHAR (100) NULL,
    [PATHT]              VARCHAR (100) NULL,
    [UTENTEMODIFICA]     VARCHAR (25)  NULL,
    [DATAMODIFICA]       DATETIME      NULL,
    [TIPOTRASFDATI]      SMALLINT      NULL,
    [CODMASTRO]          DECIMAL (5)   NULL,
    [CODLISTINO]         DECIMAL (5)   NULL,
    [TIPOMSG]            SMALLINT      NULL,
    [RANGEIDDA]          DECIMAL (19)  NULL,
    [RANGEIDA]           DECIMAL (19)  NULL,
    [NRLISTVENACQ]       DECIMAL (5)   NULL,
    [EXPDATADOC]         DATETIME      DEFAULT ('1990-01-01') NULL,
    CONSTRAINT [PK_TP_PUNTIVENDITA] PRIMARY KEY CLUSTERED ([CODCONTO] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE TRIGGER TD_TP_PUNTIVENDITA ON TP_PUNTIVENDITA FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
   /*  DELETE ALL CHILDREN IN "TP_PUNTIVENDITA"  */
    DELETE TP_TIPIAGPV
    FROM   TP_TIPIAGPV T2, DELETED T1
    WHERE  T2.ENTITA = T1.CODCONTO

/*  DELETE ALL CHILDREN IN "TP_PUNTIVENDITA"  */
    DELETE TP_CONFIGESPORTAZ
    FROM   TP_CONFIGESPORTAZ T2, DELETED T1
    WHERE  T2.CODICE = T1.CODCONTO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_PUNTIVENDITA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_PUNTIVENDITA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_PUNTIVENDITA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_PUNTIVENDITA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_PUNTIVENDITA] TO [Metodo98]
    AS [dbo];

