CREATE TABLE [dbo].[TP_TRASPORTOCOSTOACQARTICOLI] (
    [CODART]                 VARCHAR (50)    NOT NULL,
    [NRRIFPARTITA]           VARCHAR (15)    NOT NULL,
    [CODDEPOSITO]            VARCHAR (10)    NOT NULL,
    [COSTOMEDIOPEDANA]       DECIMAL (19, 6) NOT NULL,
    [COSTOMEDIOPEZZOXPEDANA] DECIMAL (19, 6) NOT NULL,
    [COSTOMEDIOPEZZOXKG]     DECIMAL (19, 6) NOT NULL,
    [UTENTEMODIFICA]         VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]           DATETIME        NOT NULL,
    [Raggruppa]              BIT             DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODART] ASC, [NRRIFPARTITA] ASC, [CODDEPOSITO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_TRASPORTOCOSTOACQARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_TRASPORTOCOSTOACQARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_TRASPORTOCOSTOACQARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_TRASPORTOCOSTOACQARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_TRASPORTOCOSTOACQARTICOLI] TO [Metodo98]
    AS [dbo];

