CREATE TABLE [dbo].[TP_TMP_STPLSTCONFIGSCNT] (
    [IDSESSIONE]          DECIMAL (5)     DEFAULT (0) NOT NULL,
    [CODART]              VARCHAR (50)    NOT NULL,
    [NRLISTINO]           DECIMAL (5)     NOT NULL,
    [UM]                  VARCHAR (3)     NOT NULL,
    [IDRIGA]              INT             NOT NULL,
    [CODICE]              VARCHAR (5)     NOT NULL,
    [DESCRIZIONE]         VARCHAR (200)   NULL,
    [TIPOSCONTO]          CHAR (1)        NULL,
    [SEGNO]               CHAR (1)        NULL,
    [VALORE]              DECIMAL (19, 6) DEFAULT (0) NULL,
    [TIPORIGHESCONTO]     VARCHAR (5)     NULL,
    [INOUTFATTURA]        SMALLINT        DEFAULT (0) NULL,
    [SCONTOPERCINFATT]    DECIMAL (19, 6) DEFAULT (0) NULL,
    [VALORESCONTOINFATT]  DECIMAL (19, 6) DEFAULT (0) NULL,
    [SCONTOPERCOUTFATT]   DECIMAL (19, 6) DEFAULT (0) NULL,
    [VALORESCONTOOUTFATT] DECIMAL (19, 6) DEFAULT (0) NULL,
    [UTENTEMODIFICA]      VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]        DATETIME        NOT NULL,
    CONSTRAINT [PK_TP_TMP_STPLSTCONFIGSCNT] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CODART] ASC, [NRLISTINO] ASC, [UM] ASC, [IDRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_TMP_STPLSTCONFIGSCNT] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_TMP_STPLSTCONFIGSCNT] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_TMP_STPLSTCONFIGSCNT] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_TMP_STPLSTCONFIGSCNT] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_TMP_STPLSTCONFIGSCNT] TO [Metodo98]
    AS [dbo];

