CREATE TABLE [dbo].[TP_TESTEVBANCOPAGAMENTI] (
    [PROGRESSIVO]    NUMERIC (18)    NOT NULL,
    [NUMERORIGA]     NUMERIC (18)    NOT NULL,
    [MODPAGAMENTO]   DECIMAL (5)     NOT NULL,
    [VALORELIRE]     DECIMAL (19, 4) NULL,
    [VALOREEURO]     DECIMAL (19, 4) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_TP_TESTEVBANCOPAGAMENTI]
    ON [dbo].[TP_TESTEVBANCOPAGAMENTI]([PROGRESSIVO] ASC, [NUMERORIGA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_TESTEVBANCOPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_TESTEVBANCOPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_TESTEVBANCOPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_TESTEVBANCOPAGAMENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_TESTEVBANCOPAGAMENTI] TO [Metodo98]
    AS [dbo];

