CREATE TABLE [dbo].[TRASPORTO_CAD_REGOLE_GIORNIESCLUSI] (
    [PROGRESSIVO]       DECIMAL (18)    NOT NULL,
    [PROGRESSIVOREGOLA] DECIMAL (5)     NOT NULL,
    [TIPOCALCOLO]       DECIMAL (5)     DEFAULT ((3)) NULL,
    [CODICE]            VARCHAR (5)     DEFAULT ((0)) NOT NULL,
    [LUNEDI]            SMALLINT        DEFAULT ((0)) NOT NULL,
    [MARTEDI]           SMALLINT        DEFAULT ((0)) NOT NULL,
    [MERCOLEDI]         SMALLINT        DEFAULT ((0)) NOT NULL,
    [GIOVEDI]           SMALLINT        DEFAULT ((0)) NOT NULL,
    [VENERDI]           SMALLINT        DEFAULT ((0)) NOT NULL,
    [SABATO]            SMALLINT        DEFAULT ((0)) NOT NULL,
    [DOMENICA]          SMALLINT        DEFAULT ((0)) NOT NULL,
    [PREZZO]            DECIMAL (19, 6) DEFAULT ((0)) NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC),
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_GIORNIESCLUSI_TRASPORTO_CAD_REGOLE] FOREIGN KEY ([PROGRESSIVOREGOLA]) REFERENCES [dbo].[TRASPORTO_CAD_REGOLE] ([PROGRESSIVO]) ON DELETE CASCADE,
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_GIORNIESCLUSI_TRASPORTO_CAD_TIPOCALCOLO] FOREIGN KEY ([TIPOCALCOLO]) REFERENCES [dbo].[TRASPORTO_CAD_TIPOCALCOLO] ([CODICE]) ON DELETE SET DEFAULT,
    CONSTRAINT [FK_TRASPORTO_CAD_REGOLE_GIORNIESCLUSI_TRASPORTO_CDA_CODICI] FOREIGN KEY ([CODICE]) REFERENCES [dbo].[TRASPORTO_CAD_CODICI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_GIORNIESCLUSI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_GIORNIESCLUSI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_GIORNIESCLUSI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_GIORNIESCLUSI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRASPORTO_CAD_REGOLE_GIORNIESCLUSI] TO [Metodo98]
    AS [dbo];

