CREATE TABLE [dbo].[TRASPORTO_CAD_EXTRAGENERICI] (
    [PROGRESSIVOFILTRO]    DECIMAL (18) NOT NULL,
    [PROGRESSIVOREGOLEQTA] DECIMAL (18) NOT NULL,
    [UTENTEMODIFICA]       VARCHAR (25) NOT NULL,
    [DATAMODIFICA]         DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVOFILTRO] ASC, [PROGRESSIVOREGOLEQTA] ASC),
    CONSTRAINT [FK_TRASPORTO_CAD_EXTRAGENERICI_TRASPORTO_CAD_FILTRI] FOREIGN KEY ([PROGRESSIVOFILTRO]) REFERENCES [dbo].[TRASPORTO_CAD_FILTRI] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRASPORTO_CAD_EXTRAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRASPORTO_CAD_EXTRAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRASPORTO_CAD_EXTRAGENERICI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRASPORTO_CAD_EXTRAGENERICI] TO [Metodo98]
    AS [dbo];

