CREATE TABLE [dbo].[TRIBUTIFORNITORI] (
    [CODFORNITORE]   VARCHAR (7)  NOT NULL,
    [CODTRIBUTO]     DECIMAL (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_TRIBUTIFORNITORI] PRIMARY KEY CLUSTERED ([CODFORNITORE] ASC, [CODTRIBUTO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TRIBUTIFORNITORI_CODFORNITORE] FOREIGN KEY ([CODFORNITORE]) REFERENCES [dbo].[ANAGRAFICACF] ([CODCONTO]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_TRIBUTIFORNITORI_CODTRIBUTO] FOREIGN KEY ([CODTRIBUTO]) REFERENCES [dbo].[TABTRIBUTI] ([CODICE])
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[TRIBUTIFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TRIBUTIFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TRIBUTIFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TRIBUTIFORNITORI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TRIBUTIFORNITORI] TO [Metodo98]
    AS [dbo];

