CREATE TABLE [dbo].[VALORICAMBIO] (
    [CODCAMBIO]      DECIMAL (5)     NOT NULL,
    [DATA]           DATETIME        NOT NULL,
    [VALORE]         DECIMAL (13, 6) DEFAULT (1) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    CONSTRAINT [PK_VALORICAMBIO] PRIMARY KEY CLUSTERED ([CODCAMBIO] ASC, [DATA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_VALORICAMBIO_CODCAMBIO] FOREIGN KEY ([CODCAMBIO]) REFERENCES [dbo].[TABCAMBI] ([CODICE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [VCMB_DATA]
    ON [dbo].[VALORICAMBIO]([DATA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[VALORICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VALORICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VALORICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VALORICAMBIO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VALORICAMBIO] TO [Metodo98]
    AS [dbo];

