
CREATE PROCEDURE [dbo].[CCT_Proc_XmlContentInfo]
(
    @CodTipologia       Decimal(10,0),
    @CodDocumento       Decimal(10,0),
    @NomeFile           varchar(50)
)
AS
BEGIN
    select 
        TD.NUMERODOC,
        TD.NUMRIFDOC,
        TD.DATADOC,
        TD.DATARIFDOC,
        TD.ESERCIZIO,
        /*Soggetto Produttore*/
        'IT' AS PAESE_PROD,
        TDT.PARTITAIVA AS PARTITAIVA_PROD,
        TDT.CODICEFISCALE AS CODICEFISCALE_PROD,
        (Select (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN '' ELSE TDT.RAGSOCCOGNOME END) ELSE '' END) AS [text()] FOR XML PATH('')) AS DENOMINAZIONE_PROD,
        (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCCOGNOME ELSE '' END) ELSE '' END) AS COGNOME_PROD,
        (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCNOME ELSE '' END) ELSE '' END) AS NOME_PROD,
        /*Soggetto Titolare*/
        'IT' AS PAESE_TTLR,
        TDT.PARTITAIVA AS PARTITAIVA_TTLR,
        TDT.CODICEFISCALE AS CODICEFISCALE_TTLR,
        (Select (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN '' ELSE TDT.RAGSOCCOGNOME END) ELSE '' END) AS [text()] FOR XML PATH('')) AS DENOMINAZIONE_TTLR,
        (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCCOGNOME ELSE '' END) ELSE '' END) AS COGNOME_TTLR,
        (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCNOME ELSE '' END) ELSE '' END) AS NOME_TTLR,
        /*Soggetto Origine*/
        (CASE WHEN TS.CliFor = 'F' THEN ACF.CODICEISO ELSE 'IT' END) AS PAESE_ORGN,
        (CASE WHEN TS.CliFor = 'F' THEN ACF.PARTITAIVA ELSE TDT.PARTITAIVA END) AS PARTITAIVA_ORGN,
        (CASE WHEN TS.CliFor = 'F' THEN ACF.CODFISCALE ELSE TDT.CODICEFISCALE END) AS CODICEFISCALE_ORGN,
        (Select (CASE WHEN TS.CliFor = 'F' THEN (CASE WHEN ACF.FLGPERSFISICA = 1 THEN (CASE WHEN ACF.COGNOMEPERSFIS <> '' AND ACF.NOMEPERSFIS <> '' THEN '' ELSE ACF.DSCCONTO1 END) ELSE ACF.DSCCONTO1 END) ELSE (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN '' ELSE TDT.RAGSOCCOGNOME END) ELSE '' END) END) AS [text()] FOR XML PATH('')) AS DENOMINAZIONE_ORGN,
        (CASE WHEN TS.CliFor = 'F' THEN (CASE WHEN ACF.FLGPERSFISICA = 1 THEN (CASE WHEN ACF.COGNOMEPERSFIS <> '' AND ACF.NOMEPERSFIS <> '' THEN ACF.COGNOMEPERSFIS ELSE '' END) ELSE '' END) ELSE (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCCOGNOME ELSE '' END) ELSE '' END) END) AS COGNOME_ORGN,
        (CASE WHEN TS.CliFor = 'F' THEN (CASE WHEN ACF.FLGPERSFISICA = 1 THEN (CASE WHEN ACF.COGNOMEPERSFIS <> '' AND ACF.NOMEPERSFIS <> '' THEN ACF.NOMEPERSFIS ELSE '' END) ELSE '' END) ELSE (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCNOME ELSE '' END) ELSE '' END) END) AS NOME_ORGN,
        /*Soggetto Destinazione*/
        (CASE WHEN TS.CliFor = 'F' THEN 'IT' ELSE ACF.CODICEISO END) AS PAESE_DSTN,
        (CASE WHEN TS.CliFor = 'F' THEN TDT.PARTITAIVA ELSE ACF.PARTITAIVA END) AS PARTITAIVA_DSTN,
        (CASE WHEN TS.CliFor = 'F' THEN TDT.CODICEFISCALE ELSE ACF.CODFISCALE END) AS CODICEFISCALE_DSTN,
        (Select (CASE WHEN TS.CliFor = 'F' THEN (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN '' ELSE TDT.RAGSOCCOGNOME END) ELSE '' END) ELSE (CASE WHEN ACF.FLGPERSFISICA = 1 THEN (CASE WHEN ACF.COGNOMEPERSFIS <> '' AND ACF.NOMEPERSFIS <> '' THEN '' ELSE ACF.DSCCONTO1 END) ELSE ACF.DSCCONTO1 END) END) AS [text()] FOR XML PATH('')) AS DENOMINAZIONE_DSTN,
        (CASE WHEN TS.CliFor = 'F' THEN (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCCOGNOME ELSE '' END) ELSE '' END) ELSE (CASE WHEN ACF.FLGPERSFISICA = 1 THEN (CASE WHEN ACF.COGNOMEPERSFIS <> '' AND ACF.NOMEPERSFIS <> '' THEN ACF.COGNOMEPERSFIS ELSE '' END) ELSE '' END) END) AS COGNOME_DSTN,
        (CASE WHEN TS.CliFor = 'F' THEN (CASE WHEN TDT.PERSONAFG = 'G' THEN (CASE WHEN TDT.RAGSOCCOGNOME <> '' AND TDT.RAGSOCNOME <> '' THEN TDT.RAGSOCNOME ELSE '' END) ELSE '' END) ELSE (CASE WHEN ACF.FLGPERSFISICA = 1 THEN (CASE WHEN ACF.COGNOMEPERSFIS <> '' AND ACF.NOMEPERSFIS <> '' THEN ACF.NOMEPERSFIS ELSE '' END) ELSE '' END) END) AS NOME_DSTN,
        /**/
        ISNULL(TC.NRRIFER,TD.NUMERODOC) AS NUMEROREGISTRAZIONECONT,
        GETDATE() AS DATAESTRAZIONE,
        Year(GetDate()) as ESERCIZIOESTRAZIONE,
        @NomeFile AS NOMEFILE,
        /* Aggiunta Gestione Codice Ufficio B2b */
        (SELECT ISNULL(CODICE_UFFICIO,'') FROM FunFETS_ImpostazioniUffici(TD.PROGRESSIVO)) CodiceDestinatario
    from 
        TESTEDOCUMENTI TD
    inner join 
        CCT_PARAMETRI_TIPOLOGIA PT 
    on 
        PT.CodTipoDocumento = TD.TIPODOC
    inner join
        CCT_TIPOLOGIA_SERVIZI TS
    ON
        TS.Codice = PT.CodTipologia
    inner join 
        ANAGRAFICACF ACF 
    on 
        ACF.CODCONTO = TD.CODCLIFOR
    inner join 
        ANAGRAFICARISERVATICF ARCF 
    on 
        ARCF.CODCONTO = ACF.CODCONTO and ARCF.ESERCIZIO = TD.ESERCIZIO
    left join 
        TESTECONTABILITA TC
    on
        TC.IDTESTADOC = TD.PROGRESSIVO
    cross join
        TABDITTE TDT
    WHERE
        TD.PROGRESSIVO = @CodDocumento AND PT.CodTipologia = @CodTipologia

    RETURN
END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[CCT_Proc_XmlContentInfo] TO [Metodo98]
    AS [dbo];

