

CREATE PROCEDURE [dbo].[GEM_RICALCOLA_SCAD_RAPPORTI]( @IDCONTRATTO VARCHAR(13), @SEZIONECONTRATTO DECIMAL (5,0), @MESIRITARDO INT,  @IDSESSIONE INT )
AS
/*TEST
DECLARE	@IDCONTRATTO			VARCHAR(13)
DECLARE	@SEZIONECONTRATTO		DECIMAL (5,0)
DECLARE @MESIRITARDO				INT

SET @IDCONTRATTO			= '2010-000100SI'
SET @SEZIONECONTRATTO		= 2
SET @MESIRITARDO				= -2

SELECT IDRAPPORTO, STATO, DATA_PREV, DATA_EFF
FROM GEM_SEZIONECONTRATTORAPPORTI
WHERE  IDCONTRATTO			= '2010-000100SI'
AND SEZIONECONTRATTO		= 2

*/


--SELECT  @ggDIFF= DATEDIFF(day, getdate(), '10-07-2010') 

declare @IDRAPPORTO_MOD			as VARCHAR(14)
declare @DATA_PREV			as DATETIME
DECLARE @FLG_DerogaRicScadenze		as varchar(1)
DECLARE @MESSAGGIO			AS VARCHAR(255)

--PER TUTTI I MEZZI ATTIVI e visitati INSERISCO UN RECORD NELL'ARRAY
DECLARE CURR_RIGHE CURSOR  LOCAL  FAST_FORWARD FOR
	
select idRapporto, Data_prev
from dbo.GEM_SEZIONECONTRATTORAPPORTI
where IDCONTRATTO = @IDCONTRATTO AND SEZIONECONTRATTO = @SEZIONECONTRATTO 
		AND STATO = 'G' AND TIPOLOGIARAPPORTO = 'O' AND NOT DATA_PREV IS NULL AND isnull(FLG_DerogaRicScadenze,'N') <> 'S' 

--Modificato il 16-08-2010 fix su proto
--AND isnull(FLG_DerogaRicScadenze,'S') = 'S'
--

OPEN CURR_RIGHE
FETCH NEXT FROM CURR_RIGHE INTO @IDRAPPORTO_MOD,@DATA_PREV
WHILE @@FETCH_STATUS = 0
BEGIN


	--select @DATA_PREV, dateadd(d, @MESIRITARDO, @DATA_PREV), @MESIRITARDO
	-- AGGIORNAMENTO 
	UPDATE GEM_SEZIONECONTRATTORAPPORTI 
	SET DATA_PREV= dateadd(mm, @MESIRITARDO, @DATA_PREV), DATAMODIFICA = getdate(), UTENTEMODIFICA= user_name()
	WHERE IDRAPPORTO = @IDRAPPORTO_MOD
	IF @@ERROR <> 0 BEGIN
		SET @MESSAGGIO	=	'RAPPORTI: ' + @IDRAPPORTO_MOD + ' - ERRORE IN AGGIORNAMENTO DATE INTERVENTI FUTURI ' 
		EXEC GEM_REG_ERRORLOG @IDSESSIONE,@MESSAGGIO
		RETURN 1
	END 					
			
				
	

	FETCH NEXT FROM CURR_RIGHE INTO @IDRAPPORTO_MOD,@DATA_PREV

END

CLOSE CURR_RIGHE
DEALLOCATE CURR_RIGHE
RETURN 0


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GEM_RICALCOLA_SCAD_RAPPORTI] TO [Metodo98]
    AS [dbo];

