
CREATE PROCEDURE [dbo].[GEM_METSIC_TO_INT_SEZIONECONTRATTORAPPORTI_OreLavoro] (@IDRAPPORTO as varchar(14),@TIPOOPERAZIONE as char(1),@Progressivo as decimal(10,0),@Stato as varchar(1)) AS
BEGIN
	declare @IdAzienda varchar(3)

	select @IdAzienda = IdSocieta
	from GEM_TabParametriAziendaGemma

	-- UPDATE PER AZIENDA METODO SICURA
	IF @Stato = 'T'
	BEGIN
		
		UPDATE INS 
			SET  
			  INS.[IDCONTRATTO] = MET.[IDCONTRATTO]
			  ,INS.[SEZIONECONTRATTO] = MET.[SEZIONECONTRATTO]
			  ,INS.[TIPOLOGIARAPPORTO] = MET.[TIPOLOGIARAPPORTO]
			  ,INS.[DATA] = MET.[DATA]
			  ,INS.[TECNICO] = MET.[TECNICO]
			  ,INS.[OREORD] = MET.[OREORD]
			  ,INS.[ORESTRA] = MET.[ORESTRA]
			  ,INS.[OREVIAGGIO] = MET.[OREVIAGGIO]
			  ,INS.[TRASFERTA] = MET.[TRASFERTA]
			  ,INS.[KM] = MET.[KM]
			  ,INS.[UTENTEMODIFICA] = MET.[UTENTEMODIFICA]
			  ,INS.[DATAMODIFICA] = MET.[DATAMODIFICA]
			  ,INS.[AZRIF] = @IdAzienda
			FROM GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_OreLavoro INS
			INNER JOIN GEM_SEZIONECONTRATTORAPPORTI_OreLavoro MET ON
			INS.IDRAPPORTO = MET.IDRAPPORTO COLLATE Latin1_General_CI_AS 
			AND INS.IDRIGA = MET.IDRIGA AND INS.AZRIF = @IdAzienda
			WHERE INS.IDRAPPORTO = @IDRAPPORTO 
              AND INS.Progressivo = @Progressivo
	END
	ELSE
	BEGIN
		INSERT INTO GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_OreLavoro
		(
		[PROGRESSIVO]
		,[IDRAPPORTO]
		,[IDRIGA]
		,[IDCONTRATTO]
		,[SEZIONECONTRATTO]
		,[TIPOLOGIARAPPORTO]
		,[DATA]
		,[TECNICO]
		,[OREORD]
		,[ORESTRA]
		,[OREVIAGGIO]
		,[TRASFERTA]
		,[KM]
		,[UTENTEMODIFICA]
		,[DATAMODIFICA]
		,[AZRIF] 
		)
		SELECT 
		@Progressivo
		,MET.[IDRAPPORTO]
		,MET.[IDRIGA]
		,MET.[IDCONTRATTO]
		,MET.[SEZIONECONTRATTO]
		,MET.[TIPOLOGIARAPPORTO]
		,MET.[DATA]
		,MET.[TECNICO]
		,MET.[OREORD]
		,MET.[ORESTRA]
		,MET.[OREVIAGGIO]
		,MET.[TRASFERTA]
		,MET.[KM]
		,MET.[UTENTEMODIFICA]
		,MET.[DATAMODIFICA]
		,@IdAzienda
		FROM GEM_SEZIONECONTRATTORAPPORTI_OreLavoro MET
		WHERE MET.IDRAPPORTO = @IDRAPPORTO 
	END
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GEM_METSIC_TO_INT_SEZIONECONTRATTORAPPORTI_OreLavoro] TO [Metodo98]
    AS [dbo];

