


CREATE PROCEDURE [dbo].[GEM_INT_TO_MET_SEZIONECONTRATTORAPPORTI_Materiali] (@AZRIF as varchar(3),
																		   @IDRAPPORTO as varchar(14),
																		   @Progressivo as decimal(10,0))

AS

BEGIN
	DECLARE @DATA_SYNC		datetime
	SET @DATA_SYNC = GetDate()	

		-- inserisco in metodo i rapporti dei materiali non presenti
		INSERT INTO GEM_SEZIONECONTRATTORAPPORTI_Materiali
		(
		[IDRAPPORTO]
		,[IDRIGA]
		,[IDCONTRATTO]
		,[SEZIONECONTRATTO]
		,[IDMATERIALE]
		,[UTENTEMODIFICA] 
		,[DATAMODIFICA] 
		,[CODDEPOSITO]
		,[CODUBICAZIONE]
		)
		SELECT
	      INS.[IDRAPPORTO] COLLATE Latin1_General_CI_AS
		  ,INS.[IdRiga]
		  ,[IDCONTRATTO] COLLATE Latin1_General_CI_AS
		  ,[SEZIONECONTRATTO] 
		  ,[IDMATERIALE] COLLATE Latin1_General_CI_AS
		  ,'Sincronizzazione'
		  ,@DATA_SYNC
		  ,[CODDEPOSITO] COLLATE Latin1_General_CI_AS
		  ,[CODUBICAZIONE] COLLATE Latin1_General_CI_AS
		FROM
		GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_Materiali INS
		WHERE isnull(INS.ELIMINATO, '0') = '0' and INS.IDRAPPORTO = @IDRAPPORTO AND INS.AZRIF = @AZRIF and INS.Progressivo = @Progressivo
		EXCEPT
		SELECT
	      MET.[IDRAPPORTO]
		  ,MET.[IDRIGA]
		  ,[IDCONTRATTO]
		  ,[SEZIONECONTRATTO]
		  ,[IDMATERIALE]
		  ,'Sincronizzazione'
		  ,@DATA_SYNC
		  ,[CODDEPOSITO]
		  ,[CODUBICAZIONE]
		FROM
		GEM_SEZIONECONTRATTORAPPORTI_Materiali MET
		WHERE MET.IDRAPPORTO = @IDRAPPORTO 
		
		UPDATE MET 
			SET MET.[IDCONTRATTO] = INS.[IDCONTRATTO]
			  ,MET.[SEZIONECONTRATTO] = INS.[SEZIONECONTRATTO]
			  ,MET.[IDMATERIALE] = INS.[IDMATERIALE]
			  ,MET.[PREZZO] = INS.[PREZZO]
			  ,MET.[SCONTO] = INS.[SCONTO]
			  ,MET.[QTA] = INS.[QTA]
			  ,MET.[PROVVIGIONE1] = INS.[PROVVIGIONE1]
			  ,MET.[PROVVIGIONE2] = INS.[PROVVIGIONE2]
			  ,MET.[PROVVIGIONE3] = INS.[PROVVIGIONE3]
			  ,MET.[flg_mat_dafatt] = INS.[flg_mat_dafatt]
			  ,MET.[NoMovimentaMagazzino] = INS.[NoMovimentaMagazzino]
			  ,MET.[UTENTEMODIFICA] = INS.[UTENTEMODIFICA]
			  ,MET.[DATAMODIFICA] = INS.[DATAMODIFICA]
			  ,MET.[CODDEPOSITO] = INS.[CODDEPOSITO]
			  ,MET.[CODUBICAZIONE] = INS.[CODUBICAZIONE]
			FROM GEM_SEZIONECONTRATTORAPPORTI_Materiali MET
			INNER JOIN GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_Materiali INS ON
			MET.IDRAPPORTO = INS.IDRAPPORTO COLLATE Latin1_General_CI_AS AND MET.IDRIGA = INS.IDRIGA
			WHERE MET.IDRAPPORTO = @IDRAPPORTO AND INS.AZRIF = @AZRIF and INS.Progressivo = @Progressivo

		DELETE MET
		FROM GEM_SEZIONECONTRATTORAPPORTI_Materiali MET
		INNER JOIN GemmaSync.dbo.GEM_SEZIONECONTRATTORAPPORTI_Materiali INS ON
		MET.IDRAPPORTO = INS.IDRAPPORTO COLLATE Latin1_General_CI_AS AND MET.IDRIGA = INS.IDRIGA
		WHERE INS.ELIMINATO = '1' and MET.IDRAPPORTO = @IDRAPPORTO AND INS.AZRIF = @AZRIF and INS.Progressivo = @Progressivo

END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GEM_INT_TO_MET_SEZIONECONTRATTORAPPORTI_Materiali] TO [Metodo98]
    AS [dbo];

