
-- --------------------------------------------------------------------------------------
-- Funzione  : GRI_RAPPORTI (Metodo->DbSync)
-- Autore   : Moreno Feletto
-- Data    : 18.04.2016
-- --------------------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[GRI_METSIC_TO_INT_RAPPORTI] (@IDRAPPORTO AS VARCHAR(14), @TIPOOPERAZIONE AS char(1), @Progressivo AS decimal(10,0), @Stato AS VARCHAR(1)) AS
BEGIN

	DECLARE @IdAzienda VARCHAR(3)
	SELECT @IdAzienda = IdSocieta
	FROM GRI_RAPPORTI RI 
	INNER JOIN GRI_TIPOLOGIARAPPORTO TR ON TR.IdTipoRapporto=RI.IdTipoRapporto
	WHERE RI.IDRAPPORTO = @IDRAPPORTO 

	-- UPDATE PER AZIENDA METODO SICURA
	IF @Stato = 'T'
		BEGIN
			
			UPDATE INS SET
				INS.[IDCONTRATTO] = MET.[IDCONTRATTO] 			
				,INS.[SEZIONECONTRATTO] = MET.[SEZIONECONTRATTO]			
				,INS.[IdDivisione] = MET.[IdDivisione]
				,INS.[CODCLIENTE] = MET.[CODCLIENTE]
				,INS.[CODCLIFAT] = MET.[CODCLIFAT]
				,INS.[CODDEST]= MET.[CODDEST]			
				,INS.[IdTipoRapporto] = MET.[IdTipoRapporto]
				,INS.[IdTipoIntervento] = MET.[IdTipoIntervento]
				,INS.[CODPAG] = MET.[CODPAG]
				,INS.[CodAGENTE1] = MET.[CodAGENTE1]			
				,INS.[CodAGENTE2] = MET.[CodAGENTE2]
				,INS.[RIFCOMMCLI] = MET.[RIFCOMMCLI]
				,INS.[ResponsabileCommessa] = MET.[ResponsabileCommessa]			
				,INS.[NodoID] = MET.[NodoID]		
				,INS.[CodiceMezzo] = MET.[CodiceMezzo]
				,INS.[Referente] = MET.[Referente]
				,INS.[Tel_Ref] = MET.[Tel_Ref]
				,INS.[Email_Responsabile] = MET.[Email_Responsabile]
				,INS.[FlgInvioEmailResp] = MET.[FlgInvioEmailResp]
				,INS.[FlgOblPiattaforma] = MET.[FlgOblPiattaforma]
				,INS.[TIPO_PIATTAFORMA] = MET.[TIPO_PIATTAFORMA]
				,INS.[GIORNI_PIATT] = MET.[GIORNI_PIATT]			
				,INS.[TECNICO_EFF] = MET.[TECNICO_EFF]
				,INS.[TECNICO_PREV] = MET.[TECNICO_PREV]
				--,INS.[AZRIF] = @IdAzienda									-- MET.[AZRIF]
				,INS.[DATA_PREV] = MET.[DATA_PREV]
				,INS.[DATA_EFF] = MET.[DATA_EFF]
				,INS.[DATA_FATT] = MET.[DATA_FATT]
				,INS.[VersioneChekList] = MET.[VersioneChekList]			
				,INS.[TitoloChekList] = MET.[TitoloChekList]
				,INS.[STATO] = 'T'												-- MET.[STATO]
				,INS.[DA_FATT] = MET.[DA_FATT]
				,INS.[DataInserimento] = MET.[DataInserimento]			
				,INS.[DataEliminazione] = MET.[DataEliminazione]
				,INS.[ELIMINATO] = MET.[ELIMINATO]
				,INS.[MOTIVAZIONE_ANN] = MET.[MOTIVAZIONE_ANN]
				,INS.[INVIOFORZATO] = MET.[INVIOFORZATO]
				,INS.[RefRDO] = MET.[RefRDO]			
				,INS.[FlgPrevistoAllegato] = MET.[FlgPrevistoAllegato]
				,INS.[FlgAllegato] = MET.[FlgAllegato]
				,INS.[FlgOblLetturaNote] = MET.[FlgOblLetturaNote]
				,INS.[FlgLetturaNote] = MET.[FlgLetturaNote]
				,INS.[EsitoDelControllo] = MET.[EsitoDelControllo]			
				,INS.[NUMERO_RFW] = MET.[NUMERO_RFW]
				,INS.[DATA_CREAZIONE] = MET.[DATA_CREAZIONE]
				,INS.[NOTE_INTERNE] = MET.[NOTE_INTERNE]
				,INS.[NOTE_TECNICO] = MET.[NOTE_TECNICO]			
				,INS.[DESCR_INT] = MET.[DESCR_INT]
				,INS.[RICHIESTA_INT] = MET.[RICHIESTA_INT]
				,INS.[RifDocOrigineMetodo] = MET.[RifDocOrigineMetodo]
				,INS.[DATA_ULT_MOD] = MET.[DATA_ULT_MOD]
				,INS.[UTENTE_ULT_MOD] = MET.[UTENTE_ULT_MOD]
				,INS.[IP_ULT_MOD] = MET.[IP_ULT_MOD]
				,INS.[AZ_TEC_EFF] = MET.[AZ_TEC_EFF]
				,INS.[BLOCCOSYNC] = MET.[BLOCCOSYNC]
				,INS.[NUMERORATA] = MET.[NUMERORATA]
				,INS.[DATABLOCCO] = MET.[DATABLOCCO]
				,INS.[UTENTEBLOCCO] = MET.[UTENTEBLOCCO]						
				,INS.[FLAGBLOCCO] = MET.[FLAGBLOCCO]
				,INS.[NUMMETODO] = MET.[NUMMETODO]
				,INS.[TECNICO1] = MET.[TECNICO1]
				,INS.[TECNICO2] = MET.[TECNICO2]
				,INS.[RIFCLIENTE] = MET.[RIFCLIENTE]
				,INS.[FLGEXP] = MET.[FLGEXP]
				,INS.[DATA_STAMPA_TABLET] = MET.[DATA_STAMPA_TABLET]
				,INS.[TOTALE_TABLET] = MET.[TOTALE_TABLET]
				,INS.[FLG_VER_TEC] = MET.[FLG_VER_TEC]
				,INS.[NOTE_GestioneRapporto] = MET.[NOTE_GestioneRapporto]
				,INS.[FLG_BLOCCO_SEGNALATO] = MET.[FLG_BLOCCO_SEGNALATO]
				,INS.[BIGCUSTOMER] = MET.[BIGCUSTOMER]
				,INS.[PresaVisAvviso] = MET.[PresaVisAvviso]
				,INS.[DataSync] = MET.[DataSync]
				,INS.[UTENTEMODIFICA] = MET.[UTENTEMODIFICA]
				,INS.[DATAMODIFICA] = MET.[DATAMODIFICA]
				,INS.[flag_GeneraListeSMS] = MET.[flag_GeneraListeSMS]
				,INS.[IdSessioneProcessiRap] = MET.[IdSessioneProcessiRap]
				,INS.[Periodicita] = MET.[Periodicita]
				,INS.[NrRevisione] = MET.[NrRevisione]
				,INS.[FunzioneReferente] = MET.[FunzioneReferente]
				,INS.[NomeEstesoFirma] = MET.[NomeEstesoFirma]
				,INS.[NomeFileAllegato] = MET.[NomeFileAllegato]
				,INS.[CostoInterventoFornitore] = MET.[CostoInterventoFornitore]
				,INS.[CostoMaterialeFornitore] = MET.[CostoMaterialeFornitore]
				,INS.[RifDocTerzita] = MET.[RifDocTerzita]
				,INS.[NoteTerzista] = MET.[NoteTerzista]
				,INS.[RifOfferta] = MET.[RifOfferta]
				,INS.[OreINTPreviste] = MET.[OreINTPreviste]
				,INS.[flag_GeneraListeCicloPass] = MET.[flag_GeneraListeCicloPass]
				,INS.[IdSessioneProcessiRapCicloPass] = MET.[IdSessioneProcessiRapCicloPass]
				,INS.[DATA_Riprogrammazione] = MET.[DATA_Riprogrammazione]
			FROM GemmaSync.dbo.GRI_RAPPORTI INS
			INNER JOIN GRI_RAPPORTI MET ON INS.IDRAPPORTO = MET.IDRAPPORTO COLLATE Latin1_General_CI_AS
			WHERE INS.IDRAPPORTO = @IDRAPPORTO 
				AND PROGRESSIVO = @Progressivo
				AND INS.AZRIF = @IdAzienda
				
		END
	ELSE
		BEGIN
			INSERT INTO GemmaSync.dbo.GRI_RAPPORTI
			(
				[PROGRESSIVO]
				,[IDRAPPORTO]
				,[IDCONTRATTO] 
				,[SEZIONECONTRATTO]			
				,[IdDivisione]
				,[CODCLIENTE]
				,[CODCLIFAT]
				,[CODDEST]			
				,[IdTipoRapporto]
				,[IdTipoIntervento]
				,[CODPAG]
				,[CodAGENTE1]			
				,[CodAGENTE2]
				,[RIFCOMMCLI]
				,[ResponsabileCommessa]
				,[NodoID]		
				,[CodiceMezzo]
				,[Referente]
				,[Tel_Ref]
				,[Email_Responsabile]
				,[FlgInvioEmailResp]
				,[FlgOblPiattaforma]
				,[TIPO_PIATTAFORMA]
				,[GIORNI_PIATT]			
				,[TECNICO_EFF]
				,[TECNICO_PREV]
				,[AZRIF]
				,[DATA_PREV]
				,[DATA_EFF]
				,[DATA_FATT]
				,[VersioneChekList]			
				,[TitoloChekList]
				,[STATO]
				,[STATO_SYNC]
				,[DA_FATT]
				,[DataInserimento]			
				,[DataEliminazione]
				,[ELIMINATO]
				,[MOTIVAZIONE_ANN]
				,[INVIOFORZATO]
				,[RefRDO]			
				,[FlgPrevistoAllegato]
				,[FlgAllegato]
				,[FlgOblLetturaNote]
				,[FlgLetturaNote]
				,[EsitoDelControllo]			
				,[NUMERO_RFW]
				,[DATA_CREAZIONE]
				,[NOTE_INTERNE]
				,[NOTE_TECNICO]			
				,[DESCR_INT]
				,[RICHIESTA_INT]
				,[RifDocOrigineMetodo]
				,[DATA_ULT_MOD]
				,[UTENTE_ULT_MOD]
				,[IP_ULT_MOD]
				,[AZ_TEC_EFF]
				,[BLOCCOSYNC]
				,[NUMERORATA]
				,[DATABLOCCO]
				,[UTENTEBLOCCO]						
				,[FLAGBLOCCO]
				,[NUMMETODO]
				,[TECNICO1]
				,[TECNICO2]
				,[RIFCLIENTE]
				,[FLGEXP]
				,[DATA_STAMPA_TABLET]
				,[TOTALE_TABLET]
				,[FLG_VER_TEC]
				,[NOTE_GestioneRapporto]
				,[FLG_BLOCCO_SEGNALATO]
				,[BIGCUSTOMER]
				,[PresaVisAvviso]
				,[DataSync]
				,[UTENTEMODIFICA]
				,[DATAMODIFICA]
				,[flag_GeneraListeSMS]
				,[IdSessioneProcessiRap]
				,[Periodicita]
				,[NrRevisione]
				,[FunzioneReferente]
				,[NomeEstesoFirma]
				,[NomeFileAllegato]
				,[CostoInterventoFornitore]
				,[CostoMaterialeFornitore]
				,[RifDocTerzita]
				,[NoteTerzista]
				,[RifOfferta]
				,[OreINTPreviste]
				,[flag_GeneraListeCicloPass]
				,[IdSessioneProcessiRapCicloPass]
				,[DATA_Riprogrammazione]
				)
			SELECT
				@Progressivo
				,MET.[IDRAPPORTO]
				,MET.[IDCONTRATTO] 
				,MET.[SEZIONECONTRATTO]			
				,MET.[IdDivisione]
				,MET.[CODCLIENTE]
				,MET.[CODCLIFAT]
				,MET.[CODDEST]			
				,MET.[IdTipoRapporto]
				,MET.[IdTipoIntervento]
				,MET.[CODPAG]
				,MET.[CodAGENTE1]			
				,MET.[CodAGENTE2]
				,MET.[RIFCOMMCLI]
				,MET.[ResponsabileCommessa]
				,MET.[NodoID]		
				,MET.[CodiceMezzo]
				,MET.[Referente]
				,MET.[Tel_Ref]
				,MET.[Email_Responsabile]
				,MET.[FlgInvioEmailResp]
				,MET.[FlgOblPiattaforma]
				,MET.[TIPO_PIATTAFORMA]
				,MET.[GIORNI_PIATT]			
				,MET.[TECNICO_EFF]
				,MET.[TECNICO_PREV]
				,@IdAzienda					--,MET.[AZRIF]
				,MET.[DATA_PREV]
				,MET.[DATA_EFF]
				,MET.[DATA_FATT]
				,MET.[VersioneChekList]			
				,MET.[TitoloChekList]
				,'T'								--,MET.[STATO]
				,'T'								--,MET.[STATO_SYNC]
				,MET.[DA_FATT]
				,MET.[DataInserimento]			
				,MET.[DataEliminazione]
				,MET.[ELIMINATO]
				,MET.[MOTIVAZIONE_ANN]
				,MET.[INVIOFORZATO]
				,MET.[RefRDO]			
				,MET.[FlgPrevistoAllegato]
				,MET.[FlgAllegato]
				,MET.[FlgOblLetturaNote]
				,MET.[FlgLetturaNote]
				,MET.[EsitoDelControllo]			
				,MET.[NUMERO_RFW]
				,MET.[DATA_CREAZIONE]
				,MET.[NOTE_INTERNE]
				,MET.[NOTE_TECNICO]			
				,MET.[DESCR_INT]
				,MET.[RICHIESTA_INT]
				,MET.[RifDocOrigineMetodo]
				,MET.[DATA_ULT_MOD]
				,MET.[UTENTE_ULT_MOD]
				,MET.[IP_ULT_MOD]
				,MET.[AZ_TEC_EFF]
				,MET.[BLOCCOSYNC]
				,MET.[NUMERORATA]
				,MET.[DATABLOCCO]
				,MET.[UTENTEBLOCCO]						
				,MET.[FLAGBLOCCO]
				,MET.[NUMMETODO]
				,MET.[TECNICO1]
				,MET.[TECNICO2]
				,MET.[RIFCLIENTE]
				,MET.[FLGEXP]
				,MET.[DATA_STAMPA_TABLET]
				,MET.[TOTALE_TABLET]
				,MET.[FLG_VER_TEC]
				,MET.[NOTE_GestioneRapporto]
				,MET.[FLG_BLOCCO_SEGNALATO]
				,MET.[BIGCUSTOMER]
				,MET.[PresaVisAvviso]
				,MET.[DataSync]
				,MET.[UTENTEMODIFICA]
				,MET.[DATAMODIFICA]
				,MET.[flag_GeneraListeSMS]
				,MET.[IdSessioneProcessiRap]
				,MET.[Periodicita]
				,MET.[NrRevisione]
				,MET.[FunzioneReferente]
				,MET.[NomeEstesoFirma]
				,MET.[NomeFileAllegato]
				,MET.[CostoInterventoFornitore]
				,MET.[CostoMaterialeFornitore]
				,MET.[RifDocTerzita]
				,MET.[NoteTerzista]
				,MET.[RifOfferta]
				,MET.[OreINTPreviste]
				,MET.[flag_GeneraListeCicloPass]
				,MET.[IdSessioneProcessiRapCicloPass]
				,MET.[DATA_Riprogrammazione]
			FROM GRI_RAPPORTI MET
			WHERE IDRAPPORTO = @IDRAPPORTO
		
		END
		
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[GRI_METSIC_TO_INT_RAPPORTI] TO [Metodo98]
    AS [dbo];

