CREATE PROCEDURE PR_TEMPTOTALICONGRPARTITE(@strW NVARCHAR(1000), @IDSESSIONE SMALLINT) AS
BEGIN
	DECLARE @SQL NVARCHAR(4000) 
	DECLARE @STRWHERE NVARCHAR(2000)

	SET @SQL = 'DELETE FROM TEMPTOTALICONGRPARTITE WHERE IDSESSIONE = ' + CAST(@IDSESSIONE AS NVARCHAR(10))
	PRINT(@SQL)
	EXEC(@SQL)

	--Nel caso di campi data rimetto un apice singolo, altrimenti vÓ in errore la query
	SET @STRWHERE = Replace(@strW, '{d '+char(39)+char(39), '{d '+char(39))
	SET @STRWHERE = Replace(@STRWHERE, char(39)+char(39)+'}', char(39)+'}')
	
	SET @SQL = 'INSERT INTO TEMPTOTALICONGRPARTITE (IDSESSIONE,CONTO,NRPARTITA,DARE,DAREEURO,DAREVALUTA,AVERE,AVEREEURO,AVEREVALUTA,SCADNONEMESSE,SCADNONEMESSEEURO,SCADNONEMESSEVALUTA,SCADEMESSE,SCADEMESSEEURO,SCADEMESSEVALUTA,SCADINSOLUTE,SCADINSOLUTEEURO,SCADINSOLUTEVALUTA) '
	SET @SQL = @SQL + 'SELECT ' + CAST(@IDSESSIONE AS NVARCHAR(10)) + ',CONTO,NRPARTITA,SUM(DARE),SUM(DAREEURO),SUM(DAREVALUTA),SUM(AVERE),SUM(AVEREEURO),SUM(AVEREVALUTA),' 
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADLIRE) FROM VISTASCADENZE WHERE ESITO=0 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),' 
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADEURO) FROM VISTASCADENZE WHERE ESITO=0 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),' 			
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADVALUTA) FROM VISTASCADENZE WHERE ESITO=0 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),' 
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADLIRE) FROM VISTASCADENZE WHERE ESITO=1 AND FLAGCONT=0 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),' 
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADEURO) FROM VISTASCADENZE WHERE ESITO=1 AND FLAGCONT=0 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),'
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADVALUTA) FROM VISTASCADENZE WHERE ESITO=1 AND FLAGCONT=0 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),'
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADLIRE) FROM VISTASCADENZE WHERE ESITO=3 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),' 
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADEURO) FROM VISTASCADENZE WHERE ESITO=3 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA),' 
	SET @SQL = @SQL + '(SELECT SUM(IMPORTOSCADVALUTA) FROM VISTASCADENZE WHERE ESITO=3 AND CODCLIFOR=CONTO AND NUMRIFPARTCONT=NRPARTITA) '
	SET @SQL = @SQL + 'FROM VISTAPARTITECONTABILITA LEFT OUTER JOIN VISTACLIFOR ON VISTAPARTITECONTABILITA.CONTO=VISTACLIFOR.CODCONTO ' 
	SET @SQL = @SQL + 'WHERE ' + @STRWHERE + ' GROUP BY CONTO,NRPARTITA'
	
	PRINT(@SQL)
	EXEC(@SQL)
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PR_TEMPTOTALICONGRPARTITE] TO [Metodo98]
    AS [dbo];

