
CREATE PROCEDURE [dbo].[PROC_TRASPORTO_ACQ](@RIFPROGRESSIVO DECIMAL(18,0)) AS
	
	EXEC PROC_TRASPORTO_ACQ_DETTAGLIO_ARTICOLO @RIFPROGRESSIVO
	EXEC PROC_TRASPORTO_ACQ_DETTAGLIO_ARTICOLO_LOTTO @RIFPROGRESSIVO
	EXEC PROC_TRASPORTO_ACQ_COSTO_ARTICOLO @RIFPROGRESSIVO


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_TRASPORTO_ACQ] TO [Metodo98]
    AS [dbo];

