

CREATE PROCEDURE [dbo].[PROC_TRASPORTO_CL](@RIFPROGRESSIVO DECIMAL(18,0) )
--ENCRY--
AS

    /*CHIAVI DI ROTTURA IDTESTA,IDRIGA,CODICE*/
    DELETE TRASPORTO_CALCOLOBATCH_RIGHE 
    FROM TRASPORTO_CALCOLOBATCH_RIGHE
    INNER JOIN
    (
        SELECT 
            RD.IDTESTA AS IDTESTADOC,
            RD.IDRIGA AS IDRIGADOC,
            T.CODICE
        FROM
            TRASPORTO_CL_TESTE_DETTAGLIO_COSTI T,
            TRASPORTO_CL_RIGHE_DETTAGLIO_COSTI R,
            TESTEDOCUMENTI TD,
            RIGHEDOCUMENTI RD,
            (SELECT TOP 1 UMTOTALEQTA FROM TRASPORTO_CL_PARAMETRI) P,
            ARTICOLIFATTORICONVERSIONE FC
        WHERE
            T.RIFPROGRESSIVO = @RIFPROGRESSIVO AND
            R.RIFPROGRESSIVO = T.RIFPROGRESSIVO AND
            TD.PROGRESSIVO = R.RIFPROGRESSIVODOC AND
            RD.IDTESTA = TD.PROGRESSIVO AND
            FC.CODART = RD.CODART AND
            FC.UM1 = RD.UMGEST AND
            FC.UM2 = P.UMTOTALEQTA
    ) C
    ON TRASPORTO_CALCOLOBATCH_RIGHE.IDTESTADOC = C.IDTESTADOC AND
       TRASPORTO_CALCOLOBATCH_RIGHE.IDRIGADOC = C.IDRIGADOC AND
       TRASPORTO_CALCOLOBATCH_RIGHE.CODICE = C.CODICE
        
        
    INSERT INTO [TRASPORTO_CALCOLOBATCH_RIGHE]([IDFILTRO],[CODSPEDIZIONIERE],[IDREGOLA],[DATADOC],[IDTESTADOC],[IDRIGADOC],
                                               [TOTRIGHEDOC],[CODICE],[QTATOT],[QTACONV],[QTAGEST],[QTACALC],[TOTVALORE],
                                               [TOTALERIGADOC],[TOTVALORE_RIGADOC],[UTENTEMODIFICA],[DATAMODIFICA])
    
    SELECT 
        0 AS IDFILTRO,
        T1.CODSPEDIZ AS CODSPEDIZIONIERE,
        999 AS IDREGOLA,
        TD.DATADOC,
        RD.IDTESTA AS IDTESTADOC,
        RD.IDRIGA AS IDRIGADOC,
        RD.TOTNETTORIGAEURO AS TOTRIGHEDOC,
        T.CODICE,
        RD.QTAGEST AS QTATOT,
        (RD.QTAGEST * FC.FATTORE) AS QTACONV /*QTA CONVERTITA*/,
        RD.QTAGEST,
        (RD.QTAGEST  * FC.FATTORE) AS QTACALC /*QTA CONVERTITA*/,
        T.VALORE AS TOTVALORE,
        SUM(RD.TOTNETTORIGAEURO) over (Partition by RD.IDTESTA) AS TOTALERIGADOC /*SOMMA DI TUTTE LE RIGHE DEL DOCUMENTO*/,
        R.TOTALECOSTOCALCOLATO AS TOTVALORE_RIGADOC,
        USER_NAME() AS UTENTEMODIFICA,
        GETDATE() AS DATAMODIFICA
    FROM
        TRASPORTO_CL_TESTE_DETTAGLIO_COSTI T,
        TRASPORTO_CL_RIGHE_DETTAGLIO_COSTI R,
        TRASPORTO_CL_TESTE T1,
        TESTEDOCUMENTI TD,
        RIGHEDOCUMENTI RD,
        (SELECT TOP 1 UMTOTALEQTA FROM TRASPORTO_CL_PARAMETRI) P,
        ARTICOLIFATTORICONVERSIONE FC
    WHERE
        T.RIFPROGRESSIVO = @RIFPROGRESSIVO AND
        R.RIFPROGRESSIVO = T.RIFPROGRESSIVO AND
        T1.PROGRESSIVO = T.RIFPROGRESSIVO AND
        TD.PROGRESSIVO = R.RIFPROGRESSIVODOC AND
        RD.IDTESTA = TD.PROGRESSIVO AND
        FC.CODART = RD.CODART AND
        FC.UM1 = RD.UMGEST AND
        FC.UM2 = P.UMTOTALEQTA


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_TRASPORTO_CL] TO [Metodo98]
    AS [dbo];

