

CREATE Procedure [dbo].[Proc_PreparaColoreGiacenza] @Esercizio As Decimal(5,0)
AS

	DELETE FROM TP_GiacenzePerColore;

	IF EXISTS(SELECT Progressivo FROM TP_GIAC_COLOR)
	INSERT INTO TP_GiacenzePerColore(CodArticolo,CodDeposito,G,GI,GOI,ColoreG,ColoreGI,ColoreGOI,UtenteModifica,DataModifica)
	SELECT 
		GIACENZA.CODART,
		GIACENZA.CODDEPOSITO,
		SUM(GIACENZA.G) AS G,
		SUM(GIACENZA.GI) AS GI,
		SUM(GIACENZA.GOI) AS GOI,
		ISNULL(G.COLOR,'000000') AS COLOR_G,
		ISNULL(GI.COLOR,'000000') AS COLOR_GI,
		ISNULL(GOI.COLOR,'000000') AS COLOR_GOI,
		User_Name() AS UTENTEMODIFICA,
		GETDATE() AS DATAMODIFICA
		/*,GIACENZA.UM
		,G.UM
		,GI.UM
		,GOI.UM*/
	FROM
	(
		SELECT
			CODART,
			CODDEPOSITO,
			SUM(G) AS G,
			SUM(GI) AS GI,
			SUM(GOI) AS GOI,
			UM
		FROM
		(
			SELECT 
				GF.CODART,
				GF.CODDEPOSITO,
				GF.GIACENZAINIZIALE AS G,
				(GF.GIACENZAINIZIALE - GF.IMPEGNATO) AS GI,
				(GF.GIACENZAINIZIALE + GF.ORDINATO - GF.IMPEGNATO) AS GOI,
				GF.UM
			FROM 
				FunGIACENZAFINALE(@Esercizio) GF,
				TP_ExtraMag TEM
			WHERE
				TEM.CodArt = GF.CodArt AND ((TEM.Esportabile = 0 OR TEM.Esportabile Is Null))
			UNION
			SELECT 
				GFT.CODART,
				'' AS CODDEPOSITO,
				SUM(GFT.GIACENZAINIZIALE) AS G,
				SUM(GFT.GIACENZAINIZIALE - GFT.IMPEGNATO) AS GI,
				SUM(GFT.GIACENZAINIZIALE + GFT.ORDINATO - GFT.IMPEGNATO) AS GOI,
				GFT.UM
			FROM 
				FunGIACENZAFINALE(@Esercizio) GFT,
				TP_ExtraMag TEMT
			WHERE
				TEMT.CodArt = GFT.CodArt AND ((TEMT.Esportabile = 0 OR TEMT.Esportabile Is Null))
			GROUP BY
				GFT.CODART,GFT.UM
			UNION
			SELECT 
				TEM.CODART,
				AD.CODICE AS CODDEPOSITO,
				0 AS G,
				0 AS GI,
				0 AS GOI,
				AUP.UM
			FROM 
				TP_ExtraMag TEM,
				ARTICOLIUMPREFERITE AUP,
				ANAGRAFICADEPOSITI AD
			WHERE
				((TEM.Esportabile = 0 OR TEM.Esportabile Is Null)) AND AUP.CODART = TEM.CodArt AND AUP.TIPOUM = 1
			UNION
			SELECT 
				TEM.CODART,
				'' AS CODDEPOSITO,
				0 AS G,
				0 AS GI,
				0 AS GOI,
				AUP.UM
			FROM 
				TP_ExtraMag TEM,
				ARTICOLIUMPREFERITE AUP
			WHERE
				((TEM.Esportabile = 0 OR TEM.Esportabile Is Null)) AND AUP.CODART = TEM.CodArt AND AUP.TIPOUM = 1
		) TOTALI
		GROUP BY
			CODART,
			CODDEPOSITO,
			UM
	) AS GIACENZA
	OUTER APPLY
	(
		SELECT TOP 1
			TGC.CODART,
			TGC.GIAC,
			AUP.UM,
			TGC.COLOR
		FROM 
			TP_GIAC_COLOR TGC
		LEFT JOIN
			ARTICOLIUMPREFERITE AUP
		ON
			AUP.CODART = TGC.CODART AND AUP.TIPOUM = 1
		LEFT JOIN
			ARTICOLIFATTORICONVERSIONE AFC
		ON
			AFC.CODART = AUP.CODART AND AFC.UM1 = TGC.UM AND AFC.UM2 = AUP.UM
		WHERE 
			TGC.CODART = GIACENZA.CODART AND TGC.GIAC >= GIACENZA.G
		ORDER BY
			TGC.GIAC 
	) G
	OUTER APPLY
	(
		SELECT TOP 1
			TGC.CODART,
			TGC.GIAC,
			AUP.UM,
			TGC.COLOR
		FROM 
			TP_GIAC_COLOR TGC
		LEFT JOIN
			ARTICOLIUMPREFERITE AUP
		ON
			AUP.CODART = TGC.CODART AND AUP.TIPOUM = 1
		LEFT JOIN
			ARTICOLIFATTORICONVERSIONE AFC
		ON
			AFC.CODART = AUP.CODART AND AFC.UM1 = TGC.UM AND AFC.UM2 = AUP.UM
		WHERE 
			TGC.CODART = GIACENZA.CODART AND TGC.GIAC >= GIACENZA.GI
		ORDER BY
			TGC.GIAC 
	) GI
	OUTER APPLY
	(
		SELECT TOP 1
			TGC.CODART,
			TGC.GIAC,
			AUP.UM,
			TGC.COLOR
		FROM 
			TP_GIAC_COLOR TGC
		LEFT JOIN
			ARTICOLIUMPREFERITE AUP
		ON
			AUP.CODART = TGC.CODART AND AUP.TIPOUM = 1
		LEFT JOIN
			ARTICOLIFATTORICONVERSIONE AFC
		ON
			AFC.CODART = AUP.CODART AND AFC.UM1 = TGC.UM AND AFC.UM2 = AUP.UM
		WHERE 
			TGC.CODART = GIACENZA.CODART AND TGC.GIAC >= GIACENZA.GOI
		ORDER BY
			TGC.GIAC 
	) GOI
	GROUP BY
		GIACENZA.CODART,
		GIACENZA.CODDEPOSITO,
		G.COLOR,
		GI.COLOR,
		GOI.COLOR



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[Proc_PreparaColoreGiacenza] TO [Metodo98]
    AS [dbo];

