

CREATE PROCEDURE PROC_CREA_OF_WINTER_VERIFICA_ARTICOLI
--ENCRY--
AS

/*VERIFICA SE ESISTONO GLI ARTICOLI*/
SET NOCOUNT ON

DECLARE @SQLQuery       nVARCHAR(4000)

DECLARE @CODARTICOLO        nVARCHAR(50)
DECLARE @CODDEPOSITO        nVARCHAR(10)

DECLARE @ALFA               DECIMAL(2,1)
DECLARE @BETA               DECIMAL(2,1)
DECLARE @VENDUTOPREVISTO    DECIMAL(19,6)
DECLARE @TRENDPREVISTO      DECIMAL(19,6)   

    /*INIZIO CURSORE PER STORICO PREVISIONI*/
    DECLARE VENDUTO_CURSOR CURSOR FAST_FORWARD FOR 
    SELECT CODARTICOLO,CODDEPOSITO FROM TP_PERIODI_VENDUTO

    OPEN VENDUTO_CURSOR
    FETCH NEXT FROM VENDUTO_CURSOR 
    INTO @CODARTICOLO,@CODDEPOSITO

    WHILE @@FETCH_STATUS = 0
        BEGIN
            SET @SQLQuery = N'IF NOT EXISTS(SELECT CODARTICOLO FROM TP_STAGIONALE_PREVISIONI WHERE CODARTICOLO = ''' + @CODARTICOLO + ''' AND CODDEPOSITO = ''' + @CODDEPOSITO + ''' AND TIPO = ''WT'')
                              INSERT INTO TP_STAGIONALE_PREVISIONI(CodArticolo,CodDeposito,Tipo,UtenteModifica,DataModifica)
                              SELECT ''' + @CODARTICOLO + ''' , ''' + @CODDEPOSITO + ''' ,''WT'', USER_NAME(), GETDATE()'

            SET @SQLQuery = @SQLQuery + N';IF NOT EXISTS(SELECT CODARTICOLO FROM TP_STORICO_WINTER WHERE CODARTICOLO = ''' + @CODARTICOLO + ''' AND CODDEPOSITO = ''' + @CODDEPOSITO + ''')
                                           INSERT INTO TP_STORICO_WINTER(CodArticolo,CodDeposito,UtenteModifica,DataModifica)
                                           SELECT ''' + @CODARTICOLO + ''' , ''' + @CODDEPOSITO + ''' , USER_NAME(), GETDATE()'

            EXEC sp_executesql @SQLQuery

            FETCH NEXT FROM VENDUTO_CURSOR 
            INTO @CODARTICOLO,@CODDEPOSITO
        END

    CLOSE VENDUTO_CURSOR
    DEALLOCATE VENDUTO_CURSOR
    /*FINE CURSORE*/


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_CREA_OF_WINTER_VERIFICA_ARTICOLI] TO [Metodo98]
    AS [dbo];

