

CREATE PROCEDURE [dbo].[PROC_CREA_PREVISIONI_EXPONENTIALSMOOTHING]
--ENCRY--
AS

BEGIN

SET NOCOUNT ON

    Exec PROC_CREA_OF_EXPONENTIALSMOOTHING_VERIFICA_ARTICOLI;
    Exec PROC_CREA_OF_EXPONENTIALSMOOTHING_PREVISIONI_STORICHE;
    Exec PROC_CREA_OF_EXPONENTIALSMOOTHING_MAD_ARTICOLI;
    Exec PROC_CREA_OF_EXPONENTIALSMOOTHING_PREVISIONI_FUTURE;

    If @@ERROR <> 0 GoTo ErrorHandler
    Set NoCount OFF
    Return(0)
  
ErrorHandler:
    Return(@@ERROR)

END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_CREA_PREVISIONI_EXPONENTIALSMOOTHING] TO [Metodo98]
    AS [dbo];

