

CREATE PROCEDURE [dbo].[PROC_CALCOLO_SCORTA]
--ENCRY--
AS

BEGIN

SET NOCOUNT ON

UPDATE TP_SCORTA SET
    TP_SCORTA.ScortaSicurezza = CALCOLI_SCORTE.SCORTASICUREZZAPROPOSTA,
    TP_SCORTA.LivelloRiordinoCalcolato = CALCOLI_SCORTE.LIVELLORIORDINO,
    TP_SCORTA.UtenteModifica = USER_NAME(),
    TP_SCORTA.DataModifica = GETDATE()
FROM
    TP_SCORTA
INNER JOIN
    (
        SELECT
            CODARTICOLO,
            CODDEPOSITO,
            CODFORNITORE,
            (ISNULL(VALOREZ,0) * DEVIAZIONESTD * RLEADTIME) AS SCORTASICUREZZAPROPOSTA,
            (((TOTALEPREVISIONE / GIORNILAVORO12PERIODIPREVISTI) * LEADTIME * FATTORESCOSTAMENTO) + SCORTASICUREZZA) AS LIVELLORIORDINO
        FROM
        (
            SELECT 
                TVPAR.CODARTICOLO,
                TVPAR.CODDEPOSITO,
                TVPFR.CODFORNITORE,
                TVPAR.TOTALEPREVISIONE,
                TVPAR.FATTORESCOSTAMENTO,
                (TVPAR.GIORNILAVOROPERIODOPREVISTI * 12) AS GIORNILAVORO12PERIODIPREVISTI,
                TS.SCORTASICUREZZA,
                TVPFR.LEADTIME,
                TVPFR.RLEADTIME,
                TVPAR.DEVIAZIONESTD,
                TVPAR.VALOREZ
            FROM
                TP_VISTAPARAMETRIARTICOLI_RIORDINO TVPAR,
                TP_VISTAPARAMETRIFORNITORI_RIORDINO TVPFR,
                TP_GIACENZE TG,
                TP_SCORTA TS
            WHERE
                TVPFR.CODARTICOLO = TVPAR.CODARTICOLO AND
                TVPFR.CODDEPOSITO = TVPAR.CODDEPOSITO AND
                TG.CODARTICOLO = TVPAR.CODARTICOLO AND
                TG.CODDEPOSITO = TVPAR.CODDEPOSITO AND
                TS.CODARTICOLO = TVPAR.CODARTICOLO AND
                TS.CODDEPOSITO = TVPAR.CODDEPOSITO AND
                TS.CODFORNPREF = TVPFR.CODFORNITORE
        ) DATI_BASE
    ) CALCOLI_SCORTE
ON
    CALCOLI_SCORTE.CODARTICOLO = TP_SCORTA.CodArticolo AND
    CALCOLI_SCORTE.CODDEPOSITO = TP_SCORTA.CodDeposito AND
    CALCOLI_SCORTE.CODFORNITORE = TP_SCORTA.CodFornPref

If @@ERROR <> 0 GoTo ErrorHandler
    Set NoCount OFF
    Return(0)
  
ErrorHandler:
    Return(@@ERROR)

END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[PROC_CALCOLO_SCORTA] TO [Metodo98]
    AS [dbo];

