CREATE PROCEDURE TP_AGGIORNA_CPO(@DATAINIZ Datetime,@DATAFIN Datetime,@Magz Varchar(10)) AS

BEGIN
  INSERT INTO TP_CPO(CODART,
			MAG,
			DATAINIZIO,
			DATAFINE,
			CARICHI,
			VENDUTI,
			MANCANTI,
			MEDIA)	
    SELECT 	TMPCPO.CODART  as CODICEART,
       		TMPCPO.MAG  as CODICEDEP,
		@DATAINIZ as DTI,
		@DATAFIN as DTF,
		0,
		0,
		0,
		0
    FROM
    (SELECT CODART,
	    MAG 
     FROM TP_CPO 
     WHERE CODART NOT IN(
			 SELECT CODART 
			 FROM TP_CPO 
			 WHERE MAG=@Magz AND 
				DATAINIZIO=@DATAINIZ AND 
				DATAFINE=@DATAFIN) AND 
				MAG=@Magz 
			 GROUP BY CODART, MAG) as TMPCPO
END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[TP_AGGIORNA_CPO] TO [Metodo98]
    AS [dbo];

