
CREATE VIEW AIOT_CFA_COND
AS

SELECT     TESTE.DESCRIZIONECONTRATTO AS [DESCRIZIONE CONTRATTO], TESTE.NUMEROCONTRATTO AS [NUMERO CONTRATTO], TESTE.CODICE, 
                      CF.DSCCONTO1 AS [RAGIONE SOCIALE], TESTE.DATAINIZIOCONTRATTO AS [DATA INIZIO CONTRATTO], TESTE.DATAFINECONTRATTO AS [DATA FINE CONTRATTO], 
                      CO.DADATA AS [DA DATA], CO.ADATA AS [A DATA], CO.NOTE, CO.TIPOCALCOLOPREMIO AS [TIPOLOGIA CALCOLO], CO.TIPODOC AS [DOCUMENTO LIQUIDAZIONE], 
                      CASE CO.EMESSO WHEN 0 THEN 'NO' ELSE 'SI' END AS LIQUIDATO, DOC.ESERCIZIO, DOC.TIPODOC, DOC.NUMERODOC, DOC.BIS, CO.PROGRESSIVO, 
                      CO.RIFCONTRATTO AS CONTRATTO, TESTE.ESERCIZIO AS ESERCIZIOCONTRATTO
FROM         dbo.VISTA_TESTE_CONTRATTI AS TESTE INNER JOIN
                      dbo.AIOT_CONDIZIONATI AS CO ON CO.RIFCONTRATTO = TESTE.PROGRESSIVO LEFT OUTER JOIN
                      dbo.TESTEDOCUMENTI AS DOC ON DOC.PROGRESSIVO = CO.RIFPROGRESSIVODOC LEFT OUTER JOIN
                      dbo.ANAGRAFICACF AS CF ON TESTE.CODICE = CF.CODCONTO



GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_CFA_COND] TO [Metodo98]
    AS [dbo];

