
CREATE VIEW AIOT_VISTASTATI
AS
SELECT     dbo.ACQ_STATI.PROFILO, dbo.ACQ_STATI.CODICE, dbo.ACQ_STATIDETT.RIGA, dbo.ACQ_STATIDETT.DESCRIZIONESTATO, dbo.ACQ_STATIOFFERTA.STATO, 
                      dbo.ACQ_STATIOFFERTA.RIFPROGRESSIVO
FROM         dbo.ACQ_STATI INNER JOIN
                      dbo.ACQ_STATIDETT ON dbo.ACQ_STATI.PROFILO = dbo.ACQ_STATIDETT.RIFPROFILO INNER JOIN
                      dbo.ACQ_STATIOFFERTA ON dbo.ACQ_STATIDETT.RIFPROFILO = dbo.ACQ_STATIOFFERTA.RIFPROFILO AND 
                      dbo.ACQ_STATIDETT.RIGA = dbo.ACQ_STATIOFFERTA.RIFRIGA

GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_VISTASTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_VISTASTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_VISTASTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_VISTASTATI] TO [Metodo98]
    AS [dbo];

