
CREATE VIEW AIOT_LISTINIVALIDI
AS
SELECT     CODART AS ARTICOLO, NRLISTINO, UM, DataVal, PREZZO, PREZZOEURO
FROM         dbo.TP_LISTINIART
WHERE     (CONVERT(varchar, GETDATE(), 112) <= CONVERT(varchar, DataVal, 112))


GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_LISTINIVALIDI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_LISTINIVALIDI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AIOT_LISTINIVALIDI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_LISTINIVALIDI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_LISTINIVALIDI] TO [Metodo98]
    AS [dbo];

