
CREATE VIEW AIOT_VistaScadenzeMovimenti AS
SELECT RIGHENORMALI.NRREG, VISTASCADENZE.* FROM
VISTASCADENZE INNER JOIN
	(SELECT DISTINCT RIGHECONTABILITA.NRREG
	FROM RIGHECONTABILITA INNER JOIN TESTECONTABILITA
	ON RIGHECONTABILITA.NRREG=TESTECONTABILITA.PROGRESSIVO
	WHERE TESTECONTABILITA.IDTESTADOC=0) AS RIGHENORMALI
ON VISTASCADENZE.NUMDOC=RIGHENORMALI.NRREG
WHERE VISTASCADENZE.TIPODOC='___'
UNION
SELECT TD.NRREG, VS.* FROM
VISTASCADENZE VS INNER JOIN
	(SELECT DISTINCT TESTEDOCUMENTI.ESERCIZIO,TESTEDOCUMENTI.TIPODOC,TESTEDOCUMENTI.NUMERODOC,TESTEDOCUMENTI.BIS,
		TESTECONTABILITA.NRREG
	FROM TESTEDOCUMENTI
	INNER JOIN
		(SELECT DISTINCT TESTECONTABILITA.IDTESTADOC,RIGHECONTABILITA.NRREG
		FROM RIGHECONTABILITA INNER JOIN TESTECONTABILITA
		ON RIGHECONTABILITA.NRREG=TESTECONTABILITA.PROGRESSIVO
		WHERE TESTECONTABILITA.IDTESTADOC<>0) AS TESTECONTABILITA
	ON TESTEDOCUMENTI.PROGRESSIVO=TESTECONTABILITA.IDTESTADOC) AS TD
ON VS.ANNODOC=TD.ESERCIZIO AND VS.TIPODOC=TD.TIPODOC AND VS.NUMDOC=TD.NUMERODOC AND VS.BIS=TD.BIS

GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_VistaScadenzeMovimenti] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_VistaScadenzeMovimenti] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AIOT_VistaScadenzeMovimenti] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_VistaScadenzeMovimenti] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_VistaScadenzeMovimenti] TO [Metodo98]
    AS [dbo];

