

CREATE VIEW [dbo].[AIOTCONTRATTI_PREMI]
AS
SELECT     TIPOCONTRIBUTO, RIFCONTRATTO, RIFCONTRIBUTO, NOTA, DADATA, ADATA, PREMIOMATURATO, DELTA, TIPOLOGIA,PREMIONONVALIDO
FROM         dbo.AIOTCONTRATTILIQUIDAZIONE_UNIONEINCONDIZIONATI
UNION
SELECT     TIPOCONTRIBUTO, RIFCONTRATTO, RIFCONTRIBUTO, NOTA, DADATA, ADATA, PREMIOMATURATO, DELTA, TIPOLOGIA,PREMIONONVALIDO
FROM         dbo.AIOTCONTRATTILIQUIDAZIONE_CON


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOTCONTRATTI_PREMI] TO [Metodo98]
    AS [dbo];

