
CREATE VIEW dbo.AIOTCONTRATTICL_MERCE
AS
SELECT     dbo.CONTRATTICL_QTAVALORE.*, dbo.ANAGRAFICAARTICOLI.DESCRIZIONE AS DESCRIZIONE
FROM         dbo.CONTRATTICL_QTAVALORE LEFT OUTER JOIN
                      dbo.ANAGRAFICAARTICOLI ON dbo.CONTRATTICL_QTAVALORE.ARTICOLO = dbo.ANAGRAFICAARTICOLI.CODICE

GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOTCONTRATTICL_MERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOTCONTRATTICL_MERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AIOTCONTRATTICL_MERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOTCONTRATTICL_MERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOTCONTRATTICL_MERCE] TO [Metodo98]
    AS [dbo];

