
CREATE VIEW [dbo].[ALD_VistaCCBILANCIOCONSCOSTIMATERIALE_MaterialiDeriservati]
AS
SELECT     AnagraficaCommesse.Progressivo AS IDCOMMCLI, IMPEGNIORDPROD.RifCommCli, TESTEORDINIPROD.ESERCIZIO, TESTEORDINIPROD.TIPOCOM, 
                      TESTEORDINIPROD.NUMEROCOM, 'DP' AS TIPORECDETT, CCBILANCIOCONSCOSTIMATERIALE.NRRIGA, IMPEGNIORDPROD.CODART, 
                      IMPEGNIORDPROD.UMGEST, IMPEGNIORDPROD.QTAGESTIONE, IMPEGNIORDPROD.QTAGESTIONEVERS, IMPEGNIORDPROD.QTAGESTIONERES, 
                      IMPEGNIORDPROD.QTAGESTIONETRASF, IMPEGNIORDPROD.QTAGESTIONE - IMPEGNIORDPROD.QTAGESTIONEVERS AS QTA_Deriservata,
                          (SELECT     TOP (1) PREZZOEURO
                            FROM          STORICOPREZZIARTICOLO
                            WHERE      (TIPOPREZZO = 'F') AND (CODARTICOLO = IMPEGNIORDPROD.CODART)
                            ORDER BY DATA DESC) AS COSTOUNITARIOEURO
, CCBILANCIOCONSCOSTIMATERIALE.DATACOMPETENZA
FROM         TESTEORDINIPROD INNER JOIN
                      IMPEGNIORDPROD ON TESTEORDINIPROD.PROGRESSIVO = IMPEGNIORDPROD.IDTESTA LEFT OUTER JOIN
                      CCBILANCIOCONSCOSTIMATERIALE ON IMPEGNIORDPROD.CODART = CCBILANCIOCONSCOSTIMATERIALE.CODART AND 
                      IMPEGNIORDPROD.IDIMPEGNO = CCBILANCIOCONSCOSTIMATERIALE.IDIMPEGNO LEFT OUTER JOIN
                      AnagraficaCommesse ON IMPEGNIORDPROD.RifCommCli = AnagraficaCommesse.RifComm
WHERE     (CCBILANCIOCONSCOSTIMATERIALE.CODART IS NULL) AND (IMPEGNIORDPROD.QTAGESTIONE - IMPEGNIORDPROD.QTAGESTIONEVERS > 0)

GO
GRANT DELETE
    ON OBJECT::[dbo].[ALD_VistaCCBILANCIOCONSCOSTIMATERIALE_MaterialiDeriservati] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALD_VistaCCBILANCIOCONSCOSTIMATERIALE_MaterialiDeriservati] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALD_VistaCCBILANCIOCONSCOSTIMATERIALE_MaterialiDeriservati] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_VistaCCBILANCIOCONSCOSTIMATERIALE_MaterialiDeriservati] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_VistaCCBILANCIOCONSCOSTIMATERIALE_MaterialiDeriservati] TO [Metodo98]
    AS [dbo];

