

CREATE VIEW [dbo].[Ald_VistaRigheDocumentiBaseCommesseCli]
AS
SELECT     VISTADOCUMENTIBASE.IDTESTA, VISTADOCUMENTIBASE.ESERCIZIO, VISTADOCUMENTIBASE.TIPODOC, VISTADOCUMENTIBASE.NUMERODOC, 
                      VISTADOCUMENTIBASE.BIS, VISTADOCUMENTIBASE.DATADOC, VISTADOCUMENTIBASE.DOCCHIUSO, VISTADOCUMENTIBASE.BLOCCATO, 
                      VISTADOCUMENTIBASE.CODCLIFOR, VISTADOCUMENTIBASE.NUMRIFDOC, VISTADOCUMENTIBASE.DATARIFDOC, 
                      VISTADOCUMENTIBASE.CODAGENTE1, VISTADOCUMENTIBASE.CODAGENTE2, VISTADOCUMENTIBASE.CODAGENTE3, 
                      VISTADOCUMENTIBASE.CODBANCAINCASSO, VISTADOCUMENTIBASE.NUMDESTDIVERSAMERCI, VISTADOCUMENTIBASE.CODPAGAMENTO, 
                      VISTADOCUMENTIBASE.CODLINGUA, VISTADOCUMENTIBASE.CODCAMBIO, VISTADOCUMENTIBASE.VALCAMBIO, 
                      VISTADOCUMENTIBASE.SCONTOFINALE, VISTADOCUMENTIBASE.CODCFFATT, VISTADOCUMENTIBASE.PRCPROVVAG1, 
                      VISTADOCUMENTIBASE.PRCPROVVFINALEAG1, VISTADOCUMENTIBASE.PRCPROVVAG2, VISTADOCUMENTIBASE.PRCPROVVFINALEAG2, 
                      VISTADOCUMENTIBASE.PRCPROVVAG3, VISTADOCUMENTIBASE.PRCPROVVFINALEAG3, VISTADOCUMENTIBASE.FLAGCONT, 
                      VISTADOCUMENTIBASE.ANNOTAZIONIPIEDE, VISTADOCUMENTIBASE.TIPOPAR, VISTADOCUMENTIBASE.FLGBLACKLIST, 
                      VISTADOCUMENTIBASE.PROGRIGADOC, VISTADOCUMENTIBASE.POSIZIONE, VISTADOCUMENTIBASE.TIPORIGA, 
                      VISTADOCUMENTIBASE.RIGACHIUSA, VISTADOCUMENTIBASE.RIGABLOCCATA, VISTADOCUMENTIBASE.CODART, 
                      VISTADOCUMENTIBASE.DESCRIZIONEART, VISTADOCUMENTIBASE.DATACONSEGNA, VISTADOCUMENTIBASE.NUMLISTINO, 
                      VISTADOCUMENTIBASE.UMGEST, VISTADOCUMENTIBASE.UM1, VISTADOCUMENTIBASE.UM2, VISTADOCUMENTIBASE.UMPREZZO, 
                      VISTADOCUMENTIBASE.SCONTORIGA, VISTADOCUMENTIBASE.SCONTIESTESI, VISTADOCUMENTIBASE.CODIVA, VISTADOCUMENTIBASE.PROVVAG1, 
                      VISTADOCUMENTIBASE.PROVVAG2, VISTADOCUMENTIBASE.PROVVAG3, VISTADOCUMENTIBASE.NUMCOLLI, VISTADOCUMENTIBASE.GENCONTROP, 
                      VISTADOCUMENTIBASE.NRRIFPARTITA, VISTADOCUMENTIBASE.PESONETTO, VISTADOCUMENTIBASE.PESOLORDO, 
                      VISTADOCUMENTIBASE.PESOIMBALLO, VISTADOCUMENTIBASE.SUPERFICIE, VISTADOCUMENTIBASE.VOLUME, 
                      VISTADOCUMENTIBASE.RIFCOMMCLI, VISTADOCUMENTIBASE.NOMECOMMESSAPROD, VISTADOCUMENTIBASE.VERSIONEDIBA, 
                      VISTADOCUMENTIBASE.CAUSALEMAG, VISTADOCUMENTIBASE.NRPEZZIIMBALLO, VISTADOCUMENTIBASE.CODIMBALLO, 
                      VISTADOCUMENTIBASE.NOMENCLCOMBINATA, VISTADOCUMENTIBASE.CONTOCDC, VISTADOCUMENTIBASE.CONTOCDCMOVCOLL, 
                      VISTADOCUMENTIBASE.CODDEPOSITO, VISTADOCUMENTIBASE.CODDEPOSITOCOLL, VISTADOCUMENTIBASE.CODDEPCOMP, 
                      VISTADOCUMENTIBASE.CODDEPCOMPCOLL, VISTADOCUMENTIBASE.VARIANTI, VISTADOCUMENTIBASE.ANNOTAZIONI, 
                      VISTADOCUMENTIBASE.PREZZOUNITNETTO, VISTADOCUMENTIBASE.PREZZOUNITLORDO, VISTADOCUMENTIBASE.PREZZOUNITNETTOVALUTA, 
                      VISTADOCUMENTIBASE.PREZZOUNITLORDOVALUTA, VISTADOCUMENTIBASE.PREZZOUNITNETTOEURO, 
                      VISTADOCUMENTIBASE.PREZZOUNITLORDOEURO, VISTADOCUMENTIBASE.UBICAZIONE, VISTADOCUMENTIBASE.UBICAZIONECOLL, 
                      VISTADOCUMENTIBASE.UBICAZIONECOMP, VISTADOCUMENTIBASE.UBICAZIONECOMPCOLL, VISTADOCUMENTIBASE.TOTPROVVFINALEAG1, 
                      VISTADOCUMENTIBASE.TOTPROVVFINALEAG2, VISTADOCUMENTIBASE.TOTPROVVFINALEAG3, VISTADOCUMENTIBASE.TOTPROVVFINALEAG1VALUTA, 
                      VISTADOCUMENTIBASE.TOTPROVVFINALEAG2VALUTA, VISTADOCUMENTIBASE.TOTPROVVFINALEAG3VALUTA, 
                      VISTADOCUMENTIBASE.TOTPROVVFINALEAG1EURO, VISTADOCUMENTIBASE.TOTPROVVFINALEAG2EURO, 
                      VISTADOCUMENTIBASE.TOTPROVVFINALEAG3EURO, VISTADOCUMENTIBASE.TOTDOCUMENTO, VISTADOCUMENTIBASE.TOTIMPOSTA, 
                      VISTADOCUMENTIBASE.TOTDOCUMENTOEURO, VISTADOCUMENTIBASE.TOTIMPOSTAEURO, VISTADOCUMENTIBASE.TOTDOCVALUTA, 
                      VISTADOCUMENTIBASE.TOTIMPOSTAVALUTA, VISTADOCUMENTIBASE.QTAGEST, VISTADOCUMENTIBASE.QTAGESTRES, 
                      VISTADOCUMENTIBASE.QTA1MAG, VISTADOCUMENTIBASE.QTA1MAGRES, VISTADOCUMENTIBASE.QTA2MAG, VISTADOCUMENTIBASE.QTA2MAGRES, 
                      VISTADOCUMENTIBASE.QTAPREZZO, VISTADOCUMENTIBASE.QTAPREZZORES, VISTADOCUMENTIBASE.QTAGESTPRELEVATA, 
                      VISTADOCUMENTIBASE.TOTLORDORIGA, VISTADOCUMENTIBASE.TOTNETTORIGA, VISTADOCUMENTIBASE.TOTLORDORIGAVALUTA, 
                      VISTADOCUMENTIBASE.TOTNETTORIGAVALUTA, VISTADOCUMENTIBASE.TOTLORDORIGAEURO, VISTADOCUMENTIBASE.TOTNETTORIGAEURO, 
                      VISTADOCUMENTIBASE.TOTPROVVAG1, VISTADOCUMENTIBASE.TOTPROVVAG2, VISTADOCUMENTIBASE.TOTPROVVAG3, 
                      VISTADOCUMENTIBASE.TOTPROVVAG1EURO, VISTADOCUMENTIBASE.TOTPROVVAG2EURO, VISTADOCUMENTIBASE.TOTPROVVAG3EURO, 
                      VISTADOCUMENTIBASE.TOTPROVVAG1VALUTA, VISTADOCUMENTIBASE.TOTPROVVAG2VALUTA, VISTADOCUMENTIBASE.TOTPROVVAG3VALUTA, 
                      VISTADOCUMENTIBASE.DSCCONTO1, VISTADOCUMENTIBASE.CODCATEGORIACF, VISTADOCUMENTIBASE.CODNAZIONE, 
                      VISTADOCUMENTIBASE.CODSETTORE, VISTADOCUMENTIBASE.CODZONA, VISTADOCUMENTIBASE.GRUPPO, VISTADOCUMENTIBASE.VARESPLICITE, 
                      VISTADOCUMENTIBASE.CATEGORIA, VISTADOCUMENTIBASE.CODCATEGORIASTAT, VISTADOCUMENTIBASE.ARTTIPOLOGIA, 
                      VISTADOCUMENTIBASE.CODICEPRIMARIO, VISTADOCUMENTIBASE.DSCART, VISTADOCUMENTIBASE.AGGIORNAMAG, 
                      VISTADOCUMENTIBASE.CODARTICOLOBASE, VISTADOCUMENTIBASE.DSCARTICOLOBASE, VISTADOCUMENTIBASE.INCIDENZASCONTI, 
                      VISTADOCUMENTIBASE.RIFRELAZIONECF, VISTADOCUMENTIBASE.TOTNETTORIGARES, VISTADOCUMENTIBASE.TOTNETTORIGAEURORES, 
                      VISTADOCUMENTIBASE.IDTESTARP, VISTADOCUMENTIBASE.IDRIGARP, VISTADOCUMENTIBASE.ANNOBOLLACLF, 
                      VISTADOCUMENTIBASE.NUMEROBOLLACLF, VISTADOCUMENTIBASE.OPERAZIONECLF, VISTADOCUMENTIBASE.STATOOPERAZIONECLF, 
                      VISTADOCUMENTIBASE.CAUSALEVERSAMENTOCLF, VISTADOCUMENTIBASE.CAUSALETRASFERIMENTOCLF, 
                      VISTADOCUMENTIBASE.IMPTOTPROVVRIGALIT, VISTADOCUMENTIBASE.IMPTOTPROVVRIGAVALUTA, 
                      VISTADOCUMENTIBASE.IMPTOTPROVVRIGAEURO, ExtraCommCli.ResponsabileCommessa AS CodRespComm, 
					  ExtraCommCli.RefCoordComm,
                      ANAGRAFICAARTICOLI.DESCRIZIONE AS DscRespComm, AnagraficaCommesse.Riferimento, AnagraficaCommesse.CodArtOggetto, 
                      AnagraficaCommesse.Oggetto, AnagraficaCommesse.DocContratto, AnagraficaCommesse.NumOfferta, AnagraficaCommesse.DataOfferta, 
                      AnagraficaCommesse.DataConferma, AnagraficaCommesse.DataEmissione, AnagraficaCommesse.DataConsegnaContr, 
                      AnagraficaCommesse.DataConsegnaPrev, AnagraficaCommesse.DataConsegnaSched, AnagraficaCommesse.DataInizioConsegna, 
                      AnagraficaCommesse.DataFineConsegna, AnagraficaCommesse.DataChiusuraComm, AnagraficaCommesse.StatoCommessa, 
                      AnagraficaCommesse.ModoConsegnaResa, AnagraficaCommesse.ValCambioOff, AnagraficaCommesse.ValCambioComm, 
                      ANAGRAFICARISERVATICF.STATOORDINI, ISNULL(ALD_Vista_CommessaCollaudoSoggetto.DscSoggetto, '') AS DscSoggetto
FROM         VISTADOCUMENTIBASE INNER JOIN
                      ANAGRAFICARISERVATICF ON VISTADOCUMENTIBASE.ESERCIZIO = ANAGRAFICARISERVATICF.ESERCIZIO AND 
                      VISTADOCUMENTIBASE.CODCLIFOR = ANAGRAFICARISERVATICF.CODCONTO LEFT OUTER JOIN
                      ALD_Vista_CommessaCollaudoSoggetto ON 
                      VISTADOCUMENTIBASE.RIFCOMMCLI = ALD_Vista_CommessaCollaudoSoggetto.RifCommessaCliente LEFT OUTER JOIN
                      AnagraficaCommesse ON VISTADOCUMENTIBASE.RIFCOMMCLI = AnagraficaCommesse.RifComm LEFT OUTER JOIN
                      ANAGRAFICAARTICOLI RIGHT OUTER JOIN
                      ExtraCommCli ON ANAGRAFICAARTICOLI.CODICE = ExtraCommCli.ResponsabileCommessa ON 
                      AnagraficaCommesse.Progressivo = ExtraCommCli.RifProgressivo


GO
GRANT DELETE
    ON OBJECT::[dbo].[Ald_VistaRigheDocumentiBaseCommesseCli] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[Ald_VistaRigheDocumentiBaseCommesseCli] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[Ald_VistaRigheDocumentiBaseCommesseCli] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[Ald_VistaRigheDocumentiBaseCommesseCli] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[Ald_VistaRigheDocumentiBaseCommesseCli] TO [Metodo98]
    AS [dbo];

