CREATE VIEW ALD_VISTA_CAUSALI AS 
	SELECT CAUSALICONTABILI.CODICECAUSALE, CAUSALICONTABILI.DESCRIZIONE
	FROM ALD_TabCausaliConvSap INNER JOIN
	 CAUSALICONTABILI ON ALD_TabCausaliConvSap.CODCausale = CAUSALICONTABILI.CODICECAUSALE
	WHERE (ALD_TabCausaliConvSap.chkMOVIntegr = 1)
	GROUP BY CAUSALICONTABILI.CODICECAUSALE, CAUSALICONTABILI.DESCRIZIONE

GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALD_VISTA_CAUSALI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_VISTA_CAUSALI] TO [Metodo98]
    AS [dbo];

