

CREATE VIEW [dbo].[ALD_VISTAIMPEGNICOMMESSEPROD] AS
SELECT     TESTEORDINIPROD.TIPOCOM + '/' + CAST(TESTEORDINIPROD.ESERCIZIO AS varchar) 
                      + '/' + RIGHT('0000000000' + CAST(TESTEORDINIPROD.NUMEROCOM AS varchar), 10) + '/' + RIGHT('00000' + CAST(RIGHEORDPROD.IDRIGA AS varchar), 5) 
                      AS RIFORDINE, TESTEORDINIPROD.TIPOCOM + '/' + CAST(TESTEORDINIPROD.ESERCIZIO AS varchar) 
                      + '/' + RIGHT('0000000000' + CAST(TESTEORDINIPROD.NUMEROCOM AS varchar), 10) + '/' + RIGHT('00000' + CAST(RIGHEORDPROD.IDRIGA AS varchar), 5) 
                      + '/' + RIGHT('00000' + CAST(IMPEGNIORDPROD.IDIMPEGNO AS varchar), 5) AS RIFIMPEGNO, TESTEORDINIPROD.ESERCIZIO, TESTEORDINIPROD.TIPOCOM, 
                      TESTEORDINIPROD.NUMEROCOM, TESTEORDINIPROD.DATAEMISSIONE, TESTEORDINIPROD.PIANOPRODRIF, TESTEORDINIPROD.CODCLIENTE, 
                      TESTEORDINIPROD.ANNOTAZIONI, TESTEORDINIPROD.STATOCHIUSO, TESTEORDINIPROD.STATOBLOCCATO, RIGHEORDPROD.IDTESTA, RIGHEORDPROD.IDRIGA, 
                      RIGHEORDPROD.CODICEORD,
                          (SELECT     TIPOORDINE
                            FROM          PARAMETRIORDPROD
                            WHERE      (CODICE = RIGHEORDPROD.CODICEORD)) AS TIPOORD, RIGHEORDPROD.CODART AS CODARTORD, RIGHEORDPROD.DESCRIZIONEART, 
                      RIGHEORDPROD.VERSIONEDBA, RIGHEORDPROD.VERSIONECICLO, RIGHEORDPROD.UMGEST, RIGHEORDPROD.QTAGESTIONE, 
                      RIGHEORDPROD.QTAGESTIONEVERS, RIGHEORDPROD.QTAGESTIONERES, RIGHEORDPROD.QTAPREZZO, RIGHEORDPROD.UMPREZZO, 
                      RIGHEORDPROD.QTA1MAG, RIGHEORDPROD.UM1MAG AS UM1ORD, RIGHEORDPROD.QTA2MAG, RIGHEORDPROD.UM2MAG AS UM2ORD, 
                      RIGHEORDPROD.QTA1MAGRES, RIGHEORDPROD.QTA2MAGRES, RIGHEORDPROD.QTASCARTO, RIGHEORDPROD.UMSCARTO, RIGHEORDPROD.IDCOSTOSTD, 
                      RIGHEORDPROD.CODCLIDEST, RIGHEORDPROD.PARTITAASSEGNATA, RIGHEORDPROD.PARTITAVINCOLATA, RIGHEORDPROD.CODFORDEST, 
                      RIGHEORDPROD.DATAEMISSIONE AS DATAEMISSIONEORD, RIGHEORDPROD.TIPOSCHEDULAZIONE, RIGHEORDPROD.STATOORDINE, 
                      RIGHEORDPROD.FASERILASCIO, RIGHEORDPROD.DATARILASCIO, RIGHEORDPROD.DATAINIZIORICH, RIGHEORDPROD.DATAFINERICH, 
                      RIGHEORDPROD.CAUSALEMAG, RIGHEORDPROD.DEPOSITO, RIGHEORDPROD.UBICAZIONE, RIGHEORDPROD.CONTOCDC, RIGHEORDPROD.CAUSALEMAGCOLL, 
                      RIGHEORDPROD.DEPOSITOCOLL, RIGHEORDPROD.UBICAZIONECOLL, RIGHEORDPROD.CONTOCDCCOLL, RIGHEORDPROD.VALOREPRIORITA, 
                      RIGHEORDPROD.RAPPORTOCRITICO, RIGHEORDPROD.SLACKTIME, RIGHEORDPROD.NOTE, IMPEGNIORDPROD.IDIMPEGNO, 
                      IMPEGNIORDPROD.IDRIGA AS IDRIGAIMP, IMPEGNIORDPROD.CODART AS CODARTIMP, IMPEGNIORDPROD.DESCRIZIONEART AS DESCRIZIONEARTIMP, 
                      IMPEGNIORDPROD.flagPreparataMatMag, IMPEGNIORDPROD.qtaPreparata, (CASE WHEN isnull(qtaPreparata, 0) 
                      <> 0 THEN IMPEGNIORDPROD.QTAGESTIONERES - isnull(qtaPreparata, 0) ELSE - 99999 END) AS ColoreRiga, IMPEGNIORDPROD.UMGEST AS UMGESTIMP, 
                      IMPEGNIORDPROD.QTAUNITARIA, IMPEGNIORDPROD.QTAGESTIONE AS QTAGESTIONEIMP, IMPEGNIORDPROD.QTAGESTIONEVERS AS QTAGESTIONEVERSIMP, 
                      IMPEGNIORDPROD.QTAGESTIONERES AS QTAGESTIONERESIMP, IMPEGNIORDPROD.QTAPREZZO AS QTAPREZZOIMP, 
                      IMPEGNIORDPROD.UMPREZZO AS UMPREZZOIMP, IMPEGNIORDPROD.QTA1MAG AS QTA1MAGIMP, IMPEGNIORDPROD.QTA2MAG AS QTA2MAGIMP, 
                      IMPEGNIORDPROD.QTA1MAGRES AS QTA1MAGRESIMP, IMPEGNIORDPROD.QTA2MAGRES AS QTA2MAGRESIMP, IMPEGNIORDPROD.UM1MAG AS UM1IMP, 
                      IMPEGNIORDPROD.UM2MAG AS UM2IMP, IMPEGNIORDPROD.CODFORIMP, IMPEGNIORDPROD.PARTITAASSEGNATA AS PARTITAASSEGNATAIMP, 
                      IMPEGNIORDPROD.PARTITAVINCOLATA AS PARTITAVINCOLATAIMP, IMPEGNIORDPROD.CAUSALEMAG AS CAUSALEMAGIMP, 
                      IMPEGNIORDPROD.DEPOSITO AS DEPOSITOIMP, IMPEGNIORDPROD.UBICAZIONE AS UBICAZIONEIMP, IMPEGNIORDPROD.CONTOCDC AS CONTOCDCIMP, 
                      IMPEGNIORDPROD.CAUSALEMAGCOLL AS CAUSALEMAGCOLLIMP, IMPEGNIORDPROD.DEPOSITOCOLL AS DEPOSITOCOLLIMP, 
                      IMPEGNIORDPROD.UBICAZIONECOLL AS UBICAZIONECOLLIMP, IMPEGNIORDPROD.CONTOCDCCOLL AS CONTOCDCCOLLIMP, IMPEGNIORDPROD.CODCLIIMP, 
                      IMPEGNIORDPROD.DATAEMISSIONE AS DATAEMISSIONEIMP, IMPEGNIORDPROD.DATAIMPEGNORICH, IMPEGNIORDPROD.DATAIMPEGNOSCH, 
                      IMPEGNIORDPROD.STATOIMPEGNO, IMPEGNIORDPROD.TIPOIMPEGNO, IMPEGNIORDPROD.NOTE AS NOTEIMP, IMPEGNIORDPROD.DATACALCCSTEFF, 
                      IMPEGNIORDPROD.DATACALCCSTPREV, IMPEGNIORDPROD.COSTOPREV, IMPEGNIORDPROD.COSTOUNITIMPPREV, IMPEGNIORDPROD.COSTOTOTIMPPREV, 
                      IMPEGNIORDPROD.COSTOPREVEURO, IMPEGNIORDPROD.COSTOUNITIMPPREVEURO, IMPEGNIORDPROD.COSTOTOTIMPPREVEURO, 
                      IMPEGNIORDPROD.COSTOEFF, IMPEGNIORDPROD.COSTOUNITIMPEFF, IMPEGNIORDPROD.COSTOTOTIMPEFF, IMPEGNIORDPROD.COSTOEFFEURO, 
                      IMPEGNIORDPROD.COSTOUNITIMPEFFEURO, IMPEGNIORDPROD.COSTOTOTIMPEFFEURO, VISTAANAGRAFICAARTICOLI.GRUPPO, 
                      VISTAANAGRAFICAARTICOLI.CATEGORIA, VISTAANAGRAFICAARTICOLI.VARESPLICITE, VISTAANAGRAFICAARTICOLI.TIPOGESTIONE, 
                      VISTAANAGRAFICAARTICOLI.FLOORSTOCK, DATEDIFF(DAY, IMPEGNIORDPROD.DATAIMPEGNOSCH, IMPEGNIORDPROD.DATAIMPEGNORICH) AS RITARDO, 
                      IMPEGNIORDPROD.QTAGESTIONETRASF AS QTAGESTIONETRASFIMP, IMPEGNIORDPROD.RifCommCli, 
                      (CASE WHEN IMPEGNIORDPROD.QTAGESTIONE <> 0 THEN IMPEGNIORDPROD.QTAGESTIONEVERS / IMPEGNIORDPROD.QTAGESTIONE * 100 ELSE 0 END) 
                      AS AVANZQTAIMP, 
                      (CASE WHEN IMPEGNIORDPROD.COSTOTOTIMPPREV <> 0 THEN IMPEGNIORDPROD.COSTOTOTIMPEFF / IMPEGNIORDPROD.COSTOTOTIMPPREV * 100 ELSE 0 END)
                       AS AVANZCOSTIIMP, IMPEGNIORDPROD.DATAMODIFICA AS DATAULTIMAATTIMP, RIGHEORDPROD.STATOLANCIO, RIGHEORDPROD.STATOSTAMPA, 
                      RIGHEORDPROD.DATALANCIO, ExtraCommCli.ResponsabileCommessa, ExtraCommCli.RefCoordComm
FROM         RIGHEORDPROD LEFT OUTER JOIN
                      IMPEGNIORDPROD LEFT OUTER JOIN
                      VISTAANAGRAFICAARTICOLI ON IMPEGNIORDPROD.CODART = VISTAANAGRAFICAARTICOLI.CODICE ON IMPEGNIORDPROD.IDTESTA = RIGHEORDPROD.IDTESTA AND
                       IMPEGNIORDPROD.IDRIGA = RIGHEORDPROD.IDRIGA RIGHT OUTER JOIN
                      ExtraCommCli LEFT OUTER JOIN
                      TESTEORDINIPROD LEFT OUTER JOIN
                      AnagraficaCommesse ON TESTEORDINIPROD.RIFCOMMCLI = AnagraficaCommesse.RifComm ON 
                      ExtraCommCli.RifProgressivo = AnagraficaCommesse.Progressivo ON RIGHEORDPROD.IDTESTA = TESTEORDINIPROD.PROGRESSIVO


GO
GRANT DELETE
    ON OBJECT::[dbo].[ALD_VISTAIMPEGNICOMMESSEPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALD_VISTAIMPEGNICOMMESSEPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALD_VISTAIMPEGNICOMMESSEPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_VISTAIMPEGNICOMMESSEPROD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_VISTAIMPEGNICOMMESSEPROD] TO [Metodo98]
    AS [dbo];

