
CREATE VIEW [dbo].[ALD_Vista_XAggto_RigheCont_DateMovCont]
AS
SELECT     TC.PROGRESSIVO, TC.ESERCIZIO, RC.DATAREG, RC.DATARIF, TC.NRRIFER, TC.MOVIVA, TC.PROVVISORIO, TC.CAUSALE, TC.ANNOPLAFOND, 
                      TC.MESEPLAFOND, TC.DESCRIZIONE, TC.APPUNTI, TC.TOTDOCLIRE, TC.TOTDOCVALUTA, TC.TOTDOCEURO, TC.NRGIORNALE, TC.IDTESTADOC, 
                      TC.UTENTEMODIFICA, TC.DATAMODIFICA, TC.flgImpExp
FROM         TESTECONTABILITA AS TC INNER JOIN
                      RIGHECONTABILITA AS RC ON TC.PROGRESSIVO = RC.NRREG

GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_Vista_XAggto_RigheCont_DateMovCont] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_Vista_XAggto_RigheCont_DateMovCont] TO [Metodo98]
    AS [dbo];

