CREATE VIEW [dbo].[Aldb_VistacontabileADIGEST]
AS
SELECT     dbo.TESTECONTABILITA.PROGRESSIVO, dbo.TESTECONTABILITA.ESERCIZIO, dbo.TESTECONTABILITA.DATAREG, dbo.TESTECONTABILITA.DATARIF, 
                      dbo.TESTECONTABILITA.NRRIFER, dbo.TESTECONTABILITA.CAUSALE, dbo.TESTECONTABILITA.DESCRIZIONE, 
                      dbo.CAUSALICONTABILI.DESCRIZIONE AS DscCausale, dbo.TESTECONTABILITA.TOTDOCEURO,
                      (SELECT  CONTO  FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS CodiceAnagra,
                      (SELECT     RTRIM(ISNULL(dscconto1,'')) + ' ' + RTRIM(ISNULL(dscconto2,''))  FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS Ragsoc,
                      (SELECT     Indirizzo  FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS Indirizzo,
                      (SELECT     CAP  FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS Cap,
                      (SELECT     Localita  FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS Localita,
                      (SELECT     Provincia FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS Provincia,
                      (SELECT     PartitaIVA FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS PartitaIVA,
                      (SELECT     CodFiscale FROM          RIGHECONTABILITA, ANAGRAFICACF  WHERE      NRREG = TESTECONTABILITA.PROGRESSIVO AND NRRIGA = 1 AND CODCONTO = CONTO) AS CodFiscale

FROM         dbo.TESTECONTABILITA INNER JOIN
                      dbo.CAUSALICONTABILI ON dbo.TESTECONTABILITA.CAUSALE = dbo.CAUSALICONTABILI.CODICECAUSALE INNER JOIN
                      dbo.AdiGest_Contabilita ON dbo.TESTECONTABILITA.CAUSALE = dbo.AdiGest_Contabilita.CODICE




GO
GRANT DELETE
    ON OBJECT::[dbo].[Aldb_VistacontabileADIGEST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[Aldb_VistacontabileADIGEST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[Aldb_VistacontabileADIGEST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[Aldb_VistacontabileADIGEST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[Aldb_VistacontabileADIGEST] TO [Metodo98]
    AS [dbo];

