



CREATE VIEW [dbo].[ALDEBRA_VISTADOCUMENTALE_PERS]
AS
-- SELEZIONE TIPI DOCUMENTO CON FLAG (INTRA=0) IN PARAMETRI ADIGEST
SELECT DISTINCT
(CASE WHEN ISNULL(TD.PROGRESSIVO, 0) <> 0 THEN AD.PREFISSO + '-' + LTRIM(RTRIM(CONVERT(VARCHAR(20), TD.PROGRESSIVO))) + ISNULL(AD.SUFFISSO,'') ELSE AC.PREFISSO + '-' + RIGHT('00000000' + LTRIM(RTRIM(CONVERT(VARCHAR(20), TC.PROGRESSIVO))), 8) + ISNULL(AC.SUFFISSO,'') END) COLLATE SQL_Latin1_General_CP1_CI_AS AS KEYUNIQUE_PERS,
ISNULL(TD.CODAGENTE2,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS CODAGENTE2,
ISNULL(TD.CODAGENTE3,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS CODAGENTE3,
ISNULL(AG2.DSCAGENTE,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS DSCAGENTE2,
ISNULL(AG3.DSCAGENTE,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS DSCAGENTE3,
ISNULL(ETD.IdDivisione,0) AS IDDIVISIONE,
ISNULL(TD.CODPAGAMENTO,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS CODPAGAMENTO,
ISNULL(TP.DESCRIZIONE,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS DSCPAGAMENTO,
TABDITTE.DESBREVE COLLATE SQL_Latin1_General_CP1_CI_AS AS NOMEDITTA,
ISNULL(TD.TOTDOCUMENTOEURO,0) AS TOTDOCUMENTOEURO,
ISNULL(TD.TOTIMPONIBILEEURO,0) AS TOTIMPONIBILEEURO,
ISNULL(CAST(TD.NUMERODOC AS VARCHAR(15))+'/'+CAST(TD.ESERCIZIO AS VARCHAR(4))+TCO.AldSezionale,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS STRNDOC,
-- sara : campi nuovi
 isnull(TIpAg.IdTipologiacommAgente, ta. codice)  as  IdTipologiaCommAgente,
 isnull(TIpAg.Descrizione, ta. Descrizione) COLLATE SQL_Latin1_General_CP1_CI_AS as  TipologiaCommAgente, 
 Cid.IdRespCid COLLATE SQL_Latin1_General_CP1_CI_AS as CidCod, 
 Cid.Descrizione COLLATE SQL_Latin1_General_CP1_CI_AS as CidDescr ,
 Resp.IdResponsabile  as CodResposabile, 
 Resp.Descrizione COLLATE SQL_Latin1_General_CP1_CI_AS as Resposabile,
 RespConformitaACQ  as IDRespConformitaACQ, 
 TR.descrizione COLLATE SQL_Latin1_General_CP1_CI_AS as RespConformitaACQ
FROM         
TABDITTE,TESTEDOCUMENTI TD 
INNER JOIN ADIGEST_DOCUMENTI AD ON TD.TIPODOC COLLATE SQL_Latin1_General_CP1_CI_AS = AD.CODICE COLLATE SQL_Latin1_General_CP1_CI_AS
LEFT OUTER JOIN TESTECONTABILITA TC ON TD.PROGRESSIVO = TC.IDTESTADOC 
LEFT OUTER JOIN ADIGEST_CONTABILITA AC ON TC.CAUSALE = AC.CODICE
LEFT OUTER JOIN ANAGRAFICAAGENTI AG2 ON TD.CODAGENTE2=AG2.CODAGENTE
LEFT OUTER JOIN ANAGRAFICAAGENTI AG3 ON TD.CODAGENTE3=AG3.CODAGENTE
LEFT OUTER JOIN TABPAGAMENTI TP ON TD.CODPAGAMENTO=TP.CODICE
LEFT OUTER JOIN EXTRATESTEDOC ETD ON TD.PROGRESSIVO=ETD.IDTESTA
LEFT OUTER JOIN PARAMETRIDOC PDO ON TD.TIPODOC = PDO.CODICE
LEFT OUTER JOIN TABCONTATORI TCO ON TD.ESERCIZIO=TCO.ESERCIZIO AND PDO.CODICETAPPO=TCO.CODICE
-- aggiunta sara 
LEFT OUTER JOIN extraagenti XA  ON  TD.CODAGENTE3=XA.CodAgente
LEFT OUTER JOIN SL_TIPOAGENTE TA on Ta.Codice = TipoAgente
LEFT OUTER JOIN consMFM.dbo.CONS_ALD_TabRespCid Cid on xa.IdRespCid = cid.IdRespCid
LEFT OUTER JOIN consMFM.dbo.ALD_TABANAGRTIPOLOGIECOMMERCIALIAGENTE TIpAg on TIpAg.IdTipologiaCommAgente = XA.IdTipologiaCommAgente
LEFT OUTER JOIN ALD_VISTRARESPONSABILIATTIVIPERRUOLO Resp ON Resp.IdREsponsabile = XA.IdREsponsabile
LEFT OUTER JOIN TABRESPONSABILI TR on RespConformitaACQ = TR.Codice
UNION
SELECT  
(AC.PREFISSO + '-' + RIGHT('00000000' + LTRIM(RTRIM(CAST(TC.PROGRESSIVO AS VARCHAR(8)))), 8)+ ISNULL(AC.SUFFISSO,'')) COLLATE SQL_Latin1_General_CP1_CI_AS AS KEYUNIQUE_PERS,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS CODAGENTE2,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS CODAGENTE3,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS DSCAGENTE2,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS DSCAGENTE3,
0 AS IDDIVISIONE,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS CODPAGAMENTO,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS DSCPAGAMENTO,
TABDITTE.DESBREVE COLLATE SQL_Latin1_General_CP1_CI_AS AS NOMEDITTA,
ISNULL(TC.TOTDOCEURO,0) AS TOTDOCUMENTOEURO,
0 AS TOTIMPONIBILEEURO,
'' COLLATE SQL_Latin1_General_CP1_CI_AS AS STRNDOC,
-- sara : campi nuovi
0  as  IdTipologiaCommAgente,
'' COLLATE SQL_Latin1_General_CP1_CI_AS asTipologiaCommAgente,
'' COLLATE SQL_Latin1_General_CP1_CI_AS as CidCod, 
'' COLLATE SQL_Latin1_General_CP1_CI_AS as CidDescr ,
0  as CodResposabile,
 '' COLLATE SQL_Latin1_General_CP1_CI_AS as Resposabile,
0 as IDRespConformitaACQ,
 '' COLLATE SQL_Latin1_General_CP1_CI_AS as RespConformitaACQ
FROM
TABDITTE,TESTECONTABILITA TC
INNER JOIN ADIGEST_CONTABILITA AC ON TC.CAUSALE = AC.CODICE
WHERE ISNULL(IDTESTADOC,0)=0 AND ISNULL(AC.INTRA,0)=0 




GO
GRANT SELECT
    ON OBJECT::[dbo].[ALDEBRA_VISTADOCUMENTALE_PERS] TO [Metodo98]
    AS [dbo];

