



CREATE VIEW [dbo].[ALDEBRA_PDC_DOCFINANCE]
AS
SELECT	dbo.ALDSPC  ((SELECT  AZIENDA   FROM  ALDEBRA_DatiStandard), 10) AS AZIENDA,

		dbo.ALDSPC(dbo.ALDCLIFOR(dbo.ANAGRAFICACF.CODCONTO), 16) AS CODPDC, 

		dbo.ALDSPC(dbo.ANAGRAFICACF.TIPOCONTO, 1) AS TIPOCONTO,
		dbo.ALDSPC(dbo.ANAGRAFICACF.DSCCONTO1, 80) AS DESCRIZIONE,
		dbo.ALDSPC('',6) AS NOMIGNOLO, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.INDIRIZZO, 40) AS INDIRIZZO,
		dbo.ALDSPC(dbo.ANAGRAFICACF.CAP, 9) AS CAP, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.LOCALITA, 40) AS CITTA,
		dbo.ALDSPC((CASE WHEN dbo.ANAGRAFICACF.CODICEISO='IT' THEN  dbo.ANAGRAFICACF.PROVINCIA  ELSE '' END) , 2) AS PROVINCIA, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.CODICEISO, 4) AS NAZIONE,
		dbo.ALDSPC(dbo.EXTRABANCHE.BANCA, 8) AS CODBANCA,
		dbo.ALDSPC(dbo.EXTRABANCHE.RBN, 4) AS RBN,
		dbo.ALDSPC(dbo.EXTRACLIENTI.CodiceDeroga, 2) AS CODICEDEROGA,
		dbo.ALDSPC(dbo.EXTRACLIENTI.GiorniRitardo, 3)  AS RITARDO,
		dbo.ALDSPC((CASE WHEN dbo.BANCAAPPCF.ABI IS NULL  OR LTRIM(dbo.BANCAAPPCF.ABI)='' THEN '01' ELSE '01' END) , 4) AS LINEA,  
		dbo.ALDSPC(dbo.BANCAAPPCF.CONTOCORRENTE, 12) AS NRCC, 
		dbo.ALDSPC(RIGHT(dbo.BANCAAPPCF.ABI, 5), 5) AS ABI,
		dbo.ALDSPC(RIGHT(dbo.BANCAAPPCF.CAB, 5), 5) AS CAB, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.CODFISCALE, 16) AS CODFISCALE,
		dbo.ALDSPC((CASE WHEN dbo.ANAGRAFICACF.PARTITAIVA LIKE '%00000000000%'  THEN '' ELSE  dbo.ANAGRAFICACF.PARTITAIVA END), 11) AS PARTITAIVA, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.TELEX, 80) AS EMAIL, 
		dbo.ALDSPC(dbo.BANCAAPPCF.CIN, 1) AS CIN, 
		dbo.ALDSPC('',2) AS PAESEBIN,
		dbo.ALDSPC('', 2) AS CHECKPAESE,
		dbo.ALDSPC(dbo.BANCAAPPCF.CODICEBIC, 11)  AS CODICEBIC, 
		dbo.ALDSPC(dbo.BANCAAPPCF.CODICEIBAN, 34) AS CODICEIBAN
FROM   	((((dbo.ANAGRAFICACF LEFT OUTER JOIN
		dbo.ANAGRAFICARISERVATICF ON dbo.ANAGRAFICACF.CODCONTO = dbo.ANAGRAFICARISERVATICF.CODCONTO) LEFT OUTER JOIN
		dbo.BANCAAPPCF ON dbo.ANAGRAFICACF.CODCONTO = dbo.BANCAAPPCF.CODCONTO AND dbo.BANCAAPPCF.CODICE = dbo.ANAGRAFICARISERVATICF.BANCAANAGR ) LEFT OUTER JOIN
		dbo.EXTRACLIENTI ON dbo.EXTRACLIENTI.CODCONTO = dbo.ANAGRAFICACF.CODCONTO )LEFT OUTER JOIN 
		dbo.EXTRABANCHE ON dbo.ANAGRAFICARISERVATICF.CODBANCA = dbo.EXTRABANCHE.CODBANCA)
WHERE	(dbo.ANAGRAFICACF.TIPOCONTO = 'C') AND (dbo.ANAGRAFICARISERVATICF.ESERCIZIO=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME()))
UNION
SELECT	dbo.ALDSPC  ((SELECT  AZIENDA   FROM  ALDEBRA_DatiStandard), 10) AS AZIENDA,
		dbo.ALDSPC(dbo.ALDCLIFOR(dbo.ANAGRAFICACF.CODCONTO), 16) AS CODPDC, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.TIPOCONTO, 1) AS TIPOCONTO,
		dbo.ALDSPC(dbo.ANAGRAFICACF.DSCCONTO1, 80) AS DESCRIZIONE,
		dbo.ALDSPC('',6) AS NOMIGNOLO, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.INDIRIZZO, 40) AS INDIRIZZO,
		dbo.ALDSPC(dbo.ANAGRAFICACF.CAP, 9) AS CAP, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.LOCALITA, 40) AS CITTA,
		dbo.ALDSPC((CASE WHEN dbo.ANAGRAFICACF.CODICEISO='IT' THEN  dbo.ANAGRAFICACF.PROVINCIA  ELSE '' END) , 2) AS PROVINCIA, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.CODICEISO, 4) AS NAZIONE,
		dbo.ALDSPC(dbo.EXTRABANCHE.BANCA, 8) AS CODBANCA,
		dbo.ALDSPC(dbo.EXTRABANCHE.RBN, 4) AS RBN,
		dbo.ALDSPC(dbo.EXTRAFORNITORI.CodiceDeroga, 2) AS CODICEDEROGA,
		dbo.ALDSPC(dbo.EXTRAFORNITORI.GiorniRitardo, 3)  AS RITARDO,
		dbo.ALDSPC((CASE WHEN dbo.BANCAAPPCF.ABI IS NULL  OR LTRIM(dbo.BANCAAPPCF.ABI)='' THEN '01' ELSE '01' END) , 4) AS LINEA,  
		dbo.ALDSPC(dbo.BANCAAPPCF.CONTOCORRENTE, 12) AS NRCC, 
		dbo.ALDSPC(RIGHT(dbo.BANCAAPPCF.ABI, 5), 5) AS ABI,
		dbo.ALDSPC(RIGHT(dbo.BANCAAPPCF.CAB, 5), 5) AS CAB, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.CODFISCALE, 16) AS CODFISCALE,

		dbo.ALDSPC((CASE WHEN dbo.ANAGRAFICACF.PARTITAIVA LIKE '%00000000000%'  THEN '' ELSE  dbo.ANAGRAFICACF.PARTITAIVA END), 11) AS PARTITAIVA, 
		dbo.ALDSPC(dbo.ANAGRAFICACF.TELEX, 80) AS EMAIL, 
		dbo.ALDSPC(dbo.BANCAAPPCF.CIN, 1) AS CIN, 
		dbo.ALDSPC('',2) AS PAESEBIN,
		dbo.ALDSPC('', 2) AS CHECKPAESE,
		dbo.ALDSPC(dbo.BANCAAPPCF.CODICEBIC, 11)  AS CODICEBIC, 
		dbo.ALDSPC(dbo.BANCAAPPCF.CODICEIBAN, 34) AS CODICEIBAN
FROM   	((((dbo.ANAGRAFICACF LEFT OUTER JOIN
		dbo.ANAGRAFICARISERVATICF ON dbo.ANAGRAFICACF.CODCONTO = dbo.ANAGRAFICARISERVATICF.CODCONTO) LEFT OUTER JOIN
		dbo.BANCAAPPCF ON dbo.ANAGRAFICACF.CODCONTO = dbo.BANCAAPPCF.CODCONTO AND dbo.BANCAAPPCF.CODICE = dbo.ANAGRAFICARISERVATICF.BANCAANAGR ) LEFT OUTER JOIN
		dbo.EXTRAFORNITORI ON dbo.EXTRAFORNITORI.CODCONTO = dbo.ANAGRAFICACF.CODCONTO )LEFT OUTER JOIN 
		dbo.EXTRABANCHE ON dbo.ANAGRAFICARISERVATICF.CODBANCA = dbo.EXTRABANCHE.CODBANCA)
WHERE	(dbo.ANAGRAFICACF.TIPOCONTO = 'F') AND (dbo.ANAGRAFICARISERVATICF.ESERCIZIO=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME()))
UNION
SELECT     	dbo.ALDSPC((SELECT  AZIENDA  FROM  ALDEBRA_DatiStandard), 10) AS AZIENDA,
		dbo.ALDSPC(dbo.ALDCLIFOR(dbo.ANAGRAFICAGENERICI.CODCONTO), 16) AS CODPDC,
		dbo.ALDSPC( '-',1) AS TIPOCONTO, 
	             	dbo.ALDSPC(dbo.ANAGRAFICAGENERICI.DSCCONTO1, 80) AS DESCRIZIONE,
		dbo.ALDSPC('', 6) AS NOMIGNOLO,
		dbo.ALDSPC('',40) AS INDIRIZZO,
		dbo.ALDSPC('', 9) AS CAP,
		dbo.ALDSPC('', 40) AS CITTA, 
               	dbo.ALDSPC('', 2) AS PROVINCIA, 
		dbo.ALDSPC('', 4) AS NAZIONE, 
               	dbo.ALDSPC('', 8) AS CODBANCA, 
		dbo.ALDSPC('', 4) AS RBN,
		/*dbo.ALDSPC(Dbo.EXTRAGENERICI.CodiceDeroga,2) AS CODICEDEROGA,*/
		/* 0 AS CODICEDEROGA, corretto con riga a valore 'N'*/
		'  ' AS CODICEDEROGA,
		/*dbo.ALDSPC(dbo.EXTRAGENERICI.GiorniRitardo,3) AS RITARDO,*/
		'   ' AS RITARDO,
	        	dbo.ALDSPC('',4) AS LINEA, 
               	dbo.ALDSPC('', 12) AS NRCC,
		dbo.ALDSPC('', 5) AS ABI, 
		dbo.ALDSPC('', 5) AS CAB,
		dbo.ALDSPC('', 16) AS CODFISCALE, 
                	dbo.ALDSPC('', 11) AS PARTITAIVA,
		dbo.ALDSPC('', 80) AS EMAIL, 
	        	dbo.ALDSPC('', 1) AS CIN,
		dbo.ALDSPC('', 2) AS PAESEBIN, 
                	dbo.ALDSPC('', 2) AS CHECKPAESE,
		dbo.ALDSPC('', 11) AS CODICEBIC, 
                	dbo.ALDSPC('', 34) AS CODICEIBAN
FROM            	dbo.ANAGRAFICAGENERICI LEFT OUTER JOIN dbo.EXTRAGENERICI ON dbo.ANAGRAFICAGENERICI.CODCONTO=dbo.EXTRAGENERICI.CODCONTO







GO
GRANT SELECT
    ON OBJECT::[dbo].[ALDEBRA_PDC_DOCFINANCE] TO [Metodo98]
    AS [dbo];

