CREATE VIEW BRIOVISTAMOVCONT
AS
SELECT  RCONT.NRREG, 
		RCONT.NRRIGA, 
		TCONT.PROGRESSIVO, 
		TCONT.ESERCIZIO, 
		TCONT.DATAREG, 
		TCONT.NRRIFER, 
		TCONT.PROVVISORIO, 
		TCONT.MOVIVA, 
        TCONT.CAUSALE, 
		TCONT.MESEPLAFOND, 
		TCONT.DESCRIZIONE, 
		TCONT.APPUNTI, 
		TCONT.TOTDOCLIRE, 
		TCONT.TOTDOCVALUTA, 
		TCONT.TOTDOCEURO,
		TCONT.NRGIORNALE, 
		TCONT.IDTESTADOC, 
		RCONT.DATARIF, 
		RCONT.NRRIF, 
		RCONT.NRPARTITA, 
		RCONT.CONTO, 
		RCONT.SEGNO, 
		RCONT.IMPORTO, 
        RCONT.IMPORTOVALUTA, 
		RCONT.IMPORTOEURO, 
		RCONT.VALORECAMBIO, 
		RCONT.DESCRIZIONE AS DESCRIZIONERIGHE, 
		RCONT.DATAVALUTA, 
		RCONT.CPARTITA, 
        RCONT.RIGACAUSALE, 
		RCONT.CODCOMMESSA, 
		RCONT.CODCAMBIO,
        (SELECT TOP (1) NUMDOC FROM dbo.RIGHEIVA WHERE (NRREG = TCONT.PROGRESSIVO) AND (TIPOREGISTRO = TCONT.MOVIVA)) AS NUMDOC,
        (SELECT TOP (1) DATADOC FROM dbo.RIGHEIVA AS RIGHEIVA_1 WHERE(NRREG = TCONT.PROGRESSIVO) AND (TIPOREGISTRO = TCONT.MOVIVA)) AS DATADOC, CAUCONT.DESCRIZIONE AS DescrCauCont, 
                      dbo.TABCFG.DSCCONTO1, (CASE WHEN RCONT.SEGNO = 0 THEN RCONT.IMPORTO ELSE 0 END) AS DARE, 
                      (CASE WHEN RCONT.SEGNO = 0 THEN RCONT.IMPORTOEURO ELSE 0 END) AS DAREEURO, 
                      (CASE WHEN RCONT.SEGNO = 0 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS DAREVALUTA, (CASE WHEN RCONT.SEGNO = 1 THEN RCONT.IMPORTO ELSE 0 END)
                       AS AVERE, (CASE WHEN RCONT.SEGNO = 1 THEN RCONT.IMPORTOEURO ELSE 0 END) AS AVEREEURO, 
                      (CASE WHEN RCONT.SEGNO = 1 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS AVEREVALUTA, 
                      SUBSTRING('01-GEN02-FEB03-MAR04-APR05-MAG06-GIU07-LUG08-AGO09-SET10-OTT11-NOV12-DIC', (MONTH(TCONT.DATAREG) - 1) * 6 + 1, 6) AS Mese
FROM        dbo.RIGHECONTABILITA AS RCONT LEFT OUTER JOIN 
			dbo.TESTECONTABILITA AS TCONT ON RCONT.NRREG = TCONT.PROGRESSIVO INNER JOIN
			dbo.CAUSALICONTABILI AS CAUCONT ON TCONT.CAUSALE = CAUCONT.CODICECAUSALE INNER JOIN
            dbo.TABCFG ON RCONT.CONTO = dbo.TABCFG.CODCONTO
WHERE     (TCONT.CAUSALE <>
                          (SELECT     CAUSCONTAP
                            FROM          dbo.TABVINCOLIGIC AS GIC
                            WHERE      (ESERCIZIO = TCONT.ESERCIZIO))) AND (TCONT.CAUSALE <>
                          (SELECT     CAUSCONTCH
                            FROM          dbo.TABVINCOLIGIC AS GIC
                            WHERE      (ESERCIZIO = TCONT.ESERCIZIO)))

GO
GRANT SELECT
    ON OBJECT::[dbo].[BRIOVISTAMOVCONT] TO [Metodo98]
    AS [dbo];

