CREATE VIEW BRIOVISTALISTINIRIGHE
AS
SELECT
LA.CODART, LA.NRLISTINO, LA.UM, LA.PREZZOEURO*FC.FATTORE AS PREZZOEURO, FC.FATTORE
FROM LISTINIARTICOLI LA
INNER JOIN ARTICOLIFATTORICONVERSIONE FC ON LA.CODART=FC.CODART AND FC.UM2=LA.UM
WHERE FC.UM1= (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = LA.CODART AND UMP.TIPOUM = 1)


GO
GRANT SELECT
    ON OBJECT::[dbo].[BRIOVISTALISTINIRIGHE] TO [Metodo98]
    AS [dbo];

