CREATE VIEW BudVistaDocumentiBudget AS 
    SELECT TD.CODCLIFOR, RD.CODART, (CASE WHEN AA.CODICEPRIMARIO = '' OR AA.CODICEPRIMARIO IS NULL THEN RD.CODART ELSE 
           AA.CODICEPRIMARIO END) AS MODELLO, RD.TIPODOC, TD.DATADOC, RD.UMPREZZO, RD.QTAPREZZO, RD.TOTNETTORIGAEURO, EC.TipoClienteBudget, 
           EC.ConsideraBudget, TD.Stagione, TD.AnnoStagione, RD.DATACONSEGNA, RD.NUMLISTINO, RD.VERSIONEDIBA
    FROM RIGHEDOCUMENTI RD INNER JOIN TESTEDOCUMENTI TD ON RD.IDTESTA = TD.PROGRESSIVO 
         INNER JOIN ANAGRAFICACF EC ON TD.CODCLIFOR = EC.CODCONTO
         INNER JOIN ANAGRAFICAARTICOLI AA ON RD.CODART = AA.CODICE
    WHERE RD.CODART <> '' 

GO
GRANT SELECT
    ON OBJECT::[dbo].[BudVistaDocumentiBudget] TO [Metodo98]
    AS [dbo];

