
CREATE VIEW [dbo].[CONTRATTILIQUIDAZIONE_CLMERCEVALORECONDATA]
AS
SELECT     TOP (100) PERCENT 'INCONDIZIONATI' AS TIPOCONTRIBUTO, dbo.CONTRATTI_CL.RIFPROGRESSIVO AS RifContratto, dbo.CONTRATTI_CL.NRRIGA AS RifContributo, 
                      0 AS RIFSOTTORIGA, 0 AS RIFSOTTORIGACOND, dbo.CONTRATTI_CL.DESCRIZIONE AS NOTA, 'MERCEVALORE' AS TIPOLOGIA, '' AS DADATA, '' AS ADATA, 
                      0 AS BudgetQta, '' AS Um, 0 AS BudgetValore, 0 AS BudgetQtaConValore, '' AS UmQtaConValore, dbo.CONTRATTI_CL.MERCEVALORE AS PREMIOVALORE, 
                      0 AS PREMIOPERCENTUALE, 0 AS CONSUNTIVATOQTA, 0 AS CONSUNTIVATOVALORE, dbo.CONTRATTI_CL.MERCEVALORE AS PREMIOMATURATO, 
                      dbo.CONTRATTI_CL.PERIODICITALIQUIDAZIONE, CASE WHEN TIPO IS NULL THEN 1 ELSE TIPO END AS TIPO, dbo.CONTRATTI_CL.TIPOCALCOLOPREMIO, 
                      dbo.CONTRATTICL_DATEDOC.DATAEMISSIONE, dbo.CONTRATTICL_DATEDOC.VALORE, dbo.CONTRATTICL_DATEDOC.EMESSO, 
                      dbo.CONTRATTICL_DATEDOC.RIFPROGRESSIVODOC, dbo.CONTRATTICL_DATEDOC.NRRIGA AS RIGARATA, dbo.CONTRATTICL_DATEDOC.VALOREEFFETTIVO, 
                      dbo.CONTRATTI_CL.PREMIONONVALIDO
FROM         dbo.CONTRATTI_CL INNER JOIN
                      dbo.CONTRATTICL_DATEDOC ON dbo.CONTRATTI_CL.RIFPROGRESSIVO = dbo.CONTRATTICL_DATEDOC.RIFPROGRESSIVOCL AND 
                      dbo.CONTRATTI_CL.NRRIGA = dbo.CONTRATTICL_DATEDOC.RIFPROGRESSIVO
WHERE     (dbo.CONTRATTI_CL.MERCEVALORE > 0) AND (dbo.CONTRATTI_CL.ESCLUSOLOGICAMENTE = 0)
ORDER BY RifContratto, RifContributo, RIFSOTTORIGA


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_CLMERCEVALORECONDATA] TO [Metodo98]
    AS [dbo];

