
CREATE VIEW [dbo].[CONTRATTILIQUIDAZIONE_CLMERCEQTA]
AS
SELECT     TOP (100) PERCENT 'INCONDIZIONATI' AS TIPOCONTRIBUTO, dbo.CONTRATTI_CL.RIFPROGRESSIVO AS RifContratto, dbo.CONTRATTI_CL.NRRIGA AS RifContributo, 
                      0 AS RIFSOTTORIGA, 0 AS RIFSOTTORIGACOND, dbo.CONTRATTI_CL.DESCRIZIONE AS NOTA, 'MERCEQTA' AS TIPOLOGIA, '' AS DADATA, '' AS ADATA, 0 AS BudgetQta,
                       '' AS Um, 0 AS BudgetValore, 0 AS BudgetQtaConValore, '' AS UmQtaConValore, dbo.CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE.Expr1 AS PREMIOVALORE, 
                      0 AS PREMIOPERCENTUALE, 0 AS CONSUNTIVATOQTA, 0 AS CONSUNTIVATOVALORE, 
                      dbo.CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE.Expr1 AS PREMIOMATURATO, dbo.CONTRATTI_CL.PERIODICITALIQUIDAZIONE, 
                      CASE WHEN dbo.CONTRATTI_CL.TIPO IS NULL THEN 1 ELSE dbo.CONTRATTI_CL.TIPO END AS TIPO, dbo.CONTRATTI_CL.TIPOCALCOLOPREMIO, 
                      dbo.CONTRATTI_CL.PREMIONONVALIDO
FROM         dbo.CONTRATTI_CL INNER JOIN
                      dbo.CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE ON 
                      dbo.CONTRATTI_CL.RIFPROGRESSIVO = dbo.CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE.RIFPROGRESSIVOCL AND 
                      dbo.CONTRATTI_CL.NRRIGA = dbo.CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE.RIFPROGRESSIVO
WHERE     (dbo.CONTRATTI_CL.MERCEQTA > 0) AND (dbo.CONTRATTI_CL.ESCLUSOLOGICAMENTE = 0)
ORDER BY RifContratto, RifContributo, RIFSOTTORIGA


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_CLMERCEQTA] TO [Metodo98]
    AS [dbo];

