

CREATE VIEW DF_AC_FATTURATO
AS

SELECT T.[PROGRESSIVO]
      ,T.[ESERCIZIO]
      ,T.[TIPODOC]
      ,T.[NUMERODOC]
      ,T.[BIS]
      ,T.[DATADOC]
      ,T.[DOCCHIUSO]
      ,T.[CODCLIFOR]
      ,T.[NUMRIFDOC]
      ,T.[DATARIFDOC]
      ,T.[CODLISTINO]
      ,T.[CODAGENTE1]
      ,T.[CODAGENTE2]
      ,T.[CODAGENTE3]
      ,(T.[TOTIMPONIBILEEURO] * T.[SEGNO]) AS [TOTIMPONIBILEEURO]
  FROM [TESTEDOCUMENTI] T,
       [PARAMETRIDOC] P
  WHERE
        P.TIPO IN('F','N') AND P.CLIFOR = 'C' AND P.CODICE = T.TIPODOC

GO
GRANT SELECT
    ON OBJECT::[dbo].[DF_AC_FATTURATO] TO [Metodo98]
    AS [dbo];

