
CREATE VIEW FRCVistaArticoliVB AS 
	SELECT AMBIENTE, ANNODOC, CODART, GRUPPO, CATEGORIA, CODCATEGORIASTAT, SERIE, MODELLO, SUM(QTAGEST) AS QTAGEST, SUM(QTAPREZZO) AS QTAPREZZO
	FROM FRCDatiVenditeBudget
	GROUP BY AMBIENTE, ANNODOC, CODART, GRUPPO, CATEGORIA, CODCATEGORIASTAT, SERIE, MODELLO

GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaArticoliVB] TO [Metodo98]
    AS [dbo];

