
CREATE VIEW FRCVistaDatiMaterialiComponenti AS 
	SELECT T1.AMBIENTE AS Ambiente, T1.ANNODOC AS Anno, T1.MESEDOC AS Mese, T1.ANNOMESEDOC, T2.NomeEsplosione AS Nome_Esplosione, T2.COMPONENTE AS Componente, 
	       T3.DESCRIZIONE AS Descrizione_Componente, T2.UMCOMPONENTE AS UM, T3.GRUPPO AS Gruppo, T3.CATEGORIA AS Categoria, T3.CODCATEGORIASTAT AS Categoria_Statistica, 
		   SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA) AS Quantita, SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA * T2.COSTOUNIEURO) AS Valore, 
		   SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA * T2.COSTOUNIEURO) + 
		   ROUND(((SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA * T2.COSTOUNIEURO) * 
		   ISNULL((SELECT Resa FROM FRCParametriDB WHERE Ambiente = T1.AMBIENTE AND Anno = T1.ANNODOC AND Gruppo = T3.GRUPPO AND Categoria = 0 AND CategoriaStat = 0), 0)) / 100), 6) + 
		   ROUND(((SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA * T2.COSTOUNIEURO) * 
		   ISNULL((SELECT Resa FROM FRCParametriDB WHERE Ambiente = T1.AMBIENTE AND Anno = T1.ANNODOC AND Gruppo = 0 AND Categoria = T3.CATEGORIA AND CategoriaStat = 0), 0)) / 100), 6) + 
		   ROUND(((SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA * T2.COSTOUNIEURO) * 
		   ISNULL((SELECT Resa FROM FRCParametriDB WHERE Ambiente = T1.AMBIENTE AND Anno = T1.ANNODOC AND Gruppo = 0 AND Categoria = 0 AND CategoriaStat = T3.CODCATEGORIASTAT), 0)) / 100), 6) + 
		   ROUND(((SUM(T1.QTAGEST * T1.FATTORE * T2.QUANTITA * T2.COSTOUNIEURO) * 
		   ISNULL((SELECT Resa FROM FRCParametriDB WHERE Ambiente = T1.AMBIENTE AND Anno = T1.ANNODOC AND Gruppo = 0 AND Categoria = 0 AND CategoriaStat = 0), 0)) / 100), 6) AS Valore_Resa, 
		   CASE WHEN EXISTS (SELECT FORNPREFACQ FROM ANAGRAFICAARTICOLIPROD WHERE CODICEART = T2.COMPONENTE AND ESERCIZIO = T1.ANNODOC) THEN
		   (SELECT FORNPREFACQ FROM ANAGRAFICAARTICOLIPROD WHERE CODICEART = T2.COMPONENTE AND ESERCIZIO = T1.ANNODOC) ELSE
		   (SELECT FORNPREFACQ FROM ANAGRAFICAARTICOLIPROD WHERE CODICEART = T2.COMPONENTE AND ESERCIZIO = (T1.ANNODOC - 1)) END AS Fornitore, 
		   ISNULL(CASE WHEN EXISTS (SELECT FORNPREFACQ FROM ANAGRAFICAARTICOLIPROD WHERE CODICEART = T2.COMPONENTE AND ESERCIZIO = T1.ANNODOC) THEN
		   (SELECT DSCCONTO1 FROM ANAGRAFICAARTICOLIPROD TT1 INNER JOIN ANAGRAFICACF TT2 ON TT1.FORNPREFACQ = TT2.CODCONTO WHERE TT1.CODICEART = T2.COMPONENTE AND TT1.ESERCIZIO = T1.ANNODOC) ELSE
		   (SELECT DSCCONTO1 FROM ANAGRAFICAARTICOLIPROD TT1 INNER JOIN ANAGRAFICACF TT2 ON TT1.FORNPREFACQ = TT2.CODCONTO WHERE TT1.CODICEART = T2.COMPONENTE AND TT1.ESERCIZIO = (T1.ANNODOC - 1)) END, '') AS Ragione_Sociale 
	FROM FRCDatiVenditeBudget T1 INNER JOIN FRCDistinteBasiEsplose T2 ON T1.CODART = T2.COMPOSTO AND T1.ANNODOC = T2.ANNO
	     INNER JOIN ANAGRAFICAARTICOLI T3 ON T2.COMPONENTE = T3.CODICE
	GROUP BY T1.AMBIENTE, T1.ANNODOC, T1.MESEDOC, T1.ANNOMESEDOC, T2.NomeEsplosione, T2.COMPONENTE, T3.DESCRIZIONE, T2.UMCOMPONENTE, T3.GRUPPO, T3.CATEGORIA, T3.CODCATEGORIASTAT

GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaDatiMaterialiComponenti] TO [Metodo98]
    AS [dbo];

