
CREATE VIEW FRCVistaOreDatiCicli2 AS 
	SELECT AMBIENTE AS Ambiente, ANNO AS Anno, MESEDOC AS Mese, CDCMop AS Centro, SUM(TEMPOUOMOTOT) AS Ore
	FROM FRCDatiCicli
	GROUP BY AMBIENTE, ANNO, MESEDOC, CDCMop
	HAVING SUM(TEMPOUOMOTOT) <> 0
	UNION ALL
	SELECT AMBIENTE AS Ambiente, ANNO AS Anno, MESEDOC AS Mese, CDCSetup AS Centro, SUM(TEMPOSETUPTOT) AS Ore
	FROM FRCDatiCicli
	GROUP BY AMBIENTE, ANNO, MESEDOC, CDCSetup
	HAVING SUM(TEMPOSETUPTOT) <> 0

GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaOreDatiCicli2] TO [Metodo98]
    AS [dbo];

