
CREATE VIEW FRCVistaArticoliVB2 AS 
	SELECT AMBIENTE, ANNODOC, CODART, GRUPPO, CATEGORIA, CODCATEGORIASTAT, SERIE, MODELLO, GENCONTROP, SUM(QTAGEST) AS QTAGEST, SUM(QTAPREZZO) AS QTAPREZZO
	FROM FRCDatiVenditeBudget
	GROUP BY AMBIENTE, ANNODOC, CODART, GRUPPO, CATEGORIA, CODCATEGORIASTAT, SERIE, MODELLO, GENCONTROP

GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaArticoliVB2] TO [Metodo98]
    AS [dbo];

