
CREATE VIEW FRCVistaClienti AS 
	SELECT ANAGRAFICACF.TIPOCONTO, ANAGRAFICACF.CODCONTO AS CODCLIFOR, ANAGRAFICACF.DSCCONTO1, RIGHT(ANAGRAFICACF.DSCCONTO1, 150) + ' - ' + RIGHT(ANAGRAFICACF.CODCONTO, 50) AS CLIENTE, 
		   ISNULL(ANAGRAFICARISERVATICF.CODSETTORE, 0) AS CODSETTORE, ISNULL(TABSETTORI.DESCRIZIONE, '') AS DESCSETTCLI, 
		   ISNULL(ANAGRAFICARISERVATICF.CODZONA, 0) AS CODZONA, ISNULL(TABZONE.DESCRIZIONE, '') AS DESCZONACLI, ISNULL(ANAGRAFICARISERVATICF.CODCATEGORIA, 0) AS CODCATEGORIA, 
		   ISNULL(CATEGORIECF.DSCCATEGORIA, '') AS DESCCATCLI, ISNULL(ANAGRAFICACF.LOCALITA, '') AS LOCALITA, ISNULL(ANAGRAFICACF.PROVINCIA, '') AS PROVINCIA, 
		   ISNULL(ANAGRAFICACF.CODNAZIONE, 0) AS CODNAZIONE, ISNULL(ANAGRAFICACF.CODICEISO, '') AS CODICEISO, ISNULL(ANAGRAFICACF.CODREGIONE, '') AS CODREGIONE, 
		   ISNULL(ANAGRAFICARISERVATICF.CODAGENTE1, '') AS CODAGENTE1, ISNULL(ANAGRAFICAAGENTI_1.DSCAGENTE, '') AS DSCAGENTE1, 
		   RIGHT(ISNULL(ANAGRAFICAAGENTI_1.DSCAGENTE, ''), 150) + ' - ' + RIGHT(ISNULL(ANAGRAFICARISERVATICF.CODAGENTE1, ''), 50) AS AGENTE1, ISNULL(ANAGRAFICARISERVATICF.CODAGENTE2, '') AS CODAGENTE2, 
		   ISNULL(ANAGRAFICAAGENTI_2.DSCAGENTE, '') AS DSCAGENTE2, RIGHT(ISNULL(ANAGRAFICAAGENTI_2.DSCAGENTE, ''), 150) + ' - ' + RIGHT(ISNULL(ANAGRAFICARISERVATICF.CODAGENTE2, ''), 50) 
		   AS AGENTE2, ISNULL(ANAGRAFICARISERVATICF.CODAGENTE3, '') AS CODAGENTE3, ISNULL(ANAGRAFICAAGENTI_3.DSCAGENTE, '') AS DSCAGENTE3, RIGHT(ISNULL(ANAGRAFICAAGENTI_3.DSCAGENTE, ''), 150) 
		   + ' - ' + RIGHT(ISNULL(ANAGRAFICARISERVATICF.CODAGENTE3, ''), 50) AS AGENTE3, (SELECT DESCRIZIONE FROM TABNAZIONI WHERE CODICE = ISNULL(ANAGRAFICACF.CODNAZIONE, 0)) AS NAZIONE, ANAGRAFICACF.TipoClienteBudget
	FROM ANAGRAFICACF LEFT OUTER JOIN ANAGRAFICARISERVATICF ON ANAGRAFICACF.CODCONTO = ANAGRAFICARISERVATICF.CODCONTO AND ANAGRAFICARISERVATICF.ESERCIZIO = (SELECT MAX(CODICE) FROM TABESERCIZI)
	     LEFT OUTER JOIN TABZONE ON ANAGRAFICARISERVATICF.CODZONA = TABZONE.CODICE
	     LEFT OUTER JOIN TABSETTORI ON ANAGRAFICARISERVATICF.CODSETTORE = TABSETTORI.CODICE
	     LEFT OUTER JOIN CATEGORIECF ON ANAGRAFICARISERVATICF.CODCATEGORIA = CATEGORIECF.CODCATEGORIA
	     LEFT OUTER JOIN ANAGRAFICAAGENTI AS ANAGRAFICAAGENTI_1 ON ANAGRAFICARISERVATICF.CODAGENTE1 = ANAGRAFICAAGENTI_1.CODAGENTE
	     LEFT OUTER JOIN ANAGRAFICAAGENTI AS ANAGRAFICAAGENTI_2 ON ANAGRAFICARISERVATICF.CODAGENTE2 = ANAGRAFICAAGENTI_2.CODAGENTE
		 LEFT OUTER JOIN ANAGRAFICAAGENTI AS ANAGRAFICAAGENTI_3 ON ANAGRAFICARISERVATICF.CODAGENTE3 = ANAGRAFICAAGENTI_3.CODAGENTE
	WHERE ANAGRAFICACF.TIPOCONTO = 'C'

GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaClienti] TO [Metodo98]
    AS [dbo];

