

CREATE VIEW PL_VISTACONFIGIMBALLI
AS 

    select TP.PROGRESSIVO,RP.NRRIGA,  
           TP.CODCLIENTE,TP.CODARTICOLO AS ARTCOMPOSTO,TP.QTARIF,TP.UMRIF,
           RP.CODIMBALLO,RP.NUMIMBALLI,RP.VOLUME,
           RDP.CODARTICOLO AS ARTCOMPONENTE,AA.DESCRIZIONE AS DSCARTCOMPONENTE,
           RDP.UM,RDP.QTA,RDP.PESONETTO,RDP.CUBATURA              
    from TESTAPACKINGLIST TP INNER JOIN 
    RIGHEPACKINGLIST RP ON TP.PROGRESSIVO = RP.RIFPROGRESSIVO INNER JOIN       
    RIGHEDETTAGLIOPACKINGLIST RDP ON RP.RIFPROGRESSIVO=RDP.RIFPROGRESSIVO  AND RP.NRRIGA=RDP.RIFNRRIGA INNER JOIN  
    ANAGRAFICAARTICOLI AA ON RDP.CODARTICOLO = AA.CODICE 


GO
GRANT SELECT
    ON OBJECT::[dbo].[PL_VISTACONFIGIMBALLI] TO [Metodo98]
    AS [dbo];

