create view TDA_VISTALISTAVERSAMENTO as
	select 
		TDA.PROGRESSIVO,VER.IDRIGA,BLV.ANNOBOLLA,BLV.NUMEROBOLLA,RPR.CODICEORD,RPR.CODART,
		'' as TIPOLISTA
	from 
		TDA_FEEDBACK TDA
		inner join TDA_DETTFEEDBACK_CONSUNTIVO BLV on BLV.RIFPROGRESSIVO=TDA.PROGRESSIVO
		inner join TDA_DETTFEEDBACK_VERSAMENTO VER on VER.RIFPROGRESSIVO=TDA.PROGRESSIVO
		inner join RIGHECICLOORDINE RCO on RCO.ANNOBOLLA=BLV.ANNOBOLLA and RCO.NUMEROBOLLA=BLV.NUMEROBOLLA
		inner join TESTACICLOORDINE TCO on TCO.PROGRESSIVO=BLV.RIFPROGRESSIVO
		inner join RIGHEORDPROD RPR on RPR.IDTESTA=TCO.IDTESTACOMM and RPR.IDRIGA=TCO.IDRIGACOMM

GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_VISTALISTAVERSAMENTO] TO [Metodo98]
    AS [dbo];

