
CREATE VIEW TP_ULTIMOLIVELLOMERCEOLOGICO
AS
	SELECT 
		CODICE,
		DESCRIZIONE 
	FROM 
		TP_LIVELLIMERCEOLOGICI
	WHERE CODICE NOT IN(SELECT CODICEPADRE FROM TP_LIVELLIMERCEOLOGICI)

GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_ULTIMOLIVELLOMERCEOLOGICO] TO [Metodo98]
    AS [dbo];

