
CREATE VIEW TP_VISTA_UMARTICOLI	AS
	SELECT ARTICOLIUMPREFERITE.CODART,TABUNITAMISURA.CODICE,TABUNITAMISURA.DESCRIZIONE 
	FROM TABUNITAMISURA 
		INNER JOIN ARTICOLIUMPREFERITE 
			ON ARTICOLIUMPREFERITE.UM=TABUNITAMISURA.CODICE 
	GROUP BY TABUNITAMISURA.CODICE,TABUNITAMISURA.DESCRIZIONE,ARTICOLIUMPREFERITE.CODART



GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTA_UMARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTA_UMARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_VISTA_UMARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTA_UMARTICOLI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTA_UMARTICOLI] TO [Metodo98]
    AS [dbo];

