
CREATE VIEW TP_VISTASTAMPAMULTIPRESAMISSIONI AS

SELECT 
  TabTesteMissioni.PROGRESSIVO AS PROG_MISS,
  TabTesteDocumentiMiss.PROGRESSIVO,
  TabTesteDocumentiMiss.PROGRESSDOC,
  TabTesteDocumentiMiss.RIFPROGRTESTAMISS, 
  TabTesteDocumentiMiss.CODCLI,
  TabTesteDocumentiMiss.CODDESTINAZIONE, 
  TabTesteDocumentiMiss.RAGSOCDDM,
  TabTesteDocumentiMiss.CODICESPED,
  TabRigheDocumentiMiss.IDRIGA,
  TabRigheDocumentiMiss.IDRIGADOC,
  TabRigheDocumentiMiss.CODART,
  TabRigheDocumentiMiss.DESCART,
  TabRigheDocumentiMiss.UM,
  TabRigheDocumentiMiss.QTACONSEG,
  TabRigheDocumentiMiss.NRRIFPARTITA,
  TabRigheDocumentiMiss.DATACONSEGNA,
  TabRigheDocumentiMiss.IDRIGAPADRE,
  TabRigheDocumentiMiss.CODUBICAZIONE,
  TabRigheDocumentiMiss.TIPOUBICAZIONE,
  ARTICOLIFATTORICONVERSIONE.FATTORE, 
  (TabRigheDocumentiMiss.QTACONSEG * ISNULL(ARTICOLIFATTORICONVERSIONE.FATTORE,0)) AS QTA_MISS, 
  (CASE WHEN RIGHEDOCUMENTI.SCONTORIGA=100 THEN 1 ELSE 0 END) AS SCONTOMERCE

FROM TabTesteMissioni 
 
 INNER JOIN TabTesteDocumentiMiss 
   ON TabTesteMissioni.PROGRESSIVO=TabTesteDocumentiMiss.RIFPROGRTESTAMISS 
 INNER JOIN TabRigheDocumentiMiss
  ON TabTesteDocumentiMiss.PROGRESSIVO=TabRigheDocumentiMiss.IDTESTA
 INNER JOIN TESTEDOCUMENTI ON 
 TabTesteDocumentiMiss.PROGRESSDOC=TESTEDOCUMENTI.PROGRESSIVO
 INNER JOIN RIGHEDOCUMENTI
  ON RIGHEDOCUMENTI.IDTESTA=TESTEDOCUMENTI.PROGRESSIVO AND RIGHEDOCUMENTI.IDRIGA=TabRigheDocumentiMiss.IDRIGADOC
 LEFT OUTER JOIN ARTICOLIFATTORICONVERSIONE 
  ON ARTICOLIFATTORICONVERSIONE.CODART=TabRigheDocumentiMiss.CODART
  AND 
  ARTICOLIFATTORICONVERSIONE.UM1=TabRigheDocumentiMiss.UM
  AND 
  ARTICOLIFATTORICONVERSIONE.UM2=TabTesteMissioni.UM



GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTASTAMPAMULTIPRESAMISSIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTASTAMPAMULTIPRESAMISSIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_VISTASTAMPAMULTIPRESAMISSIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASTAMPAMULTIPRESAMISSIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTASTAMPAMULTIPRESAMISSIONI] TO [Metodo98]
    AS [dbo];

