

CREATE VIEW TP_VISTA_DISTINCT_RELSCONTIFORCLIFOR
AS

SELECT DISTINCT PROGSCONTO , CONTRATTO FROM TP_RELSCONTIFORCLIFOR



GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTA_DISTINCT_RELSCONTIFORCLIFOR] TO [Metodo98]
    AS [dbo];

