

CREATE view TP_VISTA_AGEPV
AS
	SELECT CODAGENTE AS CODICE,DSCAGENTE AS DESCRIZIONE,ULTPREPAR, PATHR AS RICEZ,PATHT AS TRASF FROM TP_TRASFAGENTI
	WHERE ATTIVO=1
	UNION
	SELECT CODCONTO AS CODICE,DSCCONTO AS DESCRIZIONE,ULTPREPAR , PATHR AS RICEZ,PATHT AS TRASF FROM TP_PUNTIVENDITA
	WHERE ATTIVO=1

GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTA_AGEPV] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTA_AGEPV] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_VISTA_AGEPV] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTA_AGEPV] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTA_AGEPV] TO [Metodo98]
    AS [dbo];

