CREATE VIEW [dbo].[TP_VISTASCTLOGGRPCTRVAL]
AS
SELECT      TP_TESTE_SCONTI_LOGISTICICTR.DADATA, TP_TESTE_SCONTI_LOGISTICICTR.ADATA, 
                      TP_TESTE_SCONTI_LOGISTICICTR.CODCLIFOR, TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO,TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIASCONTO,
                      TP_TESTE_SCONTI_LOGISTICICTR.TIPO_TOTALE,TP_TESTE_SCONTI_LOGISTICICTR.RifContratto, 
                      ANAGRAFICAARTICOLI.CODICE, 
                      TP_RIGHE_SCONTI_LOGISTICI_GRUPPOCTR.UM, TP_RIGHE_SCONTI_LOGISTICI_GRUPPOCTR.VALORE, 
                      TP_RIGHE_SCONTI_LOGISTICI_GRUPPOCTR.SCONTO
FROM         TP_TESTE_SCONTI_LOGISTICICTR INNER JOIN
                      TP_RIGHE_SCONTI_LOGISTICI_GRUPPOCTR ON 
                      TP_TESTE_SCONTI_LOGISTICICTR.PROGRESSIVO = TP_RIGHE_SCONTI_LOGISTICI_GRUPPOCTR.RIFPROGRESSIVO INNER JOIN
                      ANAGRAFICAARTICOLI ON dbo.TP_RIGHE_SCONTI_LOGISTICI_GRUPPOCTR.GRUPPO = ANAGRAFICAARTICOLI.GRUPPO
WHERE     (TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO = 0) AND (ANAGRAFICAARTICOLI.GRUPPO <> 0)

GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASCTLOGGRPCTRVAL] TO [Metodo98]
    AS [dbo];

