

CREATE VIEW TP_VISTA_DISTINCT_RELSCONTILOGCLIFOR
AS

SELECT DISTINCT PROGSCONTO , CONTRATTO FROM TP_RELSCONTILOGCLIFOR



GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTA_DISTINCT_RELSCONTILOGCLIFOR] TO [Metodo98]
    AS [dbo];

