CREATE VIEW [dbo].[TP_VISTASCTLOGCATCTRVAL]
AS
SELECT     TP_TESTE_SCONTI_LOGISTICICTR.DADATA, TP_TESTE_SCONTI_LOGISTICICTR.ADATA, 
                      TP_TESTE_SCONTI_LOGISTICICTR.CODCLIFOR, TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO,TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIASCONTO,
                      TP_TESTE_SCONTI_LOGISTICICTR.TIPO_TOTALE,TP_TESTE_SCONTI_LOGISTICICTR.RifContratto, 
                      ANAGRAFICAARTICOLI.CODICE, 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIACTR.UM, TP_RIGHE_SCONTI_LOGISTICI_CATEGORIACTR.VALORE, 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIACTR.SCONTO
FROM         TP_TESTE_SCONTI_LOGISTICICTR INNER JOIN
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIACTR ON 
                      TP_TESTE_SCONTI_LOGISTICICTR.PROGRESSIVO = TP_RIGHE_SCONTI_LOGISTICI_CATEGORIACTR.RIFPROGRESSIVO INNER JOIN
                      ANAGRAFICAARTICOLI ON dbo.TP_RIGHE_SCONTI_LOGISTICI_CATEGORIACTR.CATEGORIA = ANAGRAFICAARTICOLI.CATEGORIA
WHERE     (TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO = 1) AND (ANAGRAFICAARTICOLI.CATEGORIA <> 0)

GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASCTLOGCATCTRVAL] TO [Metodo98]
    AS [dbo];

