

CREATE VIEW TP_VISTA_DISTINCT_RELPROMOCLIFOR
AS
SELECT DISTINCT PROMOZIONE, CONTRATTO
FROM   TP_RELPROMOCLIFOR



GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTA_DISTINCT_RELPROMOCLIFOR] TO [Metodo98]
    AS [dbo];

