
CREATE VIEW TP_VISTADOCUMENTIMISS AS
    SELECT TD.PROGRESSIVO AS IDTESTA, TD.ESERCIZIO,
    TD.TIPODOC, TD.NUMERODOC, TD.BIS, TD.DATADOC,
    TD.DOCCHIUSO, TD.BLOCCATO, TD.CODCLIFOR,
    TD.NUMRIFDOC, TD.DATARIFDOC,
    TD.CODAGENTE1, TD.CODAGENTE2,
    TD.CODAGENTE3, TD.CODBANCAINCASSO,
    TD.NUMDESTDIVERSAMERCI,TD.RAGSOCDDM, 
    TD.CODPAGAMENTO,
    TD.CODLINGUA, TD.CODCAMBIO, TD.VALCAMBIO,
    TD.SCONTOFINALE, TD.CODCFFATT,
    RD.IDRIGA AS PROGRIGADOC, RD.POSIZIONE,
    RD.TIPORIGA, RD.RIGACHIUSA, RD.RIGABLOCCATA,
    RD.CODART, RD.DESCRIZIONEART,
    (CASE WHEN  RD.DATACONSEGNA IS NULL THEN TD.DATADOC ELSE  RD.DATACONSEGNA END ) AS DATACONSEGNA,
    TD.DATACONSEGNA AS T_DATACONSEGNA,
    RD.NUMLISTINO, RD.UMGEST,
    VISTAARTICOLIUMBASE.UM1,
    VISTAARTICOLIUMBASE.UM2, RD.UMPREZZO,
    RD.SCONTORIGA, RD.SCONTIESTESI, RD.CODIVA,
    RD.NUMCOLLI, RD.GENCONTROP, RD.NRRIFPARTITA,
    RD.PESONETTO, RD.PESOLORDO, RD.PESOIMBALLO,
    RD.SUPERFICIE, RD.VOLUME,RD.RIFCOMMCLI,
    RD.CAUSALEMAG, RD.NRPEZZIIMBALLO,
    RD.CODIMBALLO, RD.NOMENCLCOMBINATA,
    RD.CODDEPOSITO, RD.CODDEPOSITOCOLL,
    RD.CODDEPCOMP, RD.CODDEPCOMPCOLL,
    RD.VARIANTI, RD.ANNOTAZIONI,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.PREZZOUNITNETTO ELSE RD.PREZZOUNITNETTO/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO END ) AS PREZZOUNITNETTO,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.PREZZOUNITLORDO ELSE RD.PREZZOUNITLORDO/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO END ) AS PREZZOUNITLORDO,
    RD.PREZZOUNITNETTO AS PREZZOUNITNETTOVALUTA,
    RD.PREZZOUNITLORDO AS PREZZOUNITLORDOVALUTA,
    RD.PREZZOUNITNETTOEURO,
    RD.PREZZOUNITLORDOEURO,
    RD.UBICAZIONE,
    RD.UBICAZIONECOLL,
    RD.UBICAZIONECOMP,
    RD.UBICAZIONECOMPCOLL,
    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTDOCUMENTO * TD.SEGNO ELSE TD.TOTDOCUMENTO/TD.VALCAMBIO/TC.CAMBIOEURO * TD.SEGNO * TCAM.CAMBIOEURO END) AS TOTDOCUMENTO,
    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTIMPOSTA * TD.SEGNO ELSE TD.TOTIMPOSTA/TD.VALCAMBIO/TC.CAMBIOEURO * TD.SEGNO * TCAM.CAMBIOEURO END) AS TOTIMPOSTA,
    TD.TOTDOCUMENTOEURO * TD.SEGNO AS TOTDOCUMENTOEURO,
    TD.TOTIMPOSTAEURO * TD.SEGNO AS TOTIMPOSTAEURO,
    TD.TOTDOCUMENTO * TD.SEGNO AS TOTDOCVALUTA,
    TD.TOTIMPOSTA * TD.SEGNO AS TOTIMPOSTAVALUTA,
    RD.QTAGEST * TD.SEGNO AS QTAGEST,
    RD.QTAGESTRES * TD.SEGNO AS QTAGESTRES,
    RD.QTA1MAG * TD.SEGNO AS QTA1MAG,
    RD.QTA1MAGRES * TD.SEGNO AS QTA1MAGRES,
    RD.QTA2MAG * TD.SEGNO AS QTA2MAG,
    RD.QTA2MAGRES * TD.SEGNO AS QTA2MAGRES,
    RD.QTAPREZZO * TD.SEGNO AS QTAPREZZO,
    RD.QTAPREZZORES * TD.SEGNO AS QTAPREZZORES,
    RD.QTAGESTPRELEVATA * TD.SEGNO AS QTAGESTPRELEVATA,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTLORDORIGA * TD.SEGNO ELSE RD.TOTLORDORIGA/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO * TD.SEGNO END) AS TOTLORDORIGA,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTNETTORIGA * TD.SEGNO ELSE RD.TOTNETTORIGA/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO * TD.SEGNO END) AS TOTNETTORIGA,
    RD.TOTLORDORIGA * TD.SEGNO AS TOTLORDORIGAVALUTA,
    RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGAVALUTA,
    RD.TOTLORDORIGAEURO * TD.SEGNO AS TOTLORDORIGAEURO,
    RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO,
    ANAGRAFICACF.DSCCONTO1,
    ANAGRAFICARISERVATICF.CODCATEGORIA AS CODCATEGORIACF,RCF.STATOBOLLE,RCF.STATOFATTURE,
    ANAGRAFICACF.CODNAZIONE,
    (CASE WHEN destdiv.ZonaspeD > '' THEN destdiv.zonasped ELSE anagraficacf.Zonasped END) AS ZonaSped, 
    ANAGRAFICARISERVATICF.CODGRUPPOPREZZIPART,    
    ANAGRAFICARISERVATICF.CODSETTORE,
    ANAGRAFICARISERVATICF.CODZONA,
    RD.RIFRELAZIONECF,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTNETTORIGARES * TD.SEGNO ELSE RD.TOTNETTORIGARES/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO * TD.SEGNO END) AS TOTNETTORIGARES,
    RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES,
    RD.IDTESTARP,
    RD.IDRIGARP,
    (SELECT ARROTNUMCOLLI FROM PARAMETRIDOC  WHERE PARAMETRIDOC.CODICE = TD.TIPODOC) AS ARROTNUMCOLLI ,
    TabGGConsegna.PROGRESSIVO AS PROGGGCONS,
    (CASE WHEN TabGGConsegna.GGRitCons IS NULL THEN 0 ELSE TabGGConsegna.GGRitCons END) AS GGRitCons ,
    TabGGConsegna.Lun_NonCons,
    TabGGConsegna.LunDA_AM,
    TabGGConsegna.LunA_AM,
    TabGGConsegna.LunDA_PM,
    TabGGConsegna.LunA_PM,
    TabGGConsegna.Mar_NonCons,
    TabGGConsegna.MarDA_AM,
    TabGGConsegna.MarA_AM,
    TabGGConsegna.MarDA_PM,
    TabGGConsegna.MarA_PM,
    TabGGConsegna.Mer_NonCons,
    TabGGConsegna.MerDA_AM,
    TabGGConsegna.MerA_AM,
    TabGGConsegna.MerDA_PM,
    TabGGConsegna.MerA_PM,
    TabGGConsegna.Gio_NonCons,
    TabGGConsegna.GioDA_AM,
    TabGGConsegna.GioA_AM,
    TabGGConsegna.GioDA_PM,
    TabGGConsegna.GioA_PM,
    TabGGConsegna.Ven_NonCons,
    TabGGConsegna.VenDA_AM,
    TabGGConsegna.VenA_AM,
    TabGGConsegna.VenDA_PM,
    TabGGConsegna.VenA_PM,
    TabGGConsegna.Sab_NonCons,
    TabGGConsegna.SabDA_AM,
    TabGGConsegna.SabA_AM,
    TabGGConsegna.SabDA_PM,
    TabGGConsegna.SabA_PM,
    TabGGConsegna.Dom_NonCons,
    TabGGConsegna.DomDA_AM,
    TabGGConsegna.DomA_AM,
    TabGGConsegna.DomDA_PM,
    TabGGConsegna.DomA_PM,
    ANAGRAFICAARTICOLI.Gruppo,
    ANAGRAFICAARTICOLI.Categoria,
    ANAGRAFICAARTICOLI.CodCategoriaStat,
    ANAGRAFICAARTICOLI.VarEsplicite,
    TP_EXTRAMAG.CODFamigliaPOS,
    TP_EXTRAMAG.CODRepartoPOS
 

FROM
    ((((((((TESTEDOCUMENTI TD INNER JOIN  RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA)
    INNER JOIN ANAGRAFICAARTICOLI ON RD.CODART = ANAGRAFICAARTICOLI.CODICE)
    INNER JOIN TABCAMBI AS TC ON TD.CODCAMBIO=TC.CODICE)
    INNER JOIN ANAGRAFICACF ON TD.CODCLIFOR = ANAGRAFICACF.CODCONTO)
    INNER JOIN ANAGRAFICARISERVATICF ON ANAGRAFICACF.CODCONTO = ANAGRAFICARISERVATICF.CODCONTO)
    LEFT OUTER JOIN DESTINAZIONIDIVERSE AS destdiv ON TD.NUMDESTDIVERSAMERCI = destdiv.CODICE AND TD.CODCLIFOR = destdiv.CODCONTO)
    LEFT OUTER JOIN TabGGConsegna
    ON TabGGConsegna.CODCONTO = TD.CODCLIFOR AND TabGGConsegna.NUMDDM = TD.NUMDESTDIVERSAMERCI)    
    LEFT OUTER JOIN TP_EXTRAMAG ON RD.CODART = TP_EXTRAMAG.CODART)
    LEFT OUTER JOIN ANAGRAFICARISERVATICF RCF ON ANAGRAFICACF.CODCONTO = RCF.CODCONTO AND RCF.ESERCIZIO = (SELECT USERS.ESERCIZIOATTIVO FROM TABUTENTI AS USERS WHERE USERS.USERDB=USER_NAME())
    LEFT OUTER JOIN VISTAARTICOLIUMBASE ON VISTAARTICOLIUMBASE.codice = RD.CODART,
    TABCAMBI TCAM, TABUTENTI

WHERE (TCAM.CODICE = 0)  AND USERDB = USER_NAME() AND
      (ANAGRAFICARISERVATICF.ESERCIZIO = TD.ESERCIZIO)
      AND ((TD.CODCLIFOR=TABUTENTI.CODCLIFOR) OR (TABUTENTI.CODCLIFOR=''))
      AND (TD.DOCCHIUSO=0 AND TD.BLOCCATO=0)
      AND (RD.TIPORIGA <> 'D' AND RD.CODART <> '' AND RD.QTAGESTRES > 0)


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTADOCUMENTIMISS] TO [Metodo98]
    AS [dbo];

