

CREATE VIEW [dbo].[TP_VISTAORDINEFORNITORE_SEL]
AS

SELECT  
    TLRRD.CODART,
    ANAGA.DESCRIZIONE AS DESCARTICOLO,
    ANAGA.DESCRIZIONE AS DESCRIZIONEART
FROM    
    (SELECT DISTINCT 
        CODART 
     FROM 
        dbo.TABLOTTIRIORDINO
     WHERE
        ((TABLOTTIRIORDINO.CODART <> '' AND TABLOTTIRIORDINO.CODART IS NOT NULL)) AND 
        ((TABLOTTIRIORDINO.CODFOR <> '' AND TABLOTTIRIORDINO.CODFOR IS NOT NULL)) AND
        ((TABLOTTIRIORDINO.TP_FORNFATTURAZIONE <> '' AND TABLOTTIRIORDINO.TP_FORNFATTURAZIONE IS NOT NULL)) AND
        ((TABLOTTIRIORDINO.TP_CODDEP <> '' AND TABLOTTIRIORDINO.TP_CODDEP IS NOT NULL))) TLRRD,
    dbo.TP_EXTRAMAG TXMAG,
    dbo.ANAGRAFICAARTICOLI ANAGA
WHERE
    TXMAG.CODART = TLRRD.CODART AND 
    TXMAG.CONSIDACQ = 1 AND
    ANAGA.CODICE = TXMAG.CODART AND 
    ANAGA.ARTTIPOLOGIA = 0


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAORDINEFORNITORE_SEL] TO [Metodo98]
    AS [dbo];

