

CREATE VIEW TP_VISTAGIACLOTTI AS 
  
    SELECT CODART , CODDEPOSITO ,
                  (CASE WHEN CODUBICAZIONE IS NULL THEN '' ELSE CODUBICAZIONE END )  AS CODUBICAZIONE ,
                  (CASE WHEN NRIFPARTITA IS NULL THEN '' ELSE NRIFPARTITA END )  AS NRIFPARTITA ,
                  (SUM(Carico)+SUM(ResoDaScarico)-SUM(Scarico)-SUM(ResoDaCarico)) AS GIAC FROM VISTAGIACENZEINIZDEPOSITI
  
    GROUP BY  CODART,CODDEPOSITO,
                        CODUBICAZIONE,NRIFPARTITA



GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAGIACLOTTI] TO [Metodo98]
    AS [dbo];

