
CREATE VIEW TP_VISTASCTLOGSCATCTR
AS
SELECT      TP_TESTE_SCONTI_LOGISTICICTR.DADATA, TP_TESTE_SCONTI_LOGISTICICTR.ADATA, 
                      TP_TESTE_SCONTI_LOGISTICICTR.CODCLIFOR, TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO,TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIASCONTO,
                      TP_TESTE_SCONTI_LOGISTICICTR.TIPO_TOTALE,TP_TESTE_SCONTI_LOGISTICICTR.RifContratto,
                      ANAGRAFICAARTICOLI.CODICE, 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIASTATCTR.UM, TP_RIGHE_SCONTI_LOGISTICI_CATEGORIASTATCTR.QTAMIN, 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIASTATCTR.SCONTO
FROM         TP_TESTE_SCONTI_LOGISTICICTR INNER JOIN
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIASTATCTR ON 
                      TP_TESTE_SCONTI_LOGISTICICTR.PROGRESSIVO = TP_RIGHE_SCONTI_LOGISTICI_CATEGORIASTATCTR.RIFPROGRESSIVO INNER JOIN
                      ANAGRAFICAARTICOLI ON 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIASTATCTR.CATEGORIASTAT = ANAGRAFICAARTICOLI.CODCATEGORIASTAT
WHERE     (TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO = 2) AND (ANAGRAFICAARTICOLI.CODCATEGORIASTAT <> 0)


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASCTLOGSCATCTR] TO [Metodo98]
    AS [dbo];

