

CREATE VIEW  TP_VISTAPROMOZIONI 
AS SELECT 	TP_PROMOZIONI_TESTE.Progressivo as NumeroPromozione,
                           TP_PROMOZIONI_TESTE.Descrizione as DescPromo, 
                           TP_PROMOZIONI_TESTE.NumeroCampagna,		
                           (SELECT DESCRIZIONE FROM TP_CAMPAGNE WHERE NUMEROCAMPAGNA = TP_PROMOZIONI_TESTE.NumeroCampagna) AS DescCampagna,
                           TP_PROMOZIONI_TESTE.Tipo,
                           TP_PROMOZIONI_TESTE.Data_inizio,
		TP_PROMOZIONI_TESTE.Data_fine,                
                           TP_PROMOZIONI_TESTE.UM_M,
                           TP_PROMOZIONI_TESTE.Qta_M,
                           TP_PROMOZIONI_TESTE.Prezzo_M,
                           TP_PROMOZIONI_TESTE.Prezzo_M_Euro,
                           TP_PROMOZIONI_TESTE.ScontoSost,
		TP_PROMOZIONI_TESTE.ScontoAgg,
		TP_PROMOZIONI_TESTE.ScontoFinale,
		TP_PROMOZIONI_TESTE.piudicui,
		TP_PROMOZIONI_TESTE.CodPag,
		TP_PROMOZIONI_TESTE.Note,
		TP_PROMOZIONI_TESTE.CLIFOR,
		TP_PROMOZIONI_TESTE.QtaBudget,
		TP_PROMOZIONI_TESTE.ValoreBudget,
		TP_PROMOZIONI_TESTE.DataConsuntiv,
		TP_PROMOZIONI_TESTE.QtaConsuntiv,
		TP_PROMOZIONI_TESTE.ValoreConsuntiv,		
                           TP_PROMOZIONI_DETT.Codice           as Codice_DETT,
                           (SELECT DESCRIZIONE FROM ANAGRAFICAARTICOLI WHERE CODICE=TP_PROMOZIONI_DETT.Codice) as DescArt,
                           TP_PROMOZIONI_DETT.UM_M           as UM_M_DETT,
		TP_PROMOZIONI_DETT.Qta_Minima   as Qta_Minima_DETT,
		TP_PROMOZIONI_DETT.UM_O,
		TP_PROMOZIONI_DETT.Qta_Omaggio,
		TP_PROMOZIONI_DETT.Abbuono,
		TP_PROMOZIONI_DETT.Prezzo_Sost,
		TP_PROMOZIONI_DETT.Prezzo_Sost_Euro,
		TP_PROMOZIONI_DETT.Sconto_Sost_Esteso,
		TP_PROMOZIONI_DETT.Sconto_Sost,
		TP_PROMOZIONI_DETT.Sconto_Agg_Esteso,
		TP_PROMOZIONI_DETT.Codice_Art_Oma,
                           (SELECT DESCRIZIONE FROM ANAGRAFICAARTICOLI WHERE CODICE=TP_PROMOZIONI_DETT.Codice_Art_Oma) as DescArtOma,		
                           TP_PROMOZIONI_DETT.Qta_Art_Oma,
		TP_PROMOZIONI_DETT.UM_A_O,
		TP_PROMOZIONI_DETT.Note                  as Note_DETT,
		TP_PROMOZIONI_DETT.QtaBudget         as QtaBudget_DETT,
		TP_PROMOZIONI_DETT.ValoreBudget     as ValoreBudget_DETT,
		TP_PROMOZIONI_DETT.DataConsuntiv   as DataConsuntiv_DETT,
		TP_PROMOZIONI_DETT.QtaConsuntiv     as QtaConsuntiv_DETT,
		TP_PROMOZIONI_DETT.ValoreConsuntiv as ValoreConsuntiv_DETT,
                           ''                                                                   as Codice_COND,
                           ''                                                                   as DescArt_COND,		 		
                           ''                                                                   as UM_M_COND,
		0                                                                   as Qta_Minima_COND,
		''                                                                    as Note_COND,
		0                                                                   as QtaBudget_COND,
		0                                                                   as ValoreBudget_COND,
		Null                                                               as DataConsuntiv_COND,
		0                                                                   as QtaConsuntiv_COND,
		0                                                                   as ValoreConsuntiv_COND                

FROM   TP_PROMOZIONI_TESTE  INNER JOIN TP_PROMOZIONI_DETT
ON     TP_PROMOZIONI_TESTE.Progressivo = TP_PROMOZIONI_DETT.RifProgressivo
WHERE TP_PROMOZIONI_TESTE.Attiv_Disat=0
UNION
SELECT            TP_PROMOZIONI_TESTE.Progressivo as NumeroPromozione,
                          TP_PROMOZIONI_TESTE.Descrizione as DescPromo, 
                          TP_PROMOZIONI_TESTE.NumeroCampagna,		
                          (SELECT DESCRIZIONE FROM TP_CAMPAGNE WHERE NUMEROCAMPAGNA = TP_PROMOZIONI_TESTE.NumeroCampagna) AS DescCampagna,
                          TP_PROMOZIONI_TESTE.Tipo,
                          TP_PROMOZIONI_TESTE.Data_inizio,
	             TP_PROMOZIONI_TESTE.Data_fine,                
                          TP_PROMOZIONI_TESTE.UM_M,
                          TP_PROMOZIONI_TESTE.Qta_M,
                          TP_PROMOZIONI_TESTE.Prezzo_M,
                          TP_PROMOZIONI_TESTE.Prezzo_M_Euro,
                          TP_PROMOZIONI_TESTE.ScontoSost,
	             TP_PROMOZIONI_TESTE.ScontoAgg,
	             TP_PROMOZIONI_TESTE.ScontoFinale,
	             TP_PROMOZIONI_TESTE.piudicui,
	             TP_PROMOZIONI_TESTE.CodPag,
	             TP_PROMOZIONI_TESTE.Note,
	             TP_PROMOZIONI_TESTE.CLIFOR,
		TP_PROMOZIONI_TESTE.QtaBudget,
		TP_PROMOZIONI_TESTE.ValoreBudget,
		TP_PROMOZIONI_TESTE.DataConsuntiv,
		TP_PROMOZIONI_TESTE.QtaConsuntiv,
		TP_PROMOZIONI_TESTE.ValoreConsuntiv,
                           ''                                                                  as Codice_DETT,
	              ''                                                                  as DescArt,
		 ''                                                                  as UM_M_DETT,
		 0                                                                 as Qta_Minima_DETT,
		 ''                                                                  as UM_O,
		0                                                                   as Qta_Omaggio,
		0                                                                   as Abbuono,
		0                                                                   as Prezzo_Sost,
		0                                                                   as Prezzo_Sost_Euro,
		''                                                                    as Sconto_Sost_Esteso,
		0                                                                   as Sconto_Sost,
		''                                                                    as Sconto_Agg_Esteso,
		''                                                                    as Codice_Art_Oma,
		''                                                                    as DescArtOma,		
		0                                                                   as Qta_Art_Oma,
		''                                                                    as UM_A_O,
                           ''                                                                    as Note_DETT,
		0                                                                    as QtaBudget_DETT,
		0                                                                    as ValoreBudget_DETT,
		Null                                                                as DataConsuntiv_DETT,
		0                                                                    as QtaConsuntiv_DETT,
		0                                                                    as ValoreConsuntiv_DETT,
	             TP_PROMOZIONI_COND.Codice                as Codice_COND,
		(SELECT DESCRIZIONE FROM ANAGRAFICAARTICOLI WHERE CODICE=TP_PROMOZIONI_COND.Codice) as DescArt_COND,		 		
		TP_PROMOZIONI_COND.UM_M                as UM_M_COND,
		TP_PROMOZIONI_COND.Qta_Minima        as Qta_Minima_COND,
		TP_PROMOZIONI_COND.Note                   as Note_COND,
		TP_PROMOZIONI_COND.QtaBudget         as QtaBudget_COND,
		TP_PROMOZIONI_COND.ValoreBudget     as ValoreBudget_COND,
		TP_PROMOZIONI_COND.DataConsuntiv   as DataConsuntiv_COND,
		TP_PROMOZIONI_COND.QtaConsuntiv     as QtaConsuntiv_COND,
		TP_PROMOZIONI_COND.ValoreConsuntiv as ValoreConsuntiv_COND 
FROM   TP_PROMOZIONI_TESTE  INNER JOIN TP_PROMOZIONI_COND 
ON TP_PROMOZIONI_TESTE.Progressivo=TP_PROMOZIONI_COND.RifProgressivo
WHERE TP_PROMOZIONI_TESTE.Attiv_Disat=0



GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAPROMOZIONI] TO [Metodo98]
    AS [dbo];

