

CREATE VIEW TP_VISTASCTLOGGPMCTR
AS
SELECT     TP_TESTE_SCONTI_LOGISTICICTR.DADATA, TP_TESTE_SCONTI_LOGISTICICTR.ADATA, 
                      TP_TESTE_SCONTI_LOGISTICICTR.CODCLIFOR, TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO, TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIASCONTO,
                      TP_TESTE_SCONTI_LOGISTICICTR.TIPO_TOTALE,TP_TESTE_SCONTI_LOGISTICICTR.RifContratto,
                      ANAGRAFICAARTICOLICOMM.CODICEART, TP_RIGHE_SCONTI_LOGISTICI_PREZZIMAGCTR.UM, 
                      TP_RIGHE_SCONTI_LOGISTICI_PREZZIMAGCTR.QTAMIN, TP_RIGHE_SCONTI_LOGISTICI_PREZZIMAGCTR.SCONTO
FROM         TP_TESTE_SCONTI_LOGISTICICTR INNER JOIN
                      TP_RIGHE_SCONTI_LOGISTICI_PREZZIMAGCTR ON 
                      TP_TESTE_SCONTI_LOGISTICICTR.PROGRESSIVO = TP_RIGHE_SCONTI_LOGISTICI_PREZZIMAGCTR.RIFPROGRESSIVO INNER JOIN
                      ANAGRAFICAARTICOLICOMM ON 
                      TP_RIGHE_SCONTI_LOGISTICI_PREZZIMAGCTR.GRPPREZZIPART = ANAGRAFICAARTICOLICOMM.GRUPPOPRZPART AND 
                      ANAGRAFICAARTICOLICOMM.ESERCIZIO = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME())
WHERE     (TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO = 3) AND (ANAGRAFICAARTICOLICOMM.GRUPPOPRZPART <> 0)


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASCTLOGGPMCTR] TO [Metodo98]
    AS [dbo];

