
CREATE VIEW TP_VISTALOTTI AS
    SELECT  TOP 100 PERCENT ANAGRAFICALOTTI.CODARTICOLO ,  ANAGRAFICALOTTI.CODLOTTO  ,  ANAGRCARLOTTI.VALORE ,
    TABCARATTLOTTI.*,
    (CASE WHEN TABCARATTLOTTI.PRIORITA IS NULL THEN 10000  WHEN TABCARATTLOTTI.PRIORITA = 0 THEN 9999  ELSE TABCARATTLOTTI.PRIORITA END) AS PRIORITARIGA 
    FROM 
         (((ANAGRAFICALOTTI INNER JOIN ANAGRAFICAARTICOLI ON ANAGRAFICALOTTI.CODARTICOLO=ANAGRAFICAARTICOLI.CODICE)
           LEFT OUTER JOIN  
           ANAGRCARLOTTI ON ANAGRAFICALOTTI.CODARTICOLO=ANAGRCARLOTTI.CODARTICOLO AND ANAGRAFICALOTTI.CODLOTTO=ANAGRCARLOTTI.CODLOTTO)
           LEFT OUTER JOIN 
           TABCARATTLOTTI ON ANAGRAFICAARTICOLI.CATEGORIA=TABCARATTLOTTI.CODICE AND ANAGRCARLOTTI.NRRIGA=TABCARATTLOTTI.NRRIGA)    
   WHERE ANAGRAFICALOTTI.CODLOTTO IN
         (SELECT NRIFPARTITA FROM TP_VISTAGIACLOTTI WHERE  GIAC  > 0  AND TP_VISTAGIACLOTTI.CODART=ANAGRAFICALOTTI.CODARTICOLO)
        ORDER BY ANAGRAFICALOTTI.CODARTICOLO,PRIORITARIGA,TABCARATTLOTTI.NRRIGA


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTALOTTI] TO [Metodo98]
    AS [dbo];

