

CREATE VIEW TP_VISTA_RELPROMOCLIFOR
AS
SELECT     TP_RELPROMOCLIFOR.CODCLIFOR, TP_RELPROMOCLIFOR.PROMOZIONE, TP_RELPROMOCLIFOR.CONTRATTO AS PROG_CONTRATTO, 
                   TP_RELPROMOCLIFOR.DESTDIVMERCI, TESTE_CONTRATTI.ESERCIZIO, TESTE_CONTRATTI.DATAINIZIOCONTRATTO, 
                   TESTE_CONTRATTI.DATAFINECONTRATTO, TESTE_CONTRATTI.NUMEROCONTRATTO
FROM         TP_RELPROMOCLIFOR LEFT OUTER JOIN
                   TESTE_CONTRATTI ON TP_RELPROMOCLIFOR.CONTRATTO =  TESTE_CONTRATTI.PROGRESSIVO




GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTA_RELPROMOCLIFOR] TO [Metodo98]
    AS [dbo];

