

CREATE VIEW [dbo].[TP_VISTAORDINEFORNITOREPRENOTATI_TO]
AS

SELECT
    TESTEDOCUMENTI.RifTransferOrder,
    TP_VISTAARTDEPFATT.depositario As CodFor,
    TP_VISTAARTDEPFATT.Magazzino As TP_CodDep,
    RIGHEDOCUMENTI.idtesta,
    RIGHEDOCUMENTI.idriga,
    RIGHEDOCUMENTI.DESCRIZIONEART,
    RIGHEDOCUMENTI.CODART AS CODICE,
    RIGHEDOCUMENTI.CODART,
    RIGHEDOCUMENTI.UMGEST,
    RIGHEDOCUMENTI.UMPREZZO,
    RIGHEDOCUMENTI.QTAGEST,
    RIGHEDOCUMENTI.QTAGESTRES,
    RIGHEDOCUMENTI.DATACONSEGNA,
    TESTEDOCUMENTI.CODCLIFOR,
    TESTEDOCUMENTI.Tipodoc,
    TESTEDOCUMENTI.numerodoc,
    TESTEDOCUMENTI.datadoc,
    TP_EXTRARIGHEDOC.Composizioneestemporaneo,
    ANAGRAFICAARTICOLI.GRUPPO,
    ANAGRAFICAARTICOLI.CATEGORIA,
    ANAGRAFICAARTICOLI.CODCATEGORIASTAT,
    ANAGRAFICAARTICOLICOMM.GRUPPOPRZPART,
    TP_EXTRAMAG.CODFAMIGLIAPOS,
    TP_EXTRAMAG.CODREPARTOPOS,
    TP_LIVELLIARTICOLI.CODLIVELLOINTERNO
FROM RIGHEDOCUMENTI 
    INNER JOIN TP_PRENOTATI ON RIGHEDOCUMENTI.IDTESTA=TP_PRENOTATI.IDTESTAP AND RIGHEDOCUMENTI.IDRIGA=TP_PRENOTATI.IDRIGAP 
    INNER JOIN TP_EXTRARIGHEDOC ON RIGHEDOCUMENTI.IDTESTA=TP_EXTRARIGHEDOC.IDTESTA AND RIGHEDOCUMENTI.IDRIGA=TP_EXTRARIGHEDOC.IDRIGA 
    INNER JOIN TP_VISTAARTDEPFATT ON RIGHEDOCUMENTI.CODART=TP_VISTAARTDEPFATT.CODART AND RIGHEDOCUMENTI.CODDEPOSITO=TP_VISTAARTDEPFATT.MAGAZZINO 
    INNER JOIN TESTEDOCUMENTI ON RIGHEDOCUMENTI.IDTESTA=TESTEDOCUMENTI.PROGRESSIVO
    INNER JOIN ANAGRAFICAARTICOLI ON ANAGRAFICAARTICOLI.CODICE=RIGHEDOCUMENTI.CODART
    INNER JOIN ANAGRAFICAARTICOLICOMM ON ANAGRAFICAARTICOLICOMM.CODICEART=RIGHEDOCUMENTI.CODART AND ANAGRAFICAARTICOLICOMM.ESERCIZIO = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME())
    INNER JOIN TP_EXTRAMAG ON TP_EXTRAMAG.CODART=RIGHEDOCUMENTI.CODART
    LEFT JOIN TP_LIVELLIARTICOLI ON TP_LIVELLIARTICOLI.CODICE=RIGHEDOCUMENTI.CODART
    LEFT JOIN Tp_DocumentiPrelevati ON Tp_DocumentiPrelevati.Progressivo = RIGHEDOCUMENTI.IDTESTA AND Tp_DocumentiPrelevati.IdRiga = RIGHEDOCUMENTI.IDRIGA  
WHERE 
    TP_PRENOTATI.STATO='A' AND 
    TESTEDOCUMENTI.RifTransferOrder <> 0 AND 
    RIGHEDOCUMENTI.TIPODOC NOT IN(SELECT TP_ASSOCIAZIONI_DOC.Cod_Doc FROM TP_ASSOCIAZIONI_DOC WHERE TP_ASSOCIAZIONI_DOC.Tipo IN(5,6)) AND
    TP_EXTRAMAG.ConsidAcq = 1 AND 
    (((Tp_DocumentiPrelevati.QTAPRP - Tp_DocumentiPrelevati.QTAORD) > 0) OR Tp_DocumentiPrelevati.Progressivo IS NULL)



GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAORDINEFORNITOREPRENOTATI_TO] TO [Metodo98]
    AS [dbo];

