

CREATE VIEW [dbo].[TPVISTATABLISTINI]
AS
    SELECT     LISTINIARTICOLI.CODART, ANAGRAFICAARTICOLI.DESCRIZIONE, LISTINIARTICOLI.NRLISTINO, 
                          TABLISTINI.DESCRIZIONE AS DSCLISTINO, LISTINIARTICOLI.UM, TABUNITAMISURA.DESCRIZIONE AS DSCUM, 
                          TABLISTINI.CODCAMBIO, TABCAMBI.DESCRIZIONE AS DSCCAMBIO, LISTINIARTICOLI.PREZZOEURO, LISTINIARTICOLI.PREZZO, 
                          LISTINIARTICOLI.DATAVALIDITA, TABCAMBI.NDECIMALIUNITARIO,LISTINIARTICOLI.TP_Sconti
    FROM         LISTINIARTICOLI INNER JOIN
                          ANAGRAFICAARTICOLI ON LISTINIARTICOLI.CODART = ANAGRAFICAARTICOLI.CODICE INNER JOIN
                          TABLISTINI ON LISTINIARTICOLI.NRLISTINO = TABLISTINI.NRLISTINO INNER JOIN
                          TABUNITAMISURA ON LISTINIARTICOLI.UM = TABUNITAMISURA.CODICE INNER JOIN
                          TABCAMBI ON TABLISTINI.CODCAMBIO = TABCAMBI.CODICE
    WHERE     (TABLISTINI.TP_Tipo = 'V')



GO
GRANT SELECT
    ON OBJECT::[dbo].[TPVISTATABLISTINI] TO [Metodo98]
    AS [dbo];

