
CREATE VIEW View_Oxatis_Users
AS
SELECT
    /*
	in caso di personalizzazioni non modificare questa vista standard
	creare una vista View_Oxatis_Users_Pers
	*/
    A.TIPOCONTO
  , A.CODCONTO
  , A.DSCCONTO1
  , A.DSCCONTO2
  , A.CODMASTRO
  , A.INDIRIZZO
  , A.CAP
  , A.LOCALITA
  , A.PROVINCIA
  , A.TELEFONO
  , A.FAX
  , A.TELEX
  , A.CODFISCALE
  , A.PARTITAIVA
  , A.CODNAZIONE
  , A.CODICEISO
  , A.CODLINGUA
  , A.TIPOPROFESSIONISTA
  , A.LUOGONASCITA
  , A.DATANASCITA
  , A.TIPODOCRTACC
  , A.VERSPRESSO
  , A.NOTE
  , A.UTENTEMODIFICA
  , A.DATAMODIFICA
  , A.INDIRIZZOINTERNET
  , A.INDIRIZZORITACC
  , A.LOCALITARITACC
  , A.PROVINCIARITACC
  , A.CAPRITACC
  , A.PARTITAIVARITACC
  , A.CODFISCALERITACC
  , A.ZonaSped
  , A.TipoClienteBudget
  , A.ConsideraBudget
  , A.CODREGIONE
  , A.PERCORSODOCUMENTI
  , A.FLGBLACKLIST
  , A.FLGPERSFISICA
  , A.DATANASCITAPERSFIS
  , A.COMNASCITAPERSFIS
  , A.PROVNASCITAPERSFIS
  , A.CODSTATOESTERO
  , A.STATOPROVCONTEA
  , A.INDIRIZZOESTERO
  , A.COGNOMEPERSFIS
  , A.NOMEPERSFIS
  , A.FLGELENCOCF
  , A.FLGSISTRI
  , A.CODDEST_EDI
  , A.FLGDOGANA
  , A.FLGQUALITY
  , A.StatoIndicatore
  , A.CODDESTINATARIOPA
  , A.CAUSALEPAGAMENTOPA
  , A.TIPOCASSAPA
  , A.RIFAMMINISTRAZIONEPA
  , A.SESSOPERSFIS
  , A.CODIDENTIVAESTERO
  , A.FLGPUBBLICAAMM
FROM
    ANAGRAFICACF AS A
WHERE
    A.TIPOCONTO = 'C'
    AND RTrim (IsNull (A.TELEX, '')) <> '';
GO
GRANT SELECT
    ON OBJECT::[dbo].[View_Oxatis_Users] TO [Metodo98]
    AS [dbo];

