
CREATE VIEW [dbo].[VISTA_TESTECONTABILITA_IMPORTATI]
AS
SELECT        i.CODICE, i.DESCRIZIONE, tc.ESERCIZIO, tc.DATARIF, tc.DATAREG, tc.NRRIFER, tc.CAUSALE, cc.DESCRIZIONE AS desc_cc, tc.DESCRIZIONE AS Dsc_Tc, tc.TOTDOCEURO, tc.PROGRESSIVO
FROM            dbo.CAUSALICONTABILI AS cc INNER JOIN
                         dbo.TESTECONTABILITA AS tc ON cc.CODICECAUSALE = tc.CAUSALE RIGHT OUTER JOIN
                         dbo.ADA_ANAGRAFICAIMPORTAZIONI AS i LEFT OUTER JOIN
                         dbo.ADA_IMPORTAZIONI_MOVCON AS mc ON i.CODICE = mc.CODICE_IMPORTAZIONE ON tc.PROGRESSIVO = mc.PROGRESSIVO
 

GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTA_TESTECONTABILITA_IMPORTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTA_TESTECONTABILITA_IMPORTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTA_TESTECONTABILITA_IMPORTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_TESTECONTABILITA_IMPORTATI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTA_TESTECONTABILITA_IMPORTATI] TO [Metodo98]
    AS [dbo];

