create view VISTAEFFETTIPIANIFICAZIONE_FASE1 as 
	select
		IDSESSIONE,FASE,TIPORECORD,
		isnull(CODART,'') as CODART,
		isnull(CODCLIFOR,'') as CODCLIFOR,
		QUANTITA
	from 
		TEMPEFFETTIPIANIFICAZIONE
	where 
		FASE = 1

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAEFFETTIPIANIFICAZIONE_FASE1] TO [Metodo98]
    AS [dbo];

