

CREATE VIEW VISTADOCUMENTIMARGINERES AS
SELECT TD.PROGRESSIVO AS IDTESTA, TD.ESERCIZIO,TD.DATARIFDOC,
    TD.TIPODOC, TD.NUMERODOC, TD.BIS, TD.DATADOC,
    TD.DOCCHIUSO, TD.BLOCCATO, TD.CODCLIFOR,
    TD.NUMRIFDOC, TD.CODAGENTE1, TD.CODAGENTE2,
    TD.CODAGENTE3, TD.CODBANCAINCASSO,
    TD.NUMDESTDIVERSAMERCI, TD.CODPAGAMENTO,
    TD.CODLINGUA, TD.CODCAMBIO, TD.VALCAMBIO,
    TD.SCONTOFINALE, TD.CODCFFATT,
    TD.PRCPROVVAG1, TD.PRCPROVVFINALEAG1,
    TD.PRCPROVVAG2, TD.PRCPROVVFINALEAG2,
    TD.PRCPROVVAG3, TD.PRCPROVVFINALEAG3,
    TD.ANNOTAZIONI AS ANNOTAZIONIPIEDE,
    PARAMETRIDOC.TIPO AS TIPOPAR,
    RD.IDRIGA AS PROGRIGADOC, RD.POSIZIONE,
    RD.TIPORIGA, RD.RIGACHIUSA, RD.RIGABLOCCATA,
    RD.CODART, RD.DESCRIZIONEART,
    RD.DATACONSEGNA, RD.NUMLISTINO, RD.UMGEST,
    VISTAARTICOLIUMBASE.UM1,
    VISTAARTICOLIUMBASE.UM2, RD.UMPREZZO,
    RD.SCONTORIGA, RD.SCONTIESTESI,
    RD.CODIVA, RD.PROVVAG1, RD.PROVVAG2,
    RD.PROVVAG3, RD.NUMCOLLI, RD.GENCONTROP,
    RD.NRRIFPARTITA, RD.PESONETTO, RD.PESOLORDO,
    RD.PESOIMBALLO, RD.SUPERFICIE, RD.VOLUME,
    RD.NOMECOMMESSAPROD, RD.VERSIONEDIBA,
    RD.CAUSALEMAG, RD.NRPEZZIIMBALLO,
    RD.CODIMBALLO, RD.NOMENCLCOMBINATA,
    RD.CONTOCDC, RD.CONTOCDCMOVCOLL,
    RD.CODDEPOSITO, RD.CODDEPOSITOCOLL,
    RD.CODDEPCOMP, RD.CODDEPCOMPCOLL,
    RD.VARIANTI, RD.ANNOTAZIONI,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.PREZZOUNITNETTO ELSE RD.PREZZOUNITNETTO/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO END ) AS PREZZOUNITNETTO,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.PREZZOUNITLORDO ELSE RD.PREZZOUNITLORDO/TD.VALCAMBIO/TC.CAMBIOEURO * TCAM.CAMBIOEURO END ) AS PREZZOUNITLORDO,
    RD.PREZZOUNITNETTO AS PREZZOUNITNETTOVALUTA,
    RD.PREZZOUNITLORDO AS PREZZOUNITLORDOVALUTA,
    RD.PREZZOUNITNETTOEURO,
    RD.PREZZOUNITLORDOEURO,
    RD.UBICAZIONE AS UBICAZIONE,
    RD.UBICAZIONECOLL AS UBICAZIONECOLL,
    (case when TD.CODCAMBIO=0 then TD.TOTPROVVAG1RES*TD.SEGNO else TD.TOTPROVVAG1RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO end) as TOTPROVVFINALEAG1,
    (case when TD.CODCAMBIO=0 then TD.TOTPROVVAG2RES*TD.SEGNO else TD.TOTPROVVAG2RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO end) as TOTPROVVFINALEAG2,
    (case when TD.CODCAMBIO=0 then TD.TOTPROVVAG3RES*TD.SEGNO else TD.TOTPROVVAG3RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO end) as TOTPROVVFINALEAG3,
    TD.TOTPROVVAG1RES*TD.SEGNO as TOTPROVVFINALEAG1VALUTA,
    TD.TOTPROVVAG2RES*TD.SEGNO as TOTPROVVFINALEAG2VALUTA,
    TD.TOTPROVVAG3RES*TD.SEGNO as TOTPROVVFINALEAG3VALUTA,
    TD.TOTPROVVAGEURO1RES*TD.SEGNO as TOTPROVVFINALEAG1EURO,
    TD.TOTPROVVAGEURO2RES*TD.SEGNO as TOTPROVVFINALEAG2EURO,
    TD.TOTPROVVAGEURO3RES*TD.SEGNO as TOTPROVVFINALEAG3EURO,
    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTDOCUMENTORES*TD.SEGNO ELSE TD.TOTDOCUMENTORES/TD.VALCAMBIO/TC.CAMBIOEURO*TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTDOCUMENTO,
    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTIMPOSTARES*TD.SEGNO ELSE TD.TOTIMPOSTARES/TD.VALCAMBIO/TC.CAMBIOEURO*TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTIMPOSTA,
    TD.TOTDOCUMENTOEURORES * TD.SEGNO AS TOTDOCUMENTOEURO,
    TD.TOTIMPOSTAEURORES * TD.SEGNO AS TOTIMPOSTAEURO,
    TD.TOTDOCUMENTORES * TD.SEGNO AS TOTDOCVALUTA,
    TD.TOTIMPOSTARES * TD.SEGNO AS TOTIMPOSTAVALUTA,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTAGEST*TD.SEGNO END) as QTAGEST,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTAGESTRES*TD.SEGNO END) as QTAGESTRES,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTA1MAG*TD.SEGNO END) as QTA1MAG,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTA1MAGRES*TD.SEGNO END) as QTA1MAGRES,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTA2MAG*TD.SEGNO END) as QTA2MAG,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTA2MAGRES*TD.SEGNO END) as QTA2MAGRES,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTAPREZZO*TD.SEGNO END) as QTAPREZZO,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTAPREZZORES*TD.SEGNO END) as QTAPREZZORES,
    (CASE WHEN RD.TIPORIGA='V' THEN 0 ELSE RD.QTAGESTPRELEVATA*TD.SEGNO END) as QTAGESTPRELEVATA,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTLORDORIGARES*TD.SEGNO ELSE RD.TOTLORDORIGARES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTLORDORIGA,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTNETTORIGARES*TD.SEGNO ELSE RD.TOTNETTORIGARES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTNETTORIGA,
    RD.TOTLORDORIGARES * TD.SEGNO AS TOTLORDORIGAVALUTA,
    RD.TOTNETTORIGARES * TD.SEGNO AS TOTNETTORIGAVALUTA,
    RD.TOTLORDORIGAEURORES * TD.SEGNO AS TOTLORDORIGAEURO,
    RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURO,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTPROVVAG1RES*TD.SEGNO ELSE RD.TOTPROVVAG1RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVAG1,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTPROVVAG2RES*TD.SEGNO ELSE RD.TOTPROVVAG2RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVAG2,
    (CASE WHEN TD.CODCAMBIO=0 THEN RD.TOTPROVVAG3RES*TD.SEGNO ELSE RD.TOTPROVVAG3RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVAG3,
    RD.TOTPROVVAGEURO1RES * TD.SEGNO AS TOTPROVVAG1EURO,
    RD.TOTPROVVAGEURO2RES * TD.SEGNO AS TOTPROVVAG2EURO,
    RD.TOTPROVVAGEURO3RES * TD.SEGNO AS TOTPROVVAG3EURO,
    RD.TOTPROVVAG1RES * TD.SEGNO AS TOTPROVVAG1VALUTA,
    RD.TOTPROVVAG2RES * TD.SEGNO AS TOTPROVVAG2VALUTA,
    RD.TOTPROVVAG3RES * TD.SEGNO AS TOTPROVVAG3VALUTA,
    ANAGRAFICACF.DSCCONTO1,
    ANAGRAFICARISERVATICF.CODCATEGORIA AS CODCATEGORIACF,
    ANAGRAFICACF.CODNAZIONE ,
    ANAGRAFICARISERVATICF.CODSETTORE,
    ANAGRAFICARISERVATICF.CODZONA,
    ANAGRAFICAARTICOLI.GRUPPO,
    ANAGRAFICAARTICOLI.VARESPLICITE,
    ANAGRAFICAARTICOLI.CATEGORIA,
    ANAGRAFICAARTICOLI.CODCATEGORIASTAT,
    ANAGRAFICAARTICOLI.ARTTIPOLOGIA,
    ANAGRAFICAARTICOLI.CODICEPRIMARIO,
    ANAGRAFICAARTICOLI.DESCRIZIONE AS DSCART,
    VISTAARTICOLIDSCBASE.CODARTICOLOBASE,
    VISTAARTICOLIDSCBASE.DSCARTICOLOBASE,
    ARTICOLIFATTORICONVERSIONE.UM1 AS FCUM1,
    ARTICOLIFATTORICONVERSIONE.UM2 AS FCUM2,
    ARTICOLIFATTORICONVERSIONE.FORMULAFC,
    (CASE WHEN ARTICOLIFATTORICONVERSIONE.FATTORE IS NULL THEN 1 ELSE ARTICOLIFATTORICONVERSIONE.FATTORE END) AS FATTORE,
    (SELECT FORMULAFC FROM VISTAFATTORICONVERSIONE WHERE((CODART=RD.CODART) AND (UMJOIN=ARTICOLIFATTORICONVERSIONE.UM2) AND (UMRIC=(SELECT UM FROM STORICOPREZZIARTICOLO WHERE ((CODARTICOLO=RD.CODART) AND (TIPOPREZZO='F')AND (ULTIMO=1))))))AS CONVPRZUNITSTORICO,
    (SELECT PREZZOLIRE FROM STORICOPREZZIARTICOLO WHERE ((CODARTICOLO=RD.CODART) AND (TIPOPREZZO='F')AND (DATA=(SELECT MAX(DATA) FROM STORICOPREZZIARTICOLO WHERE ((TIPOPREZZO='F') AND(CODARTICOLO=RD.CODART) AND (DATA<=TD.DATADOC))))))AS PRZUNITSTORLIRE,
    (SELECT PREZZOEURO FROM STORICOPREZZIARTICOLO WHERE ((CODARTICOLO=RD.CODART) AND (TIPOPREZZO='F')AND (DATA=(SELECT MAX(DATA) FROM STORICOPREZZIARTICOLO WHERE ((TIPOPREZZO='F') AND (CODARTICOLO=RD.CODART) AND (DATA<=TD.DATADOC))))))AS PRZUNITSTOREURO,
    (SELECT FORMULAFC FROM VISTAFATTORICONVERSIONE WHERE((CODART=RD.CODART) AND (UMJOIN=ARTICOLIFATTORICONVERSIONE.UM2) AND (UMRIC=(SELECT UM FROM STORICOPREZZIARTICOLO WHERE ((CODARTICOLO=RD.CODART) AND (TIPOPREZZO='F')AND DATA=(select MAX(DATA) from STORICOPREZZIARTICOLO where(TIPOPREZZO='F') and(CODARTICOLO=RD.CODART) and(DATA<=TD.DATADOC))))))) AS CONVPRZUNIT,
    (SELECT PREZZOLIRE FROM STORICOPREZZIARTICOLO WHERE ((CODARTICOLO=RD.CODART) AND (TIPOPREZZO='F')AND (ULTIMO=1))) AS ULTPRZACQLIRE,
    (SELECT PREZZOEURO FROM STORICOPREZZIARTICOLO WHERE ((CODARTICOLO=RD.CODART) AND (TIPOPREZZO='F')AND (ULTIMO=1))) AS ULTPRZACQEURO,
    RD.RIFRELAZIONECF
FROM
    (((((TESTEDOCUMENTI TD INNER JOIN  RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA)
    INNER JOIN TABCAMBI AS TC ON TD.CODCAMBIO=TC.CODICE)
    INNER JOIN ANAGRAFICACF ON TD.CODCLIFOR = ANAGRAFICACF.CODCONTO)
    INNER JOIN PARAMETRIDOC ON TD.TIPODOC = PARAMETRIDOC.CODICE)
    INNER JOIN ANAGRAFICARISERVATICF ON ANAGRAFICACF.CODCONTO = ANAGRAFICARISERVATICF.CODCONTO)
    LEFT OUTER JOIN
    (((VISTAARTICOLIDSCBASE INNER JOIN ANAGRAFICAARTICOLI ON VISTAARTICOLIDSCBASE.Codice = ANAGRAFICAARTICOLI.CODICE)
    INNER JOIN ARTICOLIFATTORICONVERSIONE ON ANAGRAFICAARTICOLI.CODICE = ARTICOLIFATTORICONVERSIONE.CODART)
    INNER JOIN VISTAARTICOLIUMBASE ON ANAGRAFICAARTICOLI.CODICE = VISTAARTICOLIUMBASE.codice)
    ON ANAGRAFICAARTICOLI.CODICE = RD.CODART,
    TABCAMBI TCAM, TABUTENTI
WHERE (TCAM.CODICE = 0) and USERDB = CAST(USER_NAME() AS VARCHAR(25)) AND
    (ANAGRAFICARISERVATICF.ESERCIZIO = TD.ESERCIZIO)
     AND (RD.UMPREZZO = ARTICOLIFATTORICONVERSIONE.UM1)
    AND (SUPERVISOR = 1 OR 
        (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSIDOCUMENTI WHERE CODDOCUMENTO = TD.TIPODOC AND FLAGVISUALIZZA=1)))
    AND ((TD.CODCLIFOR=TABUTENTI.CODCLIFOR) OR (TABUTENTI.CODCLIFOR=''))

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTADOCUMENTIMARGINERES] TO [Metodo98]
    AS [dbo];

