

CREATE VIEW dbo.VISTACONSUNTIVATPGRUPPOACQUISTOUM
AS
SELECT     CONTRATTI_TESTECONSUNTIVGRUPPIACQ.PROGRESSIVO, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ESERCIZIO, 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ, 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO, 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO AS CODART, CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO AS ASSOCIATO, 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.UM, CONTRATTI_DETTCONSUNTIVGRUPPIACQ.QTA, 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.VALORE, ARTICOLIFATTORICONVERSIONE.UM1, ARTICOLIFATTORICONVERSIONE.UM2, 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.QTA * ARTICOLIFATTORICONVERSIONE.FATTORE AS QTAGESTCONVERTITA
FROM         CONTRATTI_TESTECONSUNTIVGRUPPIACQ INNER JOIN
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ ON 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.PROGRESSIVO = CONTRATTI_DETTCONSUNTIVGRUPPIACQ.RIFPROGRESSIVO INNER JOIN
                      ARTICOLIFATTORICONVERSIONE ON 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = ARTICOLIFATTORICONVERSIONE.CODART AND 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.UM = ARTICOLIFATTORICONVERSIONE.UM1 INNER JOIN
                      VISTAMAXMESECONSGRPACQ ON 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR = VISTAMAXMESECONSGRPACQ.CODCLIFOR AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE = VISTAMAXMESECONSGRPACQ.MESE AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO = VISTAMAXMESECONSGRPACQ.anno AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ESERCIZIO = VISTAMAXMESECONSGRPACQ.ESERCIZIO AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = VISTAMAXMESECONSGRPACQ.ARTICOLO AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = VISTAMAXMESECONSGRPACQ.GRUPPOACQ


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTACONSUNTIVATPGRUPPOACQUISTOUM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTACONSUNTIVATPGRUPPOACQUISTOUM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTACONSUNTIVATPGRUPPOACQUISTOUM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONSUNTIVATPGRUPPOACQUISTOUM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTACONSUNTIVATPGRUPPOACQUISTOUM] TO [Metodo98]
    AS [dbo];

