

CREATE VIEW dbo.VISTA_TRASPORTO_SELTESTEDOC
  AS SELECT TD.*,SD.CODSPED
     FROM TESTEDOCUMENTI TD INNER JOIN  SPEDIZDOCUMENTI SD ON SD.IDTESTA = TD.PROGRESSIVO
                            INNER JOIN  TABUTENTI ON USERDB = CAST(USER_NAME() AS VARCHAR(25))
            
     WHERE (SUPERVISOR = 1 OR 
          (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSIDOCUMENTI WHERE CODDOCUMENTO = TD.TIPODOC AND FLAGABILITA=1))) 
     AND ((TD.CODCLIFOR=TABUTENTI.CODCLIFOR) OR (TABUTENTI.CODCLIFOR=''))

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_TRASPORTO_SELTESTEDOC] TO [Metodo98]
    AS [dbo];

