


/*
    RIF.A#12600 - i dati della macchina e del centro di lavoro vengono estratti dalla lista
*/
CREATE view [dbo].[VISTALISTECONSUNTIVAZIONE] as
select 
    RLC.IDTESTA
    ,TLC.CODICELISTA
    ,TLC.ESERCIZIO
    ,TLC.NUMEROLISTA
    ,TLC.DATAEMISSIONE
    ,TLC.STATOCHIUSO
    ,RLC.IDRIGA
    ,RLC.POSIZIONE
    ,RLC.RIFMOVIMENTO
    ,RLC.DATAMOV
    ,RLC.CODCAUSALE
    ,(select DESCRIZIONE from TABCAUSALIAVANZAMENTO where TABCAUSALIAVANZAMENTO.CODICE=RLC.CODCAUSALE) as DSCCAUSALE
    ,RLC.ANNOBOLLA
    ,RLC.NUMEROBOLLA
    ,RLC.TIPOBOLLA
    ,RLC.CDLAVORO
    ,(select DESCRIZIONE from TABELLACDLAVORO where TABELLACDLAVORO.CODICE=RLC.CDLAVORO) as DSCCDLAVORO
    ,(select REPARTO from TABELLACDLAVORO where TABELLACDLAVORO.CODICE=RLC.CDLAVORO) as CODREPARTO
    ,RCO.CDLAVORO as CDLAVORO_BOLLA
    ,(select DESCRIZIONE from TABELLACDLAVORO where TABELLACDLAVORO.CODICE=RCO.CDLAVORO) as DSCCDLAVORO_BOLLA
    ,(select REPARTO from TABELLACDLAVORO where RCO.CDLAVORO=TABELLACDLAVORO.CODICE) as CODREPARTO_BOLLA
    ,RLC.MACCHINA
    ,(select DESCRIZIONE from TABELLAMACCHINE where TABELLAMACCHINE.CODICE=RLC.MACCHINA) as DSCMACCHINA
    ,RCO.MACCHINA as MACCHINA_BOLLA
    ,(select DESCRIZIONE from TABELLAMACCHINE where TABELLAMACCHINE.CODICE=RCO.MACCHINA) as DSCMACCHINA_BOLLA
    ,RCO.OPERAZIONE
    ,(select DESCRIZIONE from TABELLAOPERAZIONI where RCO.OPERAZIONE=TABELLAOPERAZIONI.CODICE) as DSCOPERAZIONE
    ,RLC.DATAINIZIOSETUP
    ,RLC.ORAINIZIOSETUP
    ,RLC.DATAFINESETUP
    ,RLC.ORAFINESETUP
    ,RLC.ORESETUP
    ,RLC.DATAINIZIOMACCHINA
    ,RLC.ORAINIZIOMACCHINA
    ,RLC.DATAFINEMACCHINA
    ,RLC.ORAFINEMACCHINA
    ,RLC.OREMACCHINA
    ,RLC.DATAINIZIOUOMO
    ,RLC.ORAINIZIOUOMO
    ,RLC.DATAFINEUOMO
    ,RLC.ORAFINEUOMO
    ,RLC.OREUOMO
    ,RLC.DATAINIZIODURATA
    ,RLC.ORAINIZIODURATA
    ,RLC.DATAFINEDURATA
    ,RLC.ORAFINEDURATA
    ,RLC.OREDURATA
    ,RLC.DATAINIZIOMOVNE
    ,RLC.ORAINIZIOMOVNE
    ,RLC.DATAFINEMOVNE
    ,RLC.ORAFINEMOVNE
    ,RLC.OREMOVIMENTAZIONE
    ,RLC.COSTOSETUP
    ,RLC.COSTOSETUPEURO
    ,RLC.DSCCOSTOSETUP
    ,RLC.COSTOMACCHINA
    ,RLC.COSTOMACCHINAEURO
    ,RLC.DSCCOSTOMACCHINA
    ,RLC.COSTOUOMO
    ,RLC.COSTOUOMOEURO
    ,RLC.DSCCOSTOUOMO
    ,RLC.COSTOINDIRETTO
    ,RLC.COSTOINDIRETTOEURO
    ,RLC.DSCCOSTOINDIRETTO
    ,RLC.COSTOESTERNO
    ,RLC.COSTOESTERNOEURO
    ,RLC.DSCCOSTOESTERNO
    ,RLC.QTAVERSATA
    ,RLC.QTARILAVORATA
    ,RLC.QTASCARTATA
    ,RLC.UM
    ,RLC.STATOOPERAZIONE
    ,RLC.CODSQUADRA
    ,RLC.STATORIGA
    ,RLC.NOTE
    FROM 
        TESTELISTACONS TLC 
        inner join RIGHELISTACONS RLC on TLC.PROGRESSIVO=RLC.IDTESTA
        left outer join RIGHECICLOORDINE RCO on RLC.ANNOBOLLA=RCO.ANNOBOLLA and RLC.NUMEROBOLLA=RCO.NUMEROBOLLA


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALISTECONSUNTIVAZIONE] TO [Metodo98]
    AS [dbo];

