

CREATE VIEW VISTACONSFASICHIUSE
AS
    SELECT     *, DATEDIFF([Day], DATAINIZIOOPSCHEDULATA, DATAINIZIOOPEFFETTIVA) AS Anticipo, DATEDIFF([Day],             DATAFINEOPSCHEDULATA,DATAFINEOPEFFETTIVA) AS Ritardo,
    CAST(IDRIGACOMM AS VARCHAR) + '/' + CAST(CODICEORD AS VARCHAR) AS ORDINEPROD
    FROM dbo.VISTABOLLELAVORAZIONE
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONSFASICHIUSE] TO [Metodo98]
    AS [dbo];

