
CREATE VIEW VISTALISTINIFORTRASFSELEZ AS
	SELECT NRLISTINO, DESCRIZIONE, '' AS CODFOR, '' AS DSCCONTO1
FROM TABLISTINITRASFORMAZIONE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALISTINIFORTRASFSELEZ] TO [Metodo98]
    AS [dbo];

