create view VISTALISTAPRODOTTIMPS
AS
SELECT dbo.TESTAMPS.PROGRESSIVO, dbo.TESTAMPS.ESERCIZIO, dbo.TESTAMPS.CODICE, dbo.TESTAMPS.NUMERO, dbo.TESTAMPS.RIFERIMENTO,
       dbo.TESTAMPS.NUMEROFOGLIO, dbo.TESTAMPS.DATAEMISSIONE, dbo.TESTAMPS.FLGPRINCIPALE,
       dbo.RIGHEFORECAST.VERSIONEDBA, dbo.RIGHEFORECAST.UM, dbo.RIGHEFORECAST.QTAPREVISTA, dbo.RIGHEFORECAST.ARTICOLO,
       dbo.RIGHEFORECAST.TIPOPERIODO, dbo.ANAGRAFICAARTICOLI.DESCRIZIONE AS DescrArticolo, dbo.ANAGRAFICAARTICOLI.GRUPPO,
       dbo.ANAGRAFICAARTICOLI.CATEGORIA, dbo.ANAGRAFICAARTICOLI.CODCATEGORIASTAT, dbo.TABGRUPPI.DESCRIZIONE AS DescrGruppo,
       dbo.TABCATEGORIE.DESCRIZIONE AS DescrCategoria, dbo.TABCATEGORIESTAT.DESCRIZIONE AS DescrCategoriaStat
FROM dbo.TESTAMPS
     INNER JOIN dbo.RIGHEFORECAST ON dbo.RIGHEFORECAST.RIFPROGRESSIVO = dbo.TESTAMPS.PROGRESSIVO
     INNER JOIN dbo.ANAGRAFICAARTICOLI ON dbo.RIGHEFORECAST.ARTICOLO = dbo.ANAGRAFICAARTICOLI.CODICE
     INNER JOIN dbo.TABGRUPPI ON dbo.ANAGRAFICAARTICOLI.GRUPPO = dbo.TABGRUPPI.CODICE
     INNER JOIN dbo.TABCATEGORIE ON dbo.TABCATEGORIE.CODICE = dbo.ANAGRAFICAARTICOLI.CATEGORIA 
     INNER JOIN dbo.TABCATEGORIESTAT ON dbo.TABCATEGORIESTAT.CODICE = dbo.ANAGRAFICAARTICOLI.CODCATEGORIASTAT

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALISTAPRODOTTIMPS] TO [Metodo98]
    AS [dbo];

