
/*
    rif.10/02/2016 - creata
*/
CREATE VIEW [VISTAFORNITORIALTERNATIVIFASEEST] AS

    select 
        OPE.CODICE as CODOPERAZIONE
        ,OPE.CODICECDL as CDLAVORO
        ,CDL.TERZISTA
    from TABELLAOPERAZIONI OPE
        inner join TABELLACDLAVORO CDL on CDL.CODICE=OPE.CODICECDL
   
    union all

    select 
        MAC.CODOPERAZIONE
        ,MAC.CODCDLAVORO as CDLAVORO
        ,CDL.TERZISTA
    from MACCHINEALTERNATIVEFASEEST MAC
        inner join TABELLACDLAVORO CDL on CDL.CODICE=MAC.CODCDLAVORO


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAFORNITORIALTERNATIVIFASEEST] TO [Metodo98]
    AS [dbo];

