CREATE VIEW VISTACONTATORI AS
SELECT 
	CODICE,
	DESCRIZIONE,
	PROGR,
	CONTINUA,
	ESERCIZIO,
	CONTIVAANNONUOVO
FROM 
	TABCONTATORI
WHERE 
	ESERCIZIO = (SELECT ESERCIZIOATTIVO  FROM TABUTENTI   WHERE USERDB = USER_NAME())

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONTATORI] TO [Metodo98]
    AS [dbo];

