
CREATE VIEW  VISTAGIACENZEINIZDEPOSITI AS
SELECT ESERCIZIO,CODART,CODDEPOSITO,
    CODUBICAZIONE,NRIFPARTITA,
    SUM(ORDINATO) AS ORDINATO,
    SUM(IMPEGNATO) AS IMPEGNATO,
    SUM(ORDINATO2UM) AS ORDINATO2UM,
    SUM(IMPEGNATO2UM) AS IMPEGNATO2UM,
    SUM(CARICO) AS CARICO,
    SUM(CARICO2UM) AS CARICO2UM,
    SUM(SCARICO) AS SCARICO,
    SUM(SCARICO2UM) AS SCARICO2UM,
    SUM(RESODACARICO) AS RESODACARICO,
    SUM(RESODACARICO2UM) AS RESODACARICO2UM,
    SUM(RESODASCARICO) AS RESODASCARICO,
    SUM(RESODASCARICO2UM) AS RESODASCARICO2UM
    FROM VISTAGIACENZE
    GROUP BY ESERCIZIO,CODART,CODDEPOSITO,
    CODUBICAZIONE,NRIFPARTITA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAGIACENZEINIZDEPOSITI] TO [Metodo98]
    AS [dbo];

