CREATE VIEW VISTAIMPFORNITURACC AS
SELECT 
	IMF.RIFPROGRESSIVO,
	IMF.NUMRIGA,
	IMF.TIPOFORNITURA,
	TIF.DESCRIZIONE AS DESFORNITURA,
	IMF.CODDIVISA,
	IMF.VALOFFERTA,
	IMF.VALFORMALE,
	TC.DIVISA AS TDIVISA,
	TC.DESCRIZIONE AS DESDIVISA
FROM 
	(IMPORTIFORNCOMMCLI IMF INNER JOIN TABIMPORTIFORNITURA TIF
	ON IMF.TIPOFORNITURA=TIF.CODICE)
	INNER JOIN TABCAMBI TC ON TC.CODICE=IMF.CODDIVISA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAIMPFORNITURACC] TO [Metodo98]
    AS [dbo];

