
CREATE VIEW VISTAGIACENZEFIFO AS
SELECT 
    STMAG.CODART,
    STMAG.DATAMOV,
    STMAG.RESO,
    STMAG.CODCAUSALE,
    (CASE WHEN TVG.INCLUDISPRIP=0 THEN STMAG.IMPORTOTOTNETTO ELSE STMAG.IMPORTOTOTNETTO+STMAG.SPESERIPMAG END) AS IMPORTOTOTNETTO,
    (CASE WHEN TVG.INCLUDISPRIP=0 THEN STMAG.IMPORTOTOTNETTOEURO ELSE STMAG.IMPORTOTOTNETTOEURO+STMAG.SPESERIPMAGEURO END) AS IMPORTOTOTNETTOEURO,
    (STMAG.QTA1UM*STMAG.QUANTITACARICO) AS QTACARICO,
     (STMAG.QTA1UM*STMAG.QUANTITASCARICO) AS QTASCARICO,
    (CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS CARICO,
    (CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS SCARICO,
    (CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODACARICO,
    (CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODASCARICO
FROM 
     STORICOMAG AS STMAG INNER JOIN TABVINCOLIGIC AS TVG ON STMAG.ESERCIZIO=TVG.ESERCIZIO 
UNION ALL
SELECT 
    STMAG.CODART,
    STMAG.DATAMOV,
    STMAG.RESO,
    STMAG.CODCAUSALE,
    (CASE WHEN TVG.INCLUDISPRIP=0 THEN STMAG.IMPORTOTOTNETTO ELSE STMAG.IMPORTOTOTNETTO+STMAG.SPESERIPMAG END) AS IMPORTOTOTNETTO,
    (CASE WHEN TVG.INCLUDISPRIP=0 THEN STMAG.IMPORTOTOTNETTOEURO ELSE STMAG.IMPORTOTOTNETTOEURO+STMAG.SPESERIPMAGEURO END) AS IMPORTOTOTNETTOEURO,
    (STMAG.QTA1UM*STMAG.QUANTITACARICO) AS QTACARICO,
     (STMAG.QTA1UM*STMAG.QUANTITASCARICO) AS QTASCARICO,
    (CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS CARICO,
    (CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS SCARICO,
    (CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODACARICO,
    (CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODASCARICO
FROM 
     STORICOMAGARCH AS STMAG INNER JOIN TABVINCOLIGIC AS TVG ON STMAG.ESERCIZIO=TVG.ESERCIZIO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAGIACENZEFIFO] TO [Metodo98]
    AS [dbo];

