CREATE VIEW VISTALIVPRODCALC_ARTGEN AS
-- LIVELLI PRODUZIONE ARTICOLI GENERATI E CORRISPONDENTI NEUTRI
-- Il livello di produzione da considerare per ogni articolo è il MAX dei due
-- Articolo generato e livello produzione calcolato
SELECT DISTINCT TLP.CODART, TLP.LIVPRODNUM
	FROM TEMPLIVPROD_ARTICOLI TLP, ANAGRAFICAARTICOLI AA
	WHERE
	TLP.CODART = AA.CODICE AND
	AA.CODICEPRIMARIO IS NOT NULL

UNION

-- Articolo generato e livello produzione del relativo neutro
SELECT DISTINCT AA.CODICE AS CODART, TLP2.LIVPRODNUM
	FROM ANAGRAFICAARTICOLI AA, TEMPLIVPROD_ARTICOLI TLP2 
	WHERE
	AA.CODICEPRIMARIO IS NOT NULL AND
	AA.CODICEPRIMARIO = TLP2.CODART

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALIVPRODCALC_ARTGEN] TO [Metodo98]
    AS [dbo];

