create view VISTALOGATTIVITAMPS as
	select 
		LOG.* ,
		(select DESCRIZIONE from ANAGRAFICAARTICOLI ART where ART.CODICE=LOG.ARTICOLO) as DSCARTICOLO,
		(cast(TMPS.ESERCIZIO as varchar(4)) + '\' + TMPS.CODICE + '\' + cast(TMPS.NUMERO as varchar(10))) as RIFPIANO,
		TMPS.ESERCIZIO as ANNOMPS,TMPS.CODICE as CODICEMPS,TMPS.NUMERO as NUMEROMPS,TMPS.RIFERIMENTO,TMPS.NUMEROFOGLIO,
		RMPS.ARTICOLO ARTICOLOMPS,RMPS.NOMEPERIODO,RMPS.DESCRIZIONEPERIODO,RMPS.DATAINIZIO,RMPS.DATAFINE,RMPS.UM UMMPS,RMPS.QTAPREVISTA QTAPREVISTAMPS,
		DOC.ESERCIZIO as ANNODOC,DOC.TIPODOC,DOC.NUMERODOC,DOC.BIS,
		(case when DOC.NUMERODOC is null then
			''
		else
			cast(DOC.ESERCIZIO as varchar(4)) + '\' + DOC.TIPODOC + '\' + cast(DOC.NUMERODOC as varchar(10)) + '\' + DOC.BIS
		end) as RIFDOCUMENTO,
		DOC.CODART ARTORDINE,DOC.DESCRIZIONEART as DSCARTICOLODOC,DOC.UMGEST as UMORDINE,DOC.QTAGEST as QTAORDINE,DOC.DATACONSEGNA as DATACONSEGNAORDINE
	from 
		MPSLOGATTIVITA LOG left outer join RIGHEDOCUMENTI DOC on DOC.IDTESTA = LOG.RIFTESTADOC and DOC.IDRIGA=LOG.RIFRIGADOC, 
		TESTAMPS TMPS, RIGHEMPS RMPS
	where
		TMPS.PROGRESSIVO = LOG.RIFTESTAPIANO
		and RMPS.RIFPROGRESSIVO = LOG.RIFTESTAPIANO
		and RMPS.RIFRIGAFORECAST = LOG.RIFRIGAFORECAST
		and RMPS.NUMERORIGA = LOG.RIFRIGAPIANO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALOGATTIVITAMPS] TO [Metodo98]
    AS [dbo];

