
CREATE VIEW VISTA_SCHED_EURIS 
AS
SELECT     TP.PROGRESSIVO AS IDCOMMESSA, RP.IDRIGA AS IDORDINE, RC.PROGRESSIVO AS IDCICLO, RC.NUMEROFASE AS NUMEROFASE, 
                      RC.POSIZIONE AS POSIZIONE, TP.TIPOCOM, TP.ESERCIZIO, TP.NUMEROCOM, RP.CODICEORD, TP.DATAEMISSIONE, 
                      TP.TIPOCOM + '/' + cast(TP.ESERCIZIO AS varchar) + '/' + RIGHT('0000000000' + cast(TP.NUMEROCOM AS varchar), 10) AS RIFCOMMESSA, 
                      TP.TIPOCOM + '/' + cast(TP.ESERCIZIO AS varchar) + '/' + RIGHT('0000000000' + cast(TP.NUMEROCOM AS varchar), 10) 
                      + '/' + RP.CODICEORD + '/' + RIGHT('00000' + cast(RP.IDRIGA AS varchar), 5) AS RIFORDINE, RP.RIFCOMMCLI, RP.CODART, RP.DESCRIZIONEART, 
                      RP.CODCLIDEST,
                          (SELECT     DSCCONTO1
                            FROM          ANAGRAFICACF
                            WHERE      CODCONTO = RP.CODCLIDEST) AS RAGSOCCLIDEST, RP.CODFORDEST,
                          (SELECT     DSCCONTO1
                            FROM          ANAGRAFICACF
                            WHERE      CODCONTO = RP.CODFORDEST) AS RAGSOCFORDEST, (CASE WHEN RP.FASERILASCIO = 1 THEN 0 ELSE 1 END) 
                      AS ORDINECONFERMATO, RP.FASERILASCIO, RP.DATAINIZIORICH, RP.DATAFINERICH, RP.VALOREPRIORITA, RC.CDLAVORO, RC.RIFSOVRAPP, 
                      RC.TIPOSOVRAPP, RC.INDICESOVRAPP,
                          (SELECT     DESCRIZIONE
                            FROM          TABELLACDLAVORO
                            WHERE      CODICE = RC.CDLAVORO) AS DSCCDLAVORO, (CASE WHEN RC.MACCHINA = '' THEN RC.CDLAVORO ELSE RC.MACCHINA END) 
                      AS MACCHINA, (CASE WHEN RC.MACCHINA = '' THEN
                          (SELECT     DESCRIZIONE
                            FROM          TABELLACDLAVORO
                            WHERE      CODICE = RC.CDLAVORO) ELSE
                          (SELECT     DESCRIZIONE
                            FROM          TABELLAMACCHINE
                            WHERE      CODICE = RC.MACCHINA) END) AS DSCMACCHINA, RC.ANNOBOLLA, RC.NUMEROBOLLA, cast(RC.ANNOBOLLA AS varchar(4)) 
                      + '/' + RIGHT('00000000' + cast(RC.NUMEROBOLLA AS varchar), 8) AS DSCFASE, RC.OPERAZIONE,
                          (SELECT     DESCRIZIONE
                            FROM          TABELLAOPERAZIONI
                            WHERE      CODICE = RC.OPERAZIONE) AS DSCOPERAZIONE, RC.STATOOPERAZIONE, RC.OREPREVDURATA, RC.OREEFFDURATA, 
                      (CASE WHEN (RC.OREPREVDURATA - RC.OREEFFDURATA) < 0 THEN 0 ELSE (RC.OREPREVDURATA - RC.OREEFFDURATA) END) AS ORERESDURATA, 
                      (CASE WHEN RC.OREPREVDURATA = 0 THEN 0 ELSE (RC.OREEFFDURATA / RC.OREPREVDURATA) * 100 END) AS PERCAVANZAMENTODURATA, 
                      RC.DATAINIZIOOPEFFETTIVA, RC.DATAINIZIOOPSCHEDULATA, RC.DATAFINEOPSCHEDULATA, RC.TEMPOPREVATTRAV, RC.TIPOFASE, RP.QTA1MAG, 
                      RC.QTAVERSATA, RC.QTAPREVISTA, UC.CODICEUTENSILE,
                          (SELECT     DESCRIZIONE
                            FROM          TABUTENSILI TU
                            WHERE      TU.CODICE = UC.CODICEUTENSILE) AS DSCUTENSILE
FROM         ((((TESTEORDINIPROD TP INNER JOIN
                      RIGHEORDPROD RP ON RP.IDTESTA = TP.PROGRESSIVO) INNER JOIN
                      TESTACICLOORDINE TC ON TC.IDTESTACOMM = TP.PROGRESSIVO AND TC.IDRIGACOMM = RP.IDRIGA) INNER JOIN
                      RIGHECICLOORDINE RC ON RC.PROGRESSIVO = TC.PROGRESSIVO) LEFT OUTER JOIN
                      TABUTENSILICICLOORD UC ON UC.PROGRESSIVO = RC.PROGRESSIVO AND UC.NUMEROFASE = RC.NUMEROFASE)
WHERE     RP.FASERILASCIO < 5 AND RP.STATOLANCIO <> 2


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTA_SCHED_EURIS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTA_SCHED_EURIS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTA_SCHED_EURIS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_SCHED_EURIS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTA_SCHED_EURIS] TO [Metodo98]
    AS [dbo];

