
CREATE VIEW VISTADETTAGLIOCONSUNTIVATOGRPACQ
AS
SELECT     dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.RIFPROGRESSIVO, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO, dbo.ANAGRAFICACF.DSCCONTO1, 
                      dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.UM, dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.QTA, dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.VALORE, 
                      dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.QTAPREC, dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.VALOREPREC, 
                      dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.UTENTEMODIFICA, dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.DATAMODIFICA, 
                      dbo.ACQ_COMPONENTIGRUPPOACQUISTO.IDSOCIO, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.RIFCODICE
FROM         dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ INNER JOIN
                      dbo.ACQ_COMPONENTIGRUPPOACQUISTO ON 
                      dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO = dbo.ACQ_COMPONENTIGRUPPOACQUISTO.IDSOCIO LEFT OUTER JOIN
                      dbo.ANAGRAFICACF ON dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO = dbo.ANAGRAFICACF.CODCONTO


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTADETTAGLIOCONSUNTIVATOGRPACQ] TO [Metodo98]
    AS [dbo];

