CREATE VIEW VISTAIMPOSTAZIONIVISIONI AS
SELECT 
	NOMEVISIONE,
   NOMEIMPOSTAZIONE, 
   NOMEUTENTE,
   IMPPIVOT,
   (CASE WHEN NOMEUTENTE='TRM' THEN 'SI' ELSE 'NO' END) IMPCOMUNE,
   (CASE WHEN IMPPIVOT=1 THEN 'SI' ELSE 'NO' END) DESIMPPIVOT
FROM TESTEIMPOSTAZIONIVISIONI

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAIMPOSTAZIONIVISIONI] TO [Metodo98]
    AS [dbo];

