
/*
    rif.20/10/2015 - creata
*/
CREATE VIEW [VISTAMACCHINEALTERNATIVEFASEEST] AS
    select 
        MAC.[CODOPERAZIONE]
        ,MAC.[NRRIGA]
        ,MAC.[CODCDLAVORO]
        ,CDL.[DESCRIZIONE] AS DSCCDLAVORO
        ,CDL.[TERZISTA]
        ,MAC.[CODMACCHINA]
        ,(SELECT [DESCRIZIONE] FROM TABELLAMACCHINE MC WHERE MC.CODICE=MAC.[CODMACCHINA]) AS DSCMACCHINA
        ,MAC.[FLAGPREFERENZIALE]
        ,MAC.[TEMPOATTRAVERSAMENTO]
        ,MAC.[LOTTOATTRAVERSAMENTO]
        ,MAC.[TIPOARROTONDAMENTO]
    from [MACCHINEALTERNATIVEFASEEST] MAC   
        inner join [TABELLACDLAVORO] CDL on CDL.[CODICE]=MAC.[CODCDLAVORO]

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMACCHINEALTERNATIVEFASEEST] TO [Metodo98]
    AS [dbo];

