CREATE VIEW VISTABOLLECOLLEGATE AS
SELECT 
	VB.ANNOBOLLA,VB.NUMEROBOLLA,
	GB.ANNOBOLLA AS ANNOBOLLACOLL,GB.NUMEROBOLLA AS NUMEROBOLLACOLL
FROM 
	(VISTABOLLELAVORAZIONE VB
	LEFT OUTER JOIN (TABELLAGRUPPIBOLLE GB INNER JOIN BOLLECOLLEGATE BC ON
	GB.ANNOBOLLA=BC.RIFANNOBOLLA AND GB.NUMEROBOLLA=BC.RIFNUMEROBOLLA)
	ON VB.ANNOBOLLA=BC.ANNOBOLLA AND VB.NUMEROBOLLA=BC.NUMEROBOLLA)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTABOLLECOLLEGATE] TO [Metodo98]
    AS [dbo];

