CREATE VIEW VISTACOMPETENZEPN AS
        SELECT RCOMP.CODGENERICO AS CONTO,
        RCOMP.ANNO, RCOMP.MESE, RCOMP.CODCOMMESSA, RCOMP.NRRIGA, RCOMP.POSIZIONE, TCONT.PROGRESSIVO, TCONT.ESERCIZIO, TCONT.DATAREG,
        TCONT.DATARIF, TCONT.NRRIFER, TCONT.PROVVISORIO, TCONT.CAUSALE, TCONT.DESCRIZIONE, TCONT.NRGIORNALE,
        TCONT.MESEPLAFOND, TCONT.APPUNTI, 
        (CASE WHEN RCOMP.SEGNO=0 THEN RCOMP.IMPORTO ELSE 0 END)  AS DARE,
        (CASE WHEN RCOMP.SEGNO=0 THEN RCOMP.IMPORTOEURO ELSE 0 END)  AS DAREEURO,
        (CASE WHEN RCOMP.SEGNO=1 THEN RCOMP.IMPORTO ELSE 0 END)  AS AVERE,
        (CASE WHEN RCOMP.SEGNO=1 THEN RCOMP.IMPORTOEURO ELSE 0 END)  AS AVEREEURO,
        (SELECT DISTINCT NUMDOC FROM RIGHEIVA WHERE NRREG=RCOMP.NRREG AND TIPOREGISTRO=TCONT.MOVIVA) AS NUMDOC,
        (SELECT DISTINCT DATADOC FROM RIGHEIVA WHERE NRREG=RCOMP.NRREG AND TIPOREGISTRO=TCONT.MOVIVA) AS DATADOC,
        (SELECT DISTINCT MESELIQUIDAZ FROM RIGHEIVA WHERE NRREG=RCOMP.NRREG AND TIPOREGISTRO=TCONT.MOVIVA) AS MESELIQUIDAZ,
        RCOMP.ANNOMESE,
        (SELECT DSCCONTO1 FROM ANAGRAFICAGENERICI WHERE CODCONTO=RCOMP.CODGENERICO) AS DSCCONTO1,
        (SELECT CODMASTRO FROM ANAGRAFICAGENERICI WHERE CODCONTO=RCOMP.CODGENERICO) AS CODMASTRO,
        (SELECT DESCRIZIONE FROM TABMASTRI WHERE CODICE=(SELECT CODMASTRO FROM ANAGRAFICAGENERICI WHERE CODCONTO=RCOMP.CODGENERICO)) AS DSCMASTRO,
        (SELECT TOP 1 CODCAMBIO FROM RIGHECONTABILITA RC WHERE RC.NRREG=RCOMP.NRREG AND RC.CONTO=RCOMP.CODGENERICO) AS CODCAMBIO
        FROM COMPETENZEPN RCOMP, TESTECONTABILITA TCONT 
        WHERE (RCOMP.NRREG=TCONT.PROGRESSIVO) AND 
        TCONT.CAUSALE<>(SELECT GIC.CAUSCONTAP FROM TABVINCOLIGIC GIC WHERE ESERCIZIO=TCONT.ESERCIZIO) AND
        TCONT.CAUSALE<>(SELECT GIC.CAUSCONTCH FROM TABVINCOLIGIC GIC WHERE ESERCIZIO=TCONT.ESERCIZIO)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACOMPETENZEPN] TO [Metodo98]
    AS [dbo];

