CREATE VIEW VISTACAUSMOVCES AS 
    SELECT 
    	CODICE,
    	DESCRIZIONE
    FROM TABCAUSALICES
    WHERE CODICE NOT IN (1,5,11,12)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACAUSMOVCES] TO [Metodo98]
    AS [dbo];

