
CREATE VIEW VISTAFORNITORI AS
SELECT AF.TIPOCONTO,AF.CODCONTO,AF.DSCCONTO1,
    AF.DSCCONTO2,AF.CODMASTRO,AF.INDIRIZZO,
    AF.CAP,AF.LOCALITA,AF.PROVINCIA,AF.TELEFONO,
    AF.FAX,AF.TELEX,AF.CODFISCALE,AF.PARTITAIVA,AF.CODIDENTIVAESTERO,
    AF.CODNAZIONE,AF.CODICEISO,AF.CODLINGUA,AF.CODREGIONE,
    AF.NOTE,AF.UTENTEMODIFICA,AF.DATAMODIFICA,
    RF.ESERCIZIO,RF.CODSETTORE,RF.CODZONA,
    AF.TIPOPROFESSIONISTA,AF.LUOGONASCITA,AF.FLGBLACKLIST,AF.FLGELENCOCF,
    AF.DATANASCITA,AF.TIPODOCRTACC,AF.VERSPRESSO,AF.FLGDOGANA,
    RF.CODCATEGORIA,RF.CODSPED,
    RF.PRCTRASPORTO,RF.INOLTROTRASP,RF.CODPAG,
    RF.MESEESCL1,RF.GGESCL1,RF.MESEESCL2,
    RF.GGESCL2,
    (SELECT CAB FROM BANCAAPPCF WHERE CODCONTO=RF.CODCONTO AND CODICE=BANCAANAGR) AS CAB, 
    (SELECT ABI FROM BANCAAPPCF WHERE CODCONTO=RF.CODCONTO AND CODICE=BANCAANAGR) AS ABI,
    RF.CODBANCA,
    RF.BANCAANAGR,RF.CODAGENTE1,RF.CODAGENTE2,
    RF.CODAGENTE3,RF.PROVV1,RF.PROVV2,
    RF.PROVV3,RF.SCONTO1,RF.CODIVA,RF.DICHESIVA,
    RF.LISTINO,RF.CODCAMBIO,RF.DESTDIVMERCI,
    RF.DESTDIVDOCUMENTI,RF.SPESEDOCUM,
    RF.SPESEEFFETTO,RF.SPESETRASPORTO,
    RF.SPESEIMBALLO,RF.FIDO,RF.FIDOEURO,
    RF.PORTO,RF.TRASPACURA,RF.APPLSCONTORIGA,
    RF.APPLSCONTOFINALE,RF.CODCONTOFATT,
    RF.FATTFINEMESE,RF.NONRAGGRUPPDOC,
    RF.CODDEPOSITO,RF.CODDEPOSITOCOLL,
    RF.CODDEPCOMP,RF.CODDEPCOMPCOLL,
    RF.RIVIVAOMAGGI,RF.NRCONTROPCONT,
    RF.USAPRZPRVPART,RF.CCDEBITORE,
    RF.CODDEBITORE,RF.NOTE1,RF.STATOCONTABILITA,
    RF.STATOMAGAZZINO,RF.STATOORDINI,
    RF.STATOBOLLE,RF.STATOFATTURE,
    RF.STATONOTEACCREDITO,RF.STATOALTRO,
    RF.CODGRUPPOPREZZIPART,
    RF.CODGRUPPOPROVPART,
    RF.RAGGSCADENZE,
    RF.PROGDICHINTENTO,
    RF.SPLITPAYMENT
    FROM ANAGRAFICACF AF,ANAGRAFICARISERVATICF RF
    WHERE(AF.CODCONTO=RF.CODCONTO)
    AND RF.ESERCIZIO=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25))) AND AF.TIPOCONTO='F'
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAFORNITORI] TO [Metodo98]
    AS [dbo];

