create view VISTAECCEZIONIPROGPROD as
	select 
		ECC.*,
		PRP.LIVELLO,		
		ART.DESCRIZIONE as DSCARTICOLO,
		ART.VARESPLICITE,
		ART.ARTTIPOLOGIA,
		ART.CATEGORIA,ART.CODCATEGORIASTAT,ART.GRUPPO,		
		PRP.DATACONS,		
		PRP.TIPO as TIPORIGAPIANO,
		PRP.QTADOCBASE,PRP.QTAIMP,PRP.QTAORD,PRP.SITUAZIONE,PRP.UMARTICOLO,
		PRP.IDTESTADOC,PRP.IDRIGADOC,
		PRP.RIFCOMMCLI,
		ART.TIPOGESTIONE,
		ART.LOTTORIORDINO,
		ART.PROVENIENZA,
		ART.QMINRIORDACQ,ART.QMINRIORDPROD,ART.QMINRIORDLAV,
		(case ART.TIPOGESTIONE when 0 then ART.LOTTORIORDINO else 
			(case ART.PROVENIENZA when 0 then ART.QMINRIORDACQ when 1 then ART.QMINRIORDPROD when 2 then ART.QMINRIORDPROD end) 
		end) as LOTTO
	from ((ECCEZIONIPROGPROD ECC inner join PROGPRODUZIONE PRP 
		on ECC.NOMEPIANIF=PRP.NOMEPIANIF and ECC.RIFID=PRP.PROG_ID)
		left outer join VISTAANAGRAFICAARTICOLI ART on ART.CODICE=PRP.CODART)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAECCEZIONIPROGPROD] TO [Metodo98]
    AS [dbo];

