CREATE VIEW VISTACONSUMIDOCRESO AS
SELECT IDTESTA_RESOCL,IDRIGA_RESOCL,
(SELECT TIPODOC FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL) AS TIPODOCRESO,
(SELECT NUMERODOC FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL) AS NUMDOCRESO,
(SELECT BIS FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL) AS BISRESO,
(SELECT ESERCIZIO FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL) AS ESERCIZIORESO,
(SELECT DATADOC FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL) AS DATADOCRESO,
(SELECT CODCLIFOR FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL) AS CODCLIFOR,
(SELECT QTA1MAG FROM RIGHEDOCUMENTI WHERE IDTESTA=IDTESTA_RESOCL AND IDRIGA=IDRIGA_RESOCL) AS QTADOCRESO,
(SELECT VERSIONEDIBA FROM RIGHEDOCUMENTI WHERE IDTESTA=IDTESTA_RESOCL AND IDRIGA=IDRIGA_RESOCL) AS VERSIONEDBADOCRESO,
(SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO=(SELECT CODCLIFOR FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_RESOCL)) AS RAGSOCCF,
(SELECT CODART FROM RIGHEDOCUMENTI WHERE IDTESTA=IDTESTA_RESOCL AND IDRIGA=IDRIGA_RESOCL) AS CODART,
(SELECT DESCRIZIONE FROM ANAGRAFICAARTICOLI WHERE CODICE=(SELECT CODART FROM RIGHEDOCUMENTI WHERE IDTESTA=IDTESTA_RESOCL AND IDRIGA=IDRIGA_RESOCL)) AS DESCRIZIONEART
FROM CONSUMICLAVORAZIONE 
GROUP BY IDTESTA_RESOCL,IDRIGA_RESOCL

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONSUMIDOCRESO] TO [Metodo98]
    AS [dbo];

