CREATE VIEW VISTACONTIPATRIMONIALI
  AS SELECT RCONT.CONTO,RCONT.ESERCIZIO,
	(CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTO ELSE 0 END) AS DARE,
	(CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOEURO ELSE 0 END) AS DAREEURO,
	(CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS DAREVALUTA,
	(CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTO ELSE 0 END) AS AVERE,
	(CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOEURO ELSE 0 END) AS AVEREEURO,
	(CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS AVEREVALUTA,
	((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTO ELSE 0 END)-(CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTO ELSE 0 END)) AS SALDO,
	((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOEURO ELSE 0 END)-(CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOEURO ELSE 0 END)) AS SALDOEURO,
	((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOVALUTA ELSE 0 END)-(CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOVALUTA ELSE 0 END)) AS SALDOVALUTA,
	(SELECT TM.TIPO FROM TABMASTRI AS TM WHERE TM.CODICE=(SELECT AG.CODMASTRO FROM ANAGRAFICAGENERICI AS AG WHERE AG.CODCONTO=RCONT.CONTO)) AS TIPOCONTO,
	(SELECT PROVVISORIO FROM TESTECONTABILITA WHERE PROGRESSIVO=RCONT.NRREG) AS PROVVISORIO,
	(SELECT NRGIORNALE FROM TESTECONTABILITA WHERE PROGRESSIVO=RCONT.NRREG) AS NRGIORNALE
	FROM RIGHECONTABILITA AS RCONT
	WHERE(SELECT TM.TIPO FROM TABMASTRI AS TM WHERE TM.CODICE=(SELECT AG.CODMASTRO FROM ANAGRAFICAGENERICI AS AG WHERE AG.CODCONTO=RCONT.CONTO))<>'E'
	OR(SELECT TM.TIPO FROM TABMASTRI TM WHERE TM.CODICE=(SELECT AG.CODMASTRO FROM ANAGRAFICAGENERICI AG WHERE AG.CODCONTO=RCONT.CONTO)) IS NULL

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONTIPATRIMONIALI] TO [Metodo98]
    AS [dbo];

