CREATE VIEW VISTALIVPRODCALC_DBAREGOLE AS
-- Estrae tutti i codici di anagrafica generati per i quali la corrispondente distinta generica
-- contiene almeno un componente inesistente in anagrafica e quindi "a regole"
-- i componenti a tipologia vengono ignorati considerando solo la radice del codice, cioè il neutro
SELECT DISTINCT CODICE FROM ANAGRAFICAARTICOLI 
WHERE CODICEPRIMARIO+'#' IN
(
SELECT DISTINCT AC.ARTCOMPOSTO 
      FROM DISTINTAARTCOMPOSTI AC
      INNER JOIN DISTINTABASE DB ON AC.PROGRESSIVO = DB.RIFPROGRESSIVO
      LEFT OUTER JOIN ANAGRAFICAARTICOLI AA ON
                 CASE CHARINDEX('#', DB.CODARTCOMPONENTE)-1
                WHEN -1 THEN DB.CODARTCOMPONENTE
                ELSE LEFT(DB.CODARTCOMPONENTE, 
  CHARINDEX('#', DB.CODARTCOMPONENTE)-1)
           END = AA.CODICE
WHERE 
      AA.DESCRIZIONE IS NULL 
)

UNION

SELECT DISTINCT CODICE FROM ANAGRAFICAARTICOLI 
WHERE CODICE IN
(
SELECT DISTINCT AC.ARTCOMPOSTO 
      FROM DISTINTAARTCOMPOSTI AC
      INNER JOIN DISTINTABASE DB ON AC.PROGRESSIVO = DB.RIFPROGRESSIVO
      LEFT OUTER JOIN ANAGRAFICAARTICOLI AA ON
                 CASE CHARINDEX('#', DB.CODARTCOMPONENTE)-1
                WHEN -1 THEN DB.CODARTCOMPONENTE
                ELSE LEFT(DB.CODARTCOMPONENTE, 
  CHARINDEX('#', DB.CODARTCOMPONENTE)-1)
           END = AA.CODICE
WHERE 
      AA.DESCRIZIONE IS NULL 
)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALIVPRODCALC_DBAREGOLE] TO [Metodo98]
    AS [dbo];

