CREATE VIEW VISTAIMPPRODNAV
  AS SELECT
  	3 AS ORIGINE,
  	TC.PROGRESSIVO IDTESTA,RI.IDRIGA,RI.IDIMPEGNO,
	TC.ESERCIZIO,TC.TIPOCOM AS TIPO,TC.NUMEROCOM AS NUMERO,'' AS BIS,
  	TC.DATAEMISSIONE,
  	TC.CODCLIENTE AS CODCLIFOR,
  	(SELECT DSCCONTO1 FROM AnagraficaCF WHERE AnagraficaCF.CodConto=TC.CODCLIENTE) AS RagSocCliFor,
  	RI.CODART,RI.DESCRIZIONEART,
  	RI.DATAIMPEGNORICH AS DATACONSEGNA,
  	RI.UMGEST, RI.QTAGESTIONE, RI.QTAGESTIONERES, RI.QTAGESTIONEVERS, 
  	RI.UMPREZZO,RI.QTAPREZZO,RI.QTAPREZZORES,
  	(SELECT UM FROM ARTICOLIUMPREFERITE AUM WHERE AUM.CODART = RI.CODART AND AUM.TIPOUM = 1) UM1MAG,
	RI.QTA1MAG,RI.QTA1MAGRES,
	(SELECT UM FROM ARTICOLIUMPREFERITE AUM WHERE AUM.CODART = RI.CODART AND AUM.TIPOUM = 2) UM2MAG,
	RI.QTA2MAG,RI.QTA2MAGRES,
	RI.PARTITAASSEGNATA, 	
	RI.DEPOSITO AS CODDEPOSITO,RI.DEPOSITOCOLL AS CODDEPOSITOCOLL,
	RI.UBICAZIONE,RI.UBICAZIONECOLL,
	RI.COSTOUNITIMPPREV AS COSTOUNITARIO,
	RI.COSTOUNITIMPPREVEURO AS COSTOUNITARIOEURO,
	RI.COSTOTOTIMPPREV AS COSTOTOTALE,
	RI.COSTOTOTIMPPREVEURO AS COSTOTOTALEEURO
FROM
	TESTEORDINIPROD TC, IMPEGNIORDPROD RI
WHERE
	TC.PROGRESSIVO = RI.IDTESTA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAIMPPRODNAV] TO [Metodo98]
    AS [dbo];

