
CREATE VIEW VISTAIMPOSTAZIONIRICERCHE AS
SELECT 
    NOMEIMPOSTAZIONE, 
    (CASE WHEN NOMEUTENTE='TRM' THEN 'SI' ELSE 'NO' END) IMPCOMUNE,
    PROGRESSIVO,
    RIFHELPCONTEXTID,
    NOMEUTENTE,
    IDVISIONE
FROM 
    TESTEIMPOSTAZIONIRICERCHE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAIMPOSTAZIONIRICERCHE] TO [Metodo98]
    AS [dbo];

