CREATE VIEW VISTACONSUNTIVOSTRUTTURATO_DEST AS
SELECT 
	IDCOMMCLI,
	RIFCOMM,
	RIFCOMMRIEP,
	(CASE WHEN TIPONODO=0 THEN LIVPADRE ELSE CODNODO END) AS CODNODO,
	(CASE WHEN TIPONODO=0 THEN CODNODO ELSE '' END) AS CODFOGLIA,
	DESCRIZIONE,
	DESCRIZIONECC,
	TIPOCOSTO,
	VOCEBASE,
	IDVOCE,
	CODICE,
	QTABASE,
	UMBASE,
	UMVAL,
	PRC,
	STATOCOMMESSA,
	RIFTESTA_DEST AS RIFTESTA,
	RIFRIGA_DEST AS RIFRIGA,
	ORIGINEEVENTO_DEST AS ORIGINEEVENTO,
	COSTOUNIEURO,
	CONSUNTIVATORIPEURO,
	RISERVATORIPEURO,
	ORDINATORIPEURO,
	PREVISTORIPEURO,
	COSTOTOTRIPEURO,
	COSTOUNILIRE,
	CONSUNTIVATORIP,
	RISERVATORIP,
	ORDINATORIP,
	PREVISTORIP,
	COSTOTOTRIP,
	TIPOREC,
	IDRECORDV
FROM 
	VISTARIEPILOGOCCSTRUTT_DEST

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONSUNTIVOSTRUTTURATO_DEST] TO [Metodo98]
    AS [dbo];

