
CREATE VIEW VISTAFOGLILAVORAZIONE
  AS SELECT TESTACICLOORDINE.PROGRESSIVO,
    TESTACICLOORDINE.CODCICLO,
    TESTACICLOORDINE.VERSIONECICLO,
    TESTACICLOORDINE.DSCVERSIONE,
    TESTACICLOORDINE.STATOVERSIONE,
    TESTACICLOORDINE.VALIDITACICLO,
    TESTACICLOORDINE.VERSIONEDBA,
    TESTACICLOORDINE.CICLOSTANDARD,
    TESTACICLOORDINE.NOTECICLO,
    TESTACICLOORDINE.UM as UMRIF,
    TESTACICLOORDINE.QUANTITARIF,
    TESTACICLOORDINE.TIPOCICLO,
    TESTACICLOORDINE.IDTESTACOMM,
    TESTACICLOORDINE.IDRIGACOMM,
    TESTACICLOORDINE.FLGRIVALUTACICLO,
    TESTEORDINIPROD.ESERCIZIO,
    TESTEORDINIPROD.TIPOCOM,
    TESTEORDINIPROD.NUMEROCOM,
    TESTEORDINIPROD.DATAEMISSIONE,
    RIGHEORDPROD.CODICEORD,
    RIGHEORDPROD.CODART,
    RIGHEORDPROD.DESCRIZIONEART,
    RIGHEORDPROD.UMGEST,
    RIGHEORDPROD.QTAGESTIONE,
    RIGHEORDPROD.QTAGESTIONEVERS,
    RIGHEORDPROD.QTAGESTIONERES,
    RIGHEORDPROD.CODCLIDEST,
    RIGHEORDPROD.TIPOSCHEDULAZIONE,
    RIGHEORDPROD.DATAEMISSIONE as DATAEMISSIONEORD,
    RIGHEORDPROD.FASERILASCIO,
    RIGHEORDPROD.DATARILASCIO,
    RIGHEORDPROD.RIFCOMMCLI,
    RIGHEORDPROD.DEPOSITO,
    RIGHEORDPROD.UBICAZIONE,
    RIGHEORDPROD.STATOORDINE,
    RIGHEORDPROD.STATOLANCIO,
    RIGHEORDPROD.STATOSTAMPACICLO
FROM
    TESTACICLOORDINE,TESTEORDINIPROD,RIGHEORDPROD 
WHERE
    (TESTACICLOORDINE.IDTESTACOMM = TESTEORDINIPROD.PROGRESSIVO) AND
    (TESTACICLOORDINE.IDTESTACOMM = RIGHEORDPROD.IDTESTA AND
    TESTACICLOORDINE.IDRIGACOMM = RIGHEORDPROD.IDRIGA)
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAFOGLILAVORAZIONE] TO [Metodo98]
    AS [dbo];

