
CREATE VIEW VISTACASTELLETTIIVAPA AS
SELECT 
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVA),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVA),0) AS TIPOESENZIVA,
(CASE WHEN COALESCE(CODIVA,0)=0 THEN 'N2' ELSE
COALESCE((SELECT NATURAESENZPA FROM TRATTAMENTOIVA WHERE CODICE=CODIVA),'') END) AS NATURAESENZ,
(CASE WHEN COALESCE(CODIVA,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVA AND TIPOCICLO IN (0,2)),'') END) AS NATURAESENZB2B,
(CASE WHEN COALESCE(CODIVA,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVA AND TIPOCICLO IN (1,2)),'') END) AS NATURAESENZB2BPASS,
(CASE WHEN (CODIVA BETWEEN 600 AND 699) THEN 'D' 
      WHEN (SELECT SPLITPAYMENT FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA)<>0 AND NOT (CODIVA BETWEEN 200 AND 299) THEN 'S' 
      ELSE 'I' END) AS ESIGIBIVA,
(SELECT DESCRIZIONE FROM TRATTAMENTOIVA WHERE CODICE=CODIVA) AS DESCRCODIVA,
* FROM CASTELLETTIIVA
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACASTELLETTIIVAPA] TO [Metodo98]
    AS [dbo];

