
-- Fine Sviluppo 4022

CREATE VIEW VISTABROGLIACCIO AS
        SELECT TC.*,RC.CONTO,RC.CODCAMBIO,RC.VALORECAMBIO,RC.CODCOMMESSA,RC.SEGNO,RC.NRRIGA,RC.DESCRIZIONE DSCRIGA,RC.POSIZIONE,RC.NRPARTITA,RC.DATAVALUTA,
        (CASE WHEN RC.SEGNO=0 THEN IMPORTO ELSE 0 END)  DARE,(CASE WHEN RC.SEGNO=0 THEN IMPORTOEURO ELSE 0 END)  DAREEURO,(CASE WHEN RC.SEGNO=0 THEN IMPORTOVALUTA ELSE 0 END)  DAREVALUTA,
        (CASE WHEN RC.SEGNO=1 THEN IMPORTO ELSE 0 END)  AVERE,(CASE WHEN RC.SEGNO=1 THEN IMPORTOEURO ELSE 0 END)  AVEREEURO,(CASE WHEN RC.SEGNO=1 THEN IMPORTOVALUTA ELSE 0 END)  AVEREVALUTA,
        (CASE WHEN SUBSTRING(RC.CONTO,1,1)<>'G' THEN (SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO=RC.CONTO) ELSE (SELECT DSCCONTO1 FROM ANAGRAFICAGENERICI WHERE CODCONTO=RC.CONTO) END)  DSCCONTO,
        (SELECT TOP 1 NUMDOC FROM RIGHEIVA WHERE NRREG=TC.PROGRESSIVO AND TIPOREGISTRO=TC.MOVIVA) NUMDOC,
        (SELECT TOP 1 DATADOC FROM RIGHEIVA WHERE NRREG=TC.PROGRESSIVO AND TIPOREGISTRO=TC.MOVIVA) DATADOC,
        (SELECT TOP 1 MESELIQUIDAZ FROM RIGHEIVA WHERE NRREG=TC.PROGRESSIVO AND TIPOREGISTRO=TC.MOVIVA) MESELIQUIDAZ
        FROM TESTECONTABILITA TC, RIGHECONTABILITA RC WHERE TC.PROGRESSIVO=RC.NRREG

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTABROGLIACCIO] TO [Metodo98]
    AS [dbo];

