CREATE VIEW VISTAIMPOSTAZIONISTAMPA AS
SELECT DISTINCT NOMEIMPOSTAZIONE, 
        (CASE WHEN NOMEUTENTE='TRM' THEN 'SI' ELSE 'NO' END)  IMPCOMUNE,
        NOMEFILTRO,
        NOMEUTENTE,
        IMPDEFAULT,
        (CASE WHEN IMPDEFAULT<>0 THEN 'SI' ELSE 'NO' END)  IMPPREDEFINITA
        FROM IMPOSTAZIONISTAMPA WHERE TIPOIMPOSTAZIONE<>3

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAIMPOSTAZIONISTAMPA] TO [Metodo98]
    AS [dbo];

