create view VISTAMACCHINEALTERNATIVE as
	select 
		OPE.CODICE as OPERAZIONE,
		OPE.MACCHINAPREF as MACCHINA,
		MAC.DESCRIZIONE as DSCMACCHINA
	from 
		TABELLAOPERAZIONI OPE 
		inner join TABELLAMACCHINE MAC on MAC.CODICE=OPE.MACCHINAPREF
	
	union
	
	select
		ALT.CODOPERAZIONE as OPERAZIONE,
		ALT.CODMACCHINA as MACCHINA,
		MAC.DESCRIZIONE as DSCMACCHINA
	from
		MACCHINEALTERNATIVE ALT
		inner join TABELLAMACCHINE MAC on MAC.CODICE=ALT.CODMACCHINA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMACCHINEALTERNATIVE] TO [Metodo98]
    AS [dbo];

