  
CREATE VIEW VISTACLIENTI AS
        SELECT AC.TIPOCONTO, AC.CODCONTO, AC.DSCCONTO1, AC.DSCCONTO2, AC.CODMASTRO, 
        AC.INDIRIZZO, AC.CAP, AC.LOCALITA, AC.PROVINCIA, AC.TELEFONO, AC.FAX, AC.TELEX, 
        AC.CODFISCALE, AC.PARTITAIVA, AC.CODIDENTIVAESTERO, AC.CODNAZIONE, AC.CODICEISO, AC.CODLINGUA,AC.CODREGIONE, AC.NOTE, 
        AC.UTENTEMODIFICA, AC.DATAMODIFICA, AC.FLGBLACKLIST,AC.FLGELENCOCF, AC.FLGDOGANA, RC.ESERCIZIO, RC.CODSETTORE, RC.CODZONA, 
        RC.CODCATEGORIA, RC.CODSPED, RC.PRCTRASPORTO, RC.INOLTROTRASP, RC.CODPAG, 
        RC.MESEESCL1, RC.GGESCL1, RC.MESEESCL2, RC.GGESCL2, 
        (SELECT CAB FROM BANCAAPPCF WHERE CODCONTO=RC.CODCONTO AND CODICE=BANCAANAGR) AS CAB, 
        (SELECT ABI FROM BANCAAPPCF WHERE CODCONTO=RC.CODCONTO AND CODICE=BANCAANAGR) AS ABI, 
        RC.CODBANCA, 
        RC.BANCAANAGR, RC.CODAGENTE1, RC.CODAGENTE2, RC.CODAGENTE3, RC.PROVV1, RC.PROVV2, 
        RC.PROVV3, RC.SCONTO1, RC.CODIVA, RC.DICHESIVA, RC.LISTINO, RC.CODCAMBIO, 
        RC.DESTDIVMERCI, RC.DESTDIVDOCUMENTI, RC.SPESEDOCUM, RC.SPESEEFFETTO, 
        RC.SPESETRASPORTO, RC.SPESEIMBALLO, RC.FIDO, RC.FIDOEURO, RC.PORTO, 
        RC.TRASPACURA, RC.APPLSCONTORIGA, RC.APPLSCONTOFINALE, RC.CODCONTOFATT, 
        RC.FATTFINEMESE, RC.NONRAGGRUPPDOC, RC.CODDEPOSITO, 
        RC.CODDEPOSITOCOLL, RC.CODDEPCOMP, RC.CODDEPCOMPCOLL, RC.RIVIVAOMAGGI, 
        RC.NRCONTROPCONT, RC.USAPRZPRVPART, RC.CCDEBITORE, RC.CODDEBITORE, RC.NOTE1,
        RC.STATOCONTABILITA, RC.STATOMAGAZZINO,RC.STATOORDINI, RC.STATOBOLLE, RC.STATOFATTURE, RC.STATONOTEACCREDITO, RC.STATOALTRO,
        RC.CODGRUPPOPREZZIPART, RC.CODGRUPPOPROVPART,RC.RAGGSCADENZE,RC.PROGDICHINTENTO,RC.SPLITPAYMENT
        FROM ANAGRAFICACF AC, ANAGRAFICARISERVATICF RC
        WHERE ( AC.CODCONTO = RC.CODCONTO ) AND RC.ESERCIZIO = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25))) AND AC.TIPOCONTO = 'C'
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACLIENTI] TO [Metodo98]
    AS [dbo];

