
CREATE VIEW [dbo].[VISTA_TRASPORTO_SPEDIZ_SERVIZI]
AS

	SELECT  
		TTVA.CODSPEDIZ AS CODICE,
		TS.RAGIONESOCIALE
	FROM 
		TRASPORTO_CAD AS TTVA,
		TABSPEDIZ TS
	WHERE
		TTVA.TIPO IN(0,2) AND
		TS.CODICE = TTVA.CODSPEDIZ
	GROUP BY
		CODSPEDIZ,
		RAGIONESOCIALE


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_TRASPORTO_SPEDIZ_SERVIZI] TO [Metodo98]
    AS [dbo];

