CREATE VIEW [dbo].[Vista_MYTHO_Articoli_TMP]
As 
SELECT ISNULL([ItemSKU], RIF.SKU) [ItemSKU]
	  ,[ProductEntityId]
      ,[CreationDate]
      ,[ExecutedDate]
      ,[ParentItemID]
      ,[ParentItemSKU]
      ,[ProductLanguage]
      ,[ProductType]
      ,[AdditionalImagesHeight]
      ,[AdditionalImagesThumbnailChangeMode]
      ,[AdditionalImagesThumbnailWidth]
      ,[AdditionalImagesWidth]
      ,[AdditionalImagesZoomHeight]
      ,[AdditionalImagesZoomPosition]
      ,[AdditionalImagesZoomWidth]
      ,[BigImageFileName]
      ,[BrandName]
      ,[BrandOxID]
      ,[CanonicalURLCustomizedContent]
      ,[Category1Name]
      ,[Category1OxId]
      ,[Category1Language]
      ,[Category1ParentOxId]
      ,[Category2Name]
      ,[Category2OxId]
      ,[Category2Language]
      ,[Category2ParentOxId]
      ,[Category3Name]
      ,[Category3OxId]
      ,[Category3Language]
      ,[Category3ParentOxId]
      ,[Cost]
      ,[DaysToShip]
      ,[Description]
      ,[DimensionHeight]
      ,[DimensionLength]
      ,[DimensionWidth]
      ,[DiscountGridCode]
      ,[EANCode]
      ,[EcotaxTI]
      ,[Guarantee]
      ,[HandlingSurcharge1ST]
      ,[HandlingSurchargeOthers]
      ,[ItemCondition]
      ,[LinkedItemID]
      ,[LinkedItemLanguage]
      ,[LinkedItemSKU]
      ,[LinkedUpdating]
      ,[LongDescription]
      ,[MetaDescription]
      ,[MetaKeywords]
      ,[MetaTitle]
      ,[MPN]
      ,[Name]
      ,[OptionIsDefault]
      ,[OptionTypes1OxId]
      ,[OptionTypes1Name]
      ,[OptionTypes1SystemName]
      ,[OptionTypes2OxId]
      ,[OptionTypes2Name]
      ,[OptionTypes2SystemName]
      ,[OptionTypes3OxId]
      ,[OptionTypes3Name]
      ,[OptionTypes3SystemName]
      ,[OptionValues1OxId]
      ,[OptionValues1Code]
      ,[OptionValues1Name]
      ,[OptionValues2OxId]
      ,[OptionValues2Code]
      ,[OptionValues2Name]
      ,[OptionValues3OxId]
      ,[OptionValues3Code]
      ,[OptionValues3Name]
      ,[Position]
      ,[PriceValue]
      ,[PriceVATIncluded]
      ,[Price1Value]
      ,[Price1VATIncluded]
      ,[Price2Value]
      ,[Price2VATIncluded]
      ,[Price3Value]
      ,[Price3VATIncluded]
      ,[Price4Value]
      ,[Price4VATIncluded]
      ,[ReviewCount]
      ,[ReviewRating]
      ,[QuantityInstockValue]
      ,[QuantityInstockAppend]
      ,[QuantityReorderValue]
      ,[QuantityReorderAppend]
      ,[SaleIfOutOfStock]
      ,[SaleIfOutOfStockScenario]
      ,[ShipPrice]
      ,[ShowDaysToship]
      ,[ShowIfOutOfStock]
      ,[ShowInStockNote]
      ,[ShowStockLevel]
      ,[SmallImgFileName]
      ,[StrikethroughPriceValue]
      ,[StrikethroughPriceVATIncluded]
      ,[StrikethroughPrice1Value]
      ,[StrikethroughPrice1VATIncluded]
      ,[StrikethroughPrice2Value]
      ,[StrikethroughPrice2VATIncluded]
      ,[StrikethroughPrice3Value]
      ,[StrikethroughPrice3VATIncluded]
      ,[StrikethroughPrice4Value]
      ,[StrikethroughPrice4VATIncluded]
      ,[TaxCountryISOCode]
      ,[TaxRate]
      ,[UnitsForSale]
      ,[UnitsForSale1]
      ,[UnitsForSale2]
      ,[UnitsForSale3]
      ,[UnitsForSale4]
      ,[Visible]
      ,[Weight]

  FROM [dbo].[MYTHO_Articoli_TMP] 

  /* Implementare giacenze
  
  /****** Script per comando SelectTopNRows da SSMS  ******/
SELECT TOP 1000 [CODART]
      ,[CODDEPOSITO]
      ,[CODUBICAZIONE]
      ,[NRIFPARTITA]
      ,[ESERCIZIO]
      ,(CARICO - SCARICO + RESODASCARICO - RESODACARICO)  AS GIACENZA
      ,(CARICO - SCARICO + RESODASCARICO - RESODACARICO + ORDINATO - IMPEGNATO) AS DISPONIBILITA
  FROM [Test_Embyon_1620].[dbo].[VISTAGIACENZETOT]
  Where ESERCIZIO = YEAR(getdate())

  
  
  */
  LEFT OUTER JOIN [MYTHO_Codici_Articoli] RIF
  ON RIF.CODICEMETODO = [MYTHO_Articoli_TMP].CODICEMETODO
  WHERE Enabled= 1

GO
GRANT SELECT
    ON OBJECT::[dbo].[Vista_MYTHO_Articoli_TMP] TO [Metodo98]
    AS [dbo];

