
CREATE VIEW VISTADESTINAZIONIDDIV AS
       SELECT DDIV.CODCONTO,DDIV.CODICE AS NUMERO,DDIV.RAGIONESOCIALE,'' AS RAGIONESOCIALE2,DDIV.INDIRIZZO,DDIV.CAP,DDIV.LOCALITA,DDIV.PROVINCIA,
       VCF.BANCAANAGR,VCF.ABI,VCF.CAB,VCF.ABI+'/'+VCF.CAB AS CABABI,DDIV.FAX,DDIV.TELEFONO
       FROM DESTINAZIONIDIVERSE DDIV, VISTACLIFOR VCF WHERE VCF.CODCONTO=DDIV.CODCONTO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTADESTINAZIONIDDIV] TO [Metodo98]
    AS [dbo];

