CREATE VIEW VISTAIMPOSTAZIONIRIGHEDOC AS
SELECT DISTINCT NOMEIMPOSTAZIONE, 
        (CASE WHEN NOMEUTENTE='TRM' THEN 'SI' ELSE 'NO' END)  IMPCOMUNE,
        TIPORIGA,
        NOMEUTENTE,
        PREDEFINITA,
        (CASE WHEN PREDEFINITA<>0 THEN 'SI' ELSE 'NO' END)  IMPPREDEFINITA
FROM IMPRIGHEDOC

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAIMPOSTAZIONIRIGHEDOC] TO [Metodo98]
    AS [dbo];

