CREATE VIEW VISTASCHEDATRASPORTO AS
SELECT 
	TR.PROGRESSIVODOC,
	TR.DICHIARAZIONI,
	TR.COMPILATORE,
	TR.LUOGOEMISSIONE,
	TR.DATAEMISSIONE,
	TR.LUOGOCARICO,
	TR.LUOGOSCARICO,
	TR.ISTRUZIONI,
	TR.TIPOLOGIA,
	RITR.POSIZIONE,
	RITR.CODCCONTO,
	RITR.RAGSOC,
	RITR.INDIRIZZO,
	RITR.CAP,
	RITR.LOCALITA,
	RITR.PROVINCIA,
	RITR.TELEFONO,
	RITR.EMAIL,
	RITR.CODNAZIONE,
	RITR.PARTITAIVA,
	AC.CODFISCALE
FROM 
	(SCHEDATRASPORTO TR INNER JOIN SCHEDATRASPORTORIGHE RITR ON TR.PROGRESSIVODOC=RITR.PROGRESSIVODOC)
	LEFT OUTER JOIN ANAGRAFICACF AC ON AC.CODCONTO=RITR.CODCCONTO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASCHEDATRASPORTO] TO [Metodo98]
    AS [dbo];

