CREATE VIEW VISTARIEPILOGOCCSTRUTT AS
SELECT 
	IDRECORD+CAST(ISNULL(VA.PROGRESSIVO,0) AS VARCHAR) AS IDRECORDV,
	VA.CODLIV AS CODNODO,
	VA.CODLIVELLO,
	VA.TIPONODO,
	VA.LIVPADRE,
	ISNULL(VA.PERCRIPARTIZIONE,100) AS PRC,
	ISNULL(VA.NRRIGASTRUTT,1) AS NRRIGASTRUTT,
	ISNULL(VA.NRRIGASTRUTTPADRE,1) AS NRRIGASTRUTTPADRE,
	VA.RIFRIGAPREV,
	VA.DESCRIZIONE,
	VA.TIPORIP,
	VA.DECRIPQTA,
	VA.DECRIPVALORE,
	(CASE NATURARILEVAZIONE WHEN 1 THEN (VR.CONSUNTIVATOTOT*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) CONSUNTIVATORIP,
	(CASE NATURARILEVAZIONE WHEN 2 THEN (VR.RISERVATOTOT*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) RISERVATORIP,
	(CASE NATURARILEVAZIONE WHEN 3 THEN (VR.ORDINATOTOT*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) ORDINATORIP,
	(CASE NATURARILEVAZIONE WHEN 4 THEN (VR.PREVISTOTOT*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) PREVISTORIP,	
	(VR.COSTOTOTLIRE*ISNULL(VA.PERCRIPARTIZIONE,100)/100) COSTOTOTRIP,
	(CASE NATURARILEVAZIONE WHEN 1 THEN (VR.CONSUNTIVATOTOTEURO*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) CONSUNTIVATORIPEURO,
	(CASE NATURARILEVAZIONE WHEN 2 THEN (VR.RISERVATOTOTEURO*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) RISERVATORIPEURO,
	(CASE NATURARILEVAZIONE WHEN 3 THEN (VR.ORDINATOTOTEURO*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) ORDINATORIPEURO,
	(CASE NATURARILEVAZIONE WHEN 4 THEN (VR.PREVISTOTOTEURO*ISNULL(VA.PERCRIPARTIZIONE,100)/100) ELSE 0 END) PREVISTORIPEURO,
	(VR.COSTOTOTEURO*ISNULL(VA.PERCRIPARTIZIONE,100)/100) COSTOTOTRIPEURO,
	VR.*
FROM 
	VISTARIEPILOGOCONSCOMM VR LEFT JOIN VISTAASSEGNAZIONICONSCOMM VA 
	ON (VR.RIFTESTA = VA.IDTESTA) AND (VR.RIFRIGA = VA.IDRIGA) AND 
	(VR.ORIGINEEVENTO = VA.ORIGINEEVENTO) AND (VR.RIFCOMM = VA.RIFCOMMCLI) 
WHERE
	VR.TIPOREC NOT IN ('K','N')

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARIEPILOGOCCSTRUTT] TO [Metodo98]
    AS [dbo];

