

CREATE VIEW VISTATESTECONTRATTIGRPACQ
AS
SELECT     CONTRATTI_TESTECONSUNTIVGRUPPIACQ.PROGRESSIVO, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR, 
                      ANAGRAFICACF.DSCCONTO1, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ESERCIZIO, CONTRATTI_VINCOLIESERCIZIOFOR.DADATA, 
                      CONTRATTI_VINCOLIESERCIZIOFOR.ADATA, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE, 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO, 
                      ANAGRAFICAARTICOLI.DESCRIZIONE
FROM         CONTRATTI_TESTECONSUNTIVGRUPPIACQ INNER JOIN
                      ANAGRAFICACF ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR = ANAGRAFICACF.CODCONTO INNER JOIN
                      ANAGRAFICAARTICOLI ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = ANAGRAFICAARTICOLI.CODICE LEFT OUTER JOIN
                      CONTRATTI_VINCOLIESERCIZIOFOR ON 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO = CONTRATTI_VINCOLIESERCIZIOFOR.ESERCIZIO AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR = CONTRATTI_VINCOLIESERCIZIOFOR.CODCONTO


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTATESTECONTRATTIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTATESTECONTRATTIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTATESTECONTRATTIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTECONTRATTIGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTATESTECONTRATTIGRPACQ] TO [Metodo98]
    AS [dbo];

