
CREATE VIEW VISTAPLAFONDDICHINTFATT AS
SELECT 
   0 AS TIPOTF, TC.IDTESTADOC,
   RI.TIPOREGISTRO, RI.ESERCIZIO, RI.NRREG, RI.NRRIGA, RI.POSIZIONE, RI.DATADOC, RI.NUMDOC, RI.CODIVA, RI.ALIQUOTA,
   RI.IMPONIBILE, RI.IMPOSTA, RI.IMPONIBILEEURO, RI.IMPOSTAEURO, RI.CODCAMBIO, RI.VALORECAMBIO, RI.CONTO, RI.DATASTAMPA, RI.NOTAACCR,
   RI.MESELIQUIDAZ, RI.ANNOLIQUIDAZ, RI.UTENTEMODIFICA, RI.DATAMODIFICA, RI.IMPONIBILEVALUTA, RI.IMPOSTAVALUTA,
   RI.NUMPROTORIGSOSP, RI.ANNODOCORIGSOSP, RI.RIFSCADRIGSOSP,
   TC.MESEPLAFOND, TC.ANNOPLAFOND, TC.PROGDICHINTENTO,
   (SELECT REVOCA FROM DICHIARAZIONEINTENTO WHERE PROGRESSIVO=TC.PROGDICHINTENTO) AS REVOCA
FROM RIGHEIVA RI
   INNER JOIN TESTECONTABILITA TC ON RI.NRREG=TC.PROGRESSIVO
UNION ALL
SELECT 
   1 AS TIPOTF, TC.IDTESTADOC,
   RI.TIPOREGISTRO, RI.ESERCIZIO, RI.NRREG, RI.NRRIGA, RI.POSIZIONE, RI.DATADOC, RI.NUMDOC, RI.CODIVA, RI.ALIQUOTA,
   RI.IMPONIBILE, RI.IMPOSTA, RI.IMPONIBILEEURO, RI.IMPOSTAEURO, RI.CODCAMBIO, RI.VALORECAMBIO, RI.CONTO, RI.DATASTAMPA, RI.NOTAACCR,
   RI.MESELIQUIDAZ, RI.ANNOLIQUIDAZ, RI.UTENTEMODIFICA, RI.DATAMODIFICA, RI.IMPONIBILEVALUTA, RI.IMPOSTAVALUTA,
   RI.NUMPROTORIGSOSP, RI.ANNODOCORIGSOSP, RI.RIFSCADRIGSOSP,
   TC.MESEPLAFOND, TC.ANNOPLAFOND, TC.PROGDICHINTENTO,
   (SELECT REVOCA FROM DICHIARAZIONEINTENTO WHERE PROGRESSIVO=TC.PROGDICHINTENTO) AS REVOCA
FROM RIGHEIVATF RI
   INNER JOIN TESTECONTABILITATF TC ON RI.NRREG=TC.PROGRESSIVO
   

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPLAFONDDICHINTFATT] TO [Metodo98]
    AS [dbo];

