CREATE VIEW VISTARIGHEDISTINCASSI AS
SELECT RD.*,
   (RD.IMPORTOSCADEURO-RD.INCASSATOEURO) AS DIFFINCASSATO,
   VS.ESITO,VS.DSCESITO,VS.CODCAMBIO,VS.VALCAMBIO,VS.BANCAINC
FROM (RIGHEDISTINTAINCASSI RD LEFT OUTER JOIN VISTASCADENZE VS ON RD.PROGRESSIVOSCAD=VS.PROGRESSIVO)   

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARIGHEDISTINCASSI] TO [Metodo98]
    AS [dbo];

