
CREATE VIEW VISTATESTEPREVENTIVOCC AS
SELECT 
    PROGRESSIVO,
    ESERCIZIO,
    TIPO,
    NUMERO,
    REVISIONE,
    (SELECT DESCRIZIONE FROM TABREVISIONICOMMCLI WHERE CODICE=REVISIONE) AS DSCREVISIONE,
    RIFERIMENTO,
    STATO,
    OGGETTO,
    CODCLIENTE,
    CLIENTEFATT,
    RIFCOMMESSA,
    RIFSTRUTTURA,
    DATAFINE,
    NRLIVELLISTRUTT,
    CODICECONFIGURATO,
    FILESCRIPT_DATACOSTI,
    DATARIFPREZZIPART,
    DOCOFFERTA,
    DATAOFFERTAWORD,
    NOTE,
    EDIT_STATE,
    EDIT_USER,
    UTENTEMODIFICA,
    DATAMODIFICA
FROM
    TESTEFOGLICOMMCLI

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTEPREVENTIVOCC] TO [Metodo98]
    AS [dbo];

