CREATE VIEW VISTAPARTITECONTABILITA
  AS SELECT RC.NRREG,
    RC.NRRIGA,
    TC.PROGRESSIVO,
    TC.ESERCIZIO,
    TC.PROVVISORIO,
    RC.DATAREG,
    RC.DATARIF,
    TC.NRRIFER,
    TC.MOVIVA,
    TC.CAUSALE,
    TC.MESEPLAFOND,
    TC.DESCRIZIONE,
    TC.APPUNTI,
    TC.TOTDOCLIRE,
    TC.TOTDOCVALUTA,
    TC.TOTDOCEURO,
    TC.NRGIORNALE,
    TC.IDTESTADOC,
    RC.NRRIF,
    RC.NRPARTITA,
    RC.CONTO,
    RC.SEGNO,
    RC.IMPORTO,
    RC.IMPORTOVALUTA,
    RC.IMPORTOEURO,
    RC.VALORECAMBIO,
    RC.DESCRIZIONE AS DESCRIZIONERIGHE,
    RC.DATAVALUTA,
    RC.CPARTITA,
    RC.RIGACAUSALE,
    RC.CODCOMMESSA,
    RC.CODCAMBIO,
    (CASE WHEN RC.SEGNO=0 THEN RC.IMPORTO ELSE 0 END) AS DARE,
    (CASE WHEN RC.SEGNO=0 THEN RC.IMPORTOEURO ELSE 0 END) AS DAREEURO,
    (CASE WHEN RC.SEGNO=0 THEN RC.IMPORTOVALUTA ELSE 0 END) AS DAREVALUTA,
    (CASE WHEN RC.SEGNO=1 THEN RC.IMPORTO ELSE 0 END) AS AVERE,
    (CASE WHEN RC.SEGNO=1 THEN RC.IMPORTOEURO ELSE 0 END) AS AVEREEURO,
    (CASE WHEN RC.SEGNO=1 THEN RC.IMPORTOVALUTA ELSE 0 END) AS AVEREVALUTA,
    (SELECT SALDOLIRE FROM VISTASALDIPARTITECONT VP WHERE RC.CONTO=VP.CONTO AND RC.NRPARTITA=VP.NRPARTITA AND TC.PROVVISORIO=VP.PROVVISORIO) AS SALDOLIRE,
    (SELECT SALDOEURO FROM VISTASALDIPARTITECONT VP WHERE RC.CONTO=VP.CONTO AND RC.NRPARTITA=VP.NRPARTITA AND TC.PROVVISORIO=VP.PROVVISORIO) AS SALDOEURO,
    (SELECT SALDOVALUTA FROM VISTASALDIPARTITECONT VP WHERE RC.CONTO=VP.CONTO AND RC.NRPARTITA=VP.NRPARTITA AND TC.PROVVISORIO=VP.PROVVISORIO) AS SALDOVALUTA,
    (SELECT SUM(SALDOLIRE) FROM VISTASALDIPARTITECONT VP WHERE RC.CONTO=VP.CONTO AND RC.NRPARTITA=VP.NRPARTITA AND VP.PROVVISORIO=0) AS SALDOLIREDEF,
    (SELECT SUM(SALDOEURO) FROM VISTASALDIPARTITECONT VP WHERE RC.CONTO=VP.CONTO AND RC.NRPARTITA=VP.NRPARTITA AND VP.PROVVISORIO=0) AS SALDOEURODEF,
    (SELECT SUM(SALDOVALUTA) FROM VISTASALDIPARTITECONT VP WHERE RC.CONTO=VP.CONTO AND RC.NRPARTITA=VP.NRPARTITA AND VP.PROVVISORIO=0) AS SALDOVALUTADEF,
    (CASE WHEN (SELECT NOTAACCRADD FROM CAUSALICONTABILI WHERE CODICECAUSALE=TC.CAUSALE)=0 THEN 1 ELSE -1 END) AS NOTAACCR
    FROM RIGHECONTABILITA AS RC,TESTECONTABILITA AS TC,TABUTENTI
    WHERE 
    	USERDB = CAST(USER_NAME() AS VARCHAR(25)) AND 
    	RC.NRREG=TC.PROGRESSIVO AND
    	(SUPERVISOR = 1 OR (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSICAUSCONT WHERE CODCAUSALE = TC.CAUSALE AND FLAGVISUALIZZA=1)))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPARTITECONTABILITA] TO [Metodo98]
    AS [dbo];

