


CREATE VIEW dbo.VISTATESTE_CONTRATTI_CF
AS
SELECT     PROGRESSIVO, CODICE
FROM         dbo.TESTE_CONTRATTI
WHERE     (TIPONODO <> 3) AND (TIPONODO <> 5) AND (TIPONODO <> 0)


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTATESTE_CONTRATTI_CF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTATESTE_CONTRATTI_CF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTATESTE_CONTRATTI_CF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTE_CONTRATTI_CF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTATESTE_CONTRATTI_CF] TO [Metodo98]
    AS [dbo];

