CREATE VIEW VISTASTORICOAVANZAMENTICOMMCLI AS
SELECT
	BL.IDTESTACOMM,BL.ESERCIZIO AS ANNOCOM,BL.TIPOCOM,BL.NUMEROCOM,
	BL.IDRIGACOMM,BL.CODICEORD,BL.PROGRESSIVO IDTESTACICLO,BL.CODART,BL.DESCRIZIONEART,
	BL.VERSIONECICLO,BL.DSCVERSIONE,BL.VALIDITACICLO,BL.VERSIONEDBA,
	BL.CICLOSTANDARD,BL.TIPOCICLO,BL.NUMEROFASE,BL.TIPOFASE,BL.OPERAZIONE,
	BL.MACCHINA,BL.CDLAVORO,BL.QTAPREVISTA,BL.UMFASE AS UMPREV, BL.RIFCOMMCLI,BL.DATAEMISSIONE,
	SR.PROGRESSIVO,SR.RIFMOVPRINCIPALE,SR.DATAMOV,SR.CODCAUSALE,SR.ANNOBOLLA,SR.NUMEROBOLLA,
	SR.ESERCIZIO,SR.TIPOMOVIMENTO,SR.CDLAVORO AS CDLAVOROMOV,SR.MACCHINA AS MACCHINAMOV,
	(SELECT REPARTO FROM TABELLACDLAVORO WHERE CODICE=SR.CDLAVORO) AS CODREPARTO,
	(CASE SGNSETUP WHEN -1 THEN ABS(SR.COSTOSETUP)*SGNSETUP ELSE SR.COSTOSETUP END) AS COSTOSETUP,
	(CASE SGNCOSTOSETUP WHEN -1 THEN ABS(SR.COSTOSETUPAGG)*SGNCOSTOSETUP ELSE SR.COSTOSETUPAGG END) AS COSTOSETUPAGG,
	(CASE SGNSETUP WHEN -1 THEN ABS(SR.COSTOSETUPEURO)*SGNSETUP ELSE SR.COSTOSETUPEURO END) AS COSTOSETUPEURO,
	(CASE SGNCOSTOSETUP WHEN -1 THEN ABS(SR.COSTOSETUPAGGEURO)*SGNCOSTOSETUP ELSE SR.COSTOSETUPAGGEURO END) AS COSTOSETUPAGGEURO,
	(CASE SGNMACCHINA WHEN -1 THEN ABS(SR.COSTOMACCHINA)*SGNMACCHINA ELSE SR.COSTOMACCHINA END) AS COSTOMACCHINA,
	(CASE SGNCOSTOMACCHINA WHEN -1 THEN ABS(SR.COSTOMACCHINAAGG)*SGNCOSTOMACCHINA ELSE SR.COSTOMACCHINAAGG END) AS COSTOMACCHINAAGG,
	(CASE SGNMACCHINA WHEN -1 THEN ABS(SR.COSTOMACCHINAEURO)*SGNMACCHINA ELSE SR.COSTOMACCHINAEURO END) AS COSTOMACCHINAEURO,
	(CASE SGNCOSTOMACCHINA WHEN -1 THEN ABS(SR.COSTOMACCHINAAGGEURO)*SGNCOSTOMACCHINA ELSE SR.COSTOMACCHINAAGGEURO END) AS COSTOMACCHINAAGGEURO,
	(CASE SGNUOMO WHEN -1 THEN ABS(SR.COSTOUOMO)*SGNUOMO ELSE SR.COSTOUOMO END) AS COSTOUOMO,
	(CASE SGNCOSTOUOMO WHEN -1 THEN ABS(SR.COSTOUOMOAGG)*SGNCOSTOUOMO ELSE SR.COSTOUOMOAGG END) AS COSTOUOMOAGG,
	(CASE SGNUOMO WHEN -1 THEN ABS(SR.COSTOUOMOEURO)*SGNUOMO ELSE SR.COSTOUOMOEURO END) AS COSTOUOMOEURO,
	(CASE SGNCOSTOUOMO WHEN -1 THEN ABS(SR.COSTOUOMOAGGEURO)*SGNCOSTOUOMO ELSE SR.COSTOUOMOAGGEURO END) AS COSTOUOMOAGGEURO,
	(CASE SGNDURATA WHEN -1 THEN ABS(SR.COSTOINDIRETTO)*SGNDURATA ELSE SR.COSTOINDIRETTO END) AS COSTOINDIRETTO,
	(CASE SGNCOSTOINDIRETTO WHEN -1 THEN ABS(SR.COSTOINDIRETTOAGG)*SGNCOSTOINDIRETTO ELSE SR.COSTOINDIRETTOAGG END) AS COSTOINDIRETTOAGG,
	(CASE SGNSETUP WHEN -1 THEN ABS(SR.COSTOINDIRETTOEURO)*SGNSETUP ELSE (CASE SGNMACCHINA WHEN -1 THEN ABS(SR.COSTOINDIRETTOEURO)*SGNMACCHINA ELSE (CASE SGNUOMO WHEN -1 THEN ABS(SR.COSTOINDIRETTOEURO)*SGNUOMO ELSE SR.COSTOINDIRETTOEURO END) END) END) AS COSTOINDIRETTOEURO,
	(CASE SGNCOSTOINDIRETTO WHEN -1 THEN ABS(SR.COSTOINDIRETTOAGGEURO)*SGNCOSTOINDIRETTO ELSE SR.COSTOINDIRETTOAGGEURO END) AS COSTOINDIRETTOAGGEURO,
	ORESETUP,
	OREMACCHINA,
	OREUOMO,
	OREDURATA,	
	(CASE SGNQTAVERSATA WHEN -1 THEN SR.QTAVERSATA*SGNQTAVERSATA ELSE SR.QTAVERSATA END) AS QTAVERSATA,
	SR.UM,SR.UMFASE,
	SR.STATOOPERAZIONE,SR.TIPOBOLLA,
	SR.RIFTESTADOCUMENTO,SR.RIFRIGADOCUMENTO,
	TC.SGNSETUP,
	TC.SGNMACCHINA,
	TC.SGNUOMO,
	TC.SGNDURATA,
	TC.SGNCOSTOSETUP,
	TC.SGNCOSTOMACCHINA,
	TC.SGNCOSTOUOMO,
	TC.SGNCOSTOINDIRETTO,
	TC.SGNQTAVERSATA,
	SR.DATAMODIFICA
FROM
	(STORICOAVANZAMENTI SR LEFT OUTER JOIN VISTABOLLELAVORAZIONE BL ON
	SR.ANNOBOLLA=BL.ANNOBOLLA AND SR.NUMEROBOLLA=BL.NUMEROBOLLA)
	INNER JOIN TABCAUSALIAVANZAMENTO TC ON SR.CODCAUSALE=TC.CODICE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOAVANZAMENTICOMMCLI] TO [Metodo98]
    AS [dbo];

