CREATE VIEW VISTASTORICOPREZZIUM
AS
SELECT STORICOPREZZIARTICOLO.TIPOPREZZO, 
    STORICOPREZZIARTICOLO.DATA, 
    STORICOPREZZIARTICOLO.CODARTICOLO, 
    STORICOPREZZIARTICOLO.ULTIMO, 
    STORICOPREZZIARTICOLO.CODCLIFOR, 
    STORICOPREZZIARTICOLO.UM, 
    STORICOPREZZIARTICOLO.QUANTITA, 
    (CASE WHEN TABVINCOLIGIC.INCLUDISPRIP=0 THEN STORICOPREZZIARTICOLO.PREZZOLIRE ELSE STORICOPREZZIARTICOLO.PREZZOLIRE+STORICOPREZZIARTICOLO.SPESERIPMAGLIRE END) AS PREZZOLIRE,
    (CASE WHEN TABVINCOLIGIC.INCLUDISPRIP=0 THEN STORICOPREZZIARTICOLO.PREZZOEURO ELSE STORICOPREZZIARTICOLO.PREZZOEURO+STORICOPREZZIARTICOLO.SPESERIPMAGEURO END) AS PREZZOEURO,
    STORICOPREZZIARTICOLO.CODPAGAMENTO, 
    VISTAFATTORICONVERSIONE.UMRIC, 
    VISTAFATTORICONVERSIONE.FORMULAFC AS FORMULAFCPRZ,
    VISTAFATTORICONVERSIONE.FATTORE AS FATTOREPRZ
FROM (STORICOPREZZIARTICOLO INNER JOIN
    VISTAFATTORICONVERSIONE ON 
    STORICOPREZZIARTICOLO.CODARTICOLO = VISTAFATTORICONVERSIONE.CODART AND 
    STORICOPREZZIARTICOLO.UM = VISTAFATTORICONVERSIONE.UMJOIN), TABUTENTI, TABVINCOLIGIC 
WHERE
    TABUTENTI.USERDB = CAST(USER_NAME() AS VARCHAR(25)) 	
    AND TABVINCOLIGIC.ESERCIZIO=TABUTENTI.ESERCIZIOATTIVO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOPREZZIUM] TO [Metodo98]
    AS [dbo];

