
CREATE VIEW VISTAVINCOLIDOCCC AS
        SELECT DISTINCT CODDOC,CODGENERICO,DSCCONTO1
        FROM PARDOCCC, ANAGRAFICAGENERICI WHERE CODCONTO=CODGENERICO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAVINCOLIDOCCC] TO [Metodo98]
    AS [dbo];

