CREATE VIEW VISTAVINCOLIDOCVF AS
        SELECT CODDOC,CODGENERICO,DSCCONTO1
        FROM PARDOCVF LEFT OUTER JOIN ANAGRAFICAGENERICI ON ANAGRAFICAGENERICI.CODCONTO=PARDOCVF.CODGENERICO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAVINCOLIDOCVF] TO [Metodo98]
    AS [dbo];

