create view VISTAOPERAIPROGPROD as
select 
	NOMEPIANIF,
	PROG_ID,FASE_ID,
	TIPO,
	MACCHINA,
	MACCHINA + ' - ' + DSCMACCHINA as DSCMACCHINA,
	dateadd(day, NUM.NUMERO-1,DATAINIZIO) as DATA,
	NUMEROOPERAI,
	DATAINIZIO,DATAFINE,
	DATAFINECICLO,DATAFABBISOGNO
from 
	VISTASITUAZIONEFASI PROG 
		inner join NUMERI NUM on NUM.NUMERO<=datediff(day,DATAINIZIO,DATAFINE)+1

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAOPERAIPROGPROD] TO [Metodo98]
    AS [dbo];

