CREATE VIEW VISTARESOCONTOVENDITE
AS
SELECT STORICOMAG.PROGRESSIVO, STORICOMAG.DATAMOV, 
    STORICOMAG.CODART, ARTICOLIUMPREFERITE1.UM, 
    STORICOMAG.QTA1UM, STORICOMAG.IMPORTOTOTNETTO, 
    STORICOMAG.IMPORTOTOTNETTO - STORICOMAG.IMPORTOTOTNETTO
     * ISNULL(TRATTAMENTOIVA.ALIQUOTA, 0) 
    / 100 AS IMPORSINEIVA, 
    STORICOMAG.IMPORTOTOTNETTOEURO, 
    STORICOMAG.IMPORTOTOTNETTOEURO - STORICOMAG.IMPORTOTOTNETTOEURO
     * ISNULL(TRATTAMENTOIVA.ALIQUOTA, 0) 
    / 100 AS IMPOREUROSINEIVA, TABGRUPPI.CODICE, 
    TABGRUPPI.DESCRIZIONE, TRATTAMENTOIVA.ALIQUOTA, 
    STORICOMAG.CODCLIFOR, 
    STORICOMAG.ESERCIZIO AS MAGESERCIZIO, 
    ANAGRAFICAARTICOLICOMM.ESERCIZIO AS COMMESERCIZIO
FROM TP_ParVBanco INNER JOIN
    ARTICOLIUMPREFERITE ARTICOLIUMPREFERITE1 ON 
    TP_ParVBanco.TipoUM = ARTICOLIUMPREFERITE1.TIPOUM RIGHT
     OUTER JOIN
    STORICOMAG INNER JOIN
    ANAGRAFICAARTICOLI ON 
    STORICOMAG.CODART = ANAGRAFICAARTICOLI.CODICE INNER JOIN
    TABGRUPPI ON 
    ANAGRAFICAARTICOLI.GRUPPO = TABGRUPPI.CODICE ON 
    ARTICOLIUMPREFERITE1.CODART = ANAGRAFICAARTICOLI.CODICE
     LEFT OUTER JOIN
    TRATTAMENTOIVA RIGHT OUTER JOIN
    ANAGRAFICAARTICOLICOMM ON 
    TRATTAMENTOIVA.CODICE = ANAGRAFICAARTICOLICOMM.CODIVA
     ON 
    ANAGRAFICAARTICOLI.CODICE = ANAGRAFICAARTICOLICOMM.CODICEART
WHERE (STORICOMAG.CODCLIFOR LIKE 'C%')



GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTARESOCONTOVENDITE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTARESOCONTOVENDITE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTARESOCONTOVENDITE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTARESOCONTOVENDITE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTARESOCONTOVENDITE] TO [Metodo98]
    AS [dbo];

