CREATE VIEW VISTAQTACONSUMATECLAV AS
SELECT SUM(QTA1UMCONSUMATA) AS QTACONSUMATA,IDTESTA_CONSCL,IDRIGA_CONSCL,
(SELECT CODART FROM RIGHEDOCUMENTI WHERE IDTESTA=IDTESTA_CONSCL AND IDRIGA=IDRIGA_CONSCL) AS CODICEART,
(SELECT DATADOC FROM TESTEDOCUMENTI WHERE PROGRESSIVO=IDTESTA_CONSCL) AS DATADOC
FROM CONSUMICLAVORAZIONE  
GROUP BY IDTESTA_CONSCL,IDRIGA_CONSCL

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAQTACONSUMATECLAV] TO [Metodo98]
    AS [dbo];

