CREATE VIEW VISTASTORICOMOVPROD AS 
SELECT STORICOMOVPROD.PROGRESSIVO, 
		STORICOMOVPROD.RIFTESTA, STORICOMOVPROD.DATAMOV, 
		STORICOMOVPROD.TIPOMOV, STORICOMOVPROD.NOTE, STORICOMOVPROD.STATOMOV,
		TESTEORDINIPROD.ESERCIZIO, TESTEORDINIPROD.TIPOCOM, TESTEORDINIPROD.NUMEROCOM, 
		TESTEORDINIPROD.DATAEMISSIONE, TESTEORDINIPROD.CODCLIENTE, TESTEORDINIPROD.ANNOTAZIONI, 
		TESTEORDINIPROD.STATOCHIUSO, TESTEORDINIPROD.STATOBLOCCATO
	FROM STORICOMOVPROD INNER JOIN TESTEORDINIPROD ON STORICOMOVPROD.RIFTESTA = TESTEORDINIPROD.PROGRESSIVO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASTORICOMOVPROD] TO [Metodo98]
    AS [dbo];

