create view VISTAORDINIDAEVADEREPROGPROD as
	select 
		RD.IDTESTA, RD.IDRIGA,
		TD.TIPODOC,
		TD.TIPODOC + '\' + cast(TD.ESERCIZIO as varchar) + '\' + cast(TD.NUMERODOC as varchar) + '\' + TD.BIS as RIFDOCUMENTO,
		TD.DATADOC,
		TD.CODCLIFOR,				
		(select DSCCONTO1 from ANAGRAFICACF CF where CF.CODCONTO=TD.CODCLIFOR) as RAGSOCCLIFOR,
		RD.CODART,RD.DESCRIZIONEART,
		RD.QTAGESTRES,RD.UMGEST,
		RD.QTA1MAGRES,(select UM from ARTICOLIUMPREFERITE AUM where AUM.CODART=RD.CODART and AUM.TIPOUM=1) as UMMAG,
		RD.DATACONSEGNA,
		datediff(d, GetDate(), RD.DATACONSEGNA) as RITARDO,
		(case when datediff(d, GetDate(), RD.DATACONSEGNA)<0 then
			abs(datediff(d, GetDate(), RD.DATACONSEGNA))
		else
			0
		end) as GIORNIRITARDO,
		RD.VERSIONEDIBA,
		RD.RIFCOMMCLI,
		RD.ANNOTAZIONI,
		RD.DAPIANIFICARE
	from
		TESTEDOCUMENTI TD 
		inner join PARAMETRIDOC PAR on PAR.CODICE=TD.TIPODOC
		inner join RIGHEDOCUMENTI RD on RD.IDTESTA=TD.PROGRESSIVO	
	where
		TD.TIPODOC in (select TIPODOC from VISTATIPIORCDAPIANIFICARE)
		and (PAR.TIPO='O' and PAR.CLIFOR='C')
		and (TD.DOCCHIUSO=0)
		and (RD.CODART<>'' and RD.QTAGESTRES > 0)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAORDINIDAEVADEREPROGPROD] TO [Metodo98]
    AS [dbo];

