CREATE VIEW VISTASCADENZESALDO3 AS 
SELECT
    SC.*,
    (SELECT SUM(SALDO) FROM VISTASALDICONTABILITA WHERE CONTO=SC.CODCLIFOR AND ESERCIZIO>=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))-1 AND PROVVISORIO=0) AS SALDOCONTABILE,
    (SELECT SUM(SALDOEURO) FROM VISTASALDICONTABILITA WHERE CONTO=SC.CODCLIFOR AND ESERCIZIO>=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))-1 AND PROVVISORIO=0) AS SALDOCONTABILEEURO,
    (SELECT SUM(SALDOVALUTA) FROM VISTASALDICONTABILITA WHERE CONTO=SC.CODCLIFOR AND ESERCIZIO>=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))-1 AND PROVVISORIO=0) AS SALDOCONTABILEVALUTA,
    (SELECT SUM(SALDO) FROM VISTASALDICONTABILITA WHERE CONTO=SC.CONTORIFBANCA AND ESERCIZIO>=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))-1 AND PROVVISORIO=0) AS SALDOCONTABILECONTORIF,
    (SELECT SUM(SALDOEURO) FROM VISTASALDICONTABILITA WHERE CONTO=SC.CONTORIFBANCA AND ESERCIZIO>=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))-1 AND PROVVISORIO=0) AS SALDOCONTABILECONTORIFEURO,
    (SELECT SUM(SALDOVALUTA) FROM VISTASALDICONTABILITA WHERE CONTO=SC.CONTORIFBANCA AND ESERCIZIO>=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))-1 AND PROVVISORIO=0) AS SALDOCONTABILECONTORIFVALUTA
FROM
    VISTASCADENZE SC


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASCADENZESALDO3] TO [Metodo98]
    AS [dbo];

