CREATE VIEW VISTATIPIORDCOMM AS
SELECT 
	TOC.CODCOMMESSA, TOC.CODORDINE AS CODICE, POP.DESCRIZIONE 
FROM 
	TABORDINICOMMESSA TOC INNER JOIN PARAMETRIORDPROD POP 
	ON TOC.CODORDINE=POP.CODICE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATIPIORDCOMM] TO [Metodo98]
    AS [dbo];

