CREATE VIEW VISTASALDIPARTITECONT AS
SELECT RCONT.CONTO,RCONT.NRPARTITA,TCONT.PROVVISORIO,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTO ELSE 0 END))-SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTO ELSE 0 END)) AS SALDOLIRE,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOEURO ELSE 0 END))-SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOEURO ELSE 0 END)) AS SALDOEURO,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOVALUTA ELSE 0 END))-SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOVALUTA ELSE 0 END)) AS SALDOVALUTA
    FROM RIGHECONTABILITA AS RCONT,TESTECONTABILITA AS TCONT
    WHERE (RCONT.NRREG=TCONT.PROGRESSIVO) AND TCONT.ESERCIZIO<=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB=USER_NAME())
    GROUP BY RCONT.CONTO,RCONT.NRPARTITA,TCONT.PROVVISORIO
    

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASALDIPARTITECONT] TO [Metodo98]
    AS [dbo];

