

CREATE VIEW VISTAPROMOCONDIZIONIMERCEOLOGICHE
AS
SELECT     ART.RIFPROGRESSIVO, 'ART' AS TIPO, ART.CODICE, TAB.DESCRIZIONE, CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, 
                      DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_ARTICOLO AS ART INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = ART.RIFPROGRESSIVO AND 
                      ART.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE ART.NRRIGA END) INNER JOIN
                      dbo.ANAGRAFICAARTICOLI AS TAB ON TAB.CODICE = ART.CODICE INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = ART.RIFPROGRESSIVO
UNION
SELECT     GRP.RIFPROGRESSIVO, 'GRP' AS TIPO, CAST(GRP.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_GRUPPO AS GRP INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = GRP.RIFPROGRESSIVO AND 
                      GRP.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE GRP.NRRIGA END) INNER JOIN
                      dbo.TABGRUPPI AS TAB ON TAB.CODICE = GRP.CODICE INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = GRP.RIFPROGRESSIVO
UNION
SELECT     CAT.RIFPROGRESSIVO, 'CAT' AS TIPO, CAST(CAT.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_CATEGORIA AS CAT INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = CAT.RIFPROGRESSIVO AND 
                      CAT.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE CAT.NRRIGA END) INNER JOIN
                      dbo.TABCATEGORIE AS TAB ON TAB.CODICE = CAT.CODICE INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = CAT.RIFPROGRESSIVO
UNION
SELECT     CATS.RIFPROGRESSIVO, 'CATS' AS TIPO, CAST(CATS.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_CATEGORIAS AS CATS INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = CATS.RIFPROGRESSIVO AND 
                      CATS.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE CATS.NRRIGA END) INNER JOIN
                      dbo.TABCATEGORIESTAT AS TAB ON TAB.CODICE = CATS.CODICE INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = CATS.RIFPROGRESSIVO
UNION
SELECT     PRZ.RIFPROGRESSIVO, 'PRZ' AS TIPO, CAST(PRZ.CODICE AS VARCHAR) AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_GRUPPO_PREZZI AS PRZ INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = PRZ.RIFPROGRESSIVO AND 
                      PRZ.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE PRZ.NRRIGA END) INNER JOIN
                      dbo.TABRAGGRUPPAPREZZI AS TAB ON TAB.CODICE = PRZ.CODICE INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = PRZ.RIFPROGRESSIVO
UNION
SELECT     FR.RIFPROGRESSIVO, 'FR' AS TIPO, 'MetFam:' + CAST(FR.FAMIGLIA AS VARCHAR) + ' - MetRep:' + CAST(FR.REPARTO AS VARCHAR) AS CODICE, 
                      'MetFam:' + FAM.Descrizione + '- MetRep:' + REP.Descrizione AS DESCRIZIONE, CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA,
                       DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_FAMREP AS FR INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = FR.RIFPROGRESSIVO AND 
                      FR.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE FR.NRRIGA END) INNER JOIN
                      dbo.TabFamigliePOS AS FAM ON FAM.Codice = FR.FAMIGLIA INNER JOIN
                      dbo.TabRepartiPOS AS REP ON REP.Codice = FR.REPARTO INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = FR.RIFPROGRESSIVO
UNION
SELECT     LIV.RIFPROGRESSIVO, 'LIV' AS TIPO, LIV.CODICE, TAB.Descrizione, CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, 
                      DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_LIVELLIMERCEOLOGICI AS LIV INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = LIV.RIFPROGRESSIVO INNER JOIN
                      dbo.Tp_LivelliMerceologici AS TAB ON TAB.Codice = REPLACE(LIV.CODICE, '''', '') INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = LIV.RIFPROGRESSIVO

UNION
SELECT     FT.RIFPROGRESSIVO, 'FT' AS TIPO, CAST(FT.CODFEATURE AS VARCHAR) + ' - Varianti:' + FT.VARESPLICITE AS Expr1, TAB.DESCRIZIONE, 
                      CASE DETT.NRRIGA WHEN 0 THEN 'TOT' ELSE 'N' END AS TIPOLOGIA, DETT.UM_M, DETT.Qta_Minima
FROM         dbo.PROMOZIONI_FEATURE AS FT INNER JOIN
                      dbo.PROMOZIONI_DETT AS DETT ON DETT.RifProgressivo = FT.RIFPROGRESSIVO AND 
                      FT.NRRIGA = (CASE WHEN DETT.NRRIGA > 0 THEN DETT.NRRIGA ELSE FT.NRRIGA END) INNER JOIN
                      dbo.FEATURE AS TAB ON TAB.CODICE = FT.CODFEATURE INNER JOIN
                      dbo.TP_PROMOZIONI_TESTE AS TESTE ON TESTE.Progressivo = FT.RIFPROGRESSIVO



GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPROMOCONDIZIONIMERCEOLOGICHE] TO [Metodo98]
    AS [dbo];

