CREATE VIEW VISTASALDOCONTIPN AS
        SELECT CONTO, ESERCIZIO, PROVVISORIO,NRGIORNALE,SUM(DARE)AS DARE , SUM(DAREEURO) AS DAREEURO, SUM(DAREVALUTA) AS DAREVALUTA,
        SUM(AVERE)AS AVERE, SUM(AVEREEURO) AS AVEREEURO, SUM(AVEREVALUTA) AS AVEREVALUTA,
        SUM(SALDO)AS SALDO, SUM(SALDOEURO) AS SALDOEURO, SUM(SALDOVALUTA) AS SALDOVALUTA
        FROM VISTASALDICONTABILITA
        GROUP BY CONTO, ESERCIZIO,PROVVISORIO,NRGIORNALE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASALDOCONTIPN] TO [Metodo98]
    AS [dbo];

