

CREATE VIEW VISTAPROGRESSIVOAVANZGRPACQ
AS

SELECT     CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ, 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO, 
                      SUM(CONTRATTI_DETTCONSUNTIVGRUPPIACQ.QTA) AS TOTQTA, SUM(CONTRATTI_DETTCONSUNTIVGRUPPIACQ.VALORE) AS TOTVALORE, 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO, ACQ_GRUPPOACQUISTO.DESCRIZIONE, 
                      ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO, ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO, ANAGRAFICACF.DSCCONTO1, 
                      VISTATOTALIAVANZGRPACQ.VALORE AS TOTVALOREANNUO, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO, 
                      ANAGRAFICAARTICOLI.GRUPPO, ANAGRAFICAARTICOLI.CATEGORIA, ANAGRAFICAARTICOLI.CODCATEGORIASTAT, 
                      TP_ExtraMag.CodFamigliaPOS, TP_ExtraMag.CodRepartoPOS, ANAGRAFICAARTICOLICOMM.GRUPPOPRZPART
FROM         CONTRATTI_TESTECONSUNTIVGRUPPIACQ INNER JOIN
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ ON 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.PROGRESSIVO = CONTRATTI_DETTCONSUNTIVGRUPPIACQ.RIFPROGRESSIVO INNER JOIN
                      ACQ_GRUPPOACQUISTO ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = ACQ_GRUPPOACQUISTO.CODICE INNER JOIN
                      ACQ_COMPONENTIGRUPPOACQUISTO ON 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = ACQ_COMPONENTIGRUPPOACQUISTO.RIFCODICE AND 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO = ACQ_COMPONENTIGRUPPOACQUISTO.IDSOCIO INNER JOIN
                      ANAGRAFICACF ON ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO = ANAGRAFICACF.CODCONTO INNER JOIN
                      VISTATOTALIAVANZGRPACQ ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR = VISTATOTALIAVANZGRPACQ.CODCLIFOR AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = VISTATOTALIAVANZGRPACQ.GRUPPOACQ AND 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO = VISTATOTALIAVANZGRPACQ.IDSOCIO AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO = VISTATOTALIAVANZGRPACQ.ANNO LEFT OUTER JOIN
                      ANAGRAFICAARTICOLICOMM ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO = ANAGRAFICAARTICOLICOMM.ESERCIZIO AND 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = ANAGRAFICAARTICOLICOMM.CODICEART LEFT OUTER JOIN
                      TP_ExtraMag ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = TP_ExtraMag.CodArt LEFT OUTER JOIN
                      ANAGRAFICAARTICOLI ON CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = ANAGRAFICAARTICOLI.CODICE
GROUP BY CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ, 
                      CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO, 
                      CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO, ACQ_GRUPPOACQUISTO.DESCRIZIONE, 
                      ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO, ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO, ANAGRAFICACF.DSCCONTO1, 
                      VISTATOTALIAVANZGRPACQ.VALORE, CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO, ANAGRAFICAARTICOLI.GRUPPO, 
                      ANAGRAFICAARTICOLI.CATEGORIA, ANAGRAFICAARTICOLI.CODCATEGORIASTAT, TP_ExtraMag.CodFamigliaPOS, 
                      TP_ExtraMag.CodRepartoPOS, ANAGRAFICAARTICOLICOMM.GRUPPOPRZPART
HAVING      (ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO <> 2)



GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTAPROGRESSIVOAVANZGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTAPROGRESSIVOAVANZGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTAPROGRESSIVOAVANZGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAPROGRESSIVOAVANZGRPACQ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTAPROGRESSIVOAVANZGRPACQ] TO [Metodo98]
    AS [dbo];

