-- FINE RM: 37403

-- RM: 39501 --------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW VISTASPESEFATTB2B AS
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+1 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
 'Spese incasso' AS DescrizioneRiga,
TOTSPESEEFFETTO AS PrezzoUnitario,
TOTSPESEEFFETTO AS PrezzoTotale,
TOTSPESEEFFETTOEURO AS PrezzoUnitarioEuro,
TOTSPESEEFFETTOEURO AS PrezzoTotaleEuro,
CODIVASPEFF AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPEFF),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPEFF),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPEFF,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPEFF AND TIPOCICLO IN (0,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZ,
(CASE WHEN COALESCE(CODIVASPEFF,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPEFF AND TIPOCICLO IN (1,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZPASS,
'SP01' AS TIPOSPESAACCESSORIA
FROM TESTEDOCUMENTI 
WHERE TOTSPESEEFFETTO<>0
UNION ALL
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+2 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
'Spese Imballo' AS DescrizioneRiga,
TOTSPESEIMBALLO AS PrezzoUnitario,
TOTSPESEIMBALLO AS PrezzoTotale,
TOTSPESEIMBALLOEURO AS PrezzoUnitarioEuro,
TOTSPESEIMBALLOEURO AS PrezzoTotaleEuro,
CODIVASPIMB AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPIMB),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPIMB),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPIMB,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPIMB AND TIPOCICLO IN (0,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZ,
(CASE WHEN COALESCE(CODIVASPIMB,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPIMB AND TIPOCICLO IN (1,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZPASS,
'SP04' AS TIPOSPESAACCESSORIA      
FROM TESTEDOCUMENTI 
WHERE TOTSPESEIMBALLO<>0
UNION ALL
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+3 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
'Spese Trasporto' AS DescrizioneRiga,
TOTSPESETRASP AS PrezzoUnitario,
TOTSPESETRASP AS PrezzoTotale,
TOTSPESETRASPEURO AS PrezzoUnitarioEuro,
TOTSPESETRASPEURO AS PrezzoTotaleEuro,
CODIVASPTRASP AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPTRASP),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPTRASP),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPTRASP,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPTRASP AND TIPOCICLO IN (0,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZ,
(CASE WHEN COALESCE(CODIVASPTRASP,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPTRASP AND TIPOCICLO IN (1,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZPASS,
'SP03' AS TIPOSPESAACCESSORIA
FROM TESTEDOCUMENTI 
WHERE TOTSPESETRASP<>0
UNION ALL
SELECT PROGRESSIVO AS IDTESTA,(SELECT MAX(POSIZIONE)+4 FROM RIGHEDOCUMENTI WHERE IDTESTA=PROGRESSIVO) AS POSSPESA,
(CASE WHEN FLGBOLLOVIRTUALE<>0 THEN 'Spese Bolli' ELSE 'Spese Documento' END) AS DescrizioneRiga,
TOTSPESEDOC AS PrezzoUnitario,
TOTSPESEDOC AS PrezzoTotale,
TOTSPESEDOCEURO AS PrezzoUnitarioEuro,
TOTSPESEDOCEURO AS PrezzoTotaleEuro,
CODIVASPDOC AS CODIVASPESA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPDOC),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVASPDOC),0) AS TIPOESENZ,
(CASE WHEN COALESCE(CODIVASPDOC,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPDOC AND TIPOCICLO IN (0,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZ,
(CASE WHEN COALESCE(CODIVASPDOC,0)=0 THEN 'N2' ELSE
COALESCE((SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=CODIVASPDOC AND TIPOCICLO IN (1,2) ORDER BY TIPOCICLO),'') END) AS NATURAESENZPASS,
(CASE WHEN FLGBOLLOVIRTUALE<>0 THEN 'SP08' ELSE 'SP99' END) AS TIPOSPESAACCESSORIA
FROM TESTEDOCUMENTI 
WHERE TOTSPESEDOC<>0

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASPESEFATTB2B] TO [Metodo98]
    AS [dbo];

