

CREATE VIEW VistaPrezziSconti
AS

SELECT     PROGRESSIVO, CODGRUPPOPREZZICF, CODCLIFOR, CODDESTINAZIONE, CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, FAMIGLIA, REPARTO, 
           TIPOARROT, ARROTAVALUTA, ARROTONDA, CODARTTIPOLOGIA, VARIANTI, UM, TIPORIGA, QTAMINIMA, IMPORTOVALUTA, IMPORTO, TIPOSCONTO, 
           PROGRESSIVOCTR, UTENTEMODIFICA, DATAMODIFICA, CODSETTORE, CODZONA, CODCATEGORIA, CODICEPRIMARIO, VARESPLICITE,
           CODFEATURE, 
           ISNULL((SELECT FEATURE.DESCRIZIONE FROM FEATURE WHERE FEATURE.Codice = PR.CODFEATURE),'') AS DSCFEATURE 
FROM       REGOLEPREZZIESTESI AS PR




GO
GRANT SELECT
    ON OBJECT::[dbo].[VistaPrezziSconti] TO [Metodo98]
    AS [dbo];

