CREATE VIEW VISTATESTECONTABILITANA AS
SELECT TC.*
FROM TESTECONTABILITA TC INNER JOIN TABUTENTI ON USERDB = CAST(USER_NAME() AS VARCHAR(25))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTECONTABILITANA] TO [Metodo98]
    AS [dbo];

