
CREATE VIEW VISTATABELLAPERSONALE AS
SELECT CODICE,RIFCODCONTO,COGNOME,NOME,NOME+' '+COGNOME NOMECOGNOME, TITOLO,TELEFONO,CELL,TELCASA,FAX,POSIZIONE,EMAIL,NOTE 
FROM TABELLAPERSONALE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATABELLAPERSONALE] TO [Metodo98]
    AS [dbo];

