
CREATE VIEW dbo.VISTATP_ELENCOGIROVISITE
AS
SELECT     TOP 100 PERCENT dbo.TP_GIROVISITE_RIGHE.CODCONTO, dbo.ANAGRAFICACF.DSCCONTO1, dbo.TP_GIROVISITE_RIGHE.OrarioPMAM, 
                      dbo.TP_GIROVISITE_RIGHE.Periodicita, dbo.TP_GIROVISITE_RIGHE.OrarioVisite, dbo.TP_GIROVISITE_RIGHE.Giorno, 
                      dbo.ANAGRAFICARISERVATICF.ESERCIZIO, dbo.ANAGRAFICACF.LOCALITA, dbo.ANAGRAFICARISERVATICF.CODSETTORE, 
                      dbo.ANAGRAFICARISERVATICF.CODZONA, dbo.ANAGRAFICARISERVATICF.CODGRUPPOPREZZIPART, CASE WHEN tp_expffido.fido_disponibile < 0 AND 
                      fido_cliente > 0 THEN 'X' ELSE '' END AS 'FUORIFIDO', anagraficacf.note
FROM         dbo.ANAGRAFICACF INNER JOIN
                      dbo.ANAGRAFICARISERVATICF ON dbo.ANAGRAFICACF.CODCONTO = dbo.ANAGRAFICARISERVATICF.CODCONTO INNER JOIN
                      dbo.TP_GIROVISITE_RIGHE INNER JOIN
                      dbo.TP_GIROVISITE_TESTA ON dbo.TP_GIROVISITE_RIGHE.RIFProgressivo = dbo.TP_GIROVISITE_TESTA.Progressivo ON 
                      dbo.ANAGRAFICACF.CODCONTO = dbo.TP_GIROVISITE_RIGHE.CODCONTO LEFT OUTER JOIN
                      dbo.TP_ExpFFido ON dbo.ANAGRAFICARISERVATICF.CODCONTO = dbo.TP_ExpFFido.CLIENTE AND 
                      dbo.ANAGRAFICARISERVATICF.ESERCIZIO = dbo.TP_ExpFFido.ESERCIZIO
WHERE     ((dbo.ANAGRAFICACF.TIPOCONTO = 'C') AND (dbo.TP_GIROVISITE_RIGHE.DISATSELCLIDOC <> 1))
ORDER BY ANAGRAFICACF.dscconto1


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTATP_ELENCOGIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTATP_ELENCOGIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTATP_ELENCOGIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATP_ELENCOGIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTATP_ELENCOGIROVISITE] TO [Metodo98]
    AS [dbo];

