
CREATE VIEW VISTATOTALIAVANZAMENTOACQM
AS

SELECT     TOP (100) PERCENT dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR, dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ, 
                      dbo.ACQ_GRUPPOACQUISTO.DESCRIZIONE, dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO, 
                      SUM(dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.QTA) AS QTA, SUM(dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.VALORE) AS VALORE, 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO, dbo.ANAGRAFICACF.DSCCONTO1, 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MARCHIO, dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE, dbo.ANAGRAFICAARTICOLI.GRUPPO
FROM         dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ INNER JOIN
                      dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ ON 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.PROGRESSIVO = dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.RIFPROGRESSIVO INNER JOIN
                      dbo.ACQ_GRUPPOACQUISTO ON dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = dbo.ACQ_GRUPPOACQUISTO.CODICE INNER JOIN
                      dbo.ACQ_COMPONENTIGRUPPOACQUISTO ON 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = dbo.ACQ_COMPONENTIGRUPPOACQUISTO.RIFCODICE AND 
                      dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO = dbo.ACQ_COMPONENTIGRUPPOACQUISTO.IDSOCIO INNER JOIN
                      dbo.ANAGRAFICACF ON dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO = dbo.ANAGRAFICACF.CODCONTO INNER JOIN
                      dbo.VISTAMAXMESECONSGRPACQ ON dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR = dbo.VISTAMAXMESECONSGRPACQ.CODCLIFOR AND 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO = dbo.VISTAMAXMESECONSGRPACQ.anno AND 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE = dbo.VISTAMAXMESECONSGRPACQ.MESE AND 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = dbo.VISTAMAXMESECONSGRPACQ.ARTICOLO AND 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ = dbo.VISTAMAXMESECONSGRPACQ.GRUPPOACQ AND 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ESERCIZIO = dbo.VISTAMAXMESECONSGRPACQ.ESERCIZIO INNER JOIN
                      dbo.ANAGRAFICAARTICOLI ON dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ARTICOLO = dbo.ANAGRAFICAARTICOLI.CODICE
GROUP BY dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.GRUPPOACQ, dbo.CONTRATTI_DETTCONSUNTIVGRUPPIACQ.IDSOCIO, 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.ANNO, dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.CODCLIFOR, dbo.ACQ_GRUPPOACQUISTO.DESCRIZIONE, 
                      dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO, dbo.ANAGRAFICACF.DSCCONTO1, 
                      dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MARCHIO, dbo.CONTRATTI_TESTECONSUNTIVGRUPPIACQ.MESE, dbo.ANAGRAFICAARTICOLI.GRUPPO
HAVING      (dbo.ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO <> 2)

GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTATOTALIAVANZAMENTOACQM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTATOTALIAVANZAMENTOACQM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTATOTALIAVANZAMENTOACQM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATOTALIAVANZAMENTOACQM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTATOTALIAVANZAMENTOACQM] TO [Metodo98]
    AS [dbo];

