CREATE VIEW VISTASCHEDULAZIONE AS SELECT 
 TP.PROGRESSIVO AS IDCOMMESSA,
 RP.IDRIGA AS IDORDINE,
 RC.PROGRESSIVO AS IDCICLO,
 RC.NUMEROFASE AS NUMEROFASE,
 RC.POSIZIONE AS POSIZIONE,
 TP.TIPOCOM,
 TP.ESERCIZIO,
 TP.NUMEROCOM,
 RP.CODICEORD,
 TP.DATAEMISSIONE,
 TP.TIPOCOM+'/'+cast(TP.ESERCIZIO as varchar)+'/'+right('0000000000'+cast(TP.NUMEROCOM as varchar),10) as RIFCOMMESSA,
 TP.TIPOCOM+'/'+cast(TP.ESERCIZIO as varchar)+'/'+right('0000000000'+cast(TP.NUMEROCOM as varchar),10)+'/'+RP.CODICEORD+'/'+right('00000'+cast(RP.IDRIGA as varchar),5) as RIFORDINE,
 RP.RIFCOMMCLI,
 RP.CODART,
 RP.DESCRIZIONEART,
 RP.CODCLIDEST,
 (SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO=RP.CODCLIDEST) AS RAGSOCCLIDEST,
 RP.CODFORDEST,
 (SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO=RP.CODFORDEST) AS RAGSOCFORDEST,
 (case when RP.FASERILASCIO = 1 then 0 else 1 end) as ORDINECONFERMATO,
 RP.FASERILASCIO,
 RP.DATAINIZIORICH,
 RP.DATAFINERICH,
 RP.VALOREPRIORITA,
 RC.CDLAVORO,
 (SELECT DESCRIZIONE FROM TABELLACDLAVORO WHERE CODICE = RC.CDLAVORO) AS DSCCDLAVORO,
 (case when RC.MACCHINA='' then RC.CDLAVORO else RC.MACCHINA end) as MACCHINA,
 (case when RC.MACCHINA='' then 
  (SELECT DESCRIZIONE FROM TABELLACDLAVORO WHERE CODICE = RC.CDLAVORO)
 else 
  (SELECT DESCRIZIONE FROM TABELLAMACCHINE WHERE CODICE = RC.MACCHINA)
 end) as DSCMACCHINA,
 RC.ANNOBOLLA,RC.NUMEROBOLLA,
 cast(RC.ANNOBOLLA as varchar(4))+'/'+right('00000000'+cast(RC.NUMEROBOLLA as varchar),8) as DSCFASE,
 RC.OPERAZIONE,
 (SELECT DESCRIZIONE FROM TABELLAOPERAZIONI WHERE CODICE = RC.OPERAZIONE) AS DSCOPERAZIONE,
 RC.STATOOPERAZIONE,
 RC.OREPREVDURATA,RC.OREEFFDURATA,
 (case when (RC.OREPREVDURATA-RC.OREEFFDURATA)<0 then 0 else (RC.OREPREVDURATA-RC.OREEFFDURATA) end) AS ORERESDURATA,
 (case when RC.OREPREVDURATA=0 then 0 else (RC.OREEFFDURATA/RC.OREPREVDURATA)*100 end) as PERCAVANZAMENTODURATA,
 RC.DATAINIZIOOPEFFETTIVA,
 RC.ORAINIZIOOPEFFETTIVA,
 RC.DATAINIZIOOPSCHEDULATA,
 RC.ORAINIZIOOPSCHEDULATA,
 RC.DATAFINEOPSCHEDULATA,
 RC.TEMPOPREVATTRAV,
 RC.TIPOFASE,
 RP.QTA1MAG
FROM 
 (((TESTEORDINIPROD TP INNER JOIN RIGHEORDPROD RP ON RP.IDTESTA=TP.PROGRESSIVO)
  INNER JOIN TESTACICLOORDINE TC ON TC.IDTESTACOMM=TP.PROGRESSIVO and TC.IDRIGACOMM=RP.IDRIGA)
   INNER JOIN RIGHECICLOORDINE RC ON RC.PROGRESSIVO=TC.PROGRESSIVO)
WHERE
 RP.FASERILASCIO < 5 AND RP.STATOLANCIO <> 2 

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASCHEDULAZIONE] TO [Metodo98]
    AS [dbo];

