CREATE VIEW VISTASALDIINIZIALIPN AS
SELECT RCONT.CONTO,RCONT.ESERCIZIO,TCONT.PROVVISORIO,TCONT.NRGIORNALE,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTO ELSE 0 END)) AS DARE,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOEURO ELSE 0 END)) AS DAREEURO,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOVALUTA ELSE 0 END)) AS DAREVALUTA,
    SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTO ELSE 0 END)) AS AVERE,
    SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOEURO ELSE 0 END)) AS AVEREEURO,
    SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOVALUTA ELSE 0 END)) AS AVEREVALUTA,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTO ELSE 0 END))-SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTO ELSE 0 END)) AS SALDO,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOEURO ELSE 0 END))-SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOEURO ELSE 0 END)) AS SALDOEURO,
    SUM((CASE WHEN RCONT.SEGNO=0 THEN RCONT.IMPORTOVALUTA ELSE 0 END))-SUM((CASE WHEN RCONT.SEGNO=1 THEN RCONT.IMPORTOVALUTA ELSE 0 END)) AS SALDOVALUTA
    FROM RIGHECONTABILITA AS RCONT,TESTECONTABILITA AS TCONT
    WHERE TCONT.PROGRESSIVO=RCONT.NRREG
    AND TCONT.CAUSALE=(SELECT GIC.CAUSCONTAP FROM TABVINCOLIGIC AS GIC WHERE GIC.ESERCIZIO=TCONT.ESERCIZIO)
    GROUP BY RCONT.ESERCIZIO,RCONT.CONTO,TCONT.PROVVISORIO,TCONT.NRGIORNALE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTASALDIINIZIALIPN] TO [Metodo98]
    AS [dbo];

