CREATE VIEW VISTATESTERATEIRISCONTI AS
SELECT TRR.*,
    (SELECT DSCCONTO1 FROM ANAGRAFICAGENERICI WHERE ANAGRAFICAGENERICI.CODCONTO=TRR.CODCONTO) AS DSCCODCONTO,
    (SELECT DESCRIZIONE FROM CAUSALICONTABILI WHERE CODICECAUSALE=TRR.CAUSALE) AS DSCCAUSALE
    FROM TABRIPARTIZRATEIRISCONTI TRR WHERE TRR.TIPORIGA=0

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATESTERATEIRISCONTI] TO [Metodo98]
    AS [dbo];

