
CREATE VIEW VISTATABFORNITORICICLO AS
	SELECT PROGRESSIVO, NUMEROFASE, LISTINOTRASF AS NRLISTINO,
	(SELECT DESCRIZIONE FROM TABLISTINITRASFORMAZIONE WHERE NRLISTINO=LISTINOTRASF) AS DESCRIZIONE,
        CODFORN AS CODFOR,
	(SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO=CODFORN) AS DSCCONTO1
FROM TABFORNITORICICLO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTATABFORNITORICICLO] TO [Metodo98]
    AS [dbo];

