
CREATE VIEW AIOT_VISTALIV1TO
AS

SELECT     CAST(A.ESERCIZIO AS VARCHAR) + '/' + CAST(A.NUMEROOFFERTA AS VARCHAR) AS NUMEROTO, F.CODCONTO, F.DSCCONTO1, T.ESERCIZIO, T.TIPODOC, 
                      T.NUMERODOC, T.BIS, T.DATADOC, T.DATARIFDOC, T.PROGRESSIVO, A.PROGRESSIVO AS PROGRESSIVOTO
FROM         dbo.TESTEDOCUMENTI AS T INNER JOIN
                      dbo.ACQ_TESTAOFFERTA AS A ON A.PROGRESSIVO = T.RifTransferOrder INNER JOIN
                      dbo.ANAGRAFICACF AS F ON T.CODCLIFOR = F.CODCONTO
WHERE     (T.RifTransferOrder > 0)


GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_VISTALIV1TO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_VISTALIV1TO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AIOT_VISTALIV1TO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_VISTALIV1TO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_VISTALIV1TO] TO [Metodo98]
    AS [dbo];

