
CREATE VIEW AIOT_VISTATESTETO
AS

SELECT     TOP (100) PERCENT T.PROGRESSIVO, T.ESERCIZIO, T.NUMEROOFFERTA, T.DATAEMISSIONE, T.DATAFINEOFFERTA, T.FORNITORE, F.DSCCONTO1, T.GRUPPOACQ, 
                      G.DESCRIZIONE, T.DOCUMENTAZIONEALLEGATA, T.FLAGSTATO, CASE WHEN E.ESITO IS NULL THEN 0 ELSE E.ESITO END AS ESITO
FROM         dbo.ACQ_TESTAOFFERTA AS T LEFT OUTER JOIN
                      dbo.ANAGRAFICACF AS F ON F.CODCONTO = T.FORNITORE LEFT OUTER JOIN
                      dbo.ACQ_GRUPPOACQUISTO AS G ON G.CODICE = T.GRUPPOACQ LEFT OUTER JOIN
                      dbo.ACQ_OFFERTAESITI AS E ON E.RIFPROGRESSIVO = T.PROGRESSIVO
ORDER BY T.ESERCIZIO, T.NUMEROOFFERTA


GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_VISTATESTETO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_VISTATESTETO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_VISTATESTETO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_VISTATESTETO] TO [Metodo98]
    AS [dbo];

