
CREATE VIEW dbo.AIOT_TP_PROMOZIONI_COND
AS
SELECT     dbo.TP_PROMOZIONI_COND.RifProgressivo, dbo.TP_PROMOZIONI_COND.Codice, dbo.ANAGRAFICAARTICOLI.DESCRIZIONE, 
                      dbo.TP_PROMOZIONI_COND.UM_M, dbo.TP_PROMOZIONI_COND.Qta_Minima, dbo.TP_PROMOZIONI_COND.Note
FROM         dbo.TP_PROMOZIONI_COND LEFT OUTER JOIN
                      dbo.ANAGRAFICAARTICOLI ON dbo.TP_PROMOZIONI_COND.Codice = dbo.ANAGRAFICAARTICOLI.CODICE


GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_TP_PROMOZIONI_COND] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_TP_PROMOZIONI_COND] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AIOT_TP_PROMOZIONI_COND] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_TP_PROMOZIONI_COND] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_TP_PROMOZIONI_COND] TO [Metodo98]
    AS [dbo];

