

CREATE VIEW dbo.AIOT_INCONDIZIONATI
AS
SELECT     dbo.CONTRATTI_CL.RIFPROGRESSIVO, dbo.CONTRATTI_CL.NRRIGA, dbo.CONTRATTI_CL.FLAGRIGA, dbo.CONTRATTI_CL.POSIZIONE, 
                      dbo.CONTRATTI_CL.DESCRIZIONE, dbo.CONTRATTI_CL.BOLISPERC, dbo.CONTRATTI_CL.VALORE, dbo.CONTRATTI_CL.MERCEVALORE, 
                      dbo.CONTRATTI_CL.MERCEQTA, dbo.CONTRATTI_CL.DATAEMISSIONEDOC, dbo.CONTRATTI_CL.TIPODOC, dbo.CONTRATTI_CL.IVA, 
                      dbo.CONTRATTI_CL.PAGAMENTO, dbo.CONTRATTI_CL.SOTTOCONTOCONTABILE, 
                      CASE WHEN dbo.CONTRATTI_CL.EMESSO = 1 THEN 'Emesso' ELSE 'Non Emesso' END AS EMESSO, dbo.CONTRATTI_CL.UTENTEMODIFICA, 
                      dbo.CONTRATTI_CL.DATAMODIFICA, dbo.CONTRATTI_CL.NOTE, 
                      CASE WHEN dbo.CONTRATTI_CL.PREVISIONI = 0 THEN '' ELSE CASE WHEN dbo.CONTRATTI_CL.PREVISIONI = 1 THEN 'Sicura' ELSE CASE WHEN dbo.CONTRATTI_CL.PREVISIONI
                       = 2 THEN 'Improbabile' ELSE 'Impossibile' END END END AS PREVISIONI, 
                      CASE WHEN dbo.CONTRATTI_CL.TIPO = 0 THEN '' ELSE CASE WHEN dbo.CONTRATTI_CL.TIPO = 1 THEN 'Interno' ELSE 'Esterno' END END AS TIPO, 
                      dbo.CONTRATTI_CL.PERIODICITALIQUIDAZIONE, 
                      CASE WHEN dbo.CONTRATTI_CL.TIPOCALCOLOPREMIO = 0 THEN '' ELSE CASE WHEN dbo.CONTRATTI_CL.TIPOCALCOLOPREMIO = 1 THEN 'Cumulativo'
                       ELSE 'Scaglioni' END END AS TIPOCALCOLOPREMIO, dbo.CONTRATTI_CL.UM, dbo.TABPAGAMENTI.DESCRIZIONE AS DSCPAGAMENTO, 
                      dbo.ANAGRAFICAGENERICI.DSCCONTO1, 
                      CASE WHEN VALORE > 0 THEN 'VALORE' ELSE CASE WHEN MERCEVALORE > 0 THEN 'MERCE VALORE' ELSE CASE WHEN BOLISPERC = 1 THEN 'PERCENTUALE'
                       ELSE CASE WHEN MERCEQTA = 1 THEN 'MERCE QTA' ELSE 'VALORE' END END END END AS TIPOLOGIA
FROM         dbo.CONTRATTI_CL LEFT OUTER JOIN
                      dbo.ANAGRAFICAGENERICI ON dbo.CONTRATTI_CL.SOTTOCONTOCONTABILE = dbo.ANAGRAFICAGENERICI.CODCONTO LEFT OUTER JOIN
                      dbo.TABPAGAMENTI ON dbo.CONTRATTI_CL.PAGAMENTO = dbo.TABPAGAMENTI.CODICE


GO
GRANT DELETE
    ON OBJECT::[dbo].[AIOT_INCONDIZIONATI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AIOT_INCONDIZIONATI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AIOT_INCONDIZIONATI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_INCONDIZIONATI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AIOT_INCONDIZIONATI] TO [Metodo98]
    AS [dbo];

