

CREATE VIEW AIOT_DATILIQUIDAZIONE
AS


SELECT     'INCOND' AS tipo, dbo.CONTRATTICL_DATEDOC.RIFPROGRESSIVOCL, dbo.CONTRATTICL_DATEDOC.RIFPROGRESSIVO, dbo.CONTRATTICL_DATEDOC.NRRIGA, 
                      dbo.CONTRATTICL_DATEDOC.FLAGRIGA, dbo.CONTRATTICL_DATEDOC.POSIZIONE, dbo.CONTRATTICL_DATEDOC.DATAEMISSIONE, 
                      dbo.CONTRATTICL_DATEDOC.VALORE, dbo.TESTEDOCUMENTI.ESERCIZIO, dbo.TESTEDOCUMENTI.TIPODOC, dbo.TESTEDOCUMENTI.NUMERODOC, 
                      dbo.TESTEDOCUMENTI.DATADOC, dbo.TESTEDOCUMENTI.NUMRIFDOC, dbo.TESTEDOCUMENTI.DATARIFDOC
FROM         dbo.CONTRATTICL_DATEDOC LEFT OUTER JOIN
                      dbo.TESTEDOCUMENTI ON dbo.CONTRATTICL_DATEDOC.RIFPROGRESSIVODOC = dbo.TESTEDOCUMENTI.PROGRESSIVO
UNION
SELECT     'COND' AS tipo, dbo.CONTRATTICC_DATELIQ.RIFPROGRESSIVO, dbo.CONTRATTICC_DATELIQ.RIFPROGRESSIVOCC, dbo.CONTRATTICC_DATELIQ.NRRIGA, 
                      dbo.CONTRATTICC_DATELIQ.FLAGRIGA, dbo.CONTRATTICC_DATELIQ.POSIZIONE, dbo.CONTRATTICC_DATELIQ.DATAEMISSIONE, 
                      dbo.CONTRATTICC_DATELIQ.VALORE, TESTEDOCUMENTI_1.ESERCIZIO, TESTEDOCUMENTI_1.TIPODOC, TESTEDOCUMENTI_1.NUMERODOC, 
                      TESTEDOCUMENTI_1.DATADOC, TESTEDOCUMENTI_1.NUMRIFDOC, TESTEDOCUMENTI_1.DATARIFDOC
FROM         dbo.CONTRATTICC_DATELIQ LEFT OUTER JOIN
                      dbo.TESTEDOCUMENTI AS TESTEDOCUMENTI_1 ON dbo.CONTRATTICC_DATELIQ.RIFPROGRESSIVODOC = TESTEDOCUMENTI_1.PROGRESSIVO


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOT_DATILIQUIDAZIONE] TO [Metodo98]
    AS [dbo];

