
CREATE VIEW [dbo].[AIOTCONTRATTILIQUIDAZIONE_UNIONEINCONDIZIONATI]
AS
SELECT     TIPOCONTRIBUTO, RifContratto, RifContributo, RIFSOTTORIGA, RIFSOTTORIGACOND, NOTA, TIPOLOGIA, DADATA, ADATA, BudgetQta, Um, BudgetValore, 
                      BudgetQtaConValore, UmQtaConValore, PREMIOVALORE, PREMIOPERCENTUALE, CONSUNTIVATOQTA, CONSUNTIVATOVALORE, PREMIOMATURATO, 
                      PERIODICITALIQUIDAZIONE, TIPO, TIPOCALCOLOPREMIO, CASE WHEN budgetvalore = 0 THEN 0 ELSE ((consuntivatovalore / budgetvalore * 100) - 100) END AS Delta,
                       PREMIONONVALIDO
FROM         dbo.CONTRATTILIQUIDAZIONE_UNIONEINCONDIZIONATI


GO
GRANT SELECT
    ON OBJECT::[dbo].[AIOTCONTRATTILIQUIDAZIONE_UNIONEINCONDIZIONATI] TO [Metodo98]
    AS [dbo];

