

CREATE VIEW [dbo].[ALD_Vista_AnagrCFRunningPD]
AS
SELECT     TESTEDOCUMENTI.CODCFFATT AS CODCLIFOR, esercizio, month(datadoc) as periodo
FROM         TESTEDOCUMENTI INNER JOIN
                      PARAMETRIDOC ON TESTEDOCUMENTI.TIPODOC = PARAMETRIDOC.CODICE
WHERE     (TESTEDOCUMENTI.DOCCHIUSO = 0) AND (PARAMETRIDOC.TIPO IN ('F', 'N')) 
union all
SELECT     TESTEDOCUMENTI.CODCFFATT AS CODCLIFOR,  year(GETDATE()) as esercizio, month(GETDATE()) as periodo
FROM         TESTEDOCUMENTI INNER JOIN
                      PARAMETRIDOC ON TESTEDOCUMENTI.TIPODOC = PARAMETRIDOC.CODICE
WHERE     (TESTEDOCUMENTI.DOCCHIUSO = 0) AND (PARAMETRIDOC.TIPO IN ('A', 'O')) AND (PARAMETRIDOC.CLIFOR IN ('C')) 
 AND (YEAR(GETDATE())-YEAR(DATADOC))<=2
union all
SELECT     RIGHECONTABILITA.CONTO AS CodCliFor, TESTECONTABILITA.ESERCIZIO, MONTH(TESTECONTABILITA.DATAREG) AS periodo
FROM         TESTECONTABILITA INNER JOIN
                      RIGHECONTABILITA ON TESTECONTABILITA.PROGRESSIVO = RIGHECONTABILITA.NRREG



GO
GRANT DELETE
    ON OBJECT::[dbo].[ALD_Vista_AnagrCFRunningPD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALD_Vista_AnagrCFRunningPD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ALD_Vista_AnagrCFRunningPD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_Vista_AnagrCFRunningPD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_Vista_AnagrCFRunningPD] TO [Metodo98]
    AS [dbo];

