
CREATE VIEW [dbo].[Ald_VistaTesteDocumenti]
AS
SELECT VISTATESTEDOC.*, ANAGRAFICARISERVATICF.STATOCONTABILITA, ANAGRAFICARISERVATICF.STATOMAGAZZINO, 
 ANAGRAFICARISERVATICF.STATOORDINI, ANAGRAFICARISERVATICF.STATOBOLLE, ANAGRAFICARISERVATICF.STATOFATTURE, 
 ANAGRAFICARISERVATICF.STATONOTEACCREDITO, ANAGRAFICARISERVATICF.STATOALTRO
FROM ANAGRAFICARISERVATICF INNER JOIN
 VISTATESTEDOC ON ANAGRAFICARISERVATICF.ESERCIZIO = VISTATESTEDOC.ESERCIZIO AND 
 ANAGRAFICARISERVATICF.CODCONTO = VISTATESTEDOC.CODCLIFOR

GO
GRANT SELECT
    ON OBJECT::[dbo].[Ald_VistaTesteDocumenti] TO [Metodo98]
    AS [dbo];

