CREATE VIEW [dbo].[Ald_VistaDaDocumenti_DeltaDate]
AS
SELECT     RD.IDTESTA AS IdTestaAnalisi, RD.IDRIGA AS IdRigaAnalisi, TD.DATADOC, RD.DATACONSEGNA, 
EXRD.DATACONS, TdRp.DATADOC AS DataDocRP, 
                      
(CASE WHEN TD.DATADOC = RD.DATACONSEGNA THEN 0 ELSE 
CASE WHEN TD.DATADOC > RD.DATACONSEGNA THEN
dbo.[AldCalcGGLAVCalendario](RD.DATACONSEGNA, TD.DATADOC) ELSE
dbo.[AldCalcGGLAVCalendario](TD.DATADOC, RD.DATACONSEGNA)*-1
END END) AS deltaGGConsDoc, 
(CASE WHEN TD.DATADOC = EXRD.DATACONS THEN 0 ELSE  
 CASE WHEN TD.DATADOC > EXRD.DATACONS THEN dbo.[AldCalcGGLAVCalendario](EXRD.DATACONS, TD.DATADOC) ELSE 
dbo.[AldCalcGGLAVCalendario](TD.DATADOC, EXRD.DATACONS)*-1                     
END END) AS deltaGGConsStorica, 
(CASE WHEN TD.DATADOC = TdRp.DATADOC THEN 0 ELSE 
 CASE WHEN TD.DATADOC > TdRp.DATADOC THEN 
dbo.[AldCalcGGLAVCalendario](TdRp.DATADOC, TD.DATADOC) ELSE
dbo.[AldCalcGGLAVCalendario](TD.DATADOC, TdRp.DATADOC)*-1  
END END) AS deltaGGDateDoc, 
TD.ESERCIZIO, TD.TIPODOC, TD.NUMERODOC, RD.IDTESTARP, TdRp.ESERCIZIO AS ESERCIZIOrp, 
                      TdRp.TIPODOC AS TIPODOCrp, TdRp.NUMERODOC AS NUMERODOCrp, 
(CASE WHEN TD.DATADOC = TdRp.DATARIFDOC THEN 0 ELSE 
 CASE WHEN TD.DATADOC > TdRp.DATARIFDOC THEN 
dbo.[AldCalcGGLAVCalendario](TdRp.DATARIFDOC, TD.DATADOC) ELSE
dbo.[AldCalcGGLAVCalendario](TD.DATADOC, TdRp.DATARIFDOC)*-1 
END END) AS deltaGGDateRifDocRP,               
TdRp.DATARIFDOC AS DATARIFDOCrp
FROM         RIGHEDOCUMENTI AS RD INNER JOIN
                      EXTRARIGHEDOC AS EXRD ON RD.IDTESTA = EXRD.IDTESTA AND RD.IDRIGA = EXRD.IDRIGA INNER JOIN
                      TESTEDOCUMENTI AS TD ON RD.IDTESTA = TD.PROGRESSIVO LEFT OUTER JOIN
                      TESTEDOCUMENTI AS TdRp ON RD.IDTESTARP = TdRp.PROGRESSIVO


GO
GRANT SELECT
    ON OBJECT::[dbo].[Ald_VistaDaDocumenti_DeltaDate] TO [Metodo98]
    AS [dbo];

