CREATE VIEW [dbo].[ALD_UPAARTFOR]
AS
	  Select SPA.CODARTICOLO
			,SPA.DATA
	        ,SPA.CODCLIFOR 
			,SPA.PREZZOEURO as PrezzoFornitore
 FROM STORICOPREZZIARTICOLO SPA
inner join 
(SELECT T.CODARTICOLO,T.CODCLIFOR,MAX(T.DATA) as MAX_DATA
FROM STORICOPREZZIARTICOLO T
WHERE PREZZOEURO>0
GROUP BY T.CODARTICOLO,T.CODCLIFOR) SPA1
on SPA.CODARTICOLO = SPA1.CODARTICOLO and SPA.CODCLIFOR=SPA1.CODCLIFOR  AND SPA1.MAX_DATA = SPA.DATA
WHERE SPA.TIPOPREZZO='F'

GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_UPAARTFOR] TO [Metodo98]
    AS [dbo];

