
create view Ald_VistaMovStoricoMagRettifiche
as
SELECT   STORICOMAG.CODCAUSALE,  
STORICOMAG.CODDEPOSITO, STORICOMAG.CODART, ANAGRAFICAARTICOLI.DESCRIZIONE AS DscArticolo, ANAGRAFICAARTICOLI.GRUPPO, 
                      TABGRUPPI.DESCRIZIONE AS DscGruppo, ANAGRAFICAARTICOLI.CATEGORIA, TABCATEGORIE.DESCRIZIONE AS DscCategoria, 
                      ANAGRAFICAARTICOLICOMM.SCGENVENDITEITA, ANAGRAFICAGENERICI.DSCCONTO1 AS DscGenericoRicavoIta, EXTRAGENERICI.IdASA, 
                      CONS_ALD_TABASA.Descrizione AS DscAsa, EXTRAGENERICI.CodSap, Ald_VisCONS_ALD_PDC_MFM.Descrizione AS DscCodSap, 
                      Ald_VisCONS_ALD_PDC_MFM.NaturaMastro, Ald_VisCONS_ALD_PDC_MFM.NaturaConto, Ald_VisCONS_ALD_PDC_MFM.GestioneAnalitica, 
					  (STORICOMAG.GIACENZA * STORICOMAG.QTA1UM) as QtaMov, 
					  ((SELECT top 1 PREZZOEURO FROM STORICOPREZZIARTICOLO UPA WHERE TIPOPREZZO = 'F' and upa.DATA<=STORICOMAG.DATAMOV  and UPA.CODARTICOLO=STORICOMAG.CODART  order by data desc) ) as UPAArticolo,
					   ( (STORICOMAG.GIACENZA * STORICOMAG.QTA1UM) * isnull(
					   ((SELECT top 1 PREZZOEURO FROM STORICOPREZZIARTICOLO UPA WHERE TIPOPREZZO = 'F' and upa.DATA<=STORICOMAG.DATAMOV  and UPA.CODARTICOLO=STORICOMAG.CODART order by data desc) )
					    ,0)) as ValMovimentoUPA
FROM         CONS_ALD_TABASA RIGHT OUTER JOIN
                      EXTRAGENERICI LEFT OUTER JOIN
                      Ald_VisCONS_ALD_PDC_MFM ON EXTRAGENERICI.CodSap = Ald_VisCONS_ALD_PDC_MFM.codSap ON 
                      CONS_ALD_TABASA.IdASA = EXTRAGENERICI.IdASA RIGHT OUTER JOIN
                      STORICOMAG INNER JOIN
                      ANAGRAFICAARTICOLICOMM ON STORICOMAG.ESERCIZIO = ANAGRAFICAARTICOLICOMM.ESERCIZIO AND 
                      STORICOMAG.CODART = ANAGRAFICAARTICOLICOMM.CODICEART INNER JOIN
                      ANAGRAFICAARTICOLI ON STORICOMAG.CODART = ANAGRAFICAARTICOLI.CODICE INNER JOIN
                      TABGRUPPI ON ANAGRAFICAARTICOLI.GRUPPO = TABGRUPPI.CODICE INNER JOIN
                      TABCATEGORIE ON ANAGRAFICAARTICOLI.CATEGORIA = TABCATEGORIE.CODICE LEFT OUTER JOIN
                      ANAGRAFICAGENERICI ON ANAGRAFICAARTICOLICOMM.SCGENVENDITEITA = ANAGRAFICAGENERICI.CODCONTO ON 
                      EXTRAGENERICI.CODCONTO = ANAGRAFICAGENERICI.CODCONTO
WHERE     (STORICOMAG.ESERCIZIO = 2014) AND (STORICOMAG.CODCAUSALE IN (10, 13, 15, 16)) AND (ANAGRAFICAARTICOLI.CATEGORIA NOT IN (11505, 95000, 95100, 20100, 
                      20200, 21000, 21100, 21200, 21300, 21400)) AND (NOT (STORICOMAG.CODDEPOSITO = 'MAG90'))


GO
GRANT DELETE
    ON OBJECT::[dbo].[Ald_VistaMovStoricoMagRettifiche] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[Ald_VistaMovStoricoMagRettifiche] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[Ald_VistaMovStoricoMagRettifiche] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[Ald_VistaMovStoricoMagRettifiche] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[Ald_VistaMovStoricoMagRettifiche] TO [Metodo98]
    AS [dbo];

