
CREATE VIEW [dbo].[ald_vista_ConsolidatoMFMCPartite]
AS

SELECT     DB_NAME() AS Ditta, RIGHECONTABILITA.ESERCIZIO, RIGHECONTABILITA.DATAREG, RIGHECONTABILITA.CONTO, RIGHECONTABILITA.CPARTITA, 
                      VISTACF1.DSCCONTO1 AS v1DscConto1, TESTECONTABILITA.PROGRESSIVO, TABMASTRI.CODICE, VISTACF1.CAP, RIGHECONTABILITA.IMPORTO, 
                      RIGHECONTABILITA.IMPORTOEURO, RIGHECONTABILITA.SEGNO, VISTACF2.DSCCONTO1, VISTACF1.CODCONTO, EXTRAGENERICI.codNaturaPDC_1, 
                      EXTRAGENERICI.codNaturaPDC_2, EXTRAGENERICI.codNaturaPDC_3, EXTRAGENERICI.CodContoMFM
FROM         TESTECONTABILITA AS TESTECONTABILITA INNER JOIN
                      RIGHECONTABILITA AS RIGHECONTABILITA ON TESTECONTABILITA.PROGRESSIVO = RIGHECONTABILITA.NRREG LEFT OUTER JOIN
                      --VISTACLIFOR AS VISTACF1 ON RIGHECONTABILITA.CPARTITA = VISTACF1.CODCONTO LEFT OUTER JOIN
					  AnagraficaCF AS VISTACF1 ON RIGHECONTABILITA.CPARTITA = VISTACF1.CODCONTO LEFT OUTER JOIN
                      ANAGRAFICAGENERICI AS VISTACF2 ON RIGHECONTABILITA.CONTO = VISTACF2.CODCONTO LEFT OUTER JOIN
                      EXTRAGENERICI AS EXTRAGENERICI ON RIGHECONTABILITA.CONTO = EXTRAGENERICI.CODCONTO LEFT OUTER JOIN
                      TABNAZIONI AS TABNAZIONI ON VISTACF1.CODNAZIONE = TABNAZIONI.CODICE LEFT OUTER JOIN
                      TABMASTRI AS TABMASTRI ON VISTACF1.CODMASTRO = TABMASTRI.CODICE
GO
GRANT DELETE
    ON OBJECT::[dbo].[ald_vista_ConsolidatoMFMCPartite] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ald_vista_ConsolidatoMFMCPartite] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ald_vista_ConsolidatoMFMCPartite] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ald_vista_ConsolidatoMFMCPartite] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ald_vista_ConsolidatoMFMCPartite] TO [Metodo98]
    AS [dbo];

