CREATE VIEW dbo.Ald_VistaCCBILANCIOCONSLAVINTDOC
AS
SELECT     AnagraficaCommesse.TipoCom, AnagraficaCommesse.StatoCommessa, dbo.RIGHEDOCUMENTI.ANNOTAZIONI AS NodoID, 
                      CCBILANCIOCONSLAVINTDOC.*
FROM         dbo.VISTACOSTILAVINTDOC CCBILANCIOCONSLAVINTDOC INNER JOIN
                      dbo.AnagraficaCommesse AnagraficaCommesse ON CCBILANCIOCONSLAVINTDOC.IDCOMMCLI = AnagraficaCommesse.Progressivo INNER JOIN
                      dbo.RIGHEDOCUMENTI ON CCBILANCIOCONSLAVINTDOC.IDTESTADOC = dbo.RIGHEDOCUMENTI.IDTESTA AND 
                      CCBILANCIOCONSLAVINTDOC.IDRIGADOC = dbo.RIGHEDOCUMENTI.IDRIGA

GO
GRANT DELETE
    ON OBJECT::[dbo].[Ald_VistaCCBILANCIOCONSLAVINTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[Ald_VistaCCBILANCIOCONSLAVINTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[Ald_VistaCCBILANCIOCONSLAVINTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[Ald_VistaCCBILANCIOCONSLAVINTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[Ald_VistaCCBILANCIOCONSLAVINTDOC] TO [Metodo98]
    AS [dbo];

