
CREATE VIEW [dbo].[ALD_Vista_UffAcqDocumentiFornitori]
AS

SELECT     TABDITTE.DITTA, TESTEDOCUMENTI.TIPODOC, TESTEDOCUMENTI.ESERCIZIO, TESTEDOCUMENTI.NUMERODOC, TESTEDOCUMENTI.DATADOC, 
                      TESTEDOCUMENTI.CODCLIFOR, TESTEDOCUMENTI.CODPAGAMENTO, TABPAGAMENTI.DESCRIZIONE AS DscPagamento, 
                      TESTEDOCUMENTI.TOTDOCUMENTORES, PARAMETRIDOC.DESCRIZIONE AS DscTipoDoc
FROM         TESTEDOCUMENTI INNER JOIN
                      PARAMETRIDOC ON TESTEDOCUMENTI.TIPODOC = PARAMETRIDOC.CODICE INNER JOIN
                      TABPAGAMENTI ON TESTEDOCUMENTI.CODPAGAMENTO = TABPAGAMENTI.CODICE CROSS JOIN
                      TABDITTE
WHERE     (PARAMETRIDOC.TIPO = 'O' OR
                      PARAMETRIDOC.TIPO = 'B') AND (PARAMETRIDOC.CLIFOR = 'F') AND (TESTEDOCUMENTI.DOCCHIUSO = 0)
GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_Vista_UffAcqDocumentiFornitori] TO [Metodo98]
    AS [dbo];

