create view ald_CDG_MagazziniFiscali
as
SELECT     
 EXTRADEPOSITI.TipologiaMag,
ANAGRAFICADEPOSITI.CODICE, ANAGRAFICADEPOSITI.TIPODEPOSITO, ANAGRAFICADEPOSITI.DISPONIBILE, ANAGRAFICADEPOSITI.DESCRIZIONE, 
                      ANAGRAFICADEPOSITI.INDIRIZZO, ANAGRAFICADEPOSITI.CAP, ANAGRAFICADEPOSITI.LOCALITA, ANAGRAFICADEPOSITI.PROVINCIA, 
                      ANAGRAFICADEPOSITI.TELEFONO, ANAGRAFICADEPOSITI.FAX, ANAGRAFICADEPOSITI.CODNAZIONE, ANAGRAFICADEPOSITI.PRINCIPALE, 
                      ANAGRAFICADEPOSITI.NOTE, ANAGRAFICADEPOSITI.DATAINIVALIDITA, ANAGRAFICADEPOSITI.DATAFINEVALIDITA, ANAGRAFICADEPOSITI.UTENTEMODIFICA, 
                      ANAGRAFICADEPOSITI.DATAMODIFICA, ANAGRAFICADEPOSITI.INTERVALLOPIANIF, ANAGRAFICADEPOSITI.GIORNILAVAZIENDALE, 
                      ANAGRAFICADEPOSITI.GIORNILAVSOLARE, ANAGRAFICADEPOSITI.NUMEROMESICOPERTURA, ANAGRAFICADEPOSITI.TASSOMANTENIMENTOSCORTA, 
                      ANAGRAFICADEPOSITI.FATTORESMORZAMENTO, ANAGRAFICADEPOSITI.FLGSISTRI
FROM         ANAGRAFICADEPOSITI INNER JOIN
                      EXTRADEPOSITI ON ANAGRAFICADEPOSITI.CODICE = EXTRADEPOSITI.CODDEPOSITO
					  where left(codice,1)<>'Z' and TipologiaMag in ('D', 's') and TIPODEPOSITO in(0,2)
					  --order by codice,TipologiaMag

GO
GRANT SELECT
    ON OBJECT::[dbo].[ald_CDG_MagazziniFiscali] TO [Metodo98]
    AS [dbo];

