




CREATE VIEW [dbo].[ALDEBRA_ADI_MANCANTIADIUTO] AS
/*SELEZIONE DOCUMENTI MANCANTI NELLA FAMIGLIA A1003*/
SELECT AVD.* 
FROM 
ALDEBRA_VISTADOCUMENTALE AVD INNER JOIN
PARAMETRIDOC PD ON AVD.TIPODOC=PD.CODICE LEFT OUTER JOIN
Sicura_DATADB.dbo.A1003 FAMDOC ON AVD.KEYUNIQUE=FAMDOC.F1001
WHERE 
/*VENGONO EVIDENZIATI SOLO I TIPIDOC FATTURA A CLIENTE*/
(PD.TIPO='F' OR PD.TIPO='N') AND PD.CLIFOR='C' AND 
/*VIENE ELIMINATO DALLA SELEZIONE TUTTO CIO' CHE E' PRECEDENTE AL 2013*/
AVD.ESERCIZIODOC>=2016 AND
/*VENGONO ELIMINATE LE FATTURE ACCOMPAGNATORIE NON APPARTENENTI ALLA FAM A1003*/
AVD.KEYUNIQUE LIKE 'FV2-%' AND
FAMDOC.F1001 IS NULL
UNION
/*SELEZIONE DOCUMENTI MANCANTI NELLA FAMIGLIA A1004*/
SELECT AVD.* 
FROM 
ALDEBRA_VISTADOCUMENTALE AVD INNER JOIN
PARAMETRIDOC PD ON AVD.TIPODOC=PD.CODICE LEFT OUTER JOIN
Sicura_DATADB.dbo.A1004 FAMDOC ON AVD.KEYUNIQUE=FAMDOC.F1001
WHERE 
/*VENGONO EVIDENZIATI SOLO I TIPIDOC FATTURA A CLIENTE*/
(PD.TIPO='F' OR PD.TIPO='N') AND PD.CLIFOR='C' AND 
/*VIENE ELIMINATO DALLA SELEZIONE TUTTO CIO' CHE E' PRECEDENTE AL 2013*/
AVD.ESERCIZIODOC>=2016 AND
/*VENGONO ELIMINATE LE FATTURE NON APPARTENENTI ALLA FAM A1004*/
AVD.KEYUNIQUE LIKE 'FM2-%' AND
FAMDOC.F1001 IS NULL
UNION
/*SELEZIONE DOCUMENTI MANCANTI NELLA FAMIGLIA A1004*/
SELECT AVD.* 
FROM 
ALDEBRA_VISTADOCUMENTALE AVD INNER JOIN
PARAMETRIDOC PD ON AVD.TIPODOC=PD.CODICE LEFT OUTER JOIN
Sicura_DATADB.dbo.A1004 FAMDOC ON AVD.KEYUNIQUE=FAMDOC.F1001
WHERE 
/*VENGONO EVIDENZIATI SOLO I TIPIDOC FATTURA A CLIENTE*/
(PD.TIPO='F' OR PD.TIPO='N') AND PD.CLIFOR='C' AND 
/*VIENE ELIMINATO DALLA SELEZIONE TUTTO CIO' CHE E' PRECEDENTE AL 2013*/
AVD.ESERCIZIODOC>=2016 AND
/*VENGONO ELIMINATE LE FATTURE NON APPARTENENTI ALLA FAM A1004*/
AVD.KEYUNIQUE LIKE 'FI2-%' AND
FAMDOC.F1001 IS NULL
UNION
/*SELEZIONE DOCUMENTI MANCANTI NELLA FAMIGLIA A1004*/
SELECT AVD.* 
FROM 
ALDEBRA_VISTADOCUMENTALE AVD INNER JOIN
PARAMETRIDOC PD ON AVD.TIPODOC=PD.CODICE LEFT OUTER JOIN
Sicura_DATADB.dbo.A1004 FAMDOC ON AVD.KEYUNIQUE=FAMDOC.F1001
WHERE 
/*VENGONO EVIDENZIATI SOLO I TIPIDOC FATTURA A CLIENTE*/
(PD.TIPO='F' OR PD.TIPO='N') AND PD.CLIFOR='C' AND 
/*VIENE ELIMINATO DALLA SELEZIONE TUTTO CIO' CHE E' PRECEDENTE AL 2013*/
AVD.ESERCIZIODOC>=2016 AND
/*VENGONO ELIMINATE LE FATTURE NON APPARTENENTI ALLA FAM A1004*/
AVD.KEYUNIQUE LIKE 'PA2-%' AND
FAMDOC.F1001 IS NULL



GO
GRANT ALTER
    ON OBJECT::[dbo].[ALDEBRA_ADI_MANCANTIADIUTO] TO [Metodo98]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[ALDEBRA_ADI_MANCANTIADIUTO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALDEBRA_ADI_MANCANTIADIUTO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALDEBRA_ADI_MANCANTIADIUTO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALDEBRA_ADI_MANCANTIADIUTO] TO [Metodo98]
    AS [dbo];

