
create view ALDEBRA_VISTADOCUMENTALE_FeB2BAttive_PERS
as
SELECT   (SELECT     TOP (1) DESBREVE
FROM         TABDITTE) as Azienda,  
(SELECT top 1    PARTITAIVA 
FROM         TABDITTE) as PartitaIvaAzienda, 
TESTEDOCUMENTI.PROGRESSIVO, TESTEDOCUMENTI.ESERCIZIO, TESTEDOCUMENTI.TIPODOC, TESTEDOCUMENTI.NUMERODOC, TESTEDOCUMENTI.BIS, 
                      TESTEDOCUMENTI.DATADOC, TESTEDOCUMENTI.DOCCHIUSO, TESTEDOCUMENTI.SEGNO, TESTEDOCUMENTI.CODCLIFOR, EXTRATESTEDOC.PROGRESSIVOINVIO, 
                      PARAMETRIDOC.CLIFOR
FROM         TESTEDOCUMENTI INNER JOIN
                      EXTRATESTEDOC ON TESTEDOCUMENTI.PROGRESSIVO = EXTRATESTEDOC.IDTESTA INNER JOIN
                      PARAMETRIDOC ON TESTEDOCUMENTI.TIPODOC = PARAMETRIDOC.CODICE
WHERE     (PARAMETRIDOC.CLIFOR = 'C') AND (NOT (EXTRATESTEDOC.PROGRESSIVOINVIO IS NULL) or EXTRATESTEDOC.PROGRESSIVOINVIO=0)
and ESERCIZIO>2017

GO
GRANT SELECT
    ON OBJECT::[dbo].[ALDEBRA_VISTADOCUMENTALE_FeB2BAttive_PERS] TO [Metodo98]
    AS [dbo];

