CREATE VIEW [dbo].[B2B_VISTACLIENTI]
	AS
	SELECT     AC.TIPOCONTO, AC.CODCONTO, AC.DSCCONTO1, AC.DSCCONTO2, AC.CODMASTRO, AC.INDIRIZZO, AC.CAP, AC.LOCALITA, AC.PROVINCIA, AC.TELEFONO, AC.FAX, 
			  AC.TELEX, AC.CODFISCALE, AC.PARTITAIVA, AC.CODNAZIONE, AC.CODICEISO, AC.CODLINGUA, AC.NOTE, AC.UTENTEMODIFICA, AC.DATAMODIFICA, RC.ESERCIZIO, 
			  RC.CODSETTORE, RC.CODZONA, RC.CODCATEGORIA, RC.CODSPED, RC.PRCTRASPORTO, RC.INOLTROTRASP, RC.CODPAG, RC.MESEESCL1, RC.GGESCL1, 
			  RC.MESEESCL2, RC.GGESCL2,
				  (SELECT     CAB
					FROM          dbo.BANCAAPPCF
					WHERE      (CODCONTO = RC.CODCONTO) AND (CODICE = RC.BANCAANAGR)) AS CAB,
				  (SELECT     ABI
					FROM          dbo.BANCAAPPCF AS BANCAAPPCF_1
					WHERE      (CODCONTO = RC.CODCONTO) AND (CODICE = RC.BANCAANAGR)) AS ABI, RC.CODBANCA, RC.BANCAANAGR, RC.CODAGENTE1, RC.CODAGENTE2, 
			  RC.CODAGENTE3, RC.PROVV1, RC.PROVV2, RC.PROVV3, RC.SCONTO1, RC.CODIVA, RC.DICHESIVA, RC.LISTINO, RC.CODCAMBIO, RC.DESTDIVMERCI, 
			  RC.DESTDIVDOCUMENTI, RC.SPESEDOCUM, RC.SPESEEFFETTO, RC.SPESETRASPORTO, RC.SPESEIMBALLO, RC.FIDO, RC.FIDOEURO, RC.PORTO, 
			  RC.TRASPACURA, RC.APPLSCONTORIGA, RC.APPLSCONTOFINALE, RC.CODCONTOFATT, RC.FATTFINEMESE, RC.NONRAGGRUPPDOC, RC.CODDEPOSITO, 
			  RC.CODDEPOSITOCOLL, RC.CODDEPCOMP, RC.CODDEPCOMPCOLL, RC.RIVIVAOMAGGI, RC.NRCONTROPCONT, RC.USAPRZPRVPART, RC.CCDEBITORE, 
			  RC.CODDEBITORE, RC.NOTE1, RC.STATOCONTABILITA, RC.STATOMAGAZZINO, RC.STATOORDINI, RC.STATOBOLLE, RC.STATOFATTURE, RC.STATONOTEACCREDITO,
			   RC.STATOALTRO, RC.CODGRUPPOPREZZIPART, RC.CODGRUPPOPROVPART, RC.RAGGSCADENZE
	FROM         dbo.ANAGRAFICACF AS AC INNER JOIN
						  dbo.ANAGRAFICARISERVATICF AS RC ON AC.CODCONTO = RC.CODCONTO INNER JOIN
						  (Select codconto from TABB2BCFLogins group by codconto) AS TB2 ON AC.CODCONTO = TB2.CodConto
	WHERE     (RC.ESERCIZIO =
							  (SELECT     ESERCIZIOATTIVO
								FROM          dbo.TABUTENTI
								WHERE      (USERDB = USER_NAME()))) AND (AC.TIPOCONTO = 'C')

GO
GRANT DELETE
    ON OBJECT::[dbo].[B2B_VISTACLIENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[B2B_VISTACLIENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[B2B_VISTACLIENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[B2B_VISTACLIENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[B2B_VISTACLIENTI] TO [Metodo98]
    AS [dbo];

