CREATE VIEW BudVistaBudget3Varianti AS 
    SELECT T1.TIPOLOGIA AS TIP1, T1.VARIANTE AS VAR1, T2.TIPOLOGIA AS TIP2, T2.VARIANTE AS VAR2, 
           T3.TIPOLOGIA AS TIP3, T3.VARIANTE AS VAR3
    FROM TABVARIANTI T1, TABVARIANTI T2, TABVARIANTI T3

GO
GRANT SELECT
    ON OBJECT::[dbo].[BudVistaBudget3Varianti] TO [Metodo98]
    AS [dbo];

