

CREATE VIEW COMMCLI_STRUTTURA_COMMESSE  AS
SELECT   
(CASE WHEN X8.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X8.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X7.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X7.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X6.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X6.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X5.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X5.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X4.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X4.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X3.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X3.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X2.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X2.CODLIV,'')+'                    ') ,20)END) +
(CASE WHEN X1.CODLIV IS NULL THEN '' ELSE LEFT( (ISNULL(X1.CODLIV,'')+'                    ') ,20)END) +

LEFT(ISNULL(AA.CODLIV,''),20) AS XXAA,

AA.*
FROM     (((((((  TABSTRUTTCONSCOMM AA
LEFT OUTER JOIN   TABSTRUTTCONSCOMM X1 ON AA.LIVPADRE = X1.CODLIV AND AA.RIFCOMMCLI = X1.RIFCOMMCLI AND AA.LIV = X1.LIV+1)
LEFT OUTER JOIN   TABSTRUTTCONSCOMM X2 ON X1.LIVPADRE = X2.CODLIV AND X1.RIFCOMMCLI = X2.RIFCOMMCLI AND X1.LIV = X2.LIV+1)
LEFT OUTER JOIN   TABSTRUTTCONSCOMM X3 ON X2.LIVPADRE = X3.CODLIV AND X2.RIFCOMMCLI = X3.RIFCOMMCLI AND X2.LIV = X3.LIV+1)
LEFT OUTER JOIN   TABSTRUTTCONSCOMM X4 ON X3.LIVPADRE = X4.CODLIV AND X3.RIFCOMMCLI = X4.RIFCOMMCLI AND X3.LIV = X4.LIV+1)
LEFT OUTER JOIN   TABSTRUTTCONSCOMM X5 ON X4.LIVPADRE = X5.CODLIV AND X4.RIFCOMMCLI = X5.RIFCOMMCLI AND X4.LIV = X5.LIV+1)
LEFT OUTER JOIN   TABSTRUTTCONSCOMM X6 ON X5.LIVPADRE = X6.CODLIV AND X5.RIFCOMMCLI = X6.RIFCOMMCLI AND X5.LIV = X6.LIV+1)
LEFT OUTER JOIN TABSTRUTTCONSCOMM x7 ON x6.LIVPADRE = x7.CODLIV and x6.RIFCOMMCLI = x7.RIFCOMMCLI) 
LEFT OUTER JOIN TABSTRUTTCONSCOMM x8 ON x7.LIVPADRE = x8.CODLIV and x7.RIFCOMMCLI = x8.RIFCOMMCLI 


GO
GRANT SELECT
    ON OBJECT::[dbo].[COMMCLI_STRUTTURA_COMMESSE] TO [Metodo98]
    AS [dbo];

