

CREATE VIEW CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE
AS
SELECT     RIFPROGRESSIVOCL, RIFPROGRESSIVO, SUM(TOTALENETTO) AS Expr1
FROM         dbo.CONTRATTICL_QTAMERCE
GROUP BY RIFPROGRESSIVOCL, RIFPROGRESSIVO


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_SOMMATORIAQTAMERCE] TO [Metodo98]
    AS [dbo];

