
CREATE VIEW [dbo].[CONTRATTILIQUIDAZIONE_CLPERCCONDATA]
AS
SELECT     TOP (100) PERCENT 'INCONDIZIONATI-COND' AS TIPOCONTRIBUTO, dbo.CONTRATTI_CL.RIFPROGRESSIVO AS RifContratto, 
                      dbo.CONTRATTI_CL.NRRIGA AS RifContributo, dbo.CONTRATTICL_QTA.NRRIGA AS RIFSOTTORIGA, 0 AS RIFSOTTORIGACOND, 
                      dbo.CONTRATTI_CL.DESCRIZIONE AS NOTA, 'PERCENTUALE' AS TIPOLOGIA, CONVERT(varchar, dbo.CONTRATTICL_QTA.DADATA, 105) AS DADATA, 
                      CONVERT(varchar, dbo.CONTRATTICL_QTA.ADATA, 105) AS ADATA, 0 AS BudgetQta, '' AS Um, dbo.CONTRATTICL_QTA.BUDGET AS BudgetValore, 
                      0 AS BudgetQtaConValore, '' AS UmQtaConValore, dbo.CONTRATTI_CL.VALORE AS PREMIOVALORE, 
                      dbo.CONTRATTICL_QTA.PERCENTUALE AS PREMIOPERCENTUALE, 0 AS CONSUNTIVATOQTA, dbo.CONTRATTICL_QTA.CONSUNTIVO AS CONSUNTIVATOVALORE, 
                      dbo.CONTRATTICL_QTA.PREMIOMATURATO, dbo.CONTRATTICL_QTA.PERIODICITALIQUIDAZIONE, CASE WHEN dbo.CONTRATTICL_QTA.TIPO IS NULL 
                      THEN 1 ELSE dbo.CONTRATTICL_QTA.TIPO END AS TIPO, dbo.CONTRATTI_CL.TIPOCALCOLOPREMIO, dbo.CONTRATTICL_QTADATEDOC.DATAEMISSIONE, 
                      dbo.CONTRATTICL_QTADATEDOC.VALORE, dbo.CONTRATTICL_QTADATEDOC.EMESSO, dbo.CONTRATTICL_QTADATEDOC.RIFPROGRESSIVODOC, 
                      dbo.CONTRATTICL_QTADATEDOC.NRRIGA AS RIGARATA, dbo.CONTRATTICL_QTADATEDOC.VALOREEFFETTIVO, dbo.CONTRATTICL_QTA.PREMIONONVALIDO
FROM         dbo.CONTRATTI_CL INNER JOIN
                      dbo.CONTRATTICL_QTA ON dbo.CONTRATTI_CL.RIFPROGRESSIVO = dbo.CONTRATTICL_QTA.RIFPROGRESSIVOCL AND 
                      dbo.CONTRATTI_CL.NRRIGA = dbo.CONTRATTICL_QTA.RIFPROGRESSIVO INNER JOIN
                      dbo.CONTRATTICL_QTADATEDOC ON dbo.CONTRATTICL_QTA.RIFPROGRESSIVOCL = dbo.CONTRATTICL_QTADATEDOC.RIFPROGRESSIVOCL AND 
                      dbo.CONTRATTICL_QTA.RIFPROGRESSIVO = dbo.CONTRATTICL_QTADATEDOC.RIFPROGRESSIVO AND 
                      dbo.CONTRATTICL_QTA.NRRIGA = dbo.CONTRATTICL_QTADATEDOC.RIFRIGA
WHERE     (dbo.CONTRATTI_CL.BOLISPERC = 1) AND (dbo.CONTRATTI_CL.ESCLUSOLOGICAMENTE = 0)
ORDER BY RifContratto, RifContributo, RIFSOTTORIGA


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTILIQUIDAZIONE_CLPERCCONDATA] TO [Metodo98]
    AS [dbo];

