
CREATE VIEW [dbo].[DA Head Report Comparison] AS 


SELECT '' AS [timestamp]
      ,[Progressivo] AS [No_]
      ,'CBI' AS [Report]
      ,0 AS [Type]
      ,CASE WHEN ISNULL([Nome],'')='' THEN 'Senza Nome' ELSE [Nome] END AS [Report Name]
      ,[AmbienteRif] AS [Environment Code]
      ,[AnnoInizioRif] AS [Start Year]
      ,[MeseInizioRif] AS [Start Month]
      ,[AnnoFineRif] AS [End Year]
      ,[MeseFineRif] AS [End Month]
      ,[DesIntestazione] AS [Header]
      ,[TipoRiclassificazione] AS [Type Refiling Code]
      ,'' AS [Destination No_]
      ,'' AS [Destination Description]
      ,'' AS [Type Description]
      ,'' AS [Division Description]
      ,'' AS [Responsible Description]
      ,'' AS [UM1 Description]
      ,'' AS [UM2 Description]
      ,'' AS [UM1 Sec_ Description]
      ,'' AS [UM2 Sec_ Description]
      ,0 AS [Type Destination Typology]
      ,0 AS [Measurement Type]
      ,'' AS [Description Foot 1]
      ,'' AS [Description Foot 2]
      ,'' AS [Description Foot 3]
      ,'' AS [Description Foot 4]
      ,'' AS [Description Foot 5]
      ,0 AS [Production 1 01]
      ,0 AS [Production 1 02]
      ,0 AS [Production 1 03]
      ,0 AS [Production 1 04]
      ,0 AS [Variable Index 1 01]
      ,0 AS [Variable Index 1 02]
      ,0 AS [Variable Index 1 03]
      ,0 AS [Variable Index 1 04]
      ,0 AS [Production 2 01]
      ,0 AS [Production 2 02]
      ,0 AS [Production 2 03]
      ,0 AS [Production 2 04]
      ,0 AS [Fixed Index 2 01]
      ,0 AS [Fixed Index 2 02]
      ,0 AS [Fixed Index 2 03]
      ,0 AS [Fixed Index 2 04]
      ,0 AS [Production Sec_ 1 01]
      ,0 AS [Production Sec_ 1 02]
      ,0 AS [Production Sec_ 1 03]
      ,0 AS [Production Sec_ 1 04]
      ,0 AS [Variable Index Sec_ 1 01]
      ,0 AS [Variable Index Sec_ 1 02]
      ,0 AS [Variable Index Sec_ 1 03]
      ,0 AS [Variable Index Sec_ 1 04]
      ,0 AS [Production Sec_ 2 01]
      ,0 AS [Production Sec_ 2 02]
      ,0 AS [Production Sec_ 2 03]
      ,0 AS [Production Sec_ 2 04]
      ,0 AS [Fixed Index Sec_ 2 01]
      ,0 AS [Fixed Index Sec_ 2 02]
      ,0 AS [Fixed Index Sec_ 2 03]
      ,0 AS [Fixed Index Sec_ 2 04]
      ,0 AS [Variable Index 1 01 SA]
      ,0 AS [Variable Index 1 02 SA]
      ,0 AS [Variable Index 1 03 SA]
      ,0 AS [Variable Index 1 04 SA]
      ,0 AS [Fixed Index 2 01 SA]
      ,0 AS [Fixed Index 2 02 SA]
      ,0 AS [Fixed Index 2 03 SA]
      ,0 AS [Fixed Index 2 04 SA]
      ,0 AS [Variable Index Sec_ 1 01 SA]
      ,0 AS [Variable Index Sec_ 1 02 SA]
      ,0 AS [Variable Index Sec_ 1 03 SA]
      ,0 AS [Variable Index Sec_ 1 04 SA]
      ,0 AS [Fixed Index Sec_ 2 01 SA]
      ,0 AS [Fixed Index Sec_ 2 02 SA]
      ,0 AS [Fixed Index Sec_ 2 03 SA]
      ,0 AS [Fixed Index Sec_ 2 04 SA]
      ,0 AS [Variable Index 1 01 SP]
      ,0 AS [Variable Index 1 02 SP]
      ,0 AS [Variable Index 1 03 SP]
      ,0 AS [Variable Index 1 04 SP]
      ,0 AS [Fixed Index 2 01 SP]
      ,0 AS [Fixed Index 2 02 SP]
      ,0 AS [Fixed Index 2 03 SP]
      ,0 AS [Fixed Index 2 04 SP]
      ,0 AS [Variable Index Sec_ 1 01 SP]
      ,0 AS [Variable Index Sec_ 1 02 SP]
      ,0 AS [Variable Index Sec_ 1 03 SP]
      ,0 AS [Variable Index Sec_ 1 04 SP]
      ,0 AS [Fixed Index Sec_ 2 01 SP]
      ,0 AS [Fixed Index Sec_ 2 02 SP]
      ,0 AS [Fixed Index Sec_ 2 03 SP]
      ,0 AS [Fixed Index Sec_ 2 04 SP]
      ,[AmbienteC1] AS [Environment Code C1]
      ,[AnnoInizioC1] AS [Start Year C1]
      ,[MeseInizioC1] AS [Start Month C1]
      ,[AnnoFineC1] AS [End Year C1]
      ,[MeseFineC1] AS [End Month C1]
      ,[AmbienteC2] AS [Environment Code C2]
      ,[AnnoInizioC2] AS [Start Year C2]
      ,[MeseInizioC2] AS [Start Month C2]
      ,[AnnoFineC2] AS [End Year C2]
      ,[MeseFineC2] AS [End Month C2]
      ,[AmbienteC3] AS [Environment Code C3]
      ,[AnnoInizioC3] AS [Start Year C3]
      ,[MeseInizioC3] AS [Start Month C3]
      ,[AnnoFineC3] AS [End Year C3]
      ,[MeseFineC3] AS [End Month C3]
FROM CGesConfrontoBilancioTeste
UNION ALL
SELECT '' AS [timestamp]
      ,[Progressivo] + 1000000000 AS [No_]
      ,CASE WHEN [TipoReport]=0 THEN 'CAI' ELSE 'CAG' END AS [Report]
      ,0 AS [Type]
      ,CASE WHEN ISNULL([Nome],'')='' THEN 'Senza Nome' ELSE [Nome] END AS [Report Name]
      ,[AmbienteRif] AS [Environment Code]
      ,[AnnoInizioRif] AS [Start Year]
      ,[MeseInizioRif] AS [Start Month]
      ,[AnnoFineRif] AS [End Year]
      ,[MeseFineRif] AS [End Month]
      ,[DesIntestazione] AS [Header]
      ,[TipoRiclassificazione] AS [Type Refiling Code]
      ,[CodDestinazione] AS [Destination No_]
      ,[DesDestinazione] AS [Destination Description]
      ,[DesTipo] AS [Type Description]
      ,[DesDivisione] AS [Division Description]
      ,[DesResponsabile] AS [Responsible Description]
      ,[DesUM1] AS [UM1 Description]
      ,[DesUM2] AS [UM2 Description]
      ,[DesUM1Sec] AS [UM1 Sec_ Description]
      ,[DesUM2Sec] AS [UM2 Sec_ Description]
      ,[TipoDestinazione] AS [Type Destination Typology]
      ,[TipoMisurazione] AS [Measurement Type]
      ,[DesPiede1] AS [Description Foot 1]
      ,[DesPiede2] AS [Description Foot 2]
      ,[DesPiede3] AS [Description Foot 3]
      ,[DesPiede4] AS [Description Foot 4]
      ,[DesPiede5] AS [Description Foot 5]
      ,[Produzione101] AS [Production 1 01]
      ,[Produzione102] AS [Production 1 02]
      ,[Produzione103] AS [Production 1 03]
      ,[Produzione104] AS [Production 1 04]
      ,[IndiceVar101] AS [Variable Index 1 01]
      ,[IndiceVar102] AS [Variable Index 1 02]
      ,[IndiceVar103] AS [Variable Index 1 03]
      ,[IndiceVar104] AS [Variable Index 1 04]
      ,[Produzione201] AS [Production 2 01]
      ,[Produzione202] AS [Production 2 02]
      ,[Produzione203] AS [Production 2 03]
      ,[Produzione204] AS [Production 2 04]
      ,[IndiceFis201] AS [Fixed Index 2 01]
      ,[IndiceFis202] AS [Fixed Index 2 02]
      ,[IndiceFis203] AS [Fixed Index 2 03]
      ,[IndiceFis204] AS [Fixed Index 2 04]
      ,[Produzione1Sec01] AS [Production Sec_ 1 01]
      ,[Produzione1Sec02] AS [Production Sec_ 1 02]
      ,[Produzione1Sec03] AS [Production Sec_ 1 03]
      ,[Produzione1Sec04] AS [Production Sec_ 1 04]
      ,[IndiceVar1Sec01] AS [Variable Index Sec_ 1 01]
      ,[IndiceVar1Sec02] AS [Variable Index Sec_ 1 02]
      ,[IndiceVar1Sec03] AS [Variable Index Sec_ 1 03]
      ,[IndiceVar1Sec04] AS [Variable Index Sec_ 1 04]
      ,[Produzione2Sec01] AS [Production Sec_ 2 01]
      ,[Produzione2Sec02] AS [Production Sec_ 2 02]
      ,[Produzione2Sec03] AS [Production Sec_ 2 03]
      ,[Produzione2Sec04] AS [Production Sec_ 2 04]
      ,[IndiceFis2Sec01] AS [Fixed Index Sec_ 2 01]
      ,[IndiceFis2Sec02] AS [Fixed Index Sec_ 2 02]
      ,[IndiceFis2Sec03] AS [Fixed Index Sec_ 2 03]
      ,[IndiceFis2Sec04] AS [Fixed Index Sec_ 2 04]
      ,[SAIndiceVar101] AS [Variable Index 1 01 SA]
      ,[SAIndiceVar102] AS [Variable Index 1 02 SA]
      ,[SAIndiceVar103] AS [Variable Index 1 03 SA]
      ,[SAIndiceVar104] AS [Variable Index 1 04 SA]
      ,[SAIndiceFis201] AS [Fixed Index 2 01 SA]
      ,[SAIndiceFis202] AS [Fixed Index 2 02 SA]
      ,[SAIndiceFis203] AS [Fixed Index 2 03 SA]
      ,[SAIndiceFis204] AS [Fixed Index 2 04 SA]
      ,[SAIndiceVar1Sec01] AS [Variable Index Sec_ 1 01 SA]
      ,[SAIndiceVar1Sec02] AS [Variable Index Sec_ 1 02 SA]
      ,[SAIndiceVar1Sec03] AS [Variable Index Sec_ 1 03 SA]
      ,[SAIndiceVar1Sec04] AS [Variable Index Sec_ 1 04 SA]
      ,[SAIndiceFis2Sec01] AS [Fixed Index Sec_ 2 01 SA]
      ,[SAIndiceFis2Sec02] AS [Fixed Index Sec_ 2 02 SA]
      ,[SAIndiceFis2Sec03] AS [Fixed Index Sec_ 2 03 SA]
      ,[SAIndiceFis2Sec04] AS [Fixed Index Sec_ 2 04 SA]
      ,[SPIndiceVar101] AS [Variable Index 1 01 SP]
      ,[SPIndiceVar102] AS [Variable Index 1 02 SP]
      ,[SPIndiceVar103] AS [Variable Index 1 03 SP]
      ,[SPIndiceVar104] AS [Variable Index 1 04 SP]
      ,[SPIndiceFis201] AS [Fixed Index 2 01 SP]
      ,[SPIndiceFis202] AS [Fixed Index 2 02 SP]
      ,[SPIndiceFis203] AS [Fixed Index 2 03 SP]
      ,[SPIndiceFis204] AS [Fixed Index 2 04 SP]
      ,[SPIndiceVar1Sec01] AS [Variable Index Sec_ 1 01 SP]
      ,[SPIndiceVar1Sec02] AS [Variable Index Sec_ 1 02 SP]
      ,[SPIndiceVar1Sec03] AS [Variable Index Sec_ 1 03 SP]
      ,[SPIndiceVar1Sec04] AS [Variable Index Sec_ 1 04 SP]
      ,[SPIndiceFis2Sec01] AS [Fixed Index Sec_ 2 01 SP]
      ,[SPIndiceFis2Sec02] AS [Fixed Index Sec_ 2 02 SP]
      ,[SPIndiceFis2Sec03] AS [Fixed Index Sec_ 2 03 SP]
      ,[SPIndiceFis2Sec04] AS [Fixed Index Sec_ 2 04 SP]
      ,[AmbienteC1] AS [Environment Code C1]
      ,[AnnoInizioC1] AS [Start Year C1]
      ,[MeseInizioC1] AS [Start Month C1]
      ,[AnnoFineC1] AS [End Year C1]
      ,[MeseFineC1] AS [End Month C1]
      ,[AmbienteC2] AS [Environment Code C2]
      ,[AnnoInizioC2] AS [Start Year C2]
      ,[MeseInizioC2] AS [Start Month C2]
      ,[AnnoFineC2] AS [End Year C2]
      ,[MeseFineC2] AS [End Month C2]
      ,[AmbienteC3] AS [Environment Code C3]
      ,[AnnoInizioC3] AS [Start Year C3]
      ,[MeseInizioC3] AS [Start Month C3]
      ,[AnnoFineC3] AS [End Year C3]
      ,[MeseFineC3] AS [End Month C3]
FROM CGesConfrontoAnalisiIndividualeTeste
  

GO
GRANT SELECT
    ON OBJECT::[dbo].[DA Head Report Comparison] TO [Metodo98]
    AS [dbo];

