

CREATE VIEW DF_AC_ORDINI
AS

SELECT T.[PROGRESSIVO]
      ,T.[ESERCIZIO]
      ,T.[TIPODOC]
      ,T.[NUMERODOC]
      ,T.[BIS]
      ,T.[DATADOC]
      ,T.[DOCCHIUSO]
      ,T.[CODCLIFOR]
      ,T.[NUMRIFDOC]
      ,T.[DATARIFDOC]
      ,T.[CODLISTINO]
      ,T.[CODAGENTE1]
      ,T.[CODAGENTE2]
      ,T.[CODAGENTE3]
      ,R.[IDRIGA]
      ,R.[CODART]
      ,R.[DESCRIZIONEART]
      ,R.[UMGEST]
      ,R.[QTAGEST]
      ,R.[QTAGESTRES]
      ,R.[NUMLISTINO]
      ,L.[PREZZOEURO]
      ,R.[PREZZOUNITNETTO]
      ,R.[TOTNETTORIGAEURO]
      ,R.[SCONTIESTESI]
      ,G.[DESCRIZIONE] AS GRUPPO
      ,C.[DESCRIZIONE] AS CATEGORIA
      ,S.[DESCRIZIONE] AS CATEGORIASTAT
  FROM [PARAMETRIDOC] P
  INNER JOIN [TESTEDOCUMENTI] T ON P.TIPO IN('O') AND P.CLIFOR = 'C' AND P.CODICE = T.TIPODOC 
  INNER JOIN [RIGHEDOCUMENTI] R ON R.IDTESTA = T.PROGRESSIVO
  INNER JOIN [ANAGRAFICAARTICOLI] A ON A.CODICE = R.CODART 
  LEFT JOIN [TABGRUPPI] G ON G.CODICE = A.GRUPPO
  LEFT JOIN [TABCATEGORIE] C ON C.CODICE = A.CATEGORIA 
  LEFT JOIN [TABCATEGORIESTAT] S ON S.CODICE = A.CODCATEGORIASTAT
  LEFT JOIN [LISTINIARTICOLI] L ON L.CODART = R.CODART AND L.UM = R.UMPREZZO AND L.NRLISTINO = R.NUMLISTINO
        

GO
GRANT SELECT
    ON OBJECT::[dbo].[DF_AC_ORDINI] TO [Metodo98]
    AS [dbo];

