
CREATE VIEW [dbo].[FRCVistaDocumentiVenditeDettaglioCF] AS 
	SELECT YEAR(TESTEDOCUMENTI.DATADOC) AS ANNODOC, MONTH(TESTEDOCUMENTI.DATADOC) AS MESEDOC, LTRIM(STR(YEAR(TESTEDOCUMENTI.DATADOC))) + CASE WHEN MONTH(TESTEDOCUMENTI.DATADOC) 
		   <= 9 THEN ('0' + LTRIM(STR(MONTH(TESTEDOCUMENTI.DATADOC)))) ELSE LTRIM(STR(MONTH(TESTEDOCUMENTI.DATADOC))) END AS ANNOMESEDOC, 
		   ANAGRAFICACF.TIPOCONTO, TESTEDOCUMENTI.CODCFFATT, LEFT(ANAGRAFICACF.DSCCONTO1, 80) AS DSCCONTO1, LEFT(ANAGRAFICACF.DSCCONTO1, 80) 
		   + ' - ' + TESTEDOCUMENTI.CODCFFATT AS CLIENTE, ISNULL(ANAGRAFICARISERVATICF.CODSETTORE, 0) AS CODSETTORE, LEFT(ISNULL(TABSETTORI.DESCRIZIONE, ''), 25) AS DESCSETTCLI, 
		   ISNULL(ANAGRAFICARISERVATICF.CODZONA, 0) AS CODZONA, LEFT(ISNULL(TABZONE.DESCRIZIONE, ''), 80) AS DESCZONACLI, ISNULL(ANAGRAFICARISERVATICF.CODCATEGORIA, 0) AS CODCATEGORIA, 
		   LEFT(ISNULL(CATEGORIECF.DSCCATEGORIA, ''), 25) AS DESCCATCLI, LEFT(ISNULL(ANAGRAFICACF.LOCALITA, ''), 80) AS LOCALITA, ISNULL(ANAGRAFICACF.PROVINCIA, '') AS PROVINCIA, 
		   ISNULL(ANAGRAFICACF.CODNAZIONE, 0) AS CODNAZIONE, ISNULL(ANAGRAFICACF.CODICEISO, '') AS CODICEISO, ISNULL(ANAGRAFICACF.CODREGIONE, '') AS CODREGIONE, 
		   ISNULL(TESTEDOCUMENTI.CODAGENTE1, '') AS CODAGENTE1, LEFT(ISNULL(ANAGRAFICAAGENTI_1.DSCAGENTE, ''), 80) AS DSCAGENTE1, 
		   LEFT(ISNULL(ANAGRAFICAAGENTI_1.DSCAGENTE, ''), 80) + ' - ' + ISNULL(TESTEDOCUMENTI.CODAGENTE1, '') AS AGENTE1, ISNULL(TESTEDOCUMENTI.CODAGENTE2, '') AS CODAGENTE2, 
		   LEFT(ISNULL(ANAGRAFICAAGENTI_2.DSCAGENTE, ''), 80) AS DSCAGENTE2, LEFT(ISNULL(ANAGRAFICAAGENTI_2.DSCAGENTE, ''), 80) + ' - ' + ISNULL(TESTEDOCUMENTI.CODAGENTE2, '') 
		   AS AGENTE2, ISNULL(TESTEDOCUMENTI.CODAGENTE3, '') AS CODAGENTE3, LEFT(ISNULL(ANAGRAFICAAGENTI_3.DSCAGENTE, ''), 80) AS DSCAGENTE3, LEFT(ISNULL(ANAGRAFICAAGENTI_3.DSCAGENTE, ''), 80) 
		   + ' - ' + ISNULL(TESTEDOCUMENTI.CODAGENTE3, '') AS AGENTE3, (TESTEDOCUMENTI.TOTSPESETRASP * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS TOTSPESETRASP, 
		   RIGHEDOCUMENTI.CODART, LEFT(FRCVistaArticoli.DESCRIZIONE, 500) AS DESCRIZIONE, LEFT(FRCVistaArticoli.ARTICOLO, 203) AS ARTICOLO, FRCVistaArticoli.GRUPPO, LEFT(FRCVistaArticoli.DESCGRPART, 80) AS DESCGRPART, FRCVistaArticoli.CATEGORIA, 
		   LEFT(FRCVistaArticoli.DESCCATART, 80) AS DESCCATART, FRCVistaArticoli.CODCATEGORIASTAT, LEFT(FRCVistaArticoli.DESCCATSTATART, 80) AS DESCCATSTATART, FRCVistaArticoli.SERIE, LEFT(FRCVistaArticoli.DESCSERIEART, 100) AS DESCSERIEART, FRCVistaArticoli.MODELLO, 
		   LEFT(FRCVistaArticoli.DESCMODART, 100) AS DESCMODART, FRCVistaArticoli.PESONETTO, FRCVistaArticoli.SUPERFICIE, FRCVistaArticoli.CUBATURA, FRCVistaArticoli.NRPEZZIIMBALLO, FRCVistaArticoli.RIFERIMIMBALLO, 
		   FRCVistaArticoli.UM_VENDITA, FRCVistaArticoli.UM_BASE, ISNULL(ARTICOLIFATTORICONVERSIONE.FATTORE, 1) AS FATTORE, 
		   FRCVistaArticoli.TIPOUM, RIGHEDOCUMENTI.UMGEST, (RIGHEDOCUMENTI.QTAGEST * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS QTAGEST, 
		   RIGHEDOCUMENTI.UMPREZZO, (RIGHEDOCUMENTI.QTAPREZZO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS QTAPREZZO, RIGHEDOCUMENTI.CODIVA, 
		   LEFT(ISNULL(TRATTAMENTOIVA.DESCRIZIONE, ''), 25) AS DESCIVA, ISNULL(TRATTAMENTOIVA.ALIQUOTA, 0) AS ALIQUOTA, ISNULL(TRATTAMENTOIVA.INDETRAIBILITA, 0) AS INDETRAIBILITA, 
		   ISNULL((CASE WHEN FRCDatiVariAzienda.AzzeraRicaviOmaggi = 0 THEN RIGHEDOCUMENTI.TOTLORDORIGAEURO ELSE 0 END * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) AS TOTLORDORIGAEURO, 
		   ISNULL((CASE WHEN FRCDatiVariAzienda.AzzeraRicaviOmaggi = 0 THEN (RIGHEDOCUMENTI.TOTLORDORIGAEURO - RIGHEDOCUMENTI.TOTNETTORIGAEURO) ELSE 0 END * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) AS TOTSCONTORIGAEURO, 
		   ISNULL((CASE WHEN FRCDatiVariAzienda.AzzeraRicaviOmaggi = 0 THEN RIGHEDOCUMENTI.TOTNETTORIGAEURO ELSE 0 END * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) AS TOTNETTORIGAEURO, 
		   ISNULL((RIGHEDOCUMENTI.TOTPROVVAGEURO1 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) AS TOTPROVVAGEURO1, 
		   CASE WHEN ISNULL((RIGHEDOCUMENTI.TOTNETTORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) <> 0 THEN 
		   ISNULL((RIGHEDOCUMENTI.TOTPROVVAGEURO1 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) / 
		   ISNULL((RIGHEDOCUMENTI.TOTNETTORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) * 100 ELSE 0 END AS PERCPROVVAGEURO1, 
		   ISNULL((RIGHEDOCUMENTI.TOTPROVVAGEURO2 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) AS TOTPROVVAGEURO2, 
		   CASE WHEN ISNULL((RIGHEDOCUMENTI.TOTNETTORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) <> 0 THEN 
		   ISNULL((RIGHEDOCUMENTI.TOTPROVVAGEURO2 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) / 
		   ISNULL((RIGHEDOCUMENTI.TOTNETTORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) * 100 ELSE 0 END AS PERCPROVVAGEURO2, 
		   ISNULL((RIGHEDOCUMENTI.TOTPROVVAGEURO3 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) AS TOTPROVVAGEURO3, 
		   CASE WHEN ISNULL((RIGHEDOCUMENTI.TOTNETTORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) <> 0 THEN 
		   ISNULL((RIGHEDOCUMENTI.TOTPROVVAGEURO3 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) / 
		   ISNULL((RIGHEDOCUMENTI.TOTNETTORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) * 100 ELSE 0 END AS PERCPROVVAGEURO3, 
		   ISNULL(RIGHEDOCUMENTI.GENCONTROP, '') AS GENCONTROP, LEFT(ISNULL(ANAGRAFICAGENERICI.DSCCONTO1, ''), 80) AS DESCGENCONTROP, ISNULL(TABMASTRI.CODICE, 0) AS CODMASTRO, 
		   ISNULL(TABMASTRI.TIPO, '') AS TIPOMASTRO, ISNULL(RIGHEDOCUMENTI.CONTOCDC, '') AS CONTOCDC, LEFT((SELECT DESCRIZIONE FROM TABNAZIONI WHERE CODICE = ISNULL(ANAGRAFICACF.CODNAZIONE, 0)), 80) AS NAZIONE, 
		   RIGHEDOCUMENTI.RIFCOMMCLI, (SELECT TOP 1 RIFCOMMRIEP FROM AnagraficaCommesse WHERE Riferimento = RIGHEDOCUMENTI.RIFCOMMCLI) AS RIFCOMMRIEP, 
		   RIGHEDOCUMENTI.MESEINIZIOCOMP AS MESEDOCUMENTO, ANAGRAFICACF.TipoClienteBudget, RIGHEDOCUMENTI.IDTESTA, RIGHEDOCUMENTI.IDRIGA, RIGHEDOCUMENTI.TIPODOC, LEFT(PARAMETRIDOC.DESCRIZIONE, 80) AS DESTIPODOCUMENTO, 
		   RIGHEDOCUMENTI.ESERCIZIO, RIGHEDOCUMENTI.NUMERODOC, RIGHEDOCUMENTI.BIS, TESTEDOCUMENTI.DATADOC, RIGHEDOCUMENTI.ANNOINIZIOCOMP, LTRIM(STR(RIGHEDOCUMENTI.ANNOINIZIOCOMP)) + CASE WHEN RIGHEDOCUMENTI.MESEINIZIOCOMP 
		   <= 9 THEN ('0' + LTRIM(STR(RIGHEDOCUMENTI.MESEINIZIOCOMP))) ELSE LTRIM(STR(RIGHEDOCUMENTI.MESEINIZIOCOMP)) END AS ANNOMESECOMP, 
		   (TESTEDOCUMENTI.TOTSPESEIMBALLOEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS SpeseImballo, 
		   (TESTEDOCUMENTI.TOTSPESETRASPEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS SpeseTrasporto, 
		   (TESTEDOCUMENTI.SCONTOINCONDEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS ScontoIncondizionato, 
		   (TESTEDOCUMENTI.TOTSPESEEFFETTOEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS SpeseEffetto, 
		   (TESTEDOCUMENTI.TOTSPESEDOCEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS SpeseDocumento, TESTEDOCUMENTI.INCIDENZASCONTI, 
		   CASE WHEN ISNULL(((SELECT SUM(ISNULL(TOTNETTORIGAEURO, 0)) FROM RIGHEDOCUMENTI T1 WHERE T1.IDTESTA = TESTEDOCUMENTI.PROGRESSIVO) * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) = 0 THEN 1 ELSE 
		   ((SELECT SUM(ISNULL(TOTNETTORIGAEURO, 0)) FROM RIGHEDOCUMENTI T1 WHERE T1.IDTESTA = TESTEDOCUMENTI.PROGRESSIVO) * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) END AS TotaleImponibile, 
		   (TESTEDOCUMENTI.TOTPROVVAGEURO1 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) - ((SELECT SUM(ISNULL(TOTPROVVAGEURO1, 0)) FROM RIGHEDOCUMENTI T1 
		   WHERE T1.IDTESTA = TESTEDOCUMENTI.PROGRESSIVO) * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS TOTPROVVTESTAAGEURO1, 
		   (TESTEDOCUMENTI.TOTPROVVAGEURO2 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) - ((SELECT SUM(ISNULL(TOTPROVVAGEURO2, 0)) FROM RIGHEDOCUMENTI T1 
		   WHERE T1.IDTESTA = TESTEDOCUMENTI.PROGRESSIVO) * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS TOTPROVVTESTAAGEURO2, 
		   (TESTEDOCUMENTI.TOTPROVVAGEURO3 * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) - ((SELECT SUM(ISNULL(TOTPROVVAGEURO3, 0)) FROM RIGHEDOCUMENTI T1 
		   WHERE T1.IDTESTA = TESTEDOCUMENTI.PROGRESSIVO) * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)) AS TOTPROVVTESTAAGEURO3 
	FROM PARAMETRIDOC INNER JOIN TESTEDOCUMENTI INNER JOIN RIGHEDOCUMENTI ON TESTEDOCUMENTI.PROGRESSIVO = RIGHEDOCUMENTI.IDTESTA ON 
		 PARAMETRIDOC.CODICE = TESTEDOCUMENTI.TIPODOC INNER JOIN TABMASTRI INNER JOIN ANAGRAFICAGENERICI ON TABMASTRI.CODICE = ANAGRAFICAGENERICI.CODMASTRO ON 
		 RIGHEDOCUMENTI.GENCONTROP = ANAGRAFICAGENERICI.CODCONTO INNER JOIN TRATTAMENTOIVA ON RIGHEDOCUMENTI.CODIVA = TRATTAMENTOIVA.CODICE INNER JOIN
		 FRCVistaArticoli ON RIGHEDOCUMENTI.CODART = FRCVistaArticoli.CODART LEFT OUTER JOIN TABSETTORI RIGHT OUTER JOIN CATEGORIECF RIGHT OUTER JOIN
		 TABZONE RIGHT OUTER JOIN ANAGRAFICARISERVATICF ON TABZONE.CODICE = ANAGRAFICARISERVATICF.CODZONA ON 
		 CATEGORIECF.CODCATEGORIA = ANAGRAFICARISERVATICF.CODCATEGORIA ON TABSETTORI.CODICE = ANAGRAFICARISERVATICF.CODSETTORE ON
		 TESTEDOCUMENTI.CODCFFATT = ANAGRAFICARISERVATICF.CODCONTO AND TESTEDOCUMENTI.ESERCIZIO = ANAGRAFICARISERVATICF.ESERCIZIO LEFT OUTER JOIN
		 ANAGRAFICAAGENTI AS ANAGRAFICAAGENTI_1 ON TESTEDOCUMENTI.CODAGENTE1 = ANAGRAFICAAGENTI_1.CODAGENTE LEFT OUTER JOIN
		 ANAGRAFICAAGENTI AS ANAGRAFICAAGENTI_2 ON TESTEDOCUMENTI.CODAGENTE2 = ANAGRAFICAAGENTI_2.CODAGENTE LEFT OUTER JOIN
		 ANAGRAFICAAGENTI AS ANAGRAFICAAGENTI_3 ON TESTEDOCUMENTI.CODAGENTE3 = ANAGRAFICAAGENTI_3.CODAGENTE LEFT OUTER JOIN
		 ANAGRAFICACF ON TESTEDOCUMENTI.CODCFFATT = ANAGRAFICACF.CODCONTO 
		 LEFT OUTER JOIN ARTICOLIFATTORICONVERSIONE ON ARTICOLIFATTORICONVERSIONE.CODART = RIGHEDOCUMENTI.CODART AND 
		 ARTICOLIFATTORICONVERSIONE.UM1 = RIGHEDOCUMENTI.UMGEST AND ARTICOLIFATTORICONVERSIONE.UM2 = FRCVistaArticoli.UM_BASE, FRCDatiVariAzienda
	WHERE TESTEDOCUMENTI.TIPODOC IN (SELECT TipoDocumento FROM FRCTipiDocVendite)
	      AND ISNULL((RIGHEDOCUMENTI.TOTLORDORIGAEURO * TESTEDOCUMENTI.SEGNO * (CASE WHEN ANAGRAFICACF.TIPOCONTO = 'C' THEN 1 ELSE -1 END)), 0) <> 0


GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaDocumentiVenditeDettaglioCF] TO [Metodo98]
    AS [dbo];

