CREATE VIEW FRCVistaDCDistinteMancantiCC AS 
	SELECT * FROM FRCVistaArticoliVB
	WHERE NOT EXISTS (SELECT COMPOSTO FROM FRCDistinteCicliEsplose WHERE COMPOSTO = COMPONENTE AND COMPOSTO = FRCVistaArticoliVB.CODART AND ANNO = FRCVistaArticoliVB.ANNODOC)
	      AND ISNULL((SELECT PROVENIENZA FROM ANAGRAFICAARTICOLIPROD WHERE CODICEART = FRCVistaArticoliVB.CODART AND ESERCIZIO = YEAR(GETDATE())), 0) <> 0

GO
GRANT SELECT
    ON OBJECT::[dbo].[FRCVistaDCDistinteMancantiCC] TO [Metodo98]
    AS [dbo];

