

CREATE VIEW [GEM_VistaTotaleOreIntLavorate]
AS
SELECT     IDRAPPORTO, SUM(OREORD) AS TOreOrd, SUM(ORESTRA) AS TOreStrord, 
SUM(OREVIAGGIO) AS TOreViag, SUM(TRASFERTA) AS TTrasf, SUM(KM) AS TKm
FROM         GEM_SEZIONECONTRATTORAPPORTI_OreLavoroINTERNE
GROUP BY IDRAPPORTO

GO
GRANT SELECT
    ON OBJECT::[dbo].[GEM_VistaTotaleOreIntLavorate] TO [Metodo98]
    AS [dbo];

