
create VIEW [dbo].[GEM_VistaTotaliRateContratto]
AS
SELECT     GEM_SEZIONECONTRATTO_RATE.IDCONTRATTO, GEM_SEZIONECONTRATTO_RATE.NUMERORATA, GEM_SEZIONECONTRATTO_RATE.DATA_PREV, 
                      GEM_SEZIONECONTRATTO_RATE.DATA_EFF, GEM_SEZIONECONTRATTO_RATE.DATA_FATT, GEM_SEZIONECONTRATTO_RATE.STATO, 
                      GEM_SEZIONECONTRATTO_RATE.DA_FATT, GEM_SEZIONECONTRATTO_RATE.IMPRATASFS, GEM_SEZIONECONTRATTO_RATE.SCONTO, 
                      GEM_SEZIONECONTRATTO_RATE.PROVVIGIONE1, GEM_SEZIONECONTRATTO_RATE.PROVVIGIONE2, 
                      GEM_SEZIONECONTRATTO_RATE.PROVVIGIONE3, GEM_SEZIONECONTRATTO_RATE.DescrizioneRata, GEM_SEZIONECONTRATTO_RATE.Note, 
                      GEM_SEZIONECONTRATTO_RATE.ELIMINATO, GEM_SEZIONECONTRATTO_RATE.NUMERO_RFW, 
                      GEM_SEZIONECONTRATTO_RATE.UTENTEMODIFICA, GEM_SEZIONECONTRATTO_RATE.DATAMODIFICA, 
                      GEM_TESTACONTRATTO.CODCLIENTE AS CLIENTE, GEM_TESTACONTRATTO.CODCLIFAT, GEM_TESTACONTRATTO.DATACONTRATTO, 
                      GEM_TESTACONTRATTO.CodAgente1, GEM_TESTACONTRATTO.CodAgente3, GEM_TESTACONTRATTO.CodAgente2, ANAGRAFICACF.DSCCONTO1
FROM         GEM_TESTACONTRATTO INNER JOIN
                      GEM_SEZIONECONTRATTO_RATE ON GEM_TESTACONTRATTO.IDCONTRATTO = GEM_SEZIONECONTRATTO_RATE.IDCONTRATTO INNER JOIN
                      ANAGRAFICACF ON GEM_TESTACONTRATTO.CODCLIENTE = ANAGRAFICACF.CODCONTO

GO
GRANT DELETE
    ON OBJECT::[dbo].[GEM_VistaTotaliRateContratto] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GEM_VistaTotaliRateContratto] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GEM_VistaTotaliRateContratto] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GEM_VistaTotaliRateContratto] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GEM_VistaTotaliRateContratto] TO [Metodo98]
    AS [dbo];

