CREATE VIEW Matika_VistaControlloMatricoleDoc as
SELECT RIGHEDOCMATRICOLE.CODMATRICOLA, Matika_VistaControlloMatricole.QtàMatricola, Matika_VistaControlloMatricole.SITUAZIONE, 
RIGHEDOCUMENTI.CODART, RIGHEDOCUMENTI.DESCRIZIONEART, RIGHEDOCMATRICOLE.IDTESTA, TESTEDOCUMENTI.ESERCIZIO, TESTEDOCUMENTI.TIPODOC, 
TESTEDOCUMENTI.NUMERODOC, ANAGRAFICACF.CODCONTO, ANAGRAFICACF.DSCCONTO1
FROM (((RIGHEDOCMATRICOLE INNER JOIN TESTEDOCUMENTI ON RIGHEDOCMATRICOLE.IDTESTA = TESTEDOCUMENTI.PROGRESSIVO) 
INNER JOIN ANAGRAFICACF ON TESTEDOCUMENTI.CODCLIFOR = ANAGRAFICACF.CODCONTO) INNER JOIN RIGHEDOCUMENTI ON (RIGHEDOCMATRICOLE.IDRIGA = RIGHEDOCUMENTI.IDRIGA) AND (RIGHEDOCMATRICOLE.IDTESTA = RIGHEDOCUMENTI.IDTESTA)) INNER JOIN Matika_VistaControlloMatricole ON RIGHEDOCMATRICOLE.CODMATRICOLA = Matika_VistaControlloMatricole.CODMATRICOLA


GO
GRANT DELETE
    ON OBJECT::[dbo].[Matika_VistaControlloMatricoleDoc] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[Matika_VistaControlloMatricoleDoc] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[Matika_VistaControlloMatricoleDoc] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[Matika_VistaControlloMatricoleDoc] TO [Metodo98]
    AS [dbo];

