
CREATE VIEW dbo.Matika_VistaSottoSCORTA1
AS SELECT VISTAINVENTARIO.CODART, 
    ANAGRAFICAARTICOLI.DESCRIZIONE, 
    SUM(VISTAINVENTARIO.CARICO - VISTAINVENTARIO.SCARICO - VISTAINVENTARIO.RESODACARICO
     + VISTAINVENTARIO.RESODASCARICO) AS giacenza, 
    SUM(VISTAINVENTARIO.ORDINATO) AS ordinato, 
    SUM(VISTAINVENTARIO.IMPEGNATO) AS impegnato, 
    MAX(ANAGRAFICAARTICOLIPROD.SCORTAMIN) 
    AS SCORTAMIN, 
    MAX(ANAGRAFICAARTICOLIPROD.SCORTAMAX) 
    AS SCORTAMAX
FROM ANAGRAFICAARTICOLIPROD INNER JOIN
    ANAGRAFICAARTICOLI INNER JOIN
    VISTAINVENTARIO ON 
    ANAGRAFICAARTICOLI.CODICE = VISTAINVENTARIO.CODART ON
     ANAGRAFICAARTICOLIPROD.ESERCIZIO = VISTAINVENTARIO.ESERCIZIO
     AND 
    ANAGRAFICAARTICOLIPROD.CODICEART = VISTAINVENTARIO.CODART
     INNER JOIN
    ANAGRAFICADEPOSITI ON 
    VISTAINVENTARIO.CODDEPOSITO = ANAGRAFICADEPOSITI.CODICE
GROUP BY VISTAINVENTARIO.CODART, 
    ANAGRAFICAARTICOLI.DESCRIZIONE


GO
GRANT DELETE
    ON OBJECT::[dbo].[Matika_VistaSottoSCORTA1] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[Matika_VistaSottoSCORTA1] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[Matika_VistaSottoSCORTA1] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[Matika_VistaSottoSCORTA1] TO [Metodo98]
    AS [dbo];

