CREATE VIEW MATRICOLEDISPONIBILI AS
SELECT 
	SM.CODART,
    SM.NRIFPARTITA,
	SMM.CODMATRICOLA,
	SUM(((CASE WHEN SM.GIACENZA=1 and SM.RESO = 0 THEN 1 ELSE 0 END)-
         (CASE WHEN SM.GIACENZA=-1 and SM.RESO = 0 THEN 1 ELSE 0 END)+
         (CASE WHEN SM.GIACENZA=1 and SM.RESO = 1 THEN 1 ELSE 0 END)-
         (CASE WHEN SM.GIACENZA=-1 and SM.RESO = 1 THEN 1 ELSE 0 END))+
         (SM.ORDINATO)-(SM.IMPEGNATO)) AS QUANTITA
FROM 
	STORICOMAGMATRICOLE SMM INNER JOIN STORICOMAG SM ON SMM.PROGRESSIVO=SM.PROGRESSIVO
GROUP BY 
	SM.CODART,
	SM.NRIFPARTITA,
	SMM.CODMATRICOLA
HAVING
	SUM(((CASE WHEN SM.GIACENZA=1 and SM.RESO = 0 THEN 1 ELSE 0 END)-
         (CASE WHEN SM.GIACENZA=-1 and SM.RESO = 0 THEN 1 ELSE 0 END)+
         (CASE WHEN SM.GIACENZA=1 and SM.RESO = 1 THEN 1 ELSE 0 END)-
         (CASE WHEN SM.GIACENZA=-1 and SM.RESO = 1 THEN 1 ELSE 0 END))+
         (SM.ORDINATO)-(SM.IMPEGNATO))=1

GO
GRANT SELECT
    ON OBJECT::[dbo].[MATRICOLEDISPONIBILI] TO [Metodo98]
    AS [dbo];

