

CREATE VIEW PL_VISTAPACKINGRIGHEAPERTI
  AS SELECT PL_PACKINGRIGHE.*
     FROM PL_PACKINGRIGHE INNER JOIN PL_PACKINGTESTA ON  
          PL_PACKINGRIGHE.RifProgressivo = PL_PACKINGTESTA.Progressivo 
     WHERE PL_PACKINGTESTA.CHIUSO=0



GO
GRANT SELECT
    ON OBJECT::[dbo].[PL_VISTAPACKINGRIGHEAPERTI] TO [Metodo98]
    AS [dbo];

