

CREATE VIEW PL_VISTASELTESTEDOC
  AS SELECT TD.*,CF.CODNAZIONE AS CODNAZIONE,PD.TIPO AS TIPOPAR 
     FROM TESTEDOCUMENTI TD 
          INNER JOIN TABUTENTI ON USERDB = CAST(USER_NAME() AS VARCHAR(25))
          INNER JOIN ANAGRAFICACF CF ON TD.CODCLIFOR = CF.CODCONTO 
          INNER JOIN PARAMETRIDOC PD ON TD.TIPODOC = PD.CODICE 
     WHERE (SUPERVISOR = 1 OR 
           (SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSIDOCUMENTI WHERE CODDOCUMENTO = TD.TIPODOC AND FLAGABILITA=1))) 
     AND ((TD.CODCLIFOR=TABUTENTI.CODCLIFOR) OR (TABUTENTI.CODCLIFOR=''))
     AND TD.DOCCHIUSO = 0 AND TD.BLOCCATO = 0

GO
GRANT SELECT
    ON OBJECT::[dbo].[PL_VISTASELTESTEDOC] TO [Metodo98]
    AS [dbo];

