
create view TDA_VISTACONSOLIDAMENTO as
	select 
		FUN.RIFCAUSALE as CAUSALE,
		FUN.PRIORITA,
		FUN.FUNZIONE,
		FUN.TIPO,
		(case TIPO
			when 0 then (select PLUGINCONS from TDA_FUNZIONITEMPO FT where FT.CODICE=FUN.FUNZIONE)
			when 1 then (select PLUGINCONS from TDA_FUNZIONIQUANTITA FQ where FQ.CODICE=FUN.FUNZIONE)
			when 2 then (select PLUGINCONS from TDA_FUNZIONIPRESENZA FP where FP.CODICE=FUN.FUNZIONE)
			when 3 then (select PLUGINCONS from TDA_FUNZIONIMATERIALE FM where FM.CODICE=FUN.FUNZIONE)
			when 4 then (select PLUGINCONS from TDA_FUNZIONIALTRE FA where FA.CODICE=FUN.FUNZIONE)
		end) as PLUGINCONS
	from 
		TDA_FUNZIONIFEEDBACK FUN;

GO
GRANT SELECT
    ON OBJECT::[dbo].[TDA_VISTACONSOLIDAMENTO] TO [Metodo98]
    AS [dbo];

