create view TP_GIROVISITE
AS
SELECT     TP_GIROVISITE_TESTA.CODAGENTE, TP_GIROVISITE_RIGHE.CODCONTO, TP_GIROVISITE_RIGHE.OrarioPMAM, 
                      TP_GIROVISITE_RIGHE.Periodicita, TP_GIROVISITE_RIGHE.OrarioVisite, TP_GIROVISITE_RIGHE.Giorno
FROM         TP_GIROVISITE_TESTA INNER JOIN
                      TP_GIROVISITE_RIGHE ON TP_GIROVISITE_TESTA.Progressivo = TP_GIROVISITE_RIGHE.RIFProgressivo

GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_GIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_GIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_GIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_GIROVISITE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_GIROVISITE] TO [Metodo98]
    AS [dbo];

