
CREATE VIEW TP_LISTINI
AS
SELECT TABLISTINI.*,TABCAMBI.DIVISA,TABCAMBI.DESCRIZIONE AS DESCRDIVISA FROM TABLISTINI
INNER JOIN TABCAMBI ON
	TABCAMBI.CODICE=TABLISTINI.CODCAMBIO



GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_LISTINI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_LISTINI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_LISTINI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_LISTINI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_LISTINI] TO [Metodo98]
    AS [dbo];

