

CREATE VIEW TP_VISTATMPRIGHEDOCDACHIUDEREMISS AS

  SELECT DISTINCT
         TMPTDOC.IDSESSIONE,TABTESTEMISSIONI.PROGRESSIVO AS PROGRMISS,
         TABTESTEMISSIONI.ESERCIZIO AS ESERCMISS,TABTESTEMISSIONI.NUMEROMISS,TABTESTEMISSIONI.DESCRMISS,
         TABTESTEMISSIONI.DATAMISS,TABTESTEMISSIONI.CODDEPOSITO AS DEPMISS,
         TMPTDOC.PROGRESSDOC,TMPTDOC.RIFPROGRTESTAMISS,
         TESTEDOCUMENTI.TIPODOC,TESTEDOCUMENTI.ESERCIZIO,
		 TESTEDOCUMENTI.NUMERODOC,TESTEDOCUMENTI.NUMRIFDOC,TESTEDOCUMENTI.BIS,
		 TESTEDOCUMENTI.DATADOC,TESTEDOCUMENTI.CODCLIFOR,ANAGRAFICACF.DSCCONTO1,
		 TESTEDOCUMENTI.NUMDESTDIVERSAMERCI,TESTEDOCUMENTI.RAGSOCDDM,
		 TESTEDOCUMENTI.INDIRIZZODDM,TESTEDOCUMENTI.CAPDDM,TESTEDOCUMENTI.LOCALITADDM,TESTEDOCUMENTI.PROVINCIADDM,
         TMPRDOC.IDRIGADOC,TMPRDOC.CODART,TMPRDOC.DESCART,TMPRDOC.UM,TMPRDOC.QTAORD,TMPRDOC.DATACONSEGNA FROM 
         TMPTABTESTEDOCUMENTIMISS TMPTDOC INNER JOIN TMPTABRIGHEDOCUMENTIMISS TMPRDOC ON 
         TMPTDOC.PROGRESSIVO = TMPRDOC.IDTESTA AND 
         TMPTDOC.IDSESSIONE = TMPRDOC.IDSESSIONE
         INNER JOIN TABTESTEMISSIONI ON TMPTDOC.RIFPROGRTESTAMISS=TABTESTEMISSIONI.PROGRESSIVO
  	     INNER JOIN TESTEDOCUMENTI ON TMPTDOC.PROGRESSDOC=TESTEDOCUMENTI.PROGRESSIVO
	     INNER JOIN ANAGRAFICACF ON TESTEDOCUMENTI.CODCLIFOR=ANAGRAFICACF.CODCONTO
  WHERE
  TMPRDOC.RIGACHIUSA=2 AND TMPRDOC.FLGMANCANTE=0 AND
  (TMPRDOC.QTACONSEG > 0 OR TMPRDOC.QTAMANCANTE > 0) 




GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTATMPRIGHEDOCDACHIUDEREMISS] TO [Metodo98]
    AS [dbo];

