
Create view [dbo].[TP_VISTAPREVISIONI_TOTALI] 
as

SELECT
	CODARTICOLO,
	TIPO,
	SUM(PREVISIONE) AS PREVISIONE
FROM
(
	SELECT
		TSP.CODARTICOLO,
		TEM.TIPO,
		(CASE WHEN TEM.QTAPREVISIONIFORZATE <> 0 THEN TEM.QTAPREVISIONIFORZATE ELSE TSP.[1] END) AS PREVISIONE
	FROM
		(
			SELECT 
				CODART,
				(
				CASE GESTSTAG 
					WHEN 0 THEN	(
								CASE OFSMOOTHINGSTAGIONALE
									WHEN 0 THEN 'MQ'
									WHEN 1 THEN 'WT'
								END
								)
					WHEN 1 THEN	(
								CASE OFTIPOPREVISIONALE
									WHEN 0 THEN 'SE'
									WHEN 1 THEN 'MM'
								END
								)
					WHEN 2 THEN	'SM'
					WHEN 3 THEN 'PR'
				END
				) AS TIPO,
				QTAPREVISIONIFORZATE
			FROM 
				TP_EXTRAMAG
		) TEM,
		TP_STAGIONALE_PREVISIONI TSP
	WHERE
		TSP.CODARTICOLO = TEM.CODART AND
		TSP.TIPO = TEM.TIPO 
) PREVISIONI_TOTALI
GROUP BY
	CODARTICOLO,
	TIPO

GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTAPREVISIONI_TOTALI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTAPREVISIONI_TOTALI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_VISTAPREVISIONI_TOTALI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAPREVISIONI_TOTALI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTAPREVISIONI_TOTALI] TO [Metodo98]
    AS [dbo];

