

CREATE VIEW [dbo].[TP_VISTAQTACONFDOCEURITMO]
AS
SELECT
    TIPOQUANTITA.IDTESTA,
    TIPOQUANTITA.IDRIGA,
    TIPOQUANTITA.TIPO,
    TIPOQUANTITA.QTAGEST AS QTAORD,
    TIPOQUANTITA.QTAGEST AS QTACONF
FROM
(
SELECT
     RGD.IDTESTA,RGD.IDRIGA,
    (CASE RGD.QTAGEST
        WHEN 0 THEN 'A'
        ELSE 'M'
     END
    ) AS TIPO,
    RGD.QTAGEST AS QTAORIGORDINE,
    RGD.QTAGEST
FROM RIGHEDOCUMENTI RGD
WHERE
    RGD.IDTESTA IN( SELECT PROGRESSIVO 
                    FROM TESTEDOCUMENTI 
                    WHERE CODCLIFOR IN(SELECT CODICE from TabCliForEuritmo)
                      AND TIPODOC   IN(SELECT CODICE FROM TabDocumentiEuritmo)  
                      AND ESERCIZIO IN(SELECT CODICE FROM TabEserciziEuritmo) 
                   ) AND
    
    RGD.TIPORIGA IN ('N','O')
) TIPOQUANTITA

GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAQTACONFDOCEURITMO] TO [Metodo98]
    AS [dbo];

