
CREATE VIEW TP_VISTACUCS
AS
SELECT  STORICOMAG.CODART,
		STORICOMAG.CODDEPOSITO,
		STORICOMAG.CODCLIFOR,
		ANAGRAFICACF.DSCCONTO1,
		STORICOMAG.DATAMOV, 
		STORICOMAG.TIPODOC, 
		STORICOMAG.CODCAUSALE,
		STORICOMAG.IMPORTOTOTLORDOVAL,
		STORICOMAG.IMPORTOTOTNETTOVAL,
		RIGHEDOCUMENTI.PREZZOUNITNETTO,
		RIGHEDOCUMENTI.PREZZOUNITLORDO,
		RIGHEDOCUMENTI.SCONTIESTESI,
		STORICOMAG.QTA1UM
FROM         STORICOMAG 
	INNER JOIN ANAGRAFICACF 
		ON ANAGRAFICACF.CODCONTO = STORICOMAG.CODCLIFOR
	INNER JOIN TP_EXTRAMAG
		ON STORICOMAG.CODART=TP_EXTRAMAG.CODART AND TP_EXTRAMAG.CONSIDACQ=1
	INNER JOIN RIGHEDOCUMENTI
		ON RIGHEDOCUMENTI.IDTESTA = STORICOMAG.idtesta AND RIGHEDOCUMENTI.IDRIGA=STORICOMAG.rigadoc 
WHERE STORICOMAG.TIPODOC<>''

GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTACUCS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTACUCS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_VISTACUCS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTACUCS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTACUCS] TO [Metodo98]
    AS [dbo];

