

CREATE VIEW [dbo].[TP_VISTASCTLOGARTCTRVAL]
AS
SELECT      
    TP_TESTE_SCONTI_LOGISTICICTR.DADATA, 
    TP_TESTE_SCONTI_LOGISTICICTR.ADATA, 
    TP_TESTE_SCONTI_LOGISTICICTR.CODCLIFOR, 
    TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO,
    TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIASCONTO,  
    TP_TESTE_SCONTI_LOGISTICICTR.TIPO_TOTALE,
    TP_TESTE_SCONTI_LOGISTICICTR.RifContratto,
    TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR.ARTICOLO,
    TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR.CODARTRIC, 
    TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR.UM, 
    TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR.VALORE, 
    TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR.SCONTO
FROM         
    TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR 
INNER JOIN 
    TP_TESTE_SCONTI_LOGISTICICTR ON TP_RIGHE_SCONTI_LOGISTICI_ARTICOLOCTR.RIFPROGRESSIVO = TP_TESTE_SCONTI_LOGISTICICTR.PROGRESSIVO
WHERE     
    (TP_TESTE_SCONTI_LOGISTICICTR.TIPOLOGIADETTAGLIO = 4)


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASCTLOGARTCTRVAL] TO [Metodo98]
    AS [dbo];

