
CREATE VIEW TP_VISTATESTEDOC_EXPORTDOC AS 
SELECT  TD.PROGRESSIVO,TD.ESERCIZIO,
	    TD.TIPODOC,TD.NUMERODOC,TD.BIS,TD.DATADOC,
	    TD.DOCCHIUSO,TD.BLOCCATO,TD.CODCLIFOR,
	    TD.NUMRIFDOC,TD.DATARIFDOC,
	    TD.CODAGENTE1,TD.CODAGENTE2,
	    TD.CODAGENTE3,TD.CODBANCAINCASSO,
	    TD.CODLISTINO,TD.CODLINGUA,
	    TD.NUMDESTDIVERSAMERCI,TD.CODPAGAMENTO,
	    TD.CODCAMBIO,TD.VALCAMBIO,
	    TD.SCONTOFINALE,TD.CODCFFATT,
	    TD.PRCPROVVAG1,TD.PRCPROVVFINALEAG1,
	    TD.PRCPROVVAG2,TD.PRCPROVVFINALEAG2,
	    TD.PRCPROVVAG3,TD.PRCPROVVFINALEAG3,
	    PARAMETRIDOC.TIPO AS TIPOPAR,
	    ANAGRAFICACF.DSCCONTO1 AS RAGSOCCF,
	    ANAGRAFICARISERVATICF.CODCATEGORIA AS CODCATEGORIACF,
	    ANAGRAFICACF.CODNAZIONE,
	    ANAGRAFICARISERVATICF.CODSETTORE,
	    ANAGRAFICARISERVATICF.CODZONA,
	    TC.DIVISA,
	    TC.DESCRIZIONE AS DSCDIVISA, 
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTPROVVAG1*TD.SEGNO ELSE TD.TOTPROVVAG1/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVFINALEAG1,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTPROVVAG2*TD.SEGNO ELSE TD.TOTPROVVAG2/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVFINALEAG2,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTPROVVAG3*TD.SEGNO ELSE TD.TOTPROVVAG3/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVFINALEAG3,
	    TD.TOTPROVVAG1    *TD.SEGNO AS TOTPROVVFINALEAG1VALUTA,
	    TD.TOTPROVVAG2    *TD.SEGNO AS TOTPROVVFINALEAG2VALUTA,
	    TD.TOTPROVVAG3    *TD.SEGNO AS TOTPROVVFINALEAG3VALUTA,
	    TD.TOTPROVVAGEURO1*TD.SEGNO AS TOTPROVVFINALEAG1EURO,
	    TD.TOTPROVVAGEURO2*TD.SEGNO AS TOTPROVVFINALEAG2EURO,
	    TD.TOTPROVVAGEURO3*TD.SEGNO AS TOTPROVVFINALEAG3EURO,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTPROVVAG1RES*TD.SEGNO ELSE TD.TOTPROVVAG1RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVFINALEAG1RES,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTPROVVAG2RES*TD.SEGNO ELSE TD.TOTPROVVAG2RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVFINALEAG2RES,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTPROVVAG3RES*TD.SEGNO ELSE TD.TOTPROVVAG3RES/TD.VALCAMBIO/TC.CAMBIOEURO*TCAM.CAMBIOEURO*TD.SEGNO END) AS TOTPROVVFINALEAG3RES,
	    TD.TOTPROVVAG1RES    *TD.SEGNO AS TOTPROVVFINALEAG1VALUTARES,
	    TD.TOTPROVVAG2RES    *TD.SEGNO AS TOTPROVVFINALEAG2VALUTARES,
	    TD.TOTPROVVAG3RES    *TD.SEGNO AS TOTPROVVFINALEAG3VALUTARES,
	    TD.TOTPROVVAGEURO1RES*TD.SEGNO AS TOTPROVVFINALEAG1EURORES,
	    TD.TOTPROVVAGEURO2RES*TD.SEGNO AS TOTPROVVFINALEAG2EURORES,
	    TD.TOTPROVVAGEURO3RES*TD.SEGNO AS TOTPROVVFINALEAG3EURORES,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTIMPONIBILE *TD.SEGNO ELSE TD.TOTIMPONIBILE/TD.VALCAMBIO/TC.CAMBIOEURO *TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTIMPONIBILE,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTIMPOSTA    *TD.SEGNO ELSE TD.TOTIMPOSTA/TD.VALCAMBIO/TC.CAMBIOEURO    *TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTIMPOSTA,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTDOCUMENTO  *TD.SEGNO ELSE TD.TOTDOCUMENTO/TD.VALCAMBIO/TC.CAMBIOEURO  *TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTDOCUMENTO,
	    TD.TOTIMPONIBILEEURO *TD.SEGNO AS TOTIMPONIBILEEURO,
	    TD.TOTIMPOSTAEURO    *TD.SEGNO AS TOTIMPOSTAEURO,
	    TD.TOTDOCUMENTOEURO  *TD.SEGNO AS TOTDOCUMENTOEURO,
	    TD.TOTIMPONIBILE     *TD.SEGNO AS TOTIMPONIBILEVALUTA,
	    TD.TOTIMPOSTA        *TD.SEGNO AS TOTIMPOSTAVALUTA,
	    TD.TOTDOCUMENTO      *TD.SEGNO AS TOTDOCVALUTA,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTDOCUMENTORES  *TD.SEGNO ELSE TD.TOTDOCUMENTORES/TD.VALCAMBIO/TC.CAMBIOEURO  *TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTDOCUMENTORES,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTIMPONIBILERES *TD.SEGNO ELSE TD.TOTIMPONIBILERES/TD.VALCAMBIO/TC.CAMBIOEURO *TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTIMPONIBILERES,
	    (CASE WHEN TD.CODCAMBIO=0 THEN TD.TOTIMPOSTARES    *TD.SEGNO ELSE TD.TOTIMPOSTARES/TD.VALCAMBIO/TC.CAMBIOEURO    *TD.SEGNO*TCAM.CAMBIOEURO END) AS TOTIMPOSTARES,
	    TD.TOTIMPONIBILEEURORES *TD.SEGNO AS TOTIMPONIBILEEURORES,
	    TD.TOTIMPOSTAEURORES    *TD.SEGNO AS TOTIMPOSTAEURORES,
	    TD.TOTDOCUMENTOEURORES  *TD.SEGNO AS TOTDOCUMENTOEURORES,
	    TD.TOTIMPONIBILERES     *TD.SEGNO AS TOTIMPONIBILEVALUTARES,
	    TD.TOTIMPOSTARES        *TD.SEGNO AS TOTIMPOSTAVALUTARES,
	    TD.TOTDOCUMENTORES      *TD.SEGNO AS TOTDOCVALUTARES,
	    TE.ESPORTATO
FROM
		(
			(
				(
					(
						(
							(TESTEDOCUMENTI AS TD JOIN PARAMETRIDOC ON TD.TIPODOC=PARAMETRIDOC.CODICE)
						JOIN TP_ESPORTATI_EXPORTDOC AS TE On TD.PROGRESSIVO = TE.PROGRESSIVO)
					JOIN TABCAMBI AS TC ON TD.CODCAMBIO=TC.CODICE)
				JOIN ANAGRAFICACF ON TD.CODCLIFOR=ANAGRAFICACF.CODCONTO)
			JOIN ANAGRAFICARISERVATICF ON ANAGRAFICARISERVATICF.CODCONTO=TD.CODCLIFOR AND ANAGRAFICARISERVATICF.ESERCIZIO=TD.ESERCIZIO)
		INNER JOIN  TABUTENTI ON USERDB = USER_NAME()), 
	TABCAMBI AS TCAM
WHERE 	(TCAM.CODICE=0) AND 
		(SUPERVISOR = 1 OR 
			(SUPERVISOR = 0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSIDOCUMENTI WHERE CODDOCUMENTO = TD.TIPODOC AND FLAGVISUALIZZA=1)
			)
		)
AND (
		(TD.CODCLIFOR=TABUTENTI.CODCLIFOR) OR (TABUTENTI.CODCLIFOR='')
	)




GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTATESTEDOC_EXPORTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTATESTEDOC_EXPORTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTATESTEDOC_EXPORTDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTATESTEDOC_EXPORTDOC] TO [Metodo98]
    AS [dbo];

