
CREATE VIEW [dbo].[TP_VISTAAGENDAUTENTEORDINI]
AS

SELECT
	TAOUT.PROGRESSIVO,
	TAOUT.UTENTE,
	TAOUT.SUPERVISOR,
	TAOUR.CODCLIENTE,
	TAOUR.DESTDIV,
	TAOUR.GIORNO,
	TAOUR.ORA
FROM
	TP_AGENDAUTENTEORDINI_T TAOUT,
	TP_AGENDAUTENTEORDINI_R TAOUR
WHERE
	TAOUR.RIFPROGRESSIVO = TAOUT.PROGRESSIVO

GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAAGENDAUTENTEORDINI] TO [Metodo98]
    AS [dbo];

