
CREATE VIEW [dbo].[TP_VISTASINONIMI]

AS


	SELECT 
		  TS.*
		, AA.DESCRIZIONE AS DESCART 
		, AA.GRUPPO
		, AA.CATEGORIA
		, AA.CODCATEGORIASTAT
		, AAC.GRUPPOPRZPART
		, TEM.CODFAMIGLIAPOS
		, TEM.CODREPARTOPOS
	FROM 
		  TP_SINONIMI TS
		, ANAGRAFICAARTICOLI AA
		, ANAGRAFICAARTICOLICOMM AAC
		, TP_EXTRAMAG TEM
	WHERE
		    AA.CODICE = TS.CODICE
		AND	AAC.CODICEART = AA.CODICE
		AND AAC.ESERCIZIO = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME())
		AND TEM.CODART = AA.CODICE


GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTASINONIMI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTASINONIMI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASINONIMI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTASINONIMI] TO [Metodo98]
    AS [dbo];

