
CREATE VIEW dbo.TP_VISTAARTICOLIINPROMOZIONEWITHDESC
AS
SELECT     dbo.TP_VISTAARTICOLIINPROMOZIONE.NumeroPromozione, dbo.TP_VISTAARTICOLIINPROMOZIONE.Descrizione, 
                      dbo.TP_VISTAARTICOLIINPROMOZIONE.Codice AS Articolo, dbo.ANAGRAFICAARTICOLI.CODICE, dbo.ANAGRAFICAARTICOLI.DESCRIZIONE AS DescArt, 
                      dbo.TP_VISTAARTICOLIINPROMOZIONE.Data_inizio, dbo.TP_VISTAARTICOLIINPROMOZIONE.Data_fine, dbo.TP_PROMOZIONI_TESTE.CLIFOR
FROM         dbo.TP_VISTAARTICOLIINPROMOZIONE LEFT OUTER JOIN
                      dbo.TP_PROMOZIONI_TESTE ON 
                      dbo.TP_VISTAARTICOLIINPROMOZIONE.NumeroPromozione = dbo.TP_PROMOZIONI_TESTE.Progressivo LEFT OUTER JOIN
                      dbo.ANAGRAFICAARTICOLI ON dbo.ANAGRAFICAARTICOLI.CODICE LIKE REPLACE(dbo.TP_VISTAARTICOLIINPROMOZIONE.Codice, '?', '_')

GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTAARTICOLIINPROMOZIONEWITHDESC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTAARTICOLIINPROMOZIONEWITHDESC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[TP_VISTAARTICOLIINPROMOZIONEWITHDESC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAARTICOLIINPROMOZIONEWITHDESC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTAARTICOLIINPROMOZIONEWITHDESC] TO [Metodo98]
    AS [dbo];

