CREATE VIEW [dbo].[TP_VISTASCTLOGCATVAL]
AS
SELECT     TP_TESTE_SCONTI_LOGISTICI.PROGRESSIVO, TP_TESTE_SCONTI_LOGISTICI.DADATA, TP_TESTE_SCONTI_LOGISTICI.ADATA, 
                      TP_TESTE_SCONTI_LOGISTICI.CODCLIFOR, TP_TESTE_SCONTI_LOGISTICI.TIPOLOGIADETTAGLIO,TP_TESTE_SCONTI_LOGISTICI.TIPOLOGIASCONTO,
                      TP_TESTE_SCONTI_LOGISTICI.TIPO_TOTALE,TP_TESTE_SCONTI_LOGISTICI.RifContratto, 
                      ANAGRAFICAARTICOLI.CODICE, 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIA.UM, TP_RIGHE_SCONTI_LOGISTICI_CATEGORIA.VALORE, 
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIA.SCONTO
FROM         TP_TESTE_SCONTI_LOGISTICI INNER JOIN
                      TP_RIGHE_SCONTI_LOGISTICI_CATEGORIA ON 
                      TP_TESTE_SCONTI_LOGISTICI.PROGRESSIVO = TP_RIGHE_SCONTI_LOGISTICI_CATEGORIA.RIFPROGRESSIVO INNER JOIN
                      ANAGRAFICAARTICOLI ON dbo.TP_RIGHE_SCONTI_LOGISTICI_CATEGORIA.CATEGORIA = ANAGRAFICAARTICOLI.CATEGORIA
WHERE     (TP_TESTE_SCONTI_LOGISTICI.TIPOLOGIADETTAGLIO = 1) AND (ANAGRAFICAARTICOLI.CATEGORIA <> 0)

GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTASCTLOGCATVAL] TO [Metodo98]
    AS [dbo];

