
CREATE VIEW dbo.TP_VISTAARTICOLIORDINEFORNITORE
AS
SELECT
	DISTINCT TABLOTTIRIORDINO.CODART,
	ANAGRAFICAARTICOLI.DESCRIZIONE AS DESCARTICOLO,
	ANAGRAFICAARTICOLI.GRUPPO,
	ANAGRAFICAARTICOLI.CATEGORIA,
	ANAGRAFICAARTICOLI.CODCATEGORIASTAT,
	TABLOTTIRIORDINO.TP_FORNFATTURAZIONE,
	FORNITOREFATTURAZIONE.DSCCONTO1 AS DESCFORNITOREFATTURAZIONE, 
	TABLOTTIRIORDINO.CODFOR,
	FORNITORE.DSCCONTO1 AS DESCFORNITORE,
	TP_TABMAGAZZINI.PROGRESSIVO AS PROGRMULTIDEPOSITO
FROM TABLOTTIRIORDINO 
INNER JOIN ANAGRAFICAARTICOLI 
	ON ANAGRAFICAARTICOLI.CODICE=TABLOTTIRIORDINO.CODART  
INNER JOIN TP_EXTRAMAG 
	ON TP_EXTRAMAG.CODART = TABLOTTIRIORDINO.CODART AND TP_EXTRAMAG.CONSIDACQ=1  
INNER JOIN ANAGRAFICACF AS FORNITOREFATTURAZIONE
	ON FORNITOREFATTURAZIONE.CODCONTO=TABLOTTIRIORDINO.TP_FORNFATTURAZIONE 
INNER JOIN ANAGRAFICARISERVATICF AS FORNITOREFATTCF
	ON FORNITOREFATTCF.CODCONTO = FORNITOREFATTURAZIONE.CODCONTO AND FORNITOREFATTCF.ESERCIZIO = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME())
INNER JOIN ANAGRAFICACF AS FORNITORE 
	ON FORNITORE.CODCONTO=TABLOTTIRIORDINO.CODFOR  
INNER JOIN ANAGRAFICARISERVATICF AS FORNITORECF
	ON FORNITORECF.CODCONTO = FORNITORE.CODCONTO AND FORNITORECF.ESERCIZIO = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = USER_NAME())
LEFT JOIN TP_TABMAGAZZINI 
	ON TP_TABMAGAZZINI.CODDEPOSITO=TABLOTTIRIORDINO.TP_CODDEP 

GO
GRANT DELETE
    ON OBJECT::[dbo].[TP_VISTAARTICOLIORDINEFORNITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TP_VISTAARTICOLIORDINEFORNITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TP_VISTAARTICOLIORDINEFORNITORE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TP_VISTAARTICOLIORDINEFORNITORE] TO [Metodo98]
    AS [dbo];

