
 CREATE VIEW [dbo].[VIEW_CATALOGO_TIPOLOGIE_VALORI]
 AS
 SELECT
 0 Codice,
 '' TipologiaValore,
 0 IDTYPE
 
GO
GRANT SELECT
    ON OBJECT::[dbo].[VIEW_CATALOGO_TIPOLOGIE_VALORI] TO [Metodo98]
    AS [dbo];

