CREATE VIEW dbo.VIEW2
AS
SELECT     dbo.TESTEFOGLICOMMCLI.RIFERIMENTO AS Expr2, dbo.TESTEFOGLICOMMCLI.TIPO AS Expr1, dbo.RIGHEPREVCOMMCLI.LIVS1, 
                      dbo.RIGHEPREVCOMMCLI.LIVPADRES1, dbo.RIGHEPREVCOMMCLI.CODLIVS1, dbo.RIGHEPREVCOMMCLI.LIV5, 
                      dbo.RIGHEPREVCOMMCLI.CODLIVELLO
FROM         dbo.TESTEFOGLICOMMCLI INNER JOIN
                      dbo.RIGHEPREVCOMMCLI ON dbo.TESTEFOGLICOMMCLI.PROGRESSIVO = dbo.RIGHEPREVCOMMCLI.RIFPROGRESSIVO
WHERE     (dbo.TESTEFOGLICOMMCLI.TIPO = 'ISA')
