

 CREATE VIEW [dbo].[VIEW_CATALOGO_TIPO_TIPOLOGIA]
 AS
 SELECT
 PT.CODTIPOLOGIAACCESSO,
 PT.DSCTIPOLOGIAACCESSO,
 PT.CODTIPOENTITA,
 PT.DSCTIPOENTITA,
 P.PROFILO
 FROM
 (
 SELECT
 P.CODICE AS CODTIPOLOGIAACCESSO,
 P.DESCRIZIONE AS DSCTIPOLOGIAACCESSO,
 T.CODICE AS CODTIPOENTITA,
 T.DESCRIZIONE AS DSCTIPOENTITA
 FROM
 CATALOGO_TIPOLOGIE_ACCESSO P,
 CATALOGO_TIPI_ENTITA T
 ) PT
 LEFT JOIN
 CATALOGO_PROFILI_TIPO_TIPOLOGIA P
 ON
 P.CODTIPOLOGIAACCESSO = PT.CODTIPOLOGIAACCESSO AND
 P.CODTIPOENTITA = PT.CODTIPOENTITA

 
GO
GRANT SELECT
    ON OBJECT::[dbo].[VIEW_CATALOGO_TIPO_TIPOLOGIA] TO [Metodo98]
    AS [dbo];

