

CREATE VIEW VISIONECONTRATTI_ASSOR
AS
SELECT     dbo.CONTRATTI_ASSOR.*, dbo.ANAGRAFICACF.DSCCONTO1 AS DSCCONTO1
FROM         dbo.CONTRATTI_ASSOR LEFT OUTER JOIN
                      dbo.ANAGRAFICACF ON dbo.CONTRATTI_ASSOR.CODCLIFOR = dbo.ANAGRAFICACF.CODCONTO


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISIONECONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISIONECONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISIONECONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISIONECONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISIONECONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];

