
CREATE VIEW VISTALISTINI AS
SELECT TABLISTINI.NRLISTINO,
    TABLISTINI.DESCRIZIONE,
    TABLISTINI.CODCAMBIO,
    TABLISTINI.VINCOLAUM,
    TABCAMBI.DIVISA,
    TABCAMBI.DESCRIZIONE AS DESCRDIVISA
    FROM TABLISTINI,TABCAMBI
    WHERE TABLISTINI.CODCAMBIO=TABCAMBI.CODICE	

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALISTINI] TO [Metodo98]
    AS [dbo];

