CREATE VIEW VISTAMATERIALEFASE AS
SELECT 
	TESTACICLOORDINE.PROGRESSIVO,
	RIGHECICLOORDINE.NUMEROFASE,
	TESTEORDINIPROD.ESERCIZIO,
	TESTEORDINIPROD.TIPOCOM,
	TESTEORDINIPROD.NUMEROCOM,
	TESTACICLOORDINE.IDRIGACOMM,
	RIGHEORDPROD.CODICEORD,
	RIGHEORDPROD.CODART,
	RIGHEORDPROD.DESCRIZIONEART,	
	TESTACICLOORDINE.CODCICLO,
	TESTACICLOORDINE.VERSIONECICLO,
	TESTACICLOORDINE.DSCVERSIONE,
	TESTACICLOORDINE.VERSIONEDBA,
	TESTACICLOORDINE.NOTECICLO,
	RIGHECICLOORDINE.ANNOBOLLA,
	RIGHECICLOORDINE.NUMEROBOLLA,
	RIGHECICLOORDINE.OPERAZIONE,
	RIGHECICLOORDINE.DSCOPERAZIONE,
	RIGHECICLOORDINE.CDLAVORO,
	(select DESCRIZIONE from TABELLACDLAVORO where RIGHECICLOORDINE.CDLAVORO=TABELLACDLAVORO.CODICE) DSCCDLAVORO,
	(select REPARTO from TABELLACDLAVORO where RIGHECICLOORDINE.CDLAVORO=TABELLACDLAVORO.CODICE) CODREPARTO,
	RIGHECICLOORDINE.MACCHINA,
	(select DESCRIZIONE from TABELLAMACCHINE where RIGHECICLOORDINE.MACCHINA=TABELLAMACCHINE.CODICE) DSCMACCHINA,
	RIGHECICLOORDINE.FOGLIOISTRUZIONI,
	RIGHECICLOORDINE.ATTREZZATURA,
	RIGHECICLOORDINE.STRUMENTICONTROLLO,
	RIGHECICLOORDINE.PIANOCONTROLLO,
	RIGHECICLOORDINE.NOTERIGA,
	RIGHEORDPROD.RIFCOMMCLI
FROM
	TESTACICLOORDINE,RIGHECICLOORDINE,TESTEORDINIPROD,RIGHEORDPROD
WHERE
	(TESTACICLOORDINE.PROGRESSIVO=RIGHECICLOORDINE.PROGRESSIVO)
	and (TESTACICLOORDINE.IDTESTACOMM=TESTEORDINIPROD.PROGRESSIVO)
	and (TESTACICLOORDINE.IDTESTACOMM=RIGHEORDPROD.IDTESTA and TESTACICLOORDINE.IDRIGACOMM=RIGHEORDPROD.IDRIGA)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAMATERIALEFASE] TO [Metodo98]
    AS [dbo];

