CREATE VIEW VISTACAUSALICONT AS
SELECT CC.CODICECAUSALE,
    CC.DESCRIZIONE,
    CC.NRREGISTRO,
    CC.CODCAUSMOVCES,
    CC.SCADENZE,
    CC.NOTAACCRADD,
    CC.NOTE,
    CC.INVALUTA,
    CC.RIPCDC,
    CC.COMPETENZE,
    CC.NRGIORNALE,
    CC.CAUSCOLLEGATA,
    CC.SCADOBBL,
    CC.CDCOBBL,
    CC.COMPOBBL,
    CC.QSCADOBBL,
    CC.QCDCOBBL,
    CC.QCOMPOBBL,
    CC.CONTNACCR,
    CC.GESTRITACC,
    CC.CAUSALEAUTOMATICA,
    CC.CODCAUSCOMMCLI,
    CC.DATAINIVALIDITA,
    CC.DATAFINEVALIDITA,
    CC.VISDSCCONTO,
    CC.VISDSCRIGA,
    CC.VISIMPEURO,
    CC.VISIMPLIRE,
    CC.VISNUMFATT,
    CC.VISNUMPART,
    CC.VISDTFATT,
    CC.VISDTVAL,
    CC.VISRIFCOMMCLI,
    CC.UTENTEMODIFICA,
    CC.DATAMODIFICA
    FROM CAUSALICONTABILI CC INNER JOIN TABUTENTI ON USERDB = CAST(USER_NAME() AS VARCHAR(25))
    WHERE
    ((SUPERVISOR=1) OR (SUPERVISOR=0 AND USERID IN (SELECT NOMEUTENTE FROM ACCESSICAUSCONT WHERE CODCAUSALE=CC.CODICECAUSALE AND FLAGVISUALIZZA=1)))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACAUSALICONT] TO [Metodo98]
    AS [dbo];

