CREATE VIEW VISTACCBILANCIOCONSCOSTIDIRPN AS
SELECT
	IDCOMMCLI,
	RIFCOMM,
	RIFCOMMRIEP,
	CLICOMMITT,
	TIPOCOM,
	ANNOCOM,
	NUMCOM,
	DATAEMISSIONE,
	STATOCOMMESSA,
    FLGTIPOCOMM,
	NRRIGA,
	NRREG AS RIFTESTA,
	NRRIGAPN AS RIFRIGA,
	ORIGINEEVENTO,
	NRREG AS RIFTESTA_DEST,
	NRRIGAPN AS RIFRIGA_DEST,
	ORIGINEEVENTO AS ORIGINEEVENTO_DEST,	
	CONTOGEN,
	CONTOCDC,
	CAUSALE,
	DESCRIZIONE,
	RIFFATTURA,
	CONTROPARTITA,
	IMPORTO,
	NATURARILEVAZIONE,
	TIPOREC,
	VOCEBASE,
	IDVOCE,
	IDCENTROCOSTO,
	IMPORTOEURO,
	TIPOCOSTO,
	IDTABELLA,
	0 AS NUMEROMOV
FROM
	CCBILANCIOCONSCOSTIDIRPN CC INNER JOIN ANAGRAFICACOMMESSE AC ON CC.IDCOMMCLI=AC.PROGRESSIVO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACCBILANCIOCONSCOSTIDIRPN] TO [Metodo98]
    AS [dbo];

