

CREATE VIEW VISTAGRPACQ_DETTAGLIO
AS
SELECT     dbo.ACQ_COMPONENTIGRUPPOACQUISTO.RIFCODICE, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.IDSOCIO, 
                      dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO, dbo.ANAGRAFICACF.DSCCONTO1, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.TIPOSOCIO, 
                      dbo.ACQ_COMPONENTIGRUPPOACQUISTO.UTENTEMODIFICA, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.DATAMODIFICA, 
                      dbo.ACQ_GRUPPOACQUISTO.CODICE, dbo.ACQ_GRUPPOACQUISTO.DESCRIZIONE, dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO AS AUX
FROM         dbo.ACQ_COMPONENTIGRUPPOACQUISTO INNER JOIN
                      dbo.ANAGRAFICACF ON dbo.ACQ_COMPONENTIGRUPPOACQUISTO.SOCIO = dbo.ANAGRAFICACF.CODCONTO INNER JOIN
                      dbo.ACQ_GRUPPOACQUISTO ON dbo.ACQ_COMPONENTIGRUPPOACQUISTO.RIFCODICE = dbo.ACQ_GRUPPOACQUISTO.CODICE


GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTAGRPACQ_DETTAGLIO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTAGRPACQ_DETTAGLIO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VISTAGRPACQ_DETTAGLIO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAGRPACQ_DETTAGLIO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTAGRPACQ_DETTAGLIO] TO [Metodo98]
    AS [dbo];

