CREATE VIEW VISTA_SCHED_MACCHINE AS 
SELECT CODICE,MACCHINAPREF FROM TABELLAOPERAZIONI
UNION
SELECT CODOPERAZIONE,CODMACCHINA FROM MACCHINEALTERNATIVE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_SCHED_MACCHINE] TO [Metodo98]
    AS [dbo];

