CREATE VIEW VISTAGIACENZEPARTITE
AS
SELECT 
	ANAGRAFICALOTTI.CODARTICOLO,
	ANAGRAFICALOTTI.CODLOTTO,
	ANAGRAFICALOTTI.BLOCCATO,
	(SELECT UM FROM ARTICOLIUMPREFERITE WHERE TIPOUM=1 AND COdart=ANAGRAFICALOTTI.CODARTICOLO) AS UM1,
	(SELECT UM FROM ARTICOLIUMPREFERITE WHERE TIPOUM=2 AND COdart=ANAGRAFICALOTTI.CODARTICOLO) AS UM2,
	SUM(ORDINATO) AS ORDINATO,
	SUM(ORDINATO2UM) AS ORDINATO2UM,
	SUM(IMPEGNATO) AS IMPEGNATO,
	SUM(IMPEGNATO2UM) AS IMPEGNATO2UM,
	SUM(CARICO) AS CARICO,
	SUM(CARICO2UM) AS CARICO2UM,
	SUM(SCARICO) AS SCARICO,
	SUM(SCARICO2UM) AS SCARICO2UM,
	SUM(RESODACARICO) AS RESODACARICO,
	SUM(RESODACARICO2UM) AS RESODACARICO2UM,
	SUM(RESODASCARICO) AS RESODASCARICO,
	SUM(RESODASCARICO2UM) AS RESODASCARICO2UM,
	(SUM(CARICO)+SUM(RESODASCARICO)-SUM(SCARICO)-SUM(RESODACARICO)) AS GIACENZA,
	(SUM(CARICO2UM)+SUM(RESODASCARICO2UM)-SUM(SCARICO2UM)-SUM(RESODACARICO2UM)) AS GIACENZA2UM,
	(SUM(CARICO)+SUM(RESODASCARICO)-SUM(SCARICO)-SUM(RESODACARICO)+SUM(ORDINATO)-SUM(IMPEGNATO)) AS DISPONIBILITA,
	(SUM(CARICO2UM)+SUM(RESODASCARICO2UM)-SUM(SCARICO2UM)-SUM(RESODACARICO2UM)+SUM(ORDINATO2UM)-SUM(IMPEGNATO2UM)) AS DISPONIBILITA2UM
FROM 
	ANAGRAFICALOTTI LEFT OUTER JOIN VISTAGIACENZE
	ON ANAGRAFICALOTTI.CODARTICOLO = VISTAGIACENZE.CODART
	AND ANAGRAFICALOTTI.CODLOTTO = VISTAGIACENZE.NRIFPARTITA
GROUP BY
	ANAGRAFICALOTTI.CODARTICOLO,ANAGRAFICALOTTI.CODLOTTO,ANAGRAFICALOTTI.BLOCCATO

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAGIACENZEPARTITE] TO [Metodo98]
    AS [dbo];

