

CREATE VIEW VISTAASSEGNAZIONICONSCOMM AS
SELECT 
    ASS.RIFCOMMCLI,
    ASS.IDTESTA,
    ASS.IDRIGA,
    STRUTT.CODLIV,
    STRUTT.CODLIVELLO,
    STRUTT.TIPONODO,
    STRUTT.LIVPADRE,
    STRUTT.DESCRIZIONE,
    ASS.PERCRIPARTIZIONE,
    ASS.TIPORIP,
    ASS.DECRIPQTA,
    ASS.DECRIPVALORE,
    STRUTT.NRRIGA      AS NRRIGASTRUTT,
    STRUTT.NRRIGAPADRE AS NRRIGASTRUTTPADRE,
    STRUTT.NRRIGAPREV  AS RIFRIGAPREV,
    STRUTT.POSIZIONE,
    ASS.ORIGINEEVENTO,
    STRUTT.PROGRESSIVO,
      AA.Progressivo AS IDCOMMCLI,
      AA.TIPOASSEGNAZIONE,
      (CASE WHEN STRUTT.TIPONODO=0 THEN PADRE.CODLIV     ELSE STRUTT.CODLIV     END ) AS CODNODO_DEST,         
      (CASE WHEN STRUTT.TIPONODO=0 THEN PADRE.CODLIVELLO ELSE STRUTT.CODLIVELLO END ) AS CODLIVELLO_DEST,
      (CASE WHEN STRUTT.TIPONODO=0 THEN PADRE.LIVPADRE   ELSE STRUTT.LIVPADRE   END ) AS LIVPADRE_DEST,
      (CASE WHEN STRUTT.TIPONODO=0 THEN PADRE.NRRIGA      ELSE STRUTT.NRRIGA      END) AS NRRIGASTRUTT_DEST,
      (CASE WHEN STRUTT.TIPONODO=0 THEN PADRE.NRRIGAPADRE ELSE STRUTT.NRRIGAPADRE END) AS NRRIGASTRUTTPADRE_DEST
FROM 
    TABSTRUTTCONSCOMM STRUTT 
    INNER JOIN TABSTRUTTCONSCOMM PADRE ON PADRE.NRRIGA = STRUTT.NRRIGAPADRE AND PADRE.rifcommcli = STRUTT.rifcommcli
    INNER JOIN TABASSEGNAZIONICONSCOMM ASS ON STRUTT.PROGRESSIVO=ASS.IDRIGASTRUTTCONS
    INNER JOIN AnagraficaCommesse AA ON STRUTT.rifcommcli = AA.RifComm
WHERE
    ASS.PERCRIPARTIZIONE > 0

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAASSEGNAZIONICONSCOMM] TO [Metodo98]
    AS [dbo];

