
/****** Script per comando Seleziona le prime N righe da SSMS  ******/
CREATE VIEW [dbo].[VISTA_TRASPORTO_COSTI]
AS
	SELECT   
		(ROW_NUMBER() OVER(ORDER BY IDTESTADOC DESC) & 1)  As PD,
		TR.IDFILTRO, 
		TR.CODSPEDIZIONIERE, 
		SP.RAGIONESOCIALE AS DESCRCODSPEDIZIONE, 
		TR.IDREGOLA, 
		TR.DATADOC, 
		TD.CODCLIFOR, 
		RD.CODART, 
		TR.IDTESTADOC, 
		TR.IDRIGADOC, 
		TR.TOTRIGHEDOC, 
		TR.CODICE, 
		TR.TOTVALORE, 
		TR.TOTALERIGADOC, 
		TR.TOTVALORE_RIGADOC, 
		TR.UTENTEMODIFICA, 
		TR.DATAMODIFICA, 
		TRASPORTO_CAD_CODICI.DESCRIZIONE, 
		TRASPORTO_CAD_CODICI.TIPO
	FROM         
		TRASPORTO_CALCOLOBATCH_RIGHE AS TR 
	INNER JOIN TESTEDOCUMENTI AS TD ON TD.PROGRESSIVO = TR.IDTESTADOC 
	INNER JOIN RIGHEDOCUMENTI AS RD ON TR.IDTESTADOC = RD.IDTESTA AND TR.IDRIGADOC = RD.IDRIGA 
	INNER JOIN TABSPEDIZ AS SP ON SP.CODICE = TR.CODSPEDIZIONIERE 
	INNER JOIN TRASPORTO_CAD_CODICI ON TR.CODICE = TRASPORTO_CAD_CODICI.CODICE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_TRASPORTO_COSTI] TO [Metodo98]
    AS [dbo];

