CREATE VIEW VISTACOSTILAVINTDOC AS
SELECT 
	IDCOMMCLI,
	NRRIGA,
	IDTESTADOC,
	IDRIGADOC,
	(SELECT POSIZIONE FROM RIGHEDOCUMENTI WHERE IDTESTA=CC.IDTESTADOC AND IDRIGA=CC.IDRIGADOC) AS POSDOC,
	CODART,
	DSCARTICOLO,
	QUANTITA,
	UMBASE,
	COSTOUNILAV,
	COSTOTOTLAV,
	CODFOR,
	TIPOCLP,
	NATURARILEVAZIONE,
	TIPOREC,
	CODOPERAZIONE,
	VOCEBASE,
	IDVOCE,
	COSTOUNILAVEURO,
	COSTOTOTLAVEURO,
	TIPOCOSTO,
	IDTABELLA,
	ORIGINEEVENTO,
	QTAVAL,
	UMVAL,
	TIPOINSERIMENTO,
	DATAELAB_CONS,
	DATAELAB_VAL,
	DATAMOVIMENTO,
	DATADISPONIBILITA,
	DATACOMPETENZA,
	DATARIFVALORIZ,
	TIPORECDETT,
	CONTOCDC,
	QTABUDGET,
	PESO,
	NOTE,
	DESCRIZIONE,
	UTENTEMODIFICA,
	DATAMODIFICA
FROM
    CCBILANCIOCONSLAVINTDOC CC

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACOSTILAVINTDOC] TO [Metodo98]
    AS [dbo];

