


-- FINE A#12147


/*
    rif.08/01/2015 - rif.a#12594 - aggiunti campi QTA1MAGRES e QTA2MAGRES
*/
CREATE view [dbo].[VISTALISTETRASFERIMENTO] as 
select 
    TESTELISTATRASF.ESERCIZIO,
    TESTELISTATRASF.CODICELISTA,
    TESTELISTATRASF.NUMEROLISTA,
    TESTELISTATRASF.DATAEMISSIONE,
    TESTELISTATRASF.STATOCHIUSO,
    TESTELISTATRASF.NOTE,
    RIGHELISTATRASF.IDTESTA,
    RIGHELISTATRASF.IDRIGA,
    RIGHELISTATRASF.RIFTESTACOMM,
    RIGHELISTATRASF.DATADISPONIBILITA,
    TESTEORDINIPROD.TIPOCOM,
    TESTEORDINIPROD.ESERCIZIO as ANNOCOM,
    TESTEORDINIPROD.NUMEROCOM,
    TESTEORDINIPROD.DATAEMISSIONE as DATAEMISSIONECOM,
    RIGHELISTATRASF.RIFRIGAORD,
    RIGHEORDPROD.CODICEORD,
    (select TIPOORDINE from PARAMETRIORDPROD where PARAMETRIORDPROD.CODICE=RIGHEORDPROD.CODICEORD) as TIPOORD,
    RIGHELISTATRASF.CODART,
    RIGHELISTATRASF.DESCRIZIONEART, 
    RIGHELISTATRASF.RIFRIGAIMP,
    RIGHEORDPROD.VERSIONEDBA,
    RIGHEORDPROD.DATAINIZIORICH,
    RIGHEORDPROD.DATAFINERICH,
    RIGHELISTATRASF.QTATRASFGESTIONE,RIGHELISTATRASF.QTAGESTIONERES,RIGHELISTATRASF.UMGEST,
    RIGHELISTATRASF.QTATRASFPREZZO,RIGHELISTATRASF.UMPREZZO,RIGHELISTATRASF.QTAPREZZOMAN,
    RIGHELISTATRASF.QTATRASF1MAG,RIGHELISTATRASF.QTA1MAGMAN,RIGHELISTATRASF.QTA1MAGRES,
    RIGHELISTATRASF.QTA2MAGMAN,RIGHELISTATRASF.QTATRASF2MAG,RIGHELISTATRASF.QTA2MAGRES,
    RIGHELISTATRASF.QTAGESTIONEDOC,
    RIGHELISTATRASF.UM1MAG as UM1,
    RIGHELISTATRASF.UM2MAG as UM2,
    RIGHELISTATRASF.PARTITAASSEGNATA,
    RIGHELISTATRASF.CODCLIFOR,
    (select DSCCONTO1 from ANAGRAFICACF where CODCONTO = CODCLIFOR) RAGSOCCLIFOR,
    RIGHELISTATRASF.DEPOSITO,RIGHELISTATRASF.UBICAZIONE,RIGHELISTATRASF.CONTOCDC,
    RIGHELISTATRASF.DEPOSITOCOLL,RIGHELISTATRASF.UBICAZIONECOLL,RIGHELISTATRASF.CONTOCDCCOLL,
    RIGHELISTATRASF.COSTOUNITTRASF,RIGHELISTATRASF.COSTOTOTTRASF,
    RIGHELISTATRASF.COSTOUNITTRASFEURO,RIGHELISTATRASF.COSTOTOTTRASFEURO,
    RIGHELISTATRASF.STATORIGA,RIGHELISTATRASF.NOTE as NOTERIGA,
    RIGHELISTATRASF.RIFCOMMCLI,
    RIGHELISTATRASF.TIPOMATERIALE,RIGHELISTATRASF.RIFANNOBOLLA,RIGHELISTATRASF.RIFNUMEROBOLLA,
    (TESTELISTATRASF.CODICELISTA + '/' + cast(TESTELISTATRASF.ESERCIZIO as varchar(4)) + '/' + right('00000' + cast(TESTELISTATRASF.NUMEROLISTA as varchar(10)),5)) as RIFLISTA,
    (TESTEORDINIPROD.TIPOCOM + '/' + cast(TESTEORDINIPROD.ESERCIZIO as varchar(4)) + '/' + right('00000' + cast(TESTEORDINIPROD.NUMEROCOM as varchar(10)),5) + '/' + right('00000' + cast(RIGHELISTATRASF.RIFRIGAORD as varchar(10)),5)) as RIFORDINE,
    (TESTEORDINIPROD.TIPOCOM + '/' + cast(TESTEORDINIPROD.ESERCIZIO as varchar(4)) + '/' + right('00000' + cast(TESTEORDINIPROD.NUMEROCOM as varchar(10)),5) + '/' + right('00000' + cast(RIGHELISTATRASF.RIFRIGAORD as varchar(10)),5) + '/' + right('00000' + cast(RIGHELISTATRASF.RIFRIGAIMP as varchar(10)),5)) as RIFIMPEGNO,
    (cast(RIGHELISTATRASF.RIFANNOBOLLA as varchar(4)) + '/' + right('00000' + cast(RIGHELISTATRASF.RIFNUMEROBOLLA as varchar(10)),5)) as RIFBOLLALAV,
    (SELECT OPERAZIONE FROM RIGHECICLOORDINE RC WHERE RC.ANNOBOLLA=RIGHELISTATRASF.RIFANNOBOLLA AND RC.NUMEROBOLLA=RIGHELISTATRASF.RIFNUMEROBOLLA) AS OPERAZIONECLF
from 
    TESTELISTATRASF,
    RIGHELISTATRASF 
    left outer join TESTEORDINIPROD on RIGHELISTATRASF.RIFTESTACOMM=TESTEORDINIPROD.PROGRESSIVO
    left outer join RIGHEORDPROD on RIGHELISTATRASF.RIFTESTACOMM=RIGHEORDPROD.IDTESTA and RIGHELISTATRASF.RIFRIGAORD=RIGHEORDPROD.IDRIGA
    left outer join IMPEGNIORDPROD on RIGHELISTATRASF.RIFTESTACOMM=IMPEGNIORDPROD.IDTESTA and RIGHELISTATRASF.RIFRIGAORD=IMPEGNIORDPROD.IDRIGA and RIGHELISTATRASF.RIFRIGAIMP=IMPEGNIORDPROD.IDIMPEGNO  
where
    TESTELISTATRASF.PROGRESSIVO=RIGHELISTATRASF.IDTESTA



GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTALISTETRASFERIMENTO] TO [Metodo98]
    AS [dbo];

