CREATE  VIEW VISTAAGENTI_ECOM AS
SELECT AA.DscAgente, AA.PartitaIVA, AA.CodFiscale, AA.CODagente, AA.TELEX EMAIL, AE.PASSWORD  FROM 
Anagraficaagenti AA LEFT OUTER JOIN AGENTI_ECOM AE ON AA.CODagente = AE.CODagente

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAAGENTI_ECOM] TO [Metodo98]
    AS [dbo];

