
CREATE VIEW VISTACICLOPIANORIS
  AS SELECT TCO.NOMEPIANORIS,TCO.PROGRESSIVO,TCO.CODCICLO,
    TCO.VERSIONECICLO,TCO.DSCVERSIONE,
    TCO.STATOVERSIONE,TCO.VALIDITACICLO,
    TCO.VERSIONEDBA,TCO.CICLOSTANDARD,TCO.NOTECICLO,
    TCO.UM,TCO.QUANTITARIF,TCO.TIPOCICLO,TCO.IDTESTACOMM,
    TCO.IDRIGACOMM,TCO.LOTTOASSEGNATO,TCO.DATAINIZIOLAV,TCO.TIPOVALUTAZIONE,
    STSV.DESCRIZIONE AS DSCSTATOVERSIONE,
    (CASE WHEN RIGHT(CODCICLO,1) = '#' THEN
      (SELECT DESCRIZIONE FROM ANAGRAFICAARTICOLI WHERE CODICE = SUBSTRING(TCO.CODCICLO,1,CHARINDEX('#',TCO.CODCICLO)-1))
    ELSE
      (SELECT DESCRIZIONE FROM ANAGRAFICAARTICOLI WHERE CODICE = TCO.CODCICLO)
    END) AS DSCCODCICLO,COM.TIPOCOM+'/'+CAST(COM.ESERCIZIO AS VARCHAR)+'/'+RIGHT('0000000000'+CAST(COM.NUMEROCOM AS VARCHAR),10)+'/'+RIGHT('00000'+CAST(TCO.IDRIGACOMM AS VARCHAR),5) AS RIFORDINE,
    STSV.USAVERSIONE,
    DAC.VALIDITADBA,DAC.DBASTANDARD FROM(((
    TESTACICLOPIANORISORSE AS TCO LEFT OUTER JOIN TABSTATOVERSIONECICLO AS STSV ON
    TCO.STATOVERSIONE = STSV.CODICE) LEFT OUTER JOIN
    DISTINTAARTCOMPOSTI AS DAC ON
    TCO.CODCICLO = DAC.ARTCOMPOSTO AND TCO.VERSIONEDBA = DAC.VERSIONEDBA) LEFT OUTER JOIN
    TESTEORDINIPROD AS COM ON
    COM.PROGRESSIVO = TCO.IDTESTACOMM)


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACICLOPIANORIS] TO [Metodo98]
    AS [dbo];

