CREATE VIEW VISTADOCALLESTIM AS
SELECT TD.PROGRESSIVO AS IDTESTA,
    TD.ESERCIZIO,
    TD.TIPODOC,
    TD.NUMERODOC,
    TD.BIS,
    TD.DATADOC,
    TD.DOCCHIUSO,
    TD.BLOCCATO,
    TD.CODCLIFOR,
    TD.CODCFFATT,
    (SELECT DSCCONTO1 FROM ANAGRAFICACF AS AX WHERE TD.CODCLIFOR=AX.CODCONTO) AS RAGSOCCLI,
    TD.NUMRIFDOC,
    TD.DATARIFDOC,
    TD.CODAGENTE1,
    TD.CODAGENTE2,
    TD.CODAGENTE3,
    TD.NUMDESTDIVERSAMERCI,
    TD.CODCAMBIO,
    RD.IDRIGA,
    RD.CODART,
    RD.CODDEPOSITO,
    (CASE WHEN RD.UBICAZIONE IS NULL THEN '' ELSE RD.UBICAZIONE END) AS UBICAZIONE,
    (CASE WHEN RD.NRRIFPARTITA IS NULL THEN '' ELSE RD.NRRIFPARTITA END) AS NRRIFPARTITA,
    RD.TIPORIGA,
    RD.VARIANTI,
    RD.DATACONSEGNA,
    RD.NRRIFPARTITA AS CODPARTITA,
    ARCF.CODSETTORE,
    ARCF.CODZONA,
    ARCF.CODCATEGORIA AS CODCATEGORIACF,
    AA.CATEGORIA,
    AA.CODCATEGORIASTAT,
    AA.GRUPPO,
    AA.DESCRIZIONE,
    ACF.DSCCONTO1,
    ACF.CODNAZIONE,
    AFC.FATTORE AS FATTORECUM,
    AUP.TIPOUM,
    AFC.UM1 AS OLDUM,
    AUP.UM,
    (CASE WHEN UMGEST=AUP.UM THEN 
      RD.QTAGESTRES*SEGNO 
    ELSE 
      (CASE WHEN UMPREZZO=AUP.UM THEN 
         RD.QTAPREZZORES*SEGNO 
      ELSE
         RD.QTAGESTRES*AFC.FATTORE*SEGNO 
      END) 
    END) AS QUANTITARES,
    (CASE WHEN UMGEST=AUP.UM THEN
      RD.QTAGEST*SEGNO
    ELSE
      (CASE WHEN UMPREZZO=AUP.UM THEN
        RD.QTAPREZZO*SEGNO
      ELSE
        RD.QTAGEST*AFC.FATTORE*SEGNO
      END)
    END) AS QUANTITA,
    RD.RIFRELAZIONECF
    FROM 
    (((TESTEDOCUMENTI AS TD JOIN PARAMETRIDOC AS PD ON TD.TIPODOC=PD.CODICE)
	INNER JOIN ANAGRAFICACF AS ACF ON TD.CODCLIFOR=ACF.CODCONTO)
    INNER JOIN ANAGRAFICARISERVATICF AS ARCF ON TD.CODCLIFOR=ARCF.CODCONTO AND TD.ESERCIZIO=ARCF.ESERCIZIO)
    INNER JOIN 
    ((RIGHEDOCUMENTI AS RD LEFT OUTER JOIN ANAGRAFICAARTICOLI AS AA ON AA.CODICE=RD.CODART)
    LEFT OUTER JOIN (ARTICOLIUMPREFERITE AS AUP INNER JOIN ARTICOLIFATTORICONVERSIONE AS AFC ON AUP.CODART=AFC.CODART AND AFC.UM2=AUP.UM)
    ON RD.CODART=AUP.CODART) 
    ON TD.PROGRESSIVO=RD.IDTESTA
    WHERE RD.UMGEST=AFC.UM1

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTADOCALLESTIM] TO [Metodo98]
    AS [dbo];

