CREATE VIEW VISTACOSTILAVEST AS
SELECT
	IDCOMMCLI,
	NRRIGA,
	IDTESTADOC,
	IDRIGADOC,	
	(CASE ORIGINEEVENTO WHEN 3 THEN 
		(SELECT POSIZIONE FROM RIGHEORDPROD WHERE IDTESTA=CC.IDTESTADOC AND IDRIGA=CC.IDRIGADOC) 
		ELSE (SELECT POSIZIONE FROM RIGHEDOCUMENTI WHERE IDTESTA=CC.IDTESTADOC AND IDRIGA=CC.IDRIGADOC) END) AS POSDOC,		
	IDTESTAFATT,
	IDRIGAFATT,
	(SELECT POSIZIONE FROM RIGHEDOCUMENTI WHERE IDTESTA=CC.IDTESTAFATT AND IDRIGA=CC.IDRIGAFATT) AS POSFATT,
	CODART,
	DSCARTICOLO,
	QUANTITA,
	UMBASE,
	COSTOUNILAV,
	COSTOTOTLAV,
	CODFOR,
	TIPOCLP,
	NATURARILEVAZIONE,
	TIPOREC,
	CODOPERAZIONE,
	VOCEBASE,
	IDVOCE,
	COSTOUNILAVEURO,
	COSTOTOTLAVEURO,
	TIPOCOSTO,
	IDTABELLA,
	ORIGINEEVENTO,
	QTAVAL,
	UMVAL,
	TIPOINSERIMENTO,
	DATAELAB_CONS,
	DATAELAB_VAL,
	DATAMOVIMENTO,
	DATADISPONIBILITA,
	DATACOMPETENZA,
	DATARIFVALORIZ,
	TIPORECDETT,
	CONTOCDC,
	QTABUDGET,
	PESO,
	NOTE,
	DESCRIZIONE,
	UTENTEMODIFICA,
	DATAMODIFICA
FROM
	CCBILANCIOCONSLAVEST CC

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACOSTILAVEST] TO [Metodo98]
    AS [dbo];

