CREATE VIEW VISTAGIACENZETOT
AS SELECT STMAG.CODART,
        STMAG.CODDEPOSITO,
        STMAG.CODUBICAZIONE,
        STMAG.NRIFPARTITA,
        STMAG.ESERCIZIO,
        SUM(STMAG.QTA1UM*STMAG.ORDINATO) AS ORDINATO,
        SUM(STMAG.QTA1UM*STMAG.IMPEGNATO) AS IMPEGNATO,
        SUM(STMAG.QTA2UM*STMAG.ORDINATO2UM) AS ORDINATO2UM,
        SUM(STMAG.QTA2UM*STMAG.IMPEGNATO2UM) AS IMPEGNATO2UM,
        SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS CARICO,
        SUM(CASE WHEN STMAG.GIACENZA2UM=1 and STMAG.RESO = 0 THEN STMAG.QTA2UM ELSE 0 END) AS CARICO2UM,
        SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS SCARICO,
        SUM(CASE WHEN STMAG.GIACENZA2UM=-1 and STMAG.RESO = 0 THEN STMAG.QTA2UM ELSE 0 END) AS SCARICO2UM,
        SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODACARICO,
        SUM(CASE WHEN STMAG.GIACENZA2UM=-1 and STMAG.RESO = 1 THEN STMAG.QTA2UM ELSE 0 END) AS RESODACARICO2UM,
        SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODASCARICO,
        SUM(CASE WHEN STMAG.GIACENZA2UM=1 and STMAG.RESO = 1 THEN STMAG.QTA2UM ELSE 0 END) AS RESODASCARICO2UM	
FROM 
	STORICOMAG STMAG
GROUP BY 
	CODART,ESERCIZIO,NRIFPARTITA,CODDEPOSITO,CODUBICAZIONE

GO
GRANT DELETE
    ON OBJECT::[dbo].[VISTAGIACENZETOT] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VISTAGIACENZETOT] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAGIACENZETOT] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VISTAGIACENZETOT] TO [Metodo98]
    AS [dbo];

