
-- Fine Anomalia rif RM #16000 ----------------------------------------------------------------------------------------------------------------------------------


-- RM: 16018 ----------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW VISTAFATTUREELETTRONICHE AS
SELECT 
TD.PROGRESSIVO,TD.ESERCIZIO AS ESERCIZIODOC,TD.DATADOC,TD.DOCCHIUSO,TD.SEGNO,TD.CODCLIFOR,TD.NUMRIFDOC,TD.DATARIFDOC,
TD.CODLISTINO,TD.CODCAMBIO,TD.VALCAMBIO,TD.ADDSPESEDOCUM,TD.ADDSPESEEFFETTO,TD.ADDSPESETRASPORTO,TD.ADDSPESEIMBALLO,TD.CODLINGUA,
TD.CODAGENTE1,TD.PRCPROVVAG1,TD.PRCPROVVFINALEAG1,TD.TOTPROVVAG1 AS TOTPROVVAG1DOC,TD.TOTPROVVAGEURO1 AS TOTPROVVAGEURO1DOC,TD.TOTPROVVAG1RES AS TOTPROVVAG1RESDOC,TD.TOTPROVVAGEURO1RES AS TOTPROVVAGEURO1RESDOC,
TD.CODAGENTE2,TD.PRCPROVVAG2,TD.PRCPROVVFINALEAG2,TD.TOTPROVVAG2 AS TOTPROVVAG2DOC,TD.TOTPROVVAGEURO2 AS TOTPROVVAGEURO2DOC,TD.TOTPROVVAG2RES AS TOTPROVVAG2RESDOC,TD.TOTPROVVAGEURO2RES AS TOTPROVVAGEURO2RESDOC,
TD.CODAGENTE3,TD.PRCPROVVAG3,TD.PRCPROVVFINALEAG3,TD.TOTPROVVAG3 AS TOTPROVVAG3DOC,TD.TOTPROVVAGEURO3 AS TOTPROVVAGEURO3DOC,TD.TOTPROVVAG3RES AS TOTPROVVAG3RESDOC,TD.TOTPROVVAGEURO3RES AS TOTPROVVAGEURO3RESDOC,
TD.NUMDESTDIVERSACORR,TD.NUMDESTDIVERSAMERCI,TD.RAGSOCDDM,TD.INDIRIZZODDM,TD.CAPDDM,TD.LOCALITADDM,TD.PROVINCIADDM,
TD.SCONTOFINALE,TD.CODBANCAINCASSO,TD.CODBANCAAPPOGGIO,TD.CODPAGAMENTO,TD.SPESEDOC,TD.SPESEEFFETTO,TD.TOTSPESEDOC,TD.TOTSPESEEFFETTO,TD.TOTIVASPESEDOC,
TD.TOTIVASPESEEFFETTO,TD.TOTIVAALTRESPESE,TD.TOTIVAALTRESPESERES,TD.TOTALTRESPESE,TD.TOTALTRESPESERES,TD.TOTIMPONIBILE,TD.TOTIMPONIBILERES,TD.TOTIMPOSTA,
TD.TOTIMPOSTARES,TD.TOTDOCUMENTO,TD.TOTDOCUMENTORES,TD.TOTSPESETRASP,TD.TOTSPESETRASPRES,TD.TOTSPESEIMBALLO,TD.TOTSPESEIMBALLORES,TD.TOTIVASPESEIMBALLO,
TD.TOTIVASPESEIMBALLORES,TD.TOTIVASPESETRASP,TD.TOTIVASPESETRASPRES,TD.SPESEDOCEURO,TD.SPESEEFFETTOEURO,TD.TOTSPESEDOCEURO,TD.TOTSPESEEFFETTOEURO,TD.TOTIVASPESEDOCEURO,
TD.TOTIVASPESEEFFETTOEURO,TD.TOTIVAALTRESPESEEURO,TD.TOTIVAALTRESPESEEURORES,TD.TOTALTRESPESEEURO,TD.TOTALTRESPESEEURORES,TD.TOTIMPONIBILEEURO,TD.TOTIMPONIBILEEURORES,
TD.TOTIMPOSTAEURO,TD.TOTIMPOSTAEURORES,TD.TOTNONIMPONIBILE,TD.TOTNONIMPONIBILERES,TD.TOTNONIMPONIBILEEURO,TD.TOTNONIMPONIBILEEURORES,TD.TOTDOCUMENTOEURO,TD.TOTDOCUMENTOEURORES,
TD.TOTSPESETRASPEURO,TD.TOTSPESETRASPEURORES,TD.TOTSPESEIMBALLOEURO,TD.TOTSPESEIMBALLOEURORES,TD.TOTIVASPESEIMBALLOEURO,TD.TOTIVASPESEIMBALLOEURORES,TD.TOTIVASPESETRASPEURO,
TD.TOTIVASPESETRASPEURORES,TD.PRCSPESEIMBALLO,TD.PRCSPESETRASP,TD.CODIVASPTRASP,TD.DATACONSEGNA AS DATACONSEGNADOC,TD.DATAMOVMAGAZZINO,TD.TRASPACURA,TD.CAUSALETRASP,TD.DATAINIZIOTRASP,TD.ORAINIZIOTRASP,
TD.MODOTRASP,TD.ASPETTOBENI,TD.ASPETTOBENIINLINGUA,TD.PORTO,TD.NUMCOLLI AS NUMCOLLIDOC,TD.ANNOTAZIONI AS ANNOTAZIONIDOC,TD.TOTPESONETTO,TD.TOTPESOLORDO,TD.TOTPESOIMBALLO,TD.TOTSUPERFICIE,TD.TOTVOLUME,TD.NATURATRANS,
TD.CONDCONSINTRA,TD.ORIGINEINTRACEE,TD.DESTINAZIONE,TD.VALSTATCEE,TD.VALSTATCEEEURO,TD.NUMLETTERACREDITO,TD.DATALETTERACREDITO,TD.SCONTOINCOND,TD.SCONTOINCONDEURO,TD.PRCSCONTOINCOND,
TD.INCIDENZASCONTI,TD.IMPORTOPAGATO,TD.IMPORTOPAGATOEURO,TD.CODCFFATT,TD.DATADEC,TD.BLOCCATO,TD.FLAGCONT,TD.TOTOMAGGI,TD.TOTOMAGGIRES,TD.TOTOMAGGIEURO,TD.TOTOMAGGIEURORES,TD.RIVIVAOMAGGI,
TD.MESELIQUIDAZ,TD.ANNOLIQUIDAZ,TD.IMPORTIPRELEVATI,TD.MESEPLAFOND,TD.ANNOPLAFOND,TD.FLGIMPEXP AS FLGIMPEXPDOC,TD.TOTCAUZ,TD.TOTCAUZEURO,TD.TOTCAUZRES,TD.TOTCAUZEURORES,
TD.TOTIVACAUZ,TD.TOTIVACAUZEURO,TD.TOTIVACAUZRES,TD.TOTIVACAUZEURORES,TD.LEGAME,TD.SPESERIPMAG,TD.SPESERIPMAGEURO,TD.DOCREPLICATO,TD.STAGIONE,TD.ANNOSTAGIONE,TD.PROGRESSIVOCTR,
TD.RIFTRANSFERORDER,TD.RIFDOCPERIFERIA,TD.ESISTEPROMOTOTALE,TD.VALORESCONTOPROMOTOTALE,TD.NOTEMAG AS NOTEMAGDOC,TD.NOTECOMM AS NOTECOMMDOC,TD.NOTEALTRO AS NOTEALTRODOC,TD.RIFTESTAPL,TD.NUMCOLLIPL,TD.TIPOORDINE,TD.RIFBOLLADOGANALE,
TD.NUMCOLLIDOGANALE,TD.PESOSPEDDOGANALE,TD.SPUNTADOCCARICO,TD.COMMITTENTELOGISTICA,TD.FLGBLACKLIST,TD.TIPODOCBLACKLIST,TD.IMPORTORITENUTA,TD.IMPORTORITENUTAEURO,TD.IMPORTOALTRORA,
TD.IMPORTOALTRORAEURO,TD.PROGRESSIVOSSP,TD.CODICECIG,TD.CODICECUP,TD.NAZIONEDDM,TD.CODICEBUYER,TD.DATAVALLIST,TD.TIPOVALLIST,TD.NRBANCALI,TD.SEZIONALEIVA,TD.CONSEGNAURGENTE,TD.TOTIMPOSTAART17,
TD.TOTIMPOSTAART17EURO,TD.CODIVASPDOC,TD.CODIVASPIMB,TD.CODIVASPEFF,TD.TOTMERCE,TD.TOTMERCERES,TD.TOTMERCEEURO,TD.TOTMERCEEURORES,TD.PRCRITACC,TD.PRCCASSA,TD.IMPORTOCASSAEURO,TD.IMPORTOCASSA,TD.PROGDICHINTENTO,
(CASE WHEN TD.INCIDENZASCONTI<>1 THEN (RD.TOTNETTORIGA-(RD.TOTNETTORIGA*((1-INCIDENZASCONTI)*100)/100)) ELSE RD.TOTNETTORIGA END) AS TOTNETTORIGASCFIN,
(CASE WHEN TD.INCIDENZASCONTI<>1 THEN (RD.TOTNETTORIGAEURO-(RD.TOTNETTORIGAEURO*((1-INCIDENZASCONTI)*100)/100)) ELSE RD.TOTNETTORIGAEURO END) AS TOTNETTORIGAEUROSCFIN,
(1-INCIDENZASCONTI)*100 AS PRCSCONTOFINALE,
(CASE WHEN (SELECT ISNULL(CODIVA,0) FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=4)=0 THEN 0 ELSE (SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=(SELECT CODIVA FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=4)) END) AS ALIQIVACAUZ,
(CASE WHEN (SELECT ISNULL(CODIVA,0) FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=4)=0 THEN 'N2' ELSE (SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=(SELECT CODIVA FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=4) AND TIPOCICLO IN (0,2) ORDER BY TIPOCICLO) END) AS NATURAESENZCAUZ,
(CASE WHEN (SELECT ISNULL(CODIVA,0) FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=4)=0 THEN 'N2' ELSE (SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=(SELECT CODIVA FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=4) AND TIPOCICLO IN (1,2) ORDER BY TIPOCICLO) END) AS NATURAESENZCAUZPASS,
(CASE WHEN (SELECT ISNULL(CODIVA,0) FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=2)=0 THEN 0 ELSE (SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=(SELECT CODIVA FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=2)) END) AS ALIQIVASCINCOND,
(CASE WHEN (SELECT ISNULL(CODIVA,0) FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=2)=0 THEN 'N2' ELSE (SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=(SELECT CODIVA FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=2) AND TIPOCICLO IN (0,2) ORDER BY TIPOCICLO) END) AS NATURAESENZSCINCOND,
(CASE WHEN (SELECT ISNULL(CODIVA,0) FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=2)=0 THEN 'N2' ELSE (SELECT TOP 1 CODICEFEPA FROM FETS_CODIFICHEESENZIVA WHERE CODICEMET=(SELECT CODIVA FROM PARDOCCC WHERE CODDOC=TD.TIPODOC AND CODSPESA=2) AND TIPOCICLO IN (1,2) ORDER BY TIPOCICLO) END) AS NATURAESENZSCINCONDPASS,
TD.SCONTOINCOND*-1 AS IMPSCONTOINCOND,
TD.SCONTOINCONDEURO*-1 AS IMPSCONTOINCONDEURO,
TD.FLGBOLLOVIRTUALE,
(SELECT DAIMPORTOSPESE FROM PARAMETRIDOC WHERE CODICE=TD.TIPODOC) AS DAIMPORTOSPESEDOC,
RD.*,
(SELECT UPPER(DIVISA) FROM TABCAMBI WHERE CODICE=CODCAMBIO) AS DIVISA,
(CASE WHEN (SELECT PERSONAFG FROM TABDITTE)='G' THEN 'RT02' ELSE 'RT01' END) AS TIPORITENUTA,
(SELECT DESCRIZIONE FROM PARAMETRIDOC WHERE CODICE=TD.TIPODOC) AS DSCDOCUMENTO,
(SELECT TIPODOCPA FROM PARAMETRIDOC WHERE CODICE=TD.TIPODOC) AS TIPODOCPA,
COALESCE((SELECT ALIQUOTA FROM TRATTAMENTOIVA WHERE CODICE=CODIVA),0) AS ALIQIVA,
COALESCE((SELECT TIPOESENZ FROM TRATTAMENTOIVA WHERE CODICE=CODIVA),0) AS TIPOESENZIVA,
(CASE WHEN COALESCE(CODIVA,0)=0 THEN 'N2' ELSE 
COALESCE((SELECT NATURAESENZPA FROM TRATTAMENTOIVA WHERE CODICE=CODIVA),'') END) AS NATURAESENZ
FROM TESTEDOCUMENTI TD INNER JOIN RIGHEDOCUMENTI RD ON TD.PROGRESSIVO=RD.IDTESTA
GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAFATTUREELETTRONICHE] TO [Metodo98]
    AS [dbo];

