
CREATE VIEW VISTACONFRD AS
SELECT 
     PROGRESSIVO,
     NOMEIMPOSTAZIONE,
     NOTE,
     TIPORIGA,
     ESEGUITAB,
     VAITAB,
     (SELECT (CASE WHEN IMPPREDEFINITA<>0 THEN 'SI' ELSE 'NO' END) FROM UTENTICONFRD WHERE RIFPROGRESSIVO=PROGRESSIVO AND UTENTE=(SELECT USERID FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))) AS IMPPREDEFINITA
FROM 
     TESTECONFRD

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONFRD] TO [Metodo98]
    AS [dbo];

