

CREATE VIEW [dbo].[VISTA_TRASPORTO_ACQ_COSTI_TOTALI] AS

    SELECT 
         L.RIFPROGRESSIVO
        ,C.[CODART]
        ,C.[NRRIFPARTITA]
        ,C.[CODDEPOSITO]
        ,C.[COSTOMEDIOPEDANA]
        ,C.[COSTOMEDIOPEZZOXPEDANA]
        ,C.[COSTOMEDIOPEZZOXKG]
    FROM 
        TP_TRASPORTOCOSTOACQARTICOLI C
    INNER JOIN
        TP_TRASPORTOTOTALEARTICOLOLOTTO L
    ON
        L.CODART = C.CODART AND
        L.CODDEPOSITO = C.CODDEPOSITO AND
        L.NRRIFPARTITA = C.NRRIFPARTITA
 

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_TRASPORTO_ACQ_COSTI_TOTALI] TO [Metodo98]
    AS [dbo];

