
CREATE VIEW VISTACONTRATTI_REPFAM
AS
SELECT     ANAGRAFICAARTICOLI.CODICE, 
           CONTRATTI_RCFV_FAMIGLIA.RIFPROGRESSIVO, 
           ANAGRAFICAARTICOLI.DESCRIZIONE,
           ANAGRAFICAARTICOLI.VARESPLICITE,
           ANAGRAFICAARTICOLI.TIP_CONTATORE
FROM       TP_ExtraMag INNER JOIN
           CONTRATTI_RCFV_FAMIGLIA ON TP_ExtraMag.CodFamigliaPOS = CONTRATTI_RCFV_FAMIGLIA.FAMIGLIA AND 
           TP_ExtraMag.CodRepartoPOS = CONTRATTI_RCFV_FAMIGLIA.REPARTO INNER JOIN
           ANAGRAFICAARTICOLI ON TP_ExtraMag.CodArt = ANAGRAFICAARTICOLI.CODICE
WHERE     (ANAGRAFICAARTICOLI.ARTTIPOLOGIA = 0)



GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONTRATTI_REPFAM] TO [Metodo98]
    AS [dbo];

