

CREATE VIEW VISTA_FETS_ELENCOFILEELABORATI AS

     SELECT * FROM (
		select EL.PROGRESSIVO AS PROGRESSELENCODOC,EL.NOMEFILE,(SELECT TOP 1 PERCORSODOWNLOADFILE  FROM  FETS_ParametriGenerali) AS PATHFILE,
		ISNULL(Uffici.CODCF,'') AS CODCF, ISNULL((SELECT DSCCONTO1 FROM ANAGRAFICACF CF WHERE CF.CODCONTO=Uffici.CODCF),'') AS RAGSOCCF,
 		ISNULL(Uffici.CODCFFATT,'') AS CODCFFATT, ISNULL((SELECT DSCCONTO1 FROM ANAGRAFICACF CF WHERE CF.CODCONTO=Uffici.CODCFFATT),'') AS RAGSOCCFFATT,
		ISNULL(Uffici.DESTINAZIONEDIVERSA,0) AS DESTINAZIONEDIVERSA , ISNULL((SELECT RAGIONESOCIALE FROM DESTINAZIONIDIVERSE DD WHERE DD.CODICE = Uffici.DESTINAZIONEDIVERSA AND DD.CODCONTO=Uffici.CODCF),'') AS RAGSOCDDM,
        ISNULL((SELECT INDIRIZZO FROM DESTINAZIONIDIVERSE DD WHERE DD.CODICE = Uffici.DESTINAZIONEDIVERSA AND DD.CODCONTO=Uffici.CODCF),'') AS INDIRIZZODDM,
		ISNULL((SELECT LOCALITA FROM DESTINAZIONIDIVERSE DD WHERE DD.CODICE = Uffici.DESTINAZIONEDIVERSA AND DD.CODCONTO=Uffici.CODCF),'') AS LOCALITADDM, 
        ISNULL((SELECT PROVINCIA FROM DESTINAZIONIDIVERSE DD WHERE DD.CODICE = Uffici.DESTINAZIONEDIVERSA AND DD.CODCONTO=Uffici.CODCF),'') AS PROVINCIADDM,   		
		
		ISNULL((Select top 1 DOC.CODICEMET from FETS_CODIFICHEDOCUMENTI DOC
		  WHERE DOC.TIPOCICLO = 1 AND 
		  (EL.CodiceB2b = DOC.CODICEB2B AND EL.CodiceCarattB2b = DOC.CODICECARATTB2B))
		  ,'') AS MET_TIPODOC,

         CodiceB2B,CodicecarattB2B,
		 ISNULL(TD.PROGRESSIVO,0) AS PROGRESSDOC,ISNULL(TD.ESERCIZIO,0) AS ESERCIZIO, ISNULL(TD.NUMERODOC,0) AS NUMERODOC,ISNULL(TD.BIS,'') AS BIS,
		 ISNULL(TD.NUMRIFDOC,'') AS NUMRIFDOC,ISNULL(EL.STATOELAB,0) AS STATOELAB,
         ROW_NUMBER() OVER(PARTITION BY EL.PROGRESSIVO ORDER BY EL.PROGRESSIVO) AS PRow
		 From FETS_ELENCODOCUMENTI EL LEFT JOIN TESTEDOCUMENTI TD ON EL.PROGRESSIVODOC=TD.PROGRESSIVO  
		 ,FETS_ListaUfficiAttivi Uffici
		Where 
		EL.stato=1 AND EL.Tipo = 0  AND LEFT(Uffici.CODCF,1)='F' AND 
		(Uffici.PROGRESSIVOUFFICIO = El.Transmitterid or Uffici.PROGRESSIVOUFFICIO  = El.Transmitterid  +'-000') ) AS TAB
     WHERE PRow=1



GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_FETS_ELENCOFILEELABORATI] TO [Metodo98]
    AS [dbo];

