
CREATE VIEW VISTAARTICOLITABLET
AS
SELECT     TOP (100) PERCENT NULL AS sStatistica, dbo.TMP_VISARTULTPREZZFORCLI.CODCONTO, dbo.ANAGRAFICAARTICOLI.CODICE AS CODARTICOLO, 
                      dbo.ANAGRAFICAARTICOLI.DESCRIZIONE, 0 AS Listino, dbo.TMP_VISARTULTPREZZFORCLI.DATADOC, dbo.TMP_VISARTULTPREZZFORCLI.UMGEST, 0 AS PREZZO, 
                      dbo.TMP_VISARTULTPREZZFORCLI.QTAGEST AS QTA, 0 AS QTAOMA, 0 AS TipoOma, 0 AS QTAN, 0 AS QTANO, 0 AS TipoOmaN, NULL AS SCONTOBASE, NULL 
                      AS SCONTOAGGIUNTIVO, NULL AS SCONTOCONTRATTO, NULL AS cCalc1, NULL AS cCalc2, NULL AS cCalc3, NULL AS cCalc4, NULL AS cCalc5, NULL AS cCalc6, NULL
                       AS cCalc7, NULL AS cCalc8, NULL AS cCalc9, NULL AS cDATACons, dbo.ANAGRAFICAARTICOLI.GRUPPO, dbo.ANAGRAFICAARTICOLI.CATEGORIA, 
                      dbo.ANAGRAFICAARTICOLI.CODCATEGORIASTAT, dbo.TP_ExtraMag.CodFamigliaPOS, dbo.TP_ExtraMag.CodRepartoPOS, dbo.TP_ExtraMag.DataFineSegn, 
                      dbo.TMP_VISARTULTPREZZFORCLI.TIPODOC
FROM         dbo.ANAGRAFICAARTICOLI LEFT OUTER JOIN
                      dbo.TMP_VISARTULTPREZZFORCLI ON dbo.ANAGRAFICAARTICOLI.CODICE = dbo.TMP_VISARTULTPREZZFORCLI.CODARTICOLO LEFT OUTER JOIN
                      dbo.TP_ExtraMag ON dbo.ANAGRAFICAARTICOLI.CODICE = dbo.TP_ExtraMag.CodArt
WHERE     (dbo.ANAGRAFICAARTICOLI.ARTTIPOLOGIA = 0) AND (dbo.TP_ExtraMag.EscludiVal IS NULL) OR
                      (dbo.TP_ExtraMag.EscludiVal = 0)
ORDER BY dbo.TMP_VISARTULTPREZZFORCLI.DATADOC DESC, dbo.ANAGRAFICAARTICOLI.DESCRIZIONE


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAARTICOLITABLET] TO [Metodo98]
    AS [dbo];

