CREATE VIEW VISTAFORNITORIRIORDINO AS
select
	ART.CODICE as CODART,
	-1 as NUMERO,
	-1 as TIPORIORD,
	CF.CODCONTO as CODFOR,
	CF.DSCCONTO1 as RAGSOCFOR,
	'' as UM,
	0 as QTAMINIMA,
	0 as QTAMASSIMA,
	0 as GGAPPRONT,
	0 as GGAPPROVV,
	0 as LOTTORIF,
	0 as ARROTLOTTO
from ANAGRAFICAARTICOLI ART, ANAGRAFICACF CF
where CF.TIPOCONTO='F'

union all

select 
	CODICEART as CODART,
	0 as NUMERO,
	0 as TIPORIORD,
	FORNPREFACQ as CODFOR,
	(select DSCCONTO1 from ANAGRAFICACF where CODCONTO=FORNPREFACQ) as RAGSOCFOR,
	UMLOTTOACQ as UM,
	QMINRIORDACQ as QTAMINIMA,
	QMAXRIORDACQ as QTAMASSIMA,
	TAPPRONTACQ as GGAPPRONT,
	TAPPROVVACQ as GGAPPROVV,
	LOTTORIFACQ as LOTTORIF,
	ARROTLOTTOACQ as ARROTLOTTO
from ANAGRAFICAARTICOLIPROD
where ESERCIZIO=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))

union all

select 
	CODICEART as CODART,
	0 as NUMERO,
	1 as TIPORIORD,
	(select top 1 CODFOR from TABVINCOLIPRODUZIONE order by PROGRESSIVO desc) as CODFOR,
	(select DSCCONTO1 from ANAGRAFICACF where CODCONTO=(select top 1 CODFOR from TABVINCOLIPRODUZIONE order by PROGRESSIVO desc)) as RAGSOCFOR,
	UMLOTTOPROD as UM,
	QMINRIORDPROD as QTAMINIMA,
	QMAXRIORDPROD as QTAMASSIMA,
	TAPPRONTPROD as GGAPPRONT,
	TAPPROVVPROD as GGAPPROVV,
	LOTTORIFPROD as LOTTORIF,
	ARROTLOTTOPROD as ARROTLOTTO
from ANAGRAFICAARTICOLIPROD
where ESERCIZIO=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))

union all

select 
	CODICEART as CODART,
	0 as NUMERO,
	2 as TIPORIORD,
	FORNPREFLAV as CODFOR,
	(select DSCCONTO1 from ANAGRAFICACF where CODCONTO=FORNPREFLAV) as RAGSOCFOR,
	UMLOTTOLAV as UM,
	QMINRIORDLAV as QTAMINIMA,
	QMAXRIORDLAV as QTAMASSIMA,
	TAPPRONTLAV as GGAPPRONT,
	TAPPROVVLAV as GGAPPROVV,
	LOTTORIFLAV as LOTTORIF,
	ARROTLOTTOLAV as ARROTLOTTO
from ANAGRAFICAARTICOLIPROD
where ESERCIZIO=(SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB = CAST(USER_NAME() AS VARCHAR(25)))

union all

select 
	CODART,
	NUMERO,
	TIPORIORD,
	CODFOR,
	(select DSCCONTO1 from ANAGRAFICACF where CODCONTO=CODFOR) as RAGSOCFOR,
	UM,
	QTAMINIMA,
	QTAMASSIMA,
	GGAPPRONT,
	GGAPPROVV,
	LOTTORIF,
	ARROTLOTTO
from TABLOTTIRIORDINO


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAFORNITORIRIORDINO] TO [Metodo98]
    AS [dbo];

