

-- Fine Anomalie nr. 13200, 13210

CREATE VIEW VISTAAZIONIUTENTEFORM AS 
SELECT 
    OWNERHELPCONTEXTID,
    NRRIGA,
    DESCRIZIONE, 
    VOCEMENU,
    TIPOPARAMETRO,
    (CASE WHEN TIPOPARAMETRO=1 THEN CONTROLLO ELSE ANAGRAFICA+'.'+VARIABILE END) PARAMETRO,
    CONTROLLO,
    ANAGRAFICA,
    VARIABILE,
    HELPCONTEXTID,
    NOMEUTENTE,
    (CASE WHEN NOMEUTENTE='TRM' THEN 'SI' ELSE 'NO' END) IMPCOMUNE,
    SINCRONIZZAFORM,
    FORZAAPERTURAFORM,
    FORZACHIUSURAFORM,
    IDRIGAFILTRO,
    IMPOSTAZIONE,
    TOTALE,
    PROGRESSIVO,
    (CASE WHEN SINCRONIZZAFORM=1 THEN 'SI' ELSE 'NO' END) SINCRONIZZAFORMVIS,
    (CASE WHEN FORZAAPERTURAFORM=1 THEN 'SI' ELSE 'NO' END) FORZAAPERTURAFORMVIS,
    (CASE WHEN FORZACHIUSURAFORM=1 THEN 'SI' ELSE 'NO' END) FORZACHIUSURAFORMVIS
FROM 
    AZIONIUTENTEFORM

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAAZIONIUTENTEFORM] TO [Metodo98]
    AS [dbo];

