CREATE VIEW VISTACASTELLETTIBANCHE AS
        SELECT CASTELLETTOBANCHE.CODBANCA, CASTELLETTOBANCHE.DATAINIVALIDITA, 
        CASTELLETTOBANCHE.CASTELLETTO, CASTELLETTOBANCHE.CASTELLETTOEURO, 
        CASTELLETTOBANCHE.UTENTEMODIFICA, CASTELLETTOBANCHE.DATAMODIFICA
        FROM TABESERCIZI, CASTELLETTOBANCHE
        WHERE CASTELLETTOBANCHE.DATAINIVALIDITA >= TABESERCIZI.DATAINICONT
        AND TABESERCIZI.CODICE = (SELECT ESERCIZIOATTIVO FROM TABUTENTI WHERE USERDB=CAST(USER_NAME() AS VARCHAR(25)))


GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACASTELLETTIBANCHE] TO [Metodo98]
    AS [dbo];

