
CREATE VIEW VISTACONGRUENZAPARTITESCAD AS
SELECT VPC.*,
   (SELECT DSCCONTO1 FROM TABCFG WHERE CODCONTO=VPC.CONTO) AS DSCCONTO,
   (SELECT SUM(IMPORTOSCADLIRE) FROM VISTASCADENZE WHERE ESITO=0 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADNONEMESSELIRE,
   (SELECT SUM(IMPORTOSCADLIRE) FROM VISTASCADENZE WHERE ESITO=1 AND FLAGCONT=0 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADEMESSELIRE,
   (SELECT SUM(IMPORTOSCADLIRE) FROM VISTASCADENZE WHERE ESITO=3 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADINSOLLIRE,
   (SELECT SUM(IMPORTOSCADEURO) FROM VISTASCADENZE WHERE ESITO=0 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADNONEMESSEEURO,
   (SELECT SUM(IMPORTOSCADEURO) FROM VISTASCADENZE WHERE ESITO=1 AND FLAGCONT=0 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADEMESSEEURO,
   (SELECT SUM(IMPORTOSCADEURO) FROM VISTASCADENZE WHERE ESITO=3 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADINSOLEURO,
   (SELECT SUM(IMPORTOSCADVALUTA) FROM VISTASCADENZE WHERE ESITO=0 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADNONEMESSEVALUTA,
   (SELECT SUM(IMPORTOSCADVALUTA) FROM VISTASCADENZE WHERE ESITO=1 AND FLAGCONT=0 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADEMESSEVALUTA,
   (SELECT SUM(IMPORTOSCADVALUTA) FROM VISTASCADENZE WHERE ESITO=3 AND NUMRIFPARTCONT=VPC.NRPARTITA AND CODCLIFOR=VPC.CONTO) AS SCADINSOLVALUTA
   FROM VISTAPARTITECONTABILITA VPC

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONGRUENZAPARTITESCAD] TO [Metodo98]
    AS [dbo];

