
CREATE VIEW VISTADATAVALORICAMBIO AS
        SELECT VALORICAMBIO.DATA
        FROM VALORICAMBIO
        GROUP BY VALORICAMBIO.DATA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTADATAVALORICAMBIO] TO [Metodo98]
    AS [dbo];

