-- FINE RM: 6138 ------------------------------------------------------------------------------------------------------------------------------

-- RM: 5302 ------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW VISTADATIFATTURAIVA AS
SELECT DFI.IDTESTA,MAX(DFI.IDRIGA) AS IDRIGA,
   (SUM(DFI.IMPONIBILEEURO)*-1) AS IMPONIBILEFATT,
   (SUM(DFI.IMPOSTAEURO)*-1) AS IMPOSTAFATT,
   SUM(DFI.IMPONIBILEEURO) AS IMPONIBILEEURO,
   SUM(DFI.IMPOSTAEURO) AS IMPOSTAEURO,   
   TI.ALIQUOTA AS ALIQIVA,
   TI.TIPOINTRACEE,
   MIN(TI.INDETRAIBILITA) AS INDETRAIBILITA,
   0 AS DEDUCIBILITA,
   TI.NATURAESENZPA AS NATURAESENZ,
   ISNULL((SELECT TOP 1 NOTAACCR FROM RIGHEIVA WHERE NRREG=(SELECT NRREGCONT FROM TESTEDATIFATTURA WHERE PROGRESSIVO=IDTESTA)),0) AS NOTAACCR,
  (CASE WHEN (MAX(DFI.CODIVA) BETWEEN 600 AND 699) THEN 'D' 
      WHEN ISNULL((SELECT SPLITPAYMENT FROM TESTECONTABILITA WHERE PROGRESSIVO=(SELECT NRREGCONT FROM TESTEDATIFATTURA WHERE PROGRESSIVO=IDTESTA)),0)<>0 AND NOT (MAX(DFI.CODIVA) BETWEEN 200 AND 299) THEN 'S' 
      ELSE 'I' END) AS ESIGIBIVA   
   FROM RIGHEIVADATIFATTURA DFI LEFT OUTER JOIN TRATTAMENTOIVA TI ON DFI.CODIVA=TI.CODICE GROUP BY DFI.IDTESTA,TI.ALIQUOTA,TI.TIPOINTRACEE,TI.NATURAESENZPA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTADATIFATTURAIVA] TO [Metodo98]
    AS [dbo];

