CREATE VIEW VISTACONSEGNE AS
SELECT CA.TIPODOC, CA.NUMERODOC, CA.BIS, CA.VARIANTI, 
    CA.ESERCIZIO, CA.IDRIGA, CA.IDTESTA, CA.IDSESSIONE, 
    CA.QUANTITA, CA.QTADACONS, CA.PROGAGENTE, CA.IDENTIFICATIVOCONS,
    TD.CODCLIFOR AS CODCLIENTE,
    (SELECT DSCCONTO1 FROM ANAGRAFICACF WHERE CODCONTO = TD.CODCLIFOR) AS RAGSOCCLI, 
    RD.CODART AS CODARTICOLO, CA.QTACONSIDERATA, CA.CAMPOCONSIDERATO,
    RD.DESCRIZIONEART, CA.NRRIFPARTITA AS CODPARTITA, 
    CA.UBICAZIONE, CA.CODDEPOSITO, CA.UM
FROM CONSEGNEAGENTE CA INNER JOIN
    TESTEDOCUMENTI TD ON 
    CA.IDTESTA = TD.PROGRESSIVO INNER JOIN
    RIGHEDOCUMENTI RD ON CA.IDRIGA = RD.IDRIGA AND 
    CA.IDTESTA = RD.IDTESTA

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACONSEGNE] TO [Metodo98]
    AS [dbo];

