CREATE VIEW VISTACOSTIDIRPN AS
SELECT
	IDCOMMCLI,
	NRRIGA,
	NRREG,
	NRRIGAPN,
	(SELECT POSIZIONE FROM RIGHECONTABILITA WHERE NRREG=CC.NRREG AND NRRIGA=CC.NRRIGAPN) AS POSIZIONEPN,
	CONTOGEN,
	CONTOCDC,
	CAUSALE,
	DESCRIZIONE,
	RIFFATTURA,
	CONTROPARTITA,
	IMPORTO,
	NATURARILEVAZIONE,
	TIPOREC,
	VOCEBASE,
	IDVOCE,
	IMPORTOEURO,
	TIPOCOSTO,
	IDTABELLA,
	IDCENTROCOSTO,
	ORIGINEEVENTO,
	TIPOINSERIMENTO,
	DATAELAB_CONS,
	DATAELAB_VAL,
	DATAMOVIMENTO,
	DATADISPONIBILITA,
	DATACOMPETENZA,
	DATARIFVALORIZ,
	TIPORECDETT,
	QTABASE,
	QTAVAL,
	UMBASE,
	UMVAL,
	QTABUDGET,
	PESO,
	UTENTEMODIFICA,
	DATAMODIFICA
FROM
	CCBILANCIOCONSCOSTIDIRPN CC

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTACOSTIDIRPN] TO [Metodo98]
    AS [dbo];

