create view VISTAANALISILISTEMOVORD as
select 
	TEMPANALISILISTEMOV.IDSESSIONE,TEMPANALISILISTEMOV.IDTESTALISTA,TEMPANALISILISTEMOV.IDRIGALISTA,
	TESTELISTAMOV.CODICELISTA,TESTELISTAMOV.ESERCIZIO as ANNOLISTA,TESTELISTAMOV.NUMEROLISTA,
	TEMPANALISILISTEMOV.IDTESTACOMM,TEMPANALISILISTEMOV.IDRIGAORD,TEMPANALISILISTEMOV.IDRIGAIMPEGNO,
	TESTEORDINIPROD.TIPOCOM,TESTEORDINIPROD.ESERCIZIO as ANNOCOM,TESTEORDINIPROD.NUMEROCOM,RIGHEORDPROD.CODICEORD,
	TEMPANALISILISTEMOV.ARTICOLO,RIGHEORDPROD.DESCRIZIONEART,
	TEMPANALISILISTEMOV.QTALISTA,TEMPANALISILISTEMOV.QTAPROPOSTA,RIGHELISTAMOV.UMGEST,
	TEMPANALISILISTEMOV.FLAGSELEZIONA,TEMPANALISILISTEMOV.FLAGAZIONE
from 
	((TEMPANALISILISTEMOV inner join 
		(TESTEORDINIPROD inner join RIGHEORDPROD on RIGHEORDPROD.IDTESTA=TESTEORDINIPROD.PROGRESSIVO) 
		on RIGHEORDPROD.IDTESTA=TEMPANALISILISTEMOV.IDTESTACOMM and RIGHEORDPROD.IDRIGA=TEMPANALISILISTEMOV.IDRIGAORD)
	inner join (RIGHELISTAMOV inner join TESTELISTAMOV on TESTELISTAMOV.PROGRESSIVO=RIGHELISTAMOV.IDTESTA) 
		on RIGHELISTAMOV.IDTESTA=TEMPANALISILISTEMOV.IDTESTALISTA and RIGHELISTAMOV.IDRIGA=TEMPANALISILISTEMOV.IDRIGALISTA)

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAANALISILISTEMOVORD] TO [Metodo98]
    AS [dbo];

