
CREATE VIEW VISTA_CESCCOSTO_ATI
AS
SELECT  
    CODCESPITE,
    NRRIGA,
    CODCCOSTO,
    PRCRIPARTIZIONE,
    UTENTEMODIFICA,
    DATAMODIFICA,
    0 AS TIPOPERC
FROM    
    CESCCOSTO_ATI

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTA_CESCCOSTO_ATI] TO [Metodo98]
    AS [dbo];

