

CREATE VIEW VISTAAVANZAMENTOMOVIMENTI
AS
    SELECT dbo.VISTASTORICOAVANZAMENTI.*, dbo.TABELLADIPENDENTI.COGNOME + ' ' + dbo.TABELLADIPENDENTI.NOME AS DIP, 
    dbo.TABELLAREPARTI.DESCRIZIONE AS DESCREP
    FROM dbo.TABELLADIPENDENTI RIGHT OUTER JOIN
    dbo.DIPENDENTIMOVIMENTO ON dbo.TABELLADIPENDENTI.CODICE = dbo.DIPENDENTIMOVIMENTO.DIPENDENTE RIGHT OUTER JOIN
    dbo.VISTASTORICOAVANZAMENTI ON 
    dbo.DIPENDENTIMOVIMENTO.RIFPROGRESSIVO = dbo.VISTASTORICOAVANZAMENTI.PROGRESSIVO LEFT OUTER JOIN
    dbo.TABELLAREPARTI ON dbo.VISTASTORICOAVANZAMENTI.CODREPARTO = dbo.TABELLAREPARTI.CODICE

GO
GRANT SELECT
    ON OBJECT::[dbo].[VISTAAVANZAMENTOMOVIMENTI] TO [Metodo98]
    AS [dbo];

