CREATE TABLE [dbo].[ACQ_OFFERTAESITI] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [ESITO]          SMALLINT     CONSTRAINT [DF_ACQ_OFFERTAESITI_ESITO] DEFAULT ((0)) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ACQ_OFFERTAESITI]
    ON [dbo].[ACQ_OFFERTAESITI]([RIFPROGRESSIVO] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ACQ_OFFERTAESITI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ACQ_OFFERTAESITI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ACQ_OFFERTAESITI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ACQ_OFFERTAESITI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ACQ_OFFERTAESITI] TO [Metodo98]
    AS [dbo];

