CREATE TABLE [dbo].[AGENTI_ECOM] (
    [CODAGENTE]      VARCHAR (7)  CONSTRAINT [DF_CODAGENTE] DEFAULT ('') NOT NULL,
    [EMAIL]          VARCHAR (50) CONSTRAINT [DF_EMAIL] DEFAULT ('') NOT NULL,
    [PASSWORD]       VARCHAR (50) CONSTRAINT [DF_PASSWORD] DEFAULT ('') NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [CK_CODAGENTE] PRIMARY KEY CLUSTERED ([CODAGENTE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[AGENTI_ECOM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AGENTI_ECOM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[AGENTI_ECOM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AGENTI_ECOM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AGENTI_ECOM] TO [Metodo98]
    AS [dbo];

