CREATE TABLE [dbo].[ALD_TEMPPIANIFDEP] (
    [NRTERMINALE] SMALLINT     NOT NULL,
    [CODART]      VARCHAR (50) NOT NULL,
    [CODDEPOSITO] VARCHAR (10) NOT NULL,
    [DATA]        DATETIME     NULL,
    CONSTRAINT [PK_ALD_TEMPPIANIFDEP] PRIMARY KEY CLUSTERED ([NRTERMINALE] ASC, [CODART] ASC, [CODDEPOSITO] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ALD_TEMPPIANIFDEP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ALD_TEMPPIANIFDEP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ALD_TEMPPIANIFDEP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ALD_TEMPPIANIFDEP] TO [Metodo98]
    AS [dbo];

