CREATE TABLE [dbo].[ARTICOLICAUZIONI] (
    [CODCLIFOR]      VARCHAR (7)  NOT NULL,
    [CODART]         VARCHAR (50) NOT NULL,
    [CODCAUZIONE]    VARCHAR (50) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_ARTICOLICAUZIONI] PRIMARY KEY CLUSTERED ([CODCLIFOR] ASC, [CODART] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ARTICOLICAUZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ARTICOLICAUZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ARTICOLICAUZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ARTICOLICAUZIONI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ARTICOLICAUZIONI] TO [Metodo98]
    AS [dbo];

