CREATE TABLE [dbo].[CASTELLETTOBANCHE] (
    [CODBANCA]         VARCHAR (7)     NOT NULL,
    [DATAINIVALIDITA]  DATETIME        NOT NULL,
    [DATAFINEVALIDITA] DATETIME        NULL,
    [CASTELLETTO]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [CASTELLETTOEURO]  DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]   VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]     DATETIME        NOT NULL,
    CONSTRAINT [PK_CASTELLETTOBANCHE] PRIMARY KEY CLUSTERED ([CODBANCA] ASC, [DATAINIVALIDITA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CASTELLETTOBANCHE_CODBANCA] FOREIGN KEY ([CODBANCA]) REFERENCES [dbo].[ANAGRAFICABANCHE] ([CODBANCA]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CASTELLETTOBANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CASTELLETTOBANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CASTELLETTOBANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CASTELLETTOBANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CASTELLETTOBANCHE] TO [Metodo98]
    AS [dbo];

