CREATE TABLE [dbo].[CATALOGO_ACCESSI_GRUPPO] (
    [ID]             INT          NOT NULL,
    [CODTIPO]        INT          NOT NULL,
    [GRUPPOID]       DECIMAL (5)  NOT NULL,
    [FLAGABILITA]    SMALLINT     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC, [CODTIPO] ASC, [GRUPPOID] ASC),
    CONSTRAINT [FK_CATALOGO_ACCESSI_GRUPPO_CATALOGO_TIPI_ENTITA] FOREIGN KEY ([CODTIPO]) REFERENCES [dbo].[CATALOGO_TIPI_ENTITA] ([CODICE]) ON DELETE CASCADE,
    CONSTRAINT [FK_CATALOGO_ACCESSI_GRUPPO_TABGRUPPIUTENTE] FOREIGN KEY ([GRUPPOID]) REFERENCES [dbo].[TABGRUPPIUTENTE] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_GRUPPO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_GRUPPO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_GRUPPO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_GRUPPO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CATALOGO_ACCESSI_GRUPPO] TO [Metodo98]
    AS [dbo];

