CREATE TABLE [dbo].[CAUSALIPAGAMENTOPA] (
    [CODICE]      VARCHAR (2)   NOT NULL,
    [DESCRIZIONE] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_CAUSALIPAGAMENTOPA] PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CAUSALIPAGAMENTOPA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CAUSALIPAGAMENTOPA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CAUSALIPAGAMENTOPA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CAUSALIPAGAMENTOPA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CAUSALIPAGAMENTOPA] TO [Metodo98]
    AS [dbo];

