CREATE TABLE [dbo].[CAUSALICOLLEGATE] (
    [CODCAUSALE]     DECIMAL (5)  NOT NULL,
    [CODCAUSCOLL]    DECIMAL (5)  NOT NULL,
    [RIGACOLL]       SMALLINT     NOT NULL,
    [RIGAORIG]       SMALLINT     NOT NULL,
    [SEGNO]          SMALLINT     DEFAULT (0) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_CAUSALICOLLEGATE] PRIMARY KEY CLUSTERED ([CODCAUSALE] ASC, [CODCAUSCOLL] ASC, [RIGACOLL] ASC, [RIGAORIG] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_SEGNO_CAUSALIC] CHECK ([SEGNO] = 0 or [SEGNO] = 1),
    CONSTRAINT [FK_CAUSALICOLLEGATE_CODCAUSALE] FOREIGN KEY ([CODCAUSALE]) REFERENCES [dbo].[CAUSALICONTABILI] ([CODICECAUSALE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [CAUSALICONTABILI]
    ON [dbo].[CAUSALICOLLEGATE]([CODCAUSALE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [CAUSCOLL_1]
    ON [dbo].[CAUSALICOLLEGATE]([CODCAUSALE] ASC, [RIGACOLL] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CAUSALICOLLEGATE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CAUSALICOLLEGATE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CAUSALICOLLEGATE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CAUSALICOLLEGATE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CAUSALICOLLEGATE] TO [Metodo98]
    AS [dbo];

