CREATE TABLE [dbo].[CCBILANCIOCONSLAVEST] (
    [IDCOMMCLI]         DECIMAL (10)    NOT NULL,
    [NRRIGA]            INT             NOT NULL,
    [IDTESTADOC]        DECIMAL (10)    NULL,
    [IDRIGADOC]         INT             NULL,
    [IDTESTAFATT]       DECIMAL (10)    NULL,
    [IDRIGAFATT]        INT             NULL,
    [CODART]            VARCHAR (50)    NULL,
    [DSCARTICOLO]       VARCHAR (255)   NULL,
    [QUANTITA]          DECIMAL (16, 6) DEFAULT (0) NULL,
    [UMBASE]            VARCHAR (3)     NULL,
    [COSTOUNILAV]       DECIMAL (19, 4) DEFAULT (0) NULL,
    [COSTOTOTLAV]       DECIMAL (19, 4) DEFAULT (0) NULL,
    [CODFOR]            VARCHAR (7)     NULL,
    [TIPOCLP]           SMALLINT        DEFAULT (0) NOT NULL,
    [NATURARILEVAZIONE] SMALLINT        DEFAULT (0) NOT NULL,
    [TIPOREC]           VARCHAR (2)     NULL,
    [CODOPERAZIONE]     VARCHAR (5)     NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    [VOCEBASE]          VARCHAR (3)     DEFAULT ('') NULL,
    [IDVOCE]            VARCHAR (3)     DEFAULT ('') NULL,
    [COSTOUNILAVEURO]   DECIMAL (19, 4) CONSTRAINT [DF_CCBILANCIOCONSLAVEST_COSTOUNILAVEURO] DEFAULT (0) NULL,
    [COSTOTOTLAVEURO]   DECIMAL (19, 4) CONSTRAINT [DF_CCBILANCIOCONSLAVEST_COSTOTOTLAVEURO] DEFAULT (0) NULL,
    [TIPOCOSTO]         VARCHAR (4)     CONSTRAINT [DF_CCBILANCIOCONSLAVEST_TIPOCOSTO] DEFAULT ('LEST') NULL,
    [IDTABELLA]         VARCHAR (10)    CONSTRAINT [DF_CCBILANCIOCONSLAVEST_IDTABELLA] DEFAULT ('LEST') NULL,
    [ORIGINEEVENTO]     SMALLINT        NULL,
    [QTAVAL]            DECIMAL (16, 6) CONSTRAINT [DF_CCBILANCIOCONSLAVEST_QTAVAL] DEFAULT (0) NULL,
    [UMVAL]             VARCHAR (3)     NULL,
    [TIPOINSERIMENTO]   SMALLINT        NULL,
    [DATAELAB_CONS]     DATETIME        NULL,
    [DATAELAB_VAL]      DATETIME        NULL,
    [DATAMOVIMENTO]     DATETIME        NULL,
    [DATADISPONIBILITA] DATETIME        NULL,
    [DATACOMPETENZA]    DATETIME        NULL,
    [DATARIFVALORIZ]    DATETIME        NULL,
    [TIPORECDETT]       VARCHAR (2)     NULL,
    [CONTOCDC]          VARCHAR (10)    NULL,
    [QTABUDGET]         DECIMAL (16, 6) NULL,
    [PESO]              DECIMAL (8, 5)  NULL,
    [NOTE]              VARCHAR (500)   NULL,
    [DESCRIZIONE]       VARCHAR (254)   NULL,
    [ANNOBOLLA]         SMALLINT        NULL,
    [NUMEROBOLLA]       INT             NULL,
    [TIPORECVAL]        VARCHAR (2)     NULL,
    CONSTRAINT [PK_CCBILANCIOCONSLAVEST] PRIMARY KEY CLUSTERED ([IDCOMMCLI] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CCBILANCIOCONSLAVEST_IDCOMMCLI] FOREIGN KEY ([IDCOMMCLI]) REFERENCES [dbo].[AnagraficaCommesse] ([Progressivo]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CCBILANCIOCONSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CCBILANCIOCONSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CCBILANCIOCONSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CCBILANCIOCONSLAVEST] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CCBILANCIOCONSLAVEST] TO [Metodo98]
    AS [dbo];

