CREATE TABLE [dbo].[CONSEGNEGIAC] (
    [IDSESSIONE]     INT             NOT NULL,
    [CODART]         VARCHAR (50)    NOT NULL,
    [NRRIFPARTITA]   VARCHAR (15)    NOT NULL,
    [UBICAZIONE]     VARCHAR (10)    NOT NULL,
    [UM]             VARCHAR (3)     NOT NULL,
    [GIACENZA]       DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [RESIDUO]        DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    [CODDEPOSITO]    VARCHAR (10)    CONSTRAINT [DF_CONSEGNEGIAC_CODDEPOSITO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_CONSEGNEGIAC] PRIMARY KEY CLUSTERED ([IDSESSIONE] ASC, [CODART] ASC, [NRRIFPARTITA] ASC, [CODDEPOSITO] ASC, [UBICAZIONE] ASC, [UM] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [CONSEGNEGIAC_CODART]
    ON [dbo].[CONSEGNEGIAC]([CODART] ASC, [IDSESSIONE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [NRRIFPARTITACONS]
    ON [dbo].[CONSEGNEGIAC]([NRRIFPARTITA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONSEGNEGIAC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONSEGNEGIAC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONSEGNEGIAC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONSEGNEGIAC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONSEGNEGIAC] TO [Metodo98]
    AS [dbo];

