CREATE TABLE [dbo].[CONTRATTI_CL] (
    [RIFPROGRESSIVO]          DECIMAL (10)    NOT NULL,
    [NRRIGA]                  INT             NOT NULL,
    [FLAGRIGA]                SMALLINT        NULL,
    [POSIZIONE]               INT             NULL,
    [DESCRIZIONE]             VARCHAR (500)   NULL,
    [BOLISPERC]               SMALLINT        DEFAULT (0) NOT NULL,
    [VALORE]                  DECIMAL (19, 6) DEFAULT (0) NULL,
    [MERCEVALORE]             DECIMAL (19, 6) NULL,
    [MERCEQTA]                SMALLINT        DEFAULT (0) NULL,
    [DATAEMISSIONEDOC]        DATETIME        NULL,
    [TIPODOC]                 VARCHAR (3)     NULL,
    [IVA]                     VARCHAR (3)     NULL,
    [PAGAMENTO]               VARCHAR (4)     NULL,
    [SOTTOCONTOCONTABILE]     VARCHAR (7)     NULL,
    [EMESSO]                  SMALLINT        DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]          VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]            DATETIME        NOT NULL,
    [NOTE]                    VARCHAR (500)   NULL,
    [PREVISIONI]              SMALLINT        DEFAULT (2) NULL,
    [TIPO]                    SMALLINT        DEFAULT (0) NULL,
    [PERIODICITALIQUIDAZIONE] INT             DEFAULT (0) NULL,
    [TIPOCALCOLOPREMIO]       SMALLINT        DEFAULT (0) NULL,
    [UM]                      VARCHAR (3)     NULL,
    [CODSCONTO]               VARCHAR (5)     DEFAULT ('') NULL,
    [GGTOLLERANZA]            INT             DEFAULT ((0)) NULL,
    [PREMIONONVALIDO]         SMALLINT        DEFAULT ((0)) NULL,
    [PRCAG1]                  SMALLINT        DEFAULT ((0)) NULL,
    [PRCAG2]                  SMALLINT        DEFAULT ((0)) NULL,
    [PRCAG3]                  SMALLINT        DEFAULT ((0)) NULL,
    [ESCLUSOLOGICAMENTE]      SMALLINT        DEFAULT ((0)) NULL,
    [LiqIntestaCFFatt]        SMALLINT        DEFAULT ((0)) NULL,
    [CPCALCSCAD]              SMALLINT        DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO


CREATE TRIGGER CANCELLACLQTA ON CONTRATTI_CL
FOR DELETE 
AS
      DELETE CONTRATTICL_QTA
       FROM   CONTRATTICL_QTA T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVOCL = T1.RIFPROGRESSIVO
          AND T2.RIFPROGRESSIVO=T1.NRRIGA

      DELETE CONTRATTICL_QTAMERCE
       FROM   CONTRATTICL_QTAMERCE T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVOCL = T1.RIFPROGRESSIVO
          AND T2.RIFPROGRESSIVO=T1.NRRIGA

      DELETE CONTRATTICL_QTAVALORE
       FROM   CONTRATTICL_QTAVALORE T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVOCL = T1.RIFPROGRESSIVO
          AND T2.RIFPROGRESSIVO=T1.NRRIGA

      DELETE CONTRATTICL_DATEDOC
       FROM   CONTRATTICL_DATEDOC T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVOCL = T1.RIFPROGRESSIVO
          AND T2.RIFPROGRESSIVO=T1.NRRIGA

      DELETE CONTRATTIDOC_NCIMP 
       FROM   CONTRATTIDOC_NCIMP  T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.RIFPROGRESSIVO
          AND T2.NRRIGA=T1.NRRIGA
 

GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_CL] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_CL] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_CL] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_CL] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_CL] TO [Metodo98]
    AS [dbo];

