CREATE TABLE [dbo].[CONTRATTI_PREMIMATURATI] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [RIFRIGA]        INT             NOT NULL,
    [RIFRIGADICUI]   INT             DEFAULT (0) NOT NULL,
    [VALORE]         DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NULL,
    [DATAMODIFICA]   DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [RIFRIGA] ASC, [RIFRIGADICUI] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_PREMIMATURATI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_PREMIMATURATI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_PREMIMATURATI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_PREMIMATURATI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_PREMIMATURATI] TO [Metodo98]
    AS [dbo];

