CREATE TABLE [dbo].[CONTRATTIPERC_ASSOR] (
    [RIFPROGRESSIVO] DECIMAL (18)    NOT NULL,
    [ANNO]           INT             NOT NULL,
    [MESE]           INT             NOT NULL,
    [VALOREPERC]     DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [NRRIGA]         INT             DEFAULT (0) NOT NULL,
    [TIPORIGA]       VARCHAR (1)     DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_CONTRATTIPERC_ASSOR] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [ANNO] ASC, [MESE] ASC, [NRRIGA] ASC, [TIPORIGA] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTIPERC_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTIPERC_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTIPERC_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTIPERC_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTIPERC_ASSOR] TO [Metodo98]
    AS [dbo];

