CREATE TABLE [dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [CONTRATTO]      DECIMAL (10)    DEFAULT (0) NOT NULL,
    [CATEGORIA]      DECIMAL (5)     DEFAULT (0) NOT NULL,
    [FATTURATO]      DECIMAL (19, 6) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [CONTRATTO] ASC, [CATEGORIA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO]
    ON [dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO]([RIFPROGRESSIVO] ASC, [CATEGORIA] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTIAVPROGRESSIVO_RIGHEFATTURATO] TO [Metodo98]
    AS [dbo];

