CREATE TABLE [dbo].[CONTRATTICL_QTA] (
    [RIFPROGRESSIVOCL]        DECIMAL (10)    NOT NULL,
    [RIFPROGRESSIVO]          DECIMAL (10)    NOT NULL,
    [NRRIGA]                  INT             NOT NULL,
    [FLAGRIGA]                SMALLINT        NULL,
    [POSIZIONE]               INT             NULL,
    [DADATA]                  DATETIME        NULL,
    [ADATA]                   DATETIME        NULL,
    [PERCENTUALE]             DECIMAL (19, 6) NULL,
    [BUDGET]                  DECIMAL (19, 6) NULL,
    [CONSUNTIVO]              DECIMAL (19, 6) NULL,
    [DATAEMISSIONEDOC]        DATETIME        NULL,
    [TIPODOC]                 VARCHAR (3)     NULL,
    [IVA]                     VARCHAR (3)     NULL,
    [PAGAMENTO]               VARCHAR (4)     NULL,
    [SOTTOCONTOCONTABILE]     VARCHAR (7)     NULL,
    [EMESSO]                  SMALLINT        NULL,
    [UTENTEMODIFICA]          VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]            DATETIME        NOT NULL,
    [PREVISIONI]              SMALLINT        DEFAULT (2) NULL,
    [TIPO]                    SMALLINT        DEFAULT (0) NULL,
    [PERIODICITALIQUIDAZIONE] INT             DEFAULT (0) NULL,
    [CONSUNTIVOSTORICO]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [PREMIOMATURATO]          DECIMAL (19, 6) DEFAULT (0) NULL,
    [BUDGETQTA]               DECIMAL (19, 6) DEFAULT (0) NULL,
    [CONSUNTIVOQTA]           DECIMAL (19, 6) DEFAULT (0) NULL,
    [CONSUNTIVOSTORICOQTA]    DECIMAL (19, 6) DEFAULT (0) NULL,
    [PREMIONONVALIDO]         SMALLINT        DEFAULT ((0)) NULL,
    [ESCLUSOLOGICAMENTE]      SMALLINT        DEFAULT ((0)) NULL,
    [LiqIntestaCFFatt]        SMALLINT        DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVOCL] ASC, [RIFPROGRESSIVO] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO


CREATE TRIGGER DELETECLQTA ON CONTRATTICL_QTA
FOR DELETE 
AS

      DELETE CONTRATTICL_QTADATEDOC
       FROM   CONTRATTICL_QTADATEDOC T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVOCL = T1.RIFPROGRESSIVOCL
	AND T2.RIFPROGRESSIVO=T1.RIFPROGRESSIVO 
	AND T2.RIFRIGA=T1.NRRIGA


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTICL_QTA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTICL_QTA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTICL_QTA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTICL_QTA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTICL_QTA] TO [Metodo98]
    AS [dbo];

