CREATE TABLE [dbo].[CONTRATTI_ASSOR] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (50) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [CODCLIFOR]      VARCHAR (7)  NOT NULL,
    [ESERCIZIO]      DECIMAL (5)  NOT NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO

CREATE TRIGGER CANCELLAASSOR ON CONTRATTI_ASSOR
FOR DELETE 
AS

    BEGIN	


       DELETE CONTRATTIGRP_ASSOR
       FROM   CONTRATTIGRP_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

       DELETE CONTRATTICAT_ASSOR
       FROM   CONTRATTICAT_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

       DELETE CONTRATTICATST_ASSOR
       FROM   CONTRATTICATST_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

       DELETE CONTRATTIGRPPRZ_ASSOR
       FROM   CONTRATTIGRPPRZ_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

       DELETE CONTRATTIFAMREP_ASSOR
       FROM   CONTRATTIFAMREP_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

       DELETE CONTRATTIART_ASSOR
       FROM   CONTRATTIART_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

       DELETE CONTRATTIPERC_ASSOR
       FROM   CONTRATTIPERC_ASSOR T2, DELETED T1
       WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

    END


GO
GRANT DELETE
    ON OBJECT::[dbo].[CONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[CONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CONTRATTI_ASSOR] TO [Metodo98]
    AS [dbo];

