CREATE TABLE [dbo].[DEP_IMPOSTAZIONIPRODDEP] (
    [NOMEPIANIF]     VARCHAR (30) NOT NULL,
    [PROGRESSIVO]    SMALLINT     NOT NULL,
    [CODDEPOSITO]    VARCHAR (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_DEP_IMPOSTAZIONIPRODDEP] PRIMARY KEY CLUSTERED ([NOMEPIANIF] ASC, [PROGRESSIVO] ASC),
    CONSTRAINT [FK_DEP_IMPPRODDEP] FOREIGN KEY ([NOMEPIANIF]) REFERENCES [dbo].[IMPOSTAZIONIPRODDEP] ([NOMEPIANIF]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[DEP_IMPOSTAZIONIPRODDEP] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[DEP_IMPOSTAZIONIPRODDEP] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[DEP_IMPOSTAZIONIPRODDEP] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[DEP_IMPOSTAZIONIPRODDEP] TO [Metodo98]
    AS [dbo];

