CREATE TABLE [dbo].[DICHIARAZIONEINTENTO_TABDOC] (
    [CODICE]         VARCHAR (3)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_DICHIARAZIONEINTENTO_TABDOC] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[DICHIARAZIONEINTENTO_TABDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[DICHIARAZIONEINTENTO_TABDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[DICHIARAZIONEINTENTO_TABDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[DICHIARAZIONEINTENTO_TABDOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[DICHIARAZIONEINTENTO_TABDOC] TO [Metodo98]
    AS [dbo];

