CREATE TABLE [dbo].[DISTINTEEFFETTI] (
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [DATAEMISS]      DATETIME     NULL,
    [DESCRIZIONE]    VARCHAR (80) NULL,
    [CODBANCA]       VARCHAR (7)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_DISTINTEEFFETTI] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [DATAEMISS]
    ON [dbo].[DISTINTEEFFETTI]([DATAEMISS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [DSCDISTINTA]
    ON [dbo].[DISTINTEEFFETTI]([DESCRIZIONE] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[DISTINTEEFFETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[DISTINTEEFFETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[DISTINTEEFFETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[DISTINTEEFFETTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[DISTINTEEFFETTI] TO [Metodo98]
    AS [dbo];

