CREATE TABLE [dbo].[ESCLUDIEFF_FIDO] (
    [ESERCIZIO]      DECIMAL (5)  NOT NULL,
    [PROGRESSIVO]    DECIMAL (5)  NOT NULL,
    [ESITO]          NUMERIC (1)  NOT NULL,
    [TIPOEFF]        NUMERIC (5)  NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_ESCLUDIEFF_FIDO] PRIMARY KEY CLUSTERED ([ESERCIZIO] ASC, [PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[ESCLUDIEFF_FIDO] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ESCLUDIEFF_FIDO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[ESCLUDIEFF_FIDO] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ESCLUDIEFF_FIDO] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ESCLUDIEFF_FIDO] TO [Metodo98]
    AS [dbo];

