CREATE TABLE [dbo].[EURIS_PRO_DIS_RIS] (
    [COD_AZIENDA]      NVARCHAR (3)     NULL,
    [COD_STABILIMENTO] NVARCHAR (3)     NULL,
    [COD_RISORSA]      NVARCHAR (12)    NULL,
    [DT_INIZIO_VAL]    DECIMAL (8)      NULL,
    [DT_FINE_VAL]      DECIMAL (8)      NULL,
    [QTA_RISORSE]      DECIMAL (8, 3)   NULL,
    [T_DISPONIBILE]    DECIMAL (15, 10) NULL,
    [TIPO_T_DISPONIB]  NVARCHAR (1)     NULL,
    [TIME_BUFFER]      DECIMAL (4, 2)   NULL,
    [T_CODA]           DECIMAL (15, 10) NULL,
    [TIPO_T_CODA]      NVARCHAR (1)     NULL,
    [T_CODA_MAX]       DECIMAL (15, 10) NULL,
    [TIPO_T_CODA_MAX]  NVARCHAR (1)     NULL,
    [PER_EFFICENZA]    DECIMAL (3)      NULL,
    [COD_CALENDARIO]   NVARCHAR (5)     NULL,
    [TMP_SOGLIA]       DECIMAL (15, 10) NULL,
    [TIPO_TMP_SOGLIA]  NVARCHAR (1)     NULL,
    [ULTIMA_MODIFICA]  DECIMAL (8)      NULL,
    [ULTIMO_UTENTE]    NVARCHAR (10)    NULL,
    CONSTRAINT [FK_EURIS_PRO_DIS_RIS_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_PRO_DIS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_PRO_DIS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_PRO_DIS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_PRO_DIS_RIS] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_PRO_DIS_RIS] TO [Metodo98]
    AS [dbo];

