CREATE TABLE [dbo].[EURIS_FAB_LEG_ORD] (
    [COD_AZIENDA]      NVARCHAR (3)  NULL,
    [COD_STABILIMENTO] NVARCHAR (3)  NULL,
    [TIP_ORD_PADRE]    NVARCHAR (3)  NULL,
    [NUM_ORD_PADRE]    NVARCHAR (15) NULL,
    [COD_FASE_PADRE]   DECIMAL (5)   NULL,
    [COD_ART_PADRE]    NVARCHAR (20) NULL,
    [TIP_ORD_FIGLIO]   NVARCHAR (3)  NULL,
    [NUM_ORD_FIGLIO]   NVARCHAR (15) NULL,
    [COD_FASE_FIGLIO]  DECIMAL (5)   NULL,
    [COD_ART_FIGLIO]   NVARCHAR (20) NULL,
    [COD_COMMESSA]     NVARCHAR (10) NULL,
    [GG_SFA_IMP_ORD]   SMALLINT      NULL,
    [FLG_CONTEMPOR]    NVARCHAR (1)  NULL,
    [ULTIMA_MODIFICA]  DATETIME      NULL,
    [ULTIMO_UTENTE]    NVARCHAR (20) NULL,
    [TIPO_CAT_ORD_P]   NVARCHAR (1)  NULL,
    [TIPO_CAT_ORD_F]   NVARCHAR (1)  NULL,
    [NUM_RIG_ORD_P]    SMALLINT      NULL,
    [NUM_RIG_ORD_F]    SMALLINT      NULL,
    CONSTRAINT [FK_EURIS_FAB_LEG_ORD_COD_AZIENDA] FOREIGN KEY ([COD_AZIENDA]) REFERENCES [dbo].[EURIS_SCHEDULAZIONI] ([CODICE]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EURIS_FAB_LEG_ORD] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EURIS_FAB_LEG_ORD] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EURIS_FAB_LEG_ORD] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EURIS_FAB_LEG_ORD] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EURIS_FAB_LEG_ORD] TO [Metodo98]
    AS [dbo];

