CREATE TABLE [dbo].[EXTRATESTECOMM] (
    [IDTESTA]        DECIMAL (10) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    CONSTRAINT [PK_EXTRATESTECOMM] PRIMARY KEY CLUSTERED ([IDTESTA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_EXTRATESTECOMM" FOR TABLE "EXTRATESTECOMM"  */
CREATE TRIGGER TI_EXTRATESTECOMM ON EXTRATESTECOMM FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TESTEORDINIPROD" MUST EXIST WHEN INSERTING A CHILD IN "EXTRATESTECOMM"  */
    IF UPDATE(IDTESTA)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TESTEORDINIPROD T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.IDTESTA) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TESTEORDINIPROD". Cannot create child in "EXTRATESTECOMM".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_EXTRATESTECOMM" FOR TABLE "EXTRATESTECOMM"  */
CREATE TRIGGER TU_EXTRATESTECOMM ON EXTRATESTECOMM FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TESTEORDINIPROD" MUST EXIST WHEN UPDATING A CHILD IN "EXTRATESTECOMM"  */
      IF UPDATE(IDTESTA)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TESTEORDINIPROD T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.IDTESTA) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TESTEORDINIPROD" does not exist. Cannot ALTER COLUMN child in "EXTRATESTECOMM".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRATESTECOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRATESTECOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRATESTECOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRATESTECOMM] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRATESTECOMM] TO [Metodo98]
    AS [dbo];

