CREATE TABLE [dbo].[EXTRACICLOPIANORISORSE] (
    [NOMEPIANORIS]   VARCHAR (10) NOT NULL,
    [PROGRESSIVO]    DECIMAL (10) NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_EXTRACICLOPIANORISORSE] PRIMARY KEY CLUSTERED ([NOMEPIANORIS] ASC, [PROGRESSIVO] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_EXTRACICLOPIANORISORSE" FOR TABLE "EXTRACICLOPIANORISORSE"  */
CREATE TRIGGER TI_EXTRACICLOPIANORISORSE ON EXTRACICLOPIANORISORSE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TESTACICLOPIANORISORSE" MUST EXIST WHEN INSERTING A CHILD IN "EXTRACICLOPIANORISORSE"  */
    IF UPDATE(NOMEPIANORIS) OR
       UPDATE(PROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TESTACICLOPIANORISORSE T1, INSERTED T2
           WHERE  T1.NOMEPIANORIS = T2.NOMEPIANORIS
            AND   T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TESTACICLOPIANORISORSE". Cannot create child in "EXTRACICLOPIANORISORSE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_EXTRACICLOPIANORISORSE" FOR TABLE "EXTRACICLOPIANORISORSE"  */
CREATE TRIGGER TU_EXTRACICLOPIANORISORSE ON EXTRACICLOPIANORISORSE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TESTACICLOPIANORISORSE" MUST EXIST WHEN UPDATING A CHILD IN "EXTRACICLOPIANORISORSE"  */
      IF UPDATE(NOMEPIANORIS) OR
         UPDATE(PROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TESTACICLOPIANORISORSE T1, INSERTED T2
             WHERE  T1.NOMEPIANORIS = T2.NOMEPIANORIS
              AND   T1.PROGRESSIVO = T2.PROGRESSIVO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TESTACICLOPIANORISORSE" does not exist. Cannot modify child in "EXTRACICLOPIANORISORSE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRACICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRACICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRACICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRACICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRACICLOPIANORISORSE] TO [Metodo98]
    AS [dbo];

