CREATE TABLE [dbo].[EXTRADIPENDENTI] (
    [CODDIP]         VARCHAR (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_EXTRADIPENDENTI] PRIMARY KEY CLUSTERED ([CODDIP] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_EXTRADIPENDENTI" FOR TABLE "EXTRADIPENDENTI"  */
CREATE TRIGGER TI_EXTRADIPENDENTI ON EXTRADIPENDENTI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABELLADIPENDENTI" MUST EXIST WHEN INSERTING A CHILD IN "EXTRADIPENDENTI"  */
    IF UPDATE(CODDIP)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABELLADIPENDENTI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODDIP) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABELLADIPENDENTI". Cannot create child in "EXTRADIPENDENTI".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_EXTRADIPENDENTI" FOR TABLE "EXTRADIPENDENTI"  */
CREATE TRIGGER TU_EXTRADIPENDENTI ON EXTRADIPENDENTI FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABELLADIPENDENTI" MUST EXIST WHEN UPDATING A CHILD IN "EXTRADIPENDENTI"  */
      IF UPDATE(CODDIP)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABELLADIPENDENTI T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODDIP) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABELLADIPENDENTI" does not exist. Cannot ALTER COLUMN child in "EXTRADIPENDENTI".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRADIPENDENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRADIPENDENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRADIPENDENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRADIPENDENTI] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRADIPENDENTI] TO [Metodo98]
    AS [dbo];

