CREATE TABLE [dbo].[EXTRAMACCHINE] (
    [CODMAC]         VARCHAR (5)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_EXTRAMACCHINE] PRIMARY KEY CLUSTERED ([CODMAC] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_EXTRAMACCHINE" FOR TABLE "EXTRAMACCHINE"  */
CREATE TRIGGER TI_EXTRAMACCHINE ON EXTRAMACCHINE FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "TABELLAMACCHINE" MUST EXIST WHEN INSERTING A CHILD IN "EXTRAMACCHINE"  */
    IF UPDATE(CODMAC)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   TABELLAMACCHINE T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODMAC) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "TABELLAMACCHINE". Cannot create child in "EXTRAMACCHINE".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_EXTRAMACCHINE" FOR TABLE "EXTRAMACCHINE"  */
CREATE TRIGGER TU_EXTRAMACCHINE ON EXTRAMACCHINE FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "TABELLAMACCHINE" MUST EXIST WHEN UPDATING A CHILD IN "EXTRAMACCHINE"  */
      IF UPDATE(CODMAC)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   TABELLAMACCHINE T1, INSERTED T2
             WHERE  T1.CODICE = T2.CODMAC) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"TABELLAMACCHINE" does not exist. Cannot ALTER COLUMN child in "EXTRAMACCHINE".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRAMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRAMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRAMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRAMACCHINE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRAMACCHINE] TO [Metodo98]
    AS [dbo];

