CREATE TABLE [dbo].[EXTRABANCHE] (
    [CODBANCA]       VARCHAR (7)  NOT NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    [BANCA]          CHAR (8)     COLLATE Latin1_General_CI_AS NULL,
    [RBN]            CHAR (4)     COLLATE Latin1_General_CI_AS NULL,
    CONSTRAINT [PK_EXTRABANCHE] PRIMARY KEY CLUSTERED ([CODBANCA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EXTRABANCHE_CODBANCA] FOREIGN KEY ([CODBANCA]) REFERENCES [dbo].[ANAGRAFICABANCHE] ([CODBANCA]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[EXTRABANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EXTRABANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EXTRABANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EXTRABANCHE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EXTRABANCHE] TO [Metodo98]
    AS [dbo];

