CREATE TABLE [dbo].[FEPA_RIGHEIMPORTAZIONE] (
    [RIFPROGRESSIVO] DECIMAL (10)    NOT NULL,
    [NUMLINEA]       INT             NOT NULL,
    [METIDRIGADOC]   INT             DEFAULT ((0)) NULL,
    [TIPOCESSPR]     VARCHAR (2)     DEFAULT ('') NULL,
    [CODICETIPO]     VARCHAR (50)    DEFAULT ('') NULL,
    [CODICEVALORE]   VARCHAR (50)    DEFAULT ('') NULL,
    [DESCRIZIONE]    VARCHAR (1000)  DEFAULT ('') NULL,
    [QUANTITA]       DECIMAL (16, 6) DEFAULT ((0)) NULL,
    [UM]             VARCHAR (10)    DEFAULT ('') NULL,
    [PREZZOUNITARIO] DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [ALIQUOTAIVA]    DECIMAL (5)     DEFAULT ((0)) NULL,
    [NATURAESENZIVA] VARCHAR (2)     DEFAULT ('') NULL,
    [TIPOSCMAGG]     VARCHAR (100)   DEFAULT ('') NULL,
    [PERCSCMAGG]     VARCHAR (100)   DEFAULT ('') NULL,
    [IMPSCMAGG]      DECIMAL (19, 6) DEFAULT ((0)) NULL,
    [STATO]          SMALLINT        DEFAULT ((0)) NULL,
    [UTENTEMODIFICA] VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [NUMLINEA] ASC),
    CONSTRAINT [FK_FEPA_TESTEIMPORTAZIONE_FEPA_RIGHEIMPORTAZIONE] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[FEPA_TESTEIMPORTAZIONE] ([PROGRESSIVO]) ON DELETE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[FEPA_RIGHEIMPORTAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FEPA_RIGHEIMPORTAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FEPA_RIGHEIMPORTAZIONE] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FEPA_RIGHEIMPORTAZIONE] TO [Metodo98]
    AS [dbo];

