CREATE TABLE [dbo].[FETS_CODIFICHEESENZIVA] (
    [TIPOCICLO]      SMALLINT     NOT NULL,
    [CODICEMET]      VARCHAR (3)  NOT NULL,
    [CODICEB2B]      VARCHAR (10) DEFAULT ('') NOT NULL,
    [CODICEFEPA]     VARCHAR (10) DEFAULT ('') NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_FETS_FETS_CODIFICHEESENZIVA] PRIMARY KEY CLUSTERED ([TIPOCICLO] ASC, [CODICEMET] ASC, [CODICEB2B] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[FETS_CODIFICHEESENZIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FETS_CODIFICHEESENZIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FETS_CODIFICHEESENZIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FETS_CODIFICHEESENZIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FETS_CODIFICHEESENZIVA] TO [Metodo98]
    AS [dbo];

