CREATE TABLE [dbo].[FETS_CARATTDOCUMENTI_B2B] (
    [CODICE]         VARCHAR (10) NOT NULL,
    [DESCRIZIONE]    VARCHAR (50) NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([CODICE] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[FETS_CARATTDOCUMENTI_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FETS_CARATTDOCUMENTI_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FETS_CARATTDOCUMENTI_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FETS_CARATTDOCUMENTI_B2B] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FETS_CARATTDOCUMENTI_B2B] TO [Metodo98]
    AS [dbo];

