CREATE TABLE [dbo].[GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG] (
    [IDCONTRATTO]         VARCHAR (13) NOT NULL,
    [SEZIONECONTRATTO]    DECIMAL (5)  NOT NULL,
    [IDRAPPORTO]          VARCHAR (14) NOT NULL,
    [IdRigaMezzo]         DECIMAL (5)  NOT NULL,
    [idAttivita]          DECIMAL (5)  NOT NULL,
    [idRiga]              DECIMAL (5)  NOT NULL,
    [IDRAPPORTOAGGREGATO] VARCHAR (14) NULL,
    [DATA_EFF]            DATETIME     NULL,
    [STATO_FATTURAZIONE]  VARCHAR (14) DEFAULT ('N') NULL,
    [UTENTEMODIFICA]      VARCHAR (25) NOT NULL,
    [DATAMODIFICA]        DATETIME     NOT NULL,
    CONSTRAINT [GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG_PK] PRIMARY KEY CLUSTERED ([IDCONTRATTO] ASC, [SEZIONECONTRATTO] ASC, [IDRAPPORTO] ASC, [IdRigaMezzo] ASC, [idAttivita] ASC)
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GEM_SEZIONECONTRATTORAPPORTI_MEZZI_ATTIV_ESEG] TO [Metodo98]
    AS [dbo];

