CREATE TABLE [dbo].[GESTIONEPREZZITRASF] (
    [PROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [CODGRUPPOPREZZICF]  DECIMAL (5)     NULL,
    [CODCLIFOR]          VARCHAR (7)     NULL,
    [CODART]             VARCHAR (50)    NULL,
    [CODGRUPPOPREZZIMAG] DECIMAL (5)     NULL,
    [INIZIOVALIDITA]     DATETIME        NULL,
    [FINEVALIDITA]       DATETIME        NULL,
    [USANRLISTINO]       SMALLINT        DEFAULT (0) NULL,
    [TIPOARROT]          VARCHAR (1)     DEFAULT ('C') NULL,
    [ARROTALIRE]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [ARROTAEURO]         DECIMAL (19, 6) DEFAULT (0) NULL,
    [CODARTRIC]          VARCHAR (50)    NULL,
    [CODOPERAZIONE]      VARCHAR (5)     NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [CODICEPRIMARIO]     VARCHAR (50)    DEFAULT ('') NULL,
    [VARESPLICITE]       VARCHAR (255)   DEFAULT ('') NULL,
    [CODFEATURE]         INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_GESTIONEPREZZITRASF] PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOARROT_GESTIONETRAF] CHECK ([TIPOARROT] = 'N' or [TIPOARROT] = 'D' or [TIPOARROT] = 'E' or [TIPOARROT] = 'C'),
    CONSTRAINT [CKC_USANRLISTINO_GESTIONETR] CHECK ([USANRLISTINO] = 0 or [USANRLISTINO] = 1)
);


GO

/*  UPDATE TRIGGER "TU_GESTIONEPREZZITRASF" FOR TABLE "GESTIONEPREZZITRASF"  */
CREATE TRIGGER TU_GESTIONEPREZZITRASF ON GESTIONEPREZZITRASF FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  ALTER COLUMN PARENT CODE OF "GESTIONEPREZZITRASF" FOR ALL CHILDREN IN "GESTIONEPREZZIRIGHETRASF"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE GESTIONEPREZZIRIGHETRASF
          SET   RIFPROGRESSIVO = I1.PROGRESSIVO
         FROM   GESTIONEPREZZIRIGHETRASF T2, INSERTED I1, DELETED D1
         WHERE  T2.RIFPROGRESSIVO = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  DELETE TRIGGER "TD_GESTIONEPREZZITRASF" FOR TABLE "GESTIONEPREZZITRASF"  */
CREATE TRIGGER TD_GESTIONEPREZZITRASF ON GESTIONEPREZZITRASF FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "GESTIONEPREZZIRIGHETRASF"  */
    DELETE GESTIONEPREZZIRIGHETRASF
    FROM   GESTIONEPREZZIRIGHETRASF T2, DELETED T1
    WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[GESTIONEPREZZITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GESTIONEPREZZITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GESTIONEPREZZITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GESTIONEPREZZITRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GESTIONEPREZZITRASF] TO [Metodo98]
    AS [dbo];

