CREATE TABLE [dbo].[GESTIONEPREZZICTR] (
    [PROGRESSIVO]        DECIMAL (10)    NOT NULL,
    [PROGRESSIVOCTR]     DECIMAL (10)    NOT NULL,
    [CODGRUPPOPREZZICF]  DECIMAL (5)     NULL,
    [CODCLIFOR]          VARCHAR (7)     NULL,
    [CODART]             VARCHAR (50)    NULL,
    [CODGRUPPOPREZZIMAG] DECIMAL (5)     NULL,
    [INIZIOVALIDITA]     DATETIME        NULL,
    [FINEVALIDITA]       DATETIME        NULL,
    [USANRLISTINO]       SMALLINT        DEFAULT (0) NULL,
    [TIPOARROT]          VARCHAR (1)     DEFAULT ('C') NULL,
    [ARROTALIRE]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [ARROTAEURO]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [CODARTRIC]          VARCHAR (50)    NULL,
    [UTENTEMODIFICA]     VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]       DATETIME        NOT NULL,
    [CODICEPRIMARIO]     VARCHAR (50)    DEFAULT ('') NULL,
    [VARESPLICITE]       VARCHAR (255)   DEFAULT ('') NULL,
    [CODFEATURE]         INT             DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([PROGRESSIVO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_TIPOARROT_GESTIONECTR] CHECK ([TIPOARROT] = 'N' or [TIPOARROT] = 'D' or [TIPOARROT] = 'E' or [TIPOARROT] = 'C'),
    CONSTRAINT [CKC_USANRLISTINO_GESTIONECTR] CHECK ([USANRLISTINO] = 0 or [USANRLISTINO] = 1)
);


GO
CREATE NONCLUSTERED INDEX [GPRZ_ARTCATCF]
    ON [dbo].[GESTIONEPREZZICTR]([CODART] ASC, [CODGRUPPOPREZZICF] ASC, [CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CATCFGRART]
    ON [dbo].[GESTIONEPREZZICTR]([CODGRUPPOPREZZICF] ASC, [CODCLIFOR] ASC, [CODGRUPPOPREZZIMAG] ASC, [CODART] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CFGRART]
    ON [dbo].[GESTIONEPREZZICTR]([CODCLIFOR] ASC, [CODGRUPPOPREZZIMAG] ASC, [CODART] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODART]
    ON [dbo].[GESTIONEPREZZICTR]([CODART] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODCATEGORIACF]
    ON [dbo].[GESTIONEPREZZICTR]([CODGRUPPOPREZZICF] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODCLIFOR]
    ON [dbo].[GESTIONEPREZZICTR]([CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_CODGRUPPO]
    ON [dbo].[GESTIONEPREZZICTR]([CODGRUPPOPREZZIMAG] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_FINEVALIDITA]
    ON [dbo].[GESTIONEPREZZICTR]([FINEVALIDITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_GRARTCATCF]
    ON [dbo].[GESTIONEPREZZICTR]([CODGRUPPOPREZZIMAG] ASC, [CODART] ASC, [CODGRUPPOPREZZICF] ASC, [CODCLIFOR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_INIZIOVALIDITA]
    ON [dbo].[GESTIONEPREZZICTR]([INIZIOVALIDITA] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [GPRZ_PROGCTR]
    ON [dbo].[GESTIONEPREZZICTR]([PROGRESSIVOCTR] ASC) WITH (FILLFACTOR = 90);


GO

CREATE TRIGGER TD_GESTIONEPREZZICTR ON GESTIONEPREZZICTR FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  DELETE ALL CHILDREN IN "GESTIONEPREZZIRIGHE"  */
    DELETE GESTIONEPREZZIRIGHECTR
    FROM   GESTIONEPREZZIRIGHECTR T2, DELETED T1
    WHERE  T2.RIFPROGRESSIVO = T1.PROGRESSIVO

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

CREATE TRIGGER TU_GESTIONEPREZZICTR ON GESTIONEPREZZICTR FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  MODIFY PARENT CODE OF "GESTIONEPREZZI" FOR ALL CHILDREN IN "GESTIONEPREZZIRIGHE"  */
      IF UPDATE(PROGRESSIVO)
      BEGIN
         UPDATE GESTIONEPREZZIRIGHECTR
          SET   RIFPROGRESSIVO = I1.PROGRESSIVO
         FROM   GESTIONEPREZZIRIGHECTR T2, INSERTED I1, DELETED D1
         WHERE  T2.RIFPROGRESSIVO = D1.PROGRESSIVO
          AND  (I1.PROGRESSIVO != D1.PROGRESSIVO)
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[GESTIONEPREZZICTR] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GESTIONEPREZZICTR] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GESTIONEPREZZICTR] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GESTIONEPREZZICTR] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GESTIONEPREZZICTR] TO [Metodo98]
    AS [dbo];

