CREATE TABLE [dbo].[GESTIONEPREZZIRIGHETRASF] (
    [IDRIGA]            DECIMAL (10)    NOT NULL,
    [RIFPROGRESSIVO]    DECIMAL (10)    NOT NULL,
    [NRLISTINO]         DECIMAL (5)     NOT NULL,
    [UM]                VARCHAR (3)     NOT NULL,
    [QTAMINIMA]         DECIMAL (16, 6) DEFAULT (0) NOT NULL,
    [PREZZO_MAGG]       DECIMAL (19, 6) DEFAULT (0) NULL,
    [PREZZO_MAGGEURO]   DECIMAL (19, 6) DEFAULT (0) NULL,
    [SCONTO_UNICO]      VARCHAR (10)    NULL,
    [SCONTO_AGGIUNTIVO] VARCHAR (10)    NULL,
    [TIPO]              DECIMAL (5)     DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]    VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]      DATETIME        NOT NULL,
    CONSTRAINT [PK_GESTIONEPREZZIRIGHETRASF] PRIMARY KEY CLUSTERED ([IDRIGA] ASC) WITH (FILLFACTOR = 90)
);


GO

/*  INSERT TRIGGER "TI_GESTIONEPREZZIRIGHETRASF" FOR TABLE "GESTIONEPREZZIRIGHETRASF"  */
CREATE TRIGGER TI_GESTIONEPREZZIRIGHETRASF ON GESTIONEPREZZIRIGHETRASF FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "GESTIONEPREZZITRASF" MUST EXIST WHEN INSERTING A CHILD IN "GESTIONEPREZZIRIGHETRASF"  */
    IF UPDATE(RIFPROGRESSIVO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   GESTIONEPREZZITRASF T1, INSERTED T2
           WHERE  T1.PROGRESSIVO = T2.RIFPROGRESSIVO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "GESTIONEPREZZITRASF". Cannot create child in "GESTIONEPREZZIRIGHETRASF".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_GESTIONEPREZZIRIGHETRASF" FOR TABLE "GESTIONEPREZZIRIGHETRASF"  */
CREATE TRIGGER TU_GESTIONEPREZZIRIGHETRASF ON GESTIONEPREZZIRIGHETRASF FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "GESTIONEPREZZITRASF" MUST EXIST WHEN UPDATING A CHILD IN "GESTIONEPREZZIRIGHETRASF"  */
      IF UPDATE(RIFPROGRESSIVO)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   GESTIONEPREZZITRASF T1, INSERTED T2
             WHERE  T1.PROGRESSIVO = T2.RIFPROGRESSIVO) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"GESTIONEPREZZITRASF" does not exist. Cannot ALTER COLUMN child in "GESTIONEPREZZIRIGHETRASF".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHETRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHETRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHETRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHETRASF] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[GESTIONEPREZZIRIGHETRASF] TO [Metodo98]
    AS [dbo];

