CREATE TABLE [dbo].[IMPOSTAZIONIPRODLISTADOC] (
    [NOMEPIANIF]         VARCHAR (30) NOT NULL,
    [NRRIGA]             SMALLINT     NOT NULL,
    [TIPODOC]            VARCHAR (3)  NULL,
    [DAANNODOC]          SMALLINT     NULL,
    [DANUMERODOC]        INT          NULL,
    [DABIS]              CHAR (1)     NULL,
    [AANNODOC]           SMALLINT     NULL,
    [ANUMERODOC]         INT          NULL,
    [ABIS]               CHAR (1)     NULL,
    [FINODATACONS]       DATETIME     NULL,
    [RECUPERARITARDI]    SMALLINT     DEFAULT (0) NULL,
    [TIPODOCUMENTO]      SMALLINT     NULL,
    [IMPOSTAZIONEFILTRO] VARCHAR (50) NULL,
    [SQLFILTRO]          TEXT         NULL,
    [UTENTEMODIFICA]     VARCHAR (25) NOT NULL,
    [DATAMODIFICA]       DATETIME     NOT NULL,
    [ESCLUDIRIFCOMM]     SMALLINT     NULL,
    CONSTRAINT [PK_IMPOSTAZIONIPRODLISTADOC] PRIMARY KEY CLUSTERED ([NOMEPIANIF] ASC, [NRRIGA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CKC_RECUPERARITARDI_IMPOSTAZ] CHECK ([RECUPERARITARDI] = 0 or [RECUPERARITARDI] = 1)
);


GO

/*  INSERT TRIGGER "TI_IMPOSTAZIONIPRODLISTADOC" FOR TABLE "IMPOSTAZIONIPRODLISTADOC"  */
CREATE TRIGGER TI_IMPOSTAZIONIPRODLISTADOC ON IMPOSTAZIONIPRODLISTADOC FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    
    /*  PARENT "IMPOSTAZIONIPROGPROD" MUST EXIST WHEN INSERTING A CHILD IN "IMPOSTAZIONIPRODLISTADOC"  */
    IF UPDATE(NOMEPIANIF)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   IMPOSTAZIONIPROGPROD T1, INSERTED T2
           WHERE  T1.NOMEPIANIF = T2.NOMEPIANIF) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "IMPOSTAZIONIPROGPROD". Cannot create child in "IMPOSTAZIONIPRODLISTADOC".'
             GOTO ERROR
          END
    END

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO

/*  UPDATE TRIGGER "TU_IMPOSTAZIONIPRODLISTADOC" FOR TABLE "IMPOSTAZIONIPRODLISTADOC"  */
CREATE TRIGGER TU_IMPOSTAZIONIPRODLISTADOC ON IMPOSTAZIONIPRODLISTADOC FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)

      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN

      
      /*  PARENT "IMPOSTAZIONIPROGPROD" MUST EXIST WHEN UPDATING A CHILD IN "IMPOSTAZIONIPRODLISTADOC"  */
      IF UPDATE(NOMEPIANIF)
      BEGIN
         IF (SELECT COUNT(*)
             FROM   IMPOSTAZIONIPROGPROD T1, INSERTED T2
             WHERE  T1.NOMEPIANIF = T2.NOMEPIANIF) != @NUMROWS
            BEGIN
               SELECT @ERRNO  = 30003,
                      @ERRMSG = '"IMPOSTAZIONIPROGPROD" does not exist. Cannot modify child in "IMPOSTAZIONIPRODLISTADOC".'
               GOTO ERROR
            END
      END

      RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END

GO
GRANT DELETE
    ON OBJECT::[dbo].[IMPOSTAZIONIPRODLISTADOC] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[IMPOSTAZIONIPRODLISTADOC] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[IMPOSTAZIONIPRODLISTADOC] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[IMPOSTAZIONIPRODLISTADOC] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[IMPOSTAZIONIPRODLISTADOC] TO [Metodo98]
    AS [dbo];

