
CREATE FUNCTION [DBO].CALCOLARIPRESAVAL(@CODART VARCHAR(MAX), @ESERCIZIO AS SMALLINT)
RETURNS @TMPPRM TABLE
(
    CODART             VARCHAR(MAX),
    QTA1UM             DECIMAL(16, 6),
    QTA2UM             DECIMAL(16, 6),
    QTACARICO          DECIMAL(16, 6),
    VALORECARICO       DECIMAL(19, 6),
    VALORECARICOEURO   DECIMAL(19, 6),
    PREZZOMEDIO        DECIMAL(19, 6),
    PREZZOMEDIOEURO    DECIMAL(19, 6)
)
AS
BEGIN
    DECLARE @TMPVALORECARICOEURO DECIMAL(19, 6)

    INSERT INTO @TMPPRM(CODART,QTA1UM,QTA2UM,QTACARICO,VALORECARICO,VALORECARICOEURO,PREZZOMEDIO,PREZZOMEDIOEURO)
    SELECT 
        CODART,
        SUM(QTACARICO-QTASCARICO),
        SUM(QTACARICO2UM-QTASCARICO2UM),
        SUM(QTACARICO), 
        SUM(VALORECARICO) AS VALORECARICO, 
        SUM(VALORECARICOEURO) AS VALORECARICOEURO,
        0,
        0
    FROM 
        VISTAGIACENZE 
    WHERE 
        CODART = @CODART AND 
        ESERCIZIO = @ESERCIZIO AND
        RIPVALGIAC0 = 0 
    GROUP BY 
        CODART

    SELECT @TMPVALORECARICOEURO = VALORECARICOEURO FROM @TMPPRM
    IF @TMPVALORECARICOEURO IS NULL
        BEGIN
        DELETE FROM @TMPPRM

        INSERT INTO @TMPPRM(CODART,QTA1UM,QTA2UM,QTACARICO,VALORECARICO,VALORECARICOEURO,PREZZOMEDIO,PREZZOMEDIOEURO)
        SELECT 
            CODART,
            0,
            0,
            0, 
            0, 
            0,
            IMPORTOTOTNETTO,
            IMPORTOTOTNETTOEURO
        FROM 
            VISTAGIACENZE 
        WHERE 
            CODART = @CODART AND 
            ESERCIZIO = @ESERCIZIO AND
            RIPVALGIAC0 = 1
        END
    ELSE
        BEGIN
        UPDATE @TMPPRM 
        SET PREZZOMEDIO=(CASE WHEN ISNULL(QTACARICO,0)<>0 THEN (VALORECARICO/QTACARICO) ELSE 0 END),
        PREZZOMEDIOEURO=(CASE WHEN ISNULL(QTACARICO,0)<>0 THEN (VALORECARICOEURO/QTACARICO) ELSE 0 END)
        END
    RETURN
END

GO
GRANT REFERENCES
    ON OBJECT::[dbo].[CALCOLARIPRESAVAL] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CALCOLARIPRESAVAL] TO [Metodo98]
    AS [dbo];

