

CREATE FUNCTION [dbo].[Fun_Vendors_Statistiche](@IdSessione DECIMAL(5,0),
                                                  @CodAgente nVARCHAR(7))
RETURNS TABLE 
AS
RETURN 
(
    
    SELECT 
        STMAG.CODART,
        STMAG.CODDEPOSITO,
        STMAG.CODCLIFOR,
        STMAG.ESERCIZIO,
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 1 THEN STMAG.QTA1UM ELSE 0 END) AS "M1",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 2 THEN STMAG.QTA1UM ELSE 0 END) AS "M2",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 3 THEN STMAG.QTA1UM ELSE 0 END) AS "M3",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 4 THEN STMAG.QTA1UM ELSE 0 END) AS "M4",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 5 THEN STMAG.QTA1UM ELSE 0 END) AS "M5",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 6 THEN STMAG.QTA1UM ELSE 0 END) AS "M6",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 7 THEN STMAG.QTA1UM ELSE 0 END) AS "M7",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 8 THEN STMAG.QTA1UM ELSE 0 END) AS "M8",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 9 THEN STMAG.QTA1UM ELSE 0 END) AS "M9",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 10 THEN STMAG.QTA1UM ELSE 0 END) AS "M10",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 11 THEN STMAG.QTA1UM ELSE 0 END) AS "M11",
        SUM(CASE WHEN MONTH(STMAG.DATAMOV)= 12 THEN STMAG.QTA1UM ELSE 0 END) AS "M12"
    FROM 
        STORICOMAG STMAG
    WHERE 
        STMAG.CODART IN(SELECT DISTINCT CODICE FROM Tp_ElencoVariazioni WHERE MODCHIAVE = @IdSessione) AND
        STMAG.CODCLIFOR IN(SELECT DISTINCT CODCONTO FROM TP_CLIENTIEXPORT WHERE MODCHIAVE = @IdSessione) AND
        (
                (STMAG.TIPODOC IN (select ReturnedValue From dbo.SplitFieldIntoRows((SELECT DOCUMENTI_RG1 FROM TP_DOCSTATAG WHERE CODAGENTE = @CodAgente),1,1,','))) 
            OR  (STMAG.TIPODOC IN (select ReturnedValue From dbo.SplitFieldIntoRows((SELECT DOCUMENTI_RG2 FROM TP_DOCSTATAG WHERE CODAGENTE = @CodAgente),1,1,',')))
            OR  (STMAG.TIPODOC IN (select ReturnedValue From dbo.SplitFieldIntoRows((SELECT DOCUMENTI_RG3 FROM TP_DOCSTATAG WHERE CODAGENTE = @CodAgente),1,1,',')))
        ) AND 
        (
                (STMAG.CODCAUSALE IN (select ISNULL(NULLIF(ReturnedValue,''),0) From dbo.SplitFieldIntoRows((SELECT CAUSALI_RG1 FROM TP_DOCSTATAG WHERE CODAGENTE = @CodAgente),1,1,','))) 
            OR  (STMAG.CODCAUSALE IN (select ISNULL(NULLIF(ReturnedValue,''),0) From dbo.SplitFieldIntoRows((SELECT CAUSALI_RG2 FROM TP_DOCSTATAG WHERE CODAGENTE = @CodAgente),1,1,',')))
            OR  (STMAG.CODCAUSALE IN (select ISNULL(NULLIF(ReturnedValue,''),0) From dbo.SplitFieldIntoRows((SELECT CAUSALI_RG3 FROM TP_DOCSTATAG WHERE CODAGENTE = @CodAgente),1,1,',')))
        ) AND
        STMAG.DATAMOV >= (SELECT ULTPREPAR FROM TP_TRASFAGENTI WHERE CODAGENTE = @CodAgente) 
    GROUP BY 
        STMAG.CODART,
        STMAG.CODDEPOSITO,
        STMAG.CODCLIFOR,
        STMAG.ESERCIZIO
)


GO
GRANT SELECT
    ON OBJECT::[dbo].[Fun_Vendors_Statistiche] TO [Metodo98]
    AS [dbo];

