

CREATE FUNCTION [dbo].[FUNBOLLANDNEGOZIO](@PROGRESSIVORP DECIMAL(10,0))
RETURNS NVARCHAR(25)
AS
BEGIN

DECLARE @BOLLADDNEGOZIO VARCHAR(25)
    
    
    --SELECT @BOLLADDNEGOZIO = ISNULL(CODESTERNO,'') FROM EXTRACLIENTI WHERE CODCONTO = (SELECT CODCLIFOR FROM TESTEDOCUMENTI WHERE PROGRESSIVO=@PROGRESSIVORP)
    SELECT @BOLLADDNEGOZIO = ISNULL(CODDEST_EDI,'') FROM ANAGRAFICACF WHERE CODCONTO = (SELECT CODCLIFOR FROM TESTEDOCUMENTI WHERE PROGRESSIVO=@PROGRESSIVORP)

    RETURN(@BOLLADDNEGOZIO)
END



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[FUNBOLLANDNEGOZIO] TO [Metodo98]
    AS [dbo];

