
/****** Oggetto: funzione definita dall'utente dbo.FunGIACENZAART    Data dello script: 22/04/2005 10.39.49 ******/
CREATE FUNCTION FunGIACENZATOTART(@ARTICOLO nVARCHAR(50), 
				   @DEPOSITO nVARCHAR(10))
RETURNS @Results TABLE (PROGRESSIVO numeric(10, 0) IDENTITY (1, 1),
			CODART nVARCHAR(50) COLLATE database_default,
			CODUBICAZIONE nVARCHAR(10) COLLATE database_default,
			NRIFPARTITA nVARCHAR(15) COLLATE database_default,
			ESERCIZIO INT,
			ORDINATO decimal(19,4),
			IMPEGNATO decimal(19,4),
			ORDINATO2UM decimal(19,4),
			IMPEGNATO2UM decimal(19,4),
			CARICO decimal(19,4),
			CARICO2UM decimal(19,4),
			SCARICO decimal(19,4),
			SCARICO2UM decimal(19,4),
			RESODACARICO decimal(19,4),
			RESODACARICO2UM decimal(19,4),
			RESODASCARICO decimal(19,4),
			RESODASCARICO2UM decimal(19,4)
)
AS

    BEGIN

DECLARE @CODART nVARCHAR(50)
DECLARE @CODUBICAZIONE nVARCHAR(10)
DECLARE @NRIFPARTITA nVARCHAR(15)
DECLARE @ESERCIZIO INT
DECLARE @ORDINATO decimal(19,4)
DECLARE @IMPEGNATO decimal(19,4)
DECLARE @ORDINATO2UM decimal(19,4)
DECLARE @IMPEGNATO2UM decimal(19,4)
DECLARE @CARICO decimal(19,4)
DECLARE @CARICO2UM decimal(19,4)
DECLARE @SCARICO decimal(19,4)
DECLARE @SCARICO2UM decimal(19,4)
DECLARE @RESODACARICO decimal(19,4)
DECLARE @RESODACARICO2UM decimal(19,4)
DECLARE @RESODASCARICO decimal(19,4)
DECLARE @RESODASCARICO2UM decimal(19,4)

	DECLARE Articoli_Cursor CURSOR FOR
			SELECT 
				STMAG.CODART,
				STMAG.CODUBICAZIONE,
				STMAG.NRIFPARTITA,
				STMAG.ESERCIZIO,
				SUM(STMAG.QTA1UM*STMAG.ORDINATO) AS ORDINATO,
				SUM(STMAG.QTA1UM*STMAG.IMPEGNATO) AS IMPEGNATO,
				SUM(STMAG.QTA2UM*STMAG.ORDINATO2UM) AS ORDINATO2UM,
				SUM(STMAG.QTA2UM*STMAG.IMPEGNATO2UM) AS IMPEGNATO2UM,
				SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS CARICO,
				SUM(CASE WHEN STMAG.GIACENZA2UM=1 and STMAG.RESO = 0 THEN STMAG.QTA2UM ELSE 0 END) AS CARICO2UM,
				SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS SCARICO,
				SUM(CASE WHEN STMAG.GIACENZA2UM=-1 and STMAG.RESO = 0 THEN STMAG.QTA2UM ELSE 0 END) AS SCARICO2UM,
				SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODACARICO,
				SUM(CASE WHEN STMAG.GIACENZA2UM=-1 and STMAG.RESO = 1 THEN STMAG.QTA2UM ELSE 0 END) AS RESODACARICO2UM,
				SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODASCARICO,
				SUM(CASE WHEN STMAG.GIACENZA2UM=1 and STMAG.RESO = 1 THEN STMAG.QTA2UM ELSE 0 END) AS RESODASCARICO2UM	
			FROM 
				STORICOMAG STMAG
			WHERE CODART=@ARTICOLO AND
			      CODDEPOSITO=@DEPOSITO
			GROUP BY 
				CODART,ESERCIZIO,NRIFPARTITA,CODUBICAZIONE
	OPEN Articoli_Cursor
	FETCH NEXT FROM Articoli_Cursor
 	    INTO  @CODART,@CODUBICAZIONE,@NRIFPARTITA,@ESERCIZIO,@ORDINATO,@IMPEGNATO,
 		  @ORDINATO2UM,@IMPEGNATO2UM,@CARICO,@CARICO2UM,@SCARICO,
		  @SCARICO2UM,@RESODACARICO,@RESODACARICO2UM,@RESODASCARICO,
		  @RESODASCARICO2UM

	WHILE @@FETCH_STATUS = 0
		BEGIN

		    INSERT INTO @Results VALUES(@CODART,@CODUBICAZIONE,@NRIFPARTITA,@ESERCIZIO,@ORDINATO,@IMPEGNATO,
						@ORDINATO2UM,@IMPEGNATO2UM,@CARICO,@CARICO2UM,@SCARICO,
						@SCARICO2UM,@RESODACARICO,@RESODACARICO2UM,@RESODASCARICO,
						@RESODASCARICO2UM)
		    
		    FETCH NEXT FROM Articoli_Cursor
			INTO  @CODART,@CODUBICAZIONE,@NRIFPARTITA,@ESERCIZIO,@ORDINATO,@IMPEGNATO,
  	 		      @ORDINATO2UM,@IMPEGNATO2UM,@CARICO,@CARICO2UM,@SCARICO,
			      @SCARICO2UM,@RESODACARICO,@RESODACARICO2UM,@RESODASCARICO,
			      @RESODASCARICO2UM
		END
	
	CLOSE Articoli_Cursor
	DEALLOCATE Articoli_Cursor
    
    RETURN
END


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FunGIACENZATOTART] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FunGIACENZATOTART] TO [Metodo98]
    AS [dbo];

