
CREATE FUNCTION FunGIACLOG(@ARTICOLO nVARCHAR(50),@DEPOSITO nVARCHAR(10),@NRIFPARTITA nVARCHAR(15))
	
             RETURNS @Results TABLE (CODUBICAZIONE nVARCHAR(24) ,
				        TIPOUBICAZIONE  smallint,
                                                             GIAC                        DECIMAL(19,6) )
AS

BEGIN

DECLARE @CODUBICAZIONE nVARCHAR(24)
DECLARE @TIPOUBICAZIONE Smallint
DECLARE @GIAC DECIMAL(19,6)



	DECLARE Articoli_Cursor CURSOR fast_forward read_only  FOR
	
	SELECT TAB.CODUBICAZIONE,TAB.TIPOUBICAZIONE,SUM(TAB.GIAC)  FROM
             (SELECT
                           (CASE WHEN STORICOMAG.CODUBICAZIONE IS NULL THEN '' ELSE STORICOMAG.CODUBICAZIONE END )  AS CODUBICAZIONE ,
	   	(CASE WHEN STORICOMAG.NRIFPARTITA IS NULL THEN '' ELSE STORICOMAG.NRIFPARTITA END )  AS NRIFPARTITA ,
                           TABUBICAZIONIDEPOSITI.TIPOUBICAZIONE AS TIPOUBICAZIONE,
	   	(SUM(CASE WHEN GIACENZA=1 and RESO = 0 THEN QTA1UM ELSE 0 END)+
	    	 SUM(CASE WHEN GIACENZA=1 and RESO = 1 THEN QTA1UM ELSE 0 END)-
	   	 SUM(CASE WHEN GIACENZA=-1 and RESO = 0 THEN QTA1UM ELSE 0 END)-
		 SUM(CASE WHEN GIACENZA=-1 and RESO = 1 THEN QTA1UM ELSE 0 END)) AS GIAC 
	FROM STORICOMAG LEFT JOIN 
                        TABUBICAZIONIDEPOSITI ON  STORICOMAG.CODDEPOSITO=TABUBICAZIONIDEPOSITI.CODDEPOSITO AND STORICOMAG.CODUBICAZIONE= TABUBICAZIONIDEPOSITI.CODUBICAZIONE
	WHERE STORICOMAG.CODART=@ARTICOLO  AND STORICOMAG.CODDEPOSITO=@DEPOSITO
	GROUP BY STORICOMAG.NRIFPARTITA,STORICOMAG.CODUBICAZIONE,TABUBICAZIONIDEPOSITI.TIPOUBICAZIONE
             ) AS TAB 
             WHERE  TAB.NRIFPARTITA=@NRIFPARTITA
             GROUP BY TAB.CODUBICAZIONE,TAB.TIPOUBICAZIONE
             ORDER BY TAB.TIPOUBICAZIONE Desc , TAB.CODUBICAZIONE
	

             OPEN Articoli_Cursor
		
	FETCH NEXT FROM Articoli_Cursor
 	    INTO @CODUBICAZIONE,@TIPOUBICAZIONE,@GIAC

	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @GIAC > 0
            
                                             BEGIN                                        
                                                    INSERT INTO @Results VALUES(@CODUBICAZIONE,@TIPOUBICAZIONE,@GIAC)
                                             END 
			
                                        FETCH NEXT FROM Articoli_Cursor
			     INTO @CODUBICAZIONE,@TIPOUBICAZIONE,@GIAC
		END
	
	CLOSE Articoli_Cursor
	DEALLOCATE Articoli_Cursor
	
RETURN
END

GO
GRANT SELECT
    ON OBJECT::[dbo].[FunGIACLOG] TO [Metodo98]
    AS [dbo];

