

CREATE FUNCTION [dbo].[FunLISTAARTICOLITABLET]
(
   @CodAgente varchar(7) = ''
)
RETURNS TABLE AS RETURN
(
    SELECT DISTINCT
        AA.CODICE
    FROM
        ANAGRAFICAARTICOLI AA
    INNER JOIN
        TP_ExtraMag TEM
    ON
        TEM.CodArt = AA.CODICE
    LEFT OUTER JOIN
        TP_CONFIGESPORTAZ TCE
    ON
        ISNULL(TCE.GRUPPO,0) = ISNULL(AA.GRUPPO,0) OR
        ISNULL(TCE.CATEGORIA,0) = ISNULL(AA.CATEGORIA,0) OR
        ISNULL(TCE.CATEGORIASTATISTICA,0) = ISNULL(AA.CODCATEGORIASTAT,0) OR
        ISNULL(TCE.ARTICOLICONTIPOLOGIA,'') = ISNULL(AA.CODICE,'') OR
        ((ISNULL(TCE.FAMIGLIAPOS,0) = ISNULL(TEM.CodFamigliaPOS,0) AND
        ISNULL(TCE.REPARTOPOS,0) = ISNULL(TEM.CodRepartoPOS,0))) 
    WHERE TCE.CODICE = @CodAgente AND TCE.TIPO = 'A' AND (TEM.Esportabile=0 OR TEM.Esportabile IS NULL)
)


GO
GRANT SELECT
    ON OBJECT::[dbo].[FunLISTAARTICOLITABLET] TO [Metodo98]
    AS [dbo];

