
CREATE FUNCTION [dbo].[FunORDINATO_DEPOSITO_ARTICOLO](@ARTICOLO nVARCHAR(50),
													   @ESERCIZIO INT,
														@MAGAZZINO nVARCHAR(10))
RETURNS NUMERIC(19,6)
AS
BEGIN   

DECLARE @ORDINATOINIZIALE	AS NUMERIC(19,6)
DECLARE @ORDINATOATTUALE	AS NUMERIC(19,6)
DECLARE @ORDINATO			AS NUMERIC(19,6)
	
	SET @ORDINATO = 0

	SELECT 
		@ORDINATOINIZIALE = ISNULL(SUM(ORDINATOINIZIALE),0)
	FROM
	(
		SELECT 
			ORDINATO AS ORDINATOINIZIALE
		FROM
		(
			SELECT
				STMAG.CODART,STMAG.CODDEPOSITO,STMAG.ESERCIZIO,
				SUM(STMAG.QTA1UM*STMAG.ORDINATO) AS ORDINATO,
				AUM.UM
			FROM STORICOMAG AS STMAG 
			INNER JOIN TABVINCOLIGIC AS TVG ON STMAG.ESERCIZIO=TVG.ESERCIZIO
			INNER JOIN ANAGRAFICAARTICOLI ART ON ART.CODICE=STMAG.CODART
			INNER JOIN ARTICOLIUMPREFERITE AUM ON AUM.CODART=STMAG.CODART AND AUM.TIPOUM=1
			WHERE 	
					STMAG.CODART = @ARTICOLO AND 
					STMAG.CODDEPOSITO = @MAGAZZINO AND 
					STMAG.DataMov < (SELECT DATAINIMAG FROM TABESERCIZI WHERE CODICE = @Esercizio)
			GROUP BY 
					STMAG.CODART,
					STMAG.CODDEPOSITO,
					STMAG.ESERCIZIO,
					AUM.UM
			HAVING 	
					SUM(STMAG.QTA1UM*STMAG.ORDINATO) <>0 OR 
					SUM(STMAG.QTA1UM*STMAG.IMPEGNATO) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 
		) ORDINATOINIZIALEMETODO
	) ORDINATOINIZIALE 
	
	
	SELECT 
		@ORDINATO = ISNULL(SUM(ORDINATOATTUALE),0)
	FROM
	(
		SELECT	ORDINATO AS ORDINATOATTUALE
		FROM
		(
			SELECT 	
					STMAG.CODART,STMAG.CODDEPOSITO,STMAG.ESERCIZIO,
					SUM(STMAG.QTA1UM*STMAG.ORDINATO) AS ORDINATO,
					AUM.UM
			FROM STORICOMAG AS STMAG 
			INNER JOIN TABVINCOLIGIC AS TVG ON STMAG.ESERCIZIO=TVG.ESERCIZIO
			INNER JOIN ANAGRAFICAARTICOLI ART ON ART.CODICE=STMAG.CODART
			INNER JOIN ARTICOLIUMPREFERITE AUM ON AUM.CODART=STMAG.CODART AND AUM.TIPOUM=1
			WHERE 
					STMAG.CODART = @ARTICOLO AND 
					STMAG.CODDEPOSITO = @MAGAZZINO AND 
					STMAG.ESERCIZIO = @ESERCIZIO
			GROUP BY 
					STMAG.CODART,
					STMAG.CODDEPOSITO,
					STMAG.ESERCIZIO,
					AUM.UM
			HAVING 	
					SUM(STMAG.QTA1UM*STMAG.ORDINATO) <>0 OR 
					SUM(STMAG.QTA1UM*STMAG.IMPEGNATO) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 OR 
					SUM(CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) <>0 
		) ORDINATOATTUALEMETODO
	) ORDINATOATTUALE

	SET @ORDINATO = @ORDINATOINIZIALE + @ORDINATOATTUALE


RETURN(@ORDINATO)
END


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[FunORDINATO_DEPOSITO_ARTICOLO] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FunORDINATO_DEPOSITO_ARTICOLO] TO [Metodo98]
    AS [dbo];

