
/****** Oggetto: funzione definita dall'utente dbo.FunSCORTAMINIMA    Data dello script: 13/07/2005 15.24.44 ******/
CREATE FUNCTION [dbo].[FunSCORTAMINIMA](@ARTICOLO nVARCHAR(50),
										 @ESERCIZIO INT,
										  @MAGAZZINO nVARCHAR(10))
RETURNS NUMERIC(19,6)
AS
BEGIN   
--Var X Funzione
DECLARE @PROGRESSIVO DECIMAL(5,0)
DECLARE @COUNT INT
DECLARE @TIPORIGA nCHAR(2)
	SELECT @PROGRESSIVO=TP_TABMAGAZZINI.PROGRESSIVO
	FROM 	TP_TABMAGAZZINI
	WHERE TP_TABMAGAZZINI.CODDEPOSITO = @MAGAZZINO
	ORDER BY TP_TABMAGAZZINI.PROGRESSIVO
--*****************************Cerco relative configurazioni sulle righe*************************************
	SET @TIPORIGA = ''			
	SELECT  @TIPORIGA =
		(CASE WHEN COUNT_ARTICOLO > 0
		      THEN 'AR'
		      ELSE (CASE WHEN COUNT_GRUPPO > 0
			    THEN 'GR'
		            ELSE (CASE WHEN COUNT_CATEGORIA >0
				  THEN 'CT'
				  ELSE (CASE WHEN COUNT_CATEGORIAST > 0
					THEN 'CS'
					ELSE (CASE WHEN COUNT_GRUPPOPREZZI > 0
						   THEN 'GP'
						   ELSE (CASE WHEN COUNT_FAMIGLIAREPARTO > 0
							      THEN 'FR'
							      ELSE ''
							 END)
					      END)
				        END)
				  END)
			    END)
		END) 
	FROM
	(SELECT COUNT(*) AS COUNT_ARTICOLO FROM TP_CONFIGMULTIDEP_6ART WHERE 
		IdTesta = (@PROGRESSIVO) AND 
		Codice IN(SELECT items FROM SplitARTICOLO(@ARTICOLO,'?'))) ARTICOLO,
	(SELECT COUNT(*) AS COUNT_GRUPPO FROM TP_CONFIGMULTIDEP_1GRP WHERE 
		IdTesta= (@PROGRESSIVO)) GRUPPO,
	(SELECT COUNT(*) AS COUNT_CATEGORIA FROM TP_CONFIGMULTIDEP_2CAT WHERE 
		IdTesta = (@PROGRESSIVO)) CATEGORIA,
	(SELECT COUNT(*) AS COUNT_CATEGORIAST FROM TP_CONFIGMULTIDEP_3CATST WHERE 
		IdTesta = (@PROGRESSIVO)) CATEGORIAST,
	(SELECT COUNT(*)AS COUNT_GRUPPOPREZZI FROM TP_CONFIGMULTIDEP_4GRPPRZ WHERE 
		IdTesta = (@PROGRESSIVO)) GRUPPOPREZZI,
	(SELECT COUNT(*) AS COUNT_FAMIGLIAREPARTO FROM TP_CONFIGMULTIDEP_5FAMREP WHERE 
		IdTesta = (@PROGRESSIVO)) FAMIGLIAREPARTO
			
--*****************************FINE Cerco relative configurazioni sulle righe********************************			
--*****************************Cerco i valori di ScortaMin E Lotto Riord.********************************			
DECLARE @TMP_SCORTAMIN NUMERIC(16,6)
DECLARE @CODRIGA1 DECIMAL(5,0)
DECLARE @CODRIGA2 DECIMAL(5,0)
		
		SET @TMP_SCORTAMIN = NULL
		--Cerco Per Articolo
		IF (@TIPORIGA = 'AR')
			BEGIN
				SELECT @TMP_SCORTAMIN=ScortaMin
				FROM TP_CONFIGMULTIDEP_6ART	
				WHERE IdTesta=@PROGRESSIVO AND Codice IN(SELECT items FROM SplitARTICOLO(@ARTICOLO,'?'))
			END
		--Cerco Per Gruppo
		IF (@TIPORIGA = 'GR')
			BEGIN
						
				SELECT @TMP_SCORTAMIN=ScortaMin
				FROM TP_CONFIGMULTIDEP_1GRP 
				WHERE IdTesta=@PROGRESSIVO AND Codice=(SELECT GRUPPO 
										  FROM ANAGRAFICAARTICOLI
										  WHERE CODICE=@ARTICOLO)
			END
		--Cerco Per Categoria
		IF (@TIPORIGA = 'CT')
			BEGIN
				SELECT @TMP_SCORTAMIN=ScortaMin
				FROM TP_CONFIGMULTIDEP_2CAT 
				WHERE IdTesta=@PROGRESSIVO AND Codice=(SELECT CATEGORIA 
										FROM ANAGRAFICAARTICOLI 
										WHERE CODICE=@ARTICOLO)
			END
		--Cerco Per Categoria STATISTICA
		IF (@TIPORIGA = 'CS')
			BEGIN		
				SELECT @TMP_SCORTAMIN=ScortaMin
				FROM TP_CONFIGMULTIDEP_3CATST 
				WHERE IdTesta=@PROGRESSIVO AND Codice=(SELECT CODCATEGORIASTAT 
										FROM ANAGRAFICAARTICOLI 
										WHERE CODICE=@ARTICOLO)
			END
		--Cerco Per Famiglia Reparto
		IF (@TIPORIGA = 'GP')
			BEGIN		
				SELECT @TMP_SCORTAMIN=ScortaMin
				FROM TP_CONFIGMULTIDEP_4GRPPRZ  
				WHERE IdTesta=@PROGRESSIVO AND Codice=(SELECT GRUPPOPRZPART
										FROM ANAGRAFICAARTICOLICOMM
										WHERE  ESERCIZIO=@ESERCIZIO AND CODICEART=@ARTICOLO)
			END
		--Cerco Per Gruppo Prezzi
		IF (@TIPORIGA = 'FR')
			BEGIN
				SELECT @CODRIGA1=CODFAMIGLIAPOS,@CODRIGA2=CODREPARTOPOS
				FROM TP_EXTRAMAG
				WHERE CODART=@ARTICOLO
		
				SELECT @TMP_SCORTAMIN=ScortaMin
				FROM TP_CONFIGMULTIDEP_5FAMREP
				WHERE IdTesta=@PROGRESSIVO AND CodFam=@CODRIGA1 AND (CodRep=0 OR CodRep=@CODRIGA2)
			END
--***************************FINE Cerco i valori di ScortaMin E Lotto Riord.*****************************
		IF  (@TMP_SCORTAMIN IS NULL)
			BEGIN
				SET @TMP_SCORTAMIN = 0
			END
--*************************FINE Verifico Giacenze e le Inserisco nella Tabella TMP**************************
RETURN(@TMP_SCORTAMIN)
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[FunSCORTAMINIMA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FunSCORTAMINIMA] TO [Metodo98]
    AS [dbo];

