
/****** Oggetto: funzione definita dall'utente dbo.FunUltPrz    Data dello script: 22/04/2005 10.39.49 ******/


CREATE FUNCTION FunUltPrz()
	RETURNS @Results TABLE (Progressivo numeric(10, 0) IDENTITY (1, 1),
				CODART NVARCHAR(50)  COLLATE SQL_Latin1_General_CP850_CI_AS,
				CODCLIFOR NVARCHAR(7)  COLLATE SQL_Latin1_General_CP850_CI_AS,
				DATADOC DateTime,
				ESERCIZIO decimal(5,0),
				TIPODOC NVARCHAR(3)  COLLATE SQL_Latin1_General_CP850_CI_AS,
				NUMERODOC decimal(10,0),
				PREZZOUNITNETTOVALUTA decimal(19,4),
				QTAGEST decimal(19,6),
				DESCCAMP NVARCHAR(50)  COLLATE SQL_Latin1_General_CP850_CI_AS,
				DESCPROMO NVARCHAR(50) COLLATE SQL_Latin1_General_CP850_CI_AS)
AS

    BEGIN
	DECLARE @CODART NVARCHAR(50)
	
	DECLARE Articoli_Cursor CURSOR FOR
			SELECT DISTINCT 
				VISTADOCUMENTIBASE.CODART
			FROM VISTADOCUMENTIBASE  
			INNER JOIN TP_ASSOCIAZIONI_DOC 
				ON VISTADOCUMENTIBASE.TIPODOC = TP_ASSOCIAZIONI_DOC.Cod_Doc AND 
				   TP_ASSOCIAZIONI_DOC.Tipo IN(1, 2, 3, 8, 10, 11, 12, 15, 16, 17, 18)
			LEFT OUTER JOIN  TP_EXTRARIGHEDOC ON TP_EXTRARIGHEDOC.IDTESTA = VISTADOCUMENTIBASE.IDTESTA AND
				   TP_EXTRARIGHEDOC.IDRiga = VISTADOCUMENTIBASE.PROGRIGADOC
			WHERE VISTADOCUMENTIBASE.TIPORIGA='N' 
	OPEN Articoli_Cursor
		
	FETCH NEXT FROM Articoli_Cursor 
		INTO @CODART

	WHILE @@FETCH_STATUS = 0
		BEGIN
		    INSERT INTO @Results 
			SELECT TOP 5 VISTADOCUMENTIBASE.CODART,
				      VISTADOCUMENTIBASE.CODCLIFOR,
				      VISTADOCUMENTIBASE.DATADOC,
				      VISTADOCUMENTIBASE.ESERCIZIO,
				      VISTADOCUMENTIBASE.TIPODOC,
				      VISTADOCUMENTIBASE.NUMERODOC,
				      VISTADOCUMENTIBASE.PREZZOUNITNETTOVALUTA,
				      VISTADOCUMENTIBASE.QTAGEST,
				      TP_EXTRARIGHEDOC.DescCampagna AS DescrizioneCampagna,
				      TP_EXTRARIGHEDOC.DescPromozione AS DescrizionePromozione
			 FROM VISTADOCUMENTIBASE 
	 			INNER JOIN TP_ASSOCIAZIONI_DOC 
					ON VISTADOCUMENTIBASE.TIPODOC = TP_ASSOCIAZIONI_DOC.Cod_Doc AND 
					   TP_ASSOCIAZIONI_DOC.Tipo IN(1, 2, 3, 8, 10, 11, 12, 15, 16, 17, 18)
				LEFT OUTER JOIN  TP_EXTRARIGHEDOC 
					ON TP_EXTRARIGHEDOC.IDTESTA = VISTADOCUMENTIBASE.IDTESTA AND
					   TP_EXTRARIGHEDOC.IDRiga = VISTADOCUMENTIBASE.PROGRIGADOC  
			 WHERE VISTADOCUMENTIBASE.CODART = @CODART AND VISTADOCUMENTIBASE.CODART<>'' 
				ORDER BY VISTADOCUMENTIBASE.DATADOC DESC

		    FETCH NEXT FROM Articoli_Cursor 
					INTO @CODART
		END

	CLOSE Articoli_Cursor

	DEALLOCATE Articoli_Cursor
    
    RETURN
END



GO
GRANT DELETE
    ON OBJECT::[dbo].[FunUltPrz] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FunUltPrz] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[FunUltPrz] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FunUltPrz] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FunUltPrz] TO [Metodo98]
    AS [dbo];

