CREATE FUNCTION LEGGICLIENTEINTESTATARIO
	(@IDTESTA int) RETURNS varchar(7)
AS
BEGIN
	DECLARE @CODCLIFOR AS varchar(7)
	
	DECLARE CUR_DOC CURSOR SCROLL SCROLL_LOCKS FOR	
	SELECT CODCLIFOR FROM TESTEDOCUMENTI WHERE PROGRESSIVO=@IDTESTA
	OPEN CUR_DOC
	FETCH NEXT FROM CUR_DOC INTO @CODCLIFOR
	IF @@FETCH_STATUS<>0 SELECT @CODCLIFOR = ''
 	CLOSE CUR_DOC
	DEALLOCATE CUR_DOC

	RETURN @CODCLIFOR
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[LEGGICLIENTEINTESTATARIO] TO [Metodo98]
    AS [dbo];

