CREATE TABLE [dbo].[UTENTICONFAZ] (
    [RIFPROGRESSIVO] DECIMAL (10) NOT NULL,
    [UTENTE]         VARCHAR (25) NOT NULL,
    [IMPPREDEFINITA] SMALLINT     NULL,
    [UTENTEMODIFICA] VARCHAR (25) NOT NULL,
    [DATAMODIFICA]   DATETIME     NOT NULL,
    CONSTRAINT [PK_UTENTICONFAZ] PRIMARY KEY CLUSTERED ([RIFPROGRESSIVO] ASC, [UTENTE] ASC),
    CONSTRAINT [FK_UTENTICONFAZ_RIFPROGRESSIVO] FOREIGN KEY ([RIFPROGRESSIVO]) REFERENCES [dbo].[TESTECONFAZ] ([PROGRESSIVO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
GRANT DELETE
    ON OBJECT::[dbo].[UTENTICONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[UTENTICONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[UTENTICONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[UTENTICONFAZ] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[UTENTICONFAZ] TO [Metodo98]
    AS [dbo];

