CREATE TABLE [dbo].[VENTILAZIONEIVA] (
    [NRTERMINALE]     DECIMAL (5)     NOT NULL,
    [TIPO]            SMALLINT        NOT NULL,
    [CODIVA]          DECIMAL (5)     NOT NULL,
    [ALIQUOTA]        DECIMAL (8, 5)  DEFAULT (0) NOT NULL,
    [IMPACQUISTI]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPACQUISTIEURO] DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [COEFF]           DECIMAL (8, 5)  DEFAULT (0) NOT NULL,
    [COEFFEURO]       DECIMAL (8, 5)  DEFAULT (0) NOT NULL,
    [IMPVENDITE]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPVENDITEEURO]  DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPONIBILE]      DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPONIBILEEURO]  DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPOSTA]         DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [IMPOSTAEURO]     DECIMAL (19, 4) DEFAULT (0) NOT NULL,
    [UTENTEMODIFICA]  VARCHAR (25)    NOT NULL,
    [DATAMODIFICA]    DATETIME        NOT NULL,
    CONSTRAINT [PK_VENTILAZIONEIVA] PRIMARY KEY CLUSTERED ([NRTERMINALE] ASC, [TIPO] ASC, [CODIVA] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [VENT_ALIQ]
    ON [dbo].[VENTILAZIONEIVA]([ALIQUOTA] ASC) WITH (FILLFACTOR = 90);


GO
GRANT DELETE
    ON OBJECT::[dbo].[VENTILAZIONEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[VENTILAZIONEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[VENTILAZIONEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VENTILAZIONEIVA] TO [Metodo98]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[VENTILAZIONEIVA] TO [Metodo98]
    AS [dbo];

